### ISSUE TITLE
SpongeForge vs Galacticraft

### ISSUE THREAD

**Issue by ToastyNikk** [SpongePowered/SpongeForge#1841] opened 2017-11-07 23:35 UTC
The server crashed due to a memory leak, but when we attempted to restart it, it kept crashing due to an issue where Galacticraft tried to load before sponge. Sponge obvs did not like that so it spanked it and crashed the server. This problem was fixed by disabling sponge and all the plugins and restarting the server and then stopping it properly. We re-enabled sponge and most plugins and it loaded up just fine.

**I am currently running...**
- SpongeForge version: spongeforge-1.11.2-2476-6.1.0-BETA-2715
- Forge version: 13.20.1.2510 for MC 1.11.2
- Java version: openjdk version "1.8.0_131"
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
 -Plugins:
   BuyCraftX for sponge
   CatClearLag-0.8
   HuskyCrates-v1.7.2
   HuskyUI-v0.2.1
   LuckPerms-Sponge-3.4.20
   Nucleus-1.1.4-LTS-S5.1-MC1.10.2-plugin
   griefprevention-1.11.2-4.1.1.487
   nuvotifier-universal-2.3.5 //The guy who runs this forgot to change this to serious-nuvotifier
   seriousvote-4.4
 -Mods:
   The website [list](https://minecraft.curseforge.com/projects/industrial-architecture/relations/dependencies)

Expected result is to not crash.

Current result is an occasional crash.

Here is the [pastebin](https://pastebin.com/SWUTAkqV)
And just in case you want it, I will attach the log file to [here](https://github.com/SpongePowered/SpongeForge/files/1452050/crash-2017-11-06_19.20.00-server.txt)

**Comment by phit** [comment] 2017-11-10 11:55
@ToastyNikk Can you please report this to Galacticraft, the dev has been pretty helpful and uses Sponge himself to test.

**Comment by phit** [comment] 2017-12-02 02:55
Sorry, log doesn't even mention Sponge and I couldn't reproduce this. I'm closing this for now, if you still experience this please open an issue with Galacticraft.

**Closed as completed by phit** 2017-12-02 02:55 UTC
Labels: version: 1.11 (u)
