### ISSUE TITLE
Crash after generating over 50k chunks succesfully and trying to restart

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1970] opened 2018-01-22 20:49 UTC
SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2790.jar
Java version: OpenJDK 64-Bit Server VM, version 1.8.0_151
Operating System:Linux
All plugins and mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, Aroma1997Core, IvToolkit, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, Nucleus Mixins, AdamantineShield, AdminShop, IndustrialCraft 2, Advanced Solar Panels, BD Lib, Advanced Generators, Applied Energistics 2, AE2 Stuff, Aroma1997Core|Helper, AromaBackup, AromaBackup Recovery, Psi, AutoRegLib, Base Metals, Baubles, Better Builder's Wands, Better Command Signs, BiblioCraft, Biomes O' Plenty, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Botania, Buycraft, Chisel, CodeChicken Lib, CodeChicken Core, CoFH Core, Compact Solar Arrays, CraftTweaker JEI Support, MineTweaker 3, Custom Starting Gear, Cyberware, PTRModelLib, Decocraft, Doomlike Dungeons, DTCommands, Eagle Factions, EnderStorage, EnderCore, Waila, Ender IO, Ender Zoo, Exp Seedling Mod, Extra Utilities 2, MCMultiPart, Mekanism, OpenComputers, Thermal Foundation, Thermal Expansion, Zero CORE, Extreme Reactors, Fast Leave Decay, Forestry, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, Gravestone Mod, GriefPrevention, GWMCrates, Hammer Core, iChunUtil, Hats, Infernal Mobs, Iron Chest, JourneyMap, Loot Bags, The Lost Cities, LuckPerms, Mantle, MekanismGenerators, MekanismTools, MMCRestrict, Ore Spawn, ModBanner, MrTJPCore, Modern Warfare, Nether Metals, No Downfall, Nucleus, PlaceholderAPI, Nucleus Gluon, NuVotifier, OMLib, Open Modular Passive Defense, Open Glider, Open Modular Turrets, Ore Shrubs, Pam's HarvestCraft, ProjectE, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, RebornCore, QuantumStorage, Railcraft, Rainbow Oak Trees, reborncore-MCMultiPart, Redstone Arsenal, SanAndreasPs Mod Library, SanAndreasPs Player Model, SecurityCraft, VotifierListener, Solar Flux Reborn, SpongyChest, Tinkers' Construct, Tinker I/O, Tinkers' Addons, Tinkers Tool Leveling, Total Economy, Tree Chopper, Turret Mod Rebirth, Vanish, Vein Miner, Mod Support, Vending, I Can See Everything, What Are We Looking At, WorldEdit

The lost cities mod has succesfully generated over 50k chunks and after restarting the server crashes
whenever anyone tries to join and the dev thinks that the crash is most likely being caused by sponge although he ain't sure as he didn't have the time to fully look into the crash yet.
[crash-2018-01-22_15.09.30-server.txt](https://github.com/SpongePowered/SpongeForge/files/1653546/crash-2018-01-22_15.09.30-server.txt)
And incase it helps this is what appears in the console when someone tries to join: https://pastebin.com/FtxkJTVn

**Comment by phit** [comment] 2018-01-22 20:56
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1815

**Closed as completed by phit** 2018-01-22 20:56 UTC
Labels: resolution: duplicate, resolution: invalid, version: 1.10 (u)

**Comment by ghost** [comment] 2018-01-22 21:02
It still exists on 1.10.2 even though the report it is a duplicate off is a few months old
