### ISSUE TITLE
Cyclic 3x3 inventory crafting disconnects player with FastWorkBench installed

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#2751] opened 2019-05-12 13:37 UTC
**I am currently running**

- SpongeForge version: 3705
- Forge version: 2831
- Java version:  201

- Mods (201): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, B.A.S.E, BD Lib, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Carry On, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, DragonMurder, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, Mekanism: Generators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PlaneFix, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XC Patch, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

**Issue Description**
A player eats the cyclicmagic:crafting_food. After that a "c" pops up in his inventory. if he presses C, he now sees a 3x3 crafting field in his inventory for a second, like a workbench. But right after, he gets disconnected:
https://pastebin.com/CDLRjSkm

**Comment by CaptainSisko** [comment] 2019-05-13 02:16
I have been experiencing this same issue using the ATM3: Remix modpack

Modlist: https://hastebin.com/novaxoveke.cs
Error message: https://hastebin.com/ezahahulaq.rb

I am also using spongeforge-1.12.2-2825-7.1.6-RC3705.

I have tested a client using only sponge and cyclic and have found that this issue does not occur so it is likely a combination of sponge, cyclic and another mod.

I haven't had a chance to troubleshoot further in an attempt to find the exact combination of mods that are causing this issue.

**Comment by CaptainSisko** [comment] 2019-05-14 07:46
This is actually a duplicate of this issue opened in November last year.
https://github.com/SpongePowered/SpongeForge/issues/2498

The modpack used in that issue is likely ATM3, i am experiencing this issue with ATM3: Remix but not with a client that has ONLY cyclic and sponge.

I should have some time tonight to do some further troubleshooting in order to find out which combination of mods from ATM3:Remix + Sponge is causing this issue.

**Comment by CaptainSisko** [comment] 2019-05-14 12:14
Alright after some further testing i have found the combination of mods that causes this issue.

I am using
Cyclic-1.12.2-1.18.5
FastWorkbench-1.12.2-1.7.1
spongeforge-1.12.2-2825-7.1.6-RC3708

Only these 3 in a client and it will disconnect the player when attempting to open the cyclic inventory crafting table.

**Comment by phit** [comment] 2019-05-14 12:17
you can remove fastworkbench from the server as a temporary solution

**Comment by Faithcaio** [comment] 2019-06-01 10:39
found it!
Without fastworkbench:
https://github.com/Lothrazar/Cyclic/blob/374be9e55f140a540d1c5c11b5a26dee722de216/src/main/java/com/lothrazar/cyclicmagic/playerupgrade/crafting/ContainerPlayerExtWorkbench.java
With fastworkbench:
https://github.com/Lothrazar/Cyclic/blob/c3d732c8cbf5fe3884ec64aeda3690c39591f5de/src/main/java/com/lothrazar/cyclicmagic/compat/fastbench/ContainerFastPlayerBench.java

So basicly ContainerFastPlayerBench is a ContainerWorkbench with additional slots which messes up our assumptions about the size of the Workbench.

But it looks like the slots are added at the end of the "normal" Workbench, so that fix should work just fine.

**Closed as completed by Faithcaio** 2019-06-01 10:39 UTC
Labels: type: mod incompatibility, system: inventory, version: 1.12
