### ISSUE TITLE
PlayerTickPhase CapturedBlocks

### ISSUE THREAD

**Issue by Magi1053** [SpongePowered/SpongeForge#1753] opened 2017-08-28 23:27 UTC
I have a mod pack with 200 some mods in it. I've been running the server fine for a while. I have just now updated all the mods in the pack, including forge and spongeforge. Now I am getting this error spamming my console as far as it can read.
```/* Minecraft : 1.10.2                                                                                               */                                                                                                                                                  [998/1960]
/* SpongeAPI : 5.2.0-SNAPSHOT-c675e80                                                                               */
/* SpongeForge : 1.10.2-2281-5.2.0-BETA-2597                                                                        */
/* Minecraft Forge : 12.18.3.2422                                                                                   */
/********************************************************************************************************************/
/********************************************************************************************************************/
/*                                           Exception during phase body                                            */
/********************************************************************************************************************/
/* Something happened trying to run the main body of a phase PlayerTickPhase                                        */
/* PhaseContext :                                                                                                   */
/*         - Name: Source                                                                                           */
/*           Object: EntityPlayerMP['Magi1053'/59755, l='world', x=946.95, y=95.00, z=281.14]                       */
/*         - Name: CapturedBlocks                                                                                   */
/*           Object: CapturedBlocksSupplier{Captured=0}                                                             */
/*         - Name: CapturedEntities                                                                                 */
/*           Object: CapturedEntitiesSupplier{Captured=0}                                                           */
/* Phases remaining :                                                                                               */
/*   - Phase: PlayerTickPhase                                                                                       */
/*     Context:                                                                                                     */
/*     - Name: Source                                                                                               */
/*       Object: EntityPlayerMP['Magi1053'/59755, l='world', x=946.95, y=95.00, z=281.14]                           */
/*     - Name: CapturedBlocks                                                                                       */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                 */
/*     - Name: CapturedEntities                                                                                     */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                               */
/* Stacktrace:                                                                                                      */
/* net.minecraft.util.ReportedException: Ticking player                                                             */
/*     net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380)                             */
/*     net.minecraft.network.NetHandlerPlayServer.lambda$onPlayerTick$0(NetHandlerPlayServer.java:1956)             */
/*     org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163)                    */
/*     net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zhf000(NetHandlerPlayServer.java:1955)      */
/*     net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)                       */
/*     net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) */
/*     net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)                                   */
/*     net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)                                    */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)                                  */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                        */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                                  */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                           */
/*     java.lang.Thread.run(Thread.java:748)                                                                        */
/* java.lang.NullPointerException: null                                                                             */
/*     net.minecraft.world.storage.MapData.func_76191_a(MapData.java:157)                                           */
/*     net.minecraft.item.ItemMap.func_77663_a(ItemMap.java:244)                                                    */
/*     net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:442)                                                */
/*     net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)                           */
/*     net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)                                 */
/*     net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)                              */
/*     net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)                                */
/*     net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)                             */
/*     net.minecraft.network.NetHandlerPlayServer.lambda$onPlayerTick$0(NetHandlerPlayServer.java:1956)             */
/*     org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163)                    */
/*     net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zhf000(NetHandlerPlayServer.java:1955)      */
/*     net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)                       */
/*     net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) */
/*     net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)                                   */
/*     net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)                                    */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)                                  */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                        */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                                  */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                           */
/*     java.lang.Thread.run(Thread.java:748)                                                                        */
/*                                                                                                                  */
/* Minecraft : 1.10.2                                                                                               */
/* SpongeAPI : 5.2.0-SNAPSHOT-c675e80                                                                               */
/* SpongeForge : 1.10.2-2281-5.2.0-BETA-2597                                                                        */
/* Minecraft Forge : 12.18.3.2422                                                                                   */
/********************************************************************************************************************/```

**Comment by phit** [comment] 2017-08-28 23:29
possibly related to #1456

**Comment by bloodmc** [comment] 2017-08-29 01:38
@Aaron1011 want to look into this?

**Comment by ktole1999** [comment] 2017-09-02 13:52
i saw this comment "Disable method tracker system until we can test it further.
bloodshot - 12 days ago"

was that to disable these messages or is this something different. Just not sure if this error is gamebreaking or not.

**Comment by Aaron1011** [comment] 2017-09-03 13:52
@ktole1999: The 'tracker' in that commit message actually refers to an entirely different system, which transforms mod classes that invoke certain methods. The error and stacktrace you're seeing are due to the 'Cause Tracker', which is responsible for detecting and attributing (to players or entities) changes made to the world.

**Comment by ktole1999** [comment] 2017-09-03 14:45
I am hoping there is a way to turn off that message to keep from spamming console or does that message mean I have an underlying issue?



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by phit** [comment] 2017-11-22 22:28
Closing this for now. If this is still an issue for you, please let us know and provide relevant new info e.g. which mods are required to reproduce this.

**Closed as completed by phit** 2017-11-22 22:28 UTC
Labels: version: 1.10 (u)
