### ISSUE TITLE
Chisel n Bits not working on certain blocks

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2369] opened 2018-08-06 19:30 UTC
**I am currently running**

- SpongeForge version: 3374
- Forge version: 2739
- Java version: 1.8 update 181
- Operating System: Windows Server 2012 R2

- Plugins/Mods: Mods (156): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Actually Additions, Advanced Generators, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Advancements, Better Builder's Wands, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Elevator Mod, EluCore, EluLib, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, FastWorkbench, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MeeCreeps, Mercurius, MineTogether, MineTogetherServer, Mod Tweaker, Morph, Morph-o-Tool, Morpheus, NetherPortalFix, Not Enough Wands, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, PneumaticCraft: Repressurized, PortalGun, Psi, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simple Inventory sorting, Simply Jetpacks 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Wireless Crafting Terminal 2, XNet, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library

---
After update SF: 3328 Chisel n Bits mod cannot Chisel certain blocks. These blocks include, Obsidian, Stone, Cobblestone and a few more.

You can reproduce this with Chisel n Bits version chiselsandbits-14.20 and Spongeforge 3375 - Then use version 3328 to see the issue gone.

If you need any more information, I can assist the best I can. Logs are not produced when reproducing the problem.

**Comment by ResqDiver1317** [comment] 2018-08-06 20:02
@Shybella, the version we know works referenced in our thread on the CandB Git is 3328, not 3288 :)

**Comment by ResqDiver1317** [comment] 2018-08-06 20:04
I as well can confirm this issue in our custom modpack. I update SpongeForge from 3328 to 3344 (I think) and began having this issue. I rolled back to 3328 and the problem went away. I'm not sure exactly what SpongeForge version the issue with Chisels and Bits begins occurring, but I do know it is somewhere after 3328.

**Comment by TeraNovell** [comment] 2018-08-24 20:47
I can also confirm that with version 3415.

**Comment by Shybella** [comment] 2018-08-27 14:01
Please, someone look into this.

**Comment by ResqDiver1317** [comment] 2018-08-27 14:18
I intended to test this when he released the potential fix but RL and issues on our other servers for in the way. I will update ours tonight and test it out

**Comment by liampearson96** [comment] 2018-08-30 21:29
I’m having the same problem. Was working and then broke after I updated to one of the latest beta builds. I’ve worked out that if the player is in creative it allows the player to chisel it, in single player it doesn’t. Also, it spams an error in the console “error executing task”. Please look into this.

**Comment by liampearson96** [comment] 2018-08-31 08:51
Also get this in the latest.log 


```[08:50:18] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_102]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_102]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3417]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3972) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.ClassCastException```

**Comment by ImMorpheus** [comment] 2018-09-01 15:19
@liampearson96 The stacktrace is missing the important part. Can you upload the complete error ?

**Comment by Shybella** [comment] 2018-09-01 15:22
@ImMorpheus 

```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: mod.chiselsandbits.chiseledblock.HarvestWorld cannot be cast to org.spongepowered.common.interfaces.world.IMixinWorld
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3422]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3972) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: mod.chiselsandbits.chiseledblock.HarvestWorld cannot be cast to org.spongepowered.common.interfaces.world.IMixinWorld
	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:1689) ~[ForgeHooks.class:?]
	at net.minecraft.block.Block.canHarvestBlock(Block.java:1154) ~[aow.class:?]
	at mod.chiselsandbits.chiseledblock.BlockChiseled.canHarvestBlock(BlockChiseled.java:1139) ~[BlockChiseled.class:?]
	at mod.chiselsandbits.items.ItemChisel.canMine(ItemChisel.java:409) ~[ItemChisel.class:?]
	at mod.chiselsandbits.items.ItemChisel.chiselBlock(ItemChisel.java:326) ~[ItemChisel.class:?]
	at mod.chiselsandbits.network.packets.PacketChisel.doAction(PacketChisel.java:190) ~[PacketChisel.class:?]
	at mod.chiselsandbits.network.packets.PacketChisel.server(PacketChisel.java:92) ~[PacketChisel.class:?]
	at mod.chiselsandbits.network.ModPacket.func_148833_a(ModPacket.java:57) ~[ModPacket.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-3422]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zle000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more

**Comment by liampearson96** [comment] 2018-09-01 15:28
Shys is pretty much the same... i'd reproduce it but i've downgraded my sponge now as too many things broke lol

**Comment by ImMorpheus** [comment] 2018-09-02 15:17
Fixed by https://github.com/SpongePowered/SpongeForge/pull/2420

**Closed as completed by ImMorpheus** 2018-09-02 15:17 UTC
Labels: type: mod incompatibility, version: 1.12
