### ISSUE TITLE
NPE Raised every time world save occurs

### ISSUE THREAD

**Issue by teaearlgraycold** [SpongePowered/SpongeForge#675] opened 2016-06-09 01:04 UTC
I'm currently running SpongeForge 1.9.4, and every 45 seconds (when the world auto-saves) and when running `save-all`, this appears in the console. This is on Windows 10 x64.

```
> SpongeNBT is: not null
Dimension id is: null
DimensionType is: OVERWORLD
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]: java.lang.NullPointerException
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.world.storage.WorldInfo.writeSpongeNbt(WorldInfo.java:742)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.world.storage.WorldInfo.getSpongeRootLevelNbt(WorldInfo.java:696)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.world.storage.SaveHandler.saveSpongeDatData(SaveHandler.java:124)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.world.storage.SaveHandler.handler$onSaveWorldInfoWithPlayerEnd$0(SaveHandler.java:99)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.world.storage.SaveHandler.func_75755_a(SaveHandler.java:172)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.world.chunk.storage.AnvilSaveHandler.func_75755_a(AnvilSaveHandler.java:40)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1055)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1004)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:441)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:640)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$0(MinecraftServer.java:595)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:630)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
[20:52:17] [Server thread/INFO] [STDERR]: [net.minecraft.world.storage.SaveHandler:saveSpongeDatData:142]:      at java.lang.Thread.run(Unknown Source)
> SpongeNBT is: not null
Dimension id is: -1
DimensionType is: NETHER
SpongeNBT is: not null
Dimension id is: 1
DimensionType is: THE_END
```

I believe [this](https://github.com/SpongePowered/SpongeCommon/blob/5afad37c96b825b9db7eb06cba52a02b4a856bea/src/main/java/org/spongepowered/common/mixin/core/world/storage/MixinWorldInfo.java#L727) is the method.

**Comment by teaearlgraycold** [comment] 2016-06-09 01:22
The world data can be saved and updated, but I suppose Sponge related metadata or whatever is having issues.

**Comment by gabizou** [comment] 2016-06-09 02:32
This is a duplicate of https://github.com/SpongePowered/SpongeCommon/issues/781

**Closed by gabizou** 2016-06-09 02:32 UTC
