### ISSUE TITLE
NPCs are disappearing in the newest version of sponge

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#2990] opened 2019-10-04 09:50 UTC
Hey guys! After updating my sponge from 2768 to 3924 and forge to 2838. Also I updated mod LagGoggless and plugins GriefPrevention I got new problem with NPCs. 
From morning to evning my server lost more than 5 NPCs (from CustomNPCs). I didnt have this issue on version 2768

**Comment by kasdo** [comment] 2019-10-04 22:07
I already lost more than 15 npcs for 2 days. So Im going to downgrade sponge and forge. If you would fix that issue then let me know, please. Thank you.

**Comment by gabizou** [comment] 2019-10-04 23:37
Sounds like a duplicate of https://github.com/SpongePowered/SpongeForge/issues/2984.

**Closed as completed by gabizou** 2019-10-04 23:37 UTC

**Comment by kasdo** [comment] 2019-10-05 09:33
Nope, its not dublicate. That problem just with vision, NPC didnt gone, player just cant see NPCs. But this problem is other. My NPCs is gone, forever.

**Comment by kasdo** [comment] 2019-10-05 09:33
> Sounds like a duplicate of #2984.

Nope, its not dublicate. That problem just with vision, NPC didnt gone, player just cant see NPCs. But this problem is other. My NPCs is gone, forever.
So... open please this issue
