### ISSUE TITLE
Server crashes after server incorrectly shut down.

### ISSUE THREAD

**Issue by oliveryasuna** [SpongePowered/SpongeForge#1849] opened 2017-11-12 20:16 UTC
I lost power to my computer so the server did not shut down correctly. Ever since the server wont start up correctly. See the crashlog at the bottom.

Thank you.

**I am currently running...**

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2698
- Forge version: 1.10.2-12.18.3.2185
- Java version: 1.8.0_151
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows
- Plugins/Mods: 

- Nucleus
- Worldedit Forge
- Just Enough Items.

**What is the expected result?**

Running fine.

**What is the current result?**

Crashlog -> https://gist.github.com/oliveryasuna/373ec9b1b7e288b444f7711c124af3a6

**Comment by phit** [comment] 2017-11-12 20:21
Roll back to a world backup, if you don't have one try deleting the level_sponge.dat in the world folder. 

Regardless this is not a bug, and stuff like that can happen when you don't shut down a server properly, so I'm closing this.

If you're still having issues, feel free to reach out in our [support channels](https://discord.gg/PtaGRAs) or [forums](https://forums.spongepowered.org/)!

**Closed as completed by phit** 2017-11-12 20:21 UTC
Labels: type: support, version: 1.10 (u)
