### ISSUE TITLE
[1.10.2] OpenComputers crash

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeForge#824] opened 2016-08-12 21:34 UTC
Crash report: http://pastebin.com/SYXJxxYx

Occurred when putting a floppy disc into a robot according to the user.

**Comment by Aaron1011** [comment] 2016-10-03 22:36
I cannot reproduce this with the latest SpongeForge (it was probably fixed with some of the recent inventory improvements). Please re-open this issue if it occurs again.

**Closed by Aaron1011** 2016-10-03 22:36 UTC
Labels: 1.10, needs testing
