### ISSUE TITLE
Bee effect not persisting through server reboot

### ISSUE THREAD

**Issue by KingDan27** [SpongePowered/SpongeForge#2211] opened 2018-06-09 06:21 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar
- Forge version: FTBserver-1.12.2-14.23.3.2702-universal.jar
- Java version: openjdk version "1.8.0_171"
- Operating System: Ubuntu

- Plugins/Mods: Catclearlag, Modpack: FTB Continuum

**Issue Description**
Yente Bee's effect from career bees mod does not persist through server reboot. Works fine with out sponge installed. doesnt work with or without catclearlag running.

<!-- Please provide a *full* server log (and crash-report if applicable).
https://gist.github.com/KingDan27/c477dc4b68599cb65c648a0ad0fcc58d

**Comment by gabizou** [comment] 2018-06-09 07:10
Aside from "testing" an entire mod pack, is this reproducible with just the mod and sponge forge? Can you provide the steps involved to reproduce the issue as if I've never used the mod before?

**Comment by KingDan27** [comment] 2018-06-09 16:14
Okay, so with just career bees and its dependancy forestry this issue is repeatable. 
Step 1: Make a apiary put a queen in it
Step 2: Make Yente princess and shift+right click the apiary with it in main hand
Step 3: Wait full bee cycle and see the effect happens correctly (effect is it takes the princess and best drone from the output and moves them to the breeding slots in the apiary)
Without Sponge
Step 4: Reboot server, wait full cycle see bee effect still happens
With Sponge
Step 4: Reboot server wait full cycle see bee effect stops happening

This test was run with the same forge and sponge forge versions as above OS is Windows 10 this time here is the log from my test: https://gist.github.com/KingDan27/546807f4abd6c2028381614f67942b21

**Comment by phit** [comment] 2018-06-09 16:29
you completely forgot to mention what the effect is,

>Yente Bees
>
> Matchmaker, matchmaker make me a match
Yente will make matches for your bees. Shift-right-click a Yente princess onto an apiary and it's breeding will be automated. Yente will always choose the drone that she judges to have the best traits for the princess.

so the automation breaks? does this also happen with other bees or just this specific one?

source for reference https://github.com/rwtema/Careerbees/blob/6a0e67cfd7132320d4f70f0a745484458de1dd54/src/main/java/com/rwtema/careerbees/entity/YenteBeeManager.java#L53

**Comment by KingDan27** [comment] 2018-06-09 16:29
i edited it

**Comment by KingDan27** [comment] 2018-06-09 16:30
just this one specificly that i have found my other ones work fine

**Comment by bloodmc** [comment] 2018-06-13 16:39
@KingDan27 retest with entity activation disabled.

**Comment by phit** [comment] 2018-06-15 21:58
to be exact make sure tile-entity-activation is disabled, the only way this realistically could be broken is if the bee house isn't updating

**Comment by KingDan27** [comment] 2018-06-19 21:32
Okay tested this today with tileentity-activation set to disabled and the effect did not persist through reboot.

**Comment by bloodmc** [comment] 2018-07-24 03:52
Is this still an issue with latest builds?

**Comment by KingDan27** [comment] 2018-07-27 04:19
as of 1.12.2-2705-710-BETA-3349 it is still not working

**Comment by phit** [comment] 2018-09-27 23:40
reproduced with 
1.12.2-2705-7.1.0-BETA-3465
careerbees-0.4.0.jar
forestry_1.12.2-5.8.1.344.jar

most likely related to https://github.com/SpongePowered/SpongeForge/issues/2293

https://github.com/rwtema/Careerbees/blob/6a0e67cfd7132320d4f70f0a745484458de1dd54/src/main/java/com/rwtema/careerbees/entity/PlacedBeeManager.java#L104

the data is simply not being saved, or stripped when read haven't actually checked the nbt yet

**Comment by Zidane** [comment] 2019-06-06 03:53
Can we get a retest of this on latest SF?

**Comment by clienthax** [comment] 2019-08-09 12:01
This may be fixed as of 3882, please retest on latest.
You may also need the config change from https://github.com/SpongePowered/SpongeForge/issues/2293

**Comment by Zidane** [comment] 2019-08-10 03:09
This is a very old issue and my previous comment has remained unanswered. I am going to close this since I agree that client's fix likely solved this one. If not, someone can let us know and we'll reopen.

**Closed as completed by Zidane** 2019-08-10 03:09 UTC
Labels: type: mod incompatibility, version: 1.12
