### ISSUE TITLE
Dupe with nether portal

### ISSUE THREAD

**Issue by mistek131995** [SpongePowered/SpongeForge#2809] opened 2019-06-07 22:56 UTC
SpongeForge version: 1.12.2-2825-7.1.6
Forge version: 1.12.2 - 14.23.5.2838
Java version: Version 8 Update 211 build 1.8.0_211-b12
Operating System: Windows Server 2012 x64

Dupe's simple... Throw the object into the portal, waiting for it to disappear and go after. It works almost the first time. Works on the latest recommended build sponge.

**Comment by JBYoshi** [comment] 2019-06-08 00:16
I can't seem to reproduce this. I'm using SpongeForge 1.12.2-2825-7.1.7-RC3769 with Forge 2825, but I don't think there have been any changes in Sponge since 7.1.6 that would affect this.

**Comment by JBYoshi** [comment] 2019-06-08 00:17
Do you have any mods or plugins installed?

**Comment by mistek131995** [comment] 2019-06-08 00:20
> Do you have any mods or plugins installed?

![Снимок экрана (1)](https://user-images.githubusercontent.com/14914380/59139551-59711f00-899c-11e9-84ab-ebaee8a0e5f2.png)

**Comment by SSKirillSS** [comment] 2019-06-11 16:50
Also faced with this problem. In the code removed the ability to transfer items through portals.

**Comment by Zidane** [comment] 2019-06-11 18:21
We need someone to narrow down a combination of mods/plugins that cause this. I cannot reproduce it with just SpongeForge.

**Comment by JBYoshi** [comment] 2019-06-14 12:33
@SSKirillSS What mods/plugins are you using? If you can post that list, it can help us narrow down what's causing the problem.

**Comment by Zidane** [comment] 2019-06-14 13:49
@JBYoshi I am putting this on hold as my upcoming changes re-writes how we teleport entities and players and it is quite possible this will be resolved (if it is an issue).

**Comment by SSKirillSS** [comment] 2019-06-14 18:01
@JBYoshi, modlist:
![image](https://user-images.githubusercontent.com/38190325/59528599-65526900-8ee7-11e9-946c-682e224aa3ed.png)
I think COFH mods is to blame, but I can't check yet.

**Comment by JBYoshi** [comment] 2019-06-14 21:46
So the mods shared between both of those cases are:

- Advanced Solar Panels
- Applied Energistics 2
- BDLib
- Binnie Mods
- Biomes O’ Plenty
- CodeChickenLib
- CoFH Core
- CoFH World
- Craft Tweaker 2
- Energy Converters
- Forestry
- Gravitation Suite
- Hwyla
- Immersive Engineering
- Immersive Petroleum
- Immersive Tech
- IndustrialCraft
- Iron Chest
- Just Enough Items
- OpenBlocks
- OpenModsLib
- Redstone Flux
- Thermal Cultivation
- Thermal Dynamics
- Thermal Expansion
- Thermal Foundation

...Except I can't reproduce this with just those mods. Probably best to wait for Zidane's changes before doing any further testing.

**Comment by Zidane** [comment] 2019-06-19 03:06
Try the latest changes in stable-7. I can absolutely confirm that does not happen with SF only.

**Comment by Zidane** [comment] 2019-06-26 18:22
Closing as I still cannot reproduce this. We'll re-open if anyone can come forward with a way.

**Closed as completed by Zidane** 2019-06-26 18:22 UTC
Labels: status: more information needed
