### ISSUE TITLE
End isn't generating any portals/egg

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1752] opened 2017-08-28 17:17 UTC
When a player kills ender dragon, no portal to the overworld/ender cities and dragon eggs are generated

![image](https://user-images.githubusercontent.com/20505933/29784578-e37f839a-8bfa-11e7-932f-baae195e65d9.png)

**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2597
- Forge version: 1.10.2-2281
- Java version: 1.8.0_144
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins (98): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, Nucleus Mixins, CoFH Core, Actually Additions, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Aliases, Baubles, Just Enough Items, Extra Utilities 2, AngelRing 2 Bauble, Applied Energistics 2, Quark, AutoRegLib, Battle Towers, Better Achievements, BetterChunkLoader, BetterKits, Bookshelf, Botania, CodeChicken Lib, Brandon's Core, BungeeTabListPlus-SpongeBridge, Buycraft, CarrotShop, CatClearLag, Chameleon, ChangeSkin, Chisel, ColorAnvil, CraftTweaker JEI Support, MineTweaker 3, Custom Stuff 4, Waila, Dark Utilities, Draconic Evolution, Elevator Mod, Valkyrie Lib, Environmental Tech,  FastAsyncWorldEdit, WorldEdit, Fast Leaf Decay, FoxCore, FoxGuard, Gravestone Mod, Gravitation Suite, GriefPrevention, GWMCrates, iChunUtil, Hats, Holograms, HorizonMC, Infernal Mobs, Iron Backpacks, JourneyMap, LuckPerms, Nucleus, UltimateChat, MagiBridge, Mantle, MCClans, MineTweakerRecipeMaker, MMCReboot, MMCRestrict, mob_grinding_utils, MTLib, Mod Tweaker, PlaceholderAPI, Nucleus Gluon, NuVotifier, PacketGate, Personal Time, PixelVip, Tinkers' Construct, Thermal Foundation, PlusTiC, Prism, PvpToggle, Thermal Expansion, Redstone Arsenal, SeriousVote, Simply Jetpacks 2, Storage Draw

Log: https://gist.github.com/PretoAlbino/92cdf55c51c90f1aa7bda925d28c633f

**Comment by pen-siv** [comment] 2017-10-02 05:32
Still appears to be an issue in 1.12.2

**Comment by ryantheleach** [comment] 2017-10-03 00:28
@travis-anderson What Sponge version did you test with? the Sponge versions available for MC 1.12 have gone through radical changes over the last month, it would be valuable to know the exact version used.

**Comment by pen-siv** [comment] 2017-10-03 00:35
@ryantheleach 
I've tried in the following versions:
1.12.1-2480-7.0.0-BETA-2643
1.12.2-2486-7.0.0-BETA-2674
1.12.2-2486-7.0.0-BETA-2682
1.12.2-2486-7.0.0-BETA-2683

**Comment by phit** [comment] 2017-11-01 04:02
can't reproduce with spongeforge-1.12.2-2503-7.0.0-BETA-2716, if you can find out which mod is needed so this doesn't work, please add it to this issue, will make debugging this a lot easier

![2017-11-01_05 02 18](https://user-images.githubusercontent.com/2097483/32259595-da2cd3fc-bec1-11e7-8c97-e73899873888.png)

**Comment by phit** [comment] 2017-11-06 19:55
Closing this for now. If this is still an issue for you, please let us know and provide relevant new info e.g. which mods are required to reproduce this.

**Closed as completed by phit** 2017-11-06 19:55 UTC
Labels: type: bug, version: 1.10 (u), status: more information needed, system: phase tracker, version: 1.12

**Comment by misaka00251** [comment] 2018-04-13 15:57
Latest 1.12.2-2611-7.0.0-BETA still have this issue....
Maybe a plugin problem?

**Comment by phit** [comment] 2018-04-13 16:02
then please test and figure out what is needed to reproduce this, we can't really help when the requirement is to install 40 mods/plugins
