### ISSUE TITLE
No Lightning / Thunderstorm Sounds

### ISSUE THREAD

**Issue by D3nnis3n** [SpongePowered/SpongeForge#1776] opened 2017-09-18 23:34 UTC
- SpongeForge version: 1.12.1-2480-7.0.0-BETA-2641
- Forge version: 2485
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

**What is the expected result?**
Hear the Lightning and Thunderstorm Sounds. 

**What is the current result?**
No hearable Lightning and Thunderstorm Sounds, until removing sponge - then i can hear them.

As there is no Crash or anything like that i did not include logs. If you need them, give me a heads up.

**Comment by davv1** [comment] 2017-09-20 10:56
I can confirm that too. After adding SpongeForge to our server, nobody can't hear Thunderstorm sound. Lighting is visible.
We were using Forge 2477 and updated to 2485, without any change in this case. Also, We're using Windows 7 OS on our server.

**Comment by D3nnis3n** [comment] 2017-09-20 10:58
Yes, lightning is visible but the sound of the lightning when it occurs and the general thunder sounds from more far away are not hearble. This is sad, as we use CoroUtils Weather Mod and it takes out a lot of immersion.

**Comment by davv1** [comment] 2017-09-20 11:20
@D3nnis3n Sorry for offtop, but by the way... How you got WeatherMod for 1.12.1? I would be very grateful for help!

**Comment by D3nnis3n** [comment] 2017-09-20 11:22
Hey,
it has been out since yesterday on CurseForge, just search it 😊

Gesendet von Mail für Windows 10

Von: davv1
Gesendet: Mittwoch, 20. September 2017 13:20
An: SpongePowered/SpongeForge
Cc: D3nnis3n; Mention
Betreff: Re: [SpongePowered/SpongeForge] No Lightning / Thunderstorm Sounds(#1776)

@D3nnis3n Sorry for offtop, but by the way... How you got WeatherMod for 1.12.1? I would be very grateful for help!

**Comment by ryantheleach** [comment] 2017-09-21 01:30
@D3nnis3n Can you confirm the list of mods you had added, or is this reproducible without mods? The 'offtopic' comments seem to imply that you are running mods that potentially interact with the weather.

**Comment by D3nnis3n** [comment] 2017-09-21 05:06
I'll do so later. But no, on the Time i opened the issue i had not had a Weather altering mod and the issue was already there for several days.

**Comment by ryantheleach** [comment] 2017-09-21 05:36
No weather altering mods? or No other mods?

**Comment by D3nnis3n** [comment] 2017-09-21 07:26
No Weather altering mods. When i come home i Post you a log where you can
See the mods. Its 135 of them. But it's working in Singleplayer with These
mods and on servers without sponge. As soon as sponge is Installed
Lightning sounds are gone.

Am 21.09.2017 07:36 schrieb "Ryan Leach" <notifications@github.com>:

**Comment by D3nnis3n** [comment] 2017-09-21 07:56
https://pastebin.com/gaFjDTee

This is the log, i also edited my post above, as it was fucked up when writing mobile.
If this is not what you need, please tell me what you want me to provide.

**Comment by davv1** [comment] 2017-09-27 18:05
@ryantheleach I'm not using any weather altering mods in my case, and still I don't get any thunder sounds.

**Comment by D3nnis3n** [comment] 2017-10-01 21:55
Do you need any more Information from me? The issue is still there in 2679.

**Comment by kashike** [comment] 2017-10-01 22:55
https://github.com/SpongePowered/SpongeCommon/blob/7678e517fb3c79535a3d0727cc061e461f09c674/src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java#L139-L143

**Comment by D3nnis3n** [comment] 2017-10-01 22:58
Ah, i saw there is an similar Issue in SpongeCommon. Didn't get you got multiple issue trackers, sorry for that.

**Comment by kashike** [comment] 2017-10-01 23:00
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1529.

**Closed as completed** 2017-10-01 23:00 UTC
Labels: version: 1.12
