### ISSUE TITLE
[1.12.2] "Silently" catching entity tracking error console spam

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1785] opened 2017-09-27 09:57 UTC
Minecraft: 1.12.2
    SpongeAPI: 7.0.0-SNAPSHOT-fb55a76
    SpongeForge: 1.12.2-2486-7.0.0-BETA-2665
    Minecraft Forge: 14.23.0.2493

<pre>
[11:49:02] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:256) [ol.class:?]
        at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:145) [ol.class:?]
        at net.minecraft.world.ServerWorldEventHandler.func_72703_a(ServerWorldEventHandler.java:37) [op.class:?]
        at net.minecraft.world.World.func_72923_a(World.java:1218) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1111) [oo.class:?]
        at net.minecraft.world.WorldServer.onSpongeEntityAdded(WorldServer.java:2897) [oo.class:?]
        at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:2943) [oo.class:?]
        at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:2926) [oo.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.splitAndSpawnEntities(TrackingUtil.java:860) [TrackingUtil.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.event.tracking.TrackingUtil.splitAndSpawnEntities(TrackingUtil.java:825) [TrackingUtil.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.event.tracking.phase.general.PostState.postDispatch(PostState.java:105) [PostState.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.event.tracking.phase.general.PostState.unwind(PostState.java:80) [PostState.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.event.tracking.phase.general.PostState.unwind(PostState.java:41) [PostState.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:209) [CauseTracker.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:399) [PhaseContext.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:215) [CauseTracker.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:399) [PhaseContext.class:1.12.2-2486-7.0.0-BETA-2665]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-2486-7.0.0-BETA-2665]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkb000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:271) [SpongeImplHooks.class:1.12.2-2486-7.0.0-BETA-2665]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zid000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Entity EntityItem['item.item.immersiveengineering.seed.hemp'/12680, l='world', x=1656.71, y=87.32, z=-4266.21] is already tracked for world: world
        at net.minecraft.entity.EntityTracker.redirect$reportEntityAlreadyTrackedWithWorld$zdg000(EntityTracker.java:561) ~[ol.class:?]
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:224) ~[ol.class:?]
        ... 29 more

</pre>

**Comment by theboomer** [comment] 2017-09-29 12:36
This is actually a SpongeCommon issue, I didn't notice this had been filed earlier when I filed mine.
The above error is caused by dragging and discarding itemstacks out of inventory GUIs and dropping outside.  It is present in SpongeVanilla as well hence spongecommon.

https://github.com/SpongePowered/SpongeCommon/issues/1543

**Comment by Zidane** [comment] 2017-09-29 13:51
Closing as this is an issue in common hence the ticket by @theboomer .

**Closed as completed by Zidane** 2017-09-29 13:51 UTC
Labels: version: 1.12
