### ISSUE TITLE
Server crash Ftbutils fakeplayer and spongepowered.common.mixin.plugin.entityactivation.ActivationRange.addEntityToConfig

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#929] opened 2016-10-01 18:01 UTC
http://pastebin.com/hXuwryAq

**Comment by LatvianModder** [comment] 2016-10-01 21:25
Def FTBU bug

**Comment by gabizou** [comment] 2016-10-01 21:31
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/928

**Closed by gabizou** 2016-10-01 21:31 UTC
