### ISSUE TITLE
Sponge + 1.16 not working

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#3277] opened 2021-12-19 21:33 UTC
**I am currently running**

- SpongeForge version: 1.16.5-36.2.5-8.0.0-RC962 
- Forge version: forge-1.16.5-36.2.20.jar
- Java version: 
- Operating System: Linux

- Plugins/Mods: Sponge / Bootsrap

**Issue Description**
Hi there,

We are having an issues Launching Enigmatica 6 with SpongeForge, once sponge is in the Mods Folder server goes to boot and crashes with this: https://pastebin.com/YgG0kRHp

With "SpongeFix" Enabled within the config and SpongeBootsrap added it crashes with this: https://imgur.com/a/EA8rnte

Using the Latest Sponge+Forge so not really sure whats going on.

Also have the Log4j Fix installed within this.

**Comment by gabizou** [comment] 2022-01-14 07:23
Duplicate of SpongePowered/Sponge#3514.

**Closed as completed by gabizou** 2022-01-14 07:23 UTC
