### ISSUE TITLE
Cost too much time to load zenscripts files

### ISSUE THREAD

**Issue by yuanjie000** [SpongePowered/SpongeForge#1767] opened 2017-09-08 12:44 UTC
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2610
- Forge version: forge-1.10.2-12.18.3.2422-universal
- Java version: 1.8.0_131-b11
- Operating System: Windows Server 2012 R2 Standard

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
Using the "Age of Engineering" modpack version(1.1.0), (I split the scripts file into four)
**What is the expected result?**
Should be loaded quickly
**What is the current result?**
As the picture shows, it took about 15minutes
![qq 20170908203558](https://user-images.githubusercontent.com/20902900/30212127-2152f20e-94d6-11e7-96a7-4761b498c1ca.png)

[logs.zip](https://github.com/SpongePowered/SpongeForge/files/1287865/logs.zip)

**Comment by phit** [comment] 2017-09-08 12:46
did you test this with vanilla forge?

also the normal AoE scripts are way more than 4 files, why did you change this?

**Comment by yuanjie000** [comment] 2017-09-08 12:48
yes, it runs perfect in a forge server.
I think it may be because the file too much lead to the slow loading, the results are no difference

**Comment by phit** [comment] 2017-09-15 22:41
I can't reproduce this on my own AoE server using the latest pack version (1.1.1b) and SpongeForge (5.2.0-BETA-2632). My server is on Linux though, might be a Windows issue?

**Comment by Deamon5550** [comment] 2017-09-15 23:31
Use a profiler to see where the time is going, no way to debug this otherwise espeically if we can't reproduce it.

**Comment by yuanjie000** [comment] 2017-09-16 07:03
Here has some sampling Snapshot of server and logs. AoE pack version (1.1.1)
Once I use profiler it did not responding. [files.zip](https://github.com/SpongePowered/SpongeForge/files/1308148/files.zip)
when i use my own pc to run the server, everything is normal. (win10 15063.608)
But Windows Server not. (Windows Server 2012 R2 Standard)
might be a Windows server issue?

**Comment by phit** [comment] 2017-11-06 20:24
Did newer AoE or Sponge versions resolve this for you or is this still an issue?

**Comment by yuanjie000** [comment] 2017-11-07 06:33
still have this problem
spongeforge-1.10.2-2477-5.2.0-BETA-2698

**Comment by phit** [comment] 2018-01-01 15:51
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:51 UTC
Labels: status: needs testing, version: 1.10 (u)
