### ISSUE TITLE
[1.11.2] Cause tracker is crazy

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1536] opened 2017-05-23 18:42 UTC
It randomly started printing this stacktrace: https://gist.github.com/Eufranio/3fe9038d2b05b6cd4231de34ec35628c

**I am currently running...**
    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-a15cc3e
    SpongeForge: 1.11.2-2282-6.1.0-BETA-2347
    Minecraft Forge: 13.20.0.2298
    Operating System: Linux (Alpine)

- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, IvToolkit, OpenComputers (Core), SpongeA
PI, SpongeForge, FoamFixCore, ccl-entityhook, Psi, Quark, AutoRegLib, Baubles, BetterChunkLoader, Biomes O' Plenty, Botania, BuildCraft Lib, BuildCraft, BC Fa
ctory, BC Transport, BC Builders, BC Energy, BC Robotics, BC Silicon, Chameleon, CodeChicken Lib, CraftTweaker JEI Support, Just Enough Items, Crafttweaker, E
mbers, EnderPay, EnderStorage, Ender Zoo,  FastAsyncWorldEdit, WorldEdit, FoamFix, IndustrialCraft 2, Forestry, Gravestone, GriefPrevention, Inventory Tweaks,
 JourneyMap, Kai's Commons, LuckPerms, MagiChat, Magistics, Nucleus, OpenComputers, Pam's HarvestCraft, Player Glow, Reborn Core, reborncore-MCMultiPart, Recu
rrent Complex, Roots 2, SignEditor, SimpleAntiAFK, Steve's Carts 2, Storage Drawers, TabManager, The One Probe, Vending

Full server log: https://gist.github.com/Eufranio/ba785df5eca7e35dde70ccb43a22bd2f

**Comment by gabizou** [comment] 2017-05-31 15:33
Your full server log doesn't actually include any of the cause tracker stack traces. The problem looks to be some chunks were generated but an exception occurred during that generation. It's important that you find the first stack trace instead of the intermediary stack traces.

**Comment by Eufranio** [comment] 2017-05-31 15:42
Hmmmm, the crash that happens after those errors is the one that I linked here: https://github.com/SpongePowered/SpongeForge/issues/1534

It's a duplicated issue then?

**Comment by Zidane** [comment] 2017-06-15 16:50
Closing as I think it is a duplicate.

**Closed as completed by Zidane** 2017-06-15 16:50 UTC
Labels: status: accepted, status: more information needed, system: phase tracker
