### ISSUE TITLE
[1.12.2] Random crash 

### ISSUE THREAD

**Issue by Flashback083** [SpongePowered/SpongeForge#1987] opened 2018-02-05 16:45 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2887
- Forge version: forge-1.12.2-14.23.1.2586
- Java version: 1.8.0_131 (61 bits)
- Operating System: Debian 8.10 (Jessie)

- Plugins/Mods:
Sponge plugins : 
SpongeAPI, SpongeForge,  FastAsyncWorldEdit, CmdBuilder, CmdControl, CoinPurse, DailyRewards, EconomyLite, GriefPrevention, Inventory Sync, LuckPerms, MultiChat Sponge, Nucleus, Pixel Announcer, PixelAutoMessages, PixelUpgrade, PixelmonEconomyBridge, PixelmonPlaceholders, PlaceholderAPI, ProjectCore, StackBan for SpongeAPI 7.x, TabManager, Tournaments, VirtualChest, VoxelSniper, WorldEdit, lootcrate project

Mods : 
 Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AutoRegLib, Backpacks!, Chameleon, CustomNPCs, Gameshark, Iron Chest, MalisisCore, MalisisDoors, MorePlayerModels, MrCrayfish's Furniture Mod, Pixel Extras, Pixelmon, Pixelmon Trainer Commands, PixelmonQuest, Quark, Varied Commodities, Wondertrade

Its very hard to explain, i have 2 servers who's running the same mods, and only one have a random crash ,*i think* its when player generate chunk, also, the crash report says lots of thing but i don't understand/find a solution on google T.T.

(I put all crash report on this link -> https://gist.github.com/Flashback083/702eb8ee3c03cc77ef02e4df974f3e58 )
Edit: new crash : 
https://gist.github.com/Flashback083/fd27fc3a6e536400ce0b74c37720354f
For this, its seems to be the connection with RCON (when user get reward while voting on my website) but i havent this problem in 1.10.2

Really thanks for your help ! ><

**Comment by ryantheleach** [comment] 2018-02-05 17:44
The website is under your control right? I've never heard of something using rcon for voting

**Comment by Flashback083** [comment] 2018-02-05 17:49
Yeah, i'm on ovh (website and server) (the website isnt dedicated but i have full access database/files) and i never see this in my 1.8.9 sponge server and 1.10.2 <_<

Edit : I disable voting/purchase on my website (also, no rcon connection) and my server is up since 2 hours, it can be hazard but weird, also, if its RCON how we can fix it, cause its Minecraft fonction o_o

Thanks !

**Comment by LXGaming** [comment] 2018-02-05 20:38
In the crash report your server was stopped by the `Server Watchdog`.

In the `server.properties` try setting `max-tick-time` value to `-1`

**Comment by Flashback083** [comment] 2018-02-06 19:17
I have still crash :/ 
https://gist.github.com/Flashback083/f8519b8189ba551968d7f88d3fa1d49e

**Comment by phit** [comment] 2018-02-06 19:26
looks like related to https://github.com/SpongePowered/SpongeForge/issues/1456
but there's a lot of weird crashes in your initial gist, any idea how to reproduce any of them?

**Comment by Flashback083** [comment] 2018-02-07 01:14
I have 10 report look different, and i think its not a map issue, its occure often when i have a rcon connection, but i'll make more test into this to confirm that

**Comment by LXGaming** [comment] 2018-02-07 01:55
Any crash reports that have `Description: Watching Server` I would ignore as they are only created when the server is **forcibly** killed by the Server Watchdog, The exception shown in the crash report is just a stack trace of the Main thread.

The latest crash you posted seems to indicate that the overworld is ether non-existent or has been unloaded.

**Comment by ryantheleach** [comment] 2018-02-07 02:17
Whilst true, if you can get repeatable stack traces, it's usually a sign of where the server is experiencing perf issues, or can get locked in an infinite loop.

**Comment by Flashback083** [comment] 2018-02-07 14:08
also, i make somes test and i just see one thing : 
Each time i disable RCON, the server have 20 TPS (no crash now)
If i enable and players vote, TPS drop a lot <_<
I close this issue, i try to use Buycraft for my shop and nuvotifier for vote, if i have another issue, i create another ticket with more information ^^
Sorry for the wasted time, and thanks for the help !

**Comment by ryantheleach** [comment] 2018-02-07 23:36
@Flashback083 I still feel this is worth investigating if someone can reproduce the issue.

**Comment by Zidane** [comment] 2018-04-19 17:16
Closing this until we get feedback it happens again.

**Closed as completed by Zidane** 2018-04-19 17:16 UTC
Labels: status: more information needed, version: 1.12
