### ISSUE TITLE
Baubles Inventory voids items - Reopened issue.

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1933] opened 2018-01-03 22:28 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2817
- Forge version: 14.23.1.2575
- Java version: 1.8.0_151-b12
- Operating System:  CentOS Linux release 7.2.1511

- Plugins/Mods:
This is an issue on 1.10/1.12 servers

**Issue Description**
https://github.com/SpongePowered/SpongeForge/issues/1320

Still an issue, was first reported for 1.10.2, have testing on 1.12.2 and getting the same issue.

Press E, pick up any item, click on your baubles icon with the item in your hand and it will void the item.

**Comment by phit** [comment] 2018-01-04 00:19
Ah, that's a different reproduction from the original issue. The original repro no longer works, but can confirm the new one does using 
[`Baubles-1.12-1.5.1.jar`](https://minecraft.curseforge.com/projects/baubles/files/2459083)

**Comment by bloodmc** [comment] 2018-02-01 03:26
@Keaton1188 @phit Are you sure this isn't the same exact issue as https://github.com/Azanor/Baubles/issues/223

If so then close this as it's intended behavior.

**Comment by bloodmc** [comment] 2018-02-01 03:35
Just tested bleeding and item dropped fine.

**Closed as completed by bloodmc** 2018-02-01 03:35 UTC
Labels: version: 1.10 (u), system: inventory, version: 1.11 (u), version: 1.12
