### ISSUE TITLE
[1.10.2] Feature Request (Moved too quickly)

### ISSUE THREAD

**Issue by Proxying** [SpongePowered/SpongeForge#1121] opened 2016-12-18 06:17 UTC
While players are riding entities within Minecraft, if the entity moves too quickly the server incorrectly calculates where it should be and "rubber-bands" it back to that location while printing "Vehicle X of Player Y moved too quickly". This is a pretty significant issue with mods such as Pixelmon where there are many Pokemon of varying speeds and abilities (land mounts, flying mounts, water mounts). This issue affects all of these, and contributes to lag within the server. (Example of a complaint with this issue: https://forums.spongepowered.org/t/1-10-2-too-quickly-error-performance-issue/14376)

Within Cauldron (Where modded servers ran within 1.7.10), this was not an issue as I believe it was patched manually. 

It would be nice for this patch to be created for Sponge as a config option for modded servers with ride-able entities to use.

EDIT: Placed this within Sponge Forge as it's more of a modded server issue, I'm not sure if it occurs with vanilla vehicles as the movement code within minecraft was written with them in mind. However if it is, it'd probably be a feature worthwhile within SpongeCommon.

**Comment by Rasgnarok** [comment] 2016-12-18 06:34
Referencing this off of a ticket made months ago; 
https://github.com/SpongePowered/SpongeForge/issues/952

Both the `PLAYER moved wrongly!` and `VEHICLE (vehicle of PLAYER) moved too quickly!` are great causes for lag spikes in servers - they not only clutter logs, but suspend action for a few seconds, until the spam ends. I have personally tried setting sponge's config option `max-speed=0`, which is the "square of the max speed of an entity before removing it". By setting it to 0, you are supposed to make it ignore the removal; but this does not seem to apply to vehicle entities. My guess, it is entirely error complaints without actually processing the entity more than the rubber-banding of the player.

It is still a much needed feature, as it would help curb the lag spikes caused by hundreds of error messages being spammed from a player using a boat, riding a horse, or even Pixelmon.

**Comment by phit** [comment] 2017-11-07 15:25
Closing this in favor of https://github.com/SpongePowered/SpongeCommon/issues/1511

**Closed as completed by phit** 2017-11-07 15:25 UTC
Labels: type: enhancement, version: 1.10 (u)
