### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by Shmeeb** [SpongePowered/SpongeForge#2899] opened 2019-07-24 10:10 UTC
Crash on boot: https://pastebin.com/fuA2hJ3y

**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3856.jar
- Forge version: 14.23.5.2838
- Java version: 8

**Comment by Shmeeb** [comment] 2019-07-24 10:15
I downgraded to SF 3845 and it was able to boot

**Comment by ImMorpheus** [comment] 2019-07-24 19:22
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2324

Fixed by https://github.com/SpongePowered/SpongeCommon/pull/2327

**Closed as completed by ImMorpheus** 2019-07-24 19:22 UTC
Labels: resolution: duplicate, version: 1.12
