### ISSUE TITLE
The domesticated wolf becomes sluggish after entering the portal

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2843] opened 2019-06-27 01:15 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2825-7.1.6-RC3731.jar
- Forge version: 1.12.2-2768
- Java version: java8
- Operating System: debian

- Plugins/Mods:
custom npcs
BOP
Ferdinand's+Flowers
twilightforest-1.12.2-3.8.689
Nucleus-1.11.0-S7.1-MC1.12.2-plugin

**Issue Description**
The portal represents any portal , the end/nether/twilightforest portal, mainly manifested as unable to follow the owner, I tested, this does not happen in single player mode, the second problem, multiple teleport entities between portal can disappear.

After some debugging, I found 
```
EntityAIFollowOwner#isTeleportFriendlyBlock 
line: this.world.isAirBlock(blockpos.up())
```
that it always returns false, but it's definitely air!

**Comment by Zidane** [comment] 2019-06-27 01:17
I'm sorry but this issue isn't really readable...and has multiple problems in one. Please clarify, a lot.

**Comment by zhourui123** [comment] 2019-06-27 01:22
When a domesticated wolf enters the portal, he is still (not sitting) and does not follow his owner

**Comment by zhourui123** [comment] 2019-06-27 01:33
You only need the following steps to reproduce the problem:
step1.  Make a end portal or nether portal
step2.  Summon and domesticate a wolf
step3.  Lead the wolf into the portal
step4. Similarly, you enter the portal
step5.  Right click on the Wolf to make it stand, then move, and see if the Wolf follows you
You can also summon a skeleton, which the Wolf cannot hunt.
If wolves are normal, try again, because I have a 90% chance of reappearing

**Comment by KorewaLidesu** [comment] 2019-06-27 06:42
try on server instead of SP?

**Comment by zhourui123** [comment] 2019-06-27 14:21
Yes, sluggish performance only occurs on servers

**Comment by JBYoshi** [comment] 2019-06-27 16:01
I can't reproduce this on SpongeForge 1.12.2-2838-7.1.7-RC3822. After several attempts, the wolf was able to freely move around, although it did take a moment before it started moving.

**Comment by KorewaLidesu** [comment] 2019-06-28 00:56
> spongeforge-1.12.2-2825-7.1.6-RC3731.jar

nice SF version sir

**Comment by phit** [comment] 2019-06-28 01:02
@zhourui123 update Sponge

**Comment by zhourui123** [comment] 2019-06-28 01:06
I will test the version you said as soon as possible, and then give feedback

**Comment by zhourui123** [comment] 2019-06-29 08:11
https://vimeo.com/user100271098/review/345164934/b44385b34e
I tested it in this 2825 version(The recommended version),same problem, is there a problem with the setting file?

**Comment by KorewaLidesu** [comment] 2019-07-14 02:36
RC3822 not the 2825

**Comment by KorewaLidesu** [comment] 2019-07-14 02:37
RCxxxx => version update by the time

**Comment by Zidane** [comment] 2019-08-05 01:18
Closing until we can get reproduction steps on the latest SF. We'll reopen when we hear back.

**Closed as completed by Zidane** 2019-08-05 01:18 UTC
Labels: version: 1.12, status: waiting for reply
