### ISSUE TITLE
CME On teleport

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeForge#891] opened 2016-09-06 19:30 UTC
On teleporting there seems to be a small chance of this crash occuring.

It's happened with both Nucleus and Prism teleports so far.

```
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-196e11e
    SpongeForge: 1.10.2-2073-5.0.0-BETA-1707
    Minecraft Forge: 12.18.1.2076
```

http://pastebin.com/raw/2MpKu1xM

**Comment by Nentify** [comment] 2016-09-09 00:14
Steps to reproduce:

1. Download and install Minecraft Forge 1.10.2 12.18.1.2076 from http://files.minecraftforge.net/
2. Run server and agree to the eula
6. Stop server
7. Download SpongeForge 1.10.2 5.0.0-BETA-1708 from http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/
9. Download EnderCore 1.10.2 0.4.1.54 from https://minecraft.curseforge.com/projects/endercore/files/2328765
12. Download Nucleus 0.9.0-S5-1.10.2 from https://github.com/NucleusPowered/Nucleus/releases
14. Run server
15. Join the server
16. Run the `/rtp` command many times until the CME occurs

This is the Nucleus issue: https://github.com/NucleusPowered/Nucleus/issues/360

I can reproduce with `/rtp` quite reliably. I can also reproduce with `/minecraft:tp` but only after reproducing with `/rtp` and then removing Nucleus (may be coincidence, but I've tried many times and spent many hours trying to figure out this issue). `/rtp` can crash within a few usages.

Removing any 1 of the 3 mods stops the issue from occurring.

**Comment by Nentify** [comment] 2016-09-09 11:49
Can reproduce on build 1707, can't reproduce on 1704. The builds in between all crash on start up.

**Comment by bloodmc** [comment] 2016-09-12 00:18
@Nentify Try to reproduce this on latest build.

**Comment by inklit** [comment] 2016-09-12 00:27
I've seen this error quite a lot although I have not really linked it to teleporting, I originally thought it had to do with either chunk loading or unloading.

**Comment by Nentify** [comment] 2016-09-12 11:20
@bloodmc Can still reproduce this issue on build 1719.

**Comment by bloodmc** [comment] 2016-09-13 21:21
This issue is caused by EnderCore calling isInLava when 'EntityPlayer.isElytraFlying' is called which has the potential of loading a chunk causing re-entry to 'EntityTracker.updateTrackedEntities'.

**Comment by Zidane** [comment] 2016-10-04 19:15
https://github.com/SleepyTrousers/EnderCore/commit/8c630f79ad05058378dd4b5f3aefa5e02809ff25

Fixed in EnderCore.

**Closed by Zidane** 2016-10-04 19:15 UTC
