### ISSUE TITLE
Simple Dimensions Incompatibility 

### ISSUE THREAD

**Issue by Eldwen** [SpongePowered/SpongeForge#1684] opened 2017-07-29 22:33 UTC
apprently there is some issues with the mod simple dimensions

**I am currently running 1.11.2 with a modpack and spongeforge 2484**

- SpongeForge version: 1.11.2-2484
- Forge version: 1.11.2-2421
- Java version: omgserv' servers one
- Operating System: omgserv' servers one (maybe linux)

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Plugins (130): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, ColorUtility, CreativeCoreDummy, IvToolkit, SpongeAPI, SpongeForge, ccl-entityhook, SecurityCraft, Additional Banners, AppleCore, Armor Overlay, Just Enough Items, B.A.S.E, BetterBedrockGen, Better Achievements, Better Builder's Wands, BiblioCraft, Mantle, Natura, BiblioWoodNatura, Chameleon, Chest Transporter, CodeChicken Lib, ChickenChunks, Chisel, Chisels & Bits, ShadowMC, Clipboard, Clumps, Craftable Notch Apple Mod - MCVersion 1.11.2, Cooking for Blockheads, CosmeticArmorReworked, Craftable Saddles, Craftable Chainmail, Craftable Horse Armour [CHA&S], Crafteable Totem And ChainMail Armor Mod, CraftTweaker JEI Support, Crafttweaker, CreativeCore, CustomNPCs, CXLibrary, Dbrown55 Util Mod, 1.12 Concrete, ptrmodellib, Decocraft, Dimension Rules, Disenchanter, Earthworks, Elevator Mod, Enjin Minecraft Plugin, Lapis Stays in the Enchanting Table, EnderPay, EnderStorage, Extra Bit Manipulation, EZStorage 2, Fairy Lights, Fast Leaf Decay, Flat Colored Blocks, Shadowfacts' Forgelin, SimpleCore API, SimpleOres 2, Netherrocks, Fusion, Harvest, HelpFixer, hungerinpeace, Iron Chest, Just Enough HarvestCraft, Just Enough Pattern Banners, JourneyMap, Just Enough Buttons, Keeping Inventory, KleeSlabs, LLibrary, Login Shield, �3Map Maker's Tabs, MiniCoal, Mo'Bends, MTLib, Mod Tweaker, More Anvils, More Furnaces, Morpheus, Nether Chest, NetherPortalFix, No Mob Spawning on Trees, OnlinePictureFrame, Open Glider, Pam's HarvestCraft, Plants, Thut Core, In-game NBTEdit - Pokecube Edition, Pok�cube Core, Pokecube Model Loader, Thut's Wearables, Thut's Bling, Thut Essentials, waila, Pok�cube Revival, Pok�cube Mobs, Pokecube Movess, Pokecube Origin, Pokecube Compat, Pokecube Mystery Dungeon, Pokecube Server Utils, Potion Icon Remover, Quadrum, Rainbow Oak Trees, Redstone Paste, Server Tick Monitor, ShowArmsStand, Simple Dimensions, Simple Grinder, Simple Magnet, Storage Drawers, Storage Drawers Extras, Glazed Terracotta for 1.11.2, Thermal Solars, TorchMaster, Tree Chopper, Underp Hangables, Vein Miner, Mod Support, Vending, What Are We Looking At, WorldEdit, Xtones

**What is the current result?**

Sponge not working with simple dimensions thing : https://pastebin.com/H43WkfxU

**Comment by phit** [comment] 2017-11-07 11:23
I have edited your post to make this about only one issue and opened a new issue here https://github.com/SpongePowered/SpongeForge/issues/1838, for the command block desync

**Comment by HorizonsMC** [comment] 2017-11-30 07:43
Same issue with Just Enough Dimensions in 1.12.2

**Comment by phit** [comment] 2017-12-02 03:13
Duplicate of #1444

**Closed as completed by phit** 2017-12-02 03:13 UTC
Labels: resolution: duplicate, type: mod incompatibility, version: 1.11 (u)
