### ISSUE TITLE
Draconic Evolution Grinder Crash

### ISSUE THREAD

**Issue by tgstyle** [SpongePowered/SpongeForge#1783] opened 2017-09-23 17:48 UTC
This keeps happening with a draconic grinder and draconic stabalized spawner.

**I am currently running...**

- SpongeForge version: 7.0.0-BETA-2653
- Forge version: 12.13.0.2489
- Java version:  1.8.0_144-b01
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 

Draconic Evolution 1.12-2.3.4.265

https://gist.github.com/tgstyle/4bb31234fbb7f0626edfc84be4e0a185

**Comment by Eufranio** [comment] 2017-09-23 17:56
I believe this is duplicate of https://github.com/SpongePowered/SpongeForge/issues/1588.

**Comment by tgstyle** [comment] 2017-09-23 19:14
Somewhat, the Grinder is a TE, the other is entities.

**Comment by tgstyle** [comment] 2017-09-23 19:30
Seems it could be an effect of the Grinder killing an effected Entity though.

**Comment by tgstyle** [comment] 2017-09-25 20:28
In my case it seems to be caused by Scaling Health creating blight mobs (via a Stabalized Spawner), which then crashes the server when the DE Grinder kills them.

https://minecraft.curseforge.com/projects/scaling-health/files

**Comment by phit** [comment] 2017-11-06 22:21
Duplicate of #1588

**Closed as completed by phit** 2017-11-06 22:21 UTC
Labels: resolution: duplicate, version: 1.12
