### ISSUE TITLE
StackOverflowError with Tracking

### ISSUE THREAD

**Issue by johnfg2610** [SpongePowered/SpongeForge#1564] opened 2017-06-03 21:39 UTC
**I am currently running...**

- SpongeForge version: 1.11.2-2282-6.1.0-BETA-2358
- Forge version: 13.20.0.2282
- Java version: 8 111
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Plugins (180): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Aroma1997Core, Micdoodle8 Core, OpenEye, Backpacks!, SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, Baubles, extrautils2, AngelRing 2 Bauble, AppleCore, Just Enough Items, AppleSkin, Forgelin, Mantle, Chisel, Tinkers' Construct, TheDragonLib, ArmorPlus, Aroma1997Core|Helper, Aroma1997sDimension, Astral Sorcery, Psi, Computality, IndustrialCraft 2, Mekanism, Natura, Better With Mods, Quark, AutoRegLib, BD Lib, Bed Bugs, Bedrock-B-Gone, Better Achievements, Better Builder's Wands, BiblioCraft, Biomes O' Plenty, BiblioWoodBoP, BiblioWoodNatura, Cyclic, Guide-API, Blood Magic: Alchemical Wizardry, Bloodmoon, Bookshelf, Bookshelf, Botania, SonarCore, Calculator, Can I Join Now?, MrCrayfish's Furniture Mod, Chameleon, CodeChicken Lib, ChickenChunks, Chisels & Bits, Cyclops Core, CommonCapabilities, Compact Solar Arrays, CompactStorage, Cooking for Blockheads, CraftTweaker JEI Support, Crafttweaker, CXLibrary, Cyberware, Dark Utilities, Death Quotes, ElecCore, DeepResonance, Storage Drawers, Drawers & Bits, Elevator Mod, Embers, EnderStorage, Ender Utilities, Ender Zoo, Valkyrie Lib, Environmental Tech, EvilCraft, Zero CORE, Extreme Reactors, EZStorage 2, Fire's Random Things, FL, FluxNetworks, FoamFix, Forge Endertech, Not Enough Items, FTBLib, Galacticraft Core, Galacticraft Planets, Advanced Generators, GlareTorch, Gravestone, Grue, Hammer Core, Hardcore Darkness, Hardcore ORE, HelpFixer, Infernal Mobs, MTLib, InitialInventory, Inventory Pets, Inventory Tweaks, Iron Chest, JourneyMap, Just JetPacks, LimeLib, Mana Wells, MekanismGenerators, MekanismTools, Metamorph, Mike Dongles, Missing Pieces, MmmMmmMmmMmm, mob_grinding_utils, Morpheus, Mysterious Miscellany, Mystical Agriculture, NoMoreRecipeConflict, NotEnoughIDs, Not Enough Wands, NuclearCraft, OMLib, Open Modular Turrets, Ore Control, Ore Dictionary Converter, OreExcavation, Overloaded, Pam's HarvestCraft, Quick Leaf Decay, Random Things, Ranged Pumps, Reborn Core, reborncore-MCMultiPart, Redstone Paste, Refined Storage, Reforged, Reliquary, RFTools, Roguelike Dungeons, Roots 2, ShetiPhian-Core, Silent Lib, Silent's Gems, Simple Fluid Tanks, Simple Teleporters, Simply Conveyors & More, SlashBlade, Slurpie's Dongles, Solar Flux Reborn, Soul Shards - The Old Ways, The Spice of Life, Steve's Carts 2, Subaraki's Common Library, Super Crafting Frame, The One Probe, Tiny Progressions, TOP Addons, TorchMaster, Translocator, Transprot, Woot, XNet, BetterChunkLoader, Buycraft, CatClearLag, GriefPrevention, DimReseter, Discord Bridge, LuckPerms, Nucleus, NuVotifier, PlayerShopsRPG, SpongeAnnounce, WorldEdit, denseores

**What is the expected result?**
it to not crash

**What is the current result?**
it crashes

crash log: https://pastebin.com/dUUzSiZm
server log: https://pastebin.com/Z02gPetF

**Comment by johnfg2610** [comment] 2017-06-08 17:45
some debug info from @Aaron1011 custom debug build https://thepasteb.in/p/3lhJcDJ9LGAXJuN 
"this looks bad I don't think we handle captures for forge's fluids properly since acutallyadditions doesn't change any of the fluid behavior in their blocks" was what aaron said to one of our staff

**Comment by Zidane** [comment] 2017-06-15 15:54
@Aaron1011 

Status?

**Comment by johnfg2610** [comment] 2017-06-15 17:53
it seems to be doing it to other blocks too like gravel ive attached the crashlog 
[crash-2017-06-15_04.09.07-server.txt](https://github.com/SpongePowered/SpongeForge/files/1078500/crash-2017-06-15_04.09.07-server.txt)

**Comment by tyler489** [comment] 2017-06-22 21:48
@Aaron1011 Bad News Added Imersive Petrolium to the pack and now our console is spammed with this https://pastebin.com/5GA5C2V5

**Comment by phit** [comment] 2018-01-01 15:58
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:58 UTC
Labels: version: 1.11 (u)

**Comment by tyler489** [comment] 2018-01-07 20:19
Can't say im to impressed  with spongeforge currently. 6 months with no responce to this issue then you tell me  this issue is invalid because its outdated. Kinda a  dick move there dont you think
