### ISSUE TITLE
Console span with errors: Completing incorrect phase

### ISSUE THREAD

**Issue by Wadimich** [SpongePowered/SpongeForge#1713] opened 2017-08-12 18:16 UTC
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2546
- Forge version: 12.18.3.2281
- Java version: 8 build 92
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
https://hastebin.com/ihayojiqug.pl
**What is the expected result?**
No errors.
**What is the current result?**
TPS is going low, may go to crash or not, depends on errors.
Here is a little bit of log https://gist.github.com/Wadimich/ca1d9cb60a01e19cdd4ef5ccc149556a
**Full log:** [fml-server-latest.zip](https://github.com/SpongePowered/SpongeForge/files/1219974/fml-server-latest.zip)

**Comment by phit** [comment] 2017-08-12 18:24
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1477

**Closed as completed** 2017-08-12 23:00 UTC
