### ISSUE TITLE
ClassCastException WeakReference cannot be cast to org.spongepowered.api.world.World

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [SpongePowered/SpongeForge#1852] opened 2017-11-13 00:27 UTC
**I am currently running...**

- SpongeForge version: 270 1.12 
- Forge version: 2731
- Java version: 1.8
- Operating System: Some kind of Linux that the host uses

 - [x ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
-------------
Rank Upper 5.0-6.0-3.0.1-b207
React-1.2.4
EMPSponge7
MMCReboot 2.1.1
Boop 1.6.0
Nucleus 1.2.0 PR2 S7.0
Luckperms-Sponge-3.4.39
ActiveTime-s6.0-v1.2.4
griefprevention-1.12.1-4.3.0.480
TabManager-1.0.4
TotalEconomy-1.7.1-API7
Project Core 7.00-0.2.0
Stackban 7.0.0-0.3.0
LangSwitch
CatClearLag 0.8
Placeholder API 4.1
WalletDrop 7.0.0. 4.1
DimReseter 1.0.2
CommandSigns API 6.0.0 1.3.1
Menu 0.0.8
BuyCraftX
---------------
**What is the expected result?**
For the server to work
**What is the current result?**
A Crash 

https://paste.ee/p/ZU91T

**Comment by phit** [comment] 2017-11-13 00:29
@gabizou I believe this is related to https://github.com/SpongePowered/SpongeForge/commit/d16eb67d4f640625ab28863e545757eabddbf719

**Comment by CrankySupertoonArchive** [comment] 2017-11-13 00:31
Also the server does go up but then it crashes a minute or 2 later. Maybe a plugin is registering a invalid something

**Comment by phit** [comment] 2017-11-13 00:33
actually this is a dupe of https://github.com/SpongePowered/SpongeForge/issues/1851
my bad I told @Technobot7 to open an issue

**Closed as completed by phit** 2017-11-13 00:33 UTC
Labels: resolution: duplicate, version: 1.12
