### ISSUE TITLE
Sponge Crash With Morpheus Mod

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#1635] opened 2017-07-07 03:23 UTC
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar
- Forge version: 12.18.3.2281
- Java version: 1.8.0_111
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: 
Morpheus-1.10.2-3.1.13.jar
VoidCraft-1.10.2-0.19.6.jar

**What is the current result?**
I discovered that sponge has a problem when using ViodCraft and Morpheus mod.
To play the crash, you must enter the voidcraft portal to create that dimension and just when the server appears it will close.
I have already reported this to the authors of the mods but said that it is sponge problem.

CrashReport: https://pastebin.com/raw/PShNfNaH

**Comment by phit** [comment] 2017-07-07 03:39
dupe of https://github.com/SpongePowered/SpongeForge/issues/830

**Closed as completed** 2017-07-07 05:50 UTC
