### ISSUE TITLE
Server crash with Sponge dealing with dimensions

### ISSUE THREAD

**Issue by silent-mobious** [SpongePowered/SpongeForge#1429] opened 2017-04-10 04:55 UTC
Forge: 1.10.2-12.18.3.2272
Sponge: 1.10.2-2254-5.2.0-BETA-2272
Galacticraft: 1.10.2-4.0.0.58-BETA

When launching my server with just forge and Galacticraft things work well, however when adding Sponge it crashes with Dimension errors.  I believe I saw this with Sponge issue #1360 however that was for 1.8.9 so you understandably weren't supporting it you told @radfast.  This is with supported 1.10.2, so hopefully you can see if the dimension issues with Sponge have a possible resolution?

Thanks!

Silent

Full Log:
https://pastebin.com/vtETxR0K

<details>
<summary>Relevant Section of Crash Log :</summary>

```
[00:29:25] [Server thread/ERROR] [galacticraftplanets/]: Skipping event FMLPostInitializationEvent and marking errored mod galacticraftplanets since required dependency galacticraftcore has errored
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: PostInitialization - Galacticraft Planets took 0.000s
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Finished: PostInitialization took 0.064s
[00:29:25] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from POSTINITIALIZATION to AVAILABLE. Loading cannot continue
[00:29:25] [Server thread/ERROR] [FML/]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2272-universal.jar) 
	UCHIJ	Forge{12.18.3.2272} [Minecraft Forge] (forge-1.10.2-12.18.3.2272-universal.jar) 
	UCHIJ	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJ	spongeapi{5.2.0-SNAPSHOT-a3257a0} [SpongeAPI] (minecraft.jar) 
	UCHIJ	sponge{1.10.2-2254-5.2.0-BETA-2272} [SpongeForge] (spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar) 
	UCHIE	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.58-BETA.jar) 
	UCHIE	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.58-BETA.jar) 
[00:29:25] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[00:29:25] [Server thread/ERROR] [FML/]: Caught exception from Galacticraft Core (galacticraftcore)
java.lang.IllegalArgumentException: Invalid dimension id -28
	at net.minecraft.world.DimensionType.lambda$getById$0(DimensionType.java:636) ~[atm.class:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_111]
	at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:636) ~[atm.class:?]
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.postInit(GalacticraftCore.java:372) ~[GalacticraftCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) ~[forge-1.10.2-12.18.3.2272-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[00:29:25] [Server thread/WARN] [FML/]: Can't revert to frozen GameData state without freezing first.
[00:29:25] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStoppedEvent to mod mcp
[00:29:25] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStoppedEvent to mod mcp
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Minecraft Coder Pack took 0.000s
[00:29:25] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStoppedEvent to mod FML
[00:29:25] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStoppedEvent to mod FML
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Forge Mod Loader took 0.000s
[00:29:25] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStoppedEvent to mod Forge
[00:29:25] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStoppedEvent to mod Forge
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Minecraft Forge took 0.000s
[00:29:25] [Server thread/TRACE] [Micdoodlecore/Micdoodlecore]: Sending event FMLServerStoppedEvent to mod Micdoodlecore
[00:29:25] [Server thread/TRACE] [Micdoodlecore/Micdoodlecore]: Sent event FMLServerStoppedEvent to mod Micdoodlecore
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Micdoodle8 Core took 0.000s
[00:29:25] [Server thread/TRACE] [spongeapi/spongeapi]: Sending event FMLServerStoppedEvent to mod spongeapi
[00:29:25] [Server thread/TRACE] [spongeapi/spongeapi]: Sent event FMLServerStoppedEvent to mod spongeapi
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - SpongeAPI took 0.000s
[00:29:25] [Server thread/TRACE] [sponge/sponge]: Sending event FMLServerStoppedEvent to mod sponge
[00:29:25] [Server thread/TRACE] [sponge/sponge]: Sent event FMLServerStoppedEvent to mod sponge
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - SpongeForge took 0.005s
[00:29:25] [Server thread/TRACE] [galacticraftcore/galacticraftcore]: Sending event FMLServerStoppedEvent to mod galacticraftcore
[00:29:25] [Server thread/TRACE] [galacticraftcore/galacticraftcore]: Sent event FMLServerStoppedEvent to mod galacticraftcore
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Galacticraft Core took 0.009s
[00:29:25] [Server thread/ERROR] [galacticraftplanets/]: Skipping event FMLServerStoppedEvent and marking errored mod galacticraftplanets since required dependency galacticraftcore has errored
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Galacticraft Planets took 0.000s
[00:29:25] [Server thread/DEBUG] [FML/]: Bar Finished: ServerStopped took 0.016s
[00:29:25] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[00:29:25] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
```
</details>

**Comment by radfast** [comment] 2017-04-10 11:47
**UPDATE:  please see [this post below](https://github.com/SpongePowered/SpongeForge/issues/1429#issuecomment-352966266) for a current issue**

-------------------------------

hey, I was notified of this.  anything we can do on our side as Galacticraft devs to help you guys to fix this, we will.

Dimension -28 is the Moon, that should be registered as a dimension with a WorldProviderMoon type by both client and server, during post-init phase.

[DimensionType.register(name, suffix, id, provider, keepLoaded);](https://github.com/micdoodle8/Galacticraft/blob/MC1.10/src/main/java/micdoodle8/mods/galacticraft/api/GalacticraftRegistry.java#L219)

(Also to say I haven't forgotten about #1360, I will make a PR for that soon, as discussed there, we've been a bit busy last few days with the simultaneous lauch of our beta versions for 1.8.9, 1.10.2 and 1.11.2)

**Comment by Zidane** [comment] 2017-04-10 14:48
@radfast 

Why are you registering it as late as post init?

**Comment by radfast** [comment] 2017-04-10 15:01
3 reasons, I think
* we have several submods made by other developers (mods like AmunRa, Extra Planets, More Planets) and it's to give them a chance to register their planets with our internal Registry, which then registers all the dimensions together
* it reduces conflicts with other Forge Mods, because by this stage we'll know if other mods are trying to use the same dimension ID
* we've always done it this way, and it worked fine in vanilla servers and Bukkit/Cauldron/Thermos  :)

**Comment by radfast** [comment] 2017-04-10 15:04
Bear in mind that we can also **dynamically** create and load dimensions even later than this - we create Space Station dimensions on the fly (Mystcraft uses a similar system, so does AE2's Storage Cells)

**Comment by gabizou** [comment] 2017-04-10 17:45
@radfast I have no clue how Galacticraft is supposed to even be imported into an IDE, it doesn't have all dependencies on a clone and setup. That being said, if you could link to where you're dynamically creating dimensions, we can also look into that as well.

**Comment by radfast** [comment] 2017-04-10 18:00
You hopefully shouldn't need to do anything other than make sure that ```DimensionType``` and ```DimensionManager``` behaviour is unaltered from standard, for Forge mods.  We make **full** use of all the functionality that standard Forge ```DimensionManager``` provides.

IDE setup instructions (valid for 1.10 as well, just use the correct branch of our Github project)
https://wiki.micdoodle8.com/wiki/GC3_API#Full_Galacticraft_Sources

Summary:

Galacticraft is two Github projects: [micdoodle8/Galacticraft](https://github.com/micdoodle8/Galacticraft) and [micdoodle8/MicdoodleCore](https://github.com/micdoodle8/MicdoodleCore).  Both have a MC1.10 branch.

1.  (_If you only want to browse our source code and you don't care about compile errors (field visibility errors etc) then you can skip this step 1._)  Set up the Forge workspace with the access transformers required - the access transformers are found in Micdoodlecore [/main/resources](https://github.com/micdoodle8/MicdoodleCore/tree/1.10/src/main/resources) and in Galacticraft [/dependencies/main/resources](https://github.com/micdoodle8/Galacticraft/tree/MC1.10/dependencies/main/resources), you need to put all four of those access transformers somewhere where ForgeGradle can find them during setupdecompworkspace

2.  Set your source file paths to include [src/](https://github.com/micdoodle8/MicdoodleCore/tree/1.10/src) from MicdoodleCore repository and [src/](https://github.com/micdoodle8/Galacticraft/tree/MC1.10/src) and [dependencies/](https://github.com/micdoodle8/Galacticraft/tree/MC1.10/dependencies) from Galacticraft repository.

**Comment by radfast** [comment] 2017-04-10 18:04
Server space station dimension registrations - note this is during **world load** if it's a SSP integrated server, because these dimensions can be different for each different saved map.
[Space stations world load registrations](https://github.com/micdoodle8/Galacticraft/blob/MC1.10/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L463-L483)
These dimensions will therefore be released (unregistered) on **world unload**.

In addition, new dimensions can be created on the fly, by player actions in the game (riding a rocket and pressing the 'Create Space Station' button once he reaches space):

[New space station dimID allocation](https://github.com/micdoodle8/Galacticraft/blob/MC1.10/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L617)

[New space station dimension creation dynamically](https://github.com/micdoodle8/Galacticraft/blob/MC1.10/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L630-L646)

In addition to all the above these things also happen on the client, but you don't have to worry about client side I think!

**Comment by radfast** [comment] 2017-04-10 18:20
If you want to spend some time actually playing our mod (it is enjoyable: riding a rocket to space the first time is fairly awesome) latest 1.10 beta is [here](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)

To make a space station and get to space very quickly
* make a new world with cheats enabled (you need to be op)
* /gamemode 1
* /dimensiontp
* click once on the Overworld orbiting the sun, the GUI should show "A spacestation can be created here" with a green Create button
* click the Create button

To do this slightly more slowly, use creative mode or JEI or similar to spawn in 9 Rocket Launch Pads and 1 Tier 3 Rocket (Pre-fueled) (Creative only).  Place down the rocket launch pads in a 3 x 3 grid on the ground.  Take the rocket in hand as your current item, right-click the launch pad to place it.  Right click to mount the rocket and press SPACE to launch.

**Comment by gabizou** [comment] 2017-04-10 21:47
@radfast I'm still confused as to how to set up the workspace according to the wiki. It's mentioning that I'd need to set up a Forge workspace as well?? The entire point of ForgeGradle is not needing to set up a Forge workspace by itself before working on the mod.

Anyways, that being said, is there a link to download a de-obfuscated build?

**Comment by radfast** [comment] 2017-04-10 22:13
Access Transformers require the Forge workspace to be re-setup before they take effect.  Maybe you haven't used those before?  If you already have a Forge workspace, then it is a quick process to run ```gradle decompworkspace``` with some access transformers in src/main/resources.  It has the effect of changing the access of specified vanilla (or Forge) private fields and methods to public as required.  It doesn't damage anything else, but if you don't like the sound of that then I guess you'd need to duplicate or backup your whole Forge workspace before doing this!

You can skip step 1 if you don't actually want to build the mod: but if you want to build and run de-obfuscated Galacticraft in an IDE, you will need to do step 1.

We do not have a de-obfuscated distribution of the mod in 1.10.2 at this time.  I'll ask @micdoodle8 if it's possible to make one, but that could take a few days, the build gradle and Jenkins are not currently set up for that in 1.10.2.

**Comment by DenWav** [comment] 2017-04-10 22:24
Uhm https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/resources/META-INF/common_at.cfg

It sounds like you don't know how to setup a proper Forge mod workspace.

**Comment by radfast** [comment] 2017-04-10 22:48
Quite possibly.  We're using what has worked for us for the last 3 years, it may not be the current way of doing things.

**Comment by radfast** [comment] 2017-04-17 01:50
A de-obfuscated distribution version of Galacticraft for Minecraft 1.10.2 is now available.  You can download it directly from our [Jenkins](https://ci.micdoodle8.com/job/Galacticraft-1.10-dev/)   You need three .jars, **GalacticraftCore**, **Galacticraft-Planets** and **MicdoodleCore**, but not the API.

**Comment by VOiDProXy** [comment] 2017-04-17 17:07
Dealing with the same issue as OP here.
I tried the three new jars from your Jenkins and now [the error is different for me](https://hastebin.com/tasunojiji.sql), at least.

> Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/EntityEvolvedZombie

**Comment by radfast** [comment] 2017-04-17 21:38
@VOiDProXy  you are running a server, or you are part of the SpongeForge development team?

The de-obfuscated Galacticraft I posted is only for Java programmers to use in a de-obfuscated development environment.  It's not going to work on a server!!

**Comment by VOiDProXy** [comment] 2017-04-17 22:21
Oh I'm just a meager server owner. I'm Sorry @radfast - I'm still learning the lingo ;)
Thanks for setting me straight, I guess I'm just desperate for some space action but I'll try to stay out of the big kids pool for updates :)

**Comment by radfast** [comment] 2017-04-17 22:39
@silent-mobious  @VOiDProXy   I am attempting a workaround for this in our next Galacticraft 1.10.2 build 67

Should be available in about 30 minutes from now.  No promise that it will fix the Sponge problem, but I hope it will.

Please can you guys take any further discussion of Galacticraft-specific to [this issue discussion](https://github.com/micdoodle8/Galacticraft/issues/2612), not here.

-----

I am happy to continue to help the Sponge guys find a more general solution to this which will work for all Forge mods, but let's get a working solution in Galacticraft first.

**Comment by radfast** [comment] 2017-04-18 01:35
@silent-mobious @VOiDProXy  please try [new Galacticraft build 68](https://ci.micdoodle8.com/job/Galacticraft-1.10/)    Please report any problems with this build at the **Galacticraft** Github issues list, not here.  I'm very interested to know if this fixes the problem.

**Comment by radfast** [comment] 2017-04-18 01:43
@gabizou  My guess is that Sponge is not doing anything special when the vanilla method ```net.minecraft.world.DimensionType.register()``` is called by Forge mods.  If so then Sponge ```WorldManager``` registers only the 3 vanilla ```DimensionType```.  It's likely that would then cause all of a Forge mod's DimensionManager dimension registration calls to fail, if attempting to use any DimensionType except the vanilla 3.

 To test this, on Galacticraft's side I have inserted, by reflection, a call to ```org.spongepowered.common.world.WorldManager.registerDimensionType(id, type)``` at the same time that we call ```DimensionType.register()```.  If these server owners can kindly test now that build 68 for us, then we will know if it works...

**Comment by radfast** [comment] 2017-04-18 16:23
@gabizou 

I found what looks like a bug in Sponge:

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinDimensionType.java#L135-L137

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/world/WorldManager.java#L232-L250


I think it should be coded like this in ```MixinDimensionType```:

    public static DimensionType getById(int dimensionTypeId) {
        return WorldManager.getDimensionTypeByTypeId(dimensionTypeId).orElseThrow(() -> new IllegalArgumentException("Invalid dimension id " + dimensionTypeId));
    }


and in ```WorldManager``` a new method:

    public static Optional<DimensionType> getDimensionTypeByTypeId(int dimensionTypeId) {
        return Optional.ofNullable(dimensionTypeByTypeId.get(dimensionTypeId));
    }

I didn't make a PR for this because I'm not sure which branch(es) you want this on.  I suggest this is needed on **every** branch which has DimensionType, but that's up to you :)

**Comment by radfast** [comment] 2017-04-18 16:56
Also:  in ```WorldManager``` shouldn't this:

    public static int[] getRegisteredDimensionIds() {
        return dimensionTypeByTypeId.keySet().toIntArray();
    }

better be:

    public static int[] getRegisteredDimensionIds() {
        return dimensionTypeByDimensionId.keySet().toIntArray();
    }

**Comment by radfast** [comment] 2017-04-18 18:48
One more thing (semi-related):

The Forge dimensions have ```level_sponge.dat``` containing a NBT tag```dimensionType``` in compound tag ```SpongeData```.  The value of that tag is the name of the DimensionType.  

Sponge ```WorldManager``` reads that tag [here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/world/WorldManager.java#L946-L960).  With our mod, that gives the incorrect DimensionType result on first world load for our dynamically loaded dimensions (even though we registered our DimensionType correctly in _pre-init_).  It gives a DimensionType.NETHER instead of giving our DimensionType!  I didn't find the exact reason, possibly some kind of name string matching error, possibly because the Forge DimensionTypes are not registered in Sponge.getRegistry()?

I'm working around this in our mod by using Java reflection to forcefully put the correct DimensionType into ```WorldManager.dimensionTypeByDimensionId``` in _post-init_.  But I shouldn't have to do this, and what I did won't help other mods.

**Comment by Faithcaio** [comment] 2017-04-18 19:15
@radfast typically target the bleeding branch for PRs

**Comment by gabizou** [comment] 2017-04-18 22:51
Typically target bleeding, but in this case I'd suggest targeting stable-5 for 1.10.2 development. We can always port the change to 1.11.2 by cherrypicking the changes.

**Comment by ryantheleach** [comment] 2017-12-20 05:09
https://github.com/micdoodle8/Galacticraft/issues/2975 and several other issues that have been closed suggest that 

>One more thing (semi-related):

>The Forge dimensions have level_sponge.dat containing a NBT tagdimensionType in compound tag SpongeData. The value of that tag is the name of the DimensionType.

>Sponge WorldManager reads that tag here. With our mod, that gives the incorrect DimensionType result on first world load for our dynamically loaded dimensions (even though we registered our DimensionType correctly in pre-init). It gives a DimensionType.NETHER instead of giving our DimensionType! I didn't find the exact reason, possibly some kind of name string matching error, possibly because the Forge DimensionTypes are not registered in Sponge.getRegistry()?

>I'm working around this in our mod by using Java reflection to forcefully put the correct DimensionType into WorldManager.dimensionTypeByDimensionId in post-init. But I shouldn't have to do this, and what I did won't help other mods.

Is still a problem that may have been missed.

**Comment by MJRLegends** [comment] 2017-12-20 13:42
It seems that https://github.com/SpongePowered/SpongeCommon/blob/8e3fc2f6a4c04d955aad7a83d9e5defe4220b0d2/src/main/java/org/spongepowered/common/world/WorldManager.java#L958 isnt the cause of my pain, it seems to be later on than this method is called. as it seems to return all correct dimension types

**Comment by phit** [comment] 2018-01-01 16:02
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please replay with updated information and I will reopen this issue.

**Closed as completed by phit** 2018-01-01 16:02 UTC
Labels: type: bug, status: accepted, version: 1.10 (u), version: 1.11 (u), system: world

**Comment by MJRLegends** [comment] 2018-01-01 16:03
@phit Wow just wow, i reported it about a month back and still waiting for anyone to help me.....

**Comment by ryantheleach** [comment] 2018-01-03 02:11
@MJRLegends Note the message above doesn't mean this won't be fixed, just that the support terms for 1.10 / 1.11 has ended.

Developers before this cutoff were expected to at least attempt to backport fixes in 1.12 back to 1.10, this cutoff just means that they are no longer expected to do this, and are encouraged to look forwards. This increases the speed of fixes for 1.12 and forward looking development of Sponge, and concentrates developer resources, this is of course, up to the individual developer, it is an open source project after all.

And thus we have stopped tracking issue statuses for 1.10 and 1.11.

That said, if it's reproducible on 1.12, and a fix is made, and shown to be readily backported to 1.10, that doesn't mean someone won't backport it (explicitly: by request, not supporting possible side effects).

We will also readily accept well tested, well written PR's by the community that fix issues on previous versions.

**Comment by MJRLegends** [comment] 2018-01-03 02:13
@ryantheleach Thanks for the reply, this is the latest on my issue Right i added some outputs before this line https://github.com/SpongePowered/SpongeCommon/blob/347bc09f3ad55e316b330c472170a4cd9fd68f97/src/main/java/org/spongepowered/common/world/WorldManager.java#L793 see https://gyazo.com/894e999906fdb4168bbe11b5985c9363 for my output code. From doing this, i got these results https://gist.github.com/MJRLegends/d9806b56751020529eea0a446e8e1668 you can see multiple dimensions being added but at line 133 & 403 it starting removing random ones

**Comment by radfast** [comment] 2018-01-09 19:26
hey guys

@ryantheleach  thanks for re-opening this, I am not aware of the [issue you quoted](https://github.com/SpongePowered/SpongeForge/issues/1429#issuecomment-352966266) being fixed, so I would agree it is likely a probable cause of any "weird" or occasional dimension issues which people are still seeing.

@phit it's hard to understand your approach when moderating this issue, **ryantheleach** re-opened this for discussion only a few days before you closed / moved it!  Although first seen in 1.10 and 1.11, it seems like it is still a current issue including in 1.12 as well!

Together with MJRLegends I will do some testing on live servers in 1.12 and with any luck, one of us will give you updates and more specific 1.12 details.  Might take a few days.

**Comment by radfast** [comment] 2018-01-09 19:43
@MJRLegends  in your logged output, I see at line 133 of your log dimensions -38 and -35 - which were there before - have **disappeared!**  And instead there are now duplicates of dimension 1 and dimension -1 which persist.  Then at line 157, DIM-39 "comes back" but now it is taking the place of DIM-33 which has disappeared.

The total number of worldServers seems correct.  So what looks to have happened in each case is that a ```worldServer``` object is still there, but the entry in ```server.worldServers``` is in the problem cases pointing to the wrong ```worldServer``` object.  This seems like the only way to explain how DIM-39 (rhea) can "come back" at line 157 after it had already disappeared.

I'm wondering if this can be either:

1)  a hashcode collision, if server.worldServers is a HashSet

2) a deep and obscure issue connected with how the JVM optimiser works to in-line code.  Which could explain why you only start seeing the issue if your mod makes heavy use of ```.createWorldFromProperties()```

**Comment by MJRLegends** [comment] 2018-01-09 19:44
@radfast yeah i couldn't find the issue personally i spent ages on it

**Comment by radfast** [comment] 2018-01-09 19:48
@MJRLegends I updated my post with a thought about a possible hashcode collision.  (I'm not in a workspace now to investigate any more deeply)

**Comment by MJRLegends** [comment] 2018-01-09 19:51
@radfast no problem, ive never really done much with spongeforge so i dont know the internals that well to be able to know everything that could be messing this up from my testing i couldnt find much about the cause

**Comment by phit** [comment] 2018-01-09 20:01
@radfast I'm sorry that you feel that way. I don't have the time or energy to go through every single issue that may still be an issue on 1.12. I went through around 100 issues during November/December, that can be tested on 1.12 and checked if it can be reproduced on 1.12. Since Galacticraft didn't have a 1.12 version, this issue was closed alongside all other issues that can't be reproduced on 1.12 on the 1st when Sponge dropped support for older versions. 
I think I closed around 60 issues on the 1st so I didn't really chose to moderate this.. it just falls in the to be closed for now category. 
This still applies:
>If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please reply with updated information and I will reopen this issue.

**Comment by radfast** [comment] 2018-01-09 23:17
It's ok, I understand the pressure you're under with a big project like this.

Although SpongeForge is "downstream" for us, obviously we want everything to work properly in SpongeForge and I am happy to help where I can - you will see PRs I have contributed in the past.  I believe the issues discussed here are still current in 1.12.  As discussed above, together with MJRLegends we will test carefully in 1.12 and post again in a few days as appropriate.

**Comment by ryantheleach** [comment] 2018-01-10 00:06
@radfast The reason I've been commenting on a closed ticket thread, is I believe it's going to follow us to 1.12

Until that can be proven though, it's going to remain closed as per the Sponge teams support policy regarding our support period of 1.10 / 1.11

Other parts of the Sponge implementation have undergone fundamental changes, and we really do need all hands on deck making sure that is running smoothly on 1.12

That said, we will accept PR's and this is on my personal TODO list to do some investigation that would aid a PR.

>Although SpongeForge is "downstream" for us, obviously we want everything to work properly in SpongeForge and I am happy to help where I can - you will see PRs I have contributed in the past. I believe the issues discussed here are still current in 1.12. As discussed above, together with MJRLegends we will test carefully in 1.12 and post again in a few days as appropriate.

I know the issue status doesn't reflect this, but we seriously do value contributions, we are just in a crunch point with 1.12 and the amount of time the team has currently.
  
If you wern't aware, Phit and myself are 'merely' issue managers in this project, bar some small support / moderation duties. Occasionally we will PR something, but they tend to be minor fixes.

**Comment by radfast** [comment] 2018-01-10 02:03
All good.  Lol at 'merely' issue managers, that's a lot of work.

**Comment by MJRLegends** [comment] 2018-02-23 16:38
@phit @ryantheleach any chance https://github.com/SpongePowered/SpongeForge/issues/1429 can be marked as 1.12.2 issue too please as someone has reported it for 1.12.2 here https://github.com/micdoodle8/Galacticraft/issues/3185

**Comment by phit** [comment] 2018-02-23 17:04
make a new issue, that log is completely different from what was reported here

**Comment by MJRLegends** [comment] 2018-02-23 17:59
Its the same issue :/

**Comment by phit** [comment] 2018-02-23 18:10
It's the same issue as the one you've been having yes, but not the same one that this issue started with which was closed [a long time ago](https://github.com/SpongePowered/SpongeForge/issues/1429#event-1063199618). It is also not the same issue, as this was reopened with, which makes this whole issue thread now have 3 separate issues.

It's already way too long for anyone to remotely grasp what is still relevant, make a clean new issue with all the relevant info to reproduce this. It will make everyones job way easier when it comes to getting into fixing this. Feel free to reference this issue in there.

**Comment by MJRLegends** [comment] 2018-02-23 21:42
@phit No problem i will do, i wasn't clear over 
`make a new issue, that log is completely different from what was reported here`
but now you have explained it in details i totally agree thank you for your messages
