### ISSUE TITLE
Crash with Advanced Rocketry and sponge

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2430] opened 2018-09-06 02:44 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3432
- Forge version: 2760
- Java version: Jave 8 
- Operating System: Windows 10

- Plugins/Mods:

**Issue Description**
Happens as soon as the server fully loads then it crashes

https://gist.github.com/TacticalUniverse/777e1daea8ddf205225cf2c26ad03de3

https://github.com/zmaster587/AdvancedRocketry/issues/1391

**Comment by ImMorpheus** [comment] 2018-09-06 18:46
You are using FoamFix which has a compatibility issue with us. Contact them to get the appropriate version of their product that works fine with us.

Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2432

**Closed as completed by ImMorpheus** 2018-09-06 18:46 UTC
Labels: resolution: duplicate, version: 1.12
