### ISSUE TITLE
Customnpcs mod with Sponge

### ISSUE THREAD

**Issue by LornexMc** [SpongePowered/SpongeForge#1451] opened 2017-04-19 21:56 UTC
Hello I have a problem with a mod and sponge. Let me explain if you know the mod customnpcs, that may help you. With this mod, it is possible to teleport to a point to another with a dialog of the npc (it works like a block command) ... But nothing happens and I deleted even all sponge plugins. I thought it was a problem with a plugin). So I tried a command block and it works ... Then I went to see on my solo world (I thought the version of the mod customnpcs was with full bug) but it worked. Do you have a solution to this problem?

Thanks

**Comment by Aaron1011** [comment] 2017-04-22 17:53
What version of Sponge and CustomNPCs are you using?

**Comment by LornexMc** [comment] 2017-04-22 19:13
sponge-forge-1.10.2-2254-5.2.0-BETA-2264
                                  and
                        CustomNPCs_1.10.2

**Comment by LornexMc** [comment] 2017-05-01 21:35
Hello I found something, a kind of permission to use the commands block via the mod customnpcs.It is with a config file that the customnpc mod creates in the config folder.  I changed the value by true, but there is still nothing that works, you think there is another trick that needs to be done? Thank you

![sans titre](https://cloud.githubusercontent.com/assets/27787968/25595920/b04e07b2-2e94-11e7-8c4b-d685e98d0b55.png)

**Comment by phit** [comment] 2017-07-19 18:45
So I barely understand this mod, but I setup two NPC's and made them both transporters. And linked them, teleporting between them worked without any issues. @LornexMc Do you have a log or anything throwing an error or are you simply having issues due to permissions?

I used CustomNPCs_1.10.2(25may17).jar with spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar and didn't change any CustomNPC configs.

**Comment by LornexMc** [comment] 2017-07-19 19:17
Ok thanks i will test these versions if it works with me^^

**Comment by Zidane** [comment] 2017-07-19 19:35
Closing as we cannot reproduce. We'll re-open if we're given a way to re-produce.

**Closed as completed by Zidane** 2017-07-19 19:35 UTC
