### ISSUE TITLE
ftb utilities buttons crash

### ISSUE THREAD

**Issue by MasterSloth1** [SpongePowered/SpongeForge#2047] opened 2018-03-14 01:58 UTC
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2963.jar
- Forge version: 14.23.2.2625
- Java version: 1.8.0_161
- Operating System: Windows 7 version 6.1

please ask me any questions u need
https://cdn.discordapp.com/attachments/321806752985120789/423296484201463808/crash-2018-03-13_20.43.44-server.txt
^^crash report

**Comment by phase** [comment] 2018-03-14 05:46
Gist of the crash report: https://gist.github.com/phase/8993fc9c3373fa1969da91565b2d640f
<sub>(some people don't want to download the file)</sub>

**Comment by gabizou** [comment] 2018-03-14 07:05
It looks like FTBUtilities is having an NPE [here](https://github.com/LatvianModder/FTBUtilities/blob/776814c6e37cb2215d685e5bd84b02f4bcca12e0/src/main/java/com/feed_the_beast/ftbutilities/data/FTBUTeamData.java#L58), maybe get some input from @LatvianModder perhaps? I'm not sure from the stack trace where the world saving is coming from or what phase of the game it is in to cause a world save, but it looks like FTBUtilities has some things not set up correctly at that time.

**Comment by gabizou** [comment] 2018-03-14 07:05
Could there be some more information as to what was going on the server when this happened? Is it reproducible? There's more to the issue template that you didn't fill out.

**Comment by MasterSloth1** [comment] 2018-03-15 04:00
yes its reproducable it happens when clicking the buttons in the E menu (top left corner) ive also messaged the dev of ftb utilities and they said that ftbu is not compatible with sponge atm so thanks ill wait till its updated if there is still a problem ill be back 😄

**Comment by Zidane** [comment] 2018-04-19 05:36
Closing this due to mod incompatibility

**Closed as completed by Zidane** 2018-04-19 05:36 UTC
Labels: type: mod incompatibility, status: more information needed, version: 1.12

**Comment by LatvianModder** [comment] 2018-04-19 13:29
I think this was fixed? not sure tbh
