### ISSUE TITLE
FTBUtilities permissions no longer working after adding sponge to server.

### ISSUE THREAD

**Issue by zach2045** [SpongePowered/SpongeForge#2714] opened 2019-04-26 01:43 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.6-RC3643
- Forge version: 14.23.5.2781
- Java Version: Lastest
- Operating System: Windows 10

We recently installed Sponge on our server running the Enigmatica 2 Expert pack but as soon as we did that the ftbutilities commands such as /home and /enderchest seem to have conflicts and aren't able to run for the players without the mod prefix. (e.g. /ftbutilities:home). I am unsure how to go about fixing this issue so any help on this is much appreciated. Thank you.

**Comment by phit** [comment] 2019-04-26 01:45
Remove the plugins that add conflicting commands or disable those features of those plugins.
I'm closing this as this is a support post and not a bug, but feel free to use this to ask for further help.
Alternatively you can also get help in our forums or support chats https://www.spongepowered.org/chat

**Closed as completed by phit** 2019-04-26 01:45 UTC
Labels: type: support, version: 1.12

**Comment by zach2045** [comment] 2019-04-26 01:49
Well I attempted to add the commands to the 'aliases' portion of the configs however once I reload my server config it says that FTBUtilities it send back a msg saying 'Error occurred while executing command: Plugin FTB Utilities seems to have multiple commands registered as home! This is a programming error!' Is there something I am missing config wise? And if disabling the commands from the other mods is the only option how would I go about doing so? I apologize for my lack on knowledge on this. I am a bit new to Sponge and am having a hard time getting this to work.

**Comment by phit** [comment] 2019-04-26 01:54
you probably wanna start by disabling a few ftbu things that tend to mess things up first
in `config/ftbutilities.cfg` set both of these to false and then restart the server
```
    B:override_chat=false
    B:override_commands=false
```

then to figure out which commands are the ones that conflict you can do `/sponge which home`, that should tell you what is currently the active /home command
from there you can disable the conflicting command usually in the related mod/plugin config file

**Comment by zach2045** [comment] 2019-04-26 02:26
Alright well it looks like that worked for the /home command. I think the enderchest command might be a permission issue because it looks to be from Cyclic Magics and disabling it just removed the command entirely. But thank you so much for all your help. You have seemingly sovled my issue for the time being and I really appreciate it.
