### ISSUE TITLE
Crash with coremod farseek (mod: streams)

### ISSUE THREAD

**Issue by EnderStar** [SpongePowered/SpongeForge#754] opened 2016-07-12 22:38 UTC
https://github.com/delvr/Farseek/blob/f4c446523b1b4883dba16a9ee401b08d013ebb01/src/main/scala/farseek/world/gen/ChunkGeneratorExtensions.scala

crash log: http://pastebin.com/k24nygqA

**Comment by Aaron1011** [comment] 2016-07-13 01:38
@EnderStar:The issue is that Farseek completely replaces `GameRegistry#generateWorld`, which Spoonge needs to inject into.

I'll look into submitting a fix.

**Comment by Aaron1011** [comment] 2016-07-13 01:45
I've opened an issue: https://github.com/delvr/Farseek/issues/16

**Comment by Zidane** [comment] 2016-07-13 20:40
Closing as this isn't a Sponge issue.

**Closed by Zidane** 2016-07-13 20:40 UTC
