### ISSUE TITLE
Server hangs - PhaseTracker PrintUnexpectedBlockChange - 

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [SpongePowered/SpongeForge#2549] opened 2019-01-05 22:53 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3515
- Forge version: 2768
- Java version: V 8 U 191
- Operating System: Win server 2008 r2 enterprise

- Plugins/Mods:
https://pastebin.com/hKTCqQFN

**Issue Description**
Copied in new version of Spongeforge to patch the teleporting/portal bug found here https://github.com/SpongePowered/SpongeForge/issues/2266
Edited config to further prevent server crashing when generating chunks here: https://forums.spongepowered.org/t/server-crash-in-start/26236

Now it has a further issue when anyone attempts to log in. The server does not crash, it just hangs and times with the tick watchdog, you are able to see the sky of the world and clouds however no terrain generates. At the bottom of the debug file you will see what the console is spammed with.
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2729975/debug.log)

Debug log above.

**Comment by phit** [comment] 2019-01-05 23:19
Duplicate of #2526

**Closed as completed by phit** 2019-01-05 23:19 UTC
Labels: resolution: duplicate, version: 1.12

**Comment by nzminecraftDOTcom** [comment] 2019-01-06 01:48
Solved - pre-creating a world made the problem go away :) VoidIslandControl (Stoneblock 2 modpack) was having issues generating an island when new players joined.
