### ISSUE TITLE
Hatchery Mod's Animal Net does not empty and places Infinite mobs.

### ISSUE THREAD

**Issue by Wissi** [SpongePowered/SpongeForge#2392] opened 2018-08-19 20:50 UTC
**I am currently running**
- SpongeForge version:  1.12.2-2705-7.1.0-BETA-3401
- Forge version:  1.12.2 - 14.23.4.2705
- Java version:  1.8.0_181
- Operating System:  Windows 10 (amd64) version 10.0

- Plugins/Mods:
```
Forge.jar
OpenEye-1.12.2-0.8.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3401.jar
minecraft.jar
Baubles-1.12-1.5.2.jar
Chisel-MC1.12.2-0.2.0.31.jar
EnderCore-1.12.2-0.5.37.jar
jei_1.12.2-4.12.0.215.jar
CodeChickenLib-1.12.2-3.2.1.351-universal.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
BrandonsCore-1.12.2-2.4.4.173-universal.jar
CoFHWorld-1.12.2-1.2.0.5-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
Draconic-Evolution-1.12.2-2.3.13.306-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
EnderIO-1.12.2-5.0.31.jar
EnderIO-1.12.2-5.0.31.jar
Mantle-1.12-1.3.2.24.jar
TConstruct-1.12.2-2.10.1.87.jar
extrautils2-1.12-1.8.3.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
AppleSkin-mc1.12-1.0.9.jar
AutoDropper-1.12-2.0.0.jar
Quark-r1.4-125.jar
AutoRegLib-1.3-18.jar
backpacks 1.12.2 - 3.5.2.jar
badwithernocookiereloaded-1.12.2-2.12.jar
CraftTweaker2-1.12-4.1.9.jar
base-1.12.2-3.10.0.jar
bdlib-1.14.3.12-mc1.12.2.jar
BedBugs-1.12-1.0.1.jar
BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar
bonsaitrees-1.0.5-b77.jar
Bookshelf-1.12.2-2.3.553.jar
Botania r1.10-354.jar
Ceramics-1.12-1.3.4.jar
Chameleon-1.12-4.1.3.jar
ChestTransporter-1.12.2-2.8.8.jar
chickens-6.1.0.jar
chiselsandbits-14.21.jar
ShadowMC-1.12-3.8.0.jar
Clipboard-1.12-1.3.0.jar
Clumps-3.1.1.jar
Morpheus-1.12-3.3.2.jar
comforts-1.12.2-1.1.3.jar
CyclopsCore-1.12.2-0.11.8.jar
CommonCapabilities-1.12-1.4.0.jar
CookingForBlockheads_1.12.2-6.4.44.jar
CosmeticArmorReworked-1.12.2-v3.jar
1.12.2-v3
CraftingTweaks_1.12.2-8.1.9.jar
CraftTweaker2-1.12-4.1.9.jar
Cucumber-1.12.2-1.1.1.jar
Cyclic-1.12.2-1.16.9.jar
Hwyla-1.8.26-B41_1.12.2.jar
DarkUtils-1.12.2-1.8.211.jar
DeathCounter-1.12.1-1.0.0.jar
diethopper-1.1.jar
Display-1.2.4.jar
ElevatorMod-1.12.2-1.3.6.jar
EnchantingTable-1.12-1.1.3.jar
endercrop-1.12.2-1.6.0.jar
EnderIO-1.12.2-5.0.31.jar
EnderIO-1.12.2-5.0.31.jar
EnderIO-1.12.2-5.0.31.jar
refinedstorage-1.6.3.jar
EnderIO-1.12.2-5.0.31.jar
EnderIO-1.12.2-5.0.31.jar
EnderIO-1.12.2-5.0.31.jar
EnderIO-1.12.2-5.0.31.jar
MCMultiPart-2.5.1.jar
FTBLib-5.0.2.10.jar
EnderIO-1.12.2-5.0.31.jar
EnderIO-1.12.2-5.0.31.jar
EnderStorage-1.12.2-2.4.5.135-universal.jar
energyconverters_1.12.1-1.0.1.2.jar
valkyrielib-1.12.2-2.0.13a.jar
environmentaltech-1.12.2-2.0.13a.jar
EqualDragons-1.1.jar
etlunar-1.12.2-2.0.13a.jar
exnihilocreatio-1.12-0.2.4.jar
ExCompressum_1.12.2-3.0.24.jar
ExtraBitManipulation-1.12.2-3.3.0.jar
fairylights-2.1.2-1.12.x.jar
FarmingForBlockheads_1.12.2-3.1.21.jar
FastLeafDecay-v14.jar
FastWorkbench-1.12.2-1.5.1.jar
foamfix-0.10.0-1.12.2.jar
Forgelin-1.7.4.jar
ForgeMultipart-1.12.2-2.5.0.71-universal.jar
ForgeMultipart-1.12.2-2.5.0.71-universal.jar
ForgeMultipart-1.12.2-2.5.0.71-universal.jar
FTBUtilities-5.0.2.10.jar
GardenOfGlass.jar
Placebo-1.12.2-1.4.1.jar
Growable Cells-1.12.2-3.1.0.jar
Guide-API-1.12-2.1.7-62.jar
HammerCore-1.12.2-2.0.2.2.jar
hatchery-1.12.2-2.1.2.jar
Headcrumbs-1.12.2-2.0.4.14.jar
HydroGel-1.12.2-1.1.0.jar
llibrary-1.7.15-1.12.2.jar
iceandfire-1.5.2.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.46.831.jar
iskalliumreactors-1.12.2-0.5.16.jar
journeymap-1.12.2-5.5.2.jar
KleeSlabs_1.12.2-5.4.10.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
LaserLevel-1.12.2-2.1.0.19-universal.jar
LoadingProfiler-MC1.12-1.3.jar
LootBags-1.12.2-2.5.7.jar
mcjtylib-1.12-3.0.3.jar
Mekanism-1.12.2-9.4.13.349.jar
MekanismGenerators-1.12.2-9.4.13.349.jar
MekanismTools-1.12.2-9.4.13.349.jar
Guidebook-1.12.2-2.8.2.jar
minecolonies-1.12.2-0.9.91-ALPHA-universal.jar
MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar
missing_pieces-1.12.2-4.3.0.jar
MobGrindingUtils-0.3.11.jar
morechickens-1.12.2-3.2.0.jar
mysticalagriculture-1.12-1.6.12.jar
mysticalagradditions-1.12-1.2.8.jar
NetherPortalFix_1.12.1-5.3.13.jar
NoMoreRecipeConflict-0.11(1.12.2).jar
NotEnoughIDs-1.5.4.2.jar
OpenModsLib-1.12.2-0.11.5.jar
OpenBlocks-1.12.2-1.7.6.jar
OreExcavation-1.4.119.jar
Pam's HarvestCraft 1.12.2w.jar
pamscookables-1.1.jar
Stellar+API-1.12.2-0.4.2.9.jar
Photoptics-1.12.2-0.1.1.1.jar
Ping-1.12.2-1.4.3.jar
plustic-6.5.2.0.jar
PumpkinCarving1.12-1.4.0.jar
RebornCore-1.12.2-3.10.0.332-universal.jar
QuantumStorage-1.12-4.6.1.jar
RandomThings-MC1.12.2-4.2.0.1.jar
redstonepaste-mc1.12-1.7.5.jar
refinedstorageaddons-0.4.1.jar
rftools-1.12-7.55.jar
sampler-1.73.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
SimplyJetpacks2-1.12.2-2.2.7.45.jar
Snad-1.12.1-1.7.09.16a.jar
SolarFluxReborn_1.12.2-4.10r.jar
SoulShards-TOW-1.12-2.7.6-56.jar
Stellar Sky-1.12.2-0.5.3.2.jar
stg-1.12.2-1.2.3.jar
StorageDrawers-1.12.2-5.3.7.jar
tinker_io-1.12.2-release 2.6.1.jar
TinkerToolLeveling-1.12.2-1.0.5.jar
tinyprogressions-1.12.2-3.3.29-Release.jar
torchmaster_1.12.2-1.6.4.62.jar
Translocators-1.12.2-2.5.1.77-universal.jar
TrashSlot_1.12.1-8.4.6.jar
TS2K16-1.2.8.jar
unloader-1.2.0.jar
usefulnullifiers-1.5.0.jar
valkyrielib-1.12.2-2.0.13a.jar
Waddles-1.12.2-0.6.0.jar
WanionLib-1.12.2-1.5.jar
WaterStrainer-1.12-3.2.0.jar
Wawla-1.12.2-2.5.257.jar
witherCrumbs-1.12.2-0.10.jar
woot-1.12.2-1.4.2.jar
worldedit-forge-mc1.12-6.1.8-dist.jar
betterchunkloader-S7.0-3.6.5.jar
griefprevention-1.12.2-4.3.0.621.jar
LagGoggles-SPONGEFORGE-1.12.2-4.1.jar
LuckPerms-Sponge-4.2.33.jar
Nucleus-1.4.3-S7.0-MC1.12.2-plugin.jar
MagiBridge-API7-2.4.5.1 (1).jar
MMCReboot-2.3.0-API-7.jar
RedProtect-7.3.0-b68-Universal.jar
SkyClaims-0.27.2-S7.0-BETA.jar
spark.jar
UniDict-1.12.2-2.6.jar
```

**Issue Description**
"Animal Net" (From Hatchery Mod) in servers not working. Once a mob is captured it will continue to appear as captures in net and can be released over and over, basically infinite mob release. The "Animal Net" will **not** appear as *Empty* once released and is not reusable for any other mob.
Modpack can be found [here](https://minecraft.curseforge.com/projects/skycolonies). Server info is preinstalled.
Unresolved Issues on developers [Github](https://github.com/GenDeathrow/Hatchery/issues/152#issuecomment-384822571).

Thank you very much.

**Comment by phit** [comment] 2018-08-19 20:53
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1982

**Closed as completed by phit** 2018-08-19 20:53 UTC
Labels: resolution: duplicate, version: 1.12
