### ISSUE TITLE
Error when I dying

### ISSUE THREAD

**Issue by Tototi1** [SpongePowered/SpongeForge#2184] opened 2018-05-30 15:01 UTC
**I am currently running**

- SpongeForge version: 2705-7.1.0-BETA-3135
- Forge version: 14.23.4.2705
- Java version: java 8 - 64bits
- Operating System: linux

- Plugins/Mods: ctgui@1.0.0,extendedrenderer@v1.0,creativecoredummy@1.0.0,configmod@v1.0,jei@4.9.1.188,attributefix@1.0.1,mtrm@1.2.2.30,custommainmenu@2.0.8,nei@2.4.1,contenttweaker@1.12.2-4.5.0,schematics@1.12.2.4,redstonepaste@1.7.5,subcommonlib@1.2.0.1,waystones@4.0.42,mcp@9.42,entityspring@2.0.0,ctm@MC1.12-0.2.3.12,zombieawareness@1.12.1-1.11.14,classiccombat@1.0.0,justthetips@1.12-1.0.1.1,forgelin@1.6.0,props@2.6.0,crafttweaker@4.1.8,forge@14.23.4.2705,variedcommodities@1.12.2,weaponlevels@2.3.3,minecraft@1.12.2,stackie@1.6.0.48,ptrmodellib@1.0.2,crafttweakerjei@2.0.2,bma_addon@1.11.2 4.0.3.0,silentlib@2.2.18,creativecore@1.9.9,compatskills@1.1
2.2-1.7.0,corpsecomplex@1.0.2.2,resourceloader@1.5.3,rpginventory@1.12.2,sophisticatedwolves@3.13.2,trapcraft@v2.4.3a,quark@r1.4-123,mapgadgets@@VERSION@,waitingtime@1.0.0,lunatriuscore@1.2.0.42,autoreglib@1.3-16,reskillable@1.12.2-GRADLE:BUILD,moarboats@2.0.0,FML@8.0.99.99,customnpcs@1.12,worldeditcuife2@2.1.2-mf-1.12-14.21.1.2387,coroutil@1.12.1-1.2.11,umbralux@1.12.2,chisel@MC1.12.2-0.2.0.31,tsquare@1.0.7,nbtedit@1.11.2-2.0.2,trade@1.0.4,codechickenlib@3.1.8.341,scalinghealth@1.3.15,extraalchemy@0.3.8.4-release,beastmaster@$version,playerrevive@1.0,base@3.7.2,defaultoptions@9.2.5, spongeapi, sponge, blockyarena, chestrefill, luckperms, minereset, modcontrol, morpheus, nucleus, redprotect, worldedit

**When i died i have an error in the console**

this is a error :
```
[16:47:25] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45-internal]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:284) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3135]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3987) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:3837) ~[oq.class:?]
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3574) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038) ~[aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) ~[oq.class:?]
at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1316) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_180430_e(EntityPlayer.java:1946) ~[aed.class:?]
at net.minecraft.block.Block.func_180658_a(Block.java:821) ~[aow.class:?]
at net.minecraft.entity.Entity.redirect$onBlockFallenUpon$zea000(Entity.java:5985) ~[vg.class:?]
at net.minecraft.entity.Entity.func_184231_a(Entity.java:1130) ~[vg.class:?]
at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:213) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:838) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:583) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[lk.class:?]
at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) ~[lk$a.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-3135]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) ~[hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45-internal]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 7 more
```
and the complete log :
https://gist.github.com/Tototi1/eae97536ba244e4ff60af535e6576bfb

**Comment by XakepSDK** [comment] 2018-05-30 15:12
Pleaseusegisttopostanylogbecauseitsimpossibletoreadthislogwhileitisntproperlyformatted. Thank you.
(Please use gist to post any log because its impossible to read this log while it isn't properly formatted)

**Comment by Tototi1** [comment] 2018-05-30 15:24
I use git, just small code is here.

**Comment by gabizou** [comment] 2018-05-30 15:24
Is it possible to get a reduced mod list to replicate the issue? Or is it just a one off thing that happened once?

Also saying "I died" isn't enough. Did you have any armor on? Items in your inventory? Killed by what (looks like a zombie attacked you)? What did the entity that killed you have equipped?

**Comment by Tototi1** [comment] 2018-05-30 15:28
I think you can use just "scaling healt", "corpse complex" and "player revive". It must be they only ones affecting death.
It happens at every death, i don't have anything and no matter how I die

**Comment by Grauldon** [comment] 2018-06-04 23:47
Which versions of [PlayerRevive](https://minecraft.curseforge.com/projects/playerrevive/files?filter-game-version=2020709689%3A6756) and [InGameConfigManager](https://minecraft.curseforge.com/projects/ingameconfigmanager/files?filter-game-version=2020709689%3A6756) are you using?

**Comment by Tototi1** [comment] 2018-06-05 12:39
Player revive 1.2.13 and creative core 1.9.22, i don't have IGCM

**Comment by Grauldon** [comment] 2018-06-05 23:16
OK Thanks!

I can re-create the PhaseState exception.  It may be take a little time, but I will see if I can determine the cause.

**Comment by Tototi1** [comment] 2018-06-06 09:08
OK Thanks!

**Comment by Aaron1011** [comment] 2018-06-07 02:27
This should be fixed in the latest SpongeForge.

**Closed as completed by Aaron1011** 2018-06-07 02:27 UTC
Labels: system: event, version: 1.12
