### ISSUE TITLE
java.lang.ExceptionInInitializerError on server starting (Sponge 3272)

### ISSUE THREAD

**Issue by yaroslav4167** [SpongePowered/SpongeForge#2283] opened 2018-07-08 14:28 UTC
**I am currently running**

- SpongeForge version: 3272

- Plugins/Mods:
Plugins (22): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, AntiBot for Sponge, BlockyArena, Broadcast, CatClearLag, GameSpleef, GriefPrevention, KeepInventorySponge, LuckPerms, Mirage, Nucleus, Plan, ProtectionPerms, Total Economy, Web-API, WebCmd, WorldEdit, ireport

Mods (83): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AgriCraft, Applied Energistics 2, AutoRegLib, BD Lib, Better Builder's Wands, Better Questing, Better Questing Quest Book, Biomes O' Plenty, Chameleon, Charset, ChickenChunks, Chisel, Chisels & Bits, CodeChicken Lib, Compact Machines 3, ContainerFix, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dense Metals, DiscordIntegration, Dynamic Trees, Dynamic Trees BOP, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnergeticSheep, EventHelper, FoamFix, FoamFixCore, Foamflower, Forestry, Hardcore Questing Mode, Immersive Cables, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, InfinityLib, Integration Foregoing, Inventory Tweaks, Just Enough Buttons, Just Enough Items, MCMultiPart, MTLib, Mod Tweaker, NetherPortalFix, Not Enough Scaffold, OreSpawn, Practical Logistics 2, Quark, Reborn Core, Sampling Performance Profiler, Shadowfacts' Forgelin, SimpleLogic, SonarCore, Standard Expansion, Steve's Carts 2, Storage Drawers, TESLA, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Tiny Progressions, Wireless Crafting Terminal 2, p455w0rd's Library

**Issue Description**
At 3270 this error is not present.

[Crash Report](http://bit.ly/2J8Rn0y)
[Full Server Log](http://bit.ly/2J1N5YN)

**Comment by Aaron1011** [comment] 2018-07-08 17:10
The next build of SpongeForge contains a fix for this issue.

**Closed as completed by Aaron1011** 2018-07-08 17:10 UTC
Labels: type: bug, resolution: duplicate, version: 1.12, system: advancement

**Comment by kashike** [comment] 2018-07-09 06:24
duplicate of #2280
