### ISSUE TITLE
Items disappearing when dropped in inventory

### ISSUE THREAD

**Issue by MrJoki007** [SpongePowered/SpongeForge#704] opened 2016-06-21 20:07 UTC
Im playing FTB Unstable and have a weired bug, when I drop items out of my inventory with the q key on hovering an item when the inventory is open. But insted of dropping the item, it disappears.

I removed all the mods to check if its an mods fault but it wasnt fixed then I removed them.

Modpack: FTB Unstable 1.9.4 Forge version: forge-1.9.4-12.17.0.1965-universal.jar Sponge version: spongeforge-1.9.4-1965-5.0.0-BETA-1472.jar

**Comment by gabizou** [comment] 2016-06-21 20:17
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/803. Will be fixed in the next bump of SpongeCommon.

**Closed by gabizou** 2016-06-21 20:17 UTC
