### ISSUE TITLE
Server won't boot with SpongeForge and Abnormals Core installed

### ISSUE THREAD

**Issue by mja00** [SpongePowered/SpongeForge#3280] opened 2021-12-31 02:22 UTC
**I am currently running**

- SpongeForge version: 1.16.5-36.2.5-8.0.0-RC976
- Forge version: 1.16.5-36.2.22
- Java version: 1.8.0_312
- Operating System: Ubuntu

- Plugins/Mods: SpongeForge, Abnormals Core, Upgrade Aquatic

**Issue Description**

When installing both Abnormals Core and SpongeForge the server won't boot and crashes upon start. No crash report is generated.

[Server log](https://gist.github.com/mja00/2e01d6f0a853af5a3df36b66bd2f3d43) since no crash report is generated.

**Comment by zml2008** [comment] 2021-12-31 02:34
Duplicate of SpongePowered/Sponge#3514

**Closed as completed by zml2008** 2021-12-31 02:34 UTC
Labels: resolution: duplicate
