### ISSUE TITLE
Just Installed SpongeForge and server wont start

### ISSUE THREAD

**Issue by largeorbitalobject** [SpongePowered/SpongeForge#3003] opened 2019-10-13 19:32 UTC
I am currently running the newest 1.12.2 version of sponge forge through my hosted server company. And when I installed I recieved this crash. Heres the log:

[sponge crash.txt](https://github.com/SpongePowered/SpongeForge/files/3722190/sponge.crash.txt)

**Comment by ghost** [comment] 2019-10-14 22:16
There are several errors within your log file. Can you please try some of the following:

- Inside of `/config/foamfix` please set the `B:optimizedBlockPos` variable to `false`
- Also, again, inside of `/config/foamfix` please set the `B:patchChunkSerialization` variable to `false`

Can you also try (if you haven't already) to update to the latest RC of SpongeForge? You can find that here: https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2

If these don't help, try having a look into the `malisiscore-1.12.2-6.5.1` file. It was brought up a few times in your log and **could be a configuration** trying to do something that SpongeForge does not like.

**Comment by largeorbitalobject** [comment] 2019-10-15 08:38
So I did everything you asked except malisiscore, and my server actually started up! Great progress. However there are a ton of errors popping up in console and I can't join the server from my client. All the errors and the log are attached. 

![cant connect](https://user-images.githubusercontent.com/56324351/66815087-84402680-eeec-11e9-99b4-e5a120218d12.png)
![sponge errors1](https://user-images.githubusercontent.com/56324351/66815096-873b1700-eeec-11e9-9fb6-3e0f75c902b4.png)
[sponge errors.txt](https://github.com/SpongePowered/SpongeForge/files/3728182/sponge.errors.txt)

**Comment by largeorbitalobject** [comment] 2019-10-15 09:11
found this post [https://github.com/SpongePowered/SpongeForge/issues/1961](url)
and tried their solution of creating a config. Didn't work, but maybe I did it wrong?

[the config for quarry dim.txt](https://github.com/SpongePowered/SpongeForge/files/3728353/the.config.for.quarry.dim.txt)

**Comment by ghost** [comment] 2019-10-15 21:40
By the looks of things, this could do with a bit more looking into, can you try removing every single mod except for FoamFix, MalisisCore and SpongeForge? See if it boots up fine, if it does, add more and more until it eventually has issues, then narrow it down.

`and tried their solution of creating a config. Didn't work, but maybe I did it wrong?`
Malisis should make a config by itself. #1961 is due to Extra Utilities, not Malisis.

You *could* try to register Malisis as a broken mod and see if that helps. Usually this won't really help as this is more or less used for mods using main server threads(?) but you never know!

`sponge configuration file`
        `broken-mod=true`
        `broken-network-handler-mods=[
malisiscore
]`

**Comment by phit** [comment] 2019-10-16 17:29
post proper logs, otherwise nobody can help you

**Comment by largeorbitalobject** [comment] 2019-10-16 22:07
are the text files i attatched not proper logs?

**Comment by LXGaming** [comment] 2019-10-16 22:53
You need to post your debug.log

However going off the latest.log you already posted it appears there is a conflict involving several mods applying patches regarding vehicle movement in the NetHandlerPlayServer class.

**Comment by largeorbitalobject** [comment] 2019-10-18 08:20
So after removing all the mods and testing one by one I narrowed it down to  OpenTerrainGenerator. After going into the OTG discord and discussing the error i learned that this mod is actually incompatible with sponge. The dev says "if Sponge wants to do stuff that needs explicit support we just simply don't have the time for it." They also added that hopefully sponge can work on compatibility from their end. Sad that I can't use both :(

**Comment by ghost** [comment] 2019-10-18 14:58
Questionable as to why OTG is not compatible with Sponge- should work just like BiomesOPlenty and any other mod.

I am probably incorrect here, but OTG must be doing some wacky stuff to be incompatible, right?

**Comment by JBYoshi** [comment] 2019-10-18 21:40
Based on information from the original log, the error I'm seeing is something with Extra Utilities 2.

```
/**************************************************************************************************************************************************************************/
/* Sponge's tracking system makes a best effort to not throw exceptions randomly                                                                                          */
/* but sometimes it is inevitable. In most cases, something else triggered this                                                                                           */
/* exception and Sponge prevented a crash by catching it. The following stacktrace                                                                                        */
/* can be used to help pinpoint the cause.                                                                                                                                */
/**************************************************************************************************************************************************************************/
/* The PhaseState having an exception: Tick{TileEntity}                                                                                                                   */
/* The PhaseContext:                                                                                                                                                      */
/* org.spongepowered.asm.util.PrettyPrinter@482cd6df                                                                                                                      */
/*                                                                                                                                                                        */
/*  StackTrace :                                                                                                                                                          */
/* java.lang.ClassCastException: com.rwtema.extrautils2.fakeplayer.FakeServerHandler cannot be cast to org.spongepowered.common.bridge.network.NetHandlerPlayServerBridge */
/*     net.minecraft.entity.Entity.handler$onSetPosition$zej000(Entity.java:7473)                                                                                         */
/*     net.minecraft.entity.Entity.setPosition(Entity.java)                                                                                                              */
/*     net.minecraft.entity.Entity.setLocationAndAngles(Entity.java:1423)                                                                                                         */
/*     com.rwtema.extrautils2.fakeplayer.XUFakePlayer.setLocationEdge(XUFakePlayer.java:78)                                                                               */
/*     com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:133)                                                                                                      */
/*     com.rwtema.extrautils2.tile.TileAdvInteractor.update(TileAdvInteractor.java:94)                                                                              */
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)                                                                         */
/*     net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:5228)                                                                                            */
/*     net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zln000(WorldServer.java:5212)                                                                        */
/*     net.minecraft.world.World.updateEntities(World.java:1835)                                                                                                            */
/*     net.minecraft.world.WorldServer.updateEntities(WorldServer.java:4430)                                                                                                */
/*     net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)                                                                                        */
/*     net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)                                                                              */
/*     net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)                                                                                        */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                                                 */
/*     java.lang.Thread.run(Thread.java:748)                                                                                                                              */
/*                                                                                                                                                                        */
/* Minecraft : 1.12.2                                                                                                                                                     */
/* SpongeAPI : 7.1.0-2ad94d346                                                                                                                                            */
/* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                                                         */
/* SpongeForge : 1.12.2-2838-7.1.7-RC3928                                                                                                                                 */
/* Minecraft Forge : 14.23.5.2838                                                                                                                                         */
/**************************************************************************************************************************************************************************/
```

**Comment by LXGaming** [comment] 2019-10-18 21:48
If you read line 606 to 681 you'll see multiple mods and a Sponge Mixin attempting to patch the NetHandlerPlayServer class and failing which is why your seeing the ClassCastException.

**Comment by JBYoshi** [comment] 2019-10-18 22:12
Ah, missed that. Can reproduce with just SpongeForge and OTG.

**Comment by JBYoshi** [comment] 2019-10-18 22:14
Actually, it needs more than just OTG, but I am able to reproduce it.

**Comment by JBYoshi** [comment] 2019-10-18 22:36
This appears to be related to [a Mixin bug](https://github.com/SpongePowered/Mixin/pull/299) which should be fixed in 0.8. However, that won't actually fix the bug. Still need to figure this out.

**Comment by JBYoshi** [comment] 2019-10-18 23:09
I've finished tracing this down. A mod is removing the first call to `new SPacketMoveVehicle()` in `NetHandlerPlayServer.processVehicleMove()`. Because of this, the end of the `@Slice` in `NetHandlerPlayServerMixin_PlayerVehiclesSyncPatch.playerSyncVehicleImpl$onEntitySetRotationIfCancelled` (wow, that's a long name) no longer has the correct ordinal. There's no other `SPacketMoveVehicle` created, so the injection fails. Because of the above Mixin bug, the rest of the class transformations fail, and the class is returned unmodified. That means the `NetHandlerPlayServerBridge` implementation doesn't get provided, but it never has any symptoms until someone joins (or an ExtraUtilities tile entity tries to set up a fake player).

However, Forge [has had the patch in question](https://github.com/MinecraftForge/MinecraftForge/pull/5160) for just over a year. I think the easiest fix for this would be to move the patch to SpongeVanilla and leave the Forge version as-is.

**Comment by largeorbitalobject** [comment] 2019-10-19 20:59
Hey, sorry I'm not great with the technical stuff, I don't really understand what I need to do?

**Comment by ImMorpheus** [comment] 2019-10-19 21:19
> Hey, sorry I'm not great with the technical stuff, I don't really understand what I need to do?

He was explaining the issue, you just need to wait for the PR to get reviewed/tested and merged.
You can then update Sponge to the new version with the above fix.

**Closed as completed** 2019-11-15 23:40 UTC
Labels: type: mod incompatibility, version: 1.12, status: pr pending
