### ISSUE TITLE
Kick player randomly using AoA3

### ISSUE THREAD

**Issue by Zarpyk** [SpongePowered/SpongeForge#3073] opened 2020-02-06 21:55 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.10-RC3992 
- Forge version: 14.23.5.2847
- Java version: --- (Java 8 probably)
- Operating System: ---  (Is only a Minecraft host)

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Advanced Solar Panels, Advent Of Ascension, Akashic Tome, AppleSkin, Attribute Fix, AutoRegLib, B.A.S.E, Backpacks!, Baubles, Bloodmoon, Bookshelf, Bookworm API, Botania, CasinoCraft, Charset, Chest Transporter, Chisel, Chisels & Bits, Chococraft 3, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Comforts, Corail Tombstone, CraftStudio API, CreativeCore, CreativeCoreDummy, Cucumber Library, Decocraft, DiscordIntegration, Dragon Mounts, EmberRoot Zoo, Enchanting Plus, Engineer's Doors, ExplorerCraft, Eyes in the Darkness, FTB Backups, FTB Library, FTB Utilities, Fairy Lights, FastFurnace, FastWorkbench, Fence Jumper, Foamflower, Future MC, Future Versions, FutureMCCore, GottschCore, Harvest, HideNames, Immersive Craft, Immersive Engineering, IndustrialCraft 2, Infernal Mobs, JourneyMap, Just Enough Dimensions, Just Enough Items, LLibrary, LibraryEx, MCMultiPart, Mantle, McJtyLib, McLib, Minecraft Comes Alive, Modern Lights, Morpheus, MrCrayfish's Furniture Mod, Mystical Agradditions, Mystical Agriculture, Nature's Compass, NetherPortalFix, Nightmares, NotEnoughIDs, OnlinePictureFrame, OpenBlocks, OpenModsLib, OpenModsLib Core, Phosphor Lighting Engine, Player Revive, Player Skin Mobs, Potion Core, Quark, Railcraft, RandomPatches, Reap Mod, Redstone Flux, Refined Storage, Roost, Rustic, SecurityCraft, Shadowfacts' Forgelin, Spartan Shields, SpongeForge, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TorchMaster, Treasure2!, TreeCapitator, Uncrafting Table, Unloader, Useful Interior, VanillaFix, Vending, Waila, Water Strainer, Waystones, What Are We Looking At, bspkrsCore, iChunUtil, kinetic anti-cheat
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, FlexibleLogin, LuckPerms, MMCLogger, Nucleus, PlaceholderAPI, Prism, SkinsRestorer, Universe Guard 2, Vanish

**Issue Description**
Kick player randomly
I report the error to the aoa author, but he say it's a sponge error

Error log: https://gist.github.com/GuerreroCraft61/a0ae497c4437ecd4d34f56681ad7f3bc
Error log 2: https://gist.github.com/GuerreroCraft61/bb6bbe289144b81428a32f70c7611f88
Full log (in this log, any player have been kicked): https://gist.github.com/GuerreroCraft61/4de9f4f0bb062eccd72dc5d0cb2bed18

**Comment by GuerreroCraft61** [comment] 2020-02-06 21:59
Other error log: https://gist.github.com/GuerreroCraft61/d0902b016b0c036c7d475a249efcc529

**Comment by ImMorpheus** [comment] 2020-02-06 22:49
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/3071

**Closed as completed by ImMorpheus** 2020-02-06 22:49 UTC
Labels: resolution: duplicate
