### ISSUE TITLE
New sponge crash (1.10.2)

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#1632] opened 2017-07-05 13:32 UTC
Forge Mod Loader version 12.18.3.2316
spongeforge-1.10.2-2281-5.2.0-BETA-2424
Mods: CustomNpcs, Mo'Creatures, CustomMobSpawner, LotsOfFood
Plugins: WorldEdit, RedProtect, EssentialCMDs, ProjectWorlds, ProjectPortals, Twentyticks, PermissionsEx, Holograms

https://hastebin.com/bikidimivo.php

**Comment by kasdo** [comment] 2017-07-06 12:37
1 more crash:
https://hastebin.com/ojozeberil.pl

Help me with this crashes, please

**Comment by kasdo** [comment] 2017-07-07 12:03
+1 more crash: 
Its fun, guys. I already have ~6 crashes
https://hastebin.com/razalarodo.pl

**Comment by gabizou** [comment] 2017-07-07 15:14
3rd crash looks to be a duplicate of https://github.com/SpongePowered/SpongeForge/issues/1534. The other two aren't necessarily helpful without more information. Since the server just ends because of an error, and not an exception, It's not very well possible to figure out just from the log what happened to cause the error, let alone cause what looks like infinite loops or exceptions previously causing the CauseTracker stack to grow excessively. If you can post the actual server logs with some of these crashes, that'd help out.

**Comment by kasdo** [comment] 2017-07-10 15:03
I have new crash:
https://hastebin.com/daligufopu.pl

Log when crashed:
https://hastebin.com/suhadeqibe.md

I dont know what information u need for fix this...

**Comment by dualspiral** [comment] 2017-07-10 16:30
@kasdo I personally suspect that this might be down to a faulty plugin. Something that strikes me is that some of those plugins that you are using have been discontinued or have not seen updates for a while and should be replaced:

* EssentialCmds has been discontinued in favour of my plugin Nucleus, another alternative is UltimateCore
* I believe TwentyTicks is no longer supported, there are other "clear lag" plugins available.
* PermissionsEx has not been updated since January and has been known to cause issues, other options are LuckPerms and PermissionManager.

I would also update to the latest SF version for 1.10.2 - build 2433

If you try changing the plugins, let us know what happens.

(Please note that I do not endorse any plugin that you may choose to use, including those I have involvement with)

**Comment by kasdo** [comment] 2017-07-10 17:46
I replaced plugins and updated SF
But I cant found clear lag plugin, can u throw me ulr?

**Comment by dualspiral** [comment] 2017-07-13 19:26
From #1644 (which is a continuation of this and so deduplicating)

> Forge Mod Loader version 12.18.3.2316
> spongeforge-1.10.2-2281-5.2.0-BETA-2456
> Mods: CustomNpcs, Mo'Creatures, CustomMobSpawner, LotsOfFood
> Plugins: WorldEdit, RedProtect, Nucleus, ProjectWorlds, ProjectPortals, Twentyticks, LuckPerms, > Holograms
>
>    Crash: https://hastebin.com/alacepewuc.php
>    Log: https://hastebin.com/dokewiboxo.md
>
>    Crash: https://hastebin.com/eyutiwosul.php
>    Log: no log, crash 1 min after restart

The error is simply the server watchdog killing it. The server froze, but didn't necessarily crash. Do you have any context as to what you were doing before the server freezes? One of the stack traces has WorldEdit in it, for example, were you using WE each time before it froze?

One other thing you can try is removing mods one at a time, and seeing when the freezing stops. That will at least give us _some_ idea as to what mod or plugin might be causing your issue.

**Comment by kasdo** [comment] 2017-07-13 19:46
Cant delete mods and test. Coz this error crashed only 1 time at a 4-5 days. What about other crash?

**Comment by bloodmc** [comment] 2017-08-20 18:29
Update to latest SF and make a new ticket if it persists.

**Closed as completed by bloodmc** 2017-08-20 18:29 UTC
Labels: status: more information needed
