### ISSUE TITLE
A lot of console spam

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2568] opened 2019-01-21 14:22 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.5-RC3526
- Forge version: forge-1.12.2-14.23.4.2768
- Java version: 1.8.0_162 x64
- Operating System: Linux(Server), Windows7(Client) - x64

- Plugins/Mods:
Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Aquaculture, Biomes O' Plenty, Blockcraftery, Chisel, Chisels & Bits, CustomNPCs, Dynamic Trees, Dynamic Trees BOP, Dynamic Trees PHC, Exotic Birds, Flat Colored Blocks, Inventory Tweaks, Iron Chest, Just Enough Items, MysticalLib, Pam's HarvestCraft, Progressive Bosses, SpongeForge, TickProfiler, Waila;
Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, Boop, CarrotShop, CatClearLag, GriefPrevention, HilPack, ItemChat, LuckPerms, MMCRestrict, Nucleus, Plan, Title Broadcaster, WorldEdit, spark

**Issue Description**
The first case is related to the fact that I am trying to cut down a tree(Dynamic Trees with enabled falling tree mode(http://prntscr.com/ma3q10)) with a nest(Exotic Birds) on it (http://prntscr.com/ma3idh). Looking at the console, I saw this - https://gist.github.com/SSKirillSS/64f32401d08b555e78c4e4454bd0a6c2

The conditions of the second case are not completely known to me yet, but I suppose that spam in console appears after an attempt to change the blocks that are already installed in the world using a chisel(Chisel mod) - https://gist.github.com/SSKirillSS/10c8d5f8784aae31d7bc830b422379e2

I would like to know, can I somehow disable these messages? Too much space they occupy.

**Comment by phit** [comment] 2019-01-21 14:44
First issue is a duplicate of https://github.com/SpongePowered/SpongeForge/issues/2376
second issue is a duplicate of https://github.com/SpongePowered/SpongeForge/issues/1972

**Closed as completed by phit** 2019-01-21 14:44 UTC
Labels: resolution: duplicate, version: 1.12

**Comment by SSKirillSS** [comment] 2019-01-21 15:13
Okay. But could you tell me how to turn off these alerts in the console?

**Comment by phit** [comment] 2019-01-21 15:14
you don't

**Comment by SSKirillSS** [comment] 2019-01-21 15:20
Cruel ... Well, thank you.
