### ISSUE TITLE
Game crash (tile entity activation) when placing IC2 Batbox

### ISSUE THREAD

**Issue by jelaw21** [SpongePowered/SpongeForge#1127] opened 2016-12-20 19:48 UTC
Spongeforge 2000
Forge 1.10.2 - 2171

This is the first instance of this error, when placing a basic bat box in world. 
[crash-2016-12-20_14.36.34-server.txt](https://github.com/SpongePowered/SpongeForge/files/664591/crash-2016-12-20_14.36.34-server.txt)

This is a second instance when placing the next tier batbox, but this one now crashes the server each time that player tries to enter world.
[crash-2016-12-20_14.41.56-server.txt](https://github.com/SpongePowered/SpongeForge/files/664594/crash-2016-12-20_14.41.56-server.txt)

**Comment by ghost** [comment] 2016-12-20 20:05
I think its duplicate of #1122

**Comment by Aaron1011** [comment] 2016-12-20 20:07
@jelaw21: Can you retest with the latest SpongeForge?

**Comment by jelaw21** [comment] 2016-12-20 20:14
What is the latest version?

**Comment by Aaron1011** [comment] 2016-12-20 20:17
`1.10.2-2171-5.1.0-BETA-2003`, which is t he latest build on [the downloads page](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2).

**Comment by jelaw21** [comment] 2016-12-20 20:19
Ok. Will try that in about 30 mins.

**Comment by jelaw21** [comment] 2016-12-20 21:26
That seemed to fix the problem. Thank you.

**Closed as completed** 2016-12-20 21:42 UTC
