### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by flamechair** [SpongePowered/SpongeForge#2193] opened 2018-06-03 04:53 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3136
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: Shared host (not sure)
- Operating System: Shared host (container based server I believe)

- Plugins/Mods: 
> [04:48:49] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Mods (79): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, AbyssalCraft, AbyssalCraft Integration, Aether Legacy, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, AutoRegLib, Baubles, Bookshelf, Chameleon, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Cyclops Core, Dark Utilities, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EvilCraft, EvilCraft-Compat, Extra Utilities 2, Guide-API, Hammer Core, Improvable Skills, Inventory Tweaks, Iron Chest, Just Enough Items, LagGoggles, Less Forgiving Void, McJtyLib, NetherEx, Not Enough Items, OpenBlocks, OpenModsLib, OpenModsLib Core, Quark, RFTools, Redstone Flux, Roguelike Dungeons, Storage Drawers, TOP Addons, TeamLapen Library, Thaumcrafft Inventory Scanning, Thaumcraft, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tree Chopper, UniDict, Unlimited Chisel Works, Vampirism, VampirismIntegrations, WanionLib, WorldEdit

> [04:49:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Plugins (16): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActionBroadcaster, CarrotShop, ClearMob, EconomyLite, GriefPrevention, LuckPerms, MMCRestrict, MagiBridge, Nucleus, ProjectCore, ProjectPortals, Rankup

**Issue Description**
Walking through the world, everytime I get near a village the server crashes with an "Exception ticking world error"

```
java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
	at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:43)
	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:2268)
	at net.minecraft.entity.passive.EntityVillager.func_190672_a(EntityVillager.java:862)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_74893_a(StructureVillagePieces.java:1791)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Church.func_74875_a(StructureVillagePieces.java:379)
	at de.teamlapen.vampirism.world.gen.village.VillagePieceModChurch.func_74875_a(VillagePieceModChurch.java:32)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:603)
	at net.minecraft.world.gen.structure.MapGenVillage.populate(SourceFile:553)
	at org.spongepowered.common.interfaces.world.gen.IFlaggedPopulator.populate(IFlaggedPopulator.java:40)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:244)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bcf000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

https://gist.github.com/iamtpage/6eb92ddb6e723c7f332af16365b73348
https://gist.github.com/iamtpage/24011716e60d4e856735c4261d57fc50
https://gist.github.com/iamtpage/3bdf29b0feee99ef0fbadb44e861b1a5

**Comment by phit** [comment] 2018-06-03 05:00
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2127

**Closed as completed by phit** 2018-06-03 05:00 UTC
Labels: resolution: duplicate, version: 1.12
