### ISSUE TITLE
[1.11] Server closes while creating dimensions

### ISSUE THREAD

**Issue by Nullga** [SpongePowered/SpongeForge#1094] opened 2016-12-09 01:39 UTC
Forge 1.11-13.19.0.2178
Sponge 1.11-2178-6.0.0-BETA-1972
RFTools 1.1x-5.70
RFTools Dimensions 1.1x-4.50
McJty lib 1.1x-2.3.1
CompatLayer - 1.11-0.1.3

Logs
http://pastebin.com/1RkdPTyY
http://pastebin.com/PrzQr22w

Server closes while creating RFTools dimensions. Installed mods are RFT Dims and its dependencies. Dimlets specified to create the dimension are Normal sky, Effect none and Feature non though other elements could be picked randomly by the mod I guess. Anyway can't reproduce on the same version of forge server.

**Comment by gabizou** [comment] 2016-12-09 17:50
Wait, is this reproducible? Or not reproducible?

**Comment by Aaron1011** [comment] 2016-12-09 22:44
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/910. @Zidane needs to decide how we want to handle this.

**Closed as completed by Aaron1011** 2016-12-09 22:44 UTC
