### ISSUE TITLE
Error teleporting cross-dimension

### ISSUE THREAD

**Issue by PoroUsedSnax** [SpongePowered/SpongeForge#2438] opened 2018-09-10 01:28 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3431 (Also tested with 3442)
- Forge version: 1.12.2-14.23.4.2705
- Java version: 1.8.0_181
- Operating System: Linux

- Plugins/Mods: https://gist.github.com/PoroUsedSnax/9ddb81c3fa6561a31d51c578d56545ca

**Issue Description**
When a player teleports cross-dimension (Tested with /spawn and /home from Nucleus and /world teleport from Project Worlds) they are given an error in chat: "Intended to track block entity spawns! Please analyze the current phase context." and they are teleported to a seemingly random location, and begin having other strange issues, as if they are desynced with the server.

Full error from console: https://gist.github.com/PoroUsedSnax/5d1c112e974284d8eb7716688fea6530 This specific one came after using a Nucleus command, but the same thing showed up for the Project Worlds command without the mention of Nucleus of course

**Comment by phit** [comment] 2018-09-14 00:58
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2355

**Closed as completed by phit** 2018-09-14 00:58 UTC
Labels: resolution: duplicate, version: 1.12
