### ISSUE TITLE
Console output Crash when powering Ender IO Farming station

### ISSUE THREAD

**Issue by macman73** [SpongePowered/SpongeForge#1511] opened 2017-05-14 16:35 UTC
I am currently running...

SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2322

Forge version: 12.18.3.2281

Java version: 8

Operating System:

[ x] Linux (Ubuntu, Debian, Fedora, etc)

Plugins/Mods: Various (Invasion Modpack)
Mods supplied in console output

**What is the expected result?**
Endio IO Farming station receives RF power

**What is the current result?**
Tried various methods to supply RF power to the farming station,  the station takes the power from RF supply but it does not get the power in its internal buffers, also deletes any items inserted.
Tried this without spongeforge mod installed and I get expected behaviour.

Console output
https://gist.github.com/macman73/f8c1fab9f4666e043b0f8a98ff1c2058

**Comment by phit** [comment] 2017-05-14 17:23
dupe of #1509

**Closed as completed** 2017-05-14 17:37 UTC
Labels: resolution: duplicate
