### ISSUE TITLE
Can't keep up! 1.10.2 5.0.0-BETA-1726 

### ISSUE THREAD

**Issue by TheMrCaveman** [SpongePowered/SpongeForge#905] opened 2016-09-16 21:03 UTC
What ever version of sponge i use for 1.10.2 it keeps freaking the server out! 

Modpack is ftb unstable 1.10.2  4.2.8

Take sponge away and we never have this problem @ all and server runs whitout issues!

11:15:27Can't keep up! Did the system time change, or is the server overloaded? Running 2108ms behind, skipping 42 tick(s)

22:57:38Can't keep up! Did the system time change, or is the server overloaded? Running 93636ms behind, skipping 1872 tick(s)

What is going on here?

**Comment by kinggoesgaming** [comment] 2016-09-16 21:49
Can you provide a timings report?

**Comment by iKaneki-Ken** [comment] 2016-09-17 01:53
Problem is EnderIO. https://timings.aikar.co/v2/?id=3e15edad1b6f4f4c9b7f678689f695f8&section=lag

**Comment by gabizou** [comment] 2016-09-17 05:55
I would personally attach a profiler to the server and get some more data on what is taking a chunk of processing every tick. I'm not 100% sure as to what could be causing the issue, but it would be very fast at finding out what is the biggest issue and why.

**Comment by TheMrCaveman** [comment] 2016-09-17 20:05
https://timings.aikar.co/v2/?id=f1f32e04b9e540e8980c6381b4e05513

**Comment by ProsperCraft** [comment] 2016-09-21 00:31
Here is my timings and warmroast.

https://github.com/ZeroNoRyouki/BigReactors/issues/20

**Comment by ProsperCraft** [comment] 2016-09-21 00:33
We are running Sponge 1752

**Comment by LotuxPunk** [comment] 2016-09-28 14:31
Any solution ?

**Comment by inklit** [comment] 2016-09-28 19:11
@TheMrCaveman The issue with OpenComputers is a seperate bug, you should open it seperately too.

**Comment by gabizou** [comment] 2016-09-29 16:51
Ok, here's where I'm drawing the line, because mod packs are so immensely huge to test, can you test individual mods that are breaking with sponge and sponge alone? From what I gather, there are issues with OpenComputers + Sponge.

Also, version testing with the latest versions would be much appreciated.

**Comment by inklit** [comment] 2016-09-29 19:41
I've tested OC + Sponge on Sponge 1755 and OpenComputers 1.5.22.6 on 1.8.9.

The issues with robots moving and components occasionally disappearing is unique to Sponge and is most certainly an issue.

However, I haven't personally observed an obvious performance issue with OpenComputers and Sponge, but it could just be because my server is super beefy and I simply have not noticed.

**Comment by ProsperCraft** [comment] 2016-10-03 23:19
Roll foward to Sponge 1779 and Enderio  EnderIO-1.10.2-3.0.1.116_beta.jar 

Modpack- Allthemods

With sponge enabled the server is unplayable, blocks take 3-4 hits to break, and the day doesn't cycle.  Yet the TPS is reported as being fine on some accounts.
Remove sponge and the playability is instantly returned.

https://timings.aikar.co/v2/?id=9d5c8a529afc44cfa510fa5f12cbec91
https://gyazo.com/5575b319f16ac649980b8387447b59f0  <--warmroast

**Comment by LotuxPunk** [comment] 2016-10-04 13:59
@ProsperCraft I've the same trouble on my server

**Comment by Zidane** [comment] 2016-10-04 14:13
@ProsperCraft @LotuxPunk 

I am going to have @gabizou or @Aaron1011 look into why EnderIO is having a fit with us but we need your help by confirming it is SOLELY with EnderIO + SpongeForge that the server starts going to pieces. If you cannot confirm after running SOLELY those two, then keep adding mods till you can. Once you find the mod that when adding it turns into this issue, run that SOLELY with SpongeForge and see if the same issue happens.

It is critical that you do the above. If you fail to perform the steps as I've outlined, I'm afraid our support will stop here.

**Comment by Aaron1011** [comment] 2016-10-04 22:03
@ProsperCraft: Do you have a particularly complex or special conduit setup? My timings report looked perfectly normal after doing some testing.

**Comment by ProsperCraft** [comment] 2016-10-04 22:37
@aaron1011 I have a server full of players.

**Comment by ProsperCraft** [comment] 2016-10-04 22:38
I can provide the map file if that would help.

**Comment by Zidane** [comment] 2016-10-04 22:41
@ProsperCraft 

Please do.

**Comment by dogboy21** [comment] 2016-10-05 00:22
Same issue here.
Timings: https://timings.aikar.co/v2/?id=6a72a17df885449fa46406e13fa16c6c
Warmroast: https://ss.myftb.de/pCOKfnn2.png

**Comment by Aaron1011** [comment] 2016-10-05 03:06
To everyone having this issue - I believe that it's caused by chunk thrasing (in the world I'm using, rftools is doing on it).

Please set `chunk-load`, `chunk-unload`, and `chunk-gc-queue-unload` to `true` in your `global.conf`. If my theory is correct, your logs should be continuously spammed with unload messages for a very small number of chunks (for me, it was just two).

**Comment by Aaron1011** [comment] 2016-10-05 03:08
@bloodmc: This is your area of expertise.

**Comment by dogboy21** [comment] 2016-10-05 22:49
As requested by @Aaron1011:
If anyone want's a map to reproduce the issue, use [this one](https://ss.myftb.de/zAunq_xe.zip). There's a conduit network at -346 73 1218 which triggers the problem. Required mods are IronChest (1.10.2-7.0.9.796), IC2 (2.6.15-ex110), rftools (1.10-5.22) and obviously enderio (1.10.2-3.0.1.107_beta)

**Comment by Aaron1011** [comment] 2016-10-09 03:52
Closed in https://github.com/SpongePowered/SpongeForge/issues/939.

**Closed by Aaron1011** 2016-10-09 03:52 UTC

**Comment by Bebabo10** [comment] 2016-10-09 20:49
With build 5.0.0-BETA-1788
https://gyazo.com/f9497191e70b1528f04ad361fd4a1860
https://timings.aikar.co/v2/?id=3dcf1ba0542c4327b50a63ea3acb143c << running since server start
https://timings.aikar.co/v2/?id=38f24078ac2041b7af0fbaaf9b85f908 << running for a few min 
Still the same issue when adding sponge to a world that has 20 tps the world will start experiencing major lag.

**Comment by Bebabo10** [comment] 2016-10-09 21:01
Also after disabling sponge the tps resumed to its normal level at 20
https://gyazo.com/a3f73dd8035e40dc9f32c537e03ba70e

**Comment by Aaron1011** [comment] 2016-10-09 21:05
@Bebabo10: This is a completely separate issue - the one I fixed had to do with chunk thrashing. Can you please open a new issue for the problem that you're having?

**Comment by Bebabo10** [comment] 2016-10-09 21:08
ok ty
