### ISSUE TITLE
ActuallyAdditions buttons don't work

### ISSUE THREAD

**Issue by mkrtes** [SpongePowered/SpongeForge#1602] opened 2017-06-25 15:25 UTC
There is one strange problem, that I don't know where to write. When I use bungeecord for sponge-server there was a problem with mod ActuallyAdditions. Interface buttons don't work. I run server only with sponge - it works well. Once connect with bungee - buttons not working. Something similar was discussed here: https://github.com/SpongePowered/SpongeForge/issues/1394 
I don't know what to do and who to contact... Sponge, Bungee, ActuallyAdditions?

- Bungee: 11245
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2414
- Forge version: 2281
- Java version: 8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods:

**Comment by phit** [comment] 2017-07-17 21:04
dupe of #1394

**Closed as completed** 2017-07-17 21:05 UTC
