### ISSUE TITLE
Cancelling InteractBlockEvent still places liquids

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#2469] opened 2018-10-07 23:32 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3361 
- Forge version: 2705
- Java version: 1.8.0_101
- Operating System: Windows 10

**Issue Description**
When cancelling a InteractBlockEvent from a bucket, it still places the liquid. Test code: 
```java
    @Listener
    public void onClick(InteractBlockEvent.Secondary.MainHand e, @Root Player p) {
        e.setCancelled(true);
    }
```
When right clicking with a water bucket, the event gets cancelled but water is still placed. This does NOT happen on SpongeVanilla (tested on 1.12.2-7.1.0-BETA-121). **Cancelling InteractBlockEvent.Secondary.OffHand cancels the water bucket place if it's in the main hand. I believe the events are swapped...**

**Comment by gabizou** [comment] 2018-10-09 16:51
This has been fixed in newer SpongeForge builds. Retry with 3477 and report back if it's not working as expected.

Commit https://github.com/SpongePowered/SpongeForge/commit/7414c6ef79c5fdf19e37be27a7825cc8cf9e9514 has most of the fixes pertaining to cancelling interaction events and buckets.

Minor duplicate of https://github.com/SpongePowered/SpongeForge/issues/2385.

**Closed as completed by gabizou** 2018-10-09 16:51 UTC
Labels: resolution: duplicate, version: 1.12
