### ISSUE TITLE
[1.11.2] Error painting blocks with BC Paintbrush

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1551] opened 2017-05-30 23:12 UTC
**I am currently running...**

- SpongeForge version: 1.11.2-2282-7.0.0-BETA-2356
- Forge version: 1.11.2-13.20.0.2304
- Java version: 1.8.0_131
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows Server 2012 R2

- Plugins/Mods: 
Plugins (132): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Aroma1997Core, IvToolkit, OpenComputers (Core), SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, Actually Additions, Ambidextrous, Animania, Just Enough Items, AppleSkin, Aroma1997Core|Helper, Aroma1997sDimension, Astral Sorcery, Morph-o-Tool, Psi, Quark, AutoRegLib, Baubles, BD Lib, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, BuildCraft Lib, BuildCraft, BC Factory, BC Transport, BC Builders, BC Energy, BC Robotics, BC Silicon, Chameleon, Chisel, Chisels & Bits, CodeChicken Lib, IndustrialCraft 2, Compact Solar Arrays, CraftTweaker JEI Support, Crafttweaker, Dark Utilities, Forestry, ElecCore, DeepResonance, Storage Drawers, Drawers & Bits, Dynamic Surroundings, Elevator Mod, Embers, EnderStorage, ShadowMC, Extra Rails, extrautils2, Flat Colored Blocks, FoamFix, Forgelin, MCMultiPart, FTBLib, Funky Locomotion, Gear Swapper, GenDustry, Harvest, Homecraft Mineware, Inventory Tweaks, Iron Chest, JEI Bees, JourneyMap, LLibrary, JurassiCraft, KleeSlabs, Literal Ascension, MalisisCore, MalisisDoors, Malisis Switches, Mantle, The Middle Torch, More Bees, New Age Bee Breeding, Nice, OMLib, Open Modular Passive Defense, OpenComputers, Open Modular Turrets, ShetiPhian-Core, Platforms, Ranged Pumps, Reborn Core, reborncore-MCMultiPart, Refined Storage, Reliquary, RF Lux, RFTools, RFTools Control, Roots 2, Steve's Carts 2, Super Crafting Frame, Tinkers' Construct, The One Probe, Tomb Many Graves, TOP Addons, TorchMaster, Travel Huts, Waddles, The Weirding Gadget, XNet, YABBA, BungeeTabListPlus-SpongeBridge, EconomyLite, NuVotifier, Enjin Minecraft Plugin, GriefPrevention, HuskyCrates, LuckPerms, Market, MMCReboot, MMCRestrict, MultiChat Sponge, Nucleus, PlaceholderAPI, Nucleus Gluon, PayDay, Player Glow, RankUpper, VotifierListener, SleepVote, WorldEdit, denseores

**What is the expected result?**
No exceptions

**What is the current result?**
Exception during phase body when painting blocks using buildcraft

Exception during phase body:
https://gist.github.com/FiveEYZ/240a609d0177c443f481a70500c2f325

fml-server-latest.log:
https://gist.github.com/FiveEYZ/5f0b7827eb7bc1b2eb1762ba8963ccf5

**Comment by FiveEYZ** [comment] 2017-05-31 22:43
this gets generated when u eat from a lunchbox from the mod SpiceOfLife
https://gist.github.com/FiveEYZ/db3f52d73334a59e7b4bd8c9fb112d61

full log:
https://gist.github.com/FiveEYZ/55c02c39551083c31709274d39abb6ec

**Comment by phit** [comment] 2017-12-02 22:56
can't reproduce with
spongeforge-1.12.2-2529-7.0.0-BETA-2753.jar
buildcraft-7.99.12.jar

**Comment by phit** [comment] 2018-01-01 15:49
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:49 UTC
Labels: version: 1.11 (u)
