### ISSUE TITLE
Inventory Phase - IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/SpongeForge#2337] opened 2018-07-23 04:31 UTC
**I am currently running**

- SpongeForge version: SF3333
- Forge version: 2705 
- Link: https://gist.githubusercontent.com/Dockter/1dab2b2ce635522ddc8ce449fea21af0/raw/e7864a6625a9f1db926f3ad3caa906b89359d610/gistfile1.txt

- Feedback:  I was clicking fast within the Recipe Manager on a IronBlock.

**Comment by Faithcaio** [comment] 2018-07-27 17:13
Is this modded? 
You must have somehow clicked on a Slot 49 which does not exist on a normal crafting table.

**Comment by mmis1000** [comment] 2018-07-29 17:02
Also happened to me when using inventory tweaks to send a bunch of clicks that normal user has no way to do that fast.

Part of log: https://pastebin.com/SCsGFwf0
Full log: https://transfer.sh/H5Gn0/latest.log#

I don't know whether it is caused by our plugin modified the inventory out of server thread or not.
But the sponge api itself does not prevent us to do so, so I suspect it is safe to do that.
We are using big chest, so slot 54 should exist, but the error message say there is no slot 54

[our plugin](https://github.com/OKTW-Network/Galaxy/tree/86f3d739d049d2ac294081f3c591071b5b77260c)

And this error should theoretically not happen when using only sponge api, Beacuse `GridInventory::setSlot` itself has a boundary check to prevent us from doing dumb things

**Comment by ryantheleach** [comment] 2018-07-30 02:40
> But the sponge api itself does not prevent us to do so, so I suspect it is safe to do that.

It is never safe to call any Sponge API methods off the main server thread, unless specifically stated so.

If a method was intended to be called async or off the main thread, and it's not documented as such, create an issue about that specific piece of JavaDocs.

>I don't know whether it is caused by our plugin modified the inventory out of server thread or not.

Your plugin is quite large, a hint to where you call it, and the circumstances you call it from would be appreciated.

**Comment by mmis1000** [comment] 2018-07-30 02:56
https://github.com/OKTW-Network/Galaxy/blob/86f3d739d049d2ac294081f3c591071b5b77260c/src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt
https://github.com/OKTW-Network/Galaxy/blob/86f3d739d049d2ac294081f3c591071b5b77260c/src/main/kotlin/one/oktw/galaxy/gui/view/GridGUIView.kt
https://github.com/OKTW-Network/Galaxy/blob/86f3d739d049d2ac294081f3c591071b5b77260c/src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt

There are many call sites to the sponge api through

`launch` and `async` in kotlin creates runtime managed threads, so anything in that block is off main thread.

The `offerPage` function in PageGUI is wrapped in `launch` block, so they are all off main thread.
The ` setSlot(x: Int, y: Int, item: ItemStack?)` in `GridGUIView.kt` called by  `offerPage`  is also wrapped in `launch`, so it is also off main thread. 

So the path to call sponge gui will looks like
1. `PageGUI::clickEvent`(sync) -> `event.isCancelled = true` -> `sponge api rollback items` (sync)
2. `PageGUI::clickEvent`(sync) -[launch]->`PageGUI::offerPage`(async) -> `GridGUIView::clear`(async) -> `GridInventory::inventory.clear`(async)
3. `PageGUI::clickEvent`(sync) -[launch]->`PageGUI::offerPage`(async) -> `GridGUIView::setSlot`(async) -[launch]-> `GridInventory::setSlot`(async)

I just have no idea which one create conflicts with others when click in very short interval.

The purpose to do it in another thread here is that sponge api is unacceptable slow when set skull with player skin on slot, fill a big chest cost about 20~30 ms, do these thing in server thread cause a noticeable lag for everyone in the server 

![](https://cdn.discordapp.com/attachments/276631300390125579/473343756528254976/unknown.png)

Halt every player 30ms when any player click `next page` on the screen is not a reasonable option.

**Comment by ryantheleach** [comment] 2018-07-30 18:00
Performance problems in the API implementation is the real issue then. And I believe @Aaron1011 has taken some steps to workaround / mitigate it recently. https://github.com/SpongePowered/SpongeAPI/commit/a3431307f06996321489b69664b16202e8806042

To my limited knowledge, you should not be modifying inventories async, end of story.

Loading and preparing heads / game profiles might be ok async (as I don't believe the implementation tracks item changes (yet! could change?)), and caching those if they are reused may be one way around it. 

As long as you don't modify the inventory off the main thread.

Anyway, it seems to me at least that this is probably unrelated to Dockters original issue, which is directly talking about the recipe books. So I'd advise opening a ticket against SpongeCommon linking to this, and including the information you had above, to address the performance issue only. I suspect this API may change in API 8 in regards to heads if it's not already changed by aarons work above. If the API needs to change, a ticket against SpongeAPI should be opened.

**Comment by mmis1000** [comment] 2018-07-30 18:42
Just tried to reschedule every action related to inventory to server thread.
[commit](https://github.com/mmis1000/Galaxy/commit/e703844493053e4e2bf96c0ef6253fd23bda20ec)
But it still unfortunately crash when sort with inventory tweak.
So off main thread problebly not the real cause of that crash...
The race must happen inside somewhere in the sponge itself
And probably the same issue.

**Comment by ryantheleach** [comment] 2018-07-30 19:47
> Feedback: I was clicking fast within the Recipe Manager on a IronBlock.

> https://github.com/Inventory-Tweaks/inventory-tweaks/issues

Looking at Inventory-tweaks issue tracker, it's possible that the combined source of these is Sponge choking on (something) when many inventory packets is sent.

The issue tracker of Inventory-Tweaks shows that Spigot tends to just boot people who send packets that quickly.

So the easiest way to replicate this, is probably to use "Z style sorting" on Inventory Tweaks, only on the client. (After reading various Inventory Tweaks issues)

**Comment by mmis1000** [comment] 2018-07-31 03:46
I seems it is a regression bug.
I test it with a old build 3322, the crash does not happen. (there is no log spam and error messages) (the user opening the inventory and click sort may still get kicked due to packet burst or server lag)
But, with 3357 we are using, it does log spam and kick every user from server 
I am trying to bisect it to find the exact commit that cause the crash.

3322 works
3357 crash
3330 crash
3325 works
3328 works
(3329 does not exist)

so the crash is caused by 3330 (?)

**Comment by Faithcaio** [comment] 2018-07-31 06:58
Inventory Events were not fired when there was no inventory change. Build 3030 fixed that issue.

Apparantly packets are sent with an invalid index.
Maybe I can just ignore those ...

**Comment by mmis1000** [comment] 2018-08-01 10:15
The problem for this is, it creates a lot of log spam, and stuck the server due to stdio to write a giant log file, the error itself does not actually make the server down, but the message log to file does.

**Comment by Faithcaio** [comment] 2018-08-05 09:17
Latest should now only print warnings instead of full exceptions.

I'll have to investigate further what happens without Sponge when packets have invalid slotindex.

**Comment by mmis1000** [comment] 2018-08-05 09:37
Is the log rate being limited?  
Or it is likely still going to kick players due to log spam.

**Comment by Faithcaio** [comment] 2018-08-05 09:45
No limit. I'd like to really fix it. It should give me some hopefully useful output now.

**Comment by phit** [comment] 2018-09-14 01:29
@mmis1000 did you get any logs for this?

**Comment by mmis1000** [comment] 2018-09-14 04:25
@phit 
here is 
sponge version: spongeforge-1.12.2-2705-7.1.0-BETA-3415.jar
log: https://transfer.sh/Ap9x0/latest.log

**Comment by Faithcaio** [comment] 2018-09-14 07:25
well thats useless.. Apparantly message formatting is done differently here

**Comment by mmis1000** [comment] 2018-09-14 10:30
@Faithcaio 
I remember that there is pr in sponge forge or sponge common that fix the formating issue here, not sure if it is merged.
I will try to upgrade to latest and try again later.

**Comment by Faithcaio** [comment] 2018-09-14 10:50
https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinContainer.java#L560 still there.
Dont remember seeing smth to fix it.

**Comment by mmis1000** [comment] 2018-09-14 13:13
@Faithcaio 
https://github.com/SpongePowered/SpongeCommon/issues/2090

Turns out issue opened 12 days ago but no PR yet.

**Comment by Faithcaio** [comment] 2018-09-14 15:26
now again with the correct formatting

**Comment by mmis1000** [comment] 2018-09-14 16:00
@Faithcaio 
Here is
https://transfer.sh/TXOoK/latest.log#
And I may found the root cause in my case
I open the hopper(5 Slot) after I clicked one of the item in Big Chest(54 slot)

And some race condition happened, cause sponge(or maybe vanilla) try to find slot 51 in hopper(which is obviously out of index)

Same situation may be applied to some containers that switch from a bigger one to smaller one.

Maybe this can be fixed by verify container id of the container player opened against window id in packet.
And abort those bad packets.

Vanilla actually aborts these bad packets, but sponge seems didn't do that

**Comment by Faithcaio** [comment] 2018-09-14 18:33
Thanks didn't think about that when I added the empty Transaction when the event had none.
So should be fixed with latest then...

**Comment by mmis1000** [comment] 2018-09-14 19:01
@Faithcaio confirmed, issue is gone for me in latest sponge forge version (3445)

**Closed as completed** 2018-09-14 19:03 UTC
Labels: system: inventory, status: more information needed, version: 1.12
