### ISSUE TITLE
Sponge Error w/ CoFH Mods

### ISSUE THREAD

**Issue by ukdyl94** [SpongePowered/SpongeForge#1620] opened 2017-07-02 05:05 UTC
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2422
- Forge version: forge-1.10.2-12.18.3.2281-universal
- Java version: Java 8 v131
- Operating System: 

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: Plugins (247): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Energistics 2 Core, Aroma1997Core, OpenComputers (Core), CoFH ASM, FoamFixCore, ccl-entityhook, Just Enough Items, AbyssalC
raft, AbyssalCraft Heads, Mantle, Tinkers' Construct, AbyssalCraft Integration, CoFH Core, Actually Additions, Forge Endertech, Advanced Chimneys, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Advanced Swords, Applied Energistics 2, BD Lib, AE2 Stuff, Infi
nityLib, AgriCraft, Baubles, Botania, Akashic Tome, Biomes O' Plenty, animalium, Animania, AppleCore, AppleSkin, Aquaculture, ArchitectureCraft, TheDragonLib, ArmorPlus, Aroma1997Core|Helper, Aroma1997's Dimensional World, Ars Magica 2, AnimationAPI, AutoPackager, Morph-
o-Tool, Psi, Quark, AutoRegLib, CodeChicken Lib, Avaritia, Bagginses, Baubles Stuff, Bed Bugs, Better Builder's Wands, BiblioCraft, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, Brandon's Core, Craftable Elytra Mod - MCV 1.10.2, Ceramics, Chamele
on, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Cooking for Blockheads, CosmeticArmorReworked, Craftable Saddles, Craftable Name Tags, Crafting Tweaks, CraftTweaker JEI Support, MineTweaker 3, Cross
roads, Cyclops Core, Dark Utilities, PTRModelLib, Decocraft, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, Storage Drawers, Drawers & Bits, Elevator Mod, Embers, EnderBags, EnderCore, Ender IO, Ender-Rift, ShetiPhian-Core, EnderTanks
, Ender Zoo, End Metals, Engineers Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, EvilCraft, Expandable Backpacks, Extra Golems, Extra Utilities 2, Zero CORE, Extreme Reactors, Fast Leave Decay, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' F
orgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, FTBUtilities, Funky Locomotion, Funnels, GenDustry, Pressure Pipes, Advanced Generators, Gravestone Mod, Gravitation Suite, Hammer Core, HelpFixer, Hopper Ducts, The One Probe, Immersive
 Engineering, Immersive Petroleum, LunatriusCore, InGame Info XML, Interaction Wheel, Inventory Tweaks, Iron Chest, JEI Bees, JourneyMap, KleeSlabs, Long Fall Boots, Loot Bags, MalisisCore, MalisisDoors, Mekanism, MekanismGenerators, MekanismTools, MmmMmmMmmMmm, mob_grin
ding_utils, MTLib, Mod Tweaker, numina, MachineMuse's Modular Powersuits, Railcraft, RebornCore, TechReborn, More Bees, Morpheus, ModPack Utilities, ModPack Basic Tools, MrTJPCore, Multi-Storage, Mystical Agriculture, Natura, Nether Metals, Nether Portal Fix, NotEnoughID
s, OMLib, Open Glider, Open Modular Turrets, Ore Spawn, p455w0rd's Library, Pam's HarvestCraft, Progressive Automation, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed
Exploration, QuantumStorage, Random Things, Ranged Pumps, reborncore-MCMultiPart, Thermal Foundation, Thermal Expansion, Redstone Arsenal, Refined Relocation, Refined Storage, Reliquary, RFTools, RFTools Control, Roguelike Dungeons, Roots, Realistic Terrain Generation, S
ignals, Simply Jetpacks 2, Sleeping Bag, Solar Flux Reborn, Soul Shards - The Old Ways, Steve's Carts 2, Steve's Factory Manager, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, Thermal Dynamics, Tinkers Tool Leveling, TOP Addons, TorchMaster, Transloc
ator, Useful Nullifiers, WanionLib, Wireless Crafting Terminal 2, Woot, WirelessRedstone-CBE, XNet, Boop, Broadcast, CarrotShop, CommandSigns, CrazyFeetSponge, EconomyLite, NuVotifier, Enjin Minecraft Plugin, FoxCore, FoxGuard, Holograms, LuckPerms, MMCReboot, Nucleus, P
layerShopsRPG, Prism, Project Core, SeriousVote, SpongyCord, Stack Ban, Wallet Drop, WorldEdit, UniDict

**What is the expected result?**

**What is the current result?**
The current result is that when trying to load the server with the updated versions of CoFH Mods listed below. I get the error listed inside of the log file below.

-CoFHCore-1.10.2-4.1.9.13-universal
-ThermalDynamics-1.10.2-2.0.9.12-universal
-ThermalExpansion-1.10.2-5.1.8.11-universal
-ThermalFoundation-1.10.2-2.1.4.6-universal
-RedstoneArsenal-1.10.2-2.0.6.3-universal

https://gist.github.com/ukdyl94/d4a97c5bf0d146cdab80777eef8f0a70

**Comment by ryantheleach** [comment] 2017-07-02 11:23
Duplicate of: https://github.com/SpongePowered/SpongeForge/issues/1604

**Closed as completed** 2017-07-02 14:50 UTC
Labels: resolution: duplicate
