### ISSUE TITLE
Forge wont load my plugin, everything is fine on spongevanilla

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeForge#2512] opened 2018-11-14 22:29 UTC
**I am currently running**
- SpongeForge version: 1.12.2 - 14.23.5.2768
- Forge version: forge-1.12.2-14.23.5.2768
- Java version: 1.8.0_191
- Operating System: 
Windows 10 & sponge vanilla - works
Windows 10 & sponge forge - works
linux centos 7 & sponge forge - exception, see the first log
linux centos 7 & sponge vanilla - works

when running centos 7, sponge forge wont load my plugin nt-core there are no exceptions in the console or debug log which would tell me why it wont initialize the plugin nt-core. Somehow its classes are not even added to the classpath. 

Then the ntrpg plugin is listening to one of events, which class is defined in the ntcore plugin. A classdefnotfound exception is thrown one ntrpg plugin is being initialized. 

What are differences in modloading between sponge forge and sponge vanilla? Could anybody tell me why the plugin loads fine on sponge vanilla but sponge forge wont even add it to the classpath.

- Plugins/Mods: 
https://ore.spongepowered.org/NeumimTo/NT-Core
https://ore.spongepowered.org/NeumimTo/NT-Rpg

log when running sponge forge 
https://hastebin.com/odedohuhox.md
debug log sponge forge 
https://hastebin.com/wuwudiyifi.sql

log when running sponge vanilla (same machine, same setup, same plugins) everything is ok
https://hastebin.com/uyugugotuk.sql

Yes the server is running under root, yes im aware of that, and yes i know i should not be doing that

**Comment by NeumimTo** [comment] 2018-11-25 17:01
Bump

**Comment by phit** [comment] 2018-11-25 17:12
looks pretty simple, nt-rpg is loaded before ntcore, since forge loads alphabetically using the filename order

```
[23:19:45] [Server thread/TRACE] [FML]: Mod sorting completed successfully
[23:19:45] [Server thread/DEBUG] [FML]: Mod sorting data
[23:19:45] [Server thread/DEBUG] [FML]:         luckperms(LuckPerms:4.3.8): LuckPerms-Sponge-4.3.8.jar ()
[23:19:45] [Server thread/DEBUG] [FML]:         nt-rpg(NT-RPG:1.0.12-RC-1): NT-RPG-1.0.12-RC-1.jar ()
[23:19:45] [Server thread/DEBUG] [FML]:         nt-core(NT-Core:1.13-SNAPSHOT-6): NTCore-1.13-SNAPSHOT-6-shaded.jar ()
[23:19:45] [Server thread/DEBUG] [FML]:         nucleus(Nucleus:1.6.3-S7.1): Nucleus-1.6.3-S7.1-MC1.12.2-plugin.jar ()
```

**Comment by phit** [comment] 2018-11-25 17:16
mh looking at it some more
<https://github.com/Sponge-RPG-dev/NT-RPG/blob/develop/Plugin/src/main/java/cz/neumimto/rpg/NtRpgPlugin.java#L185>
looks like this may not be passed to forge

**Comment by NeumimTo** [comment] 2018-11-25 17:29
interesting catch, i havent noticed that.

**Comment by NeumimTo** [comment] 2018-11-25 17:32
But is there a reason why it is attempting to initialize the plugin (nt-rpg) before it adds all jars within the mods folder to the classpath?

**Comment by phit** [comment] 2018-11-25 17:48
to my knowledge this is not how the loading works, mods are sorted and then loaded and constructed (and added to the modclassloader) one by one
non mod jars will be injected separately before that

https://github.com/MinecraftForge/MinecraftForge/blob/5771c8ffea9a4b31043358a26ec456218a724ac0/src/main/java/net/minecraftforge/fml/common/Loader.java#L557

**Comment by NeumimTo** [comment] 2018-11-26 20:10
@phit is there anything else on my side how to fix this issue?

If i rename the nt-core jar so it will be loaded first it will sometimes work and sometimes it wont, this quite strage.

If that wont work ill get during the server loading 

```
Caused by: java.lang.LinkageError: loader (instance of  org/spongepowered/common/event/gen/DefineableClassLoader): attempted  duplicate class definition for name: "org/spongepowered/common/event/filters/RegisterFilter_NtRpgPlugin_postInit16"
```

i would say that the chances are 50:50...

logs:
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2617157/debug.log)
:
[crash-2018-11-26_21.07.31-server.txt](https://github.com/SpongePowered/SpongeForge/files/2617154/crash-2018-11-26_21.07.31-server.txt)

**Comment by phit** [comment] 2018-11-26 20:24
sorry, I don't understand this any more than what I already said, someone of the dev team probably has a better idea

**Comment by NeumimTo** [comment] 2018-11-29 20:00
So. 
If i put this code 
https://gist.github.com/XakepSDK/436534bc52916894a065bf184e79e4b7
Into static initializer into NtCore plugin everything starts working.

**Comment by ryantheleach** [comment] 2018-11-29 23:22
@NeumimTo where is the method postInit16 defined in class NtRpgPlugin? I'm unable to see it in your source.

Finding the signature and name of that method may aid debugging.

**Comment by NeumimTo** [comment] 2018-11-30 08:30
@ryantheleach Theres no such method called "postinit16" anywhere in my plugin.
I tought sponge generated the class on its own `org/spongepowered/common/event/filters/RegisterFilter_NtRpgPlugin_postInit16`

At least its in the sponge package as far i can tell. My plugin has no classes within the package  "org.spongepowered"

**Comment by kashike** [comment] 2018-11-30 08:36
Your method would be `postInit` - we add the number to the end.

**Comment by XakepSDK** [comment] 2018-11-30 08:54
You should debug classloading, if my solution helps.

**Comment by NeumimTo** [comment] 2018-11-30 09:46
@kashike Theres indeed multiple methods called postinit.

All of them can be found here
https://github.com/Sponge-RPG-dev/NT-RPG/blob/develop/Plugin/src/main/java/cz/neumimto/rpg/NtRpgPlugin.java#L379-L448 

@XakepSDK unfortunately i do not know (sponge)forge internals, no idea where to start.

**Comment by XakepSDK** [comment] 2018-11-30 09:55
Compile this repo by yourself, replace server-packaged version by your version.
https://github.com/Mojang/LegacyLauncher
Debug every place, where `invalidClasses.add` and `negativeResourceCache.add` called.
https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java

**Comment by dualspiral** [comment] 2018-11-30 10:26
This solution didn't really fix anything but allowing NT-Core to load, NT-RPG still will have failed before it, Forge/FML doesn't go back to try mods again after they failed. As an _actual_ workaround, you could put any method that has a signature that contains a NT-Core class into a second class that is loaded during pre-init, all plugins will be constructed at this phase so any class loading will succeed.

Note this is a workaround, and I'm sure everyone wants to see this work properly.

> You should debug classloading, if my solution helps.

Given that it's the mod sorting order that's the problem as phit suggested, debugging how the class loader works isn't going to help. Of _course_ clearing the negative/invalid class cache is going allow some things to load in the wrong order. It doesn't mean it's the right thing to do.

[In Forge, when it's a mod's turn to be constructed, the jar file is added to the classpath via the class loader, the main mod/plugin class is loaded, then an instance is created, with various bits and bobs inbetween, in the same function.](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/FMLModContainer.java#L505-L611). [This is emulated by SpongeForge too, though in a simpler fashion.](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/plugin/SpongeModPluginContainer.java#L268-L293) So, if NT-RPG's main class depends on NT-Core classes, and NT-RPG is loaded first, then NT-RPG _will_ fail, because the classes in NT-Core are not yet on the classpath and so marks them as invalid when trying to find them, as well as not constructing the RPG mod. These failed class names are then added to an invalid class cache, so when NT-Core comes up, the classloader recognises some of the classes the main class (which isn't referenced by NT-RPG's main class) as already invalid, so throws an exception straight away.

What part of the "fix" did was clear the invalid class cache. I would recommend **not** messing with the internals, but the "fix" is unsurprising in why it worked for NT-Core. It's working as intended, it doesn't need debugging. All you're doing is allowing NT-Core to load after NT-RPG has failed.

The real bug is that either Forge's depedency sorting algorithm is a bit off, or Sponge isn't properly passing the dependecy information as phit suggested - there's probably a problem with the latter. Your time would be better spent debugging these. I had a quick look the other day, but each time the dependencies were sorted correctly and so I couldn't trace anything.

---

Forge mod sorting is found at https://github.com/MinecraftForge/MinecraftForge/tree/1.12.x/src/main/java/net/minecraftforge/fml/common/toposort

Sponge dependency metadata is read at https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/plugin/SpongeModPluginContainer.java#L135 - that might be a good place to start (but I haven't spent time looking at that).

**Comment by phit** [comment] 2018-12-03 13:46
@NeumimTo can you try adding [`"useDependencyInformation": true`](https://github.com/MinecraftForge/FML/wiki/FML-mod-information-file#property-documentation) to your `mcmod.info`

**Comment by dualspiral** [comment] 2020-06-09 09:59
The workaround is there. Closing.

**Closed as completed by dualspiral** 2020-06-09 09:59 UTC
Labels: type: bug, status: needs testing, version: 1.12
