### ISSUE TITLE
Sponge breaks lycanitesmobs roc functionality

### ISSUE THREAD

**Issue by Pangamma** [SpongePowered/SpongeForge#3118] opened 2020-03-31 07:49 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.10    and   1.12.2-2838-7.2.0
- Forge version: forge-1.12.2-14.23.5.2838
- Java version: 8
- Operating System: Debian or something, idk

- Plugins/Mods: 
lycanitesmobs-1.12.2-2.0.7.0-aberrant14.jar
_spongeforge-1.12.2-2838-7.1.10.jar

**Issue Description**
Literally add this mod and this mod to a forge 1.12.2 server. 
spongeforge-1.12.2-2838-7.2.1   also https://nephrite.uk/storage/app/media/lycanitesmobs-1.12.2-2.0.7.0-aberrant12.jar

That's it. Those are the only two mods. Then spawn a roc and tame it using avian treats. Next, slap a saddle on it. You can go up with spacebar. Shift will lock everything to where you cannot move. If I were to remove sponge this issue would go away.

https://gist.github.com/Pangamma/8e9757c539f3a12d14a8890594bf16d1

**Comment by KorewaLidesu** [comment] 2020-04-03 12:41
Have you try asking mod' author for support?

**Comment by Pangamma** [comment] 2020-04-03 18:16
@madokaorimura I have. " Yeah sponge compatibility is a tough one as it's more down to forge and sponge to work things out"

**Comment by clienthax** [comment] 2020-04-26 16:26
https://gitlab.com/Lycanite/LycanitesMobs/-/issues/739

**Comment by clienthax** [comment] 2020-04-26 17:22
Closing as duplicate of https://github.com/SpongePowered/SpongeForge/issues/3133 (even as it came first :'))

**Closed as completed** 2020-04-26 17:23 UTC
Labels: resolution: duplicate
