### ISSUE TITLE
[1.11.2] Baubles Menu Button Voids Items

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#1563] opened 2017-06-03 21:27 UTC
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2282-7.0.0-BETA-2356
- Forge version: forge-1.11.2-13.20.0.2299-universal
- Java version: 1.8.0_131
- Operating System: 

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [x] Windows

- Plugins/Mods:
```Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Potion Core Coremod, SpongeAPI, SpongeForge, FoamFixCore, Actually Additions, Akashic Tome, Baubles, extrautils2, AngelRing 2 Bauble, Alternate Terrain Generation, Psi, Quark, Skillable, AutoRegLib, Avaritia, BetterBedrockGen, BD Lib, Better Achievements, Better Builder's Wands, Better Than Mending, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, SonarCore, Calculator, Cavern, Chameleon, Chest Transporter, Chisel, Chisels & Bits, Compact Machines 2, Cooking for Blockheads, CosmeticArmorReworked, CraftTweaker JEI Support, Just Enough Items, Crafttweaker, Custom Achievements, Cyberware, Dark Utilities, Forestry, ElecCore, DeepResonance, Disenchanter, Elevator Mod, Embers, Lapis Stays in the Enchanting Table, ShetiPhian-Core, EnderTanks, Valkyrie Lib, Environmental Tech, ET Lunar, Extra Bit Manipulation, Fast Leaf Decay, FoamFix, GenDustry, Advanced Generators, Harvest, TESLA, Tesla Core Lib, Industrial Foregoing, MTLib, InitialInventory, Inventory Tweaks, Iron Chest, JEI Bees, JourneyMap, LootTweaker, Mantle, Mending Fix, MmmMmmMmmMmm, MNU, Modular Machines, Morpheus, Terraqueous, Multi-Storage, Mysterious Miscellany, Natura, NetherPortalFix, No Mob Spawning on Trees, Not Enough Wands, NuclearCraft, Ore Core, Potion Core, Quality Tools, Random Things, Reborn Core, reborncore-MCMultiPart, RefinedRelocation, Refined Storage, Reliquary, Restricted Portals, RF Lux, RFTools, RFTools Control, Rocky Core, Roots 2, Rustic, Silent Lib, Scaling Health, Scannable, SimpleVoidWorld, Steve's Carts 2, Storage Drawers, Substratum, Super Multi-Drills, Tinkers' Construct, The One Probe, Tiny Progressions, Tomb Many Graves, TOP Addons, TorchMaster, ViesCraft, WanionLib, The Weirding Gadget, Wither Skeleton Tweaks, Woot, WorldEdit, XNet, BadgeUp Sponge Client, Discord Bridge, EconomyLite, GriefPrevention, LuckPerms, Nucleus, SpongyCord, denseores, UniDict```

**What is the expected result?**
In a regular Forge environment with the same mods, if you click on the baubles menu with an item stack on your mouse it will be thrown out on the ground.

**What is the current result?**
In a Sponge Forge environment, if you click on the baubles menu with an item stack on your mouse it will be voided.

**Comment by FiveEYZ** [comment] 2017-06-10 02:05
is not happening on:
forge-1.11.2-13.20.0.2310-universal
spongeforge-1.11.2-2282-6.1.0-BETA-2368
Baubles-1.11-1.4.5

Baubles menu opens and the items on the mouse falls to the ground

**Comment by JBYoshi** [comment] 2017-06-10 12:13
Then is this resolved?

**Comment by FiveEYZ** [comment] 2017-06-10 15:05
i would say its not resolved, tested this using only Baubles and SpongeForge on a test server, this bug happens... so why is it working properly on the modpack im running? this confuses me

**Comment by Zidane** [comment] 2017-06-15 15:56
You're confusing me.

First you say it doesn't happen with just Forge + SF + Baubles then you say it does but it doesn't happen in the modpack yet the issue OP says it DOES happen in the modpack.

Please clarify..

**Comment by FiveEYZ** [comment] 2017-06-15 16:09
yes, im sorry should have clarified that in my first comment i was using A modpack, and those are the versions of the mods in that pack. 

later (hence my second comment) i tested the affected mods on a test server and got same result as OP

sorry for confusion

**Comment by phit** [comment] 2017-07-20 02:50
dupe of #1320

**Closed as completed** 2017-07-20 02:56 UTC
