### ISSUE TITLE
Are there any issues with ender eyes?

### ISSUE THREAD

**Issue by Sunconure11** [SpongePowered/SpongeForge#1535] opened 2017-05-23 11:32 UTC
Sorry for another potentially vague issue, but ender eyes, at least, as far as I can tell, do not function as they normally should. I am using a spongeforge server with around 150 or so mods, The map was pregenerated on a server on my main machine, due to seeming screwiness with RTG on what I can only assume is with multicraft at the moment.

Ender eyes are basically, about as useful as if they were used on a flat map. I so far, do not have any major specifics, or if it is replicable on other spongeforge servers, since I've only noticed this on one server.

**Comment by ryantheleach** [comment] 2017-05-23 11:33
@Sunconure11 What version of Sponge are you using?

Edit: Possible duplicate issue: https://github.com/SpongePowered/SpongeForge/issues/937

**Comment by Sunconure11** [comment] 2017-05-23 11:36
Currently, I'm on 1.10.2-2281-5.2.0-BETA-2350, I just moved from 1.10.2-2281-5.2.0-BETA-2344, which is where I last saw the issue.

**Comment by srs-bsns** [comment] 2017-05-26 01:07
Yesterday, I created a local dedicated server (with default configs) for testing and I discovered 3 strongholds in the world just fine using both Eyes of Ender, and the compass from the EnderCompass mod, using:
- Forge version: 1.10.2-12.18.3.2281
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2322
- RTG version: 1.10.2-4.1.2.4

**Comment by gabizou** [comment] 2017-05-26 05:28
Just going to close this to consolidate efforts on one singular issue: https://github.com/SpongePowered/SpongeForge/issues/937

Since this is a difficult one to reproduce, we'll need exact details, if not complete world copies and config copies with mods to replicate the issue. Any further possibility of reducing how much has to exist to replicate the ender eyes not working will help.

**Closed as completed by gabizou** 2017-05-26 05:28 UTC
Labels: resolution: duplicate
