### ISSUE TITLE
Default Sneak Keybind Conflicting with Lycanites Mobs Mod

### ISSUE THREAD

**Issue by thew313** [SpongePowered/SpongeForge#3189] opened 2020-07-24 06:19 UTC
Running
- SpongeForge version: 1.12.2-2838-7.2.3
- Forge version: 1.12.2 - 14.23.5.2854
- Java version: jre-8u261
- Operating System: Windows 10

- Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge

- Mods (114): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Reducer, Advanced Fishing, Advanced Hook Launchers, AlcatrazCore, Antique Atlas, Anvil Patch - Lawful, Aquaculture, Armor Underwear, AutoRegLib, BNBGamingLib, Battle Towers, Baubles, Better Combat Rebirth, Better Survival, Bloodmoon, Bountiful Baubles, Campfire Spit, Carrots Lib, Carry On, Chunk Pregenerator, Comforts, CompatSkills, Coralreef, Corpse Complex, CraftTweaker JEI Support, CraftTweaker2, Craftable Chainmail, Craftable Horse Armour [CHA&S], CreativeCore, CreativeCoreDummy, Defiled Lands, Disenchanter, Doomlike Dungeons, Dynamic Surroundings, Dynamic Trees, Dynamic Trees for Traverse, Enhanced Visuals, Familiar Fauna, First Aid, FoamFix, FoamFixCore, Food Expansion, Forge Endertech, Forgotten Items, FriendlyEndermite, Global GameRules, Grappling hook mod, ISeeDragons, Ice and Fire, Infernal Mobs, Inventory Tweaks, It's the little things, ItemPhysic, IvToolkit, Just Enough Items, LLibrary, Level Up! Reloaded, Lost Souls, Lycanites Mobs, Mo' Bends, Multi Mine, No Tree Punching, OreLib Support Mod, Phosphor Lighting Engine, Potion Core, Potion Fingers, Quality Tools, RLTweaker, Realistic Torches, Reborn Core, Recurrent Complex, Reskillable, Rin's So Many Enchantments?, Roguelike Dungeons, Rough Tweaks, Ruins Mod, Scaling Health, Serene Seasons, Shadowfacts' Forgelin, Silent Lib, Simple Camp Fire, Sit, Snow! Real Magic!, Spartan Fire, Spartan Shields, Spartan Weaponry, SpawnerControl, SpongeForge, SwingThroughGrass, Switch-Bow, TNTUtils, TNTUtils Core, The Lost Cities, TickProfiler, Tool Belt, Tough As Nails, Traverse, Trinkets and Baubles, Trumpet Skeleton, TschippLib, Tumbleweed, Varied Commodities, Waystones, Wearable Backpacks, Wolf Armor and Storage, XP From Harvest, XP Tome, bacodifficulty (RLCraft 2.8.2)

I'm having an issue with SpongeForge conflicting with the default sneak keybind on a rlcraft server. Everything works fine until you try to fly on your mount(flying creature). You normally hold left shift to go down, but when pressed it causes you to freeze in place on your mount. A simple fix is to just change the sneak keybind, but I don't want to have people do that. I would like for people to play the game as intended. When I remove SpongeForge everything works fine. I would love for this issues to be resolved.

**Comment by ImMorpheus** [comment] 2020-07-24 16:12
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/3133

**Closed as completed by ImMorpheus** 2020-07-24 16:12 UTC
