### ISSUE TITLE
Possible BloodMagic/SpongeForge compatibility issue

### ISSUE THREAD

**Issue by GeneralStrange** [SpongePowered/SpongeForge#1128] opened 2016-12-20 22:03 UTC
**Copy and paste direct from what I posted on WayOfTime's Github Issue https://github.com/WayofTime/BloodMagic/issues/1011**
#### Issue Description:
Server instantly crashes when a Demon Pylon is loaded in a nearby area.

This is in Madhouse Madpack, my own pack, this has happened a few times even with updates to BM, Forge and SpongeForge. Once the Demon Pylons had been removed from the world all was fine.

Crash report:
http://pastebin.com/fCRyRcHk

#### What happens:
As noted above. 

I'm unsure if it's a bug with BM of SpongeForge. I've submitted the crash report to them too.

#### What you expected to happen:
The world to load as normal.

#### Steps to reproduce:

1. Have Demon Pylons in use.
2. Have a player load the world near them.
3. Server  crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- SpongeForge: 5.1.0 BETA-1980

**Comment by Aaron1011** [comment] 2016-12-20 22:17
@Crouch93: I'm unable to reproduce this. Can you try reproducing this on a fresh world with only Sponge and BloodMagic?

**Comment by TehNut** [comment] 2016-12-21 00:19
Close this. It's an unfinished feature that is unobtainable through normal gameplay.

**Closed as completed** 2017-03-27 15:54 UTC
