### ISSUE TITLE
[3616] Netty issues getting worse.

### ISSUE THREAD

**Issue by MoMo2935** [SpongePowered/SpongeForge#2670] opened 2019-04-06 18:38 UTC
**I am currently running**

- SpongeForge version:  3616
- Forge version: 14.23.5.2809
- Java version: N/A
- Operating System: Linux

- Plugins/Mods:
Mods (20): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AquaVote, Icy U Melting, In-game NBTEdit, LegendaryFixer, LunatriusCore, NultraDitto, Pixel Extras, Pixelmon, Pixelmon Trainer Commands, Schematica, SpongeForge, Unbreed, Wondertrade, shulkerbox
Plugins (60): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AGP Responged, AltLogger, Aura Update Checker, AurionsVoteListener, BossBarMessages, ByteItems, CatClearLag, CmdBuilder, CmdControl, CraftingStore, EconomyLite, Enjin Minecraft Plugin, EntityParticles, Even More Pixelmon Commands, ExternalReMover, FixForEconomyBridge, GTS, GTS Reforged Bridge, GriefPrevention, GymRecords, HeadDatabase, Holograms, HuskyUI, IMCPacks, Impactor API, LinkMe, LuckPerms, NuVotifier, Nucleus, PixelAnnouncer, PixelHunt, PixelmonBroadcasts, PixelmonEconomyBridge, PlaceholderAPI, PokeColor, PokeKibble, PokeTeams, Pokedex Rewards, ProjectBorders, ProjectCore, Referrals, SafeTrade, ShrineFees, TabManager, TeslaCore, TeslaCrate, TeslaLibs, UltraDisable, VirtualChest, VoteParty, VoxelSniper, WorldEdit, YourCustomPaintings, pokeTexture, pokebuilder, xP// PayDay

Netty having constant errors due to a multitude of things. doing /tp (Tab) brings up around 50 players names, even though we only have 20 or so on. they seem to be random too, as we've had over 1000 people join at some point. We're crashing due to netty broken pipe with no crash report, and no auto restart, so i have to come on and manually start, massive tps spikes when doing /tp (tab) and /seen (tab)

Couple of different crashes. heres all of them.

https://gist.github.com/PokeHub/4af9244154ae916ec129ec1cc7f0cb5e
https://gist.github.com/PokeHub/895e6d20fa6b347d730c89dc880cecde
https://gist.github.com/PokeHub/7c33c72b14b48445f51c900338237524

**Comment by phit** [comment] 2019-04-06 18:41
Dragon stuff is a duplicate of https://github.com/SpongePowered/SpongeForge/issues/2282
otherwise for netty issues it's out of our control, you can try upgrading netty manually, otherwise you are stuck with the version that's shipped with Minecraft.

**Closed as completed by phit** 2019-04-06 18:41 UTC

**Comment by dualspiral** [comment] 2019-04-08 15:53
For those coming to this issue about broken pipe issue - the latest thinking is that it could be due to tab completion on user elements, such as Nucleus' tp. We are aware and considering fixes - see the following:

* https://github.com/SpongePowered/SpongeCommon/issues/2233
* https://github.com/SpongePowered/SpongeCommon/pull/2124
