### ISSUE TITLE
Issue regarding Spice of Life and Sponge

### ISSUE THREAD

**Issue by Siigari** [SpongePowered/SpongeForge#987] opened 2016-10-24 16:42 UTC
http://pastebin.com/W6vM5Q30

This issue occurs after a player dies and then eats with Spice of Life installed. It generates an internal server error.

**Comment by Zidane** [comment] 2016-10-24 17:27
That trace really doesn't show anything to do with Sponge. Have you tested this without Sponge installed? Need way way more details. Need Forge build numbers/Spice of Life version/Sponge build numbers.

**Comment by simon816** [comment] 2016-10-24 17:30
Known issue with AppleCore, see https://github.com/SpongePowered/SpongeForge/issues/916

**Comment by gabizou** [comment] 2016-10-24 18:26
Duplicate of #916.

**Closed as completed by gabizou** 2016-10-24 18:26 UTC
Labels: resolution: duplicate
