### ISSUE TITLE
Can't activate ender shard with ender dragon

### ISSUE THREAD

**Issue by tomm2000** [SpongePowered/SpongeForge#2200] opened 2018-06-05 06:37 UTC
**I am currently running**
Idk the specs of the machine our server is running on, I am not an admin. I just know it uses sponge.

- Plugins/Mods:
We are running the all the mods 3 modpack.

    
**Issue Description**
When I go to the end and I got an ender dragon with an ender shard it does not start the programming when it should (atm3 is configured to have that enabled)
(Ender shard from woot)

**Steps to reproduce**
1.play on an atm3 sponge server
2.go to the end
3.punch the dragon with a woot ender Shard
4.discover that nothing happens

**Comment by phit** [comment] 2018-06-05 06:45
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1912

**Closed as completed by phit** 2018-06-05 06:45 UTC
Labels: resolution: duplicate, version: 1.12
