### ISSUE TITLE
[1.12.2] Malisis Core Incompatibility 

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1800] opened 2017-10-03 20:25 UTC
**I am currently running...**
- SpongeForge version: 1.12.2-2486-7.0.0-BETA-2685
- Forge version: 14.23.0.2495
- Java version: 8
- Operating System: 
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

Crash Report - https://gist.github.com/Tencao/411ea87e9851629a5d0ebe50fd2ccac5
Log - https://gist.github.com/Tencao/14b80c3cea7b1077d0e31168eda9f0f0

Confirmed this crash only happens with sponge installed, removing sponge immediately gets rid of this.

**Comment by gabizou** [comment] 2017-10-03 23:06
Does renaming the sponge jar with an `a` at the beginning help?

**Comment by kashike** [comment] 2017-10-03 23:23
@Ordinastie

**Comment by Tencao** [comment] 2017-10-04 04:22
I will try and report back

**Comment by Tencao** [comment] 2017-10-04 04:24
No, if anything this causes it to crash even faster.

Log - https://gist.github.com/Tencao/490b89f49dda0e56af465037b6960afa

**Comment by Mumfrey** [comment] 2017-10-04 15:12
Read the error [here](https://gist.github.com/Tencao/490b89f49dda0e56af465037b6960afa#file-gistfile1-txt-L347):

    [05:23:17] [main/WARN] [mixin/]: Mixin config mixins.malisiscore.core.json requires mixin
    subsystem version 0.7.4 but 0.7.2 was found. The mixin config will not be applied.

Ordinastie is using features from 0.7.4 but Sponge's version is loading first and is out of date.

You need malisiscore to load first because it has the required version so ensure spongeforge filename starts with a letter **after** `m`. However the version of Malsiscore you have is bugged, redownload it.

**Comment by kashike** [comment] 2017-10-04 15:40
That's not the issue. The issue is that MalisisCore [is injecting](https://github.com/Ordinastie/MalisisCore/blob/1.12/src/main/java/net/malisis/core/asm/mixin/core/MixinChunk.java#L46) into a method that Sponge [overwrites](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L399-L403). @Ordinastie is working on fixing this in MalisisCore, but is having issues.

https://github.com/Ordinastie/MalisisCore/issues/125
#1794

**Comment by Tencao** [comment] 2017-10-04 19:50
For reference as well, I am using the 6.1.6 build where he fixed the crash his end, hence why it only crashes with sponge installed now.

**Comment by D3nnis3n** [comment] 2017-10-05 06:11
So not using sponge an using malisis 6.1.6 will work for now?

**Comment by Tencao** [comment] 2017-10-05 09:56
Yes, that's correct

**Comment by D3nnis3n** [comment] 2017-10-09 11:12
Yep, that works out. So hopefully there will be a solution to this. At least now i can use crafttweaker again, even though i have to lose out on Sponge.

**Comment by Tencao** [comment] 2017-10-12 05:00
Any update regarding this issue?

**Comment by Ordinastie** [comment] 2017-10-12 05:07
Will be fixed in the next update of MalisisCore that should come in a few days.

**Comment by Tencao** [comment] 2017-10-12 05:22
Thanks for that, once the update is out I'll recheck the issue and close once I've confirmed it fixed my end

**Closed as completed** 2017-10-23 10:17 UTC
Labels: type: mod incompatibility, version: 1.12
