### ISSUE TITLE
IC2 jetpacks dupe - cannot take from crafting table

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1037] opened 2016-11-10 18:09 UTC
Without spongeforge all works as expected.

With SF build 1876 (no plugins installed) cannot take crafted IC2 backpack, jetpack and electric jetpack from crafting table.

When close gui, ingredients are in the ground, but not removed from inventory - duped.

**Comment by phit** [comment] 2016-11-11 05:17
relevant issue #999

**Comment by ghost** [comment] 2016-11-13 07:44
It looks like some kind of crafting check cancel click/move inventory event...

**Comment by ghost** [comment] 2016-11-15 15:45
When tested found issue. When try take jetpack (mouse click) from craftingtable gui and have some item selected in hotbar see hand animation, similar when interacting. When craft for example stick and try to take using mouse click see no hand animation.

**Comment by ghost** [comment] 2016-11-15 15:58
Hand animation is with forge (no spongeforge installed) too. Every clicking to batpack in the inventory lead to hand animation.

**Comment by ghost** [comment] 2016-11-15 17:48
Issue at IC2 BT:

http://bt.industrial-craft.net/view.php?id=2036

**Comment by ghost** [comment] 2016-11-15 21:20
Tried some debug.

With this patch of SpongeCommon:

<pre>
diff --git a/src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java b/src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java
index 5bd5868..c3e0ece 100644
--- a/src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java
+++ b/src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java
@@ -566,8 +566,10 @@ public EntityItem onPlayerDropItem(EntityPlayerMP player, boolean dropAll) {
     @Redirect(method = "processClickWindow", at = @At(value = "INVOKE", target = "Lnet/minecraft/item/ItemStack;areItemStacksEqual(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)Z"))
     public boolean onProcessClickWindowItemValidate(ItemStack stackA, ItemStack stackB) {
         boolean result = ItemStack.areItemsEqual(stackA, stackB);
+        System.out.println("stackA: " + stackA + " stackB: " + stackB); 
         // If the client sends an invalid inventory packet, detect changes only then restore and notify client.
         if (!result) {
+        System.out.println("FALSE CLICK STACK");
             IMixinContainer mixinContainer =(IMixinContainer) this.playerEntity.openContainer;
             mixinContainer.detectAndSendChanges(true);
             PacketPhaseUtil.handleSlotRestore(this.playerEntity, Lists.newArrayList(mixinContainer.getCapturedTransactions()), true, false);
</pre>

Found what is wrong between client and server during clicking to crafting result slot in the crafting table:

<pre>
[22:16:11] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:569]: stackA: 1xic2.batpack@0 stackB: 1xic2.batpack@26
[22:16:11] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:572]: FALSE CLICK STACK
</pre>

**Comment by ghost** [comment] 2016-11-15 21:59
When look to JEI its show recipe Batpack with durability 27/27 but recipe result in the crafting table show in the client is durability 1/27.

**Comment by ghost** [comment] 2016-11-15 22:00
Similar bug with durability was in the IC2 1.6.4 :-)

**Comment by ghost** [comment] 2016-11-16 06:47
https://github.com/SpongePowered/SpongeCommon/commit/1217e1d4628b2c8da21e5c632e5253715830bee9

**Comment by phit** [comment] 2016-11-18 19:54
applied energistics 2 tools are also affected by this bug

**Comment by Xiaoyan366** [comment] 2016-11-28 05:55
[crash-2016-11-28_13.52.43-client.txt](https://github.com/SpongePowered/SpongeForge/files/615481/crash-2016-11-28_13.52.43-client.txt)

Similar mistakes

**Comment by ghost** [comment] 2016-11-28 06:32
trying spongeforge build 1914 with this fix, but get client crash when click to crafting result (IC2 batpack) - trying drag and drop.
With shift-click can be moved to inventory.
http://pastebin.com/BELW7nU0

**Comment by Xiaoyan366** [comment] 2016-11-28 06:40
This problem will be fixed?
Players have IC2 backpack, can not be on-line later
The on-line client will crash

Now what are the solutions?

**Comment by ghost** [comment] 2016-11-28 06:42
downgrade spongeforge, problem will be fixed (works on my test server)

**Comment by bloodmc** [comment] 2016-11-28 07:25
Unable to reproduce this with latest IC2 build 119.
http://jenkins.ic2.player.to/job/IC2_110/119/

**Comment by ghost** [comment] 2016-11-28 07:26
try IC2 build 109 for example

**Comment by ghost** [comment] 2016-11-28 18:03
tested on the local server too, its not latency issue, still crashes client

**Comment by ghost** [comment] 2016-11-28 19:10
My test code of latetst patch. I added some debug output to trace. When craft IC2 batpack, after latest TRACE11 - false is client crashed.
when add after line mixinContainer.setCaptureInventory(false); 

return true; 

can craft IC2 batpack and drag to inventory without client crash

<pre>
    public boolean onProcessClickWindowItemValidate(ItemStack stackA, ItemStack stackB) {
        boolean result = ItemStack.areItemsEqual(stackA, stackB);
        // If the client sends an invalid inventory packet, detect changes only then restore and notify client.
        if (!result) {
            final CauseTracker causeTracker = ((IMixinWorldServer) this.playerEntity.worldObj).getCauseTracker();
            ItemStackSnapshot cursor = causeTracker.getCurrentContext().firstNamed(InternalNamedCauses.Packet.CURSOR, ItemStackSnapshot.class).orElse(null);
            CPacketClickWindow packet = causeTracker.getCurrentContext().firstNamed(InternalNamedCauses.Packet.CAPTURED_PACKET, CPacketClickWindow.class).orElse(null);
            System.out.println("TRACE1");
            if (cursor == null || packet == null) {
                        System.out.println("TRACE2");
                return result;
            }
            // Validate last packet came from same source otherwise ignore
            if (packet.getActionNumber() != (SpongeCommonEventFactory.lastClickInventoryActionNumber+ 1)) {
                        System.out.println("TRACE3");
               return result;
            }
                        System.out.println("TRACE4");
            IMixinContainer mixinContainer =(IMixinContainer) this.playerEntity.openContainer;
                        System.out.println("TRACE5");
            mixinContainer.detectAndSendChanges(true);
                        System.out.println("TRACE6");
            PacketPhaseUtil.handleSlotRestore(this.playerEntity, Lists.newArrayList(mixinContainer.getCapturedTransactions()), true, false);
                        System.out.println("TRACE7");
            // restore cursor
            this.playerEntity.inventory.setItemStack((ItemStack) cursor.createStack());
                        System.out.println("TRACE8");
            mixinContainer.getCapturedTransactions().clear();
                        System.out.println("TRACE9");
            mixinContainer.setCaptureInventory(false);
                        System.out.println("TRACE10");
        }
                    System.out.println("TRACE11 " + result);
        return result;
    }



[20:03:46] [Server thread/INFO]: HunterzCZ joined the game
[20:03:56] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:03:57] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:03:58] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:03:58] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:03:59] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:00] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:01] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:01] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:01] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:01] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:01] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:02] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:04] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:04] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:04] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:04] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:06] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:07] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:07] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:07] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 true
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:576]: TRACE1
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:586]: TRACE4
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:588]: TRACE5
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:590]: TRACE6
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:592]: TRACE7
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:595]: TRACE8
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:597]: TRACE9
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:599]: TRACE10
[20:04:08] [Server thread/INFO] [STDOUT]: [net.minecraft.network.NetHandlerPlayServer:redirect$onProcessClickWindowItemValidate$zgp000:601]: TRACE11 false
[20:04:11] [Server thread/INFO]: HunterzCZ lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
</pre>

**Comment by Xiaoyan366** [comment] 2016-11-29 04:56
[工业2]industrialcraft-2-2.6.120-ex110.jar
1.10.2-forge1.10.2-12.18.2.2166
spongeforge-1.10.2-2123-6.0.0-BETA-1890.jar or spongeforge-1.10.2-2123-5.1.0-BETA-1914.jar
Use the latest version of IC2 and forge
I found this problem solved

Great! No BUG good

**Comment by ghost** [comment] 2016-11-29 06:35
Still crashing for me.
forge 2166
ic2 120
sf 1914

http://pastebin.com/pKs4LVM4

**Comment by Xiaoyan366** [comment] 2016-11-29 06:55
Synthetic now there won't be a BUG 
On the armor items block, do you want to take it down The client will collapse 
[crash-2016-11-29_14.45.53-client.txt](https://github.com/SpongePowered/SpongeForge/files/618269/crash-2016-11-29_14.45.53-client.txt)

**Comment by bloodmc** [comment] 2016-11-29 08:09
OK i'll review the code tomorrow and try to get a fix.

**Comment by phit** [comment] 2016-11-29 09:31
yeah, 1914 is unusable for our server :( 
clients keep crashing
[crash-2016-11-29_10.23.31-client.txt](https://github.com/SpongePowered/SpongeForge/files/618568/crash-2016-11-29_10.23.31-client.txt)
[crash-2016-11-29_10.29.20-client.txt](https://github.com/SpongePowered/SpongeForge/files/618567/crash-2016-11-29_10.29.20-client.txt)

**Comment by dezil** [comment] 2016-11-29 22:12
can confirm this issue updated to 1914 about 24-36 hours ago and have had a heap of users crash with the same rendering error

**Closed as completed** 2016-11-30 05:58 UTC
Labels: type: bug, type: mod incompatibility

**Comment by ghost** [comment] 2016-11-30 06:19
Can confirm its fixed now. Many thanks!
