### ISSUE TITLE
Memory issue with Psi and SlotTransactions

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/SpongeForge#1577] opened 2017-06-08 23:10 UTC
So I'm running a small modded sponge server where Psi is included. Sometimes when someone casts a spell I notice a big uptick in the amount of memory that the server uses (in the 100s of mb range).  Looking into a heap dump it looks like LOTS of SlotTransactions are taking place (around 2000) and that they aren't cleaned up afterwards.  Seeing as the CAD ItemStack uses quite a bit of memory by itself, this quickly adds up. I can provide the heap dump if that will help, although it's kind of big. For this specific case it took up some 600 mb of memory, although I have seen different numbers as well (don't have a dump for them).

For me a simple solution would be if I could either blacklist certain items.

**I am currently running...**
- SpongeForge version:  spongeforge-1.10.2-2281-5.2.0-BETA-2366
- Forge version: forge-1.10.2-12.18.3.2281
- Java version:  Java 1.8.102
- Operating System: 
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 

**Mods:**
    Inventory Tweaks (by Kobata)
    Chameleon (by jaquadro)
    Storage Drawers (by jaquadro)
    Waila Harvestability (by squeek502)
    Iron Chests (by progwml6)
    Extra Utilities (by RWTema)
    Chisel (by tterrag1098)
    Wawla - What Are We Looking At (by darkh4x)
    Morpheus (by Quetzi)
- Immersive Engineering (by BluSunrize)
- Forestry (by SirSengir)
- Biomes O' Plenty (by Glitchfiend)
- Random Things (by lumien231)
- Fast Leaf Decay (by Olafskii)
- Mouse Tweaks (by YaLTeR97)
- Industrial Craft (by Player)
- Just Enough Items (JEI) (by mezz)
- Soul Shards: The Old Ways (by SgtPunishment)
- Chisels & Bits (by AlgorithmX2)
- OpenComputers (by SangarWasTaken)
- Just Enough Resources (JER) (by Way2muchnoise)
- AutoRegLib (by Vazkii)
- Psi (by Vazkii)
- NetherPortalFix (by BlayTheNinth)
- Quark (by Vazkii)
- stimmedcow : NoMoreRecipeConflict (by Oliv1er)
- Compact Solars (by progwml6)
- Roots (by elucent)
- MCMultiPart (by amadornes)
- Hardcore Wither (by thor12022)
- Realistic Terrain Generation (by WhichOnesPink)
- Light Level Overlay Reloaded (by oldjunyi)
- Just Enough Forestry Bees (JEFB) (by apengu_)
- Hardcore Darkness (by lumien231)
- Mapwriter 2 (by VectronDiablon)
- NoNausea (by lumien231)
- Ping (by dmillerw)
- BiomeTweaker (by superckl)
- Dynamic Surroundings (by OreCruncher)
- Sound Filters (by Tmtravlr)
- Baubles (by azanor)
- Botania (by Vazkii)
- Mercurius (by TamasHenning)
- Flat Colored Blocks (by AlgorithmX2)
- Redstone Paste (by FyberOptic)
- Morph-o-Tool (by Vazkii)
- Super Circuit Maker (by amadornes)
- Akashic Tome (by Vazkii)
- Railcraft (by CovertJaguar)
- Grimoire of Alice (by Arekkuusu)
- Iron Backpacks (by gr8pefish)
- BetterAchievements (by Way2muchnoise)
- Farseek (by delvr)
- Streams (by delvr)
- Grappling Hook Mod (by Yyon)
- Waystones (by BlayTheNinth)
- Tough As Nails (by Glitchfiend)
- Login Shield (by Glasspelican)
- Embers (by elucent)
- Roguelike Dungeons (by Greymerk)
- ShetiPhianCore (by ShetiPhian)
- Platforms (by ShetiPhian)
- IvToolkit (by Ivorforce)
- Recurrent Complex (by Ivorforce)
- Hwyla (by TehNut)
- CoFH Core (by TeamCoFH)
- Thermal Foundation (by TeamCoFH)
- CodeChicken Lib 1.8.+ (by covers1624)
- Thermal Expansion (by TeamCoFH)
- MrTJPCore (by Mr_TJP)
- Project Red - Base (by Mr_TJP)
- Project Red - Integration (by Mr_TJP)
- Project Red - Lighting (by Mr_TJP)
- Project Red - World (by Mr_TJP)
- Project Red - Mechanical (by Mr_TJP)
- Forge MultiPart CBE (by covers1624)
- CompatLayer (by McJty)
- DanmakuCore (by Katrix97)
- Journey to Gensokyo (by Katrix97)
- Open Glider (by gr8pefish)
- LLibrary (by iLexiconn)
- Shadowfacts' Forgelin (by shadowfactsmc)
- Literal Ascension (by JamiesWhiteShirt)
- Astral Sorcery (by HellFirePvP)
- ShadowMC (by shadowfactsmc)
- Large Veins (by shadowfactsmc)
- GraveStone Mod (by EuhDawson)
- Redstone Arsenal (by TeamCoFH)
- Cooking for Blockheads (by BlayTheNinth)
- Foamfix

Plugins:
- KatLib
- ChitChat
- FAWE
- FoxCore
- FoxGuard
- IPLog
- Latch
- LuckPerms
- Nucleus
- PleaseWelcome
- Prism
- ServerListPlus

**What is the expected result?**
Memory usage stays about the same after casting a spell.

**What is the current result?**
Memory usage jumps up after casting a spell.

**Comment by Katrix** [comment] 2017-06-09 20:11
Here is a link to the heap dump. https://1drv.ms/u/s!AujWrwEeDZYGgqkU53TuYj1SO5phvw

**Comment by Aaron1011** [comment] 2017-06-09 20:17
@Katrix-: Does this occur when casting any spell, or only certain spells?

**Comment by Katrix** [comment] 2017-06-09 20:26
I'm uncertain, but from what I have seen (just looking at memory usage, no heaps), after the spell has been casted for the first time, memory seems to stay somewhat the same. I'll see if I can run some more tests once I can.

**Comment by Katrix** [comment] 2017-06-17 10:05
So, tried to get a bit more information, but haven't found much. Talked to a player that managed to create a player object roughly a gb in size. According to him, he only uses Psi for conjuring light blocks, some 10-20 times per hour. I tried to run around a conjure a bunch of light blocks myself, but couldn't get the same behavior. 

Also tried to see what changed between the item stacks (comparing hashes for nbt, as going through the actual nbt it too much work), and I didn't actually find any changes, so I'm confused about what's actually changing.

**Comment by Sir-Will** [comment] 2017-07-22 08:03
Looks like I have the same issue:
![](http://i.imgur.com/GtQ41Dd.jpg)
![](http://i.imgur.com/X1nWnmE.jpg)
![](http://i.imgur.com/pCCuWjM.jpg)

**Comment by LilyEvergreen** [comment] 2017-07-24 07:56
Hey! I found the issue with Sponge and Psi. The issue seems to be the data that psi is sending to the server when you change the spells in the CAD. You can remove the change or reduce the tick rate it sends it to the server to stop the server from over flooding from the packets. Good Luck!

I am currently unable to fully explain due to time but if anyone wants a more detailed explanation, leave a comment.

**Comment by phit** [comment] 2017-11-27 19:20
@Katrix- @Sir-Will @LilyEvergreen is this still an issue? if it is, can you please add a step by step reproduction

**Comment by gabizou** [comment] 2018-01-01 09:08
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by gabizou** 2018-01-01 09:08 UTC
Labels: version: 1.10 (u), status: waiting for reply
