### ISSUE TITLE
NeighborNotificationPhase Runaway Tracker Issue with Roguelike Dungeons redstone wire.

### ISSUE THREAD

**Issue by NovaLynxie** [SpongePowered/SpongeForge#2743] opened 2019-05-09 19:53 UTC
**I am currently running**
- SpongeForge version: 
- Forge version: 14.23.5.2825
- Java version: 1.8.0_181-b13 (PC)
- Operating System: Meloncube Server (Unknown)

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AppleCore, Applied Energistics 2, Astral Sorcery, Bauble Wings, Baubles, Better Animals+, Better Underground, BetterBedrockGen, BiblioCraft, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Bookshelf, Bookworm API, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, Cathedral, Chameleon, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Creeper Confetti, Dynamic Surroundings, DynamicSurroundingsCore, Embers Rekindled, Enchanting Plus, EnderStorage, Energy Converters, Guide-API, Hammer Core, HellBound, Hunger Overhaul, Ice and Fire, IvToolkit, JourneyMap, Just Enough Items, LLibrary, Lag'B'Gon Reborn, LagGoggles, LibEx, Loot Bags, Mantle, MetalChests, Morpheus, Multi Mob Core, Mystical Lib, NetherBound, NetherEx, OreLib Support Mod, Pam's HarvestCraft, Patchouli, Primitive Mobs, Project: Vibrant Journeys, Reborn Core, Redstone Flux, RikMuld's Core, Roguelike Dungeons, Rustic, Selim's Enchants, Shadowfacts' Forgelin, Soot, SpongeForge, Tech Reborn, Tech Reborn Mod Compatibility, Thaumcraft, Thaumic Periphery, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker's JEI, Tinkers' Construct, Underground Biomes, UniDict, Waila, WanionLib, Wearable Backpacks, Wings, WorldEdit, ZarakLib

**Issue Description**
While the server is running and one of our players does an rtp, they sometimes run into a block that spongeforge will immediately disagree with running away into a phase tracker loop till eventually the server just crashes. The world itself locks up and immediately freezes in place.
We have tried multiple times to resolve this issue with no luck. 

I have found a similar issue to this one where the server has the very same error but a different block. Our issue was pointing at a redstone wire deep inside a dungeon generated by Roguelike Dungeons.
Issue Link: https://github.com/SpongePowered/SpongeForge/issues/2425

Crash Report with looping error caught here after the server dies due to server watchdog forcefully stopping the server.
Crash Report: https://gist.github.com/NovaLynxie/47f94ba61b6b085efc83007b854bb04b
Server Logs: https://gist.github.com/NovaLynxie/96693c68c9bbe2f54b5e9dff30aa1191

**Comment by phit** [comment] 2019-05-09 19:57
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2252

**Closed as completed by phit** 2019-05-09 19:57 UTC
Labels: resolution: duplicate, system: phase tracker, version: 1.12
