### ISSUE TITLE
Sponge Container crash w/ IE workbench

### ISSUE THREAD

**Issue by TehFoxFire** [SpongePowered/SpongeForge#1531] opened 2017-05-21 21:31 UTC
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2344
- Forge version: 1.10.2-12.18.3.2297
- Java version: Unknown
- Operating System: CentOS

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods:  Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Aroma1997Core, SpongeAPI, SpongeForge, ccl-entityhook, Nucleus Mixins, ActiveTime, AdminShop, Pixelmon, AGP, Aroma1997Core|Helper, AromaBackup, AromaBackup Recovery, Quark, AutoRegLib, Baubles, Baubles Stuff, Better Builder's Wands, BiblioCraft, MalisisCore, MalisisDoors, Big Doors, Bookshelf, Bookshelf, CatClearLag, Chameleon, Just Enough Items, MCMultiPart, Chisels & Bits, CodeChicken Lib, CodeChicken Core, CommandSigns, CosmeticArmorReworked, CraftBook, CustomNPCs, Cyclic, D??Core, Discord Bridge, Dragon Mounts, Enjin Minecraft Plugin, Enchanting Plus, EnderCore, EnderStorage, Extra Bit Manipulation, Fast Leaf Decay, GriefPrevention, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, Inventory Tweaks, Iron Backpacks, Iron Chest, Loot Bags, LuckPerms, Malisis Advert, MMCReboot, MmmMmmMmmMmm, Morpheus, Natura, Natural Absorption, NeoTech, NoMoreRecipeConflict, NPCs, Nucleus, Pam's HarvestCraft, PixelAutoMessages, Pixel Extras, PixelmonEconomyBridge, Pixel Shout, Prism, Random Things, Storage Drawers, Refined Storage, RFTools, Roots, Slackr, SpongyChest, Super Circuit Maker, Tinkers Tool Leveling, Total Economy, VirtualTool, Waila, I Can See Everything, What Are We Looking At, WeaponCaseLoot, WorldEdit, XNet

**What is the expected result?**
To be able to place and retrieve items out of the work bench
**What is the current result?**
Server crash

[crash-2017-05-21_19.01.00-server.txt](https://github.com/SpongePowered/SpongeForge/files/1017348/crash-2017-05-21_19.01.00-server.txt)
Unfortunately this issue is a day old and the logs have since been over-written. As such there isnt much to show.

**Comment by axle2005** [comment] 2017-05-21 23:00
Duplicate of [1516](https://github.com/SpongePowered/SpongeForge/issues/1516)

**Comment by gabizou** [comment] 2017-05-24 18:37
All you need to do is update.

**Closed as completed** 2017-05-24 18:37 UTC
