### ISSUE TITLE
FTB Revelation 2.5.0 is a no go with SF.

### ISSUE THREAD

**Issue by MorbiusStorm** [SpongePowered/SpongeForge#2446] opened 2018-09-18 18:09 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3361
- Forge version: 14.23.4.2759
- Java version: 1.8.0_102
- Operating System: Linux (amd64) version 3.10.0-514.26.1.el7.x86_64

- Plugins/Mods: FTB Revelation 2.5.0

FTB Revelation 2.5.0 doesn't work with SpongeForge. Tried with 3361, 3445, 2447, 3448, and even 8.0.0-3449 (for giggles I guess). Revelation 2.4.1 works. I'm going to take a guess that possibly the forge version included with 2.5 just doesn't work while the one included with 2.4.1 does.

Clean install of Revelation 2.5.0. Add SF to mods folder. Start server. Crash report gives the error: Exception generating new chunk

Clean install. Run the server once to generate /world. Add SF. Start server again. Crash report now gives: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/chunk/BlockStateContainer

https://gist.github.com/MorbiusStorm/9cec8cf3fc1b86a6b60b05c7408b3ac3

**Comment by gabizou** [comment] 2018-09-18 18:11
Try running foam fix lawful or remove foam fix entirely. 

Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2432

**Closed as completed by gabizou** 2018-09-18 18:11 UTC
Labels: resolution: duplicate, type: mod incompatibility, version: 1.12

**Comment by phit** [comment] 2018-09-18 19:04
open your foamfix config and disable `general.patchChunkSerialization`

**Comment by MorbiusStorm** [comment] 2018-09-18 19:18
That seems to fix it. I also got it going by setting coremods forceDisable to true. But that option seemed like the sledgehammer method before just deleting the mod. Thanks for the help. Perhaps others will find this solution when they try to update from Revelation 2.4.1 to 2.5.0

**Comment by HFinner** [comment] 2018-12-10 01:31
Just wanted to say I also am running an FTB Revelation server and simply deleting foamfix stopped my server from crashing again. Thanks!
