### ISSUE TITLE
Conflicting default methods

### ISSUE THREAD

**Issue by runescapejon** [SpongePowered/SpongeForge#2969] opened 2019-09-09 02:53 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3910
- Forge version:  14.23.5.2846
- Java version: 8
- Operating System: windows/linux

- Plugins/Mods:
LibVulpes-1.12.2-0.4.1-60-universal
AdvancedRocketry-1.12.2-1.6.0-164-universal

**Issue Description**
Basically make a launch pad by any size and then attempt to create a space station, once you build your space station. Your space station chip and Satellite Bay will create these error once you interact with them in your inventory. 
`Conflicting default methods: net/minecraftforge/items/IItemHandler.fabric$getSize net/minecraft/inventory/IInventory.fabric$getSize`
https://gist.githubusercontent.com/runescapejon/03812fdb277dcca82d1936d0068bca21/raw/473fefc7cdce593849fabcba1b969acfb957ec9a/gistfile1.txt

**Comment by gabizou** [comment] 2019-09-10 08:09
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2943

**Closed as completed by gabizou** 2019-09-10 08:09 UTC
Labels: resolution: duplicate
