### ISSUE TITLE
Mystical Agriculture Ultimate Furnace bug

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2753] opened 2019-05-12 19:42 UTC
**I am currently running**

- SpongeForge version: 708
- Forge version: 
- Java version: 
- Operating System:

**Issue Description**
MystAgr furnaces kick you out of GUI when they are in use like the previous versions did with other furnaces

**Comment by gabizou** [comment] 2019-05-13 05:51
> * SpongeForge version: 708
> * Forge version:
> * Java version:
> * Operating System:

There's no version fo SpongeForge called 708, can you double check what version you have, and if it's earlier than 
1.12.2-2825-7.1.6-RC3701, try the latest build (which at current writing is 
1.12.2-2825-7.1.6-RC3708). You can review some of the changes in the builds [here](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2).

**Comment by krisjenner** [comment] 2019-05-13 14:14
It's 1.12.2-2825-7.1.6-RC3708

**Comment by Yorkforce** [comment] 2019-05-13 16:15
Can also confirm, its not just affecting mystical agriculture, it also affects cauldrons and nuclearcraft machines, they all start glitching out, cauldrons wont accept cobble, nuclearcraft machines end up like they used to by kicking you out of the GUI.
We have also noticed some really weird behaviour with tanks and machines in general, tanks look like they are being constantly refreshed, visually the fluid level keep dropping to 0 and then refilling constantly.
Mekanism machines for example frequently switch textures, like they are being rotated, it only happens for a split second but again it looks like they are being constantly refreshed.

A server restart fixes the problem but it soon returns.

I'll try get some logs when it occurs again but i'm sure is a phase tracking error occuring.

**Comment by CaptainSisko** [comment] 2019-05-13 16:27
I did some testing on my ATM3: Remix server and wasn't able to replicate this issue.

My live server is running 1.12.2-2825-7.1.6-RC3705
My test server is running 1.12.2-2825-7.1.6-RC3708

I tested on both servers and all of the Mystical Agriculture furnaces were working correctly. I also tested RC3708 with FastFurnace installed as that caused some issues recently but the furnaces worked correctly.

@krisjenner are you able to provide a mod list and your forge version, it might be something else causing the issue.

@Yorkforce I am also using nuclearcraft and that is working fine too. 
I have however experienced what you mention, some machines will randomly stop functioning correctly (ie. nuclearcraft machines reverting to how they were acting prior to the recent fix) and even enderio conduits will refuse to place properly but instead will show as an transparent cube with a black outline. I have had those things occur since at least RC3639 and a reboot has always fixed them.

I have been unable to troubleshoot that issue due to it happening at random times, with no logs generated and cant be reproduced by following a fixed set of steps.

**Comment by Yorkforce** [comment] 2019-05-13 16:59
@CaptainSisko Yep same thing, its odd. For some players the cauldrons and nuclearcraft machines work perfectly fine, but for others they start experiencing the issues above, a server restart fixes them all but then it can re occur at random.

It always seems to occur after something like this:
https://pastebin.com/NcNSWyd5
(this is an error on the server experiencing it right now)

Full server log:
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3173969/latest.log)

**Comment by krisjenner** [comment] 2019-05-14 12:46
Second ^ It doesn't occur all the time but can randomly start happening

**Comment by TheFlash787** [comment] 2019-05-14 14:46
It's happening to us too on SkyFactory 4 (RC3707) but only in the overworld, and a 100% success rate in a different dimension (such as the Twilight). I feel this may also be related to another issue where sometimes the miniaturization recipes (Compact Machines) will not initiate the crafting recipe for only a few items. (Because again, that only happens in the overworld, and not all the time, but most.)

**Comment by gabizou** [comment] 2019-05-15 07:43
Retest with 3709, has a pretty big bug fixed in it that may well resolve this issue. If there's another capture error (like the one listed here:)


> It always seems to occur after something like this:
> https://pastebin.com/NcNSWyd5
> (this is an error on the server experiencing it right now)

Please submit as a new issue, since this is an issue regarding Mystical Agriculture Ultimate <sup><sup>~~SuperMaster Supreme Magnifico Incredible Outstanding Exceptional Impressive Phenomenal~~<sup> I couldn't help myself...</sup> </sup></sup> Furnaces.

**Comment by Yorkforce** [comment] 2019-05-15 07:49
The Ultimate Furnace issue that occurs happens at exactly the same time as the other issues I mentioned, they all seem to be triggering from the same problem.

I'll try to test 3709 but it's difficult as the moment as we have had to revert back to 3696 due to the schematics problem.

**Comment by Yorkforce** [comment] 2019-05-18 20:03
Appears to be fixed for us since at least RC3712, have had no reports of the problem occurring since updating.

**Closed** 2019-05-18 20:07 UTC
Labels: status: waiting for reply, version: 1.12
