### ISSUE TITLE
Coke oven from IE getting duped with fortune applied

### ISSUE THREAD

**Issue by jmercado808** [SpongePowered/SpongeForge#1281] opened 2017-02-20 02:33 UTC
Coke ovens from Immersive Engineering are getting duped with the fortune enchantment applied to a tinkers pick. It does not happen on vanilla pickaxes.

**Comment by ryantheleach** [comment] 2017-05-19 13:15
Does this happen without SpongeForge, using only Forge, Immersive Engineering, and Tinkers Construct?

**Comment by phit** [comment] 2017-07-17 18:45
Retested this with 
ImmersiveEngineering-0.11-63.jar
jei_1.11.2-4.5.0.291.jar
Mantle-1.11.2-1.2.0.26.jar
spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar
TConstruct-1.11.2-2.7.1.34.jar

Tried a Tinkers and Vanilla pickaxe with both fortune III, broke coke oven bricks multiple times and couldn't get them to dupe, even when the brick was part of the Coke Oven multiblock.

**Comment by Zidane** [comment] 2017-07-17 20:51
Closing as not able to be reproduced by others (it may very well have been resolved by now).

**Closed as completed by Zidane** 2017-07-17 20:51 UTC
