### ISSUE TITLE
Invalid Villager Profession ID is present!

### ISSUE THREAD

**Issue by Siriuo** [SpongePowered/SpongeForge#1197] opened 2017-01-16 10:17 UTC
Having some server crashes caused by Villagers

Crash report from server is: http://pastebin.com/FFKSuS2Q

**Comment by Siriuo** [comment] 2017-01-16 20:56
Seems to be caused when placing a routing node from blood magic.

**Comment by Zidane** [comment] 2017-01-16 23:23
One of your mods is not registering villagers correctly (or at all). Remove mods one by one till you find the culprit.

**Comment by Eufranio** [comment] 2017-01-18 23:17
Same crash with ONLY Forge + SpongeForge + Nucleus installed. I've set nucleus to generate the world, and as long it is generating, the server crashes.

**Comment by gabizou** [comment] 2017-01-19 02:13
Duplicate of #1190 Will be fixing very soon.

**Closed as completed by gabizou** 2017-01-19 02:13 UTC
