### ISSUE TITLE
Nuclearcraft Dupe

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2716] opened 2019-04-27 02:04 UTC
I am currently running

SpongeForge version: 3679

Forge version: 2831

Plugins/Mods:
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Aliases, AntiWDL, AurionsVoteListener, AutoBroadcaster, CatClearLag, Discord Bridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MultiChatSponge, NuVotifier, Nucleus, Player Glow, PlayerShopsRPG, PwnFilter, RankUpper, SkyClaims

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, B.A.S.E, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Extra Cells Patch, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, MekanismGenerators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

Issue Description

Placing an item into a nuclearcraft manufactory results in the item being thrown to the ground but the manufactory still produces the resulting resource, this results in only ever needing 1 item to produce unlimited resources.

Probably related to #2710

**Comment by gabizou** [comment] 2019-04-27 14:12
Re-test with 3679.

**Comment by Yorkforce** [comment] 2019-04-27 14:52
Apologies @gabizou , forgot to update the version in original post.

This is on 3679, on 3671 it just threw the item on the floor, 3679 still throws the item out but also allows the manufactory to process the resource, hence the dupe.

**Comment by Aaron1011** [comment] 2019-04-28 03:37
@Yorkforce: I can't reproduce this with just NuclearCraft (I tried making compressed coal and crushed quartz)

**Comment by Yorkforce** [comment] 2019-04-28 15:33
Weird, so another mod must be conflicting via spongeforge.

The Nuclearcraft github did mention this about a recent change in spongeforge @Aaron1011 ?
https://github.com/turbodiesel4598/NuclearCraft/issues/504
Regarding this issue:
#2644 

Could that be related?

**Comment by Aaron1011** [comment] 2019-04-28 23:32
@Yorkforce: Where can I download the modpack you're using?

**Comment by bluelightning32** [comment] 2019-04-29 02:43
I was able to reproduce this with the DD&SS modpack. Repro steps:
1. Build a manufactory, and power it. I used a Creative RF source.
2. Put coal into the manufactory. The manufactory immediately spits it back out. However, the progress bar continues to progress as long as the GUI is open. In the below screenshot you can see the ejected coal to the left and the progress bar:
![image](https://user-images.githubusercontent.com/21202621/56874187-21fe7280-69ed-11e9-865c-5ede94001eea.png)
3. Without leaving the manufactory GUI, let the progress bar reach the end. It immediately spits out the finished product.
4. Go collect the raw materials that were spit out earlier. None were consumed.

Modpack:
Dungeons, Dragons, and Space Shuttles version 4.11a

NuclearCraft:
NuclearCraft-2.15b-1.12.2.jar

Forge:
forge-1.12.2-14.23.5.2836-universal.jar

SpongeForge:
spongeforge-1.12.2-2768-7.1.6-RC3682.jar

Plugins:
```
> /sponge plugins 
[19:39:29] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (10): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Inventory Sync, JdaLibraryLoader, LuckPerms, Sledgehammer, UltimateChat, spark
```

Mods: 
```
> /sponge mods
[19:41:24] [Server thread/INFO] [minecraft/DedicatedServer]: Mods (260): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, A Lib, Actually Additions, Actually Baubles, Akashic Tome, Alchemistry, Animania, AppleCore, AppleSkin, ArchitectureCraft, Aroma1997Core, AromaBackup, AromaBackuprecovery, Artisan Worktables, Astral Sorcery, Athenaeum, AutoPickup, AutoRegLib, Avaritia, B.A.S.E, BD Lib, Baubles, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bloodmoon, Bonsai Trees, Bookshelf, Botania, Brandon's Core, Ceramics, Chameleon, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Drawers, ContentTweaker, CookieCore, Corail Tombstone, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cucumber Library, Custom Starting Gear, Cyclic, Cyclops Core, DDSS Utils, Dark Utilities, DiscordIntegration, Doomlike Dungeons, Draconic Evolution, DungeonTactics, EnderStorage, Environmental Tech, EvilCraft, EvilCraft-Compat, Exchangers, Extended Crafting, Extra Alchemy, Extra Planets, Extra Utilities 2, Extreme Reactors, FTB Library, FTB Utilities, Farseek, Fast Leaf Decay, FastWorkbench, Fishing Net Mod, FluidTank, FluidTank_AE2, FluidTank_TheOneProbe, FoamFix, FoamFixCore, Forestry, Forge Endertech, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, GenDustry, Gendustry JEI Addon, Guide-API, Guidebook, HelpFixer, Hooked, Hunger Overhaul, Hunting Dimension, Ice and Fire, Immersive Engineering, Industrial Foregoing, Infernal Mobs, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Backpacks, Iron Chest, IvToolkit, JourneyMap, Just Another Rotten Flesh to Leather Mod, Just Enough Items, LLibrary, LagGoggles, Lapis Stays in the Enchanting Table, LibEx, LibrarianLib, LibrarianLib Stage 2, LittleTiles, LittleTilesCore, Loot Bags, LootTweaker, MJRLegendsLib, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanica, Mekanica: Generators, Mekanica: Tools, MekanismOres, Micdoodle8 Core, Minecraft Multipart Plugin, Mob Properties Randomness, Mod Tweaker, More Libs, More Plates, Morpheus, Mowzie's Mobs, MrCrayfish's Furniture Mod, MrTJPCore, Multi Mob Core, Mystical Agradditions, Mystical Agriculture, Mystical Lib, Natura, NetherEx, NotEnoughIDs, NuclearCraft, OMLib, OnlinePictureFrame, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Overloaded, Pam's Cookables, Pam's HarvestCraft, Pickle Tweaks, Placebo, PlusTiC, PneumaticCraft: Repressurized, Primitive Mobs, Progressive Bosses, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Prometheus Integration, Quark, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RailsPlus, RandomPatches, Reborn Core, RebornStorage, Redstone Flux, Refined Avaritia, Refined Storage, Refined Storage Addons, Rex's Additional Structures, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roguelike Dungeons, Rough Mobs 2, Ruins Mod, Rustic, Shadowfacts' Forgelin, Simply Jetpacks 2, Solar Flux Reborn, Special AI, Spice of Life: Carrot Edition, SpongeForge, Standard Expansion, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, Storage Tech, Streams, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers Alloying Addon, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, Tweakers Construct, Underground Biomes, UniDict, Universal Modifiers, V0id's Smart Backpacks, Valkyrie Lib, VanillaFix, ViesCraft, Vulcanite, WanionLib, Worley's Caves, XNet, Zero CORE, Zoesteria Biomes, galacticrafttweaker, p455w0rd's Library, projectred-compat
```

Most likely bug #2644 was never fixed and this bug is a duplicate of it.

**Comment by Yorkforce** [comment] 2019-04-29 13:11
@Aaron1011 Its Sky Factory 4, can download it from twitch, curse or atlauncher

**Comment by phit** [comment] 2019-04-30 21:40
please retest with 7.1.6-RC3683

**Comment by Yorkforce** [comment] 2019-04-30 22:29
Fixed in 3683! thanks! @phit

**Closed as completed** 2019-04-30 22:29 UTC
Labels: type: bug, system: phase tracker, version: 1.12, status: waiting for reply
