### ISSUE TITLE
Newer Versions of sponge VS mods

### ISSUE THREAD

**Issue by YOYOK9** [SpongePowered/SpongeForge#1486] opened 2017-05-03 18:42 UTC
Something I have noticed over time is that as Sponge Forge updates it seems to "break" different parts of mods out there. Which makes it hard to run a server with mods that will only half work properly or even not at all. Also making it hard for mod authors to see what's wrong when 1 version it works and the next it fails? 

Is there any news on what's going on and ways for mod authors and Sponge creators to fix this? (most of the time it seems to just be it's the others fault and gets stuck in an endless loop)

Link to sponge forums issue. (with 2 mods so far)
https://forums.spongepowered.org/t/newer-versions-of-spongeforge-crashing-mods-servers/18221

**Comment by ktole1999** [comment] 2017-05-03 18:50
latest and greatest vs stability. they dont always go hand in hand. its also impossible for sponge devs to predict mod behavior

**Comment by YOYOK9** [comment] 2017-05-03 21:44
This is true, Just find it odd how something could be working perfectly fine on the mods side (no updates) then just sponge updates and the mod then breaks. Just seems odd to me that's all.

**Comment by bloodmc** [comment] 2017-05-12 02:50
ExtraUtilities was fixed, update to latest SpongeForge build. Morpheus ticket is a dupe of https://github.com/SpongePowered/SpongeForge/issues/830

Please do not duplicate tickets.

**Closed as completed by bloodmc** 2017-05-12 02:50 UTC
