### ISSUE TITLE
[1.10.2] CME on world generation

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/SpongeForge#957] opened 2016-10-12 10:40 UTC
During world generation the log files get spammed with ConcurrentModificationExceptions

SpongeForge 1.10.2-2092-5.0.0-BETA-1787
FTB Unstable 4.2.8 Modpack

Stacktrace: https://paste.myftb.de/ozajawijez

**Comment by Zidane** [comment] 2016-10-12 13:59
Yeah this is another issue of "Re-entrant World Generation".

@Deamon5550 @gabizou We need a strategy on dealing with mods who are doing this. Can either of you comment?

**Comment by Deamon5550** [comment] 2016-10-12 14:38
Could add a flag to world which causes a check of all setBlock calls during population and if they go out of their bounds throw a thread dump of the mod.

**Comment by FiveEYZ** [comment] 2016-10-12 21:11
this is what chisel tries to do:
https://github.com/Chisel-Team/Chisel/blob/f21c63198426d7bef432c2f10c77c5dd7980867c/src/main/java/team/chisel/common/util/GenerationHandler.java#L66

here is the config i had to disable:
https://github.com/Chisel-Team/Chisel/blob/1.10/dev/src/main/java/team/chisel/common/config/Configurations.java#L86

**Comment by Deamon5550** [comment] 2016-10-12 22:50
Hmm well at a glance that seems to be alright, probably good to have that check anyway so we can catch things.

**Comment by Barteks2x** [comment] 2016-10-13 06:02
Chisel does it right as of [this commit](https://github.com/Chisel-Team/Chisel/commit/48a3fba31d7095bf3f267c0bbdee2de93ae51f09), so if something is wrong with chisel - it's old version.

**Comment by bloodmc** [comment] 2016-10-13 15:05
FTB Unstable 4.2.8 was released before that commit in chisel so @Barteks2x is correct that the issue is the version being used in that specific modpack. However, I'll keep ticket open until @Deamon5550 adds a check to catch this issue in future.

**Comment by Barteks2x** [comment] 2016-10-13 15:14
From the log, another big issue seems to be harvestcraft, I already reported that yesterday (before this issue).

**Comment by bloodmc** [comment] 2016-10-23 20:40
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/952ca27921a25d5a1829e05070816f0d88c4afbb

**Closed by bloodmc** 2016-10-23 20:40 UTC
Labels: 1.10
