### ISSUE TITLE
Exception Exiting Phase  

### ISSUE THREAD

**Issue by axin0452** [SpongePowered/SpongeForge#2723] opened 2019-04-29 09:35 UTC
******************************************************************************************************************************/
/*                                                  Exception Exiting Phase                                                   */
/******************************************************************************************************************************/
/* Something happened when trying to unwind EntityTickPhase                                                                   */
/* PhaseContext :                                                                                                             */
/*     - Source: EntityVillager['Villager'/2436, l='world', x=646.50, y=58.00, z=-158.82]                                     */
/* Phases remaining :                                                                                                         */
/*   - Phase: GeneralPhase{UnwindingState}                                                                                    */
/*     Context:                                                                                                               */
/*     - UnwindingState: EntityTickPhase                                                                                      */
/*     - UnwindingContext: EntityTickContext{isCompleted=true}                                                                */
/*     - IsPostingSpecial: false                                                                                              */
/*         - Source: EntityVillager['Villager'/2436, l='world', x=646.50, y=58.00, z=-158.82]                                 */
/*   - Phase: EntityTickPhase                                                                                                 */
/*     Context:                                                                                                               */
/*     - Source: EntityVillager['Villager'/2436, l='world', x=646.50, y=58.00, z=-158.82]                                     */
/* Stacktrace:                                                                                                                */
/* java.lang.UnsupportedOperationException: null                                                                              */
/*     com.google.common.collect.ImmutableListMultimap.removeAll(ImmutableListMultimap.java:449)                              */
/*     com.google.common.collect.ImmutableListMultimap.removeAll(ImmutableListMultimap.java:52)                               */
/*     org.spongepowered.common.event.tracking.TrackingUtil.checkCancelledEvents(TrackingUtil.java:499)                       */
/*     org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:449)                       */
/*     org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:389)                       */
/*     org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.processCaptures(EntityTickPhaseState.java:103) */
/*     org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.unwind(EntityTickPhaseState.java:93)           */
/*     org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.unwind(EntityTickPhaseState.java:63)           */
/*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:319)                              */
/*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:613)                                      */
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:165)                                 */
/*     net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zmd000(WorldServer.java:3176)                              */
/*     net.minecraft.world.World.func_72866_a(World.java:4159)                                                                */
/*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)                                                     */
/*     net.minecraft.world.World.func_72870_g(World.java:1955)                                                                */
/*     net.minecraft.world.World.func_72939_s(World.java:6789)                                                                */
/*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2290)                                                    */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                            */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                  */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                            */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                     */
/*     java.lang.Thread.run(Unknown Source)                                                                                   */
/*                                                                                                                            */
/* Minecraft : 1.12.2                                                                                                         */
/* SpongeAPI : 7.1.0-4ab0d1a5                                                                                                 */
/* Sponge : 1.12.2-7.1.6-SNAPSHOT                                                                                             */
/* SpongeForge : 1.12.2-2768-7.1.6-RC3680                                                                                     */
/* Minecraft Forge : 14.23.5.2823                                                                                             */
/******************************************************************************************************************************/

**Comment by dualspiral** [comment] 2019-04-29 09:46
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2253.

I realise that this was for a different entity type (Villager here, Zombie in the other error), but please check to see if the error messages look the same. Also, when posting an issue, please don't just post the error - follow the template that we provide. That often allows us to reproduce and isolate the issue much more quickly if necessary, it's there for a reason.

**Closed as completed by dualspiral** 2019-04-29 09:46 UTC
Labels: resolution: duplicate, version: 1.12
