### ISSUE TITLE
Server crash.and the crash-report say cause by sponge

### ISSUE THREAD

**Issue by OldKingisdie** [SpongePowered/SpongeForge#2461] opened 2018-09-27 13:01 UTC
**I am currently running**

- SpongeForge version: 3458
- Forge version: 2705
- Java version: java8
- Operating System:linux

- Plugins/Mods:
   in crash-report
**Issue Description**
    I find boss with fast speed in Twilight forest . Twilight forest chunks generation too fast and then my server crash . and I found the crash-report mention sponge.so maybe it's a sponge error?

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2018-09-27 18:42:25 HKT
Description: Exception ticking world

java.lang.RuntimeException: Exception creating chunk packet for chunk at '43 46'!
    at net.minecraft.network.play.server.SPacketChunkData.redirect$onExtractChunkData$zja000(SourceFile:547)
    at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:40)
    at net.minecraft.server.management.PlayerChunkMapEntry.sendToPlayers(PlayerChunkMapEntry.java:157)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:165)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to serialize chunk data to buffer. Attempted to write entry long[31]: 0at writer index: 44995 with size 8
    at net.minecraft.world.chunk.BlockStateContainer.redirect$onSpongeWriteLongArrayPacketBuffer$zmf000(BlockStateContainer.java:652)
    at net.minecraft.world.chunk.BlockStateContainer.write(BlockStateContainer.java:126)
    at net.minecraft.network.play.server.SPacketChunkData.extractChunkData(SourceFile:122)
    at net.minecraft.network.play.server.SPacketChunkData.redirect$onExtractChunkData$zja000(SourceFile:545)
    ... 9 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: DIM7
  All players: 1 total; [EntityPlayerMP['chuxuan'/243542, l='DIM7', x=686.31, y=57.37, z=676.31]]
  Chunk stats: ServerChunkCache: 949 Drop: 0
  Level seed: 1490669182312984176
  Level generator: ID 11 - lostcities, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (0,30,0), Chunk: (at 0,1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 6788825 game time, 6788825 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 20556 (now: true), thunder time: 149719 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
  Phase Stack: [Empty stack]

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 3.16.0-4-amd64
  Java Version: 1.8.0_144, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1389222128 bytes (1324 MB) / 3864731648 bytes (3685 MB) up to 16848388096 bytes (16067 MB)
  JVM Flags: 2 total; -Xincgc -Xmx16G
  IntCache: cache: 0, tcache: 37, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2705 116 mods loaded, 116 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State     | ID                                | Version                     | Source                                             | Signature                                |
       |:--------- |:--------------------------------- |:--------------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | UCHIJAAAA | minecraft                         | 1.12.2                      | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | mcp                               | 9.42                        | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | FML                               | 8.0.99.99                   | forge-1.12.2-14.23.4.2705-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | forge                             | 14.23.4.2705                | forge-1.12.2-14.23.4.2705-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | jecharacters                      | 1.12.0-2.3.2                | JustEnoughCharacters-1.12.0-2.3.2.jar              | None                                     |
       | UCHIJAAAA | spongeapi                         | 7.1.0-ff990df               | [核心]spongeforge-1.12.2-2705-7.1.0-BETA-3458.jar    | None                                     |
       | UCHIJAAAA | sponge                            | 1.12.2-2705-7.1.0-BETA-3458 | [核心]spongeforge-1.12.2-2705-7.1.0-BETA-3458.jar    | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
       | UCHIJAAAA | openmodscore                      | 0.11.5                      | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | foamfixcore                       | 7.7.4                       | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | catclearlag                       | 0.8.3                       | [插件]CatClearLag-0.8.3.jar                          | None                                     |
       | UCHIJAAAA | placeholderapi                    | 4.4                         | [插件]PlaceholderAPI-4.4.jar                         | None                                     |
       | UCHIJAAAA | command-utils                     | 2.2.4                       | [插件]command-utils-2.2.4.jar                        | None                                     |
       | UCHIJAAAA | commandsync                       | 2.5                         | [插件]CommandSync.jar                                | None                                     |
       | UCHIJAAAA | pjc                               | 0.2.2                       | [插件]projectcore-7.1.0-0.2.2.jar                    | None                                     |
       | UCHIJAAAA | easykits                          | 0.2.0                       | [插件]easykits-7.1.0-0.2.0.jar                       | None                                     |
       | UCHIJAAAA | economylite                       | 2.15.0                      | [插件]EconomyLite-7.1.0-2.15.0.jar                   | None                                     |
       | UCHIJAAAA | nucleus                           | 1.6.0-S7.1                  | [插件]Nucleus-1.6.0-S7.1-MC1.12.2-plugin.jar         | None                                     |
       | UCHIJAAAA | nucleus-gluon                     | 1.0.4                       | [插件]Gluon-1.0.4.jar                                | None                                     |
       | UCHIJAAAA | holograms                         | 3.1.5                       | [插件]holograms-3.1.5.jar                            | None                                     |
       | UCHIJAAAA | hunger-keeper                     | 1.0.0                       | [插件]HungerKeeper-1.0.0.jar                         | None                                     |
       | UCHIJAAAA | invsync                           | 0.6.18.204                  | [插件]InvSync-0.6.18.204.jar                         | None                                     |
       | UCHIJAAAA | itemchat                          | 1.4.0                       | [插件]ItemChat-1.4.0.jar                             | None                                     |
       | UCHIJAAAA | joincommand                       | 1.1                         | [插件]JoinCommand-1.0-SNAPSHOT.jar                   | None                                     |
       | UCHIJAAAA | kt-skript                         | 1.1.3                       | [插件]kt-skript-1.1.3.jar                            | None                                     |
       | UCHIJAAAA | langswitch                        | 1.2                         | [插件]LangSwitch-1.2.jar                             | None                                     |
       | UCHIJAAAA | luckperms                         | 4.2.40                      | [插件]LuckPerms-Sponge-4.2.40.jar                    | None                                     |
       | UCHIJAAAA | mmcrestrict                       | 1.5.1                       | [插件]MMCRestrict-1.5.1-API-7.jar                    | None                                     |
       | UCHIJAAAA | multichat                         | 1.5                         | [插件]multichat-1.5.jar                              | None                                     |
       | UCHIJAAAA | noportal                          | 0.1.1                       | [插件]NoPortal-0.1.2.jar                             | None                                     |
       | UCHIJAAAA | pixelautomessages                 | 1.0.3                       | [插件]PixelAutoMessages-1.0.3-b15.jar                | None                                     |
       | UCHIJAAAA | pjb                               | 0.2.0                       | [插件]projectborders-7.1.0-0.2.0.jar                 | None                                     |
       | UCHIJAAAA | inspector                         | 0.6.5                       | [插件]Re-Inspector-0.1.jar                           | None                                     |
       | UCHIJAAAA | serverteleport                    | 0.1.0-SNAPSHOT              | [插件]ServerTeleport-0.1.0-SNAPSHOT.jar              | None                                     |
       | UCHIJAAAA | stopspread                        | 0.1.1                       | [插件]StopSpread-0.1.1.jar                           | None                                     |
       | UCHIJAAAA | vshop                             | 1.9                         | [插件]VillagerShops-1.9.jar                          | None                                     |
       | UCHIJAAAA | virtualchest                      | 1.0.0-rc-1                  | [插件]VirtualChest-1.0.0-rc-1.jar                    | None                                     |
       | UCHIJAAAA | actuallyadditions                 | 1.12.2-r140                 | ActuallyAdditions-1.12.2-r140.jar                  | None                                     |
       | UCHIJAAAA | appliedenergistics2               | rv5-stable-11               | appliedenergistics2-rv5-stable-11.jar              | None                                     |
       | UCHIJAAAA | bdlib                             | 1.14.3.12                   | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
       | UCHIJAAAA | ae2stuff                          | 0.7.0.4                     | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
       | UCHIJAAAA | applecore                         | 3.1.3                       | AppleCore-mc1.12.2-3.1.3.jar                       | None                                     |
       | UCHIJAAAA | crafttweaker                      | 4.1.9                       | CraftTweaker2-1.12-4.1.9.jar                       | None                                     |
       | UCHIJAAAA | mtlib                             | 3.0.5                       | MTLib-3.0.5.jar                                    | None                                     |
       | UCHIJAAAA | modtweaker                        | 4.0.12                      | modtweaker-4.0.12.jar                              | None                                     |
       | UCHIJAAAA | jei                               | 4.11.0.204                  | jei_1.12.2-4.11.0.204.jar                          | None                                     |
       | UCHIJAAAA | appleskin                         | 1.0.9                       | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | UCHIJAAAA | betterbuilderswands               | 0.12.0                      | BetterBuildersWands-1.12-0.12.0.251.jar            | None                                     |
       | UCHIJAAAA | betterquesting                    | 3.5.266                     | BetterQuesting-3.5.266.jar                         | None                                     |
       | UCHIJAAAA | codechickenlib                    | 3.2.0.345                   | CodeChickenLib-1.12.2-3.2.0.345-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | redstoneflux                      | 2.0.2                       | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | brandonscore                      | 2.4.3                       | BrandonsCore-1.12.2-2.4.3.168-universal.jar        | None                                     |
       | UCHIJAAAA | chameleon                         | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | UCHIJAAAA | chisel                            | MC1.12.2-0.2.1.35           | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | UCHIJAAAA | cofhcore                          | 4.5.2                       | CoFHCore-1.12.2-4.5.2.19-universal.jar             | None                                     |
       | UCHIJAAAA | cofhworld                         | 1.2.0                       | CoFHWorld-1.12.2-1.2.0.5-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | mantle                            | 1.12-1.3.2.24               | Mantle-1.12-1.3.2.24.jar                           | None                                     |
       | UCHIJAAAA | endercore                         | 1.12.2-0.5.35               | EnderCore-1.12.2-0.5.35.jar                        | None                                     |
       | UCHIJAAAA | thermalfoundation                 | 2.5.0                       | ThermalFoundation-1.12.2-2.5.0.19-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | draconicevolution                 | 2.3.12                      | Draconic-Evolution-1.12.2-2.3.12.297-universal.jar | None                                     |
       | UCHIJAAAA | thermalexpansion                  | 5.5.0                       | ThermalExpansion-1.12.2-5.5.0.29-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | enderio                           | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderiointegrationtic             | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | twilightforest                    | 3.8.654                     | twilightforest-1.12.2-3.8.654-universal.jar        | None                                     |
       | UCHIJAAAA | tconstruct                        | 1.12.2-2.10.1.87            | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
       | UCHIJAAAA | conarm                            | 1.0.1.2                     | conarm-1.12.2-1.0.1.2.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCHIJAAAA | containerfix                      | 1.0                         | ContainerFix+MC1.12.2+v1.0.jar                     | None                                     |
       | UCHIJAAAA | crafttweakerjei                   | 2.0.2                       | CraftTweaker2-1.12-4.1.9.jar                       | None                                     |
       | UCHIJAAAA | cucumber                          | 1.1.0                       | cucumber-1.12-1.1.0.jar                            | None                                     |
       | UCHIJAAAA | eiorteis                          | 1.12.2-3.0                  | eiorteis-3.0.jar                                   | None                                     |
       | UCHIJAAAA | enderiobase                       | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderioconduits                   | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderioconduitsopencomputers      | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderiointegrationforestry        | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderiointegrationticlate         | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | ftblib                            | 5.2.0.30                    | FTBLib-5.2.0.30.jar                                | None                                     |
       | UCHIJAAAA | enderiomachines                   | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderiopowertools                 | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
       | UCHIJAAAA | enderstorage                      | 2.4.4.132                   | EnderStorage-1.12.2-2.4.4.132-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | exnihilocreatio                   | 1.12-0.2.4                  | exnihilocreatio-1.12-0.2.4.jar                     | None                                     |
       | UCHIJAAAA | excompressum                      | 3.0.22                      | ExCompressum_1.12.2-3.0.22.jar                     | None                                     |
       | UCHIJAAAA | extracells                        | 2.5.13                      | ExtraCells-1.12.2-2.5.13a60.jar                    | None                                     |
       | UCHIJAAAA | extrautils2                       | 1.0                         | extrautils2-1.12-1.8.5.jar                         | None                                     |
       | UCHIJAAAA | zerocore                          | 1.12-0.1.2.2                | zerocore-1.12-0.1.2.2.jar                          | None                                     |
       | UCHIJAAAA | bigreactors                       | 1.12.2-0.4.5.49             | ExtremeReactors-1.12.2-0.4.5.49.jar                | None                                     |
       | UCHIJAAAA | fastleafdecay                     | v14                         | FastLeafDecay-v14.jar                              | None                                     |
       | UCHIJAAAA | foamfix                           | 0.9.9.1-1.12.2              | foamfix-0.9.9.1-1.12.2-anarchy.jar                 | None                                     |
       | UCHIJAAAA | ftbutilities                      | 5.2.0.32                    | FTBUtilities-5.2.0.32.jar                          | None                                     |
       | UCHIJAAAA | grimoireofgaia                    | 1.6.3                       | GrimoireOfGaia3-1.12.2-1.6.3.jar                   | None                                     |
       | UCHIJAAAA | infernalmobs                      | 1.7.5                       | InfernalMobs-1.12.2.jar                            | None                                     |
       | UCHIJAAAA | inventorytweaks                   | 1.63+release.109.220f184    | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJAAAA | jaopca                            | 1.12.2-2.2.8.91             | JAOPCA-1.12.2-2.2.8.91.jar                         | None                                     |
       | UCHIJAAAA | oredictinit                       | 1.12.2-2.2.1.68             | JAOPCA-1.12.2-2.2.8.91.jar                         | None                                     |
       | UCHIJAAAA | longerdays                        | 1.0.4                       | longerdays-1.0.4.jar                               | None                                     |
       | UCHIJAAAA | lostcities                        | 2.0.10                      | lostcities-1.12-2.0.10.jar                         | None                                     |
       | UCHIJAAAA | mekanism                          | 1.12.2-9.4.13.349           | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
       | UCHIJAAAA | mysticalagriculture               | 1.6.12                      | mysticalagriculture-1.12-1.6.12.jar                | None                                     |
       | UCHIJAAAA | mysticalagradditions              | 1.2.8                       | mysticalagradditions-1.12-1.2.8.jar                | None                                     |
       | UCHIJAAAA | nonetherportals                   | 1.0.0                       | nonetherPortals_v1.0.0formc1.12.2.jar              | None                                     |
       | UCHIJAAAA | openmods                          | 0.11.5                      | OpenModsLib-1.12.2-0.11.5.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAA | openblocks                        | 1.7.6                       | OpenBlocks-1.12.2-1.7.6.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAA | p455w0rdslib                      | 2.0.29                      | p455w0rdslib-1.12-2.0.29.jar                       | None                                     |
       | UCHIJAAAA | plustic                           | 6.5.2.0                     | plustic-6.5.2.0.jar                                | None                                     |
       | UCHIJAAAA | roughmobs                         | 2.0.0                       | roughmobs2-1.12.2_2.0.9.jar                        | None                                     |
       | UCHIJAAAA | bq_standard                       | 3.4.143                     | StandardExpansion-3.4.143.jar                      | None                                     |
       | UCHIJAAAA | storagedrawers                    | 1.12-5.3.5                  | StorageDrawers-1.12.2-5.3.7.jar                    | None                                     |
       | UCHIJAAAA | thermalcultivation                | 0.3.0                       | ThermalCultivation-1.12.2-0.3.0.7-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | thermaldynamics                   | 2.5.1                       | ThermalDynamics-1.12.2-2.5.1.14-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | thermalinnovation                 | 0.3.0                       | ThermalInnovation-1.12.2-0.3.0.7-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | tinkersjei                        | 1.0                         | tinkersjei-1.0.jar                                 | None                                     |
       | UCHIJAAAA | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957    | TinkerToolLeveling-1.12.2-1.0.5.jar                | None                                     |
       | UCHIJAAAA | treegrowingsimulator              | 0.0.4                       | TreeGrowingSimulator2017-1.0.1.jar                 | None                                     |
       | UCHIJAAAA | vanillafix                        | 1.0.9-97                    | VanillaFix-1.0.9-97.jar                            | None                                     |
       | UCHIJAAAA | wct                               | 3.9.67                      | WirelessCraftingTerminal-1.12.2-3.9.67.jar         | None                                     |
       | UCHIJAAAA | wrapup                            | 1.12-1.1.3                  | WrapUp-1.12-1.1.3.jar                              | None                                     |
  Loaded coremods (and transformers): JechCore (JustEnoughCharacters-1.12.0-2.3.2.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
                                        openmods.core.OpenModsClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.1.16.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      SpongeCoremod ([核心]spongeforge-1.12.2-2705-7.1.0-BETA-3458.jar)
                                        org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
  AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
  List of loaded APIs: * actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r140.jar
                       * AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.3.jar
                       * appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
                       * Baubles|API (1.4.0.2) from WirelessCraftingTerminal-1.12.2-3.9.67.jar
                       * BetterQuesting|API (3.1) from BetterQuesting-3.5.266.jar
                       * BetterQuesting|API2 (3.1) from BetterQuesting-3.5.266.jar
                       * BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
                       * bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.49.jar
                       * Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * cofhapi (2.5.0) from CoFHCore-1.12.2-4.5.2.19-universal.jar
                       * ctm-api (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
                       * ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
                       * ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
                       * ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
                       * ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
                       * DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.12.297-universal.jar
                       * enderioapi (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.29.jar
                       * ExCompressum|API (1.0) from ExCompressum_1.12.2-3.0.22.jar
                       * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.11.0.204.jar
                       * MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
                       * MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
                       * MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
                       * MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
                       * MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
                       * MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
                       * MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
                       * openblocks|api (1.2) from OpenBlocks-1.12.2-1.7.6.jar
                       * ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.29.jar
                       * StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
                       * StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
                       * StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
                       * StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
                       * StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
                       * StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
                       * wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.67.jar
                       * zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
                       * zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
                       * zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
                       * zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Offline mode for dedicated servers is NOT supported by Ender IO.
                             An unsupported base software is installed: 'sponge'. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Unknown
  Profiler Position: N/A (disabled)
  Player Count: 3 / 50; [EntityPlayerMP['louisahdyer'/238793, l='world', x=334.48, y=42.20, z=-7378.87], EntityPlayerMP['2108853'/230994, l='world', x=-7968.93, y=133.00, z=5374.59], EntityPlayerMP['chuxuan'/243542, l='DIM7', x=686.31, y=57.37, z=676.31]]
  Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
  Type: Dedicated Server (map_server.txt)

```

**Comment by gabizou** [comment] 2018-09-27 16:53
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2405

**Closed as completed by gabizou** 2018-09-27 16:53 UTC
Labels: resolution: duplicate, version: 1.12
