### ISSUE TITLE
Grave losing items when breaking grave

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1097] opened 2016-12-09 16:30 UTC
Players noticed after I upgraded to 1971 from 1955 that when they break their graves they no longer get all their items (full stacks) back.

Reproduction:
1. fill your inventory http://i.imgur.com/dJeT5bJ.png
2. do /kill
3. break your grave http://i.imgur.com/odbtaQA.png

Since this worked with previous Sponge versions it's unlikely to be a mod issue and the deathnote also lists all items properly.

I could reproduce it with just these 2 mods
GraveStone Mod 1.5.9 https://minecraft.curseforge.com/projects/gravestone-mod
spongeforge-1.10.2-2171-5.1.0-BETA-1973

**Comment by FiveEYZ** [comment] 2016-12-09 16:50
same thing is happening for me, here is my "Latest.log" where this happen: https://gist.github.com/FiveEYZ/258da8f45e3c7473df41241ff052f84a#file-latest-log-L3608

**Comment by phit** [comment] 2016-12-10 13:35
this also happens when breaking hoppers

**Comment by inklit** [comment] 2016-12-10 16:37
@phit I can't reproduce with hoppers.

**Comment by phit** [comment] 2016-12-10 16:42
https://phit.link/files/share/2016-12-10_17-42-27.mp4

with spongeforge-1.10.2-2171-5.1.0-BETA-1976

**Comment by KasperFranz** [comment] 2016-12-13 20:25
any update @Aaron1011 

it is with EnderIO spamming alot (and making it nonresponding for some minutes after this) 

I am currently looking into which version this began in to narrow down what is causing it :)

**Comment by KasperFranz** [comment] 2016-12-13 20:41
it isn't present in 1967 - but in 1971 so this must be the cause of it? 

Connected [commit ](https://github.com/SpongePowered/SpongeForge/commit/622b29e6eaf96e8e9ab476e890e8cceb77b655ba) by @bloodmc 

log: https://gist.github.com/KasperFranz/d481ac6bb013c8bfbe3473f246c8c364

**Comment by Aaron1011** [comment] 2016-12-13 20:46
@KasperFranz: Can you set `verbose-errors` to `true` in your global.conf, and restart your server? The new errors will be much more helpful.

**Comment by KasperFranz** [comment] 2016-12-13 20:47
ofc gonna try that with 1 item in inventory

**Comment by KasperFranz** [comment] 2016-12-13 20:51
Here you go:

FML:  https://gist.github.com/KasperFranz/d77b670e0215a9060488f85893bebdf8
latest.log: https://gist.github.com/KasperFranz/7f79bec8bc33e4f4e3b6b22bff67b0b1

**Comment by KasperFranz** [comment] 2016-12-13 21:19
I can also reproduce with hoppers (when grave and sponge is in the pack) 
[FML](https://gist.github.com/KasperFranz/48763dd4b58988ee58893a215be94c1d)
[latest.log](https://gist.github.com/KasperFranz/7997907a6daf6c23dd47a153583a891a)

If you need more from me just say so :)

**Comment by kashike** [comment] 2016-12-14 03:37
Looks like GitHub didn't close this issue when @Aaron1011 referenced it above - closing.

**Closed as completed by kashike** 2016-12-14 03:37 UTC

**Comment by Aaron1011** [comment] 2016-12-14 03:40
Github only closes issues automatically for commits on the default branch, to prevent an issue from being closed as soon as someone creates a feature branch to start working on it.
