### ISSUE TITLE
Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mistek131995** [SpongePowered/SpongeForge#2804] opened 2019-06-06 12:29 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6-RC3755
- Forge version: 1.12.2 - 14.23.5.2838
- Java version:  Version 8 Update 211 build 1.8.0_211-b12
- Operating System: Windows Server 2012 x64

```
[15:24:45] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6-RC3755]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
```

**Comment by dualspiral** [comment] 2019-06-06 12:36
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2803

Please don't post the same issue multiple times, once is enough. We will get to it when we get chance.

**Closed as completed by dualspiral** 2019-06-06 12:36 UTC
Labels: resolution: duplicate, version: 1.12
