### ISSUE TITLE
Draconic Evolution Loot Core not being spawned

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1903] opened 2017-12-20 04:59 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2783
- Forge version:  1.12.2-14.23.1.2565
- Java version:  8
- Operating System: Windows 10

- Plugins/Mods: 
 SpongeForge-1.12.2-2555-7.0.0-BETA-2783
Draconic-Evolution-1.12-2.3.5.269-universal
BrandonsCore-1.12-2.3.4.134-universal
RedstoneFlux-1.12-2.0.1.2-universal
CodeChickenLib-1.12.2-3.1.5.331-universal

**Issue Description**
So basically DE *(known as Draconic Evolution)*
have this thing called LootCore basically when you mine someone 11x11 with  using staff of power it put the drop item into a thing called loot core when your inventory is full it does that
more information can be found here https://github.com/brandon3055/Draconic-Evolution/issues/996
this can have performance issue when a lot of dropped items are on the floor and cause by DE not having their LootCore

When you have SF installed and those mods i listed above 
then go into survival and have a Staff of power then make your staff of power either 11x11 or 5x5 then mine as once you inventory is full it should start to show on the ground lootcore
but it sometimes doesn't  and when it does it, it only collect some of the item and not all of them here a picture of what i am talking about 
![e8536ebe56f1feae263cf8cd39c3f5d4](https://user-images.githubusercontent.com/30296350/34192062-7aeb1330-e519-11e7-8de9-aa6762ab2ac1.png)
this does not happen when you are in singleplayer or without SF

**Comment by DumbSlayer** [comment] 2017-12-22 23:05
ima use it to lag the shit out of servers

**Comment by brandon3055** [comment] 2017-12-26 03:08
DE collects items via the forge Entity join world event in order to capture all possible drops from a block. I suspect sponge is somehow interfering with this event 
https://github.com/brandon3055/BrandonsCore/blob/master/src/main/java/com/brandon3055/brandonscore/handlers/BCEventHandler.java

**Comment by Zidane** [comment] 2018-01-12 15:26
Sponge isn't interfering with the event, it just isn't expecting someone else to be performing item captures like we are doing for our PhaseTracker. I'll investigate to see what can be done.

**Comment by Nitroxko** [comment] 2018-04-01 16:39
This is a bump, because this issue is still happening.

**Comment by gabizou** [comment] 2018-05-09 03:11
With other issues having been verified fixed in #2110, I'm now progressing to start working on this issue in that branch.

**Comment by gabizou** [comment] 2018-05-14 17:28
Ok, after some small refactoring and hooking into the `World.getEntitiesWithinAABB` method, I can now verify that block drop captures are working for the purposes of DraconicEvolution's uses. Here's an example of it working (I assumed it wasn't working for a brief period due to the loot core just filling the inventory instead of just dropping a loot core, but as the player inventory filled up, I found that it was working as intended):
![2018-05-14_10 26 17](https://user-images.githubusercontent.com/1203877/40013121-831605aa-5761-11e8-8191-e11ef7791af9.png)
I'll be pushing up a commit and wrapping up this refactor likely today.

**Closed as completed** 2018-05-14 19:16 UTC
Labels: system: event, version: 1.12

**Comment by JoeSGT** [comment] 2018-05-14 21:36
tested and @gabizou https://gist.github.com/JoeSGT/32bbb82d30b66eab30f752df6108e163 whenever you keep mining and you'll get the error I mine at 5x5 but it worked, this error happen whenever i attempt to mine the loot core it's self
reason for this cause i wanted too spam it xD

**Comment by gabizou** [comment] 2018-05-14 22:17
@JoeSGT open a new issue please. and can you provide explanation on how to do this step by step, and stop copying from windows console (it removes spaces and makes logs illegible).
