### ISSUE TITLE
WrapperCommandSource errors

### ISSUE THREAD

**Issue by Noppes** [SpongePowered/SpongeForge#1496] opened 2017-05-07 16:50 UTC
My mod uses a custom CommandBlockBaseLogic which sponge seems to have issues with.

Sponge 1.10.2-2281-5.2.0-BETA-2292

```
java.lang.AbstractMethodError: noppes.npcs.NoppesUtilServer$1$1.asCommandSource()Lorg/spongepowered/api/command/CommandSource;                      
     org.spongepowered.common.command.WrapperCommandSource.of(WrapperCommandSource.java:116)                                                         
     net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1082)                                                                 
     noppes.npcs.NoppesUtilServer.runCommand(NoppesUtilServer.java:252)                                                                              
     noppes.npcs.NoppesUtilServer.runCommand(NoppesUtilServer.java:163)                                                                              
     noppes.npcs.NoppesUtilServer.openDialog(NoppesUtilServer.java:151)                                                                              
     noppes.npcs.entity.EntityNPCInterface.func_184645_a(EntityNPCInterface.java:451)                                                                
     net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1229)                                                                         
     net.minecraft.entity.player.EntityPlayer.func_184822_a(EntityPlayer.java:1161)                                                                  
     net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2364)                                                        
     net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68)                                                                 
     net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12)                                                                 
     org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157)                                                       
     org.spongepowered.common.network.PacketUtil$$Lambda$832/581692968.call(Unknown Source)                                                          
     org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160)                                                       
     org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156)                                                                
     net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539)                                                        
     net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)                                                                                     
     java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)                                                                             
     java.util.concurrent.FutureTask.run(Unknown Source)                                                                                             
     net.minecraft.util.Util.func_181617_a(SourceFile:45)                                                                                            
     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241)                                                                
     net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928)                                                           
     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)                                                                     
     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                                                           
     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                                                                     
     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                                                              
     java.lang.Thread.run(Unknown Source)
```

**Comment by JBYoshi** [comment] 2017-05-08 11:23
Duplicate of #1333.

**Closed as completed** 2017-05-08 16:35 UTC
Labels: type: bug, resolution: duplicate, system: command

**Comment by Noppes** [comment] 2017-05-08 16:53
The other one is marked as incompatablity with a specific mod. Its not labeled either?

**Comment by stephan-gh** [comment] 2017-05-08 17:55
@Noppes The cause is the same, it affects multiple mods.
