### ISSUE TITLE
inventory tweaks DoS

### ISSUE THREAD

**Issue by gearkill** [SpongePowered/SpongeForge#2377] opened 2018-08-12 02:07 UTC
**I am currently running**

- SpongeForge version:  3396
- Minecraft Version: 1.12.2
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: 8
- Operating System:

- Plugins/Mods:
AutoBroadcasterSponge-0.2.1.jar
CmdCalendar-mc1.10.2-v1.1.1.jar
command-utils-2.2.4.jar
CommandSync.jar
DailyRewards-api7-1.3.2 (1).jar
Daycare-S7.1.0-0.9.0-BETA.jar
EasyScoreboards.jar
EconomyLite-7.1.0-2.14.4.jar
entity-particles-3.0.0.jar
GFCore-1.0.jar
griefprevention-1.12.2-4.3.0.646 (1).jar
GTS-3.11.0-S7.1.jar
GWMCrates 2.3.4.jar
GWMLibrary 1.2.jar
holograms-3.1.jar
Impactor-S7.1.0-1.4.0.jar
LuckPerms-Sponge-4.2.60.jar
MCClans-1.0-PT-BR.jar
MMCReboot-2.3.0-API-7.jar
MMCRestrict-1.4.3-API-7.jar
NewHonor-2.0.0-pre-17-b213.jar
Nucleus-1.5.2-S7.0-MC1.12.2-plugin.jar
PacketGate-0.1.1.jar
ParticleEffectCombinator-0.2.0.jar
PixelExtras-1.12.2-2.3.9-universal.jar
PixelHunt-1.1.1-MC1.12.2-F2705-S7.1.0 (1).jar
Pixelmon-1.12.2-6.3.4-server.jar
PixelmonEconomyBridge-1.12.2-2.0.1.jar
PixelVip-2.0.3-b34-Universal.jar
PlaceholderAPI-4.5.1.jar
pokeclear-1.12.2-2555-r7.0.0.jar
Referrals-1.3.0-7.jar
SafeTrade-1.12.2-1.0.1.jar
serious-nuvotifier-universal-API7-2.3.5.jar
seriousvote-4.8.4.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3396.jar
TabBlocker-1.0-SNAPSHOT.jar
TrainerCommands-1.12-2.4.0-universal (1).jar
TriviaQuest-s7.1-v2.1.1.jar
UltimateChat-1.8.5-b151-Universal (1).jar
VIP-Slots-1.0.jar
VirtualChest-1.0.0-beta-6.jar
WonderTradeS-s7.1-v1.0.3.jar
worldedit-sponge-6.1.9-SNAPSHOT-dist.jar
xPPayDay-0.2-MC1.12.2-F2611-S7.1.0.jar
zpixelmonplaceholders-1.4.0.jar
zVoteParty-2.1.1 (1).jar

**Issue Description**
before it generated this error, in the new version does not generate https://hastebin.com/vugalibila.md

 in 3396 it hangs and it does not allow me to generate log, I need to kill the process and when this occurs it does not generate log
no more error appears,
[22:15:18] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 17608ms behind, skipping 352 tick(s)
just this and hangs

the video below shows how any player can knock down a server using mod inventory tweaks

https://www.youtube.com/watch?v=3QSN10qfNuY

in new version it does not generate logs only the error 
[Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 17608ms behind, skipping 352 tick(s)
and hangs every console , 
I need to kill the process and start the script manually

https://hastebin.com/jawaduzeyo.sql

**Comment by DiamondArrow** [comment] 2018-08-12 08:17
The issue he seems to be describing is Inventory Tweaks trying to sort items in GUIs. This causes the plugin to be constantly triggered and spams console with something like below before lagging or in his case, crashing from lag.


GTS:
`[03:44:30] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Impactor API (Debug) Processing inventory click event for GearKillr...
[03:44:30] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Impactor API (Debug)   Title: GTS » Listingsr
[03:44:30] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Impactor API (Debug)   Provider: GTS-3.11.0-S7.1`

VirtualChest using PlaceHolderAPI
`[03:44:33] [Server thread/WARN] [Sponge]: Could not find slot #%s in Container %s`


He said this doesn't happened in sponge 3206

**Comment by Aaron1011** [comment] 2018-08-12 16:38
This sounds like it could be a bug in whatever plugin is responsible for managing that custom GUI.

To debug this further, I'll either need access to the plugin used in the video, or a way to reproduce the crash without using that plugin.

**Comment by gearkill** [comment] 2018-08-12 17:00
so far I have tested only with the GTS and the virtual chest

**Comment by Aaron1011** [comment] 2018-08-12 17:39
Can you provide a series of step-by-step instructions for reproducing this, starting with only a plain SpongeForge server?

**Comment by gearkill** [comment] 2018-08-12 20:50
https://drive.google.com/file/d/1AhaL_r7Nj7vXUiCsLkZ62ZaDnO2t_UHJ/view?usp=sharing
in sponge 1.12.2-2705-7.1.0-BETA-3399
inventory tweaks + autoclick or macro 

I think it gives you a better understanding of how it works

**Comment by phit** [comment] 2018-12-31 01:50
so this is basically an event DoS, not sure what Sponge is supposed to do in this case

**Comment by dualspiral** [comment] 2020-06-09 09:50
As this is two years old and it basically looks like Sponge can't do anything, I'm closing this. If this is still an issue, please create a new issue with up to date information and a minimal reproducable test case.

Thanks!

**Closed as completed by dualspiral** 2020-06-09 09:50 UTC
Labels: status: input wanted, system: inventory, version: 1.12
