### ISSUE TITLE
LivingDropsEvent fired twice

### ISSUE THREAD

**Issue by henkelmax** [SpongePowered/SpongeForge#1974] opened 2018-01-27 18:29 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2555-7.1.0-BETA-2851
- Forge version: forge-1.12.2-14.23.1.2555
- Java version: jre1.8.0_144
- Operating System: Windows 10

- Plugins/Mods: GraveStone Mod 1.10.0 (Works fine without SpongeForge)
    
**Issue Description**
The LivingDropsEvent is fired twice when a player dies. The first time with all drops and exactly after that again but with an empty item list.

log file
https://gist.github.com/henkelmax/d1cc620adb05ff2fea94f9628f2a2e95

**Comment by ryantheleach** [comment] 2018-01-27 18:32
Hey Henkelmax, was this working before 2851? Faith and I just finished a fix for plugins wanting to implement soulbound that may have touched this code. If you are available on discord atm, we would love to chat. https://discord.gg/PtaGRAs

**Comment by henkelmax** [comment] 2018-01-27 19:02
I can confirm it for the following versions:
spongeforge-1.12.2-2555-7.0.0-BETA-2764
spongeforge-1.12.2-2555-7.1.0-BETA-2848

**Comment by ryantheleach** [comment] 2018-01-27 19:09
Thanks.

**Comment by mindcloud69** [comment] 2018-01-27 19:22
I am seeing this issue as well FTB Revelations. 1.3.0
https://gist.github.com/mindcloud69/b5d0503f853d50b9776fafc66ab79d09

**Comment by mindcloud69** [comment] 2018-01-27 19:24
No it was still having the error I was using 2834 until earlier today and I was seeing the issue on that version as well.

**Comment by ryantheleach** [comment] 2018-01-27 19:39
We are investigating it now. It's apparent that the event was firing for LivingEntityBase as well as Players.

**Comment by ryantheleach** [comment] 2018-01-27 19:57
Duplicate of : https://github.com/SpongePowered/SpongeForge/issues/1859 Please continue discussion there if you have additional information, but we are partially through a fix.

**Closed as completed by ryantheleach** 2018-01-27 19:57 UTC
Labels: type: bug, status: accepted, system: event, type: mod incompatibility, version: 1.12
