### ISSUE TITLE
entity tracking error due to already tracked entity when ZAWA mob drops loot

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2350] opened 2018-07-29 23:20 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3358
- Forge version: 14.23.4.2739
- Java version: 1.8.0_171-b10
- Operating System: CentOS

- Plugins/Mods:
zawa - 1.3.2 (1.12.2).jar    https://minecraft.curseforge.com/projects/zoo-wild-animals-rebuild
etc.

**Issue Description**
Console reports entity tracking errors for each entity dropped by ZAWA mobs when killed by a player.

https://gist.github.com/LemADEC/d3ab05fde5c96861133dd831ecfe55b3

1- spawn a ZAWA mob
2- kill it

**Comment by LemADEC** [comment] 2018-08-04 23:11
Is there any way to disable this callstack from spamming our console?

**Comment by ryantheleach** [comment] 2018-08-05 12:54
(At first glance) This appears to be a mod bug, that we are creating louder errors for to help find and catch the problem. Unfortunately that mod isn't open source that I can see, so finding the issue and who should own it, will take a larger amount of time.

I recommend you also report this to ZAWA.

**Comment by LemADEC** [comment] 2018-08-06 04:30
https://minecraft.curseforge.com/projects/zoo-wild-animals-rebuild/issues/26

**Comment by gkazan** [comment] 2018-08-08 03:01
Is this an issue with when the entities are killed and drop items?

Edit: ZAWA dev btw

**Comment by LemADEC** [comment] 2018-08-08 08:17
Issue is reproduced by killing any ZAWA mobs in single player, using:
moon-core 7.0 (1.12)
spongeforge-1.12.2-2705-7.1.0-BETA-3375
zawa - 1.3.2 (1.12.2)

https://gist.github.com/LemADEC/c084b8fa8cb0d86832e66d485957b29e

**Comment by gkazan** [comment] 2018-08-08 21:55
Ok I'll try to run sponge with my development build and fix the issue or I'll try to send the onDeath code here when I get a chance.

**Comment by gkazan** [comment] 2018-08-12 02:16
I removed my onDeath override so it just calls the EntityTameable's onDeath now, so as long as there is no issue with the EntityTameable's onDeath the next update to zawa should fix the problem. After I release a new zawa update (I cannot say when this will be yet) if the issue is still present please put in a new issue on zawa's curse page.

**Comment by phit** [comment] 2018-09-14 01:11
gonna assume this was fixed by the mod, thanks @0SoggyMustache0 
once the new zawa build is out and this still happens please open a new issue

**Closed as completed by phit** 2018-09-14 01:11 UTC
Labels: version: 1.12, type: mod bug, system: entity
