### ISSUE TITLE
Performance issue from Unload/load chunks

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2129] opened 2018-05-05 02:04 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3060
- Forge version:  14.23.3.2655
- Java version: 8
- Operating System: Ubuntu 16.06

- Plugins/Mods:
 Plugins (32): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActiveTime, Aliases, Auction, AurionsVoteListener, AutoBroadcaster, Buycraft, CatClearLag, ClaimTweaks, CrazyFeetSponge, EconomyLite, ElytraTrails, GriefPrevention, GuiShop, HuskyCrates, HuskyUI, KeepInventorySponge, LuckPerms, LunarChat, LunarScramble, MMCReboot, NuVotifier, Nucleus, PacketGate, Plan, Tab Modifier, Unity, WorldEdit
MODS:
 Mods (97): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Rocketry, Advanced Rocketry Core, Applied Energistics 2, Avaritia, Avaritia Tweaks, B.A.S.E, BD Lib, Better Builder's Wands, Bookshelf, Brandon's Core, CC: Tweaked, CXLibrary, Chisel, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, Draconic Evolution, ET Lunar, Ender IO, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Powertools, EnderCore, EnderStorage, Energy Converters, Environmental Tech, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Forge Microblocks, Forge Multipart CBE, Hammer Core, Immersive Engineering, Industrial Foregoing, Industrial Meat, Iron Backpacks, Iron Chest, Just Enough Items, MTLib, Mantle, McJtyLib, MineTweakerRecipeMaker, Minecraft Multipart Plugin, Moar Tinkers, Mod Support, More Furnaces, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, PeripheralsPlusOne, Plethora, Plethora Core, RandomPatches, Reborn Core, Redstone Arsenal, Redstone Flux, Shadowfacts' Forgelin, Simply Jetpacks 2, Solar Flux Reborn, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, The Framework, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, Translocator, Universal Modifiers, Valkyrie Lib, Vein Miner, Vulpes library, Wireless Crafting Terminal 2, Woot, XNet, Zero CORE, p455w0rd's Library

**Issue Description**
So i really have no idea on how to reduce this but it seem my server was under a lot of lag 
i investigated this issue and made a lot of post here
https://github.com/MightyPirates/OpenComputers/issues/2826
once i have took out spongeforge the problem went away and the tps went up straight backup. It's possible this issue might be related to this 
https://github.com/SpongePowered/SpongeCommon/issues/1896 or this https://github.com/SpongePowered/SpongeForge/issues/2124
I'm not sure if they are related but i am assuming i made sure that it's not an hardware issue because i had test it on my computer on the opencomputer issue i had listed my computer spec's, it seem some how SpongeForge keep unload and loading Chunks causing OpenComputer to consistently save and causing lag. Here is even more information I will list my Sponge config folder as well as the WarmRoast that i posted in OpenComputers in hopes 
Sponge Config:
[sponge.zip](https://github.com/SpongePowered/SpongeForge/files/1976239/sponge.zip)
WarmRoast:
[WarmRoastReport (1).zip](https://github.com/SpongePowered/SpongeForge/files/1976241/WarmRoastReport.1.zip)

**Comment by Lemmmy** [comment] 2018-05-05 18:14
Try downgrading to SpongeForge 3059 and see if it persists - this solved the performance issues on my server (see https://github.com/SpongePowered/SpongeCommon/issues/1896)

**Comment by JoeSGT** [comment] 2018-05-05 18:40
I just tried  SpongeForge 3059 and it does not fix the issue but thanks you

**Comment by bloodmc** [comment] 2018-05-28 05:55
@JoeSGT Retest with latest SF build and provide new logs.

**Comment by JoeSGT** [comment] 2018-05-28 08:05
Sorry i had deleted the source of the lag in the world but i had went back into one of my backup worlds that had this issue i had ran 2 timings report to quickly help see if OpenComputer is still causing the issue
Here is the timings report of my current server without the OpenComputer issue https://timings.aikar.co/?id=e5cdbd7bb11e4b769e8d9b88ceff0160 i know applied Energistics 2 has issues but i have no idea how to fix that so just forcus on the openComputer, if you filter it and apply opencomputer and you'll see the results now i had went to my backup world that had this issue and ran timings report https://timings.aikar.co/?id=4fb3b88ee0a54b4a90f963b9c047e87d has you see `OpenComputers::SaveHandler_onChunkSave` has some performance issue as you can compare the different in the timings and will be provide the logs of the issue here
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2044204/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2044205/latest.log)

**Comment by DeadlyGamer1** [comment] 2018-05-30 17:03
Having the same issue

**Comment by JoeSGT** [comment] 2018-05-31 13:47
@bloodmc  i had enabled unload/load chunks log and i saw this 
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2058441/latest.log)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2058442/debug.log)
That a lot of unload/loading then i went to the world dim. and to the cords most of them were nothing there just a void for Advanced Rocketry space, it seem Sponge is unloading/loading chunks for no reason

EDIT: i had even wipe the global.conf and just enabled unload/load chunk logging and still there

**Comment by JoeSGT** [comment] 2018-06-01 15:13
I look into a bit more in detail and it seem it's AE2 mod that causing chunks to unload/load here is what i had found https://pastebin.com/raw/JFjHinLg i had made an issue on there https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3524 if anyone else had this issue so going to close this issue

**Comment by JoeSGT** [comment] 2018-06-01 15:51
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3524 i will reopen this issue because the Developer said ` there is something seriously broken in sponge when they tick unloaded chunks.`

**Comment by CyberSpongie** [comment] 2018-06-01 16:05
I am also having this issue here is what i had found i hope this helps  i also did sampler https://pastebin.com/raw/TrdPxnyR and use Sponge Logging https://pastebin.com/raw/zwAG665C

My server TPS is at 1-10 when i take out Spongeforge i get 18-20 TPS

**Comment by JoeSGT** [comment] 2018-06-01 16:50
I had also removed spongeforge for a test and installed Sampler once SpongeForge was out then i did do `/sampler loads show` to show me any loaded chunks that was shown in the error log and it didn't gave me any errors show im pretty sure this is a sponge issue

**Comment by bloodmc** [comment] 2018-06-01 17:18
I'm assuming the issue is related to our chunk gc feature. The odd thing is why the TE is ticking if the chunk was unloaded. Please disable Sponge's chunk gc and retest.

**Comment by JoeSGT** [comment] 2018-06-01 18:47
Okay here is the results of my testing, i set `max-chunk-unloads-per-tick=0`  instead of the default 100 and it did not unload/load chunks then i set it back to 100 then i tried ` chunk-gc-tick-interval=0` instead of default 600 and then restarted the server it started unloading/loading chunks, it seem that `max-chunk-unloads-per-tick` this setting is the cause of the problem but your right it's really is the sponge chunk gc feature causing performance issues with AE2 mod and other mods causing it to unload/load chunks all the time.

**Comment by bloodmc** [comment] 2018-06-02 01:41
Unloading chunks is normal vanilla behavior. Sponge just uses chunk gc to unload chunks that are "leaked" by worldgen and mods. Setting `chunk-gc-tick-interval` to 0 will restore vanilla behavior. Setting `max-chunk-unloads-per-tick` to 0 will never unload chunks and will cause major performance issues as more and more chunks continue to load.

**Comment by JoeSGT** [comment] 2018-06-02 02:52
im not sure how to fix this issue without touching those settings

**Comment by bloodmc** [comment] 2018-06-05 13:22
@JoeSGT test latest SF to see if it solved the issue.

**Comment by JoeSGT** [comment] 2018-06-05 17:30
Just tested with spongeforge version spongeforge-1.12.2-2705-7.1.0-BETA-3144 it is the latest at this current moment and i can confirm that it does not fix the issue

**Comment by bloodmc** [comment] 2018-06-14 22:26
Unable to reproduce this on a clean server.

**Comment by bloodmc** [comment] 2018-06-14 22:29
I'll keep this open a few more days if you find out how to reproduce.

**Comment by JoeSGT** [comment] 2018-06-14 22:33
it's fine to close it to be honest with you i have no idea how to reproduce it, it's been on going issue now i had recently enable chunk loaders and allow the player to use them. If this issue does get close and later on i manage to find a way to reproduce this i will provide as much information and a way to reproduce it then make an another ticket regarding of this again. Sorry about this but thanks you for your time

**Comment by XakepSDK** [comment] 2018-06-15 03:03
Can you make memory dumps and profiling snapshots with YourKit while server errors?
p.s. don't forget to disable watchdog before doing this, enable snapshot compression(checkbox in confirm. window), because it may be really big with that much mod count(>8GiB)
Warning: memory snapshot may contain sensitive data.

**Comment by JoeSGT** [comment] 2018-06-16 16:56
I would but i have no idea how to mess with YourKit

**Comment by bloodmc** [comment] 2018-07-19 02:04
@JoeSGT do you have a world you can provide that can easily reproduce this issue?

**Comment by JoeSGT** [comment] 2018-07-19 06:46
it's an large world about over 20gb

**Comment by bloodmc** [comment] 2018-07-20 20:53
@JoeSGT Please test latest SF build. Make sure `chunk-gc-tick-interval` is set to 600.

**Comment by JoeSGT** [comment] 2018-07-21 02:16
It's fixed in the latest
EDIT: tested with SF: spongeforge-1.12.2-2705-7.1.0-BETA-3328

**Comment by bloodmc** [comment] 2018-07-21 02:24
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/0954d501d990f455af05ca2d17d4ec2ac6a123d7

**Closed as completed by bloodmc** 2018-07-21 02:24 UTC
Labels: status: needs testing, type: performance, version: 1.12
