### ISSUE TITLE
Hatchery - Not dropping iron ingots with SpongeForge

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#1259] opened 2017-02-10 15:46 UTC
A Nesting Pen with a Iron Chicken should drop a Iron Ingot after a while which it does if SpongeForge is not installed.
![](http://i.imgur.com/CKupttx.jpg)

When SpongeForge (1.10.2-2221-5.1.0-BETA-2136) is installed it drops everything which is on the screenshot but no iron ingot.

Probably same issue with the other chickens.

**Comment by chaosblad3** [comment] 2017-02-10 18:28
Can confirm with other chickens too, no logs from log chickens, no flint from flint chickens etc.

**Comment by Kaptinobvius** [comment] 2017-02-12 07:54
The issue isn't that they are not dropping.  The issue is that actual item drops are throw out of the nesting pen and not dropped like the rest of the items.

If you enclose the space you have your nesting pens in, you'll find the random drops all over the room.

**Comment by chaosblad3** [comment] 2017-02-12 15:47
No, my nesting pens are already fully enclosed, and I have adv item collectors (random things) in the area anyway so if any items were thrown out into the world then they would be picked up by that, I have literally stood in front of my iron chicken pens for 45 mins while watching a show on my second monitor and after multiple cycles not one iron ingot had generated from my 8x 10/10/10 iron chickens, either in the nesting pens or dropped in world.

**Comment by phit** [comment] 2017-02-12 16:09
well that is also an issue then, regardless the items flying all over the place isn't happening without sponge either

**Comment by Aaron1011** [comment] 2017-02-18 00:24
I've reproduced this bug, and I'm working on a fix.

**Comment by chaosblad3** [comment] 2017-03-15 11:08
Any update on this?

**Comment by Yorkforce** [comment] 2017-03-22 22:47
Not sure if it's related but as well as the chickens not dropping items, lootbags are also not dropping with SpongeForge (2236).

**Comment by tyler489** [comment] 2017-05-01 20:06
Just like to point out that you also cant Breed the modded chickens from the chickens mod
with seeds you have to use the nesting pins on a sponge forge server in sp either works

**Comment by GenDeathrow** [comment] 2017-05-01 20:40
There is an array in the Entity.class that allows entities to store items instead of dropping the items. All nesting pens do is set it to true, and if the array has drops.. I handle the drops. 

![image](https://cloud.githubusercontent.com/assets/3720710/25593974/847f830a-2e84-11e7-9aa0-450b1e05d1d6.png)


![image](https://cloud.githubusercontent.com/assets/3720710/25593960/7545c17e-2e84-11e7-8c8b-376fc7eab7c7.png)

My guess is the captured drops aren't being handled in Sponge

Edit: I do this so that I can properly capture drops from modded entities in my nesting pens.

**Comment by Aaron1011** [comment] 2017-05-01 21:46
Sorry - I meant to link this issue here: https://github.com/SpongePowered/SpongeForge/issues/1398

**Comment by DemonHiatus** [comment] 2017-05-29 07:56
Any news from this?

**Comment by Sir-Will** [comment] 2017-08-02 05:13
Just found out that the missing items getting dropped at x: 0 y: 0 z: 0. You can also hear the chicken sounds at that location.

**Comment by GenDeathrow** [comment] 2017-08-02 05:33
@Sir-Will what version are you on of hatchery now? That issue with the chickens sounds should have been fixed with latest versions. But as far as I know this issue with the drops has not been fixed on sponges side yet

**Comment by Sir-Will** [comment] 2017-08-02 05:34
hatchery-1.10.2-0.3.17

**Comment by ryantheleach** [comment] 2017-08-02 05:51
If I were a player on your server I would have been tempted to setup hoppers there :P

**Comment by gabizou** [comment] 2018-01-01 09:13
Fairly sure this is still going to be affected in 1.12, the sooner we can try to reproduce the issue on 1.12 the better, I've kept kicking the can down the road at the monstrosity that exists for translating sponge events to forge events, sometimes it's not very clear.

**Comment by gabizou** [comment] 2018-01-12 06:44
To give an update for this issue, I went and submitted a [1.13 PR for Forge to better improve the handling of drop captures](https://github.com/MinecraftForge/MinecraftForge/pull/4673), meanwhile, in 1.12 I'll work on doing some ~hacky~ ~*insane*~ interesting workaround.

**Comment by GenDeathrow** [comment] 2018-01-12 07:42
well thanks for the update. I appreciate it. Id like for this to all work with out issue.

**Comment by gabizou** [comment] 2018-05-08 23:36
So, I've figured out the reason *precisely* why this is happening. I'm fixing it now in #2110 that is mostly paired with logic from SpongePowered/SpongeCommon#1882. @GenDeathrow I hadn't realized that the hatchery tile entity was just telling the chicken entity to create items (which is why sponge was not triggering the captures). This will be relatively easy to resolve now on sponge's end.

**Comment by gabizou** [comment] 2018-05-09 01:37
@phit I've tested locally that Hatchery is successfully capturing the resource drops from the chickens, I'm not 100% sure that it works absolutely because I had to modify some variables in local testing to make testing a little faster than waiting several minutes at a time to get some custom resource drops.

This should be closed once #2110 is merged.

**Closed as completed** 2018-05-14 19:16 UTC
Labels: type: bug, type: mod incompatibility, version: 1.10 (u)
