### ISSUE TITLE
ExceptionInInitializerError Crash

### ISSUE THREAD

**Issue by xxlio109** [SpongePowered/SpongeForge#2286] opened 2018-07-09 06:19 UTC
The server crashes while loading
SpongeForge version: 1.12.2-2705-7.1.0-BETA-3272
Forge version: 2705

Plugins/Mods: 
https://gist.github.com/xxlio109/c385e6b8c00ae4feb607ba777cb56ded

Issue Description
https://gist.github.com/xxlio109/e7c0781cd5b490fc4ecbec76a109a26f

**Comment by kashike** [comment] 2018-07-09 06:23
duplicate of #2280

**Closed as completed by kashike** 2018-07-09 06:23 UTC
Labels: type: bug, resolution: duplicate, version: 1.12, system: advancement
