### ISSUE TITLE
BlockStateContainer - start up crash - LostCities

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2774] opened 2019-05-25 20:14 UTC
**I am currently running**

- SpongeForge version: 3716
- Forge version: 2838
- Java version: 8 
- Operating System: Debian 9

- Plugins/Mods:

**Issue Description**

Trying to start up a OmniFactory server but keep hitting this BlockStateContainer crash with Lost Cities:

https://pastebin.com/W2Rh57WX

[latest.log](https://github.com/SpongePowered/SpongeForge/files/3219708/latest.log)

**Comment by ImMorpheus** [comment] 2019-05-25 20:16
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2773

**Comment by ImMorpheus** [comment] 2019-05-25 20:16
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in the `config/foamfix.cfg`
`B:optimizedBlockPos=false` (Sponge adds a similar performance patch)
`B:patchChunkSerialization=false` <https://github.com/asiekierka/FoamFix/issues/166>

**Closed as completed by ImMorpheus** 2019-05-25 20:16 UTC
Labels: resolution: duplicate

**Comment by Yorkforce** [comment] 2019-05-25 20:21
Dammit, forgot to do that, sorry and thanks ImMorpheus!
