### ISSUE TITLE
Machine recharge issue

### ISSUE THREAD

**Issue by mrdeadlocked** [SpongePowered/SpongeForge#2758] opened 2019-05-16 13:47 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2825-7.1.6-RC3711.jar
- Forge version: forge-1.12.2-14.23.5.2836-universal.jar
- Java version: java version "1.8.0_211"
- Operating System: Debian

- Plugins/Mods:

Plugins (20): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, Dynmap, ESPayMoney, EconomyLite, GriefPrevention, LuckPerms, MagiBridge, Nucleus, PlaceholderAPI, PlayerShopsRPG, Sledgehammer, SlotMachines, SpongePrometheusExporter, Spotlin, TabManager, spark

Mods (259): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, A Lib, Actually Additions, Actually Baubles, Akashic Tome, Alchemistry, Animania, AppleCore, AppleSkin, ArchitectureCraft, Aroma1997Core, Artisan Worktables, Astral Sorcery, Athenaeum, AutoPickup, AutoRegLib, Avaritia, B.A.S.E, BD Lib, Bad Mobs, Baubles, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bonsai Trees, Bookshelf, Botania, Botanic Additions, Brandon's Core, Can I Join Now?, Ceramics, Chameleon, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Drawers, ContentTweaker, CookieCore, Corail Tombstone, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cucumber Library, Custom Starting Gear, Cyclic, Cyclops Core, DDSS Utils, Dark Utilities, Doomlike Dungeons, Draconic Evolution, DungeonTactics, Dynmap, DynmapBlockScan, EnderStorage, Environmental Tech, EvilCraft, EvilCraft-Compat, Exchangers, Extended Crafting, Extra Alchemy, Extra Planets, Extra Utilities 2, Extreme Reactors, Farseek, Fast Leaf Decay, FastWorkbench, Fishing Net Mod, FluidTank, FluidTank_AE2, FluidTank_TheOneProbe, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, GenDustry, Gendustry JEI Addon, Guide-API, Guidebook, Hammer Core, HelpFixer, Hooked, Hunger Overhaul, Hunting Dimension, Ice and Fire, Immersive Engineering, Industrial Foregoing, Infernal Mobs, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Chest, IvToolkit, Just Another Rotten Flesh to Leather Mod, Just Enough Items, LLibrary, LagGoggles, Lapis Stays in the Enchanting Table, LibEx, LibrarianLib, LibrarianLib Stage 2, LittleTiles, LittleTilesCore, LogFilters, Longer Days, Loot Bags, LootTweaker, MJRLegendsLib, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanica, Mekanica: Generators, Mekanica: Tools, MekanismOres, Micdoodle8 Core, Minecraft Multipart Plugin, Mob Properties Randomness, Mod Tweaker, More Libs, More Plates, Morpheus, Mowzie's Mobs, MrCrayfish's Furniture Mod, MrTJPCore, Multi Mob Core, Mystical Agradditions, Mystical Agriculture, Mystical Lib, Natura, NetherEx, NotEnoughIDs, NuclearCraft, OMLib, OnlinePictureFrame, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Overloaded, Pam's Cookables, Pam's HarvestCraft, Pickle Tweaks, Placebo, PlusTiC, PneumaticCraft: Repressurized, Primitive Mobs, Progressive Bosses, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Quark, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RailsPlus, RandomPatches, Reborn Core, RebornStorage, Redstone Flux, Refined Avaritia, Refined Storage, Refined Storage Addons, Rex's Additional Structures, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roguelike Dungeons, Rough Mobs 2, Ruins Mod, Rustic, Shadowfacts' Forgelin, Simply Jetpacks 2, Solar Flux Reborn, Special AI, Spice of Life: Carrot Edition, SpongeForge, Standard Expansion, Steve's Carts 2, Storage Cabinet, Storage Drawers, Storage Drawers Extras, Storage Tech, Streams, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers Alloying Addon, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, Tweakers Construct, Underground Biomes, UniDict, Universal Modifiers, V0id's Smart Backpacks, Valkyrie Lib, VanillaFix, ViesCraft, Vulcanite, WanionLib, Worley's Caves, XNet, Zero CORE, Zoesteria Biomes, galacticrafttweaker, p455w0rd's Library, projectred-compat

**Issue Description**
Manufactory (and possibly other) nuclearcraft machines now work (before the new version you couldn't open them after inserting items) but they do not recharge RF until after you remove smelted item.
![KFPqeqGXlB](https://user-images.githubusercontent.com/461352/57858677-79f3f200-77bf-11e9-9c84-5d1ec3f2ca11.gif)

**Comment by Yorkforce** [comment] 2019-05-29 04:11
Can confirm, seems to happen on most nuclearcraft machines that require power.

Just to add if you toggle the redstone signal button next to the power bar while its processing something, it will start filling up the energy bar again, but you have to do every time you process something. just a simple toggle once does it, regardless of the redstone setting.

**Comment by phit** [comment] 2019-05-30 18:43
can't reproduce with RC3732 and NuclearCraft-2.17a-1.12.2

please retest!

**Comment by mrdeadlocked** [comment] 2019-06-01 14:43
I still have the issue on aaaaa-spongeforge-1.12.2-2825-7.1.6-RC3744.jar using NuclearCraft-2.17a-1.12.2.ja. Manufactory drains power and doesn't fill. Redstone toggle button still works as a workaround.

**Comment by phit** [comment] 2019-06-01 14:44
did you remove all other mods? there's probably more needed for this than just these two, figure out what mod breaks it as it works fine with just NuclearCraft and Sponge

**Comment by phit** [comment] 2019-06-26 18:18
Gonna close this as no one else has come forward with having this issue and I was completely unable to reproduce this. When you find a way to reproduce this, add it to this issue and I'll reopen!

**Closed as completed by phit** 2019-06-26 18:18 UTC
Labels: status: more information needed, version: 1.12, status: waiting for reply
