### ISSUE TITLE
Server Crash Sponge Timings

### ISSUE THREAD

**Issue by tyler489** [SpongePowered/SpongeForge#1675] opened 2017-07-25 02:36 UTC
**I am currently running...**

- SpongeForge version: (spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar)
- Forge version: {12.18.3.2422}
- Java version: 8?
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Plugins (154): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Building Bricks Hooks, CreativeCoreDummy, IvToolkit, SpongeAPI, SpongeForge, Fence Overhaul, Actually Additions, Baubles, Botania, Akashic Tome, Animania, Aquaculture, Ars Magica 2, AnimationAPI, Astral Sorcery, Alternate Terrain Generation, Quark, AutoRegLib, Bed Bugs, Better Builder's Wands, BiblioCraft, MalisisCore, MalisisDoors, Big Doors, BiomeTweaker, Bird's Nests, Guide-API, Just Enough Items, Blood Magic: Alchemical Wizardry, InfinityLib, Boatifull, Building Bricks, Chameleon, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, Copy Paste, CosmeticArmorReworked, CraftingCraft, Crafting Tweaks, CraftTweaker JEI Support, MineTweaker 3, CreativeCore, CustomNPCs, Cyberware, Cyclops Core, D³Core, Storage Drawers, Drawers & Bits, DungeonTactics, Dynamic Surroundings, Earthworks, EnderCore, Waila, Ender IO, EverlastingAbilities, Extra Bit Manipulation, Extra Utilities 2, Fast Leaf Decay, Flat Colored Blocks, Flint Instead of Wood, Shadowfacts' Forgelin, FTBLib, FTB Tweaks, Little Insignificant Things, Silent Lib, Silent's Gems, Gemulation, Grappling hook mod, Grimoire of Gaia 3, HolographicVictoryMonument, LLibrary, Ice and Fire, Immersive Engineering, Improving Minecraft, InControl, Simple Inventory sorting, Iron Backpacks, Iron Chest, JourneyMap, JsonLootBags, Just What I Needed, Levels, Level Up!, LibrarianLib, Literal Ascension, Login Shield, LootTweaker, Malisis Blocks, RadixCore, Minecraft Comes Alive, MineColonies, MmmMmmMmmMmm, Mob Properties, MTLib, Mod Tweaker, More Materials, Morpheus, Mowzie's Mobs, ModPack Utilities, ModPack Basic Tools, Natural Pledge, NoMoreRecipeConflict, Plants, ShetiPhian-Core, Platforms, Quadrum, Railcraft, Railcraft Cosmetic Additions, Rando Restockable Crates, Recurrent Complex, Reliquary, RFTools, RFTools Control, RFTools Dimensions, RikMuld's Core, Roguelike Dungeons, Roots, Runes of Wizardry, Runes of Wizardry - Classic Dusts Pack, Rustic, Scaling Health, Silent's Gems: Extra Parts, ShadowMC, Signals, Similsax Transtructors, Sleeping Bag, stacksonstacks, Super Circuit Maker, Super Multi-Drills, Terraqueous, The Camping Mod 2, Tomb Many Graves, TrashSlot, Valkyrie Lib, Village Names, Water Strainer, Waystones, WIRED: More Augs, BetterChunkLoader Forge Lib, BetterChunkLoader, Buycraft, Discord Bridge, EconomyLite, GriefPrevention, LuckPerms, Mtloader, Nucleus, LibrarianLib Stage 2
**What is the expected result?**
hmmm What do you think?
**What is the current result?**
server crashes Playing 0.9.3 in the Sprout modpack https://pastebin.com/BuN0dfim

**Comment by phit** [comment] 2017-07-25 02:42
dupe of #1402

**Comment by tyler489** [comment] 2017-07-25 03:34
Seems to be something from the ICE AND FIRE dragons mod.

**Closed as completed** 2017-07-25 03:47 UTC
Labels: resolution: duplicate

**Comment by kashike** [comment] 2017-07-25 09:56
Duplicate of #1402.
