### ISSUE TITLE
SpongeForge Decaying Leaves and Overloaded

### ISSUE THREAD

**Issue by Mysterizon** [SpongePowered/SpongeForge#760] opened 2016-07-17 17:23 UTC
spongeforge-1.10.2-2011-5.0.0-BETA-1560

**ISSUE 1**: When the trees are chopped down.. the leaves is not decaying or despawning after a long time of period. 

Proof: 
I added "FastLeafDecay" mod to the forge and it dont work, so i removed the SpongeForge mod.. it works perfectly so SpongeForge is the cause of why the leaves won't despawn or decay. 

**ISSUE 2**: While the Forge server is running with SpongeForge mod, it show a message something like "did the time system changed or is the server overloaded, skipping 80 ticks"
i think the leaf decaying may have to do with it..  no telling. so please look in it. 

**Additional Information** (you can read this or not): 

since i chopped down a lot of trees, and none of them, the leaves are decaying or despawning. It cause my world to have a map corrupted because of Issue 2, it was overloaded.. the reason is there are too many items on the ground and it takes time for them to despawn. 

when leaves are not decaying, it drop three things: apples, Sticks, and sapling. I used mods following: 
-AutoSapling
-Immersive Craft
-FastLeafDecay

**Comment by Aaron1011** [comment] 2016-07-17 21:27
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/837.

@Mysterizon: Can you please open a separate issue for 'ISSUE 2'?

**Closed by Aaron1011** 2016-07-17 21:27 UTC
