### ISSUE TITLE
HarvestEntityEvent.TargetPlayer is NOT being called

### ISSUE THREAD

**Issue by DoomedScar** [SpongePowered/SpongeForge#608] opened 2016-04-11 16:49 UTC
The "**PlayerEvents**" class is registered as a _Listener_ and does fire other events such as "**DropItemEvent.Destruct**", but for some odd reason "**HarvestEntityEvent.TargetPlayer**" doesn't fire after a player drops their items on death, therefore I can not use "**setKeepsInventory**" on them.

In the docs it says that the event should be "_Called when an Entity has been killed and is being "harvested" (drops/etc)_" 

**Link**: https://jd.spongepowered.org/4.0.3/org/spongepowered/api/event/entity/HarvestEntityEvent.html

I'm using **forge-1.8.9-11.15.1.1808**.
Here's my code:
```
public class PlayerEvents
{
    @Listener
    public void onHarvestEntityEvent(HarvestEntityEvent.TargetPlayer event)
	{
		Player player = event.getTargetEntity();
		player.sendMessage(Text.of("HarvestEntityEvent"));
		
		if(player.hasPermission("com.pokemc.deathcontrol"))
			event.setKeepsInventory(true);
    }

	@Listener
	public void onDropItemEvent(DropItemEvent.Destruct event)
	{
		boolean isPlayer = event.getCause().first(Player.class).isPresent();
		boolean isDamageSource = event.getCause().first(DamageSource.class).isPresent();
		if(isPlayer && isDamageSource)
		{
			Player player = event.getCause().first(Player.class).get();
			player.sendMessage(Text.of("DropItemEvent"));
		}
	}
}
```

**Comment by kinggoesgaming** [comment] 2016-04-11 18:41
Have you tested on spongevanilla to make sure it's a sponge forge issue or sponge common issue?

**Comment by gabizou** [comment] 2016-04-11 19:32
Closing as it's a duplicate of the existing https://github.com/SpongePowered/SpongeCommon/issues/41 event tracking issue.

**Closed by gabizou** 2016-04-11 19:32 UTC
