### ISSUE TITLE
Some mobs crashing the server

### ISSUE THREAD

**Issue by kaal-1** [SpongePowered/SpongeForge#1664] opened 2017-07-21 20:57 UTC
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464
- Forge version: 2281
- Java version: 8

- Operating System:
 - [x] Linux (Debian 8)

- Crash:
https://hastebin.com/ohugajopun.http

**Comment by Zidane** [comment] 2017-07-21 21:19
@gabizou , fix this please.

**Comment by phit** [comment] 2017-07-21 21:27
hey, its this crash again, see https://github.com/SpongePowered/SpongeForge/issues/1467 
this time a zombie is damaging the villager, I'm mainly confused because I couldn't reproduce this myself just a few days ago on the same Sponge version

**Comment by gabizou** [comment] 2017-07-21 23:47
Duplicate of #1467

**Closed as completed by gabizou** 2017-07-21 23:47 UTC
