### ISSUE TITLE
Sponge Config reverts to default 

### ISSUE THREAD

**Issue by SeaDonkey81** [SpongePowered/SpongeForge#2867] opened 2019-07-06 16:01 UTC
SpongeForge version: spongeforge-1.12.2-2825-7.1.6

Forge version: forge-1.12.2-14.23.5.2825-universal

Java version: 8

Operating System: windows 8

Plugins/Mods:
https://gist.github.com/SeaDonkey81/4367845714ccd278004f8c5b19802b86

Issue Description:
Edited Config:  https://gist.github.com/SeaDonkey81/71ac0bb5702053ee53b94f0065168141

Before you just dismiss my issue, again.  It's not just the formating. The Config file reverts everything to default even if i just change one item anywhere in the config file without the additional info in [entity - activation - range]

Sponge Config reverts to default every time the server is restarted. This started happening a few days ago.

-Please provide a full server log (and crash-report if applicable).
https://gist.github.com/SeaDonkey81/88560c8f2fe2278f6bde4f817b3a9438

**Comment by dualspiral** [comment] 2019-07-06 16:03
This was already answered (though you did request additional clarification) in https://github.com/SpongePowered/SpongeForge/issues/2866. There is _no_ need to repost the same issue.

**Comment by ImMorpheus** [comment] 2019-07-06 16:04
Please, don't duplicate issue. 
If you have more information, keep everything on the same issue.

Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2866

EDIT: dual was faster

**Closed as completed by dualspiral** 2019-07-06 16:03 UTC
