### ISSUE TITLE
Failed to process all Phase Context captured

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2794] opened 2019-06-02 23:28 UTC
**I am currently running**

- SpongeForge version: 3748
- Forge version: 2836
- Java version: 201
- Operating System: Win Server 2016 

**Issue Description**

Log: https://pastebin.com/raw/5NbzBQ03

Mods/Plugins: https://pastebin.com/raw/QVBKZm3A

Occurs when player is fighting ender dragon.

**Comment by phit** [comment] 2019-06-03 02:35
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2282

**Closed as completed by phit** 2019-06-03 02:35 UTC
Labels: resolution: duplicate
