### ISSUE TITLE
Server does not start with Sponge

### ISSUE THREAD

**Issue by Prasodym** [SpongePowered/SpongeForge#2986] opened 2019-09-28 07:20 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3891.jar
- Forge version: spongeforge-1.12.2-2838-7.1.7-RC3891.jar
- Java version: spongeforge-1.12.2-2838-7.1.7-RC3891.jar
- Operating System: Linux (amd64) version 4.15.0-29-generic

- Plugins/Mods:
Show Pastebin

**Issue Description**

This is a Modpack Project Ozone 3 3.0.41 
I tried several Sponge versions without success.
In the mod formfix I already set the 2 parametar to false.

**Pastebin Link**

[https://pastebin.com/33YEcF34](url)

**Comment by ImMorpheus** [comment] 2019-09-28 15:15
You didn't post your mod/plugin list.

However from your crash log it looks like you're running `phosphor-1.12.2-0.2.4+build46-universal.jar`

See https://github.com/jellysquid3/Phosphor/issues/34

Also duplicate of https://github.com/SpongePowered/SpongeForge/issues/2871

This is not an issue with sponge.

**Closed as completed by ImMorpheus** 2019-09-28 15:15 UTC
Labels: resolution: duplicate, type: mod bug
