### ISSUE TITLE
Server Crashes When Booting up

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1504] opened 2017-05-13 16:36 UTC
Hello. I am running a sever on windows 10. I am using Sponge with FTB Beyond and I keep getting this error. I do have plugins installed
https://gist.github.com/Solarmender/b4327561876acbc6b11a7e788756695f

Any Help is appreciated! thanks!

**Comment by phit** [comment] 2017-05-13 17:05
update sponge to latest
https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2

**Comment by phit** [comment] 2017-07-18 20:47
please close this, this crash was caused by using an outdated sponge version

**Closed as completed** 2017-07-18 20:47 UTC
