### ISSUE TITLE
No WitherSkeleton Spawn in Nether

### ISSUE THREAD

**Issue by Mallalei** [SpongePowered/SpongeForge#1904] opened 2017-12-21 08:51 UTC
I have install on a FTB-SkyFactory3 Server spongeforge-1.10.2-2477-5.2.0-BETA-2777 and try it with 1.10.2-2477-5.2.0-BETA-2782 and now do not spawn witherSkeletons and blazes, blazes spawn arround his spawner but thats all… Skeletons and WitherSkeletons dont spawn!

SpongeForge is the only one Plugin that i have installed after the ModPack by FTB.

If i delete sponge it works with the spawn of this Mobs.
sorry for my bad english! I hope any can understand and help me fast.

**Comment by phit** [comment] 2017-12-21 12:11
gotta see if backporting https://github.com/SpongePowered/SpongeCommon/pull/1604 is needed

**Comment by JBYoshi** [comment] 2017-12-22 16:13
I can't reproduce this without mods. I went to some newly generated nether fortresses (SpongeForge 1.10.2-2477-5.2.0-BETA-2782) and found multiple skeletons and wither skeletons around them, in addition to several blazes that were not near spawners.

**Comment by phit** [comment] 2017-12-22 16:15
yeah skyfactory uses custom worldgen (all void) provided by a mod, hence the PR linked above probably needs to be backported

**Comment by JBYoshi** [comment] 2017-12-22 17:43
Never mind then. Can reproduce with just [YUNoMakeGoodMap](https://minecraft.curseforge.com/projects/yunomakegoodmap) ([source](https://github.com/LexManos/YUNoMakeGoodMap))- make sure to flip on nether fortress generation in the configuration file.

**Comment by JBYoshi** [comment] 2017-12-22 17:50
That fixes it.

**Comment by JBYoshi** [comment] 2017-12-22 17:52
Fixed in SpongePowered/SpongeCommon@dfc7cb62c2d9633d25640610241cfa44e9d58024.

**Closed as completed by JBYoshi** 2017-12-22 17:52 UTC
Labels: type: bug, status: accepted, version: 1.10 (u), system: world

**Comment by JBYoshi** [comment] 2017-12-22 18:43
Also backported to 1.11. https://github.com/SpongePowered/SpongeCommon/commit/ac6fab7818388e749221a38be6063d17846c8d67
