### ISSUE TITLE
Crash With BuildCraft (need help)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1527] opened 2017-05-20 16:54 UTC
https://github.com/BuildCraft/BuildCraft/issues/3594#issuecomment-302884439
thanks...

**Comment by AlexIIL** [comment] 2017-05-20 17:45
BuildCraft dev here - This seems to be an issue with how BuildCraft's FakeWorld works - as far as I can tell there is no way (through vanilla) to set the UUID of a world.

**Comment by gabizou** [comment] 2017-05-20 21:12
@AlexIIL I have a good idea on how to fix this, would you imagine this would be reproducible on 1.10.2 as well (seeing as the few bits of code have persisted between 1.10.2 and 1.11 versions)?

**Comment by AlexIIL** [comment] 2017-05-20 21:25
Possibly. I would need to backport the relevant code to 1.10.2 though. (As none of BC is on 1.10.2 right now)

**Comment by gabizou** [comment] 2017-05-23 05:23
> Possibly. I would need to backport the relevant code to 1.10.2 though. (As none of BC is on 1.10.2 right now)

Seeing as this only cropped up on 1.11.2, I'm expecting the issue not to have cropped up in 1.10.2 since now, but SpongeForge will be back ported for the fix (workaround). Nothing really needs to be done on your end 👍.

**Comment by ghost** [comment] 2017-05-23 06:53
This has been fixed on Sponge's side? Or i misunderstood
edit: OH, i'm so sorry; it's fixed on 2348. couldn't see it. but it's still crashing with buildcraft. here is the crash report. it's so sad :/ dunno why it crashes 
[crash-2017-05-23_11.59.22-server.txt](https://github.com/SpongePowered/SpongeForge/files/1021566/crash-2017-05-23_11.59.22-server.txt)

**Comment by ghost** [comment] 2017-05-23 09:20
bump.(for crash report if didn't noticed)

**Comment by gabizou** [comment] 2017-05-23 16:19
@AlexIIL Is FakeWorld supposed to be considered the equivalent to a server world? Or is it supposed to be considered a remote (disconnected world)? Currently, you pass in `false` for the `World` constructor, which is causing Sponge to think that it's a server (non-remote) world, and performing it's tracking logic accordingly.

**Comment by AlexIIL** [comment] 2017-05-23 17:23
@gabizou Its meant to a world for testing the behaviour and properties of blocks, which might work differently in a client world to a server world. However we don't extend WorldServer because that requires an instance of MinecraftServer (which is not something we necessarily have access to).

I want to say that this is an issue with sponge, but I think that some other parts of BuildCraft's code assumes that "world.isRemote" implies extending WorldServer :/

**Comment by ghost** [comment] 2017-05-23 19:22
hey ah, i just saw the newest sponge version (2352) that has changelog about fixes 1527. Then i tried installing it again, but crashed again :((
[crash-2017-05-23_22.18.54-server.txt](https://github.com/SpongePowered/SpongeForge/files/1023492/crash-2017-05-23_22.18.54-server.txt)
i'm sorry if i'm spamming again, just thought this issue should be fixed in 2352

**Comment by AEnterprise** [comment] 2017-05-23 19:57
i'll work on making the BC fake word extend WorldServer to fix this and other potential issues caused by the current implementation

**Comment by gabizou** [comment] 2017-05-23 22:50
> I want to say that this is an issue with sponge, but I think that some other parts of BuildCraft's code assumes that "world.isRemote" implies extending WorldServer :/

If `world.isRemote == true` then it's a remote world, not a server world. This is the logic that vanilla employs and sponge uses to differentiate between non-server worlds, as from vanilla:
```java

    public WorldServer(MinecraftServer server, ISaveHandler saveHandlerIn, WorldInfo info, int dimensionId, Profiler profilerIn)
    {
        super(saveHandlerIn, info, DimensionType.getById(dimensionId).createDimension(), profilerIn, false);
        this.mcServer = server;
        this.theEntityTracker = new EntityTracker(this);
        this.thePlayerManager = new PlayerChunkMap(this);
        this.provider.registerWorld(this);
        this.chunkProvider = this.createChunkProvider();
        this.worldTeleporter = new Teleporter(this);
        this.calculateInitialSkylight();
        this.calculateInitialWeather();
        this.getWorldBorder().setSize(server.getMaxWorldSize());
    }
```
By this logic, sponge does utilize the `isRemote` check to verify it's not a fake world and is an actual world handled by various systems, including being registered with the DimensionManager etc. Because of this though, Sponge is thinking that your fake world is indeed a server world (because you pass in `false` instead of `true`) leading it to perform server sided logic like block change tracking and whatnot.

**Comment by AlexIIL** [comment] 2017-05-23 22:53
@gabizou sorry, I meant the other way around (world.isRemote == false implies WorldServer)

Although we're going to make FakeWorld extend WorldServer rather than expecting Sponge to work around this, so the distinction won't matter.

**Comment by gabizou** [comment] 2017-05-23 22:54
> Although we're going to make FakeWorld extend WorldServer rather than expecting Sponge to work around this, so the distinction won't matter.

You shouldn't have to, just pass in `true`, would that not work with Buildcraft's systems?

**Comment by AlexIIL** [comment] 2017-05-23 23:02
I know that buildcraft uses ````world.isRemote```` in a lot of block checks to determine what logic should be run, and we want the server logic to be run rather than client logic. I'm not sure if its a problem at the moment, but if we use FakeWorld for more elaborate things (for example ticking tile entities) then it will be important that we get the results for a server.

**Comment by gabizou** [comment] 2017-05-24 04:24
If you utilize FakeWorld to tick tile entities, there might be some issues with regards to how Sponge currently handles block changes and entity spawns, while it does seem feasible to work around it, I don't think it's going to work out well without making just a plain Worldserver instance with customary handling for events and preventing teleportations etc. taking place in those worlds. That being said, I'm open to discussion maybe outside this issue on the development of such a world implementation where Sponge can still remain compatible, even with modifications to SpongeForge :).

To put it into perspective, Sponge does overwrite the following methods in WorldServer:

- [`WorldServer.updateBlocks()`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L518-L727)
- [`WorldServer.updateEntities()`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L746-L772)
- [Modifications to `WorldServer.tickUpdates()`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L779-L806)

There's quite a few more that are particularly involved in it all. Not to mention the modifications we make with `Chunk` relying on the server sidedness of the `World` as seen [here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L499-L670) The overwrites should be understandable with the code comments.

I'm all ears on further discussion about what steps we both should probably take in both projects.

That being said, I'll leave this issue open for further discussion.

**Comment by AEnterprise** [comment] 2017-05-24 06:12
for now there is no ticking going on so there should be no real issues atm yet

the current use of the fake world is to check requirements of blocks for the snapshots in what blocks are required to place them (getting pickblock) but this world is also used for displaying the content of them in your inventory

as for possible compat modifications: since 1.12 is arround the corner it might be worth adding a function to world in forge: `isRealWorld` or something like that, would default to true but mods with fake worlds that are completely not accesable by players could return false there, this would allow other mods and things like spongeforge to know this and addapt (for example any permission and logging mods/plugins could just disregard that world)

**Comment by AEnterprise** [comment] 2017-05-26 20:24
i have adapted the BC fakeworld implementation so it now extends worldserver, this works fine until you add sponge to the mix, then it all crashes during startup. The final crash forge reports in the crashlog is a nullpointer cased by the fake world constructor crashing so the instance is null

these are the console output, latest.log and fml-server-latest.log: https://gist.github.com/AEnterprise/482b6f23c2fec9472341dfae24e0e590

there is a short mentioning about a nullpointer in a concurenthashmap comming from spongeforge biome related things so i suspect that this is the root cause but i have no knowledge of sponge(forge) internals so i don't know for sure if it is: https://gist.github.com/AEnterprise/482b6f23c2fec9472341dfae24e0e590#file-console-output-L152-L156

**Comment by AEnterprise** [comment] 2017-05-26 20:30
the fakeworld code: https://github.com/AEnterprise/BuildCraft/blob/FakeWorldServer/common/buildcraft/builders/snapshot/FakeWorld.java

**Comment by AEnterprise** [comment] 2017-05-29 08:28
@gabizou do you guys have an idea about what is causing this crash with spongeforge? would be nice if we could have it not blow up

**Comment by AEnterprise** [comment] 2017-06-06 15:57
so i have split the fakeworld into 2 parts now: one that extends WorldServer and one that extends World

when adding spongeforge (7.0.0-BETA-2364) to the mix this produces a number of errors, the final one that crashes the server when our dimension is loaded is again about a UUID being null

relevant code: https://github.com/BuildCraft/BuildCraft/pull/3654

**Comment by Eufranio** [comment] 2017-06-07 19:33
I'm getting (what is looks like to be) the same crash-report: https://hastebin.com/ojuxenevob.sql

**Comment by AEnterprise** [comment] 2017-06-08 07:18
@Eufranio that crash will be fixed when my PR above gets merged although another error will pop up then, we are trying to restore compatibility with sponge because it is used more and more on servers, currently waiting on the busy spongeforge team to have time to look at this

**Comment by bloodmc** [comment] 2017-08-19 04:13
@AEnterprise Is this still an issue with latest SF build?

**Comment by AEnterprise** [comment] 2017-08-19 08:30
it shoudn't be (i forgot about this issue) since 7.99.7 no longer uses a fake world to determine requirements for blueprints (or facade info)

**Comment by bloodmc** [comment] 2017-09-15 20:00
Closing as it should be resolved in latest BC builds.

**Closed as completed by bloodmc** 2017-09-15 20:00 UTC
Labels: type: bug, status: accepted, type: mod incompatibility, version: 1.11 (u), system: world
