### ISSUE TITLE
Ore Excavation mod broken after update

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2274] opened 2018-07-06 08:21 UTC
After updating SpongeForge from 3247 to 3262 using Ore Excavation breaks the blocks but does only drop one block.
Same issue with 3266.

![](https://i.imgur.com/dciAfHg.gif)

**Comment by gabizou** [comment] 2018-07-06 18:13
Is there a specific build this breaks with?

**Comment by Sir-Will** [comment] 2018-07-06 20:14
Yes but I didn't go through the builds to find which one, only got the range which I mentioned in the issue.

**Comment by Aaron1011** [comment] 2018-07-08 23:52
This issue is that OreExcavation explicitly sets Forge's `World.captureBlockSnapshots` field to `true`, and checks `World.capturedBlockSnapshots` after calling `PlayerInteractionManager.tryHarvestBlock`.

Sponge needs to properly add to `World.capturedBlockSnapshots` in our `setBlockState` rewrite.

**EDIT**: While this is necessary to make 'undo' support work in Ore Excavation, it doesn't appear to be the cause of the main issue.

**Comment by Aaron1011** [comment] 2018-07-09 00:25
This should be fixed in the next SpongeForge build.

**Closed as completed by Aaron1011** 2018-07-09 00:25 UTC
Labels: type: bug, system: phase tracker, version: 1.12

**Comment by Sir-Will** [comment] 2018-07-09 17:06
Yep, works again, thanks.
