### ISSUE TITLE
Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by NEXUS2345** [SpongePowered/SpongeForge#580] opened 2016-03-23 23:49 UTC
When breaking any ore from the Dense Ores mod with SpongeForge 4.1.0 build 1217, it causes the following error to be shown in console: https://gist.github.com/NEXUS2345/405bc2e4bd054249044b

Following this, for other clients connected to the server, the block appears to not break, and for all clients in the area, it becomes impossible to break certain block types. This only occurs if SpongeForge is installed and does not depend on the DenseOres version.

**Comment by Aaron1011** [comment] 2016-03-24 01:03
@NEXUS2345: I can't seem to reproduce this. Are you using the latest version of Dense Ores?

**Comment by NEXUS2345** [comment] 2016-03-24 01:09
Yes. We are using FTB Unstable 3.0.41 (Extra Utilities 2 removed, Dense Ores updated to alpha 2.0.3), on Forge 1764, SpongeForge 4.1.0 1217, Java 8 Update 74.

**Comment by Aaron1011** [comment] 2016-03-24 02:29
@NEXUS2345: Hmm, I was cloning it from github, but that appears to be version 2.0.2. I'll try the version from the downloads page.

Would you be able to join #sponge on EsperNet IRC? It would be a great help in tracking down this issue.

**Comment by dh47** [comment] 2016-04-08 03:50
Can also confirm the same is happening with the same error about, both sponge and denseores are installed, once a denseore is mined nothing else can be mined after.

**Comment by Aaron1011** [comment] 2016-04-08 19:21
@dh47: I've had a lot of difficulty reproducing this. Are you consistently able to get that stacktrace, or does it occur randomly when breaking blocks?

**Comment by dh47** [comment] 2016-04-09 04:12
@Aaron1011 - yep, breaking a dense ore block will work but when I want to break something else it won't, and each time you break a block a stacktrace error will be generated in the console.

Would you like me to make a short video?

**Comment by kinggoesgaming** [comment] 2016-04-09 04:25
Break a block type 1 break another type 2 and so on for a few times and put that log so there is comparison if it is the stack being repeated

**Comment by dh47** [comment] 2016-04-09 04:41
Here we go.
http://pastebin.com/b1b1hKXG

**Comment by Aaron1011** [comment] 2016-04-09 13:40
@dh47: Unfortunately, I'm still completely unable to reproduce this. Would you mind making a video?

**Comment by dh47** [comment] 2016-04-09 14:19
Sure.  Will do expect it soon.

**Comment by jpiermarini** [comment] 2016-04-09 21:54
Getting this error as well http://pastebin.com/BcnbT4Tx also using dense ores 2.0.0

**Comment by Aaron1011** [comment] 2016-04-09 23:25
@jpiermarini @dh47 @NEXUS2345: I've tracked down the issue. Sorry for the delay in finding this - I think I either wasn't testing this properly, or had some other issue.

The cause of this problem is due to the way Sponge handles block breaking. Normally, Forge's `Block#getExpDrop` method is called before the broken block has actually been set to air in the world. However, due to Sponge's CauseTracking system, the block has already been set to air in the world when the method is called. Since the method doesn't actually take a `BlockState`, the block in question ends up working with an 'air' blockstate, instead of the actual block being broken.

I'm working on a fix for this.

**Comment by dh47** [comment] 2016-04-10 02:50
@Aaron1011:  Thanks for the update, please let us know witch version to update too after you have sorted a fix.

**Comment by Aaron1011** [comment] 2016-04-10 15:30
For reference, here's the issue on the DenseOres github project: https://github.com/rwtema/DenseOres/issues/122

I'm currently waiting on a change in DenseOres to be able to fix this.

**Comment by bloodmc** [comment] 2016-05-20 20:14
@dh47 @NEXUS2345 does this still occur with latest SpongeForge builds?

**Comment by Aaron1011** [comment] 2016-05-20 23:20
@bloodmc: This won't be resolved until DenseOres makes the needed change.

**Comment by Zidane** [comment] 2016-06-18 17:23
Closing this as its an issue on DenseOre's side.

**Closed by Zidane** 2016-06-18 17:23 UTC
Labels: mod-change-pending, mod-incompatibility
