### ISSUE TITLE
Living Drops Events is fired twice was (Gravestone issue - possibly sponge related)

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1859] opened 2017-11-17 01:11 UTC
Minecraft version: 1.12.2

GaveStone Version; gravestone-1.10.0.jar

SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-14f459d
SpongeForge: 1.12.2-2529-7.0.0-BETA-2730
Minecraft Forge: 14.23.0.2528

Issue we are having is; when players break their graves sometimes the items do not drop, nothing just comes out.

Not sure if sponge related or mod related so reported to both.

See: https://github.com/NightKosh/Gravestone-mod-Graves/issues/239
Video of it happening ^

**Comment by phit** [comment] 2017-11-17 01:13
Update Sponge to latest, and if possible test this without Sponge.

**Comment by phit** [comment] 2017-11-17 20:14
confirmed `LivingDropsEvent` is being fired twice by Sponge

first with [items](https://i.imgur.com/XazT0cF.png), then [without](https://i.imgur.com/rxC9cqJ.png)

**Comment by gabizou** [comment] 2017-11-17 21:09
I see what's happening. Because Sponge does a sanity check for compatibility with Forge (where forge always fires an event, even if there are no drops), and then immediately after, sponge will throw an event with the drop. I'll have this fixed in a bit.

**Comment by Keaton1188** [comment] 2017-11-18 20:45
Sounds good, thx

**Comment by Keaton1188** [comment] 2017-11-19 01:14
So after updating to the latest version, 3 empty gravestones and 1 full now spawn. (it was 2 empty + 1)

![2017-11-19_01 04 18](https://user-images.githubusercontent.com/24898745/32986295-069d4b52-ccc7-11e7-8662-bb3fdd315c84.png)

**Comment by ryantheleach** [comment] 2017-11-20 12:17
This needs to be reverted or fixed, stat. Other bugs this causes are way more annoying.

**Comment by xorinzor** [comment] 2017-11-20 14:14
I had the same thing happen as Keaton1188 on 1.12.2-2529-7.0.0-BETA-2736

**Comment by Keaton1188** [comment] 2017-11-22 09:25
@xorinzor Have you been having an issue where when users break the graves sometimes items do not come out of any of them??

**Comment by xorinzor** [comment] 2017-11-22 09:33
@Keaton1188 we haven't been using SpongeForge that long yet. We were just setting up the server and found out about these issues, then discontinued to use SpongeForge until a stable version is reached.
So I'm afraid I cannot answer your question. I will however later today try to provide an answer to another issue (opened by me) so maybe I'll come across it. If so, I'll let you know.

**Comment by ryantheleach** [comment] 2018-01-27 23:55
Moved this from gab to Faith as he has changes in progress.

**Comment by phit** [comment] 2018-01-28 00:59
Should be fixed in 7.1.0-BETA-2852

**Closed as completed by phit** 2018-01-28 00:59 UTC
Labels: type: bug, status: accepted, system: event, system: phase tracker, version: 1.12
