### ISSUE TITLE
Entities keep causing NoSuchElementException

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#1648] opened 2017-07-14 21:44 UTC
If I set the `deny-chunk-requests` option to `false` it causes the entity tracking crashes:
Crash-Report: https://pastebin.com/BqEJKdYG
Sponge error: https://pastebin.com/Vtx23ca9

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464
- Forge version: 1.10.2-12.18.3.2281

**Comment by Sir-Will** [comment] 2017-07-15 21:57
Crash just happened with it enabled. Seems to only reduce the amount of occurrences.

**Comment by Sir-Will** [comment] 2017-07-22 04:49
@kashike any news for a fix? The crash happens a lot lately.

**Comment by Xfel** [comment] 2017-08-01 19:40
I looked into this, and the crash appears to be coming from wrong assumptions made by the cause tracker's error recovery. When encountering an unexpected Phase during completion, it always assumes that the completion is missing, however in that specific case, we had one completion too much.

Anyways, since the cause tracker is in SpongeCommon, should this issue be moved?

**Comment by phit** [comment] 2017-12-02 22:46
similar to https://github.com/SpongePowered/SpongeForge/issues/1415

**Comment by gabizou** [comment] 2018-01-01 09:09
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by gabizou** 2018-01-01 09:09 UTC
Labels: version: 1.10 (u), system: world
