### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by iLefty** [SpongePowered/SpongeForge#1337] opened 2017-03-08 18:43 UTC
Server is crashing for the unclear reason for me. I fight against this error, long time.
Here you will see today's crash-reports (4 times of this day):
https://yadi.sk/d/nNYwpWrB3FHqKM
All information of server is present at report. I need help!
P.S. At forge forum, have told that a problem in Sponge.

**Comment by Deamon5550** [comment] 2017-03-08 19:36
Please upload your logs to a paste site like http://gist.github.com/ for the future.

This one looks like a world gen issue.

**Comment by iLefty** [comment] 2017-03-09 15:01
http://pastebin.com/2jtkk1PA
http://pastebin.com/zimdVH5v
http://pastebin.com/hCpPa4d7
http://pastebin.com/qv4HZsp3
http://pastebin.com/t1VzEWBt
http://pastebin.com/SnVNaLbQ
All crashes.

**Comment by Deamon5550** [comment] 2017-03-09 18:01
The worldgen one is definitely a duplicate of #1289 the rest are all something else.

**Comment by iLefty** [comment] 2017-03-09 18:56
Really? I think, that's different...

**Comment by Deamon5550** [comment] 2017-03-09 19:07
This one http://pastebin.com/hCpPa4d7 is the exact same issue. The rest are all the something else, but also something I've seen before, I think someone mentioned it was a forge bug, or at least that it occurs in forge as well without sponge.

**Comment by iLefty** [comment] 2017-03-09 19:11
On forge forum said, that this bug in sponge.

**Comment by iLefty** [comment] 2017-03-09 19:13
http://www.minecraftforge.net/forum/topic/52425-server-crash-1102/

**Comment by Deamon5550** [comment] 2017-03-09 19:23
Test without sponge and see if they still occur.

**Comment by iLefty** [comment] 2017-03-10 07:01
There is no opportunity to test without sponge. I will lose plugins for protection and players will create chaos.

**Comment by iLefty** [comment] 2017-03-11 07:04
http://www.minecraftforge.net/forum/topic/52425-server-crash-1102/
So, people said, that error in Sponge...

**Comment by LeftBoy** [comment] 2017-03-13 11:26
Thank you that you undertake nothing. Server crashes continues.

**Comment by Time6628** [comment] 2017-03-13 15:16
Whitelist the server and test without sponge. If you want your issue fixed, you need to test it with your setup.

**Comment by iLefty** [comment] 2017-03-13 15:35
Without players, the problem doesn't arise. 
Tested. Without sponge server worked 20 hours.

**Comment by iLefty** [comment] 2017-03-13 16:51
http://pastebin.com/GHWNJFPG
http://pastebin.com/WPRVE9qH
http://pastebin.com/wNbSf9Wc
http://pastebin.com/3Z5WxdcC
Four more crashes, for today, with sponge.

**Comment by iLefty** [comment] 2017-03-16 13:42
http://pastebin.com/ujfzRaD3
http://pastebin.com/AjUtZxHV
http://pastebin.com/6ia8t9vL
http://pastebin.com/ihD4Xipk
http://pastebin.com/9nXgk4iw
Five more crashes.
YES I LIKE IT! (No.)

**Comment by LeftBoy** [comment] 2017-03-16 16:07
Perhaps I found the reason. Crash was most likely because of function "tracking". I will test.

**Comment by iLefty** [comment] 2017-03-16 17:51
@Deamon5550, what I must do, that crash wasn't?

**Comment by Time6628** [comment] 2017-03-16 18:26
They can't help you unless you can reproduce it.

**Comment by iLefty** [comment] 2017-03-17 04:46
What? I sad, Server normally work without sponge... 20 hours.

**Comment by me4502** [comment] 2017-03-17 04:57
Do you have any plugins that change blocks? Like changes water to slabs (Or vice versa)?

**Comment by iLefty** [comment] 2017-03-17 05:10
In crash-reports present all information about installed plugins and mods. I think, I haven't.

**Comment by bloodmc** [comment] 2017-08-19 01:52
Reopen if this is still an issue with SpongeForge.

**Closed as completed by bloodmc** 2017-08-19 01:52 UTC
