### ISSUE TITLE
Server Crash - java.lang.NoClassDefFoundError: net/minecraft/crash/CrashReportCategory$4

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1103] opened 2016-12-11 17:36 UTC
Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-323db46
    SpongeForge: 1.10.2-2171-5.1.0-BETA-1976
    Minecraft Forge: 12.18.2.2171

A player said they may have been moving a clock with a piston, I will update if we can reproduce it.

https://gist.github.com/ProsperCraft/0c43b4a175b812d6c096731a61887193

Thread: Server thread
Stacktrace:
	at net.minecraft.crash.CrashReportCategory.func_175750_a(CrashReportCategory.java:246)
	at org.spongepowered.common.event.tracking.CauseTracker.notifyBlockOfStateChange(CauseTracker.java:338)
	at net.minecraft.world.WorldServer.func_175685_c(WorldServer.java:1271)
	at net.minecraft.world.World.func_175722_b(World.java:423)
	at net.minecraft.world.WorldServer.spongeNotifyNeighborsPostBlockChange(WorldServer.java:1348)
	at org.spongepowered.common.event.tracking.TrackingUtil.performBlockAdditions(TrackingUtil.java:652)
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:570)
	at org.spongepowered.common.event.tracking.phase.block.PistonMovingPhaseState.unwind(PistonMovingPhaseState.java:58)
	at org.spongepowered.common.event.tracking.phase.block.BlockPhase.unwind(BlockPhase.java:73)
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192)
	at net.minecraft.block.BlockPistonBase.handler$onDoMoveReturn$zbh000(BlockPistonBase.java:118)
	at net.minecraft.block.BlockPistonBase.func_176319_a(BlockPistonBase.java:418)
	at net.minecraft.block.BlockPistonBase.func_189539_a(BlockPistonBase.java:196)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:458)
	at org.spongepowered.common.event.tracking.TrackingUtil.fireMinecraftBlockEvent(TrackingUtil.java:314)
	at net.minecraft.world.WorldServer.redirect$onFireBlockEvent$zjm000(WorldServer.java:768)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1217)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:233)

**Comment by kashike** [comment] 2016-12-11 18:01
#1100

**Comment by Aaron1011** [comment] 2016-12-11 18:54
@ProsperCraft: Can you post your full `fml-server-latest.log`?

@kashike: While those issues have the same error, they might be caused by two different mods.

**Comment by ProsperCraft** [comment] 2016-12-11 23:05
https://gist.github.com/ProsperCraft/5f0234b15ebea6c3a8a53df8cb927685

**Comment by Aaron1011** [comment] 2017-02-19 22:09
I've pushed a commit (https://github.com/SpongePowered/SpongeCommon/commit/3877881828dcf3f24a2dd3a763a8390ab1aed167) that will allow us to recover the original error that preceded the `NoClassDefFoundError`. Anyone experiencing this issue should upgrade to the latest SpongeForge, and post their `latest.log` and `fml-server-latest.log` when this occurs.

**Comment by Sir-Will** [comment] 2017-03-14 21:36
Just got the crash, logs: https://gist.github.com/Sir-Will/c5ec5fe8db10f2bc24910b14bdfd64ff
spongeforge-1.10.2-2254-5.2.0-BETA-2231

**Comment by Aaron1011** [comment] 2017-03-14 21:42
This appears to be cut off.

**Comment by Sir-Will** [comment] 2017-03-14 21:47
Downgraded to 2215 and it's no longer crashing.
Found Not Enough Wands light blocks at the location so this might be related to @bloodmc lightning changes.

Should be no longer cut off.

**Comment by phit** [comment] 2017-11-06 20:05
@ProsperCraft is this still something that happens?

**Comment by ProsperCraft** [comment] 2017-11-06 20:09
Not sure, we are not running a Sponge server right now, all Thermos and forge only for the newer stuff.

**Comment by phit** [comment] 2017-11-06 20:14
Closing this for now then, let me know if you see this again and I will reopen this issue.

**Closed as completed by phit** 2017-11-06 20:14 UTC
Labels: resolution: duplicate
