### ISSUE TITLE
BlockStateContainer Crash every few minutes

### ISSUE THREAD

**Issue by LokeYourC3PH** [SpongePowered/SpongeForge#2638] opened 2019-03-09 00:08 UTC
- SpongeForge version: 1.12.2-2768-7.1.6-RC3597
- Forge version: 14.23.5.2811
- Java version: JDK 8 202
- Operating System: Windows 10 Pro

- Plugins/Mods:
https://pastebin.com/pfNZ2k7k

**Issue Description**
So the server randomly crashes and there is nothing I can do about it, it happens mostly when no player is logged onto the server for a while but can even sometimes happen when people are on it, and I see no apparent way to fix it.

**Logs**
Crashlog: https://pastebin.com/BVCiL7w3
Latest log: https://mega.nz/#!40tlVYaT!9RadK8gAcKfRFoQIV2lmpBBY06Y1Qm8Ar0zyGcMD8wg
Debug log: https://mega.nz/#!s4sF3ALT!iDl-o3Bcv-xGBDRDpxg5Fpy-iwPvDoK52uAQ2Z7hyls

**Comment by gabizou** [comment] 2019-03-09 02:21
The crashlog only shows the issue about starting a server with foam fix's default config:
>FoamFix
>Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable >the following settings in config/foamfix.cfg
>
>B:optimizedBlockPos=false
>B:patchChunkSerialization=false

Duplicate of #2480

**Closed as completed by gabizou** 2019-03-09 02:21 UTC
Labels: resolution: duplicate, version: 1.12

**Comment by LokeYourC3PH** [comment] 2019-03-09 12:44
> 
> 
> The crashlog only shows the issue about starting a server with foam fix's default config:
> 
> > FoamFix
> > Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable >the following settings in config/foamfix.cfg
> > B:optimizedBlockPos=false
> > B:patchChunkSerialization=false
> 
> Duplicate of #2480

That is quite hilarious as I did read that part and DID in fact disable it, I checked the config and I have no idea how it all of a sudden reset itself, thanks.

**Comment by gabizou** [comment] 2019-03-13 22:10
> I checked the config and I have no idea how it all of a sudden reset itself, thanks.

Usually through a mod update the configs sometimes get overwritten, or so I've heard.
