### ISSUE TITLE
Forge does not use the current plugin as the active container

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeForge#452] opened 2015-12-20 01:43 UTC
Currently if a user tries to register an item with forge via calling the following during the GamePreInitializationEvent:
````java
GameRegistry.registerItem(itemObj, "my_item");
````

This is presumable caused by the following returning the mod container to be Sponge instead of the current plugin:
````java
// Code from GameData in the Forge src
private String addPrefix(String name)
...
        ModContainer mc = Loader.instance().activeModContainer();

        if (mc != null)
        {
            prefix = mc.getModId();
        }
...
````

This results in the item being registered as "sponge:my_item" instead of "my_plugin:my_item". This is a change in behavior, and previously this worked correctly. The build where this changed is currently unknown.

**Comment by simon816** [comment] 2015-12-20 01:46
I'm pretty sure this would have been caused by https://github.com/SpongePowered/SpongeForge/commit/22dd21c58b9040be1765fffeff74acdc8ebb10e7

**Comment by Zidane** [comment] 2015-12-20 03:53
Fixed in master

**Closed by Zidane** 2015-12-20 03:53 UTC
