### ISSUE TITLE
Quantum Quarry Mining Issue

### ISSUE THREAD

**Issue by KingDan27** [SpongePowered/SpongeForge#1488] opened 2017-05-04 02:51 UTC
Running a brand new test server with no plugins on FTB Beyond the quantum quarry does not produce any mined materials. works fine without sponge on the same server.

**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2300
- Forge version: forge-1.10.2-12.18.3.2254-universal
- Java version: 8
- Operating System:
 - [X ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: None

**What is the expected result?**
Quarry mines from its own DIM and transfers said items to storage, if no storage avail. quarry does not run

**What is the current result?**
https://gyazo.com/3fb30b2c1962bae137ba421022051370
without storage a quantum quarry will continuously run and even with a storage unit the quarry does not produce any mined materials and will endlessly run (assuming you have power to do so).

[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/975132/fml-server-latest.txt)

**Comment by Sitherious** [comment] 2017-05-05 12:05
your using the wrong forge or sponge forge, try updating your forge to 12.18.3.2281.


forge and sponge need to be the same version numbers as spongeforge is built off of a certain build of forge.

**Comment by ktole1999** [comment] 2017-05-05 12:14
i was told it was recommended not required.

**Comment by phit** [comment] 2017-05-05 12:19
yeah definitely not required and it won't fix your issue
this is also a dupe of a bunch of other issues https://github.com/SpongePowered/SpongeForge/issues?utf8=%E2%9C%93&q=quarry

**Comment by Sitherious** [comment] 2017-05-05 12:21
also have you posted in the mod about this ? https://github.com/rwtema/extrautilities/issues

**Comment by phit** [comment] 2017-05-05 12:24
rwtema doesn't even check that tracker and it's been reported a [bunch of times](https://github.com/rwtema/extrautilities/issues?utf8=%E2%9C%93&q=sponge) there.. use the search

**Comment by LIRIKKER** [comment] 2017-05-06 12:25
#1468 Duplicate Bug Report. Check before you post

**Closed as completed** 2017-05-11 06:57 UTC
