### ISSUE TITLE
Latest EnderIO version causing issues with latest sponge version?

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [SpongePowered/SpongeForge#2344] opened 2018-07-26 09:17 UTC
**I am currently running**

- SpongeForge version: 3206
- Forge version: 14.23.4.2705
- Java version: JRE 1.8.0_172
- Operating System: Windows server 2008 R2 Enterprise edition
- Minecraft version 1.12.2

- Sponge Plugins:
Page 1: https://i.imgur.com/PQIq3yI.png
Page 2: https://i.imgur.com/aaDxnFf.png

Regular minecraft Mods: 
Page 1: https://i.imgur.com/mzd7pnU.png
Page 2: https://i.imgur.com/eHkwFQQ.png
Page 3: https://i.imgur.com/5NcfDDa.png
Page 4: https://i.imgur.com/Y61cT8r.png
Page 5 https://i.imgur.com/zkWWOOd.png
page 6 https://i.imgur.com/zN5nXAB.png
Page 7 https://i.imgur.com/a6fUAag.png
Page 8 https://i.imgur.com/eMbvyPn.png
Page 9 https://i.imgur.com/r31zPbv.png
Page 10 https://i.imgur.com/vCG9XbY.png
Page 11 https://i.imgur.com/4FVdDoc.png

Aka Foolcraft 3 Modpack

**Issue Description**
We are not sure what is happening. The game will crash pretty much an hour after it is started. Here is a crash report. https://pastebin.com/rKkyjmeE
Fairly certain it is something to do with EnderIO as alot of people have said this problem has happened on their servers. 

[crash-2018-07-26_20.28.00-server.txt](https://github.com/SpongePowered/SpongeForge/files/2231248/crash-2018-07-26_20.28.00-server.txt)
[Latest server log before crash.txt](https://github.com/SpongePowered/SpongeForge/files/2231255/Latest.server.log.before.crash.txt)
[Debug before crash.txt](https://github.com/SpongePowered/SpongeForge/files/2231258/Debug.before.crash.txt)

**Comment by gabizou** [comment] 2018-07-26 10:44
Crash reports and logs are all 100% EnderIO code. Looks like they’re not intializing something they should be. Closing as it’s not appearing to be a sponge issue and sounds like it’s happening to others who don’t have sponge installed.

**Comment by yamy19** [comment] 2018-07-27 19:24
Ender io says it's an issue on you end though
https://github.com/SleepyTrousers/EnderIO/issues/4747

**Comment by theBluebaerry** [comment] 2018-07-27 22:31
Wrong link from Yamy, use this one https://github.com/SleepyTrousers/EnderIO/issues/4768

**Comment by HenryLoenwind** [comment] 2018-07-28 00:02
No, we did NOT say this is a SpongeFogre issue. We asked the OP to run his world without SpongeForge to see if there is a weird interaction with it or not. However, people don't like to cooperate in finding the bugs they report and prefer to start arguing...

**Comment by theBluebaerry** [comment] 2018-07-28 01:49
"sponge modifys how the calls are handled, resulting in different from normal execution chains ... something modifys an object along the way of the call and the call...runs into an nullpointer, which means a missing information (hence the expectation of normal forge to never fail at this point and never deliver a null)" 
If I'm not mistaken is this not telling us that its a problem with sponge forge? 
Also the "bug in other software" label was added directly after OP was told to run it without spongeforge. The message "Remove sponge forge and try again" is not a helpful piece of feedback and makes it seem like you are pointing the finger to sponge forge. A more helpful message would have been "Could you try running the server without sponge forge and see if the crash still happens?"
Its hard to cooperate when the people responsible for bugs are straight away passive aggressive with their comments...

**Comment by nzminecraftDOTcom** [comment] 2018-07-28 02:16
Why immediately jump on songeforge's back then, there's another 200 mods on that list that it could be.
EnderIO shows up in the entire crash report, so we're going to assume.. EnderIO has the fault.

**Comment by ryantheleach** [comment] 2018-07-28 19:18
Guys Guys. Settle down.

SpongeForge is an extremely large CoreMod that **does** make drastic differences to the Forge / Minecraft code.

Whilst we make effort to be compatible, sometimes problems arise.

For example, let me explain a compatibility issue between Sponge and EnderIO.

You get a crash when using a large modpack, that contains Sponge or EnderIO in some fashion.

In this case, the crash log showed everything belonging to EnderIO. 

The question is Why? It's a NPE, which is generally and usually (without taking a deeper look) something not being initialized when you expect it to.

So what could be the cause?

1. EnderIO should be initializing something earlier then it expects.
2. Sponge is (either accidentally, or on purpose so it can track + rollback,) changing the order or timing that code gets called in.

What's the easiest way to troubleshoot whether this is a possible Sponge issue?

Remove Sponge.

If the error still occurs, it **can't** possibly be Sponge, and the EnderIO guys would own it.

Now, removing EnderIO isn't quite as easy to test, because if it's something you already know is in EnderIO code, removing it just removes all of EnderIO.

So, if removing Sponge doesn't create the bug, does that mean it's "Sponges fault"?

Not necessarily, It depends whether our changes are meaningful, on purpose, and doesn't violate expectations too badly. Would another mod or coremod that wasn't Sponge possibly come across this issue? Maybe. Can the EnderIO code be changed to be more friendly to other mods? Maybe. But you can't just draw the blame one way.

It just means that an incompatibility exists.

We appreciate help from mod authors, really appreciate it, as we don't have knowledge of every other mod in existence, and working with us can often result in code that's more resilient, or our tighter contracts and checks can arguably make a mod "more correct" (See various network thread async calls that some mods make)

Our dev's don't have too much time, so sometimes snap decisions are made based on the evidence, everyone makes mistakes, and we are happy to accept bugs where it can be shown that we are violating assumptions common to **all** mods.

**Comment by theBluebaerry** [comment] 2018-07-28 22:29
Exactly, an incompatibility exists. I didn't realise that asking the two teams to work together to fix the problem would knock so many noses out of joint, my mistake.

**Comment by HenryLoenwind** [comment] 2018-07-29 14:43
as ryantheleach said, plus:

There are 2 types of bugs: Those that are self-contained and those that happen because 2 or more mods interact. Classifying a crash into "self-contained" or "mod interaction" is *extremely* important---you can have a thousand coders looking at your code for a thousand years and they will not be able to find a "interaction" bug. You have to have the other mod available to find it.

Often the stack trace already contains that tiny part of the other mod you need. Or it has one reference so you can look up the other mod's code up on github. But as often there is nothing in the crash report telling you which mod is part of the issue. Then you have to find which mod it is, and the way to do so is to remove mods until the issue doesn't happen anymore.

But even before doing that, you want to classify the issue. Our strategy usually is:

1) Look at the crash. Is it obvious what's happening?
2) Look at the code that crashes. What could be the reasons?
3) See if it also happens without the mods that are known to change the game the most? (optifine, spongeforge, etc.)
4) Find a way to recreate the crash with the least amount of mods.
4a) Load that set into a development environment and let it crash there. (usually doesn't work)
4b) Make a special mod version that logs all kinds of stuff and have the person for whom it crashes run the game with that. (usually doesn't work as the OP is AWOL at that point)
5) Change the code to catch the error and log a warning instead.

**Comment by gabizou** [comment] 2018-07-29 16:09
So, my question then is, what circumstances could the NPE be happening? From my perspective, SpongeForge doesn't interfere beyond posting events in sync with the forge events when we share parity between them (so like BlockBreakEvent vs ChangeBlockEvent). In this case however, once calling EnderIO's server tick listener, it's seemingly all EnderIO code.

What sort of situations are caused for the `null` from an inventory being retrieved here:
https://github.com/SleepyTrousers/EnderIO/blob/d4f969585f914cb7fdc827d8b6c14fbca1423aea/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/item/NetworkedInventory.java#L262

Yet, it looks like there was a case for it as a null check was added here:
https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/item/NetworkedInventory.java#L247

So, seeing as the code in question that resulted in the NPE was already checked to check for nulls, I believe the ultimate resolution is to update EnderIO.

Forgive me for having made it sound like I was passing the blame around without explanation. Just having explained here my reasoning in the opening statement is what was implied from the crash reports presented in this issue.

**Closed as completed by gabizou** 2018-07-29 16:09 UTC

**Comment by theBluebaerry** [comment] 2018-07-29 20:11
Sorry gazibou, I wasn't actually referring to you when I was talking about passing the blame around, you've only been helpful in everything you've said. Is it confirmed that the latest EnderIO fixes this problem? I thought we were using the latest version and if not why the heck wouldn't they just point us towards an update instead of running us around :/ I'm not a coder so I really don't understand any of the technical stuff.

**Comment by ImMorpheus** [comment] 2018-07-29 20:18
The fix gabizou was talking about is part of this commit https://github.com/SleepyTrousers/EnderIO/commit/fb935e24e10e10ef213c66c48dbd7901c73765e1 (8 days ago).
The latest version of EnderIO (following the download link on enderio.com) is 5.0.29 (which is the one you're using according to the issue), released on Jul 3, 2018.
There's no "update".

**Comment by HenryLoenwind** [comment] 2018-07-30 09:35
Lol, in all this back and forth about diagnosing, I completely forgot what the crash was about. ;)

Ok, back to the subject: What happens here is that a neighboring block suddenly doesn't have an inventory anymore. Usually when a block changes, the conduit gets notified and removes the connection to that block. However, with the new Forge Capabilities blocks can gain/lose inventories without having to notify their neighbors. I suspect this is happening here. The original guess was that the neighbor block was removed/replaced without a block change notification being fired, which would be something SpongeForge could be responsible for.

I added a ton of additional checks lately. They were not needed in Minecraft 1.7.10 (i.e. before there were Capabilities) as blocks couldn't change having an inventory or not. So if there was an inventory in a neighbor, it would stay there as long as the block wasn't removed.

**Comment by gabizou** [comment] 2018-07-30 17:23
> 
The original guess was that the neighbor block was removed/replaced without a block change notification being fired, which would be something SpongeForge could be responsible for.

But according to the stacktraces, this is during a server tick listener, not a neighbor notification (which yes, sponge heavily modifies to replicate vanilla block logic in correct order while allowing for some block tracking). I don’t see how once we get to this line in the stacktrace, we (spongeforge) could interfere:

crazypants.enderio.base.handler.ServerTickHandler.onServerTick(ServerTickHandler.java:56)

Unless you’re meaning that something happening long before the server tick event is occurring to cause the issue to show up only during the server tick event? If that’s the case, I’d need a lot more insight from you to figure out how it’d be happening in code locations to try and reproduce in debugging to resolve the potential issue in Sponge’s code base.

**Comment by HenryLoenwind** [comment] 2018-07-30 17:43
Without further evidence about which block it was, I'll assume this was a "block lost its inv cap without block change notification" and will not look deeper.

Technical background: Conduits keep a list of external connections which is updated on block change notifications and rely on that list being accurate when ticking the network. Scanning all their neighbors every time they want to send an item somewhere would be a teensy bit too expensive... ;)
