### ISSUE TITLE
Switching Phase error endlessly being created and freezing server.

### ISSUE THREAD

**Issue by JakePost** [SpongePowered/SpongeForge#1856] opened 2017-11-16 00:33 UTC
**I am currently running...**

- SpongeForge version: 1.12.2-2529-7.0.0-BETA-2732
- Forge version: 14.23.0.2529
- Java version: V8.131
- Operating System: Windows Server 2012

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 

**Mods:**
Animania
BiblioCraft
Biomes O' Plenty
Chisel
CraftStudios API
Decocraft
FastAsyncWorldEdit
Hats
KleeSlabs
Mantle
Natura
NetherPortalFix
Pam'sHarvestCraft
WorldEdit
iChunUtil
ptrmodlelib

**Plugins:**
AdminShop
EconomyLite
GriefPrevention
Hello MMO (Custom)
Hey I Saved Your Stuff
InstantRespawn
LuckPerms
NPCs
Nucleus
Nucleus API
VoxelSniper

After a few minutes of the server running it starts to spam console with a Switching Phase error (seen below) causing all players to time out and the server to close down from it reaching the max tick time.

https://gist.github.com/ajcool1050/988564e7afd35c12dcd6c0a4518052d4

**Comment by phit** [comment] 2017-11-16 00:35
dont just copy and paste the old issue... add a full `fml-junk-earlystartup.log` and remove the irrelevant crash report

**Comment by JakePost** [comment] 2017-11-16 00:36
Too large to post, One sec...

**Comment by phit** [comment] 2017-11-16 00:40
use https://gist.github.com

**Comment by JakePost** [comment] 2017-11-16 01:00
Edited the main post with a link to it.

**Comment by phit** [comment] 2017-11-16 01:04
Thanks! For now set `verbose=false` and `verbose-errors=false` in the `cause-tracker` section of the `configs/sponge/global.conf`. That should reduce the amount of spam in the console.

**Comment by JakePost** [comment] 2017-11-16 01:13
Will that prevent the server from timing out?

**Comment by phit** [comment] 2017-11-16 01:14
this shouldnt cause the server to freeze in the first place it's just logging errors

**Comment by Tencao** [comment] 2017-11-16 11:48
I can confirm the same bug or something very similar and it does indeed cause the server to lag to the point of freezing. Sadly the log is so big that simply attempting to copy it into gist causes the browser to crash, so I will copy the repeating error. (The log file is around 150mb+)
https://gist.github.com/Tencao/1658b70c6b4c1f628d9ae8cac3680e93

**Comment by ryantheleach** [comment] 2017-11-16 13:21
@Tencao Was this after a recent upgrade of anything? And do you have a mod list.

**Comment by Tencao** [comment] 2017-11-16 13:36
This is on sponge 1.12.2-2529-7.0.0-BETA-2732
Forge - 14.23.0.2544
Not sure exactly when this bug started, as I was dealing with another bug alongside this, but since that one has been fixed, this is the only one left. 

Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BungeeTabListPlus-SpongeBridge, LuckPerms, Nations, Nucleus, Prism, ProjectCore for SpongeAPI 7.x, ProjectPortals for SpongeAPI 7.x, ProjectWorlds for SpongeAPI 7.x, RankUpper, SpongyCord, Total Economy

Mods (148): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Animania, Applied Fluidics, Applied Llamagistics, Applied Llamagistics Core, AutoPackager, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Better Advancements, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bloodmoon, BuildCraft, BuildCraft Lib, Can I Join Now?, Chameleon, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Compacter, ComputerCraft, Corail Pillar, Corail Pillar - Quark Extension, Coralreef, CoroUtil Library, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, DeepResonance, DiscordIntegration, Dynamic Surroundings, ElecCore, Elevator Mod, Ender Zoo, EnderStorage, Energy Converters, Environmental Tech, Ex Compressum, Ex Nihilo Creatio, Extended Mod Config, Extended Renderer, Extra Utilities 2, Extreme Reactors, FTBLib, Fairy Lights, FoamFix, FoamFixCore, Forestry, Funky Locomotion, GenDustry, Hardcore Darkness, HelpFixer, Immersive Engineering, Immersive Petroleum, Industrial Wires, IndustrialCraft 2, Inventory Tweaks, Iron Chest, IvToolkit, JEI Bees, Just Enough Items, KleeSlabs, Localized Weather & Storms, Login Shield, MPUtils, MTLib, Malisis Blocks, MalisisCore, MalisisDoors, Mantle, MineTweakerRecipeMaker, Missing Pieces, Mod Tweaker, ModPack Basic Tools, More Bees, MrCrayfish's Furniture Mod, Natura, NetherPortalFix, New Age Bee Breeding, No More Drops, NoMoreRecipeConflict, Not Enough Wands, Plethora, Plethora Core, PlusTiC, ProjectE, Quark, Reborn Core, Recurrent Complex, Redstone Flux, Redstone Paste, Reforged, Roguelike Dungeons, SAOMC Library, Shadowfacts' Forgelin, Simply Conveyors & More, Spartan Shields, Spectrite, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Teslafied, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, UBC Ore Registrar, Underground Biomes, UniDict, Valkyrie Lib, WTFs Expedition, WanionLib, Wither Skeleton Tweaks, WorldEdit, XNet, Zero CORE, denseores

**Comment by phit** [comment] 2017-11-16 13:41
These are the mods that overlap between you and OP

Animania
BiblioCraft
Biomes O' Plenty
Chisel
CraftStudios API
KleeSlabs
Mantle
Natura
NetherPortalFix

**Comment by Tencao** [comment] 2017-11-16 14:12
Just got this crash, not sure if it's related or a different issue.
https://paste.ee/r/DWKJz

**Comment by ryantheleach** [comment] 2017-11-16 14:15
@Tencao Can you try with FoamFix Lawful, also I don't think that crash is related. Lets keep that on a separate ticket if you can show that's Sponge related, but I don't see Sponge featuring significantly in that stack trace.

**Comment by Tencao** [comment] 2017-11-16 14:18
For now I'll put that to a side until I can find a way to reproduce it. Going to switch to foamfix lawful and report back, do you want me to try with verbose on?

**Comment by Tencao** [comment] 2017-11-16 21:55
Just to report, so far things have been smooth, but this has been with verbose off, I have no idea if the errors are still there and repeating.

**Comment by phit** [comment] 2018-01-16 02:28
Gonna close this as there are multiple different issues in here that are probably covered somewhere else by now or fixed, generally the logging should be behave a lot better now thanks to https://github.com/SpongePowered/SpongeCommon/commit/e02ffc86fd5762450c4e2d1f97e4dda346acef3b

**Closed as completed by phit** 2018-01-16 02:28 UTC
Labels: version: 1.12
