### ISSUE TITLE
Spongeforge 1.11.2 for forge 2388

### ISSUE THREAD

**Issue by LuxerIThink** [SpongePowered/SpongeForge#1619] opened 2017-07-01 17:53 UTC
Can you update spongeforge on version 1.11.2 for forge 2388?

**Comment by phit** [comment] 2017-07-01 19:37
any reason why?

**Comment by LuxerIThink** [comment] 2017-07-01 21:59
Because CoFH Core need forge 2388:/

**Comment by phit** [comment] 2017-07-01 22:06
no it doesn't, it just doesn't work with Sponge right now
so this issue is a dupe of #1604

**Closed as completed** 2017-07-02 03:55 UTC
Labels: resolution: duplicate

**Comment by KingLemming** [comment] 2017-07-03 13:35
No, CoFHCore does actually require 2388 now, this is correct.

**Comment by phit** [comment] 2017-07-03 13:44
Good to know, but Sponge build with Forge 2315 works fine with Forge 2388 so even that is not an issue.

**Comment by KingLemming** [comment] 2017-07-03 13:51
Right. And that shouldn't be an issue at all. We upgraded to 2388 because it includes a couple of PRs we made that actually remove ASM, which hopefully reduces the number of conflicts. ;)
