### ISSUE TITLE
SpongeForge crashes server MCProHosting

### ISSUE THREAD

**Issue by grandmabaldwin** [SpongePowered/SpongeForge#3232] opened 2020-12-09 05:47 UTC
SpongeForge version: spongeforge-1.12.2-2838-7.3.1-RC4093.jar

    Forge version: 2838

    Java version: 8

    Operating System: Windows 10 (server is hosted through mcprohosting)

    Plugins/Mods:
   BOP-Patch-1.0
   BiomesOPlenty-1.12.2-7.0.1.2444-universal
   journeymap-1.12.2-5.7.1
OptiFine_1.12.2_HD_U_F5
    pixelExtras-1.12.2-2.5.6
    Pixelmon-1.12.2-8.1.2-universal
spongeforge-1.12.2-2838-7.3.1-RC4093
gravestone-1.10.2
landmanager-1.12.2-1.5.0
worldedit-forge-mc1.12.2-6.1.10-dist
Gameshark-1.12.2-6.0.0-universal
Morpheus-1.12.2-3.5.106

Issue Description: I can get rid of the spongeforge java and it runs fine. server has no issues. second i download sponge, it crashes immeditately upon start. I've tried changing it to "Aaa_SpongeForge", i've tried downloading a few other ones, not sure what the issue is. Would appreicate some help (:

Server crashes on startup when sponge forge is installed, if removed, it loads fine. Log: 
[latest.log.txt](https://github.com/SpongePowered/SpongeForge/files/5663753/latest.log.txt)

**Comment by clienthax** [comment] 2020-12-10 13:40
Dupe of https://github.com/SpongePowered/SpongeForge/issues/3221

**Closed as completed by clienthax** 2020-12-10 13:40 UTC
