### ISSUE TITLE
Dupe with Animal Nets from Hatchery

### ISSUE THREAD

**Issue by rob5251** [SpongePowered/SpongeForge#1982] opened 2018-02-02 00:26 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2586-7.1.0-BETA-2873
- Forge version: 14.23.1.2586
- Java version: 1.8.0_161
- Operating System: Win10

- Plugins/Mods:
Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Hatchery

Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge

**Issue Description**
The animal net is used to capture and move mobs (particularly chickens), right clicking will pick up the animal and shift-right click **on the nesting pen** will place it down. The problem is that when SpongeForge is on the server instead of the animal being removed from the net when placed, the animal will be placed **into the nesting pen** but also remains inside the net. This then renders the net as useless as it will still show an animal is inside it, but will not allow you to pickup/place.

If you try to place it on the ground nothing will happen though.

Logs:
https://gist.github.com/rob5251/d55906dc855538c7cd3a7cc63f545e76

**Comment by ryantheleach** [comment] 2018-02-02 05:50
> . The problem is that when SpongeForge is on the server instead of the animal being removed from the net when placed, the animal will be placed but also remains inside the net.

Does this allow animals to be duplicated?

To devs: last time this fixed it, but it was on the old phase tracker, https://github.com/SpongePowered/SpongeCommon/commit/4648e4af32f68b07690df05d5446a5b74b99f2b2

It may need to be ported to the new phase tracker.

Edit: Marked as high priority due to potential duplication of 10 10 10 Diamond Chickens etc. (Imagine a mob farm that produced diamonds)

**Comment by rob5251** [comment] 2018-02-02 21:49
You can duplicate them, but only by using the net to place the chicken in the Nesting Pen. If you try to place it on the ground nothing will happen though.

So yeah if you had a 10/10/10 diamond chicken from the chickens mod in a nesting pen, you could duplicate it to a bunch of other pens.

**Comment by ryantheleach** [comment] 2018-02-03 14:18
@rob5251 Thanks for the updated reproduction steps, That definitely would have tripped people over. I've edited your OP for the updated info.

**Comment by JoeSGT** [comment] 2018-03-21 15:45
having the same issue on 
hatchery-1.12.2-2.1.2
spongeforge-1.12.2-2611-7.1.0-BETA-2963
Forge - 14.23.2.2624

**Comment by JoeSGT** [comment] 2018-04-04 11:51
Can someone look into this please, some of my players are starting to abuse this D:

**Comment by Wissi** [comment] 2018-08-20 22:06
Original Issue opened Feb 1st, almost 7 months ago and many many sponge versions since. Is there a version that includes a fix as @ryantheleach stated:

> To devs: last time this fixed it, but it was on the old phase tracker, SpongePowered/SpongeCommon@4648e4a
It may need to be ported to the new phase tracker.

It is a Dupe Issue. Any mob caught remains in net and can be infi placed over and over.
Issue still persist on newest "stable" version of Sponge (atm of writing this) using:
SpongeForge version: 1.12.2-2705-7.1.0-BETA-3401
Forge version: 1.12.2 - 14.23.4.2705

**Closed as completed** 2018-08-23 17:16 UTC
Labels: type: bug, type: mod incompatibility, system: phase tracker
