### ISSUE TITLE
WorldEvent.Load missing Phase

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#2007] opened 2018-02-14 02:14 UTC
**I am currently running**
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-6aa4e43
SpongeForge: 1.12.2-2611-7.1.0-BETA-2916
Minecraft Forge: 14.23.1.2607
Java 1.8_151

Plugins (10): ```Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, FastAsyncWorldEdit, GriefPrevention, LuckPerms, MagiBridge, Nucleus, WorldEdit```

Mods (60): ```Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Actually Additions, Advanced Rocketry, Advanced Rocketry Core, Applied Energistics 2, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, Bookshelf, BuildCraft, BuildCraft Compat, BuildCraft Lib, Chameleon, ChickenChunks, CodeChicken Lib, Colossal Chests, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cyclops Core, Death Quotes, Elevator Mod, EnderStorage, Forestry, Gravestone Mod, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Wires, IndustrialCraft 2, Iron Backpacks, Iron Chest, JourneyMap, Just Enough Items, Mantle, MineColonies, Morpheus, PortalGun, RandomPatches, Reborn Core, Steve's Carts 2, Storage Drawers, TOP Addons, The One Probe, Tinkers' Construct, UniDict, Vulpes library, WanionLib, Wireless Crafting Terminal 2, iChunUtil, p455w0rd's Library```

Stacktrace (remapped): https://gist.github.com/ryantheleach/7416c8978dfd606f96a5e01b94d7f89d
Looks like Minecolonies is trying to set blocks before the first world tick (`onWorldLoad`), and Sponge doesn't like it. Is it a problem with Minecolonies or Sponge?

**Comment by gabizou** [comment] 2018-02-14 08:17
I'd almost say that Minecolonies should not be modifying worlds while they are being loaded, but alas, this *can* be resolved in sponge specifically. Thoughts @Zidane @Raycoms?

**Comment by bloodmc** [comment] 2018-02-14 21:53
This looks fine as the mod is running its logic during Forge's 'WorldEvent.Load' which is fired after the world has been loaded. The problem is definitely our side and should be fixed with a proper phase to handle this.

**Comment by Raycoms** [comment] 2018-02-14 21:57
We'll even remove this part of the code since it's called without purpose, nevertheless, it should probably be also fixed on your side =)

**Comment by phit** [comment] 2019-02-17 22:59
fixed with https://github.com/SpongePowered/SpongeForge/commit/85cf30cdb10e1e78ebc31bfc20f4db9163f51fb1

**Closed as completed by phit** 2019-02-17 22:59 UTC
Labels: system: event, type: mod incompatibility, system: phase tracker, version: 1.12
