### ISSUE TITLE
Sentient Pickaxe

### ISSUE THREAD

**Issue by ninja0773** [SpongePowered/SpongeForge#2143] opened 2018-05-12 19:01 UTC
**I am currently running**

- Forge version: 8.0.99.99
- Operating System: Windows 10

- Plugins/Mods: Sky Factory 3

**Issue Description**
Tossing a sentient pickaxe on the ground to summon a sentient specter doesn't consume the pickaxe.

**Comment by phit** [comment] 2018-05-12 19:07
no version info, unsupported version (we only support 1.12.2 at this point), a dupe of https://github.com/SpongePowered/SpongeForge/issues/1366 and no mod list

**Closed as completed by phit** 2018-05-12 19:07 UTC
Labels: resolution: duplicate, version: 1.10 (u), resolution: unsupported
