### ISSUE TITLE
Some turtle events being fired as wrong user

### ISSUE THREAD

**Issue by Lemmmy** [SpongePowered/SpongeForge#2034] opened 2018-03-03 13:01 UTC
Moved from https://github.com/MinecraftPortCentral/GriefPrevention/issues/610. On this server, turtles have a 100% chance of duping (+ their inventories) if they are moving up and a player is jumping on top of them. We have been able to reproduce the underlying issue on a fresh server this time.

**Update:** This is still an issue on SpongeForge 2951, and GriefPrevention 559.

# Production server - MC 1.12.2, SpongeForge [(mod list)](https://gist.github.com/Lemmmy/7568dcabfc9658539b44bc2ae55d1637)
We made a claim as Lemmmy (non-admin) and placed a turtle. Lemmmy ran [this code](https://gist.github.com/Lemmmy/18fb37954d7feef37d312590231155a2) on it. Yemmel (admin user, respecting claims, not trusted in the claim) jumped on the turtle as it was moving upwards. The turtle fully duped twice. We reproduced this multiple times, there was a 100% chance of dupe.

# Reproduction on test server - MC 1.12.2, SpongeForge

[**This video demonstrates the dupe**](https://shitty.download/t4dK.mp4)

- Run [forge 2611 installer](https://files.minecraftforge.net/)
- Added mods:
  - [cc-tweaked-1.80pr1.4](https://minecraft.curseforge.com/projects/cc-tweaked/files)
  - [griefprevention-1.12.2-4.3.0.555](http://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention/)
  - [LuckPerms-Sponge-4.1.15.jar](https://ci.lucko.me/job/LuckPerms/)
  - [spongeforge-1.12.2-2611-7.1.0-BETA-2944](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2)
- /lp creategroup admin
- /lp group admin parent set default
- /lp group admin permission set griefprevention.admin
- /lp group default permission set griefprevention.user
- /lp user ADMIN_USER group set admin
- Claim an area of land as TEST_USER
- **Do not /ignoreclaims as ADMIN_USER**
- Place a turtle as TEST_USER
- Place a block of coal in the turtle's inventory
- Run `edit dupe`
- Insert the code:

```lua
turtle.refuel()
while true do
    for i = 1, 5 do turtle.up() end
    for i = 1, 5 do turtle.down() end
end
```

- Ctrl, enter to save
- Ctrl, right arrow twice, enter to exit
- Run `dupe`, the turtle should begin vertically oscillating
- Run `/gpdebug on` as ADMIN_USER
- As ADMIN_USER, jump on top of the turtle. When it is moving upwards, start jumping.
- ChangeBlockEvent.Break will be triggered as ADMIN_USER instead of TEST_USER. Turtle will either stop moving, or completely dupe. If it stops moving, restart the server and try again.

![](https://shitty.download/tyd2.png)

**Comment by SquidDev** [comment] 2018-03-03 13:47
I've done some experimentation and found a different issue which I think stems from the same issue (namely jumping on turtles).

### Reproduction steps
 1. Setup LP and GP as normal. 
 2. Log in as two separate players.
 3. Create a claim with Player 1 and place a turtle inside.
 4. Insert a stack of items in the inventory and run `turtle.place()` to place a block. Note the block is placed. Destroy the block.
 5. Jump on the turtle several times with Player 2.
 6. Run `turtle.place()` again. Note the block is not placed, being destroyed instead.

You can achieve similar things with `turtle.dig()`: jumping on the turtle with Player 2 will result in it reporting "Cannot break unprotected block", despite Player 1 owns it.

**Comment by Lemmmy** [comment] 2018-03-03 14:56
The underlying bug can be reproduced with pistons. While I have not managed to get it to dupe the block being moved by the piston, I have managed to get it to disable the piston entirely.

### Reproduction steps

1. Place a sticky piston with a block on top as TEST_USER.
![](https://shitty.download/UVDK.png)
2. Connect the repeater to a redstone clock. I used ComputerCraft ([code])(https://gist.github.com/Lemmmy/e027ce66187fb14e1b0fd6e6517bf7a6)) as a clock for simplicity, but any should work.
3. Jump on the moving block as ADMIN_USER. Sometimes you have to jump on it, then jump next to it.
4. The piston should stop moving entirely.

Every time the piston state changes, logging.block-tracking says that ADMIN_USER is causing the block to move, even if ADMIN_USER goes offline.

![](https://shitty.download/NTdW.png)

[**GP debug log**](https://gist.github.com/anonymous/4afb97707bffef9dbb9fff96590a9c00)

**Comment by bloodmc** [comment] 2018-03-03 16:20
Ended up being GP issue. Fixed in commit
https://github.com/MinecraftPortCentral/GriefPrevention/commit/6e57991c02df71b9f63ecc4e696d3a4fd613b0f7

**Closed as completed by bloodmc** 2018-03-03 16:20 UTC
Labels: version: 1.12

**Comment by bloodmc** [comment] 2018-03-03 19:50
It turns out there was also a related sponge bug which has been fixed =).
