### ISSUE TITLE
Console Crash(Prism?) : Something happened when trying to unwind a phase

### ISSUE THREAD

**Issue by CDAGaming** [SpongePowered/SpongeForge#2149] opened 2018-05-15 13:11 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3074
- Forge version: 14.23.3.2655
- Java version: 1.8.0_161
- Operating System: Windows 10

- Plugins/Mods: Nucleus, FastAsyncWorldEdit, Prism, CatClearLag, Aether II v1.0.4, OrbisAPI v1.1, Aether Legacy v3.0, LuckPerms, ServerListPlus, TotalEconomy

**Issue Description**
This Log is now being spammed into console, after Updating SpongeForge from 3070 to 3074:
https://gist.github.com/CDAGaming/61c05f1cc50ce5b7670f976c3d720f7d

**Comment by phit** [comment] 2018-05-15 16:12
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2147

**Closed as completed by phit** 2018-05-15 16:12 UTC
Labels: resolution: duplicate, version: 1.12
