### ISSUE TITLE
Crash from village/villager issue

### ISSUE THREAD

**Issue by maddyn99** [SpongePowered/SpongeForge#2120] opened 2018-04-24 15:01 UTC
**I am currently running**

- Forge version: 
        spongeforge-1.12.2-2655-7.1.0-BETA-0.jar (hotfix/test build?)
        forge-1.12.2-14.23.3.2655-universal.jar
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.87-xxxx-std-ipv6-64
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Linux aka Centos 7

- Plugins/Mods: See attached crash log for mods list. Not sure you want all 250 pasted here.

**Issue Description**

Server crash with a villager issue.

https://pastebin.com/EvAXK5Lb

[crash-2018-04-24_09.35.38-server.txt](https://github.com/SpongePowered/SpongeForge/files/1943327/crash-2018-04-24_09.35.38-server.txt)

**Comment by Aaron1011** [comment] 2018-04-24 15:29
@maddyn99: Can you please upload all relevant log files?

**Comment by phit** [comment] 2018-04-24 15:49
@Aaron1011 I edited their issue, they had an open `<!--` comment tag before the log links, so they didnt show up

**Comment by ryantheleach** [comment] 2018-06-16 00:22
It would be worth revisiting this.

I'm not sure if it has the same root cause as the recent changes to Sponge Forge that addressed Villager Careers, but it would be worth trying again to see if the issue still persists.

**Comment by gabizou** [comment] 2018-06-16 01:04
Should be resolved in SpongeForge 3188.

**Closed as completed by gabizou** 2018-06-16 01:04 UTC
Labels: version: 1.12, system: world gen
