### ISSUE TITLE
Server closed with SpongeForge [Exception ticking world / java.lang.IllegalArgumentException]

### ISSUE THREAD

**Issue by McPersson** [SpongePowered/SpongeForge#2932] opened 2019-08-15 14:15 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3892 _(later: 1.12.2-2825-7.1.6)_
- Forge version: 14.23.5.2838
- Java version: Version 8 Update 221
- Operating System: Windows 10 Pro 64-bit

- Plugins/Mods:
A lot, but it hardly makes sense.

**Issue Description**
With SpongeForge, the server closes in a specific area of the map. Without Sponge, everything works stably, no crash.

Tell me what it is worth to fix, so that everything returns to a healthy state. I apply logs. Thank you!

**Logs:** 
https://gist.github.com/McPersson/1a3faa87678b68f27dc88ff257bddbe7

**Comment by clienthax** [comment] 2019-08-15 15:14
Dupe of https://github.com/SpongePowered/SpongeForge/issues/2930

**Closed as completed** 2019-08-15 17:53 UTC
Labels: resolution: duplicate, version: 1.12
