### ISSUE TITLE
Redstone pistons do not retract when powered directly by a repeater.

### ISSUE THREAD

**Issue by dubbeanh** [SpongePowered/SpongeForge#2669] opened 2019-04-06 14:31 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3639
- Forge version:  2768
- Java version: java 8
- Operating System: Win10

- Plugins/Mods:  This is on Dockter's Almura server. An exact list of plugins from a player is not available.

**Issue Description** These are all vanilla mechanics. The problem started started right after an update. Dockter said I needed to report it here. This is all the information I have available to me:

Basic setup before activation:
![2019-04-06_09 06 44](https://user-images.githubusercontent.com/719561/55670827-8d21b280-584e-11e9-86b7-2fdf0b720b51.png)

After initial activation: Normal behavior
![2019-04-06_09 07 01](https://user-images.githubusercontent.com/719561/55670833-9ca0fb80-584e-11e9-8eb8-9e07294252ae.png)

After deactivation, the piston is now stuck in the activated position, and cannot retract without breaking it.
![2019-04-06_09 07 46](https://user-images.githubusercontent.com/719561/55670840-b9d5ca00-584e-11e9-8d94-d549adb882fe.png)

Furthermore, levers and buttons require two interactions to toggle now after their first activation.

Hope this is remotely helpful.

**Comment by gabizou** [comment] 2019-04-09 03:40
Should be fixed in latest, please retest (3642)

**Comment by selkiess** [comment] 2019-04-10 19:16
Can confirm that piston retracting when powered directly by repeater is fixed in latest, however needing to flip levers twice is not.

**Comment by gabizou** [comment] 2019-04-11 15:48
So, there's a complicated issue that I've noticed and it's rarely reoccurring in my tests: Neighbor notifications or sometimes block changes are not being sent to clients until a second interaction is performed. I'm not sure whether there's a combination of how ProjectRed works and Sponge's delayed processing of tracking (it records the various changes as transactions and then throws events, and then processes them), but if you can try with the flag `-Dsponge.shouldFireAll=true` and see if the issue gets resolved, it will narrow down to a particular subsystem that is failing to work with ProjectRed for some reason or another.

**Comment by selkiess** [comment] 2019-04-12 23:48
do you still want me to attempt it with that flag or is it set after that commit?

**Comment by phit** [comment] 2019-04-12 23:56
should be all set without the flag

**Comment by selkiess** [comment] 2019-04-13 00:09
> should be all set without the flag

awesome, when do new builds usually  get pushed out? This was the main thing keeping me from updating spongeforge to newer builds.

**Comment by phit** [comment] 2019-04-13 00:12
every commit makes a new build, apparently the last few are missing on our site, in the meantime you can find newer builds here http://files.minecraftforge.net/spongepowered

**Comment by selkiess** [comment] 2019-04-20 01:30
Can confirm that levers/buttons still require 2 hits to toggle on the latest build(3663). Should i create i new issue or should this one be reopened since its cites it.

**Comment by phit** [comment] 2019-05-31 02:42
still not able to reproduce this, what is your mod list and try updating to latest (RC3740+) again

**Comment by gabizou** [comment] 2019-05-31 02:53
Pretty sure this was actually fixed because I've never seen it reoccur since that commit, and I've retested a lot in this last month.

**Closed as completed** 2019-06-04 19:39 UTC
Labels: status: needs testing, version: 1.12, status: waiting for reply
