### ISSUE TITLE
"Shift T" feature from Quark raises java.lang.ClassCastException

### ISSUE THREAD

**Issue by bluelightning32** [SpongePowered/SpongeForge#2547] opened 2019-01-02 09:17 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3512
- Forge version: 14.23.5.2781 for Minecraft 1.12.2
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_191
- Operating System: Fedora 29

- Plugins/Mods:
  * All the mods from Enigmatica Expert 2 v1.48a.
      * Most notably, including Quark r1.5-137, with [3dc57e2](https://github.com/Vazkii/Quark/commit/3dc57e28112bd9982caaf8c8ec94cae68a5869bf) backported.
   * Also these plugins: Inventory Sync, JdaLibraryLoader, LuckPerms, Nucleus, UltimateChat

**Issue Description**
Previously pressing 'Shift T' to display an item name in chat caused this [bug](https://github.com/Vazkii/Quark/issues/1102) in Quark. The Quark author tried to fix it, and I backported the fix to test it. Now I get a new exception, because the system can't tell which player sent the chat message.

Exception Message:
https://gist.github.com/bluelightning32/276509addd4b0a7f2a9dfde8ee0e69b6

**Comment by Shybella** [comment] 2019-01-05 19:57
I believe this is a duplicate of https://github.com/SpongePowered/SpongeForge/issues/2542

I think this has been resolved now.

**Comment by ImMorpheus** [comment] 2019-01-05 20:02
@Shybella That's a different issue.

@bluelightning32 

> The Quark author tried to fix it, and I backported the fix to test it. Now I get a new exception, because the system can't tell which player sent the chat message.

Try to reproduce with the official release. We don't have the source code of your custom version

**Comment by bluelightning32** [comment] 2019-01-06 06:28
I was hoping you'd look at the stack trace and instantly know it was some kind of threading problem, like last time.

I retested with Enigmatic Expert 2 v1.49, which version r1.5-138 of Quark. Here's the exception message:
```
[22:26:06] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: com.google.common.util.concurrent.ListenableFutureTask cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5-RC3512]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:3970) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassCastException: com.google.common.util.concurrent.ListenableFutureTask cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostServerChatEvent(SpongeToForgeEventFactory.java:309) ~[SpongeToForgeEventFactory.class:1.12.2-2768-7.1.5-RC3512]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:240) ~[SpongeToForgeEventFactory.class:1.12.2-2768-7.1.5-RC3512]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5-RC3512]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5-RC3512]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5-RC3512]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) ~[SpongeEventManager.class:1.12.2-2768-7.1.5-RC3512]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) ~[SpongeImpl.class:1.12.2-2768-7.1.5-RC3512]
        at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:60) ~[ChatUtil.class:1.12.2-2768-7.1.5-RC3512]
        at net.minecraft.server.management.PlayerList.func_148544_a(PlayerList.java:2097) ~[pl.class:?]
        at vazkii.quark.management.feature.LinkItems.linkItem(LinkItems.java:61) ~[LinkItems.class:?]
        at vazkii.quark.base.network.message.MessageLinkItem.lambda$handleMessage$0(MessageLinkItem.java:33) ~[MessageLinkItem.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
```

**Comment by bluelightning32** [comment] 2019-02-03 12:51
I retested with 1.12.2-2768-7.1.5 stable. 156d2d0 was not a fix. It left the forge event as null, which promptly raised a NullPointerException:

```
[04:36:43] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:711) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:702) ~[EventBus.class:?]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostServerChatEvent(SpongeToForgeEventFactory.java:313) ~[SpongeToForgeEventFactory.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:240) ~[SpongeToForgeEventFactory.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) ~[SpongeModEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) ~[SpongeEventManager.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) ~[SpongeImpl.class:1.12.2-2768-7.1.5]
        at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:60) ~[ChatUtil.class:1.12.2-2768-7.1.5]
        at net.minecraft.server.management.PlayerList.func_148544_a(PlayerList.java:2098) ~[pl.class:?]
        at vazkii.quark.management.feature.LinkItems.linkItem(LinkItems.java:61) ~[LinkItems.class:?]
        at vazkii.quark.base.network.message.MessageLinkItem.lambda$handleMessage$0(MessageLinkItem.java:33) ~[MessageLinkItem.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
```

**Closed as completed** 2019-02-03 13:17 UTC
Labels: status: needs testing, version: 1.12
