### ISSUE TITLE
[1.10.2] Sponge could not apply patch

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#897] opened 2016-09-09 00:06 UTC
http://pastebin.com/VbdpeC1D

Forge version - 1.10.2-12.18.1.2076
Sponge version - 1.10.2-2073-5.0.0-BETA-1709

I'm sorry if this has been reported before, I just want this to be fixed.

**Comment by ryantheleach** [comment] 2016-09-09 04:56
One of your mods is loading forge classes too early.

A possible workaround for this is to rename SpongeForge so that it runs before the other CoreMods.

Try prepending a _ to the file name of SpongeForge's mod jar.

https://github.com/SpongePowered/SpongeForge/issues/511

**Comment by Tencao** [comment] 2016-09-09 09:11
I added a _ to the beginning of the mod jars name, however the same crash happens.

**Comment by Tencao** [comment] 2016-09-09 09:31
I would also like to add that I have tried also updating CodeChickenLib to the latest version, 1.10.2-2.2.3.74, however this hasn't changed this issue

**Comment by Zidane** [comment] 2016-09-09 18:41
Closing this as this isn't a Sponge issue. You have a mod loading ModMetadata too early. Remove mods one by one until the issue stops happening and report that to the mod author.

**Closed by Zidane** 2016-09-09 18:41 UTC
Labels: mod-change-pending, mod-incompatibility

**Comment by Tencao** [comment] 2016-09-09 18:49
While I understand this, and I will do what you've suggested, isn't it possible to put some kind of failsafe into sponge to prevent an outright crash if a mod loads before sponge?, since currently everything loads perfectly fine without sponge, whether or not a mod is loading it too early.

I appreciate the help so far, but I do believe having some kind of permanent solution to this problem for future mods would be better than tracking down each individual mod and requesting them to fix compatability their end.

**Comment by Aaron1011** [comment] 2016-09-09 19:06
@Tencao: The issue is that Sponge isn't a normal mod, by any stretch of the imagination. In order to work, it needs to be able to modify many different classes (including many core Forge classes) in order for it to properly implement that API. The way things are currently set up, mods which loads certain classes early on can prevent Sponge from being able to apply the necessary transformations.

Ideally, Sponge would be able to register all of the necessary components for class transformation well before any mods have the chance to do so. However, that's currently not possible with the way Forge is setup.

For more details, see [this issue](https://github.com/SpongePowered/SpongeForge/issues/511).

**Comment by ProgrammedSoul** [comment] 2016-12-23 21:55
You are probalby using ic2 or some mod add a subfolder in mod folder on its own. In this case forge goes through the folder first then turns to all the other jar mod files. If I make a folder on my own and drop sponge in, it would not load. If i put sopnge in ic2 folder it got deleted upon loading. A solution can be put your core mod inside a folder begin with a "_" as well?

**Comment by Tencao** [comment] 2016-12-23 21:57
The issue was AE2, not IC2, and sadly the sponge devs have tried to assist them but they refused to work with them, so the issue with AE2 remains

**Comment by phit** [comment] 2016-12-24 00:28
Just fyi I maintain a fork of AE2 that works with Sponge [here](https://github.com/Stonebound/Applied-Energistics-2#about),

**Comment by tmoflash** [comment] 2016-12-30 18:33
@phit thank you for this. Much appreciated.
