### ISSUE TITLE
Mixins Issue!

### ISSUE THREAD

**Issue by BreeOge** [SpongePowered/SpongeForge#1627] opened 2017-07-03 19:13 UTC
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar
- Forge version: Tried both 2315 and 2388
- Java version: Latest
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 

**What is the expected result?**
To load

**What is the current result?**
Mixin crash

07/03/2017 14:05:13
14:05:13Forge Mod Loader version 13.20.1.2388 for Minecraft 1.11.2 loading
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131, running on Windows Server 2016:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_131
main/WARN - FML 07/03/2017 14:05:15
14:05:15The coremod org.minimallycorrect.libloader.LibLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
main/INFO - LibLoader 07/03/2017 14:05:15
14:05:15Found libs:
Console 07/03/2017 14:05:15
14:05:15[com.eclipsesource.minimal-json.minimal-json-0.9.4
org.javassist.javassist-3.22.0-CR1
org.minimallycorrect.modpatcher.ModPatcher-1.11.2-SNAPSHOT
org.minimallycorrect.mixin.Mixin-1.0-SNAPSHOT
com.github.javaparser.javaparser-core-3.2.4
org.json.json-20090211
me.nallar.whocalled.WhoCalled-1.1
me.nallar.JavaPatcher-1.6
org.minimallycorrect.javatransformer.JavaTransformer-1.8-SNAPSHOT]
main/WARN - FML 07/03/2017 14:05:15
14:05:15The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
main/INFO - FML 07/03/2017 14:05:15
14:05:15[AstralCore] Initialized.
main/WARN - FML 07/03/2017 14:05:15
14:05:15The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod io.drakon.forgelinFR.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod net.malisis.switches.asm.MalisisSwitchesPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
main/INFO - FML 07/03/2017 14:05:15
14:05:15Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar
Loading tweaker org.spongepowered.asm.launch.MixinTweaker from timewarp-2.2.1-r6.0.0.jar
main/INFO - LaunchWrapper 07/03/2017 14:05:15
14:05:15Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
main/INFO - mixin 07/03/2017 14:05:15
14:05:15SpongePowered MIXIN Subsystem Version=0.6.13 Source=file:/D:/CubeCoders/AMP/Instances/ApertureScience/Minecraft/mods/spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar Env=SERVER
Compatibility level set to JAVA_8
Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
main/WARN - LaunchWrapper 07/03/2017 14:05:15
14:05:15Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
main/INFO - LaunchWrapper 07/03/2017 14:05:15
14:05:15Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
main/INFO - TickProfiler 07/03/2017 14:05:15
14:05:15TickProfiler v1.11.2-jenkins.34 coremod injectData called, loading patches
main/INFO - ModPatcher 07/03/2017 14:05:15
14:05:15ModPatcher running under classloader net.minecraft.launchwrapper.LaunchClassLoader
main/INFO - LaunchWrapper 07/03/2017 14:05:16
14:05:16Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
main/INFO - JavaPatcher 07/03/2017 14:05:16
14:05:16Logging Patcher debug info of 1 class patches
me.nallar.javapatcher.patcher.Patcher$ClassPatchDescriptor@7b50df34
main/INFO - FML 07/03/2017 14:05:17
14:05:17Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
main/INFO - LaunchWrapper 07/03/2017 14:05:17
14:05:17Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
main/INFO - Aroma1997Core 07/03/2017 14:05:17
14:05:17Finished data injection.
Finished data injection.
main/INFO - LaunchWrapper 07/03/2017 14:05:17
14:05:17Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
main/INFO - IC2-core 07/03/2017 14:05:17
14:05:17Loaded library EJML-core-0.26.jar.
main/INFO - LaunchWrapper 07/03/2017 14:05:17
14:05:17Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
14:05:18Calling tweak class org.spongepowered.asm.launch.MixinTweaker
main/INFO - mixin 07/03/2017 14:05:18
14:05:18Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@bdc8014
main/INFO - LaunchWrapper 07/03/2017 14:05:18
14:05:18Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
main/INFO - FML 07/03/2017 14:05:18
14:05:18[AstralTransformer] Loading patches...
[AstralTransformer] Initialized! Loaded 6 class patches!
main/INFO - LaunchWrapper 07/03/2017 14:05:19
14:05:19Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
main/INFO - malisiscore 07/03/2017 14:05:19
14:05:19[ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
[ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
[ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
[MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.BlockRendererDispatcher
[MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.RenderItem
[MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.BlockModelShapes
[TextureMapTransformer] Hook registered for net.minecraft.client.renderer.texture.TextureMap
[ClientNotifTransformer] Hook registered for net.minecraft.world.World
[ClientNotifTransformer] Hook registered for net.minecraft.world.WorldServer
main/INFO - LaunchWrapper 07/03/2017 14:05:19
14:05:19Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
main/INFO - malisiscore 07/03/2017 14:05:19
14:05:19[MalisisSwitchesTransformer] Hook registered for net.minecraft.world.World
main/INFO - LaunchWrapper 07/03/2017 14:05:19
14:05:19Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
Loading tweak class name org.minimallycorrect.modpatcher.api.tweaker.ModPatcherTweaker
Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
Calling tweak class org.minimallycorrect.modpatcher.api.tweaker.ModPatcherTweaker
Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
Loading tweak class name org.minimallycorrect.modpatcher.api.tweaker.ModPatcherTweaker2
Calling tweak class org.minimallycorrect.modpatcher.api.tweaker.ModPatcherTweaker2
main/INFO - ModPatcher 07/03/2017 14:05:19
14:05:19Transformers: [net.minecraftforge.fml.common.asm.transformers.PatchingTransformer@7eae3764, org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy@10dc7d6, TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.BlamingTransformer, FMLCorePlugin), TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.SideTransformer, FMLCorePlugin), TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer, FMLCorePlugin), TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer, FMLCorePlugin), TransformerWrapper(codechicken.lib.asm.ClassHierarchyManager, CCLCorePlugin), TransformerWrapper(codechicken.lib.asm.CCL_ASMTransformer, CCLCorePlugin), TransformerWrapper(codechicken.nei.asm.NEITransformer, NEICorePlugin), TransformerWrapper(li.cil.oc.common.asm.ClassTransformer, TransformerLoader), TransformerWrapper(reborncore.mixin.transformer.MixinTransformer, RebornCoreASM), TransformerWrapper(org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer, SpongeCoremod), net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer@4f668f29, net.minecraftforge.fml.common.asm.transformers.AccessTransformer@716e431d, hellfirepvp.astralsorcery.core.AstralTransformer@7e744f43, cofh.asm.CoFHAccessTransformer@11a8042c, invtweaks.forge.asm.ITAccessTransformer@6a4ccef7, org.spongepowered.mod.asm.transformer.SpongeAccessTransformer@69391e08, net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer@35eb4a3b, net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer@64b3b1ce, org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy@6884f0d9, TransformerWrapper(cofh.asm.CoFHClassTransformer, CoFH Loading Plugin), TransformerWrapper(cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager, CoFH Loading Plugin), TransformerWrapper(invtweaks.forge.asm.ContainerTransformer, Inventory Tweaks Coremod), TransformerWrapper(net.malisis.core.util.chunkcollision.ChunkCollisionTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.core.util.chunkblock.ChunkBlockTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.core.renderer.transformer.MalisisRendererTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.core.renderer.icon.asm.TextureMapTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.core.util.clientnotif.ClientNotifTransformer, MalisisCorePlugin), TransformerWrapper(net.malisis.switches.asm.MalisisSwitchesTransformer, MalisisSwitchesPlugin), TransformerWrapper(net.fybertech.nwr.NWRTransformer, NWRTweak), net.minecraftforge.fml.common.asm.transformers.TerminalTransformer@49ec6a9f, org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy@26b95b0b, org.minimallycorrect.modpatcher.api.ModPatcherTransformer$ClassTransformer@5f7da3d3]
main/INFO - FML 07/03/2017 14:05:20
14:05:20[AstralTransformer] Transforming afj : net.minecraft.item.ItemStack with 1 patches!
[AstralTransformer] Applied patch PATCHMODIFYATTRIBUTES
main/INFO - OpenComputers 07/03/2017 14:05:20
14:05:20Successfully patched sx.recreateLeash.
main/INFO - mixin 07/03/2017 14:05:20
14:05:20A re-entrant transformer '$wrapper.li.cil.oc.common.asm.ClassTransformer' was detected and will no longer process meta class data
main/INFO - FML 07/03/2017 14:05:20
14:05:20[AstralTransformer] Transforming sw : net.minecraft.entity.EntityLivingBase with 1 patches!
[AstralTransformer] Applied patch PATCHKNOCKBACKEVENT
main/INFO - malisiscore 07/03/2017 14:05:21
14:05:21Found hooks for net.minecraft.item.ItemBlock (adv)
Found hooks for net.minecraft.network.NetHandlerPlayServer (mi)
main/WARN - mixin 07/03/2017 14:05:21
14:05:21@Mixin target net.minecraft.server.management.PlayerProfileCache$ProfileEntry is public in mixins.common.core.json:server.management.MixinPlayerProfileCacheEntry and should be specified in value
main/INFO - FML 07/03/2017 14:05:21
14:05:21[AstralTransformer] Transforming auo : net.minecraft.world.chunk.Chunk with 1 patches!
[AstralTransformer] Applied patch PATCHBLOCKMODIFY
main/INFO - malisiscore 07/03/2017 14:05:21
14:05:21Found hooks for net.minecraft.world.chunk.Chunk (auo)
Found hooks for net.minecraft.world.World (ajs)
Found hooks for net.minecraft.world.World (ajs)
Found hooks for net.minecraft.world.World (ajs)
Found hooks for net.minecraft.world.WorldServer (lw)
main/WARN - mixin 07/03/2017 14:05:23
14:05:23Discarding synthetic public method copy in mixins.common.core.json:entity.MixinEntity because it already exists in net.minecraft.entity.Entity
main/INFO - Sponge 07/03/2017 14:05:23
14:05:23/* */
/* Failed on class : net.minecraft.world.World */
/* During phase : DEFAULT */
/* Mixin : world.MixinWorld */
/* Config : mixins.forge.core.json */
/* Error Type : org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException */
/* Caused by : Unknown */
/* Message : PRIVATE @Overwrite method func_175638_a in mixins.forge.core.json:world.MixinWorld cannot reduce visibiliy of PUBLIC target method */
/* */
/*************************************************************************************************************************************************************/
Attempting to shut down the VM cleanly
main/INFO - FML 07/03/2017 14:05:23
14:05:23Java has been asked to exit (code -1) by net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:665).
This is an abortive exit and could cause world corruption or other things
Exit trace
Console 07/03/2017 14:05:23
14:05:23java.lang.Throwable
at net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:672) [FMLCommonHandler.class:?]
at org.spongepowered.mod.mixin.handler.TerminateVM.terminate(TerminateVM.java:113) [TerminateVM.class:1.11.2-2315-6.1.0-BETA-2432]
at org.spongepowered.mod.mixin.handler.MixinErrorHandler.onApplyError(MixinErrorHandler.java:195) [MixinErrorHandler.class:1.11.2-2315-6.1.0-BETA-2432]
at org.spongepowered.asm.mixin.transformer.MixinTransformer$ErrorPhase$2.onError(MixinTransformer.java:111) [spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar:1.11.2-2315-6.1.0-BETA-2432]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:889) [spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar:1.11.2-2315-6.1.0-BETA-2432]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:853) [spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar:1.11.2-2315-6.1.0-BETA-2432]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:613) [spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar:1.11.2-2315-6.1.0-BETA-2432]
at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184) [spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar:1.11.2-2315-6.1.0-BETA-2432]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_131]
at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_131]
at java.lang.Class.getDeclaredMethods0(Native Method) [?:1.8.0_131]
at java.lang.Class.privateGetDeclaredMethods(Unknown Source) [?:1.8.0_131]
at java.lang.Class.privateGetMethodRecursive(Unknown Source) [?:1.8.0_131]
at java.lang.Class.getMethod0(Unknown Source) [?:1.8.0_131]
at java.lang.Class.getMethod(Unknown Source) [?:1.8.0_131]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.11.2-13.20.1.2388-universal.jar:?]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.11.2-13.20.1.2388-universal.jar:?]

**Comment by Mumfrey** [comment] 2017-07-03 19:24
Duplicate of #1604.

**Closed as completed by Mumfrey** 2017-07-03 19:24 UTC
Labels: resolution: duplicate
