### ISSUE TITLE
Well of Suffering Crashes server with Villagers

### ISSUE THREAD

**Issue by axle2005** [SpongePowered/SpongeForge#1512] opened 2017-05-15 16:56 UTC
StackTrace: 
```Description: Ticking block entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1859)
	at net.minecraft.entity.passive.EntityVillager.func_145748_c_(EntityVillager.java:675)
	at net.minecraft.util.DamageSource.func_151519_b(SourceFile:181)
	at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:105)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:499)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:3080)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:502)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3337)
	at WayofTime.bloodmagic.ritual.RitualWellOfSuffering.performRitual(RitualWellOfSuffering.java:97)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.performRitual(TileMasterRitualStone.java:218)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:80)
	at WayofTime.bloodmagic.tile.base.TileTicking.func_73660_a(TileTicking.java:20)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2803)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2790)
	at net.minecraft.world.World.func_72939_s(World.java:6012)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)```

**I am currently running...**
BloodMagic-1.10.2-2.1.9-78
- SpongeForge version: 2328
- Forge version: 2281
- Java version: 8
- Operating System: 
<!-- Replace the empty space (" ") in with an "x" within the brackets. -->
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows
<!-- You can get a list of plugins/mods by running the `/sponge plugins` command on your server -->
- Plugins/Mods: 
```[12:55:27] [Server thread/INFO]: Plugins (209): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Energistics 2 Core, Aroma1997Core, Not Enough Items, OpenComputers (Core), CoFH ASM, FoamFixCore, ccl-entityhook, Nucleus Mixins, CoFH Core, Actually Additions, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, Baubles, Botania, Akashic Tome, Just Enough Items, AppleSkin, Aquaculture, ArchitectureCraft, Aroma1997Core|Helper, Aroma1997's Dimensional World, Morph-o-Tool, Psi, Quark, AutoRegLib, Bed Bugs, Better Builder's Wands, BetterMobsDisposal, BiblioCraft, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, CodeChicken Lib, Brandon's Core, Ceramics, Chameleon, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, MineTweaker 3, Dark Utilities, PTRModelLib, Decocraft, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, Storage Drawers, Drawers & Bits, Elevator Mod, Embers, EnderCore, Ender IO, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Extra Utilities 2, Zero CORE, Extreme Reactors, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Forgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, Funky Locomotion, Funnels, GenDustry, Gravitation Suite, Hammer Core, HelpFixer, Hopper Ducts, Mantle, Tinkers' Construct, Immersive Engineering, LunatriusCore, InGame Info XML, Interaction Wheel, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, KleeSlabs, Long Fall Boots, MalisisCore, MalisisDoors, Mercurius, Modular ForceField System, MmmMmmMmmMmm, mob_grinding_utils, MTLib, Mod Tweaker, Railcraft, More Bees, Morpheus, ModPack Utilities, ModPack Basic Tools, MrTJPCore, ShetiPhian-Core, Multi-Storage, Natura, Nether Portal Fix, Open Glider, p455w0rd's Library, Pam's HarvestCraft, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, projectred-tansportation, ProjectRed Exploration, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Thermal Foundation, Redstone Arsenal, Refined Relocation, Refined Storage, Reliquary, RFTools, RFTools Control, RFTools Dimensions, Roots, Sampler, ServerRedirect, Signals, SimpleVoidWorld, Simple Retrogen, Simply Jetpacks 2, Sleeping Bag, Snad, Solar Flux Reborn, Steve's Carts 2, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, TechReborn, Thermal Expansion, TickProfiler, Tinkers Tool Leveling, TorchMaster, Translocator, Useful Nullifiers, WanionLib, Wireless Crafting Grid, Wireless Crafting Terminal, Woot, WorldEdit, WirelessRedstone-CBE, XNet, YABBA, AdminShop, BetterKits, BetterOntime, Kai's Commons, BetterRelocation, Block Restrictor, SynX, BTickets, ClearMob, DevcoChatFilter, Sync, DevcoSpongeRandomThings, GriefPrevention, DimReseter, DirectAutoProfiler, Expanse, Holograms, Item Restrictor, krules, LuckPerms, Nucleus, RemoteSampler, RunWhenPlayerOnline, ServerListPlus, ServerStatistics, SimpleAntiAFK, SynAdminTools, Total Economy, UUIDProvider, UniDict```

**What is the expected result?**
Well of suffering takes life from villagers. 

**What is the current result?**
Crashes the server

https://gist.github.com/axle2005/d8d98825452a6cc9e079b83298ceb6d8

**Comment by gabizou** [comment] 2017-05-15 17:08
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1467

**Closed as completed by gabizou** 2017-05-15 17:08 UTC
