### ISSUE TITLE
Sponge-Forge does not create Lava Crystal Block of ArmorPlus Mod

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1260] opened 2017-02-11 03:55 UTC
Sponge-Forge does not create Lava Crystal Block of ArmorPlus Mod. I can find that block in single play world.(Default settings) I always check at a new world and same version mods&plugin, but I can find only single play. so I think it is sponge issue.

armorplus-1.11.2-9.5.4.5-beta.jar
spongeforge-1.11.2-2226-6.0.0-BETA-2114.jar
( Forge version is 2226 at client and server )

**Comment by Aaron1011** [comment] 2017-02-12 20:02
@Deamon5550: Can you take a look at this?

**Comment by Lichthagel** [comment] 2017-02-23 16:46
+1 I can agree on that

**Comment by phit** [comment] 2017-07-18 19:24
for reference https://github.com/TheDragonTeam/ArmorPlus/blob/1.11/src/main/java/net/thedragonteam/armorplus/worldgen/OreGen.java

https://github.com/TheDragonTeam/ArmorPlus/issues/96

**Comment by phit** [comment] 2017-12-02 02:43
Can't reproduce with 
armorplus-1.12.2-11.8.1.27-beta.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2748.jar

![image](https://user-images.githubusercontent.com/2097483/33510924-f57020ba-d712-11e7-8e41-1d6f232ed06f.png)

**Comment by phit** [comment] 2018-01-01 15:50
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:50 UTC
Labels: version: 1.11 (u)
