### ISSUE TITLE
Botania NPE ShapedOreRecipe

### ISSUE THREAD

**Issue by Awex0101** [SpongePowered/SpongeForge#1709] opened 2017-08-11 05:28 UTC
**I am currently running...**
- SpongeForge version: 1.11.2-2393-6.1.0-BETA-2535
- Forge version: 2393
- Java version: 1.8.0_131, Oracle Corporation
- Java VM Version: Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
- Operating System: Linux (amd64) version 2.6.32-696.3.1.el6.x86_64
- Plugins/Mods: OpemModsCores, Astral Sorcery, PSI, Autoreglib, baubles, bedbugs, betterbuilderswands, crossroads, guideapi, bloodmagic, bloodarsenal, botania, cyclopscore, eleccore, deepresonance, dooglamoocitiesmod, embers, valkyrielib, environmentaltech, fastleafdecay, mantle, tconstruct, immersiveengineering, immersivepetroleum, journeymap, lazmodder, magistics, natura, netherportalfix, nomagi, openmods, openblocks, refinedstorage, xreliquary, roguelike, roots, snad, totemic, vampirism, teamlapen-lib, and woot. No plugins.
**What is the expected result?**
Server to start.
**What is the current result?**
The server does not start.
Crash-Report: https://hastebin.com/zupenewuqi.py

Botania throws a npe when forge tries to serialise the bauble box's inventory as a copy of itemstack. https://github.com/Vazkii/Botania/blob/1.11/src/main/java/vazkii/botania/common/item/ItemBaubleBox.java#L83

This only happens with sponge forge installed.

**Comment by Aaron1011** [comment] 2017-08-19 05:23
I can't reproduce this on the latest SpongeForge and Botania (both 1.11). Can you re-test this?

**Comment by bloodmc** [comment] 2017-09-15 15:56
Closing as it cannot be reproduced.

**Closed as completed by bloodmc** 2017-09-15 15:56 UTC
Labels: version: 1.11 (u)
