### ISSUE TITLE
Run-away Phase Tracker Errors

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/SpongeForge#2395] opened 2018-08-21 14:24 UTC
**I am currently running**

- SpongeForge version: 3406
- Forge version: 1.12.2 - 2705
- Java version: 8, b171
- Operating System:  win10

Outputs:  
- https://gist.github.com/Dockter/d534ab0be2e47fd37e3d270b9dfab445
- https://gist.github.com/Dockter/e639ba16e611ef678e72ba740aa51b11

My servers log files for a 12 hour period are a few hundred MB's.  I may be able to provide additional information, just ping me.

**Comment by Zidane** [comment] 2018-08-21 14:41
```
[00:03:12] [Server thread/ERROR] [Sponge]: /**************************************************************************************************/
[00:03:12] [Server thread/ERROR] [Sponge]: /*                             Exception occurred during a PhaseState                             */
[00:03:12] [Server thread/ERROR] [Sponge]: /**************************************************************************************************/
[00:03:12] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best effort to not throw exceptions randomly                  */
[00:03:12] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most cases, something else triggered this                   */
[00:03:12] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash by catching it. The following stacktrace                */
[00:03:12] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                        */
[00:03:12] [Server thread/ERROR] [Sponge]: /**************************************************************************************************/
[00:03:12] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: EntityTickPhase                                            */
[00:03:12] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                              */
[00:03:12] [Server thread/ERROR] [Sponge]: /*     - Owner: EntityPlayerMP['Chimwolfeye'/185595, l='Asgard', x=-1381.32, y=70.00, z=-1013.52] */
[00:03:12] [Server thread/ERROR] [Sponge]: /*     - Source: EntityCustomNpc['Cuero'/2193, l='Asgard', x=-1382.50, y=70.00, z=-1013.50]       */
[00:03:12] [Server thread/ERROR] [Sponge]: /*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                   */
[00:03:12] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@24bf2faf                                              */
[00:03:12] [Server thread/ERROR] [Sponge]: /**************************************************************************************************/
[00:03:12] [Server thread/ERROR] [Sponge]: /* StackTrace:                                                                                    */
[00:03:12] [Server thread/ERROR] [Sponge]: /* java.lang.NullPointerException: null                                                           */
[00:03:12] [Server thread/ERROR] [Sponge]: /*  Phases Remaining: 
```

@gabizou unrelated a bit but we fix the places where this stuff may trigger to not send an empty-stack NPE? I can't tell at all where the issue is.

**Comment by phit** [comment] 2018-12-30 23:48
@Dockter you still seeing this? or can I close this, there was a few spammy issues like this in the past but we haven't had any recent reports for it

@Zidane that's a jvm flag https://stackoverflow.com/questions/2411487/nullpointerexception-in-java-with-no-stacktrace/3010106#3010106
you should have the first few occurences with a stacktrace, after a while they get cut for performance

**Closed as completed** 2019-02-12 19:03 UTC
Labels: system: phase tracker, version: 1.12, status: waiting for reply
