### ISSUE TITLE
IC2 explosion event cannot be captured

### ISSUE THREAD

**Issue by loveyanbei** [SpongePowered/SpongeForge#1462] opened 2017-04-24 03:53 UTC
When a IC2 TNT , IC2 nuke or IC2 Nuclear Reactor was placed near residence and detonated.
RedProtect plugin cannot protect the residence from being affected.
I tried to print log in onExplosion(ExplosionEvent.Detonate event) but the listener callback was not called
I think sponge forge didn't catch the explosion caused by mod..

**Comment by loveyanbei** [comment] 2017-04-24 11:09
Will you fix it in the future?
I mean if can hook to all classes extended from NMS classes, it will be not necessary for me to write an extra plugin to hook into IC2Explosion, IC2Potion,etc.

**Comment by Eufranio** [comment] 2017-04-24 16:03
I created an issue here: https://github.com/SpongePowered/SpongeForge/issues/1383 about the explosions.

**Comment by phit** [comment] 2017-07-18 20:36
dupe of #1383

**Comment by kashike** [comment] 2017-07-18 20:37
Duplicate of #1383.

**Closed by kashike** 2017-07-18 20:37 UTC
Labels: type: duplicate
