### ISSUE TITLE
EMC Desync

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2675] opened 2019-04-08 09:40 UTC
**I am currently running**

- SpongeForge version: 7.1.6 RC3616
- Forge version: 2815
- Java version: 8
- Operating System: Windows10

- Plugins/Mods:

Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, Broadcast, CarrotShop, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyCrates, HuskyUI, LuckPerms, MMCReboot, MagiBridge, MaintenanceSponge, Nucleus, Slash Discord, Total Economy, WorldEdit

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Wireless Terminals (AE2WTLib), Actually Additions, Actually Baubles, Advanced Rocketry, Advanced Rocketry Core, Animus, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, ArchitectureCraft, ArmoreableMobs, ArtemisLib, Artisan Worktables, Astral Sorcery, Athenaeum, AutoRegLib, Avaritia, B.A.S.E, BNBGamingLib, Baubles, Baubley Heart Canisters, Bigger Packets, please !, Blood Magic: Alchemical Wizardry, BnBGamingCore, Bookshelf, Botania, Botania Tweaks, Botania Tweaks Core, Brandon's Core, Building Gadgets, CEU, Ceramics, Chickens, Chisel, CleanView, Clumps, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, ContentTweaker, Cooking for Blockheads, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Crying Obsidian, Cucumber Library, Cyberware, Cyclic, Cyclops Core, Deadly Monsters, Deep Mob Learning, Deep Mob Learning - Blood Magic Addon, Diet Hopper, Dimension Stages, Dimensional Control, Doomlike Dungeons, Draconic Evolution, Dropt, EmberRoot Zoo, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Powertools, Ender IO endergy, Ender Utilities, EnderCore, EnderStorage, Extra Utilities 2, FTB Library, FTB Quests, FTB Utilities, FTB Utilities: Backups, FastWorkbench, Floralchemy, Flux Networks, FoamFix, FoamFixCore, ForceVoidWorld, Forge Microblocks, Forge Multipart CBE, Forge Votifier, Funky Locomotion, Game Stages, GregTech Community Edition, Guide-API, Guidebook, Hardcore Darkness, Hit With Axe, HotOrNot, Hunger Overhaul, Ice and Fire, InControl, Industrial Foregoing, InitialInventory, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Tweaks, Iron Chest, It's the little things, Item Filters, Just Enough Dimensions, Just Enough Energistics, Just Enough Items, LLibrary, Laser Creeper Robot Dino Riders From Space, Let's Encrypt Craft, LibrarianLib, LibrarianLib Stage 2, LittleTiles, LittleTilesCore, LootTweaker, MCMultiPart, MTLib, Mantle, McJtyLib, Mekanism, MightyEnderChicken, MineTogether, MineTogetherServer, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, Modular Diversity, Modular Machinery, More Chickens, Nature's Compass, Nutrition, OpenBlocks, OpenModsLib, OpenModsLib Core, OreExcavation, Pam's HarvestCraft, Patchouli, Pickle Tweaks, Placebo, Plants, PlusTiC, PortalGun, ProjectE, Quark, RFTools, Random Things, RandomPatches, RandomTweaks, Reborn Core, Redstone Arsenal, Redstone Flux, Reliquary, Resizing Potion, Roost, Rough Mobs 2, Rough Tweaks, Rustic, Rustic Thaumaturgy, Scannable, Scavenge, Shadowfacts' Forgelin, Shadows of Greg, Simple Teleporters, Simple Trophies, SonarCore, Soulus, SpongeForge, Squeezer Patch, Stats Keeper, Super Factory Manager, SwingThroughGrass, TOP Addons, TerraCore, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Energistics, Thaumic Periphery, The One Probe, The Spice of Life, The Weirding Gadget, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Thermal Logistics, Tinker Stages, Tinkers' Complement, Tinkers' Construct, TinkersExtras, TogetherForever, Tomb Many Graves, TombManyGraves2 API, TombManyPlugins Cosmetic Armor Reworked, Translocators, Traverse, Twerk-Sim 2K16, VillageTradingBan, Void Island Control, Vulpes library, Water Control Extreme, Water Strainer, Whoops, Wireless Crafting Terminal 2, Wizardry, Xtones, Zen Summoning, Zen Triggers, ZenStages, iChunUtil, p455w0rd's Library, primal_tech
> 

**Issue Description**
EMC Desyncs occaisionally - Project EX and ProjectE both use seperate tags in playerdata to store a players EMC but the value is synced between them both. The desync seems to fix itself on using portals to change dimensions but not on using commands (Nucleus)

I don't know if a log would help but if it would lmk

**Comment by krisjenner** [comment] 2019-04-08 09:40
https://github.com/FTBTeam/FTB-Interactions/issues/89

**Comment by JakobConner** [comment] 2019-04-08 21:51
The problem here is that data is stored in Capabilities, which are saved to the entity. AFAIK going through a portal creates a new Entity on the other side, which means new Capability data. Most mods (Including Project E) handles this by listening to the Forge Event PlayerChangedDimensionEvent and using that to copy the Capability data to the new Entity. Sponge has an event linked to this, a sub-event of MoveEntity. The problem is that many plugins, including Nucleus, don't actually fire this Sponge event when they set the players location across dimensions. That could probably be done on Sponge's end within the teleportation methods those plugins use, or it could be handled by each individual plugin.

**Comment by TechDweebGaming** [comment] 2019-04-08 21:52
The problem here is that data is stored in Capabilities, which are saved to the entity. AFAIK going through a portal creates a new Entity on the other side, which means new Capability data. Most mods (Including Project E) handles this by listening to the Forge Event PlayerChangedDimensionEvent and using that to copy the Capability data to the new Entity. Sponge has an event linked to this, a sub-event of MoveEntity. The problem is that many plugins, including Nucleus, don't actually fire this Sponge event when they set the players location across dimensions. That could probably be done on Sponge's end within the teleportation methods those plugins use, or it could be handled by each individual plugin.

**Comment by gabizou** [comment] 2019-04-12 17:05
> That could probably be done on Sponge's end within the teleportation methods those plugins use

Normally, Sponge should be throwing the event. I'll look into it or if @Zidane can confirm.

**Comment by phit** [comment] 2019-05-29 17:41
fixed in RC3724+ https://github.com/SpongePowered/SpongeForge/commit/fedd3a5d46e2291f0fd063ec9e2d37544be9cd98

**Closed by phit** 2019-05-29 17:41 UTC
Labels: status: accepted, system: event, type: bug, type: mod incompatibility
