### ISSUE TITLE
Bow & So Many Enchantments Mod

### ISSUE THREAD

**Issue by dregulae** [SpongePowered/SpongeForge#3002] opened 2019-10-09 12:43 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3924
- Forge version: 14.23.5.2838
- Java version: Java 8
- Operating System: Centos 7

- Plugins/Mods: So Many Enchantments

**Issue Description**

When using the bow with the custom enchantment "Advanced Power" from "So Many Enchantments" the bow / arrow entity does not take the custom enchantment into account for damage causing it to be a regular bow.

**Comment by JBYoshi** [comment] 2019-10-18 03:24
Can reproduce on SpongeForge RC3928. For reference, So Many Enchantments uses `EntityArrow.setDamage()` to change the power of the arrow.

**Comment by JBYoshi** [comment] 2019-10-18 03:53
I've found the root cause. In `EntityLivingBase.stopActiveHand`, Minecraft calls `ItemStack.onPlayerStoppedUsing()` (which fires the arrow), and then calls `resetActiveHand()` to clear the item being used. Sponge delays Forge's `EntityJoinWorldEvent` until after `resetActiveHand()`, so the player is no longer marked as using a bow, and So Many Enchantments doesn't say the bow caused the action. I'll fix this by overwriting the value during `InteractionPacketState.unwind()`.

**Closed as completed** 2019-10-18 03:56 UTC
Labels: status: accepted, type: mod incompatibility, version: 1.12, system: entity
