### ISSUE TITLE
Crash with NuclearCraft's alloy furnace on placement (server crash)

### ISSUE THREAD

**Issue by Rongmario** [SpongePowered/SpongeForge#1457] opened 2017-04-22 20:23 UTC
https://hastebin.com/tuteximixa.sql

Happens at the event of placing alloy furnace from NuclearCraft.

- spongeforge-1.10.2-2281-5.2.0-BETA-2274
- Forge = same as the build sponge was built on
- Java 8
- OS: Windows

- Plugins/Mods: (Above pastelog)

- Expected Result = Not to crash?
- Current Result = Crash?

**Comment by loveyanbei** [comment] 2017-05-05 06:15
+1
StackOverflowError with sponge
No problem with raw forge

**Comment by gabizou** [comment] 2017-05-08 21:06
We can't really "fix" this issue as it's an issue with NuclearCraft calling recursive methods by overriding `getTileData()`, which is commented out on NuclearCraft's 1.10.2 branch as marked [here](https://github.com/turbodiesel4598/NuclearCraft/blob/1.10.2/src/main/java/nc/tile/NCTile.java#L56). The issue is that Sponge cannot avoid this as we need to be able to retrieve the internal NBTTagCompound during writes to synchronize the custom data. 

The work around would involve a newer release of NuclearCraft being updated for 1.10.2 as they know this issue is resolved by commenting out the method entirely.

**Closed as completed by gabizou** 2017-05-08 21:06 UTC

**Comment by Rongmario** [comment] 2017-05-09 13:41
Bit late... He's already fixed it, jesus this speed.

**Comment by simon816** [comment] 2017-05-10 16:46
Forgot to mention it here, but just FYI I wrote an explanation of the problem on this forum post: https://forums.spongepowered.org/t/crash-on-wither-spawn/18603/4?u=simon816
