### ISSUE TITLE
Compressed Block duping (Again)

### ISSUE THREAD

**Issue by bookerthegeek** [SpongePowered/SpongeForge#1193] opened 2017-01-15 04:30 UTC
As per previous issues ([#1045](https://github.com/SpongePowered/SpongeForge/issues/1045), [1155](https://github.com/SpongePowered/SpongeForge/issues/1155) & others) Breaking compressed blocks yields to many items.

### Issue Description:
When breaking Compressed blocks from [Extra Utilities ](https://github.com/rwtema/extrautilities) or [ExNihilo Adscensio](https://github.com/MikeLydeamore/ExNihiloAdscensio/wiki) with a hammer from Ex Nihilo Adscensio or a compressed hammer from [Ex Compressum](https://github.com/blay09/ExCompressum) you will receive multiple of the broken blocks. 

### Background:
Compressed blocks are made by filling in all 9 spots of a vanilla crafting table to form a compressed version of the block. 

### What happens:
Breaking Compressed blocks yields more drops then expected. 
![Chest with results](http://i.imgur.com/LWFNO4D.png)
Top Row:

| Double Compressed| Dirt | Sand | Gravel | Netherrack | Cobblestone |
| --- | --- | --- | --- | --- | --- |
| Hammer | Dirt | Sand | Gravel | Netherrack | Cobblestone |

Bottom Row:

| Compressed| Sand | Cobblestone | Gravel | Netherrack | Dirt |
| --- | --- | --- | --- | --- | --- |
| Hammer | Sand | Cobblestone | Gravel | Netherrack | Dirt |
| Compressed Hammer | Dust | Gravel | Sand | Netherrack | Destroyed Drops |

### What I expected to happen:
For the Double compressed blocks to only one of themself instead of 16.
For the Single compressed blocks to drop only 9 of the corresponding drops instead of 16 or 36

### Steps to reproduce:
1. Place any compressed or double compressed block listed above in the world.
2. Break with either a compressed or double compressed hammer.
3. Does not have to be a player wielding the hammer, automatic options also work.

---
### Affected Versions:
- ExCompressum_1.10.2-2.0.68
- exnihiloadscensio-1.10.2-0.1.11
- extrautils2-1.10.2-1.1.3d
- spongeforge-1.10.2-2202-5.1.0-BETA-2034

### Testing Walk through:

- Reported privately on our [SF3](https://mods.curse.com/modpacks/minecraft/256183-ftb-presents-skyfactory-3) server.
- Confirmed on SF3 Server
- Could not reproduce SF3 SSP
- Could not reproduce SSP without SpongeForge
- Reproducible with only SpongeForge and above listed mods in SSP
- jei_1.10.2-3.14.2.401 was used to make testing easier, reproducible without it installed.

**Comment by Keaton1188** [comment] 2017-02-07 00:08
@Aaron1011 Hey man, you had any luck with knowing what the issue is?

**Comment by Brend-Smits** [comment] 2017-02-07 20:37
Can confirm this is still an issue on latest build

**Comment by Aaron1011** [comment] 2017-02-07 20:45
@Keaton1188: Sorry - I forgot to update the issue with what I discovered.

The problem stems from the fact the extrautils2 calls `setBlockState` in its `getHardness` method. This causes Sponge to track multiple updates for a single mine. 

Fixing this will require modifying how we process captured block drops. I should have a fix for this later today.

**Comment by Brend-Smits** [comment] 2017-02-07 20:51
@Aaron1011 awesome news! Can't wait for this :)

**Comment by Keaton1188** [comment] 2017-02-07 21:23
@Aaron1011 Thx for the update :)

**Comment by Keaton1188** [comment] 2017-02-07 21:27
I know its not related to this issue but we are still after 1 month having massive lag from the sponge mobSpawn issue.

We have had to have natural mob spawning turned off from when the server first opened. This is because the massive lag it causes when enabled (Shows us in sponge timings report) still lags hard even with natural spawning turned off.

Sponge timings report - https://timings.aikar.co/?id=2a9c7e576504474281849767812fde2b&section=all

Other things were high but that was someones base which has now been sorted, just the mobSpawn stays high.

**Comment by Deamon5550** [comment] 2017-02-07 21:53
@Keaton1188 you should open a new issue for that one.

**Comment by Brend-Smits** [comment] 2017-02-07 21:55
As far as I know there already are issues on that,  #1158 for example, I hope it's still being worked on.

**Comment by Keaton1188** [comment] 2017-02-07 21:58
Hope that it is as well :/

**Comment by Slind14** [comment] 2017-02-11 22:18
@Aaron1011 just wondering, is this still on your radar?

**Comment by Time6628** [comment] 2017-02-11 22:56
He said he's working on it. When it's fixed, it's fixed.

**Comment by phit** [comment] 2017-02-11 23:02
He also said this 4 days ago, so it's natural to ask again since it didn't happen, and/or didn't update here why it didn't.
> I should have a fix for this later today.

**Comment by Keaton1188** [comment] 2017-02-17 16:17
@Aaron1011 Hey man, hows that fix going? :)

**Comment by Aaron1011** [comment] 2017-02-20 01:15
Sorry for all of the delays in getting this fixed - it's completely my fault.

The issue should be resolved in the latest SpongeForge. Thanks for your extremely details issue report @bookerthegeek  - it was a huge help!

**Closed as completed by Aaron1011** 2017-02-20 01:15 UTC
Labels: type: bug, system: event, version: 1.10 (u)
