### ISSUE TITLE
[1.11.2] GalactiCraft rocket dupe

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1591] opened 2017-06-16 22:39 UTC
When placing a GalactiCraft's rocket in the launch pad, the itemstack will not be consumed: the rocket will be placed and will not be removed from your inventory. This allows infinite rocket duplication.

**I am currently running...**
    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-a15cc3e
    SpongeForge: 1.11.2-2315-6.1.0-BETA-2381
    Minecraft Forge: 13.20.0.2298
- Java version: Java 8 update 121
- Operating System: Alpine (Linux)

- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, IvToolkit, Micdoodle8 Core, OpenComput
ers (Core), SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, animalium, Quark, Animania, Psi, AutoRegLib, Baubles, BetterChunkLoader, Biomes O' Plenty, 
Botania, Chameleon, CodeChicken Lib, CraftTweaker JEI Support, Just Enough Items, Crafttweaker, Embers, EnderStorage, ShetiPhian-Core, EnderTanks, Ender Zoo
,  FastAsyncWorldEdit, WorldEdit, FoamFix, IndustrialCraft 2, Forestry, Galacticraft Core, Galacticraft Planets, Gravestone Mod, GriefPrevention, The One Pr
obe, Immersive Engineering, Immersive Petroleum, Inventory Tweaks, JourneyMap, Just a Few Fish, Kai's Commons, LuckPerms, MagiChat, Nucleus, OpenComputers, 
Pam's HarvestCraft, Personal Cars, Platforms, Player Glow, Reborn Core, reborncore-MCMultiPart, Recurrent Complex, Refined Storage, Roots 2, SignEditor, Sim
pleAntiAFK, Steve's Carts 2, Storage Drawers, TabManager, Wolf Armor and Storage

**What is the expected result?**
The rocket be placed and the itemstack consumed.

**What is the current result?**
The itemstack is not consumed when placing the rocket, duplicating it.

Server log (no errors, i don't think it's needed, but...): https://gist.github.com/Eufranio/b57b2be76082549e122fc01593572153

**Comment by hugeblank** [comment] 2017-08-21 04:08
_INSERT HEAVY BUMPAGE_

I am having this issue too, and have spoken with the developer of galacticraft. This is a really annoying issue, and there is literally nothing that can be done to fix it. As a server operator trying to set up a galacticraft server this issue has become the bane of my existence. 
Here is my mod list, forge, and sponge version: https://kaos-network.com/servers/sonarx

**Comment by stephan-gh** [comment] 2017-08-21 13:18
Does this affect all rocket types? I can reproduce it with the `Tier 1 Rocket` but tier 2 and tier 3 work fine.

**Comment by radfast** [comment] 2017-08-21 17:21
Hi, I'm one of the Galacticraft devs.  I think this may be simply one manifestation of the CauseTracker related issues, [already reported](https://github.com/SpongePowered/SpongeForge/issues/1552)

**Comment by stephan-gh** [comment] 2017-08-21 17:36
@radfast See https://github.com/SpongePowered/SpongeForge/issues/1552#issuecomment-323805757, I can't reproduce this using the latest SpongeForge 1.11.2 (and latest Galacticraft).

I'm pretty sure the dupe problem mentioned in this issue is fixed by https://github.com/micdoodle8/Galacticraft/pull/2955

**Comment by radfast** [comment] 2017-08-21 19:34
Nice one, thank you for identifying the issue in our mod and making a PR, thank you for taking the time when the issue was our side.  I'll respond separately on the 1552 issue after more testing.

**Comment by stephan-gh** [comment] 2017-08-22 06:22
I believe this should be fixed once the new Galacticraft build is out. @hugeblank / @Eufranio Comment here if this is still a problem.

**Closed as completed by stephan-gh** 2017-08-22 06:22 UTC
Labels: type: mod incompatibility, resolution: fixed externally, type: mod bug
