### ISSUE TITLE
Villager Death Crashes Server

### ISSUE THREAD

**Issue by Aiidoneus** [SpongePowered/SpongeForge#1467] opened 2017-04-26 05:49 UTC
Not sure if this is the place to go for this but hopefully you guys/gals can point me in the right direction. 

Currently running 
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2274
- Forge version: forge-1.10.2-12.18.3.2281-universal

- Plugins/Mods: 
https://pastebin.com/XQn1b7TJ
This is FTB Beyond modpack

Crash Report: https://pastebin.com/6gK2vJD0

All you need to do to reproduce this is to put villagers in a tinker's construct smeltery. I will supply more information if needed to help solve this issue. If you need the full server log I can provide that. I think this will be enough though. 
-Aiden

**Comment by Richetoku** [comment] 2017-04-26 08:38
I have this same issue and I have found it is modded villagers. Specifically, it happens with some actually additions villagers. Have not tried others, but I tested it with some shady merchant and the server crashes when they take damage with the crash error linked above. If it helps, I can check if any other villagers from other mods do the same.

**Comment by gabizou** [comment] 2017-05-15 17:09
I'm going to put a lot of debugging code into villagers which will provide more information as to what is going on and why. It feels like after all the careful validation I have put into villagers to find the right career and registering them after finding the profession was not registered, it feels like some careers aren't being registered at all, only professions. Will have something out later today or sometime this week to allow further debugging the issue.

**Comment by phit** [comment] 2017-07-20 00:05
So I tested this in 1.12 and couldn't get the game to crash, I though oh well possibly due to the registry rewrite, no idea. Anyways, so I went to 1.11.2 figuring I can easily get it to crash there, sadly no such luck. I even added Actually Additions hoping its villager would trigger it, but nope.

So the last hope 1.10.2, I rebuild the same setup I had used on the other versions and finally, nothing... I used latest available for all versions I've tested with, so maybe Tinkers Construct has fixed their shit.

@Richetoku @Aiidoneus @wolfhound871 have you recently seen this crash happen? Maybe I was just missing something when testing.

![villagerfun](http://i.imgur.com/GnM4I6W.png)

**Comment by Zidane** [comment] 2017-07-20 00:06
Closing unless we get a response with better details on reproduction or issue fixed.

**Comment by wolfhound871** [comment] 2017-07-22 15:51
this stopped for me after a sponge update and never happened again but i also updated the game version also several versions at the same time so one way or another the issue has disappeared for me and richi as he was an old dev of mine at the time he posted that comment that i was un aware of

**Comment by yepidoodles** [comment] 2017-09-03 11:57
I believe I am getting this or a similar crash.

https://pastebin.com/SqUcR9iF

I'm using SpongeForge version 2281-5.2.0-BETA-2597

I tried asking my players if they did anything to do with villagers before the crashes, but didn't get a conclusive answer, If I find out, I'll let you know.

**Comment by Aaron1011** [comment] 2017-09-03 14:22
@yepidoodles: I've made the exception more informative in the next Sponge build. The next time the crash occurs, can you post the updated stacktrace?

**Comment by yepidoodles** [comment] 2017-09-09 09:56
Took a while (Always crashes when you don't want it to, doesn't crash when you do, haha)

I think it's the same crash
https://pastebin.com/Va9ajYeW

**Comment by phit** [comment] 2018-01-01 16:01
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, let me know and I will reopen this issue.

**Closed as completed by phit** 2018-01-01 16:01 UTC
Labels: type: bug, status: accepted, version: 1.10 (u), version: 1.11 (u)
