### ISSUE TITLE
General Performance 2

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2573] opened 2019-01-24 06:09 UTC
Any chance few of the sponge devs can take a look at this snapshot and check if anything can be improved?
The server is running with 9 TPS with only 14-18 players online. I'm also wondering why 1.10 and 1.12 is running so much worse then 1.7.10 does. 

[enigmatica2expert.zip](https://github.com/SpongePowered/SpongeForge/files/2790391/enigmatica2expert.zip)

(spongeforge-1.12.2-2768-7.1.5-RC3521)

**Comment by Shybella** [comment] 2019-01-24 16:09
16% loaded here with just these tick entities http://prntscr.com/mbmtjx

My suggestion would be to overlook how tile activation works with Sponge and begin slowing down these expensive ticking items. Be careful with tile activation, avoid things that go cross multiple chunks and or do some form of chunk loading and unloading.

What hardware are you using?

**Comment by gabizou** [comment] 2019-01-24 20:30
Also to mention, looking further into one of the top offenders would be anything where tile entities are constantly checking against registries for recipes of sorts or checking "is something" without caching those results like so:

![screen shot 2019-01-24 at 12 29 22 pm](https://user-images.githubusercontent.com/1203877/51706602-d2ff0680-1fd3-11e9-9133-c9f05dae5f73.png)

**Comment by SawFowl** [comment] 2019-01-25 03:19
For the most part, the performance issue is related to installed mods. However, talking about this to mod developers is usually useless. I already tried.
For partial overload protection, I installed the Tiquality mod. I also slowed the tiles through global.conf.
Also in global.conf I slowed down the entities and activated panda-redstone. 
On my server there are only entities from vanilla, I don’t know for what reason, but they consume quite a lot of CPU time. The problem is observed only with the load on the processor. I don’t have any problems with RAM.
Characteristics of my server:
KVM virtualization.
CPU 4 cores I7-6700k
8Gb Ram
30Gb NVeSSD

**Comment by Sir-Will** [comment] 2019-01-25 06:39
Changing the tick time of tiles doesn't really help as plays will just place more to compensate that.
Most 1.12 mods are the same in 1.7 so I don't think that all the tiles got slower and worse in performance.

@gabizou I already reported that one to the mod dev. He is going to cache that soon.

In 1.7 you would only notice performance issues once one single tile entity would jump to 12-18%

**Comment by gabizou** [comment] 2019-01-25 11:32
@Sir-Will, what did I report to whom?

**Comment by Sir-Will** [comment] 2019-01-25 19:38
@gabizou sorry, I did report that.

**Comment by SawFowl** [comment] 2019-01-26 10:29
Maybe there is an opportunity to make the processing of entities in a separate thread? This could increase performance.

**Comment by gabizou** [comment] 2019-01-29 04:57
@Mr-Krab you can't multithread entity, tile entity, and block updates.

**Comment by liach** [comment] 2019-01-29 20:59
The best vanilla can be patched to is to handle each dimension/world in its own thread, though I don't know if they visit or modify minecraft server frequent enough to stall performance. By the way, what is that nc mod?

**Comment by Sir-Will** [comment] 2019-01-29 22:34
nc is NuclearCraft

**Comment by Shybella** [comment] 2019-01-29 22:36
1.14/1.15 is looking pretty neat. Performance may see some improvements when that rolls out.

**Comment by Sir-Will** [comment] 2019-01-29 22:39
Not going to change a lot, NC is not the main issue.

**Comment by Sir-Will** [comment] 2019-01-30 04:05
What probably would help a lot is if the gatherCapabilities of ItemStack inits can be improved.

**Comment by gabizou** [comment] 2019-01-30 10:03
Going to close this as there's not much here that points to sponge having to do a lot of underperforming code.

**Closed as completed by gabizou** 2019-01-30 10:03 UTC
Labels: type: support, type: performance, version: 1.12
