### ISSUE TITLE
Applied Energistics 2 spatial IO not working

### ISSUE THREAD

**Issue by FlandreCirno** [SpongePowered/SpongeForge#2384] opened 2018-08-16 13:46 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3361
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: build 1.8.0_181-b13
- Operating System: Windows 10 Home

- Plugins/Mods:
Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge

Mods (9): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Energistics 2, UniDict, WanionLib

**Issue Description**
I'm currently running a test server to figure things out. Applied Energistics 2 spatial IO doesn't work with Sponge and forge server, but works with only forge server. Spatial IO is supposed to teleport blocks and entities in an area inside spatial pylon to the storage dimension. upon activation. In Sponge server, it throws an Exception as posted below(only switch debug logging on in AE2 configs). And no blocks or entities are teleported. I'm not sure if these information is helpful. I traced the source code of AE2 and I think that the most possible reason for this exception is that AE2 could not get the spatial storage capabilities(forge api) of the storage world. AE2 registers the functions of creating and maintaining a storage cell inside the capabilities of the storage world with dimension id 2. I stopped at this step and posted this issue because forge and sponge are too complex for me to look through.

Exception:
https://gist.github.com/FlandreCirno/fc57dc27bbeb9df56feae9e14905b791
Full log:
https://gist.github.com/FlandreCirno/73732703f643910c3a82735e91cc69ab

**Comment by wysohn** [comment] 2018-08-19 21:42
Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-dbe3cb0
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3358
    Minecraft Forge: 14.23.4.2705

---

Could not find the log, but one of the user in my server also reported that Spatial IO doesn't work in server yet works in single player

**Comment by phit** [comment] 2018-09-14 01:23
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/bbf4d4a9ce36cee0d0e467972ea05c365299baba/src/main/java/appeng/items/storage/ItemSpatialStorageCell.java#L144

line of crash

**Comment by sowelipililimute** [comment] 2018-10-04 20:42
I also have this issue; running on the same versions as Wysohn.
Operating System: openSUSE Tumbleweed (Linux)
Mods: Sponge & AE2

**Comment by Terenx** [comment] 2018-12-11 03:09
I'm having this same problem, I'm playing on Jurassic Evolution server by Kinetic Networks and I built a 16x16x16 spatial storage area, and even with enough power to make it work at 25% efficiency, I have it at 100% and it doesn't want to work

**Comment by takarabako** [comment] 2018-12-11 14:05
The real cause of this problem is
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/core/Registration.java#L338

DimensionManager.getWorld( AEConfig.instance().getStorageDimensionID() ) returns null for the storage cell dimension while under native Forge it returns the same world object as event.getObject(), thus preventing the SpatialDimensionManager instance from being attached.

Forge [adds the dimention to its DimensionManager durning creation of the WorldServer object by calling the setWorld method](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/world/WorldServer.java.patch#L28) before calling WorldServer.init()(which calls World.initCapabilities() and triggers the event), allowing AE2 to get back the world using getWorld method. However, this setWorld call is [removed by sponge](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/world/MixinWorldServer.java#L75).

For anyone wants to mess with the code, [here](https://gist.github.com/takarabako/efdde27e0e289d0c73de3d4caf6c2c7f) is a "temp fix" for this issue.

**Comment by ryantheleach** [comment] 2018-12-11 14:18
That comment implies it's supposed to be handled elsewhere, @takarabako do you know if Sponge runs that setWorld call anywhere else?

Maybe the timing is off, and we are delaying it after that event is being thrown, or it's never set at all.

**Comment by takarabako** [comment] 2018-12-11 14:47
> That comment implies it's supposed to be handled elsewhere, @takarabako do you know if Sponge runs that setWorld call anywhere else?
> 
> Maybe the timing is off, and we are delaying it after that event is being thrown, or it's never set at all.

setWorld is not called at all and it's intentional because it IS handled elsewhere, the problem is when the world made its way to the world list which then can be get back by getWorld, happened way too late. AE2 already gave up at that point.

**Comment by phit** [comment] 2019-05-16 21:50
last I tested this the spatial io simply didn't do anything, there weren't any exceptions though
tested with sf 3616

**Comment by Zidane** [comment] 2019-06-11 19:13
This was fixed by me without even remembering this ticket as I say that right after creating the WorldServer, I did not chuck it into the WorldManager's maps. Apologies for the break. Grab the latest SF and should be good now.

**Closed as completed by Zidane** 2019-06-11 19:13 UTC
Labels: type: mod incompatibility, version: 1.12
