### ISSUE TITLE
SpongeForge crashes server when using /home from another dim

### ISSUE THREAD

**Issue by Magesw** [SpongePowered/SpongeForge#2489] opened 2018-10-26 08:21 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.2
- Forge version: FTBserver-1.12.2-14.23.5.2770-universal
- Java version: 1.8.181
- Operating System: Windows Server 2016

- Plugins/Mods:

Mods: FTB Sky Factory Mod pack v1.1.0 w/SpongeForge added and FoamFix removed.
https://www.feed-the-beast.com/projects/ftb-sky-adventures/files/2629159

Plugins: BuycraftX

**Issue Description**

When a player uses /home or /spawn from any other dim other then over world it crashes the server.

Crash log: https://gist.github.com/Magesw/da91fc9e00415332cf973c975e2cd62a

**Comment by phit** [comment] 2018-10-26 15:45
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2266

**Closed as completed by phit** 2018-10-26 15:45 UTC
Labels: resolution: duplicate, version: 1.12
