### ISSUE TITLE
Sponge conflict with animania

### ISSUE THREAD

**Issue by AiMLESS2k** [SpongePowered/SpongeForge#3151] opened 2020-05-03 16:24 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.2.1
- Forge version: 14.23.5.2847
- Java version: 8
- Operating System: Debian 10 Linux

- Plugins/Mods:
Plugins (8): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, BanManager, LuckPerms, Nucleus, WorldEdit
Mods (276): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, A Lib, AE2 Wireless Terminals (AE2WTLib), Actually Additions, Actually Baubles, Akashic Tome, Alchemistry, Animania, AppleCore, AppleSkin, Applied Energistics 2, ArchitectureCraft, Aroma1997Core, AromaBackup, AromaBackuprecovery, Artisan Integrations, Artisan Worktables, Astral Sorcery, Athenaeum, AutoRegLib, Avaritia, B.A.S.E, BD Lib, BQ Forestry Expansion, Baubles, Better Builder's Wands, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bloodmoon, Bonsai Trees, Bookshelf, Botania, Botanic Additions, Brandon's Core, Ceramics, Chameleon, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, Clumps, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Drawers, ContentTweaker, CookieCore, Corail Tombstone, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cucumber Library, Custom Starting Gear, Cyclic, Cyclops Core, DDSS Utils, Dark Utilities, Doomlike Dungeons, Draconic Evolution, DungeonTactics, EnderStorage, Environmental Tech, EvilCraft, EvilCraft-Compat, Exchangers, Extended Crafting, Extra Alchemy, Extra Cells 2, Extra Planets, Extra Utilities 2, Extreme Reactors, FTB Library, FTB Utilities, Fast Leaf Decay, FastWorkbench, Fishing Net Mod, FluidTank, FluidTank_AE2, FluidTank_TheOneProbe, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, GenDustry, Gendustry JEI Addon, Guide-API, Guidebook, GunpowderLib, Hammer Core, HelpFixer, Hooked, Hunger Overhaul, Hunting Dimension, Ice and Fire, Immersive Engineering, Industrial Foregoing, Infernal Mobs, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Chest, Just Another Rotten Flesh to Leather Mod, Just Enough Calculation, Just Enough Energistics, Just Enough Items, LLibrary, LagGoggles, Lapis Stays in the Enchanting Table, LibEx, LibrarianLib, LibrarianLib Stage 2, LittleTiles, LittleTilesCore, Loot Bags, LootTweaker, MJRLegendsLib, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Mekanism: Tools, MekanismOres, Micdoodle8 Core, Minecraft Multipart Plugin, Minerva Library, Mob Properties Randomness, Mod Tweaker, Modular Machinery, More Libs, More Plates, Morpheus, Mowzie's Mobs, MrCrayfish's Furniture Mod, MrTJPCore, Multi Mob Core, Mystical Agradditions, Mystical Agriculture, Mystical Lib, Natura, Nature's Compass, NetherEx, NotEnoughIDs, NuclearCraft, OMLib, OnlinePictureFrame, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Overloaded, PackagedAuto, PackagedExCrafting, Pam's Cookables, Pam's HarvestCraft, Patchouli, Pickle Tweaks, Placebo, PlusTiC, PneumaticCraft: Repressurized, Primitive Mobs, Progressive Bosses, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Integration, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, Quark, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RandomPatches, Reborn Core, RebornStorage, Redstone Flux, Refined Avaritia, Refined Storage, Refined Storage Addons, Rex's Additional Structures, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roguelike Dungeons, Rough Mobs 2, Ruins Mod, Rustic, SG Craft, Shadowfacts' Forgelin, Simply Backpacks, Simply Jetpacks 2, Solar Flux Reborn, Special AI, Spice of Life: Carrot Edition, SpongeForge, Standard Expansion, Steve's Carts 2, Storage Cabinet, Storage Drawers, Storage Drawers Extras, Storage Tech, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickCentral, Tinkers Alloying Addon, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, Tweakers Construct, Tweakers Construct Post Load, U Team Core, Underground Biomes, UniDict, Universal Modifiers, Useful Railroads, Valkyrie Lib, VanillaFix, ViesCraft, Vulcanite, WanionLib, Wireless Crafting Terminal 2, Worley's Caves, XNet, Zero CORE, Zoesteria Biomes, careerbees, galacticrafttweaker, p455w0rd's Library, projectred-compat

**Issue Description**
I'm running animania on my server and everything was fine, the next day i tried to login my whole game was freeze. I looked at the error in the Console and saw the error was thrown by animania.
The error was thrown by the Pigs from the mod

https://gist.github.com/GermanY1337/b561c52691935b3386b2b87c699b38f8

**Comment by clienthax** [comment] 2020-05-03 17:15
https://github.com/capnkirok/animaniamod/issues/340

**Comment by clienthax** [comment] 2020-05-03 17:16
Issue is likely caused by animania, as have had similar things in the past.

**Comment by dualspiral** [comment] 2020-06-08 22:43
Does this work now? A cast from their TE to another of their TEs does basically say to me "they're not checking properly" - surely it's their problem? I can't see it being us breaking that at all.

Any more information, or are we going to just look at closing this?

**Comment by clienthax** [comment] 2020-06-09 09:24
> Does this work now? A cast from their TE to another of their TEs does basically say to me "they're not checking properly" - surely it's their problem? I can't see it being us breaking that at all.
> 
> Any more information, or are we going to just look at closing this?

It basically seems to be the bug i previously reported but with the cast being swapped.

**Comment by dualspiral** [comment] 2020-06-09 09:26
I'm just going to close this as a mod bug, if they can prove otherwise, we can reopen.

**Closed as completed by dualspiral** 2020-06-09 09:26 UTC
Labels: version: 1.12, type: mod bug
