### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by TheWildBananas** [SpongePowered/SpongeForge#2773] opened 2019-05-25 19:04 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.5 and 1.12.2-2825-7.1.6-RC3716(Tried all versions.)
- Forge version: forge-1.12.2-14.23.5.2831
- Java version: (build 1.8.0_161-b12)
- Operating System: CentOS 7

- Plugins/Mods:

TelePastries
by Mrbysco
  
Chargers
by GoryMoon
  
Together Forever
by Buuz135
 
AromaBackup
by Aroma1997
  
Click Machine
by Shadows_of_Fire
  
Flux Networks
by sonar_sonic
 
Real Filing Cabinet
by BlueNeenja
  
Integrated Tunnels
by kroeser
  
Snad
by TheRoBrit
 
Client Tweaks
by BlayTheNinth
  
Surge
by DarkhaxDev
  
Mystcraft
by XCompWiz
 
Mantle
by mDiyo
  
Apotheosis
by Shadows_of_Fire
  
Portal Gun
by ohaiiChun
 
Sync
by ohaiiChun
  
Primitive Crafting
by Tschipp
  
Tinkers' Complement
by KnightMiner
 
More Cauldrons
by Mrbysco
  
B.A.S.E
by lanse505
  
Ignition: HydroGel
by Shadows_of_Fire
 
MPUtils Basic Tools
by GenDeathrow
  
Common Capabilities
by kroeser
  
Horse Power
by GoryMoon
 
CraftTweaker
by Jaredlll08
  
BiblioCraft
by Nuchaz
  
World Book
by Jaredlll08
 
FastFurnace
by Shadows_of_Fire
  
Recipe Stages
by Jaredlll08
  
Controlling
by Jaredlll08
 
Parabox
by Shadows_of_Fire
  
TallGates
by GoryMoon
  
Wawla - What Are We Looking At
by DarkhaxDev
 
Yoyos
by jozufozu
  
Pipe Master 2000
by davenonymous
  
Thermal Innovation
by TeamCoFH
 
Dimension Stages
by DarkhaxDev
  
Corail Tombstone
by Corail_31
  
Enchantment Descriptions
by DarkhaxDev
 
Mob Stages
by DarkhaxDev
  
ExtraCells2
by Destroyer7128
  
Cyclic
by Lothrazar
 
PigUtils
by DarkhaxDev
  
Waila Stages
by DarkhaxDev
  
ContentTweaker
by Jaredlll08
 
Slab Machines
by Mrbysco
  
Cooking for Blockheads
by BlayTheNinth
  
Simple Generators
by ValkyrieofNight
 
Inspirations
by KnightMiner
  
Just Enough Items (JEI)
by mezz
  
CompactStorage
by tobyystrong
 
Extended Crafting
by BlakeBr0
  
Toast Control
by Shadows_of_Fire
  
Prestige
by Jaredlll08
 
MPUtils
by GenDeathrow
  
Baubles
by Azanor13
  
Aroma1997Core
by Aroma1997
 
Rustic
by mangoose3039
  
Tinkers Construct
by mDiyo
  
XL Food Mod
by mariot7
 
FoamFix for Minecraft
by asiekierka
  
Bed Patch
by Mordenkainen3141
  
ZenStages
by artdude543
 
Sonar Core
by sonar_sonic
  
Bouncy Creepers
by vadis365
  
MCMultiPart
by amadornes
 
Applied Energistics 2
by AlgorithmX2
  
Forge MultiPart CBE
by covers1624
  
FindMe
by Buuz135
 
Ceramics
by KnightMiner
  
Simple Storage Network
by Lothrazar
  
Cyclops Core
by kroeser
 
CodeChicken Lib 1.8.+
by covers1624
  
Wall-Jump!
by genandnic
  
Waddles
by Girafi
 
In Control!
by McJty
  
Mercurius
by TamasHenning
  
Astral Sorcery
by HellFirePvP
 
Neat
by Vazkii_
  
Mystical Agradditions
by BlakeBr0
  
Redstone Flux
by TeamCoFH
 
Inventory Sorter
by cpw
  
Shadowfacts' Forgelin
by ShadowfactsDev
  
Mekanism
by bradyaidanc
 
Fence Overhaul
by TheWeatherPony
  
Mekanism Generators
by bradyaidanc
  
MalisisDoors
by Ordinastie
 
MalisisCore
by Ordinastie
  
WitherCrumbs
by Turkey2349
  
SlimyBoyos
by Jaredlll08
 
Deep Mob Learning
by IterationFunk
  
Sky Orchards
by vadis365
  
More Buckets
by BlakeBr0
 
Farming for Blockheads
by BlayTheNinth
  
OC XNet Driver
by davenonymous
  
Super Sound Muffler
by EdgarAllen
 
Ender Storage 1.8.+
by covers1624
  
Practical Logistics 2
by sonar_sonic
  
Headcrumbs
by ganymedes01
 
Game Stages
by DarkhaxDev
  
OGDragon +
by GenDeathrow
  
Carry On
by Tschipp
 
Thermal Foundation
by TeamCoFH
  
BNBGamingLib
by bloodnbonesgaming
  
Sky Grid
by Funwayguy
 
Construct's Armory
by TheIllusiveC4
  
Integrated Dynamics
by kroeser
  
NuclearCraft
by tomdodd4598
 
KleeSlabs
by BlayTheNinth
  
OpenBlocks Elevator
by vsngarcia
  
Hunting Dimension
by DarkhaxDev
 
ConnectedTexturesMod
by tterrag1098
  
Ranged Pumps
by raoulvdberge
  
Tiny Progressions
by Kashdeya
 
EnderCore
by tterrag1098
  
XNet
by McJty
  
Animal Crops
by KnightMiner
 
Bookshelf
by DarkhaxDev
  
Industrial Foregoing
by Buuz135
  
Culinary Construct
by TheIllusiveC4
 
BnBGamingCore
by bloodnbonesgaming
  
Mob Grinding Utils
by vadis365
  
Ore Excavation
by Funwayguy
 
Thermal Dynamics
by TeamCoFH
  
Forgiving Void
by BlayTheNinth
  
FastWorkbench
by Shadows_of_Fire
 
TorchMaster
by xalcon
  
Chisel
by tterrag1098
  
ChineseWorkshop
by cityofskytcd
 
OpenComputers
by Sangar_
  
Statues
by svennieke
  
World Utils
by masady
 
SwingThroughGrass
by exidex
  
Tinkers' Tool Leveling
by bonusboni
  
Topography
by bloodnbonesgaming
 
Stuff A Sock In It
by DarkhaxDev
  
MTLib
by Jaredlll08
  
McJtyLib
by McJty
 
Custom Main Menu
by Lumien231
  
ProjectE
by SinKillerJ
  
Iron Jetpacks
by BlakeBr0
 
Sky Bonsais
by davenonymous
  
AppleSkin
by squeek502
  
Resource Loader
by Lumien231
 
XCPatch
by Shadows_of_Fire
  
Compact Machines
by davenonymous
  
TipTheScales
by Jaredlll08
 
Translocators 1.8.+
by covers1624
  
Pickle Tweaks
by BlakeBr0
  
Proportional Destruction Particles
by Phylogeny
 
Coloured Tooltips
by DarkhaxDev
  
ValkyrieLib
by ValkyrieofNight
  
Bonsai Trees
by davenonymous
 
Resource Hogs
by DarkhaxDev
  
Fancy Block Particles
by TominoCZ
  
The Weirding Gadget
by AtomicBlom
 
Mouse Tweaks
by YaLTeR
  
The Twilight Forest
by Benimatic
  
ReAuth
by TechnicianLP
 
Mystical Agriculture
by BlakeBr0
  
Cucumber Library
by BlakeBr0
  
ModTweaker
by Jaredlll08
 
RFTools Power
by McJty
  
Uppers
by vadis365
  
Smooth Font
by bre2el
 
Default Options
by BlayTheNinth
  
Hurt Animation Remover
by bloodnbonesgaming
  
Loading Screens
by bloodnbonesgaming
 
Ender Utilities
by masady
  
Limitless Structure Blocks
by bloodnbonesgaming
  
Triumph
by bloodnbonesgaming
 
Dark Utilities
by DarkhaxDev
  
Clumps
by Jaredlll08
  
The Lost Cities
by McJty
 
Guide-API
by DatNut
  
Caliper
by DarkhaxDev
  
Morpheus
by Quetzi
 
YNot
by asiekierka
  
Chisels & Bits
by AlgorithmX2
  
Ender Crop
by DrManganese
 
JourneyMap
by techbrew
  
Hwyla
by DatNut
  
Matter Overdrive: Legacy Edition
by HRZNStudio
 
Tree Growing Simulator
by tterrag1098
  
CoFH Core
by TeamCoFH
  
Calm Down Zombie Guy
by bloodnbonesgaming
 
Tesla Core Lib
by face_of_cat
  
Placebo
by Shadows_of_Fire
  
ViesCraft - Airships!
by Vies
 
ComPatchedStorage
by Shadows_of_Fire
  
Barrels, Drums, Storage & More
by Funwayguy
  
Building Gadgets
by Direwolf20
 
Item Stages
by DarkhaxDev
  
CoFH World
by TeamCoFH
  
AppleCore
by squeek502
 
Better Advancements
by way2muchnoise
  
More Overlays
by FeldiM245
  
Advancement Book
by ParkerMc01
 
Subheads (formerly Twitchcrumbs)
by BlayTheNinth

When starting version 4.0.5 of skyfactory 4, it crashes and freezes.
Crash log: https://gist.github.com/TheWildBananas/9f7152b232a88dc6819ab557d23cfc92
Log: https://gist.github.com/TheWildBananas/cebe128ace39f230e57cc59ad3e247c9

**Comment by ImMorpheus** [comment] 2019-05-25 19:14
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2534

**Closed as completed by ImMorpheus** 2019-05-25 19:14 UTC
Labels: resolution: duplicate, version: 1.12

**Comment by ImMorpheus** [comment] 2019-05-25 19:15
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in the `config/foamfix.cfg`
`B:optimizedBlockPos=false` (Sponge adds a similar performance patch)
`B:patchChunkSerialization=false` <https://github.com/asiekierka/FoamFix/issues/166>
