### ISSUE TITLE
PhaseState having an exception: EntityTickPhase

### ISSUE THREAD

**Issue by sfxworks** [SpongePowered/SpongeForge#2527] opened 2018-11-30 07:49 UTC
**I am currently running**

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-70763aa8
    Sponge: 1.12.2-7.1.4
    SpongeForge: 1.12.2-2768-7.1.4
    Minecraft Forge: 14.23.4.2705
Centos 7 x64 

- Plugins/Mods:

 Plugins (26): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AurionsVoteListener, BattleLog, CatClearLag, LangSwitch, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, NuVotifier, Nucleus, Plan, ProjectCore, ProjectPortals, ProjectWorlds, SleepVote, Total Economy, UniversalMinecraftAPI, Universe Guard 2, VillagerShops, Web-API, WorldEdit, spark

[02:48:09] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Mods (98): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Actually Additions, Advanced Solar Panels, Ambience, Applied Energistics 2, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Bad Mobs, Baubles, Brandon's Core, BuildCraft, BuildCraft Compat, BuildCraft Lib, CoFH Core, CoFH World, CodeChicken Lib, ComputerCraft, CustomNPCs, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Ex Compressum, Ex Nihilo Creatio, Extra Cells 2, Extra Planets, Extreme Reactors, Faction Mod, Galacticraft Core, Galacticraft Planets, ICBM-Classic, Immersive Engineering, IndustrialCraft 2, Inventory Tweaks, Iron Chest, It's the little things, JourneyMap, Just Enough Items, MJRLegendsLib, Malisis Advert, MalisisCore, MalisisDoors, Mantle, Mekanism, MekanismGenerators, MekanismTools, Micdoodle8 Core, NoMoreRecipeConflict, NuclearCraft, OMLib, Open Glider, Open Modular Turrets, OpenBlocks, OpenModsLib, OpenModsLib Core, PlusTiC, Quark, Random Things, RandomPatches, Reborn Core, Redstone Arsenal, Redstone Flux, SG Craft, Simply Jetpacks 2, Smooth Font Core, SpongeForge, Steve's Carts 2, TESLA, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, What Are We Looking At, Wireless Crafting Terminal 2, Zero CORE, p455w0rd's Library

**Issue Description**

We're getting this report in our logs every milisecond that is likely leading to our server's main thread hanging after a few hours before a SIGTERM to restart it. 

How to replicate:

```
mostafapg: we stuck a galacticraft boss inside a chaotic spawner and were dropping them on players
mostafapg: the evolved creeper boss
mostafapg: which launches TNT
```

```
/* The PhaseState having an exception: EntityTickPhase                                                                                  */
/* The PhaseContext:                                                                                                                    */
/*     - Owner: GCEntityPlayerMP['mostafa_pg_'/8561673, l='REDACTED]                                      */
/*     - Source: EntityProjectileTNT['Projectile TNT'/8587632, l='REDACTED]                              */
/*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                         */
/* org.spongepowered.asm.util.PrettyPrinter@51e705d6                                                                                    */
/****************************************************************************************************************************************/
/* StackTrace:                                                                                                                          */
/* java.lang.IllegalStateException: Owner for this phase context is already set!                                                        */
/*     org.spongepowered.common.event.tracking.PhaseContext.owner(PhaseContext.java:144)                                                */
/*     org.spongepowered.common.event.tracking.PhaseContext.applyNotifierIfAvailable(PhaseContext.java:369)                             */
/*     org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.appendContextPreExplosion(EntityTickPhaseState.java:264) */
/*     org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.appendContextPreExplosion(EntityTickPhaseState.java:63)  */
/*     org.spongepowered.common.event.tracking.phase.general.ExplosionContext.populateFromCurrentState(ExplosionContext.java:48)        */
/*     org.spongepowered.common.event.tracking.phase.general.ExplosionState.createPhaseContext(ExplosionState.java:58)                  */
/*     org.spongepowered.common.event.tracking.phase.general.ExplosionState.createPhaseContext(ExplosionState.java:47)                  */
/*     net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:3233)                                                              */
/*     micdoodle8.mods.galacticraft.planets.mars.entities.EntityProjectileTNT.func_70227_a(EntityProjectileTNT.java:58)                 */
/*     net.minecraft.entity.projectile.EntityFireball.redirect$onProjectileImpact$zhf000(EntityFireball.java:595)                       */
/*     net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)                                             */
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:157)                                           */
/*     net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zma000(WorldServer.java:2982)                                        */
/*     net.minecraft.world.World.func_72866_a(World.java:4154)                                                                          */
/*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)                                                               */
/*     net.minecraft.world.World.func_72870_g(World.java:1952)                                                                          */
/*     net.minecraft.world.World.func_72939_s(World.java:6602)                                                                          */
/*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2295)                                                              */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                                      */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)                                            */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                      */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                               */
/*     java.lang.Thread.run(Thread.java:748)                                                                                            */
/*  Phases Remaining:                                                                                                                   */
/*                                                                                                                                      */
/* Minecraft : 1.12.2                                                                                                                   */
/* SpongeAPI : 7.1.0-70763aa8                                                                                                           */
/* Sponge : 1.12.2-7.1.4                                                                                                                */
/* SpongeForge : 1.12.2-2768-7.1.4                                                                                                      */
/* Minecraft Forge : 14.23.4.2705                                                                                                       */
/****************************************************************************************************************************************/
```

**Comment by ImMorpheus** [comment] 2018-12-01 16:14
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2475

**Closed as completed by ImMorpheus** 2018-12-01 16:14 UTC
Labels: version: 1.12
