### ISSUE TITLE
Looting Issue

### ISSUE THREAD

**Issue by xUmbrax** [SpongePowered/SpongeForge#1550] opened 2017-05-29 22:19 UTC
Heyo!
So Cross posting this with some testing done for you. Ipsis/Woot#139. Seems we are having an issue with the looting enchantment. (Please forgive the lack of Java speak & concrete documentation)

[Woot](https://github.com/Ipsis/Woot): A mod adding a multiblock structure that will generate mob drops at the cost of RF.
It does this by spawning the mobs (In this case a slime) instantly killing the mob with either non-enchanted damage, or one of the three levels of the looking enchantment. The issue we are having is that Woot is not able to tell that it killed the mob with the looting enchantment (That is the effect, not sure of the cause)

Here are two output logs from Woot;:

- [Run wo/ SpongeForge](https://gist.github.com/bookerthegeek/773c30b70f9c11e91606c551405d553f)
- [Run w/ SpongeForge](https://gist.github.com/bookerthegeek/b4a958f5814867da5201c3d1b60e5414)

You will notice that the one without sponge, WOOT is able to determine that the mob was killed with Looting 3, yet on the exact same MultiBlock structure with sponge installed while it is still killing the mobs, it only is registering it as non-looting kills.

You can find the original issue [HERE](https://github.com/Ipsis/Woot/issues/139)

EDIT: Forgot Versions:

- spongeforge-1.10.2-2221-5.2.0-BETA-2226
- woot-1.10.2-1.2.5
- forge-12.18.3.2254

**Comment by phit** [comment] 2017-05-29 22:21
dupe of #1346

**Comment by bookerthegeek** [comment] 2017-05-30 02:32
You literally just coppies my issue into A new one. Thief.

**Closed as completed** 2017-05-30 04:40 UTC
Labels: resolution: duplicate
