### ISSUE TITLE
SpongeForge Not working with FTB Beyond

### ISSUE THREAD

**Issue by Schuldakt** [SpongePowered/SpongeForge#1854] opened 2017-11-15 00:18 UTC
I'm trying to implement sponge with my FTB server so i can use the voxels sniper plugin, whenever i add sponge to the mods folder it makes it so i can no longer user the ftb commands and the plugin doesn't work.
I am currently running

- SpongeForge version:  1.10.2-2477-5.2.0-BETA-2731
- Forge version: forge-1.10.2-12.18.3.2511-universal.jar
- Java version: 1.8.0_151
- Operating System: Windows 10

log: https://gist.github.com/AxioParadox/b9a2082aaa534665260433d267b5833e

**Comment by phit** [comment] 2017-11-15 00:24
I edited the Java version in your post, since you aren't on Java 9.. if you were the server wouldn't even start launching.

**Comment by Schuldakt** [comment] 2017-11-15 00:25
thank you, brain fart, java 8

**Comment by ryantheleach** [comment] 2017-11-15 05:23
> no longer user the ftb commands and the plugin doesn't work.

My suspicion is that the ftb commands have some form of permission that isn't granted to non op'd players under Sponge.

My advice would be to install luckperms (you will be wanting a perms manager anyway), and do `/lp verbose` to see all permission checks that are happening while attempting to run that command.

**Comment by ryantheleach** [comment] 2017-11-15 05:26
Possibly related: https://github.com/SpongePowered/SpongeForge/issues/1144

**Comment by Schuldakt** [comment] 2017-11-15 05:26
thanks for the response, but voxel sniper still doesn't even work when i'm op'd.

also i commented on that thread and was redirected to make this thread by phit.

**Comment by ryantheleach** [comment] 2017-11-15 06:27
Yes, the related ticket wasn't necessarily a reply to you. The goal of an issue tracker is to track the **issue** as well as forming relationships between issues, in order to aid investigation.

**Comment by phit** [comment] 2018-01-01 15:51
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:51 UTC
Labels: version: 1.10 (u)
