### ISSUE TITLE
java.lang.IncompatibleClassChangeError: vtable stub 	at org.spongepowered.mod.tracker.FluidTracker

### ISSUE THREAD

**Issue by Tylerun** [SpongePowered/SpongeForge#1733] opened 2017-08-17 21:35 UTC
Server crashes upon entering the game. 

**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2569
- Forge version: 12.18.3.2422
- Java version: Java 8
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

**What is the expected result?**
Blocks should tick with no problems. Problem between Enderio and Actually Additions caused by Sponge. Can not figure out why. 

**What is the current result?**
Server crashes upon loading the chunk with the enderio pipe and actually additions barrel adjacent to one another. 

[fml-server-2.zip](https://github.com/SpongePowered/SpongeForge/files/1232676/fml-server-2.zip)
http://prntscr.com/g9syyy

**Comment by phit** [comment] 2017-08-17 21:37
Duplicate of #1732

**Closed as completed** 2017-08-17 22:32 UTC
Labels: resolution: duplicate
