### ISSUE TITLE
Server Crash on startup because of updating objective display name (StackOverflowError)

### ISSUE THREAD

**Issue by PssbleTrngle** [SpongePowered/SpongeForge#2885] opened 2019-07-18 13:29 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7-RC3848
- Forge version: 1.12.2-14.23.5.2838
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods:
AutoRegLib
Bookshelf
CraftTweaker2
D3Core
gamestagebooks
GamesStages
ItemStages
ModTweaker
MTLib
Quark
reauth
RecipeStages
TOP
VanillaFix

**Issue Description**
I am developing a plugin which creates scoreboard objectives, but does not interfere with any scoreboard events.
As soon as I start the world and there are objectives, the server crashes on startup because it is caught in some kind of loop between minecraft and sponge

Crash Report: https://gist.github.com/PssbleTrngle/6b7bb78a5731dbacc40283844d65f13d
Server Log: https://gist.github.com/PssbleTrngle/5e19edde8bbd897c7f74b97e334fb799

**Comment by PssbleTrngle** [comment] 2019-07-18 13:30
It does start again after I delete the objectives in the scoreboard.dat file, but this is no solution since I need the scoreboards

**Comment by LXGaming** [comment] 2019-07-18 13:33
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2324

**Comment by PssbleTrngle** [comment] 2019-07-18 13:37
It does not work when creating a scoreboard per command either, or without my custom plugin.

And yes, it seems like I get about the same crash as the referenced issue

**Closed as completed** 2019-07-18 16:58 UTC
Labels: resolution: duplicate, version: 1.12
