### ISSUE TITLE
"Phase incompatibility detected! Attempting to switch to an invalid phase!" when closing an inventory during clicking on an item

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeForge#2116] opened 2018-04-22 19:05 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3051
- Forge version: 14.23.3.2655
- Java version: 1.8.0_161
- Operating System: Windows 10

- Plugins/Mods: Custom plugins and HuskyUI-v0.6.0PRE1

**Issue Description**

When closing an inventory when an item is being clicked, the error below occurs.  
From my testing this only happens on SF, not SV. All recent older versions I tested had the same issue too.

https://gist.github.com/BrainStone/f482d3eaff3964bec473818a1ada4d75

**Comment by ryantheleach** [comment] 2018-04-23 08:20
Probably a duplicate of: https://github.com/SpongePowered/SpongeCommon/issues/1865

PR in progress: https://github.com/SpongePowered/SpongeCommon/pull/1869

**Closed as completed** 2018-04-23 08:20 UTC
Labels: resolution: duplicate
