### ISSUE TITLE
IC2 explosions dupe

### ISSUE THREAD

**Issue by IteratorW** [SpongePowered/SpongeForge#2982] opened 2019-09-20 20:31 UTC
**I am currently running**

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-13da4949c
    Sponge: 1.12.2-7.1.7-SNAPSHOT
    SpongeForge: 1.12.2-2838-7.1.7-RC3924
    Minecraft Forge: 14.23.5.2838
    JVM: 1.8.0_201/64-bit (Oracle Corporation)
    OS: Linux (3.10.0-862.14.4.el7.x86_64/amd64)

- Plugins/Mods:
    IC2 ver: industrialcraft-2-2.8.109-ex112
    GP as a protection plugin (does not matter actually)

**Issue Description**
First: I know about #1383, but nobody seems to notice my answer, so I'm creating a new issue.

When an IC2 explosion occurs (Industrial TNT for example), the event is being cancelled and the blocks aren't getting destroyed. However, the stacks from these block appear on the ground, which can be used to dupe stuff easily.

**Comment by ImMorpheus** [comment] 2019-09-20 21:09
> First: I know about #1383, but nobody seems to notice my answer, so I'm creating a new issue.

No, that's bad. Don't do that.

Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1383

**Closed as completed by ImMorpheus** 2019-09-20 21:09 UTC
Labels: resolution: duplicate
