### ISSUE TITLE
Dedicated Server Stops(like crash)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1475] opened 2017-04-29 20:32 UTC
i think it is the error part:

` [Server thread/ERROR] [FML/]: A fatal exception occurred during the server starting event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Planets (galacticraftplanets)

Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.add(ImmutableCollection.java:339) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:652) ~[minecraft_server.1.11.2.jar:?]
	at org.spongepowered.common.command.MinecraftCommandWrapper.getNames(MinecraftCommandWrapper.java:248) ~[MinecraftCommandWrapper.class:1.11.2-2282-6.0.0-BETA-2290]
	at net.minecraft.command.ServerCommandManager.func_71560_a(SourceFile:1108) ~[bd.class:?]
	at net.minecraftforge.fml.common.event.FMLServerStartingEvent.registerServerCommand(FMLServerStartingEvent.java:59) ~[FMLServerStartingEvent.class:?]
	at micdoodle8.mods.galacticraft.planets.asteroids.AsteroidsModule.serverStarting(AsteroidsModule.java:256) ~[AsteroidsModule.class:?]
	at micdoodle8.mods.galacticraft.planets.PlanetsProxy.serverStarting(PlanetsProxy.java:48) ~[PlanetsProxy.class:?]
	at micdoodle8.mods.galacticraft.planets.GalacticraftPlanets.serverStarting(GalacticraftPlanets.java:124) ~[GalacticraftPlanets.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641) ~[forge-1.11.2-13.20.0.2282-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.11.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.11.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:553) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:878) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:294) [lh.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131] ` 

[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/966375/fml-server-latest.txt)

**Comment by ghost** [comment] 2017-04-29 20:33
btw, used forge 2282.

**Comment by ghost** [comment] 2017-04-29 20:38
aaaand, it gives crash report with 2285 (maybe anyone need to see, just tried)
[2285 sponge dedicated server crash.txt](https://github.com/SpongePowered/SpongeForge/files/966379/2285.sponge.dedicated.server.crash.txt)

**Comment by ghost** [comment] 2017-04-30 13:55
this is the real issue i'm waiting for help. (i did it for not to be misunderstood)

**Comment by yepidoodles** [comment] 2017-04-30 13:59
This is an issue with the mod in question: Galacticraft Planets.

**Comment by yepidoodles** [comment] 2017-04-30 14:01
Is it this mod?
https://minecraft.curseforge.com/projects/extraplanets

**Comment by ghost** [comment] 2017-04-30 14:03
yes, galacticraft is installed in my modpack.

**Comment by ghost** [comment] 2017-04-30 14:03
not extraplanets, here it is.
https://ci.micdoodle8.com/job/Galacticraft-1.11/

**Comment by ghost** [comment] 2017-04-30 14:07
and i just linked that amazing compatibility issue an hour ago

**Comment by yepidoodles** [comment] 2017-04-30 14:08
I don't know what is wrong, but I'm 95% sure it's nothing to do with SpongeForge

**Comment by ghost** [comment] 2017-04-30 14:09
hmm :/ hope it be fixed soon by anyway

**Comment by Deamon5550** [comment] 2017-04-30 20:03
Looks like this was fixed by galacticraft https://github.com/micdoodle8/Galacticraft/commit/acf93095105dc939c04f74773341be3d8892e416

**Closed as completed by Deamon5550** 2017-04-30 20:03 UTC

**Comment by radfast** [comment] 2017-05-03 13:09
Guys I'm sorry, I asked kenijey **not** to report this issue to Sponge!

I can't really control what our players do :(

The issue here was a command which had a ```null``` String as its name (not sure how, not intended but bugs do creep in between versions).  Standard Forge doesn't seem to mind about a null strong there, there is no error in standard Forge.  Sponge Forge does mind.  Sponge could add a null check, but obviously the issue is easily fixable by the Forge mod just providing a name for the command, and seems reasonable that every registered command should have a name!!!
