### ISSUE TITLE
XNET Controller - Fatal Error

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1950] opened 2018-01-11 21:56 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2831
- Forge version: 14.23.1.2582
- Java version: 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods:
Modern Skyblock 2/All 1.12 packs really.

**Issue Description**
When going to open the XNET controller it kicks you with a fatal error message, this does not happen on Single Player.

https://gist.github.com/Keaton1188/2523bce1d02ba56fed2c9c3ebc4a4fe7

**Comment by phit** [comment] 2018-01-11 22:06
Did you just duplicate your own issue? lol
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1869

**Closed as completed by phit** 2018-01-11 22:06 UTC
Labels: resolution: duplicate, version: 1.12

**Comment by Keaton1188** [comment] 2018-01-11 23:18
Silly me! I forget things, too much to remember! :)

My bad @phit
