### ISSUE TITLE
Usage of GetCollisionBoxesEvent  breaks Teleportation

### ISSUE THREAD

**Issue by Bucky420** [SpongePowered/SpongeForge#2355] opened 2018-08-01 10:07 UTC
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-7105dfc
SpongeForge: 1.12.2-2705-7.1.0-BETA-3361
Minecraft Forge: 14.23.4.2732

Nucleus version 1.4.6-S7.0 (built from commit cb28285)
going to the nether and using using /tp or /spawn i get
Unexpected error running this command: Intended to track block entity spawns! Please analyze the current phase context.

u then must relog to do any thing

the console has a huge error

https://gist.github.com/codydbgt/53c550162257e11a2467623d34c464a0

this does not happen on build 3350 of sponge

https://github.com/NucleusPowered/Nucleus/issues/1231

**Comment by ryantheleach** [comment] 2018-08-02 19:08
This seems to be a mod incompatibility issue with fairylights, something in our phase tracker might be being incorrectly triggered . 

Remapped Trace:
```
Stacktrace:                                                                                                                                        
 java.lang.IllegalStateException: Intended to track block entity spawns! Please analyze the current phase context.                                  
     org.spongepowered.common.event.tracking.TrackingUtil.lambda$throwWithContext$3(TrackingUtil.java:446)                                          
     org.spongepowered.common.event.tracking.PhaseContext.getPerBlockEntitySpawnSuppplier(PhaseContext.java:452)                                    
     net.minecraft.world.WorldServer.getEntitiesWithinAABB(WorldServer.java:3085)                                                                   
     net.minecraft.world.World.getEntitiesWithinAABB(World.java:3060)                                                                               
     com.pau101.fairylights.server.ServerEventHandler.onGetCollisionBoxes(ServerEventHandler.java:79)                                               
     net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1108_ServerEventHandler_onGetCollisionBoxes_GetCollisionBoxesEvent.invoke(.dynamic) 
     net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)                                                     
     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682)                                                                    
     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639)                                                                    
     net.minecraft.world.World.getCollisionBoxes(World.java:1387)                                                                                   
     org.spongepowered.common.entity.EntityUtil.changeWorld(EntityUtil.java:889)     
```


Full Trace:
https://gist.github.com/ryantheleach/489cf1b615993196a405de4f6ab6a89a

**Comment by Bucky420** [comment] 2018-08-03 07:29
i removed that mod and i still have issues

**Comment by dualspiral** [comment] 2018-08-03 07:30
Logs showing these issues? We can’t diagnose the problem without them.

**Comment by Bucky420** [comment] 2018-08-03 07:30
will do boss

**Comment by Addalyn** [comment] 2018-08-06 20:59
We have the same issues on 2 servers (atm3 and Foolcraft3) this is log from atm3
https://paste.dimdev.org/ewojunubek.md

**Comment by PurpleIsEverything** [comment] 2018-08-09 00:38
Having the same issue here on a Foolcraft server.

**Comment by Bucky420** [comment] 2018-08-09 07:41
is this good? 
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2273233/latest.log)


```
java.lang.IllegalStateException: Intended to track block entity spawns! Please analyze the current phase context.                      */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.lambda$throwWithContext$3(TrackingUtil.java:446)                              */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.getPerBlockEntitySpawnSuppplier(PhaseContext.java:452)                        */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_175647_a(WorldServer.java:3079)                                                               */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72872_a(World.java:3060)                                                                            */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     com.creativemd.littletiles.common.events.LittleEvent.worldCollision(LittleEvent.java:458)                                          */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1079_LittleEvent_worldCollision_GetCollisionBoxesEvent.invoke(.dynamic) */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)                                         */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682)                                                        */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639)                                                        */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_184144_a(World.java:1387)                                                                           */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.entity.EntityUtil.changeWorld(EntityUtil.java:889)                                                        */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.Entity.setLocation(Entity.java:5356)                                                                          */
[07:36:21] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.Entity.setLocationAndRotation(Entity.java:5303)           
```
i can remove littletiles but that does no world stuff either its a block mod XD 
i also did test with version 3376 of sponge

**Comment by cuddylier** [comment] 2018-08-15 23:24
I can confirm I also face this issue with any Forge version above 3350 and it also disappears with Sponge 3350.

Logs:

https://pastebin.com/raw/qv1HwYT5
https://pastebin.com/raw/qnZtXCAa

**Comment by rvveber** [comment] 2018-08-23 13:05
Same or Similar Issue.

**I am currently running**
- SpongeForge version: 3413
- Forge version: forge-1.12.2-14.23.4.2756

**Plugins:**
nucleus, luckperms, totaleconomy etc. (others not relevant)

**Issue Description**
https://www.youtube.com/watch?v=pLPWPFAbTPM&feature=youtu.be

**log**
https://ghostbin.com/paste/w7q2d

And i highly doubt it's mod incompatibility

**Comment by Shybella** [comment] 2018-08-23 15:48
Other plugins/mods are relevant if you read this topic you will see that

Disable LittleTiles and see what happens. I am not experiencing this problem.

I'm assuming your home location is ontop of LittleTiles.

**Comment by selkiess** [comment] 2018-10-04 16:15
I also ran into this when running a All the mods 3 v5.10.1 server.

I can also confirm that reverting to spongeforge build 3350 fixes the problem.

Relevant log:
[log.txt](https://github.com/SpongePowered/SpongeForge/files/2447138/log.txt)

**Comment by rvveber** [comment] 2018-10-04 16:24
This was indeed a bug with little tiles on my occurence, i highly suggest
updating creativecore and little tiles as it should be fixed in newer
versions.

Selkie707 <notifications@github.com> schrieb am Do., 4. Okt. 2018, 18:16:

**Comment by selkiess** [comment] 2018-10-04 16:33
I looked up the modlist for ATM3 but it looks like little tiles is not included in this modpack:
[https://rawgit.com/AllTheMods/ATM-3/master/modlist.html](https://rawgit.com/AllTheMods/ATM-3/master/modlist.html)

**Comment by phit** [comment] 2018-10-04 18:08
@Selkie707 fairy lights is, this happens when either fairylights or little tiles is on the server

**Comment by selkiess** [comment] 2018-10-05 13:34
@phit Is the problem on sponges end then or fairylights/little tiles?

I see that the issue was referenced [Here](https://github.com/pau101/Fairy-Lights/issues/48) by fairylights but that dev said there was nothing he could do and it was on Sponge's end.

**Comment by selkiess** [comment] 2018-10-14 06:48
Not sure if this will help fix the bug but I did just have something odd happen. I was testing the latest build 3481 to see if it was fixed and it was not, was in the nether and doing /spawn would just tp me to the nethers spawn, /home would bug as well.

Relevant Bit: I disconnected with myself still in the nether and downgraded spongeforge back to 3350, When I logged in I was now in the overworld near 0,0. No idea if this will help but it was definitely odd. 

Since we know the problem started after 3350, could the problem be caused by all the changes in [https://github.com/SpongePowered/SpongeForge/commit/49e93048631f5a01a88c24b83783fb45c958f310](https://github.com/SpongePowered/SpongeForge/commit/49e93048631f5a01a88c24b83783fb45c958f310) for 3351. I see a bunch of things were added/changed for phase tracker/context

**Comment by phit** [comment] 2019-01-02 16:44
somehow calling anything with AABB inside the GetCollisionBoxesEvent causes this to happen

repro: 
install [fairy lights](https://minecraft.curseforge.com/projects/fairy-lights/files) and nucleus
be in overworld and do `/spawn DIM1`

https://github.com/pau101/Fairy-Lights/blob/1.12/src/main/java/com/pau101/fairylights/server/ServerEventHandler.java#L79

**Comment by RainOfPain125** [comment] 2019-01-22 00:32
Happening since aug 1 and no fixes?

subbing to this thread

**Closed as completed** 2019-01-24 23:38 UTC
Labels: type: bug, type: mod incompatibility, system: phase tracker, version: 1.12

**Comment by ihavelag** [comment] 2020-08-30 11:08
Is there any plan to fix this issue?
