### ISSUE TITLE
Startup crash with BetterWithMods and Triumph

### ISSUE THREAD

**Issue by wormzjl** [SpongePowered/SpongeForge#2191] opened 2018-06-02 20:47 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3136
- Forge version: forge-1.12.2-14.23.4.2707-universal
- Java version: 1.8.0 171
- Operating System: win 7
- Plugins/Mods: 
BetterWithMods-1.12-2.1.22
BNBGamingCore-1.12.2-0.8.0
BNBGamingLib-1.12-2.11.2
Triumph-1.12.2-1.13.0

**Issue Description**
This crash only happens when BOTH BetterWithMods and Triumph are present, which works normally without spongeforge. Since sevtech contains both mods I guess this will be a problem.

Crash log: https://gist.github.com/wormzjl/1495ae7d5de67c0fddbf870cfded4e0f
Server log: https://gist.github.com/wormzjl/f2b09dd200f5bacda4fe4bc13180c259

**Comment by Aaron1011** [comment] 2018-06-03 00:13
The issue is occuring [here](https://github.com/SpongePowered/SpongeCommon/blob/8307be3fad663cf2d3fa3b6715d34d1b0553e0a8/src/main/java/org/spongepowered/common/mixin/core/advancement/MixinAdvancement.java#L169). One of the Triumph mod's advancements has an entry in `requirements` that doesn't have a corresponding entry in `criterionMap`

@Cybermaxke: Is this a bug with the mod, or something that we should be handling?

**Comment by Cybermaxke** [comment] 2018-06-03 09:17
@Aaron1011 Looks like a bug in the mod to me, it makes no sense to have a criterion requirement that doesn't exist.

**Comment by wormzjl** [comment] 2018-06-03 09:20
I'll try to report to the mod author

**Comment by Cybermaxke** [comment] 2018-06-03 10:29
Maybe we can throw a meaningful error message to know which advancement it's criterion is missing.

**Comment by phit** [comment] 2018-06-07 01:39
for ref https://bitbucket.org/bloodnbonesgaming/triumph/issues/4/triumph-mods-advancements-has-an-entry-in

**Comment by phit** [comment] 2018-07-03 17:48
https://bitbucket.org/bloodnbonesgaming/triumph/issues/4/triumph-mods-advancements-has-an-entry-in

**Comment by phit** [comment] 2018-07-03 17:48
@Cybermaxke can I close this as the mod has added a check to stop this in the future, or leave it open until a better message is added?

**Comment by Cybermaxke** [comment] 2018-07-04 02:39
@phit I already added the message in my PR, so I guess that you can close it.

**Comment by phit** [comment] 2018-07-04 02:41
oh didnt see the pr https://github.com/SpongePowered/SpongeCommon/pull/1968

**Closed as completed** 2018-07-07 14:55 UTC
Labels: status: accepted, type: mod incompatibility, system: advancement
