### ISSUE TITLE
PhaseTracker StackTrace with RFTools Dimension

### ISSUE THREAD

**Issue by flamechair** [SpongePowered/SpongeForge#2041] opened 2018-03-09 22:12 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2953
- Forge version:  14.23.2.2611
- Java version: java version "1.8.0_161"
- Operating System: Hosted server

- Mods (61): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AbyssalCraft, AbyssalCraft Integration, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, Baubles, BetterChests, Bookshelf, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Cyclops Core, Dark Utilities, EvilCraft, EvilCraft-Compat, Guide-API, Immersive Engineering, Iron Chest, Just Enough Items, LagGoggles, Level Up! Reloaded, McJtyLib, Mod Control, NetherEx, OpenBlocks, OpenModsLib, OpenModsLib Core, Quark, RFTools, RFTools Control, RFTools Dimensions, Redstone Flux, Reliquary, Roguelike Dungeons, Sophisticated Wolves, TeamLapen Library, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tool Belt, Tree Chopper, UniDict, Unlimited Chisel Works, Vampirism, Waila, WanionLib, What Are We Looking At, WorldEdit

- Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActionBroadcaster, CarrotShop, EconomyLite, GriefPrevention, LuckPerms, MMCRestrict, MagiBridge, Nucleus, ProjectCore, ProjectPortals, Rankup

I was building a dimension using RFTools Dimensions, and when the dimension started to generate the server was immediately closed and the following stack trace was logged in the console

```
> [22:55:29] [Server thread/INFO] [FML]: Loading dimension 4 (RFTOOLS4) (DedicatedServer)
> [22:55:29] [Server thread/ERROR] [Sponge]: /************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
> [22:55:29] [Server thread/ERROR] [Sponge]: /* Completing incorrect phase */
> [22:55:29] [Server thread/ERROR] [Sponge]: /************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
> [22:55:29] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system is very dependent on knowing when a change to any world */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* takes place, however, we are attempting to complete a "phase" other than the one */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* we most recently entered. This is an error usually on Sponge's part, so a report */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* is required on the issue tracker on GitHub. */
> [22:55:29] [Server thread/ERROR] [Sponge]: /************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
> [22:55:29] [Server thread/ERROR] [Sponge]: /* Expected to exit phase: TileEntityTickPhase */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* But instead found phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* StackTrace: */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* java.lang.Exception: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:273) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:186) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:392) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:249) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2849) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlj000(WorldServer.java:2836) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* net.minecraft.world.World.func_72939_s(World.java:6623) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2225) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* java.lang.Thread.run(Thread.java:748) */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* Phases Remaining: */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* Context: */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Owner: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Notifier: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Source: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedBlocks: CapturedBlocksSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockItemDrops: BlockItemDropsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockItemEntityDrops: BlockItemEntityDropsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedItems: CapturedItemsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedEntities: CapturedEntitiesSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedItemStack: CapturedItemStackSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - EntityItemDrops: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - EntityItemEntityDrops: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockEntitySpawns: CapturedBlockEntitySpawnSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedBlockPosition: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - World: WorldServer{LevelName=RFTOOLS4, DimensionId=54, DimensionType=rftoolsdim:rftools_dimension} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* Context: */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Owner: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Notifier: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Source: WorldServer{LevelName=RFTOOLS4, DimensionId=54, DimensionType=rftoolsdim:rftools_dimension} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedBlocks: CapturedBlocksSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockItemDrops: BlockItemDropsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockItemEntityDrops: BlockItemEntityDropsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedItems: CapturedItemsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedEntities: CapturedEntitiesSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedItemStack: CapturedItemStackSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - EntityItemDrops: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - EntityItemEntityDrops: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockEntitySpawns: CapturedBlockEntitySpawnSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedBlockPosition: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - World: WorldServer{LevelName=RFTOOLS4, DimensionId=54, DimensionType=rftoolsdim:rftools_dimension} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Phase: TileEntityTickPhase */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* Context: */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Owner: SpongeUser{isOnline=true, profile=com.mojang.authlib.GameProfile@4b5c4dfa[id=96b9d08f-34ef-4bcd-8c7a-bf3b7bc2a45d,name=defkult,properties={},legacy=false]} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Notifier: EntityPlayerMP['defkult'/24611, l='world', x=0.75, y=73.00, z=-469.98] */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - Source: DimensionBuilderTileEntity{tileType=SpongeTileEntityType{id=rftoolsdim:rftoolsdim_dimension_builder, name=rftoolsdim_dimension_builder, TileEntityClass=class mcjty.rftoolsdim.blocks.builder.DimensionBuilderTileEntity}, world=WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld}, pos=BlockPos{x=3, y=73, z=-471}, blockMetadata=4} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedBlocks: CapturedBlocksSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockItemDrops: BlockItemDropsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockItemEntityDrops: BlockItemEntityDropsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedItems: CapturedItemsSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedEntities: CapturedEntitiesSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - CapturedItemStack: CapturedItemStackSupplier{Captured=0} */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - EntityItemDrops: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - EntityItemEntityDrops: null */
> [22:55:29] [Server thread/ERROR] [Sponge]: /* - BlockEntitySpawns: CapturedBlockEntitySpawnSupplier{Captured=0} */
> [22:55:30] [Server thread/ERROR] [Sponge]: /* - CapturedBlockPosition: org.spongepowered.common.event.tracking.context.CaptureBlockPos@1f */
> [22:55:30] [Server thread/ERROR] [Sponge]: /* */
> [22:55:30] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2 */
> [22:55:30] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-SNAPSHOT-06016f2 */
> [22:55:30] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2611-7.1.0-BETA-2953 */
> [22:55:30] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.2.2611 */
```

**Comment by phit** [comment] 2018-03-27 01:18
gonna need a full log, but probably a dupe of https://github.com/SpongePowered/SpongeForge/issues/1757

**Comment by phit** [comment] 2018-04-19 16:50
no reply and other issue was closed

**Closed as completed by phit** 2018-04-19 16:50 UTC
Labels: status: more information needed, version: 1.12
