### ISSUE TITLE
Crash with AppliedEnergistics2

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2949] opened 2019-08-31 03:23 UTC
- I am currently running
- SpongeForge version: 1.12.2-2838-7.1.7-RC3906
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: java8
- Operating System: win10
- Plugins/Mods:

			mfbl_survival_plugin-1.0-SNAPSHOT.jar,
			mfbl-1.0.jar,
			spongeforge-1.12.2-2838-7.1.7-RC3843.jar,
			twilightforest-1.12.2-3.8.689-universal.jar,
			Nucleus-1.11.0-S7.1-MC1.12.2-plugin.jar,
			Ferdinand'sFlowers-1.12.x-1.10.4.1.jar,
			spark.jar,
			LuckPerms-Sponge-4.3.75.jar,
			appliedenergistics2-rv6-stable-1.jar,
			CodeChickenLib-1.12.2-3.2.0.345-universal.jar,
			CoFHCore-1.12.2-4.6.3.27-universal.jar,
			CoFHWorld-1.12.2-1.3.1.7-universal.jar,
			Cucumber-1.12.2-1.1.3.jar,
			Mantle-1.12-1.3.3.55.jar,
			MysticalAgradditions-1.12.2-1.3.2.jar,
			MysticalAgriculture-1.12.2-1.7.5.jar,
			RedstoneFlux-1.12-2.1.0.6-universal.jar,
			SlashBlade-mc1.12-r25.jar,
			TConstruct-1.12.2-2.12.0.157.jar,
			ThermalExpansion-1.12.2-5.5.4.43-universal.jar,
			ThermalFoundation-1.12.2-2.6.3.27-universal.jar,
			SJAP-1.1.0.jar

- Issue Description
It worked in version `spongeforge-1.12.2-2838-7.1.7-RC3843`, but when I updated the spongeforge to `1.12.2-2838-7.1.7-RC3906` , it crashed.

https://gist.github.com/zhourui123/c1bb6de60eb3e1e093ed5115e7fc3977

**Comment by ImMorpheus** [comment] 2019-08-31 16:00
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2871

(You didn't provide the full mod list, but you're using phosphor and this is the same issue)

**Closed as completed by ImMorpheus** 2019-08-31 16:00 UTC
Labels: resolution: duplicate

**Comment by zhourui123** [comment] 2019-09-06 04:26
I rechecked and only one `common_plugin` was missing that wrote by myself.
