### ISSUE TITLE
Fatal error in 7.1.6 recommended build

### ISSUE THREAD

**Issue by mistek131995** [SpongePowered/SpongeForge#2803] opened 2019-06-06 08:59 UTC
- SpongeForge version: 1.12.2-2825-7.1.6
- Forge version: 1.12.2 - 14.23.5.2838
- Java version: Version 8 Update 211 build 1.8.0_211-b12
- Operating System: Windows Server 2012 x64

```
[11:54:31] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
```

**Comment by dualspiral** [comment] 2019-06-06 12:37
Going to need a bit more information - specifically the stack trace _below_ `Caused by: java.lang.NullPointerException`. If you have the full `debug.log`, that would help.

**Comment by mistek131995** [comment] 2019-06-06 12:40
> Going to need a bit more information - specifically the stack trace _below_ `Caused by: java.lang.NullPointerException`. If you have the full `debug.log`, that would help.

[debug-4.log](https://github.com/SpongePowered/SpongeForge/files/3261543/debug-4.log)

**Comment by Zidane** [comment] 2019-06-06 13:43
It looks like something is swallowing the NPE trace. This is outside of Sponge's code at this point. 

Try the following to triage:
 * Pull SF from your server and see if it still happens
 * If it does not happen then re-add SF and remove mods 1 by 1 until we can find who is in-compatible
 * If it does happen then remove SF and remove mods 1 by 1 until we can find who is causing it.

Unless someone else has encountered this and knows who is at fault.

**Comment by mistek131995** [comment] 2019-06-06 13:48
I updated the Mekanism mod and then found this error.

> It looks like something is swallowing the NPE trace. This is outside of Sponge's code at this point.
> 
> Try the following to triage:
> 
> * Pull SF from your server and see if it still happens
> * If it does not happen then re-add SF and remove mods 1 by 1 until we can find who is in-compatible
> * If it does happen then remove SF and remove mods 1 by 1 until we can find who is causing it.
> 
> Unless someone else has encountered this and knows who is at fault.

I updated the Mekanism mod and then found this error. Today I have problem with ImmersiveEngineering mod... i created report in his repository https://github.com/BluSunrize/ImmersiveEngineering/issues/3484

**Comment by mistek131995** [comment] 2019-06-06 14:22
Mekanism devolpmers say:

> Unless you can get a proper stack trace from it, there's nothing we can do. IMO not even enough to pin it on Mekanism, even if it was the only mod you updated.
> 
> It's quite odd that the caused by trace has no stacktrace attached. Definitely not caused by us.

My English is bad and very difficult to communicate.
https://github.com/mekanism/Mekanism/issues/5504

**Comment by Zidane** [comment] 2019-06-06 14:31
@mistek131995 Then you'll need to do triage based on the steps I gave above and come back when you know more.

**Comment by dualspiral** [comment] 2019-06-06 14:33
I've posted on their issue page, a relavant stacktrace was towards the top of the debug log. It seems to me that they are trying to put a `null` into a `EnumMap` - ~~but it's unclear where that `null` came from and could be symptomatic of something else~~ see https://github.com/SpongePowered/SpongeForge/issues/2802#issuecomment-499337613 as to when this could be `null`.

@mistek131995 I advise you still do what @Zidane suggests, because we can then determine if something is going wrong on our end too. In particular, try removing SpongeForge and try again, do you still get these traces?

**Comment by mistek131995** [comment] 2019-06-06 14:35
> Я разместил на странице их проблемы соответствующую трассировку стека в верхней части журнала отладки. Мне кажется , что они пытаются положить `null`в `EnumMap`- но непонятно , откуда что `null`пришли и может быть симптомом чего - то другого.
> 
> @ mistek131995 Я советую вам по-прежнему делать то, что предлагает @Zidane , потому что тогда мы можем определить, идет ли что-то не так и с нашей стороны. В частности, попробуйте удалить SpongeForge и попробуйте еще раз, вы все еще получаете эти следы?

I setup old mod and SpongeForge version and watching the console. Now there are no errors.

**Comment by Zidane** [comment] 2019-06-06 14:46
Closing as the Mekanism devs have been alerted to a stack of the issue and I believe will be pushing a fix on their ends.

**Closed as completed by Zidane** 2019-06-06 14:46 UTC
