### ISSUE TITLE
Server Crash While Teleporting Through Dimensions

### ISSUE THREAD

**Issue by RogueRaiden** [SpongePowered/SpongeForge#1447] opened 2017-04-19 03:40 UTC
Server crash when using Draconic Evolution Dislocator, teleporting from Nether to Overworld. No other players online.

Crashlog shows Morpheus as being the cause. I created an issue on that mods page and they said that it is a bug through Sponge.
Not sure if this is enough information, and I thought i'd create an issue here so you guys are aware of this, if this is actually an issue through Sponge.

https://pastebin.com/ZWGTmJV3

**Comment by phit** [comment] 2017-04-19 07:43
dupe of #830

**Closed as completed** 2017-04-19 16:42 UTC
Labels: resolution: duplicate
