### ISSUE TITLE
Terrible lag spike upon erroring entity removal

### ISSUE THREAD

**Issue by Brend-Smits** [SpongePowered/SpongeForge#1420] opened 2017-04-06 09:39 UTC
Enabling the (tile) entity removal of erroring entities in the forge.cfg will trigger very bad TPS drops whenever Forge or Sponge removes such entity. 
I've caught it with my profiler, please visit the following link to download the .nps profile: 
https://toastynetworks.net/rsampler.php?id=36139c89668f4e3fbf73f72990344e40

As you can see in this screenshot it looks like it has trouble writing it to the disk, however, I can assure you that the disks are not the issue....
![image](https://cloud.githubusercontent.com/assets/15904543/24747650/5dda1254-1abd-11e7-8e8b-4c28e8c85199.png)

btw: TPS drops from 20 to 8 whenever this happens. 
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-a3257a01
SpongeForge: 1.10.2-2254-5.2.0-BETA-2264
Minecraft Forge: 12.18.3.2254

**Comment by Aaron1011** [comment] 2017-04-06 21:05
This appears to be caused by crash reports being generated. Can you upload your `fml-server-latest.log` and `latest.log`?

**Comment by Brend-Smits** [comment] 2017-04-07 09:13
There are no crash reports being generated though, that's the odd part.
Here are the logs:
[logs.zip](https://github.com/SpongePowered/SpongeForge/files/905071/logs.zip)
Hope these help.

**Comment by phit** [comment] 2017-11-06 20:42
@Rubbertjuh Does this not happen when Sponge is not installed?

**Comment by phit** [comment] 2017-11-30 09:22
No reply, closing this for now.

**Closed as completed by phit** 2017-11-30 09:22 UTC
Labels: version: 1.10 (u), type: performance
