### ISSUE TITLE
Sponge Forge and Biomes's O Plenty

### ISSUE THREAD

**Issue by Stokykyle** [SpongePowered/SpongeForge#2935] opened 2019-08-17 01:28 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3900
- Forge version: 1.12.2-14.23.5.2838
- Java version: Java 1.8.0_212
- Operating System: Windows and Linux

It appears when we introduce sponge forge without any sponge plugins we seem to have issues with biomesoplenty and generating chunks since when the world starts to use the generator it gives up and only generates plains and as soon as SpongeForge is removed it works correctly.

I am also using JustEnoughID's as well.

**Comment by clienthax** [comment] 2019-08-17 08:29
Any logs?

**Comment by Stokykyle** [comment] 2019-08-17 13:27
I don't really get any errors when it occurs so it would be just general logs it just seems to override biome's o plenty generation. You can see this is in effect since Journeymap just thinks the biome is plains all the time. 

Although I have provided a log file which is the latest log from the running server if you can find anything https://pastebin.com/jf2t2ECk

**Comment by BlazeRuler** [comment] 2019-08-17 16:50
JustEnoughIDs has a history of causing the Plains issue, so thats the mod causing that.

**Comment by Stokykyle** [comment] 2019-08-17 22:27
Is this along with sponge and justenoughids and biomes o plenty? 

Since just enough ids and biomes o plenty on there own work fine it's when spongeforge is introduced as well.

**Comment by bluelightning32** [comment] 2019-08-19 06:58
I have this problem with just enough IDs without biomes o plenty.

https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/83

**Comment by ImMorpheus** [comment] 2019-12-15 12:15
Since the issue with JustEnoughIDs was fixed on their end I'm going to close this.

I'm someone is able to reproduce this please reply and I'll reopen.

**Closed as completed by ImMorpheus** 2019-12-15 12:15 UTC
Labels: version: 1.12, status: needs triage
