### ISSUE TITLE
Server shuts down itself.

### ISSUE THREAD

**Issue by Stantastic** [SpongePowered/SpongeForge#2807] opened 2019-06-07 14:48 UTC
- SpongeForge version: 1.12.2-2825-7.1.6
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212
- Operating System: Ubuntu 18.04 LTS

- Running Feed the Beast modpack:
https://www.feed-the-beast.com/projects/ftb-ultimate-reloaded

**Issue Description**
Server shuts down itself after spamming the console with "net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler"

**Crash Report**
There is no crash file. The server will just shut down.

**Debug.log**
https://gist.github.com/Stantastic/9529e632c5fa6229d775924b1f0c7620

**Comment by JBYoshi** [comment] 2019-06-08 21:38
The `debug.log` file seems to be cut off - is that the full thing?

**Comment by Zidane** [comment] 2019-06-10 00:03
```
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*****************************************************************************************************************************************/
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*                                              Exception while trying to apply transaction                                              */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*****************************************************************************************************************************************/
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /* BlockTransactions failing to process can lead to unintended                                                                           */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /* consequences. If the exception is *directly* coming from                                                                              */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /* Sponge's code, please report to Sponge.                                                                                               */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*                                                                                                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*  BlockStates                                                                                                                          */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*                                                                                                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*  MarkedRemoved                                                                                                                        */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*                                                                                                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*  Affected Tiles                                                                                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*                                                                                                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*  QueuedTiles                                                                                                                          */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*                                                                                                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*  QueuedRemovals                                                                                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /* NeighborNotification                                                                                                                  */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*  Source Pos : soulshardsrespawn:soul_cage[active=false,powered=true], BlockPos{x=-10435, y=51, z=-1245}                               */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*  Notification : forgemultipartcbe:multipart_block, BlockPos{x=-10435, y=51, z=-1246}                                                  */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*                                                                                                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /* Exception:                                                                                                                            */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /* net.minecraft.util.ReportedException: Exception while updating neighbours                                                             */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.PhaseTracker.notifyBlockOfStateChange(PhaseTracker.java:727)                              */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.context.BlockTransaction$NeighborNotification.process(BlockTransaction.java:578)          */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.context.MultiBlockCaptureSupplier.processTransactions(MultiBlockCaptureSupplier.java:727) */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:437)                                  */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:411)                                  */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.unwind(TileEntityTickPhaseState.java:123)             */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.unwind(TileEntityTickPhaseState.java:71)              */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:318)                                         */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:613)                                                 */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:259)                                        */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:3167)                                                           */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zme000(WorldServer.java:3151)                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.world.World.func_72939_s(World.java:6842)                                                                           */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2290)                                                               */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                             */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     java.lang.Thread.run(Thread.java:748)                                                                                             */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /* java.lang.NullPointerException: null                                                                                                  */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.PhaseTracker.notifyBlockOfStateChange(PhaseTracker.java:691)                              */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.context.BlockTransaction$NeighborNotification.process(BlockTransaction.java:578)          */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.context.MultiBlockCaptureSupplier.processTransactions(MultiBlockCaptureSupplier.java:727) */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:437)                                  */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:411)                                  */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.unwind(TileEntityTickPhaseState.java:123)             */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.unwind(TileEntityTickPhaseState.java:71)              */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:318)                                         */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:613)                                                 */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:259)                                        */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:3167)                                                           */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zme000(WorldServer.java:3151)                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.world.World.func_72939_s(World.java:6842)                                                                           */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2290)                                                               */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                             */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                       */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*     java.lang.Thread.run(Thread.java:748)                                                                                             */
[16:29:12] [Server thread/DEBUG] [MultiBlockCaptureSupplier]: /*****************************************************************************************************************************************/
```

**Comment by Zidane** [comment] 2019-06-10 00:04
@gabizou

**Comment by gabizou** [comment] 2019-06-10 00:12
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2787

Already fixed by SoulCage mod.

**Closed as completed by gabizou** 2019-06-10 00:12 UTC
Labels: resolution: duplicate, version: 1.12, resolution: fixed externally
