### ISSUE TITLE
Lost Cities SpongeChunkGeneratorForge issues

### ISSUE THREAD

**Issue by BlayzerQ** [SpongePowered/SpongeForge#1815] opened 2017-10-16 04:53 UTC
I use the [LostCities](https://github.com/McJty/LostCities) mod in my modpack and interact with it in my mod. But I encountered a problem: Sponge is replaced the chunk generator. In a single game the code works and everything is fine, but on the server I get the error: java.lang.ClassCastException: org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge cannot be cast to mcjty.lostcities.dimensions.world.LostCityChunkGenerator.
In singleplayer Chunk Generator is LostCityChunkGenerator and all fine, on the server SpongeChunkGeneratorForge. 
This trouble on the LostCities github: https://github.com/McJty/LostCities/issues/50
This SpongeForge trouble? How fix it?

**I am currently running...**
- SpongeForge version: spongeforge-1.11.2-2476-6.1.0-BETA-2699
- Forge version: 13.20.0.2282
- Java version: 1.8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [x] macOS
 - [x] Windows

**Comment by Deamon5550** [comment] 2017-10-16 20:07
The issue is with us wrapping the chunk generator and them trying to get theirs out of the world by casting. Perhaps we could be less aggressive with how we handle world generation but that would essentially mean a config option that neuters the sponge worldgen api denying any plugins access to the world generator for that world for an issue that isn't even related to the wrapping. I don't like this as the only 'issue' with the current approach is this case of the mod getting their generator out of the world field, the terrain is still generated by the mod and sponge plugins still have full access.

The other option is we include a little hack such that the chunk generator in that field in world is still the wrapped one but is not actually the generator used for chunks essentially making our wrapper transparent to any mods.

(Btw that command will crash when used in any dimension with the worldtype not set to that mods type even without sponge, but thats not the issue here).

**Comment by phit** [comment] 2017-11-01 04:23
just to add to this, the mod works fine on our server on 1.12.2

**Comment by phit** [comment] 2017-12-02 22:17
same with
lostcities-1.12-1.0.2.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2753.jar

note the mod itself works fine, just the `/lc_debug` command doesn't https://github.com/McJty/LostCities/blob/master/src/main/java/mcjty/lostcities/commands/CommandDebug.java#L38

**Comment by KatsuoRyuu** [comment] 2018-01-07 05:23
This still exist in version 1.10.2

**Comment by Vitali8** [comment] 2018-02-04 16:59
Yes, the server crashes depending on the choice of generation in the mod configs. I changed from the default parameter `S: dimensionProfile = biosphere` in the config file and...
Here's the crash log: https://pastebin.com/9guj23Dz
SpongeAPI: 7.1.0-SNAPSHOT-b163786
SpongeForge: 1.12.2-2586-7.1.0-BETA-2868
Minecraft Forge: 14.23.1.2607
Mod version: lostcities-1.12-2.0.0

**Comment by McJty** [comment] 2018-02-14 10:23
As of this moment we have found no way to solve this on Lost City side. Suggestions are always welcome. Would it be possible to at least make this optional on Sponge side as a workaround?

Thanks

**Comment by ghost** [comment] 2018-02-14 13:55
Perhaps they could add a sponge config to prevent it from messing with worldgen because most sponge plugins don't require it anyways

**Comment by McJty** [comment] 2018-02-19 08:24
I may have found a solution on Lost City side. Working on it

**Comment by McJty** [comment] 2018-02-21 09:09
Should be fixed in 2.0.3. Untested

**Comment by ryantheleach** [comment] 2018-02-21 10:16
@McJty Just curious, what was the fix?

**Comment by McJty** [comment] 2018-02-21 10:19
Well the issue is that I need access to my chunk generator given a dimension ID. So I basically made a hashmap like this:

`Map<Integer, WeakReference<LostCityChunkGenerator>> cache;
`
So from that I can get the information I want without having to use a cast

**Comment by ghost** [comment] 2018-02-21 20:36
After a small fix for 2.0.3 it turns out to be working just fine

**Closed as completed** 2018-04-19 17:07 UTC
Labels: type: mod incompatibility, version: 1.10 (u), version: 1.11 (u), system: world, version: 1.12
