### ISSUE TITLE
Sponge not passing  getDeathMessage method?

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1150] opened 2016-12-31 21:47 UTC
https://github.com/TrainerGuy22/Reliquary/issues/234#issuecomment-266904444

**Comment by Aaron1011** [comment] 2017-01-01 20:12
@ProsperCraft: I've tried killing some mobs with the Hunters Handgun, and I can't seem to reproduce it. Is there a specific mob that you killed?

**Comment by ProsperCraft** [comment] 2017-01-01 20:59
Wasn't me, it was one of my players, and a while ago.

**Comment by Aaron1011** [comment] 2017-02-09 19:58
Closing, as I was unable to reproduce this. If the issue re-occurs, please re-open this issue.

**Closed as completed** 2017-02-09 20:12 UTC
