### ISSUE TITLE
Forge mismatch for sponge forge 2705 and modpacks moving to forge 2760

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#2453] opened 2018-09-23 19:05 UTC
Hey Team,

Just a query regarding the current forge version 2705 that is being used for builds of sponge.

Recently both DW20 1.12.2 and Stoneblock modpacks have updated with the version for forge: .2760

I have tried to run our servers with the new version and the latest sponge version but i get the following error due to the forge mismatch i believe: https://pastebin.com/766T05c3

Is there a possibility of us updating for having a fork of this version we can download as it seems the modpacks are now moving to this version?

Thank you

**Comment by ImMorpheus** [comment] 2018-09-23 21:11
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2434

**Closed as completed by ImMorpheus** 2018-09-23 21:11 UTC
