### ISSUE TITLE
Server Crash When Loading Worlds

### ISSUE THREAD

**Issue by FeistyPancake** [SpongePowered/SpongeForge#2578] opened 2019-01-25 22:31 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.4.jar
- Forge version: forge-1.12.2-14.23.5.2768
- Java version: Java 8 Update 191
- Operating System: Windows 10 (x64)

- Plugins/Mods:

foxcore
foxguard
itemchat
luckperms
magibridge
nucleus
projectcore
projectportals
sleepvote
yourcustompaintings

abyssalcraft integration
abyssalcraft
advanced solar panels
applied energistics 2
baubles
betterfps
bibliocraft
blood magic
botania
carryon
chisels and bits
codechickenlib
cofhcore
cofhworld
cooking for blockheads
dimensional doors
doomlike dungeons
ender core
ender io
erebus
evilnotchlib
foamfix
gravestone
guide-api
hwyla
immersive engineering
industrialcraft 2
infernal mobs
inventory tweaks
iron backpacks
iron chest
jei
libex
mantle
multimine
natura
natures compass
netherex
netherportalfix
pam's harvestcraft
quickleafdecay
randompatches
redstoneflux
reliquary
roguelike dungeons
ruins
secret rooms
silk spawners
tinkers construct
thaumcraft
thermal cultivation
thermal dynamics
thermal expansion
thermal foundation
twilight forest
unidict
wanionlib
wawla

**Issue Description**

When the server starts and begins loading the worlds, the server reports an exception in server tick loop.

https://gist.github.com/FeistyPancake/1f20ea2696305718e746ab6e3217f21a

**Comment by phit** [comment] 2019-01-25 22:35
when did this start happen, is this a new world? can you narrow down the list of mods to reproduce this?

**Comment by FeistyPancake** [comment] 2019-01-25 23:15
Not trying to be vague, but I didn't change any mods or plugins. The server has been running fine since I updated them about 2 weeks ago. This world has been the same for about 1 and a half years.

**Comment by ghost** [comment] 2019-01-28 21:00
@FeistyPancake 
Can you please try and delete the world folder and then attempt to reload the server.

**_This could be an issue related to corrupted chunks._**

**Comment by dualspiral** [comment] 2019-01-28 21:06
> java.lang.IllegalArgumentException: value already present: fbdf2cb0-824e-4070-b292-8875c576259f

> This could be an issue related to corrupted chunks.

Not at all, the error is that there are two worlds with the same UUID.

Did you make a duplicate of a world and leave it in your server world directory? If so, delete/rename the `level_sponge.dat` for the world in question.

**Closed as completed** 2019-01-28 22:08 UTC
Labels: status: more information needed, version: 1.12
