### ISSUE TITLE
Anvil Issue 

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2152] opened 2018-05-15 22:49 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3074
- Forge version: 14.23.3.2655
- Java version: 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: SevTech

**Issue Description**
When using the anvil if it's low durability and you try to put a book on a pickaxe it consumes both the book, pickaxe, and anvil and returns nothing. This does not happen on SP.

**Comment by Aaron1011** [comment] 2018-05-18 18:54
I can't seem to reproduce this. Are you able to reproduce this on a plain SpongeForge server running the latest build?

**Comment by phit** [comment] 2018-05-21 21:53
cant reproduce either, closing until author replies with proper reproduction

**Closed as completed by phit** 2018-05-21 21:53 UTC
Labels: system: inventory, version: 1.12, status: waiting for reply
