### ISSUE TITLE
ArmorEquipables lose armor when being hit

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeForge#483] opened 2016-01-04 17:54 UTC
Hello!

Discovered this bug on latest SpongeForge:
- Spawned a skeleton(or zombie) with `/summon Skeleton ~ ~ ~ {Equipment:[{id:261},{},{},{},{id:306}]}`, so it has a helmet and a bow
- Hit it once with hand(getting damage by falling doesn't reproduce it)
- Result: Damage on Entity and it lost its armor(not the bow!)

Rejoining doesn't help. Changing ids to real name doesn't help.

Only default mods active like FML and no plugins.

**Comment by Aaron1011** [comment] 2016-01-09 21:30
Ultimately, this is being caused by a Vanilla bug. When you pass in the tagcompound for the `ItemStack`, `ItemStack#readFromNbt` is called. Since you didn't explicitly specify `Count` in the tag, its left at the default value - 0.

For whatever reason, Vanilla doesn't seem to care at all about this. However, we (correctly) null out itemstacks in the inventory with a size of 0 or less when processing damage events. Since the itemstack always had a count of 0, it gets removed from the equipment.

The temporary solution is to specify `Count` (i.e. `/summon Skeleton ~ ~ ~ {Equipment:[{id:261},{},{},{},{id:306, Count:1}]}`, until we decide what should be done about this Vanilla quirk.

**Comment by randombyte-developer** [comment] 2016-01-10 10:47
Wow, thanks. That's really strange what Vanilla Minecraft is doing. I'll use the "workaround" command as it is only for testing my plugin.

**Comment by liach** [comment] 2016-01-11 01:43
Would the better solution be patching on the command?

**Comment by Aaron1011** [comment] 2016-02-26 02:08
I'm going to close this, since omitting the 'Count' tag should really be considered undefined behavior.

**Closed by Aaron1011** 2016-02-26 02:08 UTC
Labels: accepted, bug
