### ISSUE TITLE
Client Crashes with latest builds - 2583-2585

### ISSUE THREAD

**Issue by smmmadden** [SpongePowered/SpongeForge#1947] opened 2018-01-08 02:45 UTC
Minecraft: 1.12.2
    SpongeAPI: 8.0.0-SNAPSHOT-fa3b2ab
    SpongeForge: 1.12.2-2555-8.0.0-BETA-2826
    Minecraft Forge: 14.23.1.2585
    Java 1.8.0_152 x64
    Windows 10 Pro x64
    Client 1.12.2 Build 2585
List of Mods
![image](https://user-images.githubusercontent.com/10309346/34657377-72509130-f3f3-11e7-812f-8f7341f19c27.png)

Startup Server - no issues
Startup Client - no issues
Connect to Server from Client - crash
![image](https://user-images.githubusercontent.com/10309346/34657383-8a8d0a94-f3f3-11e7-9572-1a66f529d506.png)

Full log including server exceptions when trying to connect from client
https://pastebin.com/tUrqZ7k6

First STDERR with IllegalArgumentException: timeout value is negative (does not occur in working build of 2555 / 2758).
[21:32:42] [Query Listener #1/INFO]: Query running on 0.0.0.0:25595
[21:32:42] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalArgumentException: timeout value is negative
[21:32:42] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:       at java.lang.Thread.sleep(Native Method)
[21:32:42] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:       at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
[21:32:42] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:       at java.lang.Thread.run(Unknown Source)
[21:32:42] [Server thread/INFO] [nucleus]: Nucleus is performing final tasks before server startup completes.
[21:32:42] [Server thread/INFO] [nucleus]: Nucleus has started.
> Exception in thread "Server Watchdog" Jan 07, 2018 9:32:42 PM pokecube.core.interfaces.PokecubeMod log
Main exception and client crash immediately after server is first connected to and fails due to NetworkDispatcher exception.  This is same exception repeated since trying to update to latest SpongeForge builds.
[21:37:11] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_152]
        at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_152]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_152]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_152]
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[NioSocketChannel.class:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [AbstractChannel$AbstractUnsafe.class:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [AbstractNioChannel$AbstractNioUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]

**Comment by phit** [comment] 2018-01-08 02:51
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1936

**Closed as completed by phit** 2018-01-08 02:51 UTC
Labels: resolution: duplicate, version: 1.12

**Comment by phit** [comment] 2018-01-08 02:54
don't use api 8 builds, they aren't meant for production
try again with [latest stable](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2) (currently 2825)

if it's still an issue with that version reply in #1936

**Comment by smmmadden** [comment] 2018-01-08 03:54
I tried 2825 and that's a bust also.
