### ISSUE TITLE
(1.9.4) Crash with Actually Additions (world gen related?)

### ISSUE THREAD

**Issue by knoxhack** [SpongePowered/SpongeForge#700] opened 2016-06-19 17:49 UTC
https://gist.github.com/knoxhack/229fe673f2b322e7ded7ad8662722da5

**Comment by Ellpeck** [comment] 2016-06-19 17:55
This is apparently caused by me using a Fake Player during worldgen to bonemeal grass and flowers.
This might not be good practise, but it works in vanilla with forge, so I thought it was okay. If it's not, I could also change it.

**Comment by Aaron1011** [comment] 2016-06-19 18:01
@Ellpeck: I'm looking into it right now. There may be something Sponge can do to fix this.

**Comment by gabizou** [comment] 2016-06-19 18:03
I'd avoid using fake players for world gen always, but there is a bug that I hadn't considered before, and that's because SpongeCommon is not designed to take into account for Forge's FakePlayer object even though it extends `EntityPlayerMP`. Having that said, you could reproduce placing bonemeal by simply using a flower popular of sorts, similar to our [`MixinWorldGenFlowers`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/gen/populators/MixinWorldGenFlowers.java).

**Comment by Ellpeck** [comment] 2016-06-19 18:05
Yea, I could always just copy the code that Bonemeal uses as well. It was just easier to do it that way, and I didn't take into account it could cause problems.

**Comment by Aaron1011** [comment] 2016-06-19 18:16
I'll be pushing a fix in a minute. There shouldn't be any changes needed on your end to fix the crash.

**Comment by Ellpeck** [comment] 2016-06-19 18:21
Okay, thanks :)

**Comment by Aaron1011** [comment] 2016-06-19 18:21
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/78a787e266f2210c940c16d11c208f0ac767c019.

**Closed by Aaron1011** 2016-06-19 18:21 UTC
Labels: 1.9, bug
