### ISSUE TITLE
Multiple entries with same key Server Crash

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#1616] opened 2017-06-30 17:25 UTC
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2422.jar
- Forge version: 12.18.3.2281
- Java version: 1.8.0_111
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: 
1.10.2v1.5.0_RoxaTallDoorsMod.jar
astralsorcery-1.4.4.jar
AutoRegLib-1.0-2.jar
BirdsNests1.10-1.5.1.jar
BlockArmor-1.10.2-2.4.3.jar
chickens-4.3.2.jar
Chisel-MC1.10.2-0.0.11.26.jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
CodeChickenLib-1.10.2-2.5.9.267-universal.jar
CookingForBlockheads_1.10.2-4.2.43.jar
CreativeCore v1.7.3 mc1.10.2.jar
Currency-1.10.2-1.1.1.jar
CustomNPCs_1.10.2(25may17).jar
cxlibrary-1.10.2-1.2.3.jar
Dark Roleplay Core Alpha-0.2.0b.jar
Dark Roleplay Medieval Alpha v0.1.9.1.jar
Decocraft-2.4.2_1.10.2.jar
EnderCore-1.10.2-0.4.1.66-beta.jar
EnderIO-1.10.2-3.1.193.jar
EnderStorage-1.10.2-2.2.1.106-universal.jar
gravestone-1.5.13.jar
Grim Pack-1.10.2-3.4.17.53.jar
Hwyla-1.8.17-B31_1.10.2.jar
ironchest-1.10.2-7.0.15.804.jar
jei_1.10.2-3.14.7.420.jar
JurassiCraft-2.0.5.jar
LittleTiles v1.4.12 mc1.10.2.jar
llibrary-1.7.5-1.10.2.jar
Master_Chef_v5.0.1-1.10.X.jar
morefuelsmod-1.10.x-1.6.0.jar
MoreFurnaces-1.10.2-1.8.6.jar
multistorage-1.10.0-1.2.18b.jar
musiccraft-3.0.1.jar
NoMoreRecipeConflict-0.6(1.10.2).jar
NotEnoughItems-1.10.2-2.1.3.220-universal.jar
Nucleus-0.29.5-1.10.2-S5.1-plugin.jar
OnlinePicFrame v1.3.3 mc1.10.2.zip
Pam's HarvestCraft 1.10.2j.jar
PermissionsEx-Sponge.jar
BuycraftX.jar
holograms-2.2.jar
Nations-2.4.jar
Prism-3.0.0-beta2-45-gfbbeb2b.jar
TotalEconomy-v1.5.3.jar
PrimalCore-0.2.39.jar
Quark-r1.1-70.jar
RoguelikeDungeons-1.10.2-1.5.9.jar
roughMobs1.0.11-1.10.2.jar
ScalingHealth-1.11.2-1.0.8-52.jar
shetiphiancore-1.10.0-3.3.9.jar
SilentLib-1.10.2-2.1.5-63.jar
simpleCorn-1.10.2-2.2.0.jar
TamModized-1.10.2-0.9.2.jar
Teletubbies-1.9.4_1.10.x-1.1.2.2.jar
terraqueous-1.10.0-1.2.25.jar
vending-1.10.2-1.4.3.jar
VoidCraft-1.10.2-0.19.6.jar
Wawla-1.10.2-2.3.2.215.jar
Waystones_1.10.2-2.0.12.jar
wolfarmor-1.4.1.0.jar
zz-backpacks 1.10.2 - 3.1.5.jar

**What is the expected result?**
N/A
**What is the current result?**
It should not crash

CrashReport https://pastebin.com/raw/smDrsaz1

**Comment by Zidane** [comment] 2017-07-17 17:56
@Aaron1011 

Please get this fixed.

**Comment by HeberonYT** [comment] 2017-07-18 18:38
I downloaded the latest version of sponge forge and the problem still continues, here are other similar and recent reports.
There is no way to reproduce it, it is only random.

SpongeForge: 1.10.2-2281-5.2.0-BETA-2464.jar
https://pastebin.com/raw/9cx3b90U 
https://pastebin.com/raw/W4mU3BwK
https://pastebin.com/raw/LDS2z4Ks

**Comment by phit** [comment] 2017-11-06 22:18
Duplicate of #1588

**Closed as completed by phit** 2017-11-06 22:18 UTC
Labels: type: bug, resolution: duplicate, version: 1.10 (u)
