### ISSUE TITLE
Players turning invisible randomly

### ISSUE THREAD

**Issue by GuusLieben** [SpongePowered/SpongeForge#2989] opened 2019-10-01 08:25 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3926
- Forge version: 1.12.2-2825
- Java version: 8
- Operating System: Ubuntu Server 18.04.1

- Plugins/Mods:
Appropriately wrote a plugin to log all information about it : [plugin_data.log](https://github.com/SpongePowered/SpongeForge/files/3675141/plugin_data.log)

**Issue Description**
Players randomly turn invisible (usually when using WorldEdit or PlotSquared, but happens outside of that as well). This turns all other players invisible to them, and makes it so they cannot see the despawning of entities such as Item Frames. The player appears frozen to other players.

This issue has been present since at least 1.10.2 API 5, but is still present in the latest versions of Sponge(Forge).

I haven't been able to track down the exact cause, though I am available if it needs any more testing.

**Comment by kasdo** [comment] 2019-10-01 11:34
Same...

**Comment by clienthax** [comment] 2019-10-01 17:00
Duplicate issue
https://github.com/SpongePowered/SpongeForge/issues/2984
https://github.com/SpongePowered/SpongeForge/issues/2764

**Comment by GuusLieben** [comment] 2019-10-01 17:10
@clienthax Not a duplicate. 

#2984 still shows the actual player, and a frozen version of the player. Here the player appears frozen, but the actual player turns invisible to everyone else.

In #2764 single mobs randomly disappear. Here mobs _don't_ disappear to the player, even when they should.

**Comment by clienthax** [comment] 2019-10-02 11:20
@GuusLieben Pretty sure its the same root cause, both issues started happening at the same time.

**Comment by ImMorpheus** [comment] 2019-10-11 20:47
@GuusLieben Please, try to reproduce the issue with 1.12.2-2838-7.1.7-RC3928

**Comment by ImMorpheus** [comment] 2019-10-19 17:52
gonna close this and I assume this was fixed, if this is still an issue please reply and I'll reopen

**Closed as completed by ImMorpheus** 2019-10-19 17:52 UTC

**Comment by GuusLieben** [comment] 2019-10-28 10:27
Issue is still present on 1.12.2-2838-7.1.7-RC3928. Usually occurs when deleting plots with the PlotSquared plugin

**Comment by LXGaming** [comment] 2019-10-28 11:10
Might be an issue with PlotSquared as they are sending a full Chunk here: https://github.com/IntellectualSites/PlotSquared/blob/672fb0f82900fe634c13700565554ba1a03edb2d/Sponge/src/main/java/com/github/intellectualsites/plotsquared/sponge/util/block/SpongeLocalQueue.java#L117
