### ISSUE TITLE
Game just closes after adding spongeforge to mods folder using the new mojang launcher

### ISSUE THREAD

**Issue by sayore** [SpongePowered/SpongeForge#1654] opened 2017-07-16 21:13 UTC
I am currently (not) running... spongeforge-1.10.2-2281-5.2.0-BETA-2456.jar

- SpongeForge version:  2456
- Forge version: 2281
- Java version: jre1.8.0_121
- Operating System: Windows 10

 - [x] Windows
- [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 
- Plugins/Mods: 
Only Spongeforge

**What is the expected result?**
A running single player.

**What is the current result?**
Nothing

The launcher starts and says that there is a problem.
I just want some Plugins running in my SP world that dont exist as mods :<

https://gist.github.com/edenprojectde/4dd93f4a457bf6b05086fb31523cd4cf
http://imgur.com/a/Zzqid

**Comment by Zidane** [comment] 2017-07-17 17:22
I would recommend reinstalling your client installation and then reinstalling Forge. At that time, boot your client once, shut it down, and then put SpongeForge into your mods folder created on the client.

Try and launch again.

**Comment by sayore** [comment] 2017-07-18 00:58
Will do and report back later.

**Comment by sayore** [comment] 2017-07-18 01:09
Same result: I deleted the .minecraft Folder, reinstalled forge 2281, and the only mod in the mods folder was spongeforge 2281, i removed EVERYTHING i could find in the Profile's folder except for the spongeforge mod(i let forge run once before i added spongeforge, as you told me to).
Using the default Java of MC(which seems to be 8_25) and i used my Java (8_121) to test it.
And i usually know how to make profiles to mod minecraft even with the new client skin.
https://user-images.githubusercontent.com/6115966/28296069-2653e626-6b66-11e7-8630-5833f1eac9d7.png

https://gist.github.com/edenprojectde/3d9ac7ea9bdbde44adb8d5d2bd380ef3

**Comment by phit** [comment] 2017-07-18 01:14
can you upload your fml-client-latest.log please? should be in the logs folder

**Comment by sayore** [comment] 2017-07-18 01:26
There doesn't seem to be a fml-client-latest.log, i added FoamFix(!without Spongeforge!) to see if it generates with a mod in the mods folder. It's clearly listet in the mods section. But no fml-client-latest.log. Not even in my main modpack where i have a long list of mods.
(My main modpack: https://user-images.githubusercontent.com/6115966/28296393-4b546ab6-6b68-11e7-8989-1e536b387b4c.png)
I instead added the latest.log

https://gist.github.com/edenprojectde/10d5450668bd2c7e763a8c5566294f29
There are 2 logs in this gist!

**Comment by ryantheleach** [comment] 2017-07-18 01:51
Added FoamFix? Are you trying to boot Sponge and Foamfix at the same time? If so please read:

https://github.com/SpongePowered/SpongeForge/issues/1641#issuecomment-314614232

**Comment by sayore** [comment] 2017-07-18 02:02
No i just wanted to see if there would generate a fml log if i only used one mod, it didnt. Then i looked into my main modpack to see if there is a log, and there wasn't so i uploaded the only log available. Thats what i wanted to say.
FoamFix was just one where i knew it has no base mod/dependence. I grabbed it randomly. I did not mix these two mods.
This has absolutely no correlation.
I just wanted a mod that actually starts.
Setup:
For the Spongeforge
![grafik](https://user-images.githubusercontent.com/6115966/28297499-9a1c868c-6b6e-11e7-8fce-c58d2970b7d9.png)
and for FoamFix
![grafik](https://user-images.githubusercontent.com/6115966/28297525-b4218f82-6b6e-11e7-86a9-5e85451f0912.png)
Hope that makes it clear. :')

**Comment by phit** [comment] 2017-07-18 02:09
just managed to reproduce this in a fresh Windows 10 VM, issue seems to be related to the new launcher (tested with 2.0.934) since it works fine in the old one (tested with 1.6.73-j and 1.6.69)

tested with
* launcher built in java jre1.8.0_25
* freshly installed jre1.8.0_131
* forge 2281
* forge 2316
* sponge 2464

logs: https://gist.github.com/phit/4465c16b7a7a467d576327f906c4797f
https://gist.github.com/phit/a1dd6f66249479c2eed9eec6c99cf53e

**Comment by ryantheleach** [comment] 2017-07-18 02:11
So you are seeing the GUI warning that you get when you double click on SF when you run the launcher? 

The new launcher must be scanning for a public static void main or something.

**Comment by ryantheleach** [comment] 2017-07-18 02:12
@phit [03:57:48] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[0

[03:57:48] [main/INFO]: [org.spongepowered.launch.JavaVersionCheckUtils:ensureJava8:51]: You may be running an outdated version of Java. Any crashes from Sponge may require an update to Java.

**Comment by sayore** [comment] 2017-07-18 02:13
@ryantheleach The Gui opens when i try to start the SpongeForge mod. Its not the Launcher that does that, i only got my instructions from it that i followed.

**Comment by phit** [comment] 2017-07-18 02:14
@ryantheleach read what I posted.. I also tested with 1.8.0_131 and a bunch of forge versions, same crash
https://gist.github.com/phit/a1dd6f66249479c2eed9eec6c99cf53e

**Comment by ryantheleach** [comment] 2017-07-18 02:17
Thanks phit, it wasn't immediately obvious from the logs originally posted. Thought that your second test may have missed overriding the system java version in the options :)

**Comment by bloodmc** [comment] 2017-07-20 14:05
@Mumfrey any chance you can take a look at this?

**Comment by Mumfrey** [comment] 2017-07-20 15:33
I don't have a windows 10 PC around to test on. Looks like the classpath is incomplete though, from the error. NPE can only happen there if a class is missing.

**Comment by phit** [comment] 2017-07-20 18:39
The new launcher is also available on Linux, I'll spin up a VM and see if it works there!

edit:
I tested with Ubuntu 17.04, had to `apt-get install libgconf-2-4` and used [the staging tarball provided by Mojang](https://launcher.mojang.com/mc-staging/download/Minecraft_staging.tar.gz).

Same issue as in Windows, interestingly enough I couldn't get the launcer to write logs to file.
https://gist.github.com/phit/b017ff85872477cb475547bee75c5c0a

Also not sure if it was mentioned before, this is only an issue with 1.10.2 SpongeForge!
1.11.2 works perfectly fine.

**Comment by gabizou** [comment] 2018-01-01 09:11
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by gabizou** 2018-01-01 09:11 UTC
Labels: type: bug, system: client, version: 1.10 (u)
