### ISSUE TITLE
SimpleLogic-Wires -  Maximum block processing depth exceeded

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2768] opened 2019-05-19 06:08 UTC
**I am currently running**
spongeforge-1.12.2-2825-7.1.6-RC3713
forge-1.12.2-14.23.5.2836-universal

- Plugins/Mods:
![image](https://user-images.githubusercontent.com/38190325/57978358-fcc1ba80-7a14-11e9-942c-5bfc6b060829.png)

**Issue Description**
After updating to the latest version, as I was afraid, problems started. 
When using wires, server starts spamming to the console smth like this: https://gist.github.com/SSKirillSS/fb1fed0d0f1346ee3cab6269645fe9bc
After which it hangs and need to kill the process.

I placed the wires in this form(blue wool - any block, red wool - wire):
![image](https://user-images.githubusercontent.com/38190325/57978390-bd479e00-7a15-11e9-8df7-f03af77c171b.png)

**Comment by gabizou** [comment] 2019-05-19 06:27
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2252

**Closed as completed by gabizou** 2019-05-19 06:27 UTC
Labels: version: 1.12
