### ISSUE TITLE
Sponge Forge 1.8.9-1808-4.1.0-BETA-1241

### ISSUE THREAD

**Issue by pickman** [SpongePowered/SpongeForge#600] opened 2016-04-05 11:22 UTC
Launch error sponge forge server.

[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/204316/fml-server-latest.txt)

**Comment by hunter688** [comment] 2016-04-05 11:38
duplicate #598

**Comment by simon816** [comment] 2016-04-05 14:38
Closing, duplicate of #598

**Closed by simon816** 2016-04-05 14:38 UTC
