### ISSUE TITLE
SpongeForge server crashing

### ISSUE THREAD

**Issue by DumpleDoor** [SpongePowered/SpongeForge#2531] opened 2018-12-09 18:43 UTC
**I am currently running**

- SpongeForge version: 7.1.4
- Forge version: forge-1.12.2-14.23.5.2768-universal
- Java version: build 1.8.0_191-b12
- Operating System: Windows 10 Home v1803 Build:17134.407

- Plugins/Mods: Enchantment Leveler, Nucleus-1.7.0-S7.1-MC1.12.2-plugin,serial-key

**Issue Description**
When try to start the server, it will give me an error with the Nucleus plugin (i think), and will crash the server. I have tried different versions of forge, sponge and the nucleus plugin.

[2018-12-09-7.log](https://github.com/SpongePowered/SpongeForge/files/2660885/2018-12-09-7.log)
**
[crash-2018-12-09_11.33.45-server.txt](https://github.com/SpongePowered/SpongeForge/files/2660887/crash-2018-12-09_11.33.45-server.txt)

**Comment by DumpleDoor** [comment] 2018-12-09 19:09
#1585

**Comment by dualspiral** [comment] 2018-12-09 20:36
EnchantmentLeveler is very old - the last build was for API 4 (so, Minecraft 1.8.x). Can you remove EnchantmentLeveler and try again?

(It shouldn't be crashing like that anyway, but see if it runs without first)

**Comment by JBYoshi** [comment] 2018-12-10 02:55
> `Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/spongepowered/api/item/Enchantment`

EnchantmentLeveler is probably the cause. The `Enchantment` interface was moved in Sponge 7.0 (https://github.com/SpongePowered/SpongeAPI/commit/a26b4541727264c4cfaaebfc220816557195e835) to a different package, so old plugins that use it will break in new versions.

**Comment by gabizou** [comment] 2018-12-10 05:36
So old plugin installed. Closing as this is a support issue but not an issue that's the fault of Sponge's implementation.

**Closed as completed by gabizou** 2018-12-10 05:36 UTC
