### ISSUE TITLE
Sf3 - Exception attempting to capture or spawn an Entity

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1773] opened 2017-09-17 00:40 UTC
Hi all, Just noticed our SF3 is spamming about Capture or spawn an Entity.

https://pastebin.com/1smzS5s0

SpongeForge: 
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2281-5.2.0-BETA-2620
Minecraft Forge: 12.18.3.2254

Also spamming this - https://pastebin.com/F09uwQUh

**Comment by bloodmc** [comment] 2017-09-17 00:58
Disable the causetracker debug in sponge's global config for now.

**Comment by Keaton1188** [comment] 2017-09-17 01:02
Alright, guessing its something on your guys end and not ours? :)

**Comment by phit** [comment] 2017-11-21 22:30
Can't reproduce with 

Mantle-1.12-1.3.1.21.jar
natura-1.12-4.3.0.23.jar

Blew up Nitrocreeper in the Nether, no exceptions in the console. As for the second log, no idea how to reproduce as this issue lacks information.

**Comment by phit** [comment] 2018-01-01 15:50
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:50 UTC
Labels: version: 1.10 (u), system: phase tracker
