### ISSUE TITLE
Items in NuclearCraft machines getting dropped

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2644] opened 2019-03-14 14:23 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3626
- Forge version: forge-1.12.2-14.23.5.2781

- Plugins/Mods:

**Issue Description**
Updated sponge from RC3592 to RC3626 and now items are being instantly dropped when trying to place them into a NuclearCraft inventory.

NuclearCraft-2.13e--1.12.2

To reproduce:
1. Place down a Isotope Seperator and power it
2. Put things like Uranium Ingots in it

**Comment by bloodmc** [comment] 2019-03-14 17:36
Downgrade to 3616 until a fix is in place.

**Comment by gabizou** [comment] 2019-03-27 20:31
Can you re-test with the following jar?

https://www.mediafire.com/file/9o40kii7x9drz1z/spongeforge-1.12.2-2768-7.1.6-RC0.jar

**Closed as completed** 2019-03-28 06:21 UTC
Labels: version: 1.12

**Comment by Sir-Will** [comment] 2019-04-02 17:39
I'm unable to reproduce the issue in that build.

**Comment by bluelightning32** [comment] 2019-04-24 03:05
Due to other bugs in SpongeForge, I can't run versions that have this fix. I'm trying to figure out how far I have to downgrade for it to work.

The bug reproduces in spongeforge-1.12.2-2768-7.1.6-RC3621.jar.

**Comment by bluelightning32** [comment] 2019-04-24 03:12
The bug does not reproduce in spongeforge-1.12.2-2768-7.1.6-RC3616.jar.

**Comment by gabizou** [comment] 2019-04-24 03:21
> Due to other bugs in SpongeForge, I can't run versions that have this fix. I'm trying to figure out how far I have to downgrade for it to work.

Does not change that this issue is actually already fixed. Bugs in newer builds are being fixed regardless.
