### ISSUE TITLE
Incorrect block state.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#1989] opened 2018-02-07 06:47 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2887
- Forge version: forge-1.12.2-14.23.1.2586
- Java version: 1.8.0_131 x64
- Operating System: Ubuntu Server 16.0.4   or   Windows 7/8.1 x64 

- Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CmdCalendar, CommandSyncSponge, CommandUtils, EconomyLite, GriefPrevention, Holograms, JobsLite, LangSwitch, LuckPerms, Nucleus, PayDay, PlaceholderAPI, RedProtect, SkyClaims, TabManager, UltimateChat, UniversalMarket, VillagerShops, VirtualChest, WorldEdit

- Mods (16): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Bed Patch, Ex Nihilo Creatio, Fishing Net Mod, FoamFix, FoamFixCore, Giacomo's Foundry, IndustrialCraft 2, Parachronology, Tree Chopper, Waterfree Farming

**Mod GiacomosFishingNet on SpongeForge does not work correctly. After placing the fishing net in the water, it can not be broken except by a piston. When trying to break this block, it stays in place, but the item can fall out. The flow of water also stops. [I enclose a video made by my assistant and teste](https://www.youtube.com/watch?v=9YcyR7dRDw0)r.**

This issue does not cause errors in the console or other messages.

**Comment by RedNesto** [comment] 2018-02-07 10:56
After investigation it seems that since the net and the water are on the same block, Sponge thinks it is a water block, while it should capture the net AND the water.

**Comment by SawFowl** [comment] 2018-02-07 10:59
Maybe you're right. Without Sponge, there is no such problem. This can somehow be fixed?

**Comment by RedNesto** [comment] 2018-02-07 11:04
I will search how to fix it, but I can't promise anything, don't really know the blocks tracking part of Sponge.

**Comment by gabizou** [comment] 2018-02-22 08:35
Investigated into the issue a bit further with @RedNesto, discovered what I think to be a root issue with the mod itself and Sponge's tracking system.

To summarize the findings so far:
- Sponge tracks very well the block additions/removals when they are made
- Sponge does NOT track block removals, it plays back the block removals as soon as they are performed, which is considered playing physics before the `ChangeBlockEvent` is called, it can be seen [here](https://github.com/SpongePowered/SpongeCommon/blob/213a6dbcef5fc4616f2ceaa276bc444a30738450/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L645)
- Because Sponge already allowed the break logic to be called, the mod decides to do a block check to see if water is placed already, and then decides to re-place itself
- After sponge's phase tracker triggers the unwinding, the block drop for the previously broken `TileEntity` is dropped, and yet the mod already replaced the fishing net
- This then causes the dupe of the fishing net

Providing a screenshot of what's going on at the discovery of the bug:
![image](https://i.imgur.com/KrXGXXO.png)

What I think may need to happen is preventing the `block.onBreak` to be called after block change events are thrown (therefor preventable) and successfully tracked in the unwinding state.

Needing some more opinion from @bloodmc since this is a pretty nasty thing to think about.

**Comment by gabizou** [comment] 2018-02-22 08:50
@bloodmc @Zidane I went and committed a fix that I'm hoping will work, I tested it locally and it worked fine, but I'm not sure of the potential consequences.

**Comment by SawFowl** [comment] 2018-02-26 06:58
I noticed a similar bug in this [mod](https://minecraft.curseforge.com/projects/giacomos-foundry?gameCategorySlug=mc-mods&projectID=231254).  
When the block is destroyed, 2 items are dropped instead of one.

**Closed as completed** 2018-02-28 07:53 UTC
Labels: type: bug, type: mod incompatibility, version: 1.12, status: pr pending
