### ISSUE TITLE
EnderIO crash on server start (probably PRODUCTION)

### ISSUE THREAD

**Issue by IteratorW** [SpongePowered/SpongeForge#2808] opened 2019-06-07 17:15 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6 (not the newest one, it's recommended. but the same thing appers on 1.12.2-2825-7.1.7-RC3768 - last stable)
- Forge version: 14.23.5.2815
- Java version:  "1.8.0_201"
- Operating System: CentOS 7

- Plugins/Mods:
No plugins. Mod list is in the crash report below.

**Issue Description**
The server is just crashing while starting, when Sponge is installed. It starts sucessfully without it. Looks like a problem with EnderIO (see the crash report)
Crash report: https://pastebin.com/grBdFn56
latest.log: https://pastebin.com/ux7mPFUR
debug.log: [debug.log](https://github.com/SpongePowered/SpongeForge/files/3266965/debug.log)

**Comment by phit** [comment] 2019-06-07 17:22
see also https://github.com/SpongePowered/SpongeForge/issues/2805#issuecomment-499921100

**Comment by gabizou** [comment] 2019-06-07 17:38
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2805

**Closed as completed by gabizou** 2019-06-07 17:38 UTC
Labels: resolution: duplicate, version: 1.12
