### ISSUE TITLE
MKUltra Skills cannot be used on a sponge server

### ISSUE THREAD

**Issue by luenlin** [SpongePowered/SpongeForge#2374] opened 2018-08-10 03:34 UTC
SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3383
Forge version: 14.23.4.2705
Java version: 1.8.0_1.7.2
OS：windows server 2016
Plugins/Mods:
Minecraft,
Minecraft Forge,
SpongeAPI,
MKUltra-0.76 https://github.com/ChaosBuffalo/MKUltra
targeting_api-0.12 https://github.com/ChaosBuffalo/TargetingAPI
Issue Description
Some of the professional skills are not working properly on the Sponge Server.
For example, Druid's Ball Lightning and Flame Blade, Phoenix Aspect.
The specific performance is that the potion effect cannot be correctly given.
It should be said that most of the buff skills are invalid.

**Comment by ryantheleach** [comment] 2018-08-10 03:59
Example, Flame Blade potion: https://github.com/ChaosBuffalo/MKUltra/blob/master/src/main/java/com/chaosbuffalo/mkultra/effects/spells/FlameBladeEffectPotion.java#L22-L49

**Comment by luenlin** [comment] 2018-08-10 04:34
@ryantheleach  Yes

**Comment by luenlin** [comment] 2018-08-10 04:41
It should be said that it is not a potion buff invalid. It is simply not a player's potion effect.

**Comment by Kovak** [comment] 2018-08-10 17:05
Hey everyone,

One of the devs for MKUltra here.

We make use of a ton of custom potions, and tbh I've not really ever tested with Sponge, but it looks like maybe something is incompatible here. Is there anything to keep in mind with Sponge, Forge and PotionEffects? I'd love to get things fixed so that everything works as intended with Sponge.

**Comment by gabizou** [comment] 2018-08-10 17:17
I'm not quite sure what is being said here. Are there any logs? Any warnings? exceptions? Do the effects just not apply? Does damage not get dealt? 

Could you describe in more detail about what you said here?
> The specific performance is that the potion effect cannot be correctly given.
It should be said that most of the buff skills are invalid.

**Comment by luenlin** [comment] 2018-08-11 02:56
@Kovak 
The test found two possible causes
1.The syrup is incorrectly registered on the forge
Expressed as:`[Server thread/WARN] [mkultra]: Tried to get a spell on an unregistered target! Spell: effect.flame_blade`
2.The pre-API cannot correctly judge the relationship between the enemy and the friend in the sponge environment.
Expressed as:Range buff skills cannot be given to friendly creatures or players.
Skills like the Blade of Fire can't attach damage to hostile creatures.

Maybe mixin conflict with asm
Some doubts：What is setRegistryName? ?

**Comment by luenlin** [comment] 2018-08-11 02:58
@gabizou  Sorry, because the log and the debug don't see any errors.
These problems are all discovered by practice.

**Comment by luenlin** [comment] 2018-08-11 03:01
@ryantheleach @Kovak @gabizou 
I still provide the server running log.

https://paste.ubuntu.com/p/Pp57RM4Tfg/

**Edit:** Fixed link (ryantheleach)

**Comment by Kovak** [comment] 2018-08-11 17:48
The 
`
Tried to get a spell on an unregistered target! Spell: effect.flame_blade
`
is not from potion registration. This is some custom logic in MK-Ultra that allows us to keep a pairing of caster, target with the potion for effect execution. For most of these skills this means something is going wrong in our variation on EntityAreaEffectCloud:

https://github.com/ChaosBuffalo/MKUltra/blob/master/src/main/java/com/chaosbuffalo/mkultra/entities/EntityMKAreaEffect.java#L247


Investigating further: it looks like if a potion is applied directly it takes effect, but any of the effects that are applied by the EntityMKAreaEffect never do take effect if sponge is loaded. There's nothing really all that odd in the class, and its mostly just a copy/extension of the vanilla area cloud.

Do ya'll have any guidance about things for other modders to keep in mind if they want their stuff to work with sponge?

**Comment by ryantheleach** [comment] 2018-08-11 20:09
Is this happening to all targets? Or only when a very large group of targets is aimed at?

**Comment by Kovak** [comment] 2018-08-12 07:25
any targets at all, doesn't seem to hit friends, foes, or yourself regardless of number or anything.

**Comment by luenlin** [comment] 2018-08-13 01:15
@Kovak @ryantheleach 
Will this bug be fixed?

**Comment by luenlin** [comment] 2018-08-14 16:21
@ryantheleach Will the sponge fix this problem?

**Comment by luenlin** [comment] 2018-08-14 18:02
Is all entities, any skill can't work for the entity

**Comment by luenlin** [comment] 2018-08-22 09:57
Half a month has elapsed since the initial submission
What are you doing

**Comment by RedNesto** [comment] 2018-08-22 11:37
We are doing other things.
There are many other issues (some that are opened since September 2016) and developers choose what issues they want to fix, if they want to in the first place (staff members or not).
You, as well as other people have encountered issues, and we all know that this is inconvenient, but you have two choices: fix it yourself or wait for somebody else to fix it.

To me, insisting like that will not make things go faster, especially for projects like Sponge, where people who contribute are volunteers.

And keep in mind that working with mods can be complex, and may require changes to conflicting mods. Some modders are not very welcoming to changes for Sponge compatibility, so things can take a while before being fixed. **I'm not saying your issue is caused by some mods**, but it may be.
Regardless, you will have to wait for someone to find what is wrong here.

**Comment by ustc-zzzz** [comment] 2018-08-25 17:02
The reason is simply a coincidence.

Sponge will check all of the entities whether [the `ticksExisted` field is an integer multiple of four](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java#L420), and if it is SpongeForge, the value of the fields will firstly [be increased by one](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/entityactivation/MixinWorld_Activation.java#L69), then [the updates of these ticks will be skipped](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/entityactivation/MixinWorld_Activation.java#L70), so the skipped ticks would be `4n + 1` (`[1, 5, 9, 13, 17, ...]`).

The potion effects in the area effect clouds in MKUltra will only be effective when [the `ticksExisted` field is an integer multiple of five](https://github.com/ChaosBuffalo/MKUltra/blob/master/src/main/java/com/chaosbuffalo/mkultra/entities/EntityMKAreaEffect.java#L191), so the effective ticks would be `5n + 5` (`[5, 10, 15, 20, 25, ...]`). Obviously, updates in the 5th tick could have been executed but coincidentally skipped by SpongeForge. Furthermore, most of the area effect clouds won't even wait for updates in the 10th tick, because [the duration is set to 6 ticks by default](https://github.com/ChaosBuffalo/MKUltra/blob/master/src/main/java/com/chaosbuffalo/mkultra/effects/AreaEffectBuilder.java#L26).

In my personal opinion, the mod incompatibility is caused by Sponge. I have submited a Pull Request in order to solve the problem (SpongePowered/SpongeCommon#2074).

**Comment by phit** [comment] 2018-08-25 19:13
welp if thats the case this should be easily fixed by disabling entity activation for MKUltra

`/sponge config -g entity-activation-range.mods.mkultra.enabled false`

**Closed as completed** 2018-08-25 21:56 UTC
Labels: type: mod incompatibility, version: 1.12
