### ISSUE TITLE
Biomes O' Plenty Triggers runaway phase

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeForge#1437] opened 2017-04-14 01:32 UTC
The following shows up in the logs when using Biomes O' Plenty and SpongeForge on the 5.2 stable branch.
```
> /*******************************************************************************************************************************/
/*                                                      Completing Phase                                                       */
/*******************************************************************************************************************************/
/* Detecting a runaway phase! Potentially a problem                                                                            */
/* where something isn't completing a phase!!!                                                                                 */
/*                                                                                                                             */
/* Completing phase :                                                                                                          */
/* org.spongepowered.common.event.tracking.phase.block.BlockDro                                                                */
/* ItemsPhaseState@35c9d4c1                                                                                                    */
/*  Phases Remaining:                                                                                                          */
/*   - Phase: org.spongepowered.common.event.tracking.phase.block.BlockDropItemsPhaseState@35c9d4c1                            */
/*     Context:                                                                                                                */
/*     - Name: Source                                                                                                          */
/*       Object: SpongeBlockSnapshot{worldUniqueId=04a0bb2d-9c54-4846-9c47-e4ed54fb4da5, position=(-98,                        */
/*       39, 513), blockState=minecraft:torch[facing=west], extendedState=minecraft:torch[facing=west]}                        */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=1}                                                                          */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}                                                               */
/*     Context:                                                                                                                */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}                                                               */
/*     Context:                                                                                                                */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*   - Phase: PopulatorGenerationPhaseState{id=POPULATOR_RUNNING}                                                              */
/*     Context:                                                                                                                */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*     - Name: PopulatorType                                                                                                   */
/*       Object: SpongePopulatorType{id=minecraft:mushroom, name=mushroom, modid=minecraft}                                    */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}                                                               */
/*     Context:                                                                                                                */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}                                                               */
/*     Context:                                                                                                                */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*   - Phase: PopulatorGenerationPhaseState{id=POPULATOR_RUNNING}                                                              */
/*     Context:                                                                                                                */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*     - Name: PopulatorType                                                                                                   */
/*       Object: SpongePopulatorType{id=minecraft:mushroom, name=mushroom, modid=minecraft}                                    */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}                                                               */
/*     Context:                                                                                                                */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}                                                               */
/*     Context:                                                                                                                */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*   - Phase: PopulatorGenerationPhaseState{id=POPULATOR_RUNNING}                                                              */
/*     Context:                                                                                                                */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*     - Name: PopulatorType                                                                                                   */
/*       Object: SpongePopulatorType{id=minecraft:mushroom, name=mushroom, modid=minecraft}                                    */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}                                                               */
/*     Context:                                                                                                                */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*   - Phase: GeneralGenerationPhaseState{id=TERRAIN_GENERATION}                                                               */
/*     Context:                                                                                                                */
/*     - Name: CapturedBlocks                                                                                                  */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                                            */
/*     - Name: CapturedEntities                                                                                                */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                                          */
/*     - Name: World                                                                                                           */
/*       Object: WorldServer{LevelName=Wilderness, DimensionId=0, DimensionType=minecraft:overworld}                           */
/* Stacktrace:                                                                                                                 */
/* java.lang.Exception: Stack trace                                                                                            */
/*     org.spongepowered.common.event.tracking.CauseTracker.printRunnawayPhaseCompletion(CauseTracker.java:249)                */
/*     org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:206)                               */
/*     net.minecraft.block.Block.handler$onDropBlockAsItemWithChanceReturn$zzl000(Block.java:2748)                             */
/*     net.minecraft.block.Block.func_180653_a(Block.java:555)                                                                 */
/*     net.minecraft.block.Block.func_176226_b(Block.java:537)                                                                 */
/*     net.minecraft.block.BlockTorch.func_176593_f(BlockTorch.java:190)                                                       */
/*     net.minecraft.block.BlockTorch.func_176213_c(BlockTorch.java:137)                                                       */
/*     net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:2201)                                                          */
/*     net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:2071)                                                          */
/*     org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:471)                               */
/*     net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:2670)                                                    */
/*     net.minecraft.world.gen.structure.StructureComponent.func_175811_a(StructureComponent.java:240)                         */
/*     net.minecraft.world.gen.structure.StructureComponent.func_175809_a(StructureComponent.java:346)                         */
/*     net.minecraft.world.gen.structure.StructureMineshaftPieces$Corridor.func_189921_a(SourceFile:538)                       */
/*     net.minecraft.world.gen.structure.StructureMineshaftPieces$Corridor.func_74875_a(SourceFile:460)                        */
/*     net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)                                   */
/*     net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:602)                               */
/*     biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185931_b(ChunkProviderGenerateBOP.java:487)                    */
/*     org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)             */
/*     net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)                                                          */
/*     net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)                                                           */
/*     net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)                                 */
/*     net.minecraft.world.World.func_72964_e(World.java:303)                                                                  */
/*     net.minecraft.world.World.func_175726_f(World.java:298)                                                                 */
/*     net.minecraft.world.World.func_180495_p(World.java:5689)                                                                */
/*     com.skelril.skree.content.world.wilderness.MagicMushroomPopulator.generate(MagicMushroomPopulator.java:54)              */
/*     com.skelril.skree.content.world.wilderness.MagicMushroomPopulator.populate(MagicMushroomPopulator.java:45)              */
/*     org.spongepowered.api.world.gen.Populator.populate(Populator.java:101)                                                  */
/*     org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:230)             */
/*     net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)                                                          */
/*     net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)                                                           */
/*     net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)                                 */
/*     net.minecraft.world.World.func_72964_e(World.java:303)                                                                  */
/*     net.minecraft.world.World.func_175726_f(World.java:298)                                                                 */
/*     net.minecraft.world.World.func_180495_p(World.java:5689)                                                                */
/*     com.skelril.skree.content.world.wilderness.MagicMushroomPopulator.generate(MagicMushroomPopulator.java:54)              */
/*     com.skelril.skree.content.world.wilderness.MagicMushroomPopulator.populate(MagicMushroomPopulator.java:45)              */
/*     org.spongepowered.api.world.gen.Populator.populate(Populator.java:101)                                                  */
/*     org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:230)             */
/*     net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)                                                          */
/*     net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)                                                           */
/*     net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)                                 */
/*     net.minecraft.world.World.func_72964_e(World.java:303)                                                                  */
/*     net.minecraft.world.World.func_175726_f(World.java:298)                                                                 */
/*     net.minecraft.world.World.func_180495_p(World.java:5689)                                                                */
/*     com.skelril.skree.content.world.wilderness.MagicMushroomPopulator.generate(MagicMushroomPopulator.java:54)              */
/*     com.skelril.skree.content.world.wilderness.MagicMushroomPopulator.populate(MagicMushroomPopulator.java:45)              */
/*     org.spongepowered.api.world.gen.Populator.populate(Populator.java:101)                                                  */
/*     org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:230)             */
/*     net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)                                                          */
/*     net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)                                                           */
/*     net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)                                 */
/*     net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zom000(PlayerChunkMapEntry.java:1079) */
/*     net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)                         */
/*     net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)                                             */
/*     net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)                                                      */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)                                             */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                                   */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                                             */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                                      */
/*     java.lang.Thread.run(Thread.java:745)                                                                                   */
/*                                                                                                                             */
/* Minecraft : 1.10.2                                                                                                          */
/* SpongeAPI : 5.2.0-SNAPSHOT-a3257a0                                                                                          */
/* SpongeForge : 1.10.2-2254-5.2.0-BETA-2272                                                                                   */
/* Minecraft Forge : 12.18.3.2254                                                                                              */
/*******************************************************************************************************************************/
```

**Comment by Deamon5550** [comment] 2017-04-14 06:00
The problem (at least part of it) is recursive generation caused by https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/content/world/wilderness/MagicMushroomPopulator.java#L42-L43

The volume you receive from sponge is already offset so your double offset is pushing your population in to the neighbouring chunk causing it to generate.

**Comment by DarkArc** [comment] 2017-04-14 10:47
Interesting, that was based off of https://github.com/SpongePowered/SpongeCommon/blob/f39db6bf46c27fe90c6c7f13f3d8262bf3f1a0ae/src/main/java/org/spongepowered/common/world/gen/populators/HellMushroomPopulator.java a long time ago. Hasn't been a problem using vanilla generation for some reason.

**Comment by gabizou** [comment] 2017-04-14 15:09
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1404

**Closed as completed by gabizou** 2017-04-14 15:09 UTC

**Comment by Deamon5550** [comment] 2017-04-14 19:53
@DarkArc It used to be that you got a chunk and just had to know to apply the offset, but I changed it [here](https://github.com/SpongePowered/SpongeAPI/commit/654db1d5f6f2ec6e5327223969579efd791a26cd) to instead take an extent that already had a min and max set to the area you need to populate (although it shouldn't actually let you go out of it so maybe there is a bug there, I'll look into it).
