### ISSUE TITLE
Wither never explodes, console got flooded, eventually crashed

### ISSUE THREAD

**Issue by Philosyang** [SpongePowered/SpongeForge#2514] opened 2018-11-17 04:37 UTC
**I am currently running**

- SpongeForge version: **spongeforge-1.12.2-2768-7.1.4.jar**
- Forge version: **forge-1.12.2-14.23.5.2768-universal.jar**
- Java version: **OpenJDK 64-Bit Server VM, version 1.8.0_181**
- Operating System: **Linux:amd64:2.6.32-042stab134.3**

- Plugins/Mods:
AppliedFluidics-1.12.2-2.0.2.jar
Baubles-1.12-1.5.2.jar
BrandonsCore-1.12.2-2.4.7.189-universal.jar
Chameleon-1.12-4.1.3.jar
ChickenChunks-1.12.2-2.4.1.73-universal.jar
CoFHCore-1.12.2-4.6.1.22-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
Draconic-Evolution-1.12.2-2.3.17.321-universal.jar
ElevatorMod-1.12.2-1.3.6.jar
EnderCore-1.12.2-0.5.43.jar
EnderIO-1.12.2-5.0.37.jar
EnderIO-endergy-1.12.2-5.0.37.jar
EnderIO-zoo-1.12.2-5.0.37.jar
Hwyla-1.8.26-B41_1.12.2.jar
ImmersiveEngineering-0.12-86.jar
InventoryTweaks-1.63.jar
JustEnoughCharacters-1.12.0-3.1.1.jar
Mekanism-1.12.2-9.4.13.349.jar
MekanismGenerators-1.12.2-9.4.13.349.jar
MekanismTools-1.12.2-9.4.13.349.jar
NaturesCompass-1.12.2-1.5.1.jar
RedstoneArsenal-1.12.2-2.6.1.15-universal.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
StorageDrawers-1.12.2-5.3.7.jar
ThermalCultivation-1.12.2-0.3.1.8-universal.jar
ThermalDynamics-1.12.2-2.5.3.16-universal.jar
ThermalExpansion-1.12.2-5.5.2.39-universal.jar
ThermalFoundation-1.12.2-2.6.1.22-universal.jar
ThermalInnovation-1.12.2-0.3.1.8-universal.jar
UniDict-1.12.2-2.9.1.jar
WanionLib-1.12.2-1.7.jar
Wawla-1.12.2-2.5.264.jar
_AdamantineShield-0.3.3-api7.jar
_EasyScoreboards.jar
_LagGoggles-SPONGEFORGE-1.12.2-4.1.jar
_LuckPerms-Sponge-4.0.127.jar
_MagiBridge-API7-2.4.5.1.jar
_Nucleus-1.2.2-S7.0-MC1.12.2-plugin.jar
_Rankup-V5768-API7-plugin.jar
_SayItem-1.2.0.jar
__spongeforge-1.12.2-2768-7.1.4.jar
_worldedit-sponge-6.1.9-SNAPSHOT-dist.jar
appliedenergistics2-rv5-stable-11.jar
astralsorcery-1.12.2-1.10.3.jar
chiselsandbits-14.27.jar
forestry_1.12.2-5.8.1.322.jar
industrialcraft-2-2.8.73-ex112.jar
instantunify-1.12.2-1.1.2.jar
jei_1.12.2-4.13.1.222.jar
journeymap-1.12.2-5.5.2.jar
mcjtylib-1.12-3.0.6.jar
rftools-1.12-7.56.jar
rftoolsdim-1.12-5.62.jar

**Issue Description**
Spawned a wither with vanilla-minecraft method (placing soul sand and skull with hand) One player went into the wither's collision box (that F3+B thing) and shift-right clicked with a Ender IO mod [Staff of Traveling](https://ftbwiki.org/Staff_of_Traveling). He teleported out of the collision box as normal would do, while the wither never explodes. The wither just keeps that "before explosion" phase and the server log is flooded with the same exception, eventually the TPS dropped to 0 and the server crashes.

[server log](https://gist.github.com/Philosyang/caceb7c7396c2c6522b821cd6c54b837)

**Comment by ImMorpheus** [comment] 2018-12-01 16:15
Relevant code:

```
[22:49:53] [Server thread/ERROR] [Sponge]: /******************************************************************************************************************************************************************************/
[22:49:53] [Server thread/ERROR] [Sponge]: /*                                                                   Exception occurred during a PhaseState                                                                   */
[22:49:53] [Server thread/ERROR] [Sponge]: /******************************************************************************************************************************************************************************/
[22:49:53] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best effort to not throw exceptions randomly                                                                                              */
[22:49:53] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most cases, something else triggered this                                                                                               */
[22:49:53] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash by catching it. The following stacktrace                                                                                            */
[22:49:53] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                                                                                                    */
[22:49:53] [Server thread/ERROR] [Sponge]: /******************************************************************************************************************************************************************************/
[22:49:53] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: EntityTickPhase                                                                                                                        */
[22:49:53] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                                                                                                          */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     - Owner: SpongeUser{isOnline=false, profile=com.mojang.authlib.GameProfile@4bfd4d10[id=5041d0da-fcb5-45be-9411-820ba992e3f7,name=S_Hecond,properties={},legacy=false]} */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     - Source: EntityWither['Wither'/327, l='world', x=446.85, y=35.00, z=214.45]                                                                                           */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                               */
[22:49:53] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@75707348                                                                                                                          */
[22:49:53] [Server thread/ERROR] [Sponge]: /******************************************************************************************************************************************************************************/
[22:49:53] [Server thread/ERROR] [Sponge]: /* StackTrace:                                                                                                                                                                */
[22:49:53] [Server thread/ERROR] [Sponge]: /* java.lang.IllegalStateException: Owner for this phase context is already set!                                                                                              */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.owner(PhaseContext.java:144)                                                                                      */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.applyNotifierIfAvailable(PhaseContext.java:369)                                                                   */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.appendContextPreExplosion(EntityTickPhaseState.java:264)                                       */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.appendContextPreExplosion(EntityTickPhaseState.java:63)                                        */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.phase.general.ExplosionContext.populateFromCurrentState(ExplosionContext.java:48)                                              */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.phase.general.ExplosionState.createPhaseContext(ExplosionState.java:58)                                                        */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.phase.general.ExplosionState.createPhaseContext(ExplosionState.java:47)                                                        */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:3233)                                                                                                    */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.triggerInternalExplosion(WorldServer.java:2709)                                                                                        */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.interfaces.entity.explosive.IMixinExplosive.detonate(IMixinExplosive.java:49)                                                                 */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.boss.EntityWither.redirect$onExplode$zfj000(EntityWither.java:919)                                                                                */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.boss.EntityWither.func_70619_bc(EntityWither.java:258)                                                                                            */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769)                                                                                                 */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)                                                                                         */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)                                                                                                  */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)                                                                                                 */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.boss.EntityWither.func_70636_d(EntityWither.java:188)                                                                                             */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)                                                                                        */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)                                                                                                 */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)                                                                                                */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:157)                                                                                 */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zma000(WorldServer.java:2982)                                                                              */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72866_a(World.java:4157)                                                                                                                */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)                                                                                                     */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72870_g(World.java:1955)                                                                                                                */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72939_s(World.java:6605)                                                                                                                */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2295)                                                                                                    */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                                                                            */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                                                                  */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                                                            */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                                                     */
[22:49:53] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Thread.java:748)                                                                                                                                  */
[22:49:53] [Server thread/ERROR] [Sponge]: /*  Phases Remaining:                                                                                                                                                         */
[22:49:53] [Server thread/ERROR] [Sponge]: /*                                                                                                                                                                            */
[22:49:53] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                                                                         */
[22:49:53] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-70763aa8                                                                                                                                                 */
[22:49:53] [Server thread/ERROR] [Sponge]: /* Sponge : 1.12.2-7.1.4                                                                                                                                                      */
[22:49:53] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2768-7.1.4                                                                                                                                            */
[22:49:53] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.5.2768                                                                                                                                             */
[22:49:53] [Server thread/ERROR] [Sponge]: /******************************************************************************************************************************************************************************/
```

**Comment by ImMorpheus** [comment] 2018-12-01 16:16
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2475

**Closed as completed by ImMorpheus** 2018-12-01 16:16 UTC
Labels: status: needs triage

**Comment by Philosyang** [comment] 2018-12-01 20:02
Tried with /killentity and successfully removed the wither, though problem may occur again in the future...
