### ISSUE TITLE
Singleplayer Spongeforge crash on start up

### ISSUE THREAD

**Issue by Ghostfoatitan** [SpongePowered/SpongeForge#1756] opened 2017-08-30 06:35 UTC
Spongeforge causes minecraft to crash on start up without generating a crash log, removed all mods and just had spongeforge in the mod folder and still will not start

**I am currently running...**

- SpongeForge version: 5.2.0-BETA-2597
- Forge version: 2281
- Java version: 8.141
- Operating System: Windows 7

**Comment by phit** [comment] 2017-08-30 06:36
check the logs folder, and provide the fml-client-latest.log

**Comment by Ghostfoatitan** [comment] 2017-08-30 06:40
[latest.zip](https://github.com/SpongePowered/SpongeForge/files/1262620/latest.zip)
Here is what i think is the correct log you are asking for

**Comment by phit** [comment] 2017-08-30 06:56
does it load without sponge? something broke in your installation

**Comment by Ghostfoatitan** [comment] 2017-08-30 06:57
Loads just fine without sponge, my mods load with it just fine as well

**Comment by phit** [comment] 2017-08-30 07:01
Reinstall the instance/forge/libraries, works fine here with the vanilla launcher.

![image](https://user-images.githubusercontent.com/2097483/29859306-c4db132e-8d61-11e7-8902-4c1587fc10f4.png)

**Comment by Ghostfoatitan** [comment] 2017-08-30 07:20
Did that, still not working

**Comment by Mumfrey** [comment] 2017-08-30 10:16
It looks like your forge binary is missing or incomplete, reinstall forge.

**Comment by Ghostfoatitan** [comment] 2017-08-30 20:24
already did that due to removing the library

**Comment by tgstyle** [comment] 2017-08-31 03:17
Out of curiosity are you using MultiMC and having it install liteloader? Spongeforge will not load with liteloader, at least on 1.12 and above.

**Comment by Mumfrey** [comment] 2017-08-31 10:39
> Spongeforge will not load with liteloader, at least on 1.12 and above.

~~What? This is news to me.~~ Confirmed, it works fine. Please don't just regurgitate disinformation like this. I'm sure if it wasn't working then someone might have bothered to report it to me. The only reports I've had of it not working are people trying to get liteloader to run on a server, which it obviously won't.

**Comment by Ghostfoatitan** [comment] 2017-08-31 11:09
i am not using multimc or liteloader

**Comment by phit** [comment] 2017-08-31 11:11
derp, I even tested this myself, Sponge currently does not work with the new Vanilla launcher..
this issue is a duplicate of #1654

**Comment by Ghostfoatitan** [comment] 2017-08-31 11:32
hmm good to know, thanks for pointing me to the current one, couldnt find it

**Comment by tgstyle** [comment] 2017-08-31 15:48
@Mumfrey I have tried it multiple times and could not get it to work. Always this same result. Fresh install with newest launcher as well as MultiMC.
https://gist.github.com/tgstyle/96d9be85d1363089d3701f2d544e9956

Edit: Here is your report for no disinformation.

**Comment by Mumfrey** [comment] 2017-09-01 12:18
> @Mumfrey I have tried it multiple times and could not get it to work. Always this same result. Fresh install with newest launcher as well as MultiMC.
> https://gist.github.com/tgstyle/96d9be85d1363089d3701f2d544e9956
> 
> Edit: Here is your report for no disinformation.

Oh I see, it's because Sponge currently requires 0.7.2 of Mixin but liteloader is still shipping 0.7.1 in the latest snapshot, I hadn't noticed because my local builds are already using 0.7.3.

If you come across problems with LiteLoader in the future, please report them on [the issue tracker](http://develop.liteloader.com/liteloader/LiteLoader/issues) because I can't fix problems if I don't know about them.

Apologies for accusing you of spreading disinformation, I wasn't aware of the issue and I try to be diligent and make sure that things always play nice together.

As for this issue, it seems to still be a mystery, which is not great.

**Comment by phit** [comment] 2017-09-15 23:53
@mumfrey not a mystery its a Duplicate of #1654
sponge doesn't work with the new minecraft launcher

**Comment by phit** [comment] 2017-11-06 20:19
Duplicate of #1654

**Closed as completed by phit** 2017-11-06 20:19 UTC
Labels: resolution: duplicate, version: 1.10 (u)
