### ISSUE TITLE
Exception trying to process over a phase

### ISSUE THREAD

**Issue by Coolfeather2** [SpongePowered/SpongeForge#1701] opened 2017-08-08 06:12 UTC
Source issue: ForestryMC/ForestryMC#1788
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464 
- Forge version: 12.18.3.2281        
- Java version: 1.8.0_131
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
```
Plugins (94): 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, Applied Energistics 2, BD Lib, AE2 Stuff, Ars Magica 2, AnimationAPI, CodeChicken Lib, Avaritia, Baubles, Botania, CoFH Core, Brandon's Core, BungeeTabListPlus-SpongeBridge, Chisel, CodeChicken Core, DrZhark's CustomSpawner, Draconic Evolution, DrZhark's Mo'Creatures Mod, Elevator Mod, EnderCore, Just Enough Items, Ender IO, Extra Utilities 2, Zero CORE, Extreme Reactors, Faster Ladder Climbing, IndustrialCraft 2, Forestry, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, Gravestone Mod, Guide-API, Harvest, iChunUtil, Hats, Mantle, Tinkers' Construct, Immersive Engineering, Industrial Wires, Inventory Pets, Iron Chest, Long Fall Boots, LuckPerms, MCMultiPart, Mekanism, MekanismGenerators, MekanismTools, mercurius_updater, MineFactory Reloaded, MFR Compat: Vanilla, MorePlayerModels, Morpheus, MrTJPCore, MultiChat Sponge, Natura, Nether Core, OpenComputers, p455w0rd's Library, SonarCore, Practical Logistics 2, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, Thermal Foundation, Thermal Expansion, Redstone Arsenal, Roots, Realistic Terrain Generation, Sync, Tails, Thermal Dynamics, TorchMaster, Vein Miner, Mod Support, I Can See Everything, What Are We Looking At, Wireless Crafting Terminal 2, Experience Rings
```
**What is the expected result?**
Was flying a manticore, dismounted into a creeper and the manticore vanished
**What is the current result?**
manticore vanished

https://gist.github.com/Coolfeather2/c137d86d5c30269d5170e1e4d42133ef

**Comment by Coolfeather2** [comment] 2017-08-08 06:30
SpongePowered/SpongeForge#1687

**Comment by phit** [comment] 2017-11-07 12:35
Duplicate of #1687

**Closed as completed by phit** 2017-11-07 12:35 UTC
Labels: resolution: duplicate, version: 1.10 (u)
