### ISSUE TITLE
Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@189fa0eb: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Faryzal2020** [SpongePowered/SpongeForge#1425] opened 2017-04-09 09:06 UTC
the server crashes whenever someone teleporting to DIM-1
https://pastebin.com/H79jjfwP
using spongeforge 5.2.0 2264 forge 2254

**Comment by phit** [comment] 2017-07-18 17:34
dupe of #830

**Closed as completed** 2017-07-18 17:37 UTC
Labels: resolution: duplicate
