### ISSUE TITLE
Incompatibility with Tinker Construct mod 

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#887] opened 2016-09-05 09:39 UTC
https://github.com/SlimeKnights/TinkersConstruct/issues/2367#issuecomment-244635226
Originally I reported the bug in there. Then when I run my server in forge, the bug disappeared. My sponge version is spongeforge-1.10.2-2073-5.0.0-BETA-1700.

The bug is

> There is no crash. As I said, you can know everything when you watch this video. Please watch it. Or you can try to show this error by yourself. You just need to hover your mouse on the tconstruct's equipment and then press "q" to drop them away. Now, you will find you can drop unlimited same item. Please fix it, thanks.

And I found this bug only appears in sponge.

**Comment by 5igm** [comment] 2016-09-05 09:53
https://my.pcloud.com/publink/show?code=XZuGQWZtFe4VlojngYaHNNRxFX0IzfPHVvV

**Comment by bonii-xx** [comment] 2016-09-05 10:05
Some extra info: Forge/Vanilla can't handle itemstacks with custom EntityItems when using /give. They spawn the items twice in that case. Probably the same logic affected.

**Comment by gabizou** [comment] 2016-09-05 13:19
Does disabling item pre merging in the optimization category work?

**Comment by 5igm** [comment] 2016-09-05 14:54
@bonii-xx

**Comment by hunter688** [comment] 2016-09-05 18:49
similar issue in the 1.8.9 spongeforge: #781

**Comment by Nentify** [comment] 2016-09-05 18:52
@gabizou Yes this still happens with pre-merging off.

**Comment by Nentify** [comment] 2016-09-05 23:34
Using Q does work fine though, not sure if that was mentioned.

**Comment by 5igm** [comment] 2016-09-07 09:45
@Nentify You also need to install tinker construct. When you hover your mouse on tinker construct equipment and try to drop, you will drop unlimited amount. I has showed this in the video.

**Comment by Nentify** [comment] 2016-09-07 10:00
@5igm Yes, I have Tinkers Construct and I'm having the same issue. Using Q while holding the item with the inventory closed works fine, but using Q while hovering over an item inside the inventory or moving the item to the left of the inventory and clicking dupes the tool.

**Comment by Aaron1011** [comment] 2016-09-30 20:18
The cause of this issue is Forge's [questionable](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/common/ForgeInternalHandler.java#L67) way of allowing mods to use an entity other than `EnittyItem` for their `ItemStacks`. Forge has an internal `EntityJoinWorldEvent listener which, when an `EntityItem` is spawned whose `ItemStack` requires a custom `Enitty`, cancels the event and spawns in a new entity.

This `EntityJoinWorldEvent`, however, is special. It's fired [by SpongeForgeEventFactory](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/event/SpongeForgeEventFactory.java#L979) in response to the original `DropItemEvent.Dispense`. If this `EnitityJoinWorldEvent` is cancelled, then the original `DropItemEvent.Dispense` event is cancelled. This causes the entire drop sequence to be cancelled, triggering the item to be restored to the inventory slot - just as if a plugin had cancelled the event.

Assuming that we don't want to change this behavior of `SpongeForgeEventFactory`, then we'll need to special-case Forge's event listener. Were it a normal event listener, Sponge's behavior would be perfectly correct - it sees the original event being cancelled, and another entity spawn happening (which happens to also be an `EntityItem`).

The best way to special-case this would probably be to perform Forge's `EntityItem` replacement logic ourselves, and overwrite the original listener method with a no-op. This should allow us to pass the mod-provided entity to the event, rather than passing in the 'wrong' entity and firing a separate `SpawnEntityEvent` later. Since Forge's listener should always be the first listener to receive an `EntityJoinWorldEvent`, this behavior <i>should</i> be completely transparent to mods.

Pinging @Zidane and @gabizou for input.

**Comment by Aaron1011** [comment] 2016-10-03 21:04
@5igm; This is fixed in the latest SpongeForge. Sorry for the very long delay in getting this addressed.

**Closed** 2016-10-03 21:04 UTC
Labels: accepted, bug

**Comment by 5igm** [comment] 2016-10-05 16:23
@Aaron1011 Thank you very much! Wish sponge to be better!^_^
