### ISSUE TITLE
sponge 2838-7.1.7-RC3848 and 2825-7.1.6 ,  Block production

### ISSUE THREAD

**Issue by xxlio109** [SpongePowered/SpongeForge#2886] opened 2019-07-18 14:25 UTC
SpongeForge version: 1.12.2-2838-7.1.7-RC3848 and  spongeforge-1.12.2-2825-7.1.6
Forge version: 1.12.2-14.23.5.2838
Java version: JDK_1.8.0_211
Operating System: Windows 10

Mods:
Librarianlib-1.12.2-4.19.2-release
Forgelin-1.8.3
wizardry-0.10.8

Plugins: no

Issue Description
Can't make anything through mana water, always in mana water

The default configuration  global.conf

In the absence of a sponge, everything is normal

**Comment by phit** [comment] 2019-07-18 16:57
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2795

**Closed as completed by phit** 2019-07-18 16:57 UTC
Labels: resolution: duplicate, version: 1.12
