### ISSUE TITLE
Flat Transfer Node disappearing on chunk load

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2293] opened 2018-07-10 22:38 UTC
With sponge installed the Flat Transfer Nodes from ExtraUtilties2 are disappearing when the chunk gets loaded. This issue doesn't happen without sponge. I had the similar issue with other blocks like Translocators but wasn't able to reproduce it effectively, not sure if it's the same issue.

To reproduce:
- Place a chest and place a Flat Transfer Node (Item) at one of the sides
- Reload the chunk by unloading it and loading it again
- The Flat Transfer Node is no longer there

spongeforge-1.12.2-2705-7.1.0-BETA-3284
forge-1.12.2-14.23.4.2705-universal

**Comment by bloodmc** [comment] 2018-07-24 03:51
Does this occur with the latest SF build?

**Comment by Sir-Will** [comment] 2018-07-24 10:27
Yes, this is still an issue with 3342.

**Comment by phit** [comment] 2019-02-17 23:09
still an issue with spongeforge-1.12.2-2768-7.1.6-RC3586, extrautils2-1.12-1.9.8

**Comment by Zidane** [comment] 2019-06-21 18:50
Confirmed still a bug on 3800+

**Comment by clienthax** [comment] 2019-08-07 17:41
There seems to be a couple of issues with this.

Firstly, these seem to be handled by a master Entity which is located above the chunk, at y512, obviously this breaks some assumptions about when entities should be ticked in activation ranges
adding the following to the sponge entity-activation-range - mods config allows the processing to work properly
```
            extrautils2 {
                defaults {
                    misc=16
                }
                # If 'false', entity activation rules for this mod will be ignored and always tick.
                enabled=true
                entities {
                    chunkdata=0
                }
            }
```

It also looks like sponge is filtering out any entities above 256 when loading chunks, which is why they all disappear when the chunk loads.
https://github.com/SpongePowered/SpongeCommon/blob/00f5e56506b1bf9f52489a453443c215473a0534/src/main/java/org/spongepowered/common/mixin/core/util/math/Vec3iMixin.java

**Comment by clienthax** [comment] 2019-08-07 18:51
Fixed by the above PR and config change.

**Closed as completed** 2019-08-08 03:21 UTC
Labels: type: mod incompatibility, version: 1.12, status: pr pending
