### ISSUE TITLE
Mixin Text class loader issue

### ISSUE THREAD

**Issue by DruidIdrur** [SpongePowered/SpongeForge#2818] opened 2019-06-14 05:36 UTC
**I am currently running**
Pack : Omnifactory V. 1.0.5

- SpongeForge version: spongeforge-1.12.2-2825-7.1.6
have tried latest dev build : spongeforge-1.12.2-2838-7.1.7-RC3777
Problem persists even with latest and stable build
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: Java 8
- Operating System: Linux

- Plugins/Mods:

**Issue Description**
Having an issue with Mixin.Text class file

[debug.log](https://github.com/SpongePowered/SpongeForge/files/3289168/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3289169/latest.log)

**Comment by gabizou** [comment] 2019-06-14 07:06
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2798.

**Closed as completed by gabizou** 2019-06-14 07:06 UTC
Labels: resolution: duplicate, type: mod incompatibility, version: 1.12
