### ISSUE TITLE
IC2 Scrap Boxs

### ISSUE THREAD

**Issue by bookerthegeek** [SpongePowered/SpongeForge#1230] opened 2017-01-28 19:55 UTC
[IC2 Bug Tracker Link](http://bt.industrial-craft.net/view.php?id=2073)
Likely similar to https://github.com/SpongePowered/SpongeForge/issues/1168
Versions:
- Sponge: spongeforge-1.10.2-2202-5.1.0-BETA-2019.jar
- Forge: forge-1.10.2-12.18.3.2185-universal.jar
- ModVersion: Industrialcraft-2-2.6.142-ex110.jar

What Happens:
- Item is not used on use

What is Expected to happen:
- Item is removed from inventory on use

Overview of Issue:
- Scrap boxes should be consumed upon use, providing one item from a list at random. Instead it provides the item and is not consumed, allowing a player to create an infinite number of items.

More information:
Reproducible on a DireWolf 20 Server running Sponge where issue was discovered.
Reproducible on a DireWolf 20 Single Player instance running Sponge.
Reproducible on a Single Player instance running Sponge and Mod only.
Not reproducible on DireWolf 20 server running only Forge
Not reproducible on Single Player instance running Forge and Mod only.

**Comment by Aaron1011** [comment] 2017-01-28 19:58
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1066.

**Closed as completed by Aaron1011** 2017-01-28 19:58 UTC
Labels: resolution: duplicate

**Comment by bookerthegeek** [comment] 2017-01-31 15:32
Thank you! Did not see that one for some reason.
