### ISSUE TITLE
GalactiCraft world teleportation

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2543] opened 2019-01-01 08:52 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.4
- Forge version: 1.12.2-forge1.12.2-14.23.5.2796, 1.12.2-forge1.12.2-14.23.5.2750, 1.12.2-forge1.12.2-14.23.5.2781
- Java version: 1.8.0_162 x64
- Operating System: Linux(Server), Windows7(Client) - x64

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Applied Energistics 2, Aquaculture, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, BuildCraft, BuildCraft Lib, CoFH Core, CoFH World, CodeChicken Lib, CustomNPCs, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Extra Cells 2, Extra Planets, Forestry, Galacticraft Core, Galacticraft Planets, Immersive Engineering, Immersive Petroleum, Immersive Tech, Iron Chest, Just Enough Items, MJRLegendsLib, Micdoodle8 Core, More Bees, More Planets, NuclearCraft, OMLib, Open Modular Turrets, OpenComputers, OpenComputers (Core), OpenGlasses, Pam's HarvestCraft, Reborn Core, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, Tech Reborn, Tech Reborn Mod Compatibility, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Treecapitator, UniDict, Waila, WanionLib, What Are We Looking At, WorldEdit, bspkrsCore ("/sponge mods" results);
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Boop, CatClearLag, ClaimTweaks, CommandUtils, GriefPrevention, Holograms, ItemChat, LuckPerms, MMCRestrict, Nucleus, PacketGate, PlaceholderAPI, Plan, Title Broadcaster, VoxelSniper("/sponge plugins" results).

**Issue Description**
The problem is the lack of possibility of teleportation to the worlds from GalactiCraft through /dimensiontp command or through a flight on a rocket. As soon as the galactic map GUI opens, I see something like the following: https://i.gyazo.com/14def5b30cb014bb809a83c35d2923ab.mp4 (It's no my link, but it accurately reflects the essence of my problem.)
Versions of GalactiCraft mod/addons:
ExtraPlanets-1.12.2-0.4.6
GalacticraftCore-1.12.2-4.0.1.181
Galacticraft-Planets-1.12.2-4.0.1.181
More-Planets-1.12.2-2.0.17-GC181
The error is triggered exclusively on the server with SpongeForge, usual Forge work correctly. Any plugin or mod does not affect the error, everything is tested separately and together several times. I found quite a few references to this topic, but each one has distinctive logs.

P.S. - Sorry for my English

- Logs:
Client - https://gist.github.com/SSKirillSS/d05f096591fc08bf072449eb11b38039
Server(Contains nothing interesting) - https://gist.github.com/SSKirillSS/f4913d4ea2f86a15ea9f93c7b7e408ed

**Comment by phit** [comment] 2019-01-01 15:04
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2499

**Closed as completed by phit** 2019-01-01 15:04 UTC
Labels: resolution: duplicate, version: 1.12
