### ISSUE TITLE
Sponge + Immersive Engineering Duplication Bug

### ISSUE THREAD

**Issue by focamacho** [SpongePowered/SpongeForge#2728] opened 2019-05-02 21:05 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6-RC3690
- Forge version: 1.12.2 - 14.23.5.2836
- Java version: OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
- Operating System: Ubuntu 18.04

- Plugins/Mods:
  - **Plugins (29)**: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActionBroadcaster, BetterChunkLoader, BetterKits, Buycraft, CarrotShop, CatClearLag, EconomyLite, FlexibleLogin, GWMCrates, GWMLibrary, GriefPrevention, Holograms, LangSwitch, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, Mega Menus, Nucleus, PixelVip, RankUpper, ServerListPlus, TabManager, UltimateChat, VillagerShops
  - **Mods (110)**: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AE2 Wireless Terminals (AE2WTLib), Actually Additions, Advanced Generators, AetherisMC Items, Alternating Flux, Applied Energistics 2, AutoRegLib, Avaritia, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Questing, BetterChunkLoader Forge Lib, Botania, Brandon's Core, Chameleon, Chickens, Chisel, Cloche Call, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Cyclic, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender IO endergy, EnderCore, EnderStorage, Extended Crafting, Extra Utilities 2, Fast Leaf Decay, Flux Networks, Guide-API, Immersive Cables, Immersive Engineering, Immersive Posts, Industrial Foregoing, Item Filters, Just Enough Items, MCMultiPart, MTLib, Mantle, McJtyLib, Moar Tinkers, Mod Tweaker, More Chickens, Morpheus, Natura, Nature's Aura, OpenBlocks, OpenModsLib, OpenModsLib Core, Patchouli, Placebo, PlusTiC, Psi, RFTools, Reborn Core, Redstone Flux, Rocky Core, Roost, Rustic, Scaling Health, Shadowfacts' Forgelin, Silent Lib, Simply Jetpacks 2, Solar Flux Reborn, SonarCore, SpongeForge, Standard Expansion, Storage Drawers, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, Tesslocator, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, VanillaFix, WanionLib, Wireless Crafting Terminal 2, Woot, WorldEdit, WrapUp, XL Food Mod, p455w0rd's Library

**Issue Description**
 When you break a Garden Cloche(Immersive Engineering) using a tool which breaks several blocks at a time, the garden cloche is duplicated. It happens with another blocks too.
 See the video for more info: https://www.youtube.com/watch?v=886poG1nHfQ

**Comment by gabizou** [comment] 2019-05-02 21:36
~~That's a feature!~~

I see what's potentially going on, is it possible to just reproduce with Immersive Engineering, and `-Dsponge.shouldFireAll=true`?

**Comment by focamacho** [comment] 2019-05-03 00:13
I tested it on my computer and for some reason, when only sponge and immersive engineering are installed on the server, I can not break any blocks. I break, but the block drops nothing. I can't get the drops from wood, dirt, stone...
Here's the log(with errors): https://gist.github.com/Focamacho/83c9ded134fad533404c210e3b29b4e4

**Comment by gabizou** [comment] 2019-05-03 00:57
Just pushed a commit that might help the issue. In the server, is there any exception spam from breaking blocks like during the video?


> I tested it on my computer and for some reason, when only sponge and immersive engineering are installed on the server, I can not break any blocks. I break, but the block drops nothing. I can't get the drops from wood, dirt, stone...
> Here's the log(with errors): https://gist.github.com/Focamacho/83c9ded134fad533404c210e3b29b4e4

7.1.6-RC3691 should fix the log from errors you're getting

**Comment by focamacho** [comment] 2019-05-03 01:43
No exceptions spam from breaking blocks in the server. And I can't replicate the duplication bug with only Immersive Engineering & Sponge.

**Comment by focamacho** [comment] 2019-05-03 01:55
I found the problem: Nucleus. But I do not know why this happens.

**Comment by dualspiral** [comment] 2019-05-03 08:59
> I found the problem: Nucleus

[I suspect that because Nucleus' protection module listens to the `ChangeBlockEvent`](https://github.com/NucleusPowered/Nucleus/blob/sponge-api/7/src/main/java/io/github/nucleuspowered/nucleus/modules/protection/listeners/MobProtectionListener.java#L29), it's activating that branch of the phase tracker and causing the issues.

Did you try, as @gabizou asked, with only Sponge, Immersive Engineering, **and** adding `-Dsponge.shouldFireAll=true` to the `java` command line (before the `-jar` flag)?

**Comment by focamacho** [comment] 2019-05-03 12:57
With only Sponge & Immersive Engineering and `-Dsponge.shouldFireAll=true`, I can replicate the duplication bug.

**Comment by gabizou** [comment] 2019-05-03 15:35
Which item are you using to replicate? I don't know enough about IE to know which items will break multiple blocks at once.

**Comment by focamacho** [comment] 2019-05-03 16:02
Mining Drill break multiple blocks at once.

**Comment by gabizou** [comment] 2019-05-10 20:32
Hmm, might've been unintentionally fixed in a few builds since a week ago. Tried to replicate the issue locally and couldn't get it to dupe with a mining drill and cloche.

**Comment by focamacho** [comment] 2019-05-10 21:02
I can't reply the bug using Sponge - 1.12.2-2825-7.1.6-RC3701. Everything works fine now.

**Closed as completed** 2019-05-10 21:02 UTC
Labels: type: bug, version: 1.12, status: waiting for reply
