### ISSUE TITLE
Cannot set keepInventory for nether

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeForge#399] opened 2015-11-03 12:08 UTC
I set *gamerule keepInventory true* for the overworld, but found it was *false* in the nether. I gave the command in the nether too, but it still won't work. Not sure if I can set gamerules for other than the default world. Default Forge and Minecraft behaviour sets gamerules for all worlds at once. 
Tested with Forge 1543, SpongeForge 776, and no mods or plugins.

**Comment by bloodmc** [comment] 2015-11-03 15:01
@Inscrutable In order to support multiworld functionality, Sponge uses a seperate save handler per world unlike Forge and Vanilla. What this means is, settings such as gamerule are per-world. Now the issue with it not working is a bug and I'll look into fixing it soon.

**Comment by wizjany** [comment] 2015-11-03 15:41
er, are we talking about the command in specific or gamerules in general? because iirc they are per-world.

**Comment by JBYoshi** [comment] 2015-11-03 16:10
@wizjany Game rules are per-world in vanilla. However, Sponge adds support for having multiple worlds with separate settings. It doesn't know which worlds should be linked together; all it knows is that there's a root dimension (corresponding to the vanilla overworld) and various other dimensions; some are the nether and End, and some are custom worlds.

**Comment by wizjany** [comment] 2015-11-03 17:13
are you saying that setting a gamerule for (eg) the vanilla overworld should also change the gamerule for the vanilla nether and end? it seems to me that the only issue at hand here is that the vanilla command doesn't have a parameter for which world to affect.

**Comment by JBYoshi** [comment] 2015-11-03 17:24
@wizjany 
> are you saying that setting a gamerule for (eg) the vanilla overworld should also change the gamerule for the vanilla nether and end?

Yes.
> it seems to me that the only issue at hand here is that the vanilla command doesn't have a parameter for which world to affect.

The reason it doesn't have a parameter for the world is because in vanilla, all worlds share game rules.

**Comment by ryantheleach** [comment] 2015-11-05 15:19
I think previous CraftBukkit behaviour was to use the world the player who typed the command as the world to set and seperate gamerules per world. (if it was vanilla it isn't in 1.8.8)

Vanilla 1.8.8 behaviour is to set it on the overworld, even if in the nether.
Tested just then,

1. "/gamerule asdf false" in the overworld
2. checking it was false with "/gamerule asdf" in the overworld. 
3. travelling to the nether, 
4. "/gamerule asdf" still false, 
5. "/gamerule asdf true" 
6. "/gamerule asdf" shows true. 
7. travel to overworld. 
8. "/gamerule asdf" shows true.

**Comment by ryantheleach** [comment] 2015-11-05 15:21
This further enforces my belief that default world settings like this should be split into groups of worlds. 

Ideally spawn data, inventory data, gamerule data, statistics, achievements, scoreboards, maps, would also be separated.

But it's a whole lot of work.

**Comment by JBYoshi** [comment] 2015-11-05 19:12
The easy way to share data between worlds is to create an instance of `WorldServerMulti` instead of `WorldServer`, passing in the world that holds the shared data. The problem is figuring out which worlds should use `WorldServerMulti` and which worlds hold their shared data. I'd make a PR for this, but it would probably affect both SpongeForge and SpongeVanilla, and I have problems with the combination of Eclipse, the Gradle plugin, and symlinked subprojects.

**Comment by Zidane** [comment] 2015-11-05 21:05
@JBYoshi 

We intentionally removed WorldServerMulti for the sole purpose of having full control over how data is shared (as well as separating our save handlers).

**Comment by bloodmc** [comment] 2015-11-18 01:46
Closing as this is not a bug but intended functionality.

**Closed by bloodmc** 2015-11-18 01:46 UTC
Labels: bug
