### ISSUE TITLE
Chunk problem

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#2984] opened 2019-09-23 10:51 UTC
I have broken chunks when all entitys are invinsible. Sponge 2768 hasn’t this bug. But new versions of sponge have it. Can some one help me?
https://www.youtube.com/watch?v=k3NfqT9Q7Jk
Sponge: spongeforge-1.12.2-2825-7.1.6
Mods and plugins:
![image](https://user-images.githubusercontent.com/7419546/65420211-3eba9d00-de09-11e9-991d-15e95e41c4fb.png)

**Comment by kasdo** [comment] 2019-09-23 10:52
https://forums.spongepowered.org/t/chunk-problem-1-12-2/33482

**Comment by gabizou** [comment] 2019-09-23 11:21
Re-test with a newer version. 7.1.6 is a very old build now, and we're putting out a new recommended build very soon. 1.12.2-2838-7.1.7-RC3924 is new enough that this shouldn't be happening (also note, I see you have LagGoggles, you'll need to update that too, along with GriefPrevention).

**Comment by bigenergy** [comment] 2019-09-24 19:32
This is reproducible on version 3902 and higher.

![image](https://user-images.githubusercontent.com/17977139/65544025-14f19b00-df1b-11e9-86a5-e610dbc75e75.png)
![image](https://user-images.githubusercontent.com/17977139/65544051-233fb700-df1b-11e9-8b96-6261cde24436.png)

**Comment by gabizou** [comment] 2019-09-24 22:02
Please reproduce the issue with build RC3924 or newer, and list steps to reproduce the issue **from a fresh started server with minimal mods/plugins**. You have quite a few things that have a lot of steps to set up, but nothing so far that really points to any specific mod/plugin/interaction except chunk boundaries.

**Comment by caunt** [comment] 2019-09-25 12:18
We have the same bugs on new builds

Randomly entities (not just players) disappears. Players are visually frozen/or have their duplicates. Etc.

That reproduces randomly, even if server hasn't any plugins. Not sure about mods.

**Comment by clienthax** [comment] 2019-09-27 04:10
Seems to be the same as https://github.com/SpongePowered/SpongeForge/issues/2764 ?

**Comment by PhoenixTheSage** [comment] 2019-09-27 07:58
Yes, it's the same issue, and still on RC3924. We are getting the duplicates as well.

One interesting way of seeing this occur without waiting to find affected mobs is if you use the glider from OpenBlocks to fly around the glider will "vanish" just like mobs and players do, so you can see just which chunks this occurs inside, but I suppose you could do this with a horse although less easily.

**Comment by kasdo** [comment] 2019-09-30 12:39
I upgraded my sponge to RC3924 and forge to 2838. Upgraded my griefprevention and laggoggless to the last versions. And its not help me. I have dublicated players and vanished NPCs (entity).

**Comment by kasdo** [comment] 2019-09-30 13:06
Woah! Hot news! I deleted GriefPrevention and this bug is gone (but Im not sure). What I can do with this? I cant delete this plugins... I want to remind, I havent this bug on sponge 2768.

**Comment by caunt** [comment] 2019-09-30 13:41
Thats not GP trouble cuz we are not using it and have the same bug

**Comment by kasdo** [comment] 2019-09-30 13:45
> Thats not GP trouble cuz we are not using it and have the same bug

send me your plugins and mods, please.

**Comment by caunt** [comment] 2019-09-30 13:49
> > Thats not GP trouble cuz we are not using it and have the same bug
> 
> send me your plugins and mods, please.

```
> sponge plugins
[13:47:29] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (13): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, LuckPerms, Nucleus, Nucleus API, ProjectCore, ProjectPortals-7.x, ShabbyHolograms, SkyClaims, WorldEdit, WorldGuard

> sponge mods
[13:47:59] [Server thread/INFO] [minecraft/DedicatedServer]: Mods (114): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Lib, Alchemistry, AppleCore, AppleSkin, ArchitectureCraft, Athenaeum, Atum 2, B.A.S.E, BNBGamingLib, Bad Wither No Cookie! Reloaded, Barrels, Drums, Storage & More, Baubles, Better Builder's Wands, Bookshelf, Botania, Bow Infinity Fix, Building Gadgets, Calculator, Cannibalism, Carry On, Chameleon, Chisels & Bits, Clumps, ComPatchedStorage, Combustive Fishing, CommonCapabilities, CompactStorage, ContentTweaker, CraftTweaker JEI Support, CraftTweaker2, Crafting Station, Crafting Tweaks, CropDusting, Cyclops Core, Dark Utilities, Dropt, EmberRoot Zoo, Embers Rekindled, Embersified, EvilCraft, EvilCraft-Compat, FTB Library, FTB Quests, Fast Leaf Decay, Fence Jumper, Flopper, FoamFix, FoamFixCore, Forbidden & Arcanus, FxControl, Global GameRules, Harvest, Hearth Well, InControl, InWorldCrafting, InitialInventory, Inspirations, Integrated Dynamics, Integrated Terminals, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTerminals-Compat, IntegratedTunnels-Compat, Inventory Tweaks, Item Filters, JourneyMap, Just Enough Items, LootTweaker, MTLib, Mantle, MobAmputation, Mod Tweaker, More Charcoal, Nether Chest, OreExcavation, Patchouli, Placebo, Prodigy Tech, Reborn Core, Redstone Gauges and Switches, SeedDrop, Shadowfacts' Forgelin, Simple Flax, Simple Trophies, SonarCore, Soulus, Speedy Hoppers, Speedy Ladders, Spice of Life: Carrot Edition, SpongeForge, Stone Chest, Storage Drawers, Straw Golem, Structured Crafting, TelePastries, Tetra, The One Probe, Topography, Trample Stopper, TrashSlot, Unique Crops, Useful Nullifiers, Vanilla Food Pantry, Volcano Block Tweaks, VoltzEngine Fluids module, Wooden Bucket, XenCraft, iChunUtil
```

**Comment by kasdo** [comment] 2019-09-30 13:52
> > > Thats not GP trouble cuz we are not using it and have the same bug
> > 
> > 
> > send me your plugins and mods, please.
> 
> ```
> > sponge plugins
> [13:47:29] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (13): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, LuckPerms, Nucleus, Nucleus API, ProjectCore, ProjectPortals-7.x, ShabbyHolograms, SkyClaims, WorldEdit, WorldGuard
> 
> > sponge mods
> [13:47:59] [Server thread/INFO] [minecraft/DedicatedServer]: Mods (114): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Lib, Alchemistry, AppleCore, AppleSkin, ArchitectureCraft, Athenaeum, Atum 2, B.A.S.E, BNBGamingLib, Bad Wither No Cookie! Reloaded, Barrels, Drums, Storage & More, Baubles, Better Builder's Wands, Bookshelf, Botania, Bow Infinity Fix, Building Gadgets, Calculator, Cannibalism, Carry On, Chameleon, Chisels & Bits, Clumps, ComPatchedStorage, Combustive Fishing, CommonCapabilities, CompactStorage, ContentTweaker, CraftTweaker JEI Support, CraftTweaker2, Crafting Station, Crafting Tweaks, CropDusting, Cyclops Core, Dark Utilities, Dropt, EmberRoot Zoo, Embers Rekindled, Embersified, EvilCraft, EvilCraft-Compat, FTB Library, FTB Quests, Fast Leaf Decay, Fence Jumper, Flopper, FoamFix, FoamFixCore, Forbidden & Arcanus, FxControl, Global GameRules, Harvest, Hearth Well, InControl, InWorldCrafting, InitialInventory, Inspirations, Integrated Dynamics, Integrated Terminals, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTerminals-Compat, IntegratedTunnels-Compat, Inventory Tweaks, Item Filters, JourneyMap, Just Enough Items, LootTweaker, MTLib, Mantle, MobAmputation, Mod Tweaker, More Charcoal, Nether Chest, OreExcavation, Patchouli, Placebo, Prodigy Tech, Reborn Core, Redstone Gauges and Switches, SeedDrop, Shadowfacts' Forgelin, Simple Flax, Simple Trophies, SonarCore, Soulus, Speedy Hoppers, Speedy Ladders, Spice of Life: Carrot Edition, SpongeForge, Stone Chest, Storage Drawers, Straw Golem, Structured Crafting, TelePastries, Tetra, The One Probe, Topography, Trample Stopper, TrashSlot, Unique Crops, Useful Nullifiers, Vanilla Food Pantry, Volcano Block Tweaks, VoltzEngine Fluids module, Wooden Bucket, XenCraft, iChunUtil
> ```

Wow. How did you install worldguard? He's not working on sponge 1.12.2. And how u install foamfix? He's not working too..

So... this bug can be from PC, PP, Nucleus, LuckPerm.

**Comment by caunt** [comment] 2019-09-30 13:55
> Wow. How did you install worldguard? He's not working on sponge 1.12.2. And how u install foamfix? He's not working too..

We ported WG to sponge :P

**Comment by kasdo** [comment] 2019-09-30 13:59
> > Wow. How did you install worldguard? He's not working on sponge 1.12.2. And how u install foamfix? He's not working too..
> 
> We ported WG to sponge :P

maybe we can have a deal?

**Comment by caunt** [comment] 2019-09-30 14:00
> > > Wow. How did you install worldguard? He's not working on sponge 1.12.2. And how u install foamfix? He's not working too..
> > 
> > 
> > We ported WG to sponge :P
> 
> maybe we can have a deal?

I think we are going to make it public after a few months testing on our servers

**Comment by kasdo** [comment] 2019-09-30 14:02
> > > > Wow. How did you install worldguard? He's not working on sponge 1.12.2. And how u install foamfix? He's not working too..
> > > 
> > > 
> > > We ported WG to sponge :P
> > 
> > 
> > maybe we can have a deal?
> 
> I think we are going to make it public after a few months testing on our servers

I deleted GP and now we cant find problem regions...

**Comment by ImMorpheus** [comment] 2019-10-11 20:48
@kasdo Please, try to reproduce the issue with 1.12.2-2838-7.1.7-RC3928

**Comment by ImMorpheus** [comment] 2019-10-19 17:52
gonna close this and I assume this was fixed, if this is still an issue please reply and I'll reopen

**Closed as completed by ImMorpheus** 2019-10-19 17:52 UTC
Labels: type: bug, status: more information needed, version: 1.12
