### ISSUE TITLE
AoE  - Scrap Box Dupe

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1768] opened 2017-09-10 14:23 UTC
Hi all, having a issue on our Age of Engineering server, when you right click a scrap box its meant to drop the item and remove the scrap box from your inventory, well thats not the case, its dropping the item but keeping the box in your inv letting you get lots of items over and over.

Doesn't happen on Single Player.

SpongeForge
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2281-5.2.0-BETA-2610
Minecraft Forge: 12.18.3.2422

**Comment by Aaron1011** [comment] 2017-09-10 14:29
Duplicate of #1066

**Closed as completed by Aaron1011** 2017-09-10 14:29 UTC
