### ISSUE TITLE
v1 Schematics not upgrading properly

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2785] opened 2019-05-31 14:07 UTC
**I am currently running**

- SpongeForge version: 3740
- Forge version: 2831
- Java version: 8
- Operating System: Debian 9

- Plugins:
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Aliases, AntiWDL, AurionsVoteListener, AutoBroadcaster, CatClearLag, Discord Bridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MultiChatSponge, NuVotifier, Nucleus, Player Glow, PlayerShopsRPG, PwnFilter, RankUpper, SkyClaims

- Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BD Lib, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, DragonMurder, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, LagGoggles, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, Mekanism: Generators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PlaneFix, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XC Patch, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

**Issue Description**

Same Issue as before since the schematic changes update.

Slabs and chiseled blocks are not being generated using skyclaim schematics, probably affects any non full blocks or blocks with NBT data.

This:
![SF4TheHut](https://user-images.githubusercontent.com/1526195/58710798-153ab900-83b5-11e9-9b3c-ef4281e66905.png)

Is generating as:
![brokenschematic](https://user-images.githubusercontent.com/1526195/58710762-f5a39080-83b4-11e9-9f61-172d14033e28.png)

I know this is a bit cheeky :p but any chance we could have the schematic changes made in 3697 reverted until these new schematic changes are a bit more stable? pre 3697 they worked perfectly!

No log errors this time, it just doesn't copy the schematic data properly as seen in the pics, worldedit schematics on the other hand work perfectly.
I also noticed the lava tank on the island is not full (it is in the schematic), so it seems tank contents are not being saved either.

Interestingly, when it rains the splash effects hit the missing blocks like they are just invisible. But you can walk right through them regardless, so something odd is happening.

Probably related to #2761

**Comment by gabizou** [comment] 2019-05-31 18:08
Have a schematic with a single mod that i can test against? The thing with schematics is that because they're *versioned* the problem isn't so much how they're applied, it's doing the upgrade, which for some reason broke as a process.... Somewhere down the line, I'll be making a unit test for schematics so v1 can be read and applied and verified that it'll produce the same result with a v2 schematic sans biomes and entities, but in order to do that, I do need some sample schematic to bundle with the unit test.


> I know this is a bit cheeky :p but any chance we could have the schematic changes made in 3697 reverted until these new schematic changes are a bit more stable? pre 3697 they worked perfectly!

No, that's not how any of this works... To revert the schematic changes requires reverting API support for the new Schematic format version... There's a big difference between resolving TileEntity data and not resolving them. These cases are the issue where the tile entity data is awkwardly being pruned, missed, or in some way lost in translation.

**Comment by Yorkforce** [comment] 2019-05-31 22:14
This is occurring on our Sky Factory 4.0.5 servers using [Skyclaims 0.28.0-S7.1](https://github.com/DevOnTheRocks/SkyClaims/releases/tag/beta-28-pr1)

This is the schematic for the above island (remove the .zip part on the end):
[thehut.schematic.zip](https://github.com/SpongePowered/SpongeForge/files/3243019/thehut.schematic.zip)

Extra info: This schematic was re-created from a worldedit schematic within the skyclaims plugin, so it should essentially be a freshly created schematic on SF3470

I understand with difficulties in reverting, its just we use schematics as part of our server ranks, so its quite important we get them working right else we don't get much funding, which right now is a big challenge just to cover costs. I fully get that this is not your priority or concern just anything that could help to get it working right would be great.
I know I personally appreciate everything you folks do at spongeforge, we wouldn't have servers at all if it wasn't for spongeforge so don't take anything I say as a criticism or a complaint, it's far from it.

**Closed as completed** 2019-06-02 20:27 UTC
Labels: type: bug
