### ISSUE TITLE
[1.10.2] EnderIO's Broken Spawner not dropping.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#857] opened 2016-08-23 18:08 UTC
Using SpongeForge and EnderIO results in Broken Spawner not dropping. Works fine only with Forge.

Steps:

1.- Place a vanilla Mob Spawner (ID: 52)
2.- Break it using a pickaxe.
3.- It should drop a Broken Spawner, but it doesn't.

Versions: Latest SpongeForge, EnderIO and EnderCore.

EDIT: Relevant code: https://github.com/SleepyTrousers/EnderIO/blob/c70377e3e3325f701630d9cd46b70257a41fcf2f/src/main/java/crazypants/enderio/machine/spawner/BlockPoweredSpawner.java#L145

**Comment by bloodmc** [comment] 2016-08-23 20:40
@LuxusDarkangel  Did you test without any plugins?

**Comment by gabizou** [comment] 2016-08-23 23:37
I'm pretty sure I have an understanding what's going on. I'll need to test my theory but it more than likely has to do with harvest events being misfired for forge mods.

**Comment by LuxusDarkangel** [comment] 2016-08-24 02:56
I know you're already looking into It, but yeah @bloodmc, I forgot to say It, but I always test this kind lf issues without plugins or other mods not directly related.

**Comment by Jasems** [comment] 2016-09-02 15:15
If it helps in fixing, I do notice the broken spawner drop in the air for a split second, then vanish.

**Comment by viper2g1** [comment] 2016-09-04 14:45
I can confirm this happens, I'm not sure if you need any logs to fix it at this point but I'd be happy to provide some if you do.

**Comment by dogboy21** [comment] 2016-10-04 18:05
It looks like the tileentity for the spawner is being removed before the BreakBlock event is being fired

**Comment by Aaron1011** [comment] 2016-10-04 21:43
@dogboy21: You're absolutely correct. This issue is due to Sponge's capturing system, which fires a bulk event after all of the changes have been performed for a particular action (e.g. breaking a block).

@gabizou: What do you think is the best way to deal with this?

**Comment by Vauxite** [comment] 2016-10-18 14:53
Confirmed the bug running FTB Hermitpack 1.0.1 with spongeforge
[16:53:18] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: bleeding-SNAPSHOT-b550bfa
    SpongeForge: 1.10.2-2098-bleeding-BETA-0
    Minecraft Forge: 12.18.2.2098

**Comment by bloodmc** [comment] 2016-10-18 15:00
@Vauxite Test using LATEST SF build.

**Comment by Vauxite** [comment] 2016-10-18 15:28
@bloodmc Does that include the tps fix in bleeding-beta?

**Comment by bloodmc** [comment] 2016-10-18 15:29
@Vauxite yes, my changes were merged.

**Comment by dogboy21** [comment] 2016-10-18 16:11
Broken Spawners still don't drop with the latest SF build

**Comment by Vauxite** [comment] 2016-10-18 17:24
Didn't fix the issue. Spawners still give me Spawner Shard when broken.

**Comment by gabizou** [comment] 2016-10-18 17:32
@bloodmc this is back to the HarvestDrops event not being fired correctly.

**Comment by ProsperCraft** [comment] 2016-10-24 03:12
Dragon's breath from the roots mod is also not dropping from the ender dragon

**Comment by Vauxite** [comment] 2016-10-27 17:38
Still a problem in:
Minecraft 1.10.2
spongeAPI: 6.0.0-SNAPSHOT-cebc736
SpongeForge 1.10.2-2107-6.0+.0-BETA-1836
Minecraftforge 12.18.2.2107

**Comment by lilmoefow** [comment] 2016-10-27 20:34
forge-1.10.2-12.18.2.2107-universal.jar
spongeforge-1.10.2-2107-6.0.0-BETA-1846.jar
EnderCore-1.10.2-0.4.1.56-beta.jar
EnderIO-1.10.2-3.0.1.120_beta.jar

Yeup still an issue in these versions aswell,  If i can provide anything else to help just let me know.

**Comment by ProsperCraft** [comment] 2016-10-28 23:14
Guardian scales do not drop from elder guardians (or normal ones) in multiplayer, but in single player they drop 3 per elder guardian and 1 for each few normal guardians. https://www.youtube.com/watch?v=wLANjiEyios https://www.youtube.com/watch?v=7sQiWVCCrqE

Versions-  
SpongeAPI: 6.0.0-SNAPSHOT-f247c80
SpongeForge: 1.10.2-2107-6.0.0-BETA-1852
Minecraft Forge: 12.18.2.2114

**Comment by ProsperCraft** [comment] 2016-10-30 02:16
Still an issue with 

```
SpongeAPI: 6.0.0-SNAPSHOT-f247c80
SpongeForge: 1.10.2-2107-6.0.0-BETA-1856
Minecraft Forge: 12.18.2.2114
```

**Comment by ProsperCraft** [comment] 2016-11-01 18:40
Also Draconic Evolution hearts don't drop when killing the ender dragon which stops progress in the draconic evolution mod.

```
SpongeAPI: 6.0.0-SNAPSHOT-f247c80
SpongeForge: 1.10.2-2107-6.0.0-BETA-1862
Minecraft Forge: 12.18.2.2116
```

**Closed** 2016-11-05 19:08 UTC
Labels: 1.10, needs testing
