### ISSUE TITLE
Spawn rates not taking affect

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2342] opened 2018-07-23 23:36 UTC
**I am currently running**

- SpongeForge version: 3338
- Forge version: 2705
- Java version: 1.8 update 171
- Operating System: Windows server 2012 r2

- Plugins/Mods: LuckPerms, Nucleus and Griefprevention

**Issue Description**

Sponge config settings to change mob spawn rates do not work in individual worlds when set in their configs.

**Comment by ChampTheLegend** [comment] 2018-07-23 23:39
I am having the same problem, same Forge Version, however Sponge 3206.

**Comment by bloodmc** [comment] 2018-07-24 02:17
Spawn rates are not _**exact**_ limits. They are factored in with amount of spawnable chunks available, view distance and mob spawn range to get the actual limit. Upload your configs if you are still having issues.

**Comment by Shybella** [comment] 2018-07-24 02:25
`Sponge config settings to change mob spawn rates do not work in individual worlds when set in their configs.` has nothing to do with spawn limits or rates. 

global.conf rates are overriding other worlds.

**Comment by ryantheleach** [comment] 2018-07-24 02:42
@Shybella Things like this can be hard to judge at first glance without seeing evidence in a post.

The more work that goes into a ticket, immensely helps devs reproduce errors and fix them.

If you could provide 

1. Your testing methodology of how you are counting the mob spawns.
2. the results.
3. the configuration.
4. the details on which worlds this affects, and whether they are mod loaded, vanilla, or custom loaded worlds.

That would help a ton.

It also helps the issue managers Triage the tickets in order of severity, and concentrate on what hurts server administrators the most.

Without evidence, we are essentially flying blind, and your tickets will be de-prioritized unless someone on the team can confirm it or has seen something similar themselves.

**Comment by Shybella** [comment] 2018-07-24 02:45
It's super simple. global.conf rates are overriding other dimension configs for their own set rate.

**Comment by bloodmc** [comment] 2018-07-24 02:55
It is definitely working per world as I just tested. How are you confirming that the rates you are setting are not working? We provide no such information in game. Do as I said and upload your configs or this will be closed.

**Comment by Shybella** [comment] 2018-07-24 02:58
I'm using a external mod to handle spawn rates. If @ChampTheLegend wants to do that he can.

**Comment by bloodmc** [comment] 2018-07-24 03:04
Well that explains why it isn’t working. Sponge config is to modify spawn limits for vanilla’s spawner. If the mod is trying to do the same thing then it is not going to work unless it replaces the spawner entirely.

**Comment by Shybella** [comment] 2018-07-24 03:06
This was happening before I installed it. I installed it because you ignored my multiple requests about it in Sponge testing. I only opened this issue because of @ChampTheLegend repeating the same exact issue in the Sponge discord.

**Comment by ChampTheLegend** [comment] 2018-07-24 03:11
I’m using the global.conf, no matter how low I adjust it the same amount of mobs always seem to spawn in-game

**Comment by bloodmc** [comment] 2018-07-24 03:13
Provide what ryantheleach requested or this will be closed.

**Comment by ChampTheLegend** [comment] 2018-07-24 03:14
I test this by editing the config and re-logging in - always about ~80 mobs spawn around me at night. I will post my global.conf momentarily.

**Comment by ChampTheLegend** [comment] 2018-07-24 03:19
https://pastebin.com/6rXTH3y5

**Comment by bloodmc** [comment] 2018-07-24 03:27
Are you killing all mobs and allowing them to respawn? The spawn limits do not affect "chunk spawns".

**Comment by ChampTheLegend** [comment] 2018-07-24 03:31
Yes, I'm killing them and allowing them to respawn, but no matter how I adjust the config the number stays stagnant at always about ~80 mobs per person. What exactly does spawn rates do if not adjust the amount of mobs spawning?

**Comment by bloodmc** [comment] 2018-07-24 03:34
It does affect spawning, just not chunk spawns. Chunk spawns are when chunks get generated. I'll look into non-chunk spawns.

**Comment by bloodmc** [comment] 2018-07-24 03:40
With a setting of 15
```
[23:39:26] [Server thread/INFO] [STDOUT]: [net.minecraft.world.WorldEntitySpawner:findChunksForSpawning:698]: entityCount = 16, maxCount = 15, chunks = 81, div = 81, type = MONSTER
```
With a setting of 200
```
[23:39:08] [Server thread/INFO] [STDOUT]: [net.minecraft.world.WorldEntitySpawner:findChunksForSpawning:698]: entityCount = 201, maxCount = 200, chunks = 81, div = 81, type = MONSTER
```

Working as intended. Make sure you are testing with ONLY SF and no other mods.

**Comment by ChampTheLegend** [comment] 2018-07-24 04:25
That seems to be the reason - I tested SF without other mods, and works as intended. Must be another mod overriding it, apologies for making you test something that was already working.

**Comment by bloodmc** [comment] 2018-07-24 05:08
No worries. It’s probably a mod that either provides its own spawner or makes modifications to vanilla’s that is not compatible with ours. I’ll keep this open until you discover which mod is causing the issue.

**Comment by bloodmc** [comment] 2018-07-28 00:11
Closing as there has been no update in a few days. Open a new ticket if you discover mod.

**Closed as completed by bloodmc** 2018-07-28 00:11 UTC
Labels: version: 1.12, type: mod bug
