### ISSUE TITLE
Repeat command blocks stop looping after going a certain distance away

### ISSUE THREAD

**Issue by stonestevend** [SpongePowered/SpongeForge#2100] opened 2018-04-13 08:41 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2990
- Forge version: forge-1.12.2-14.23.2.2611-universal
- Java version: jre1.8.0_161 64-bit
- Operating System: Windows 8.1

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge

**Issue Description**
      Repeat command blocks stop looping after the player goes a certain distance away from them. I'm not sure of the exact distance, but I'm able to reliably reproduce the issue by going approximately 565 blocks away. They can be reactivated by opening them, setting them to "Needs Redstone", closing them, reopening them, resetting them to "Always Active", and finally, closing them again. However, they will stop looping again once the player leaves the area. This only occurs when running my server with the spongeforge mod, and I've tested it with many different versions, including spongeforge-1.12.2-2611-7.1.0-BETA-2990, 1.12.2-2611-7.1.0-BETA-3019, 1.12.2-2611-8.0.0-BETA-3003, and 1.12.2-2611-7.1.0-BETA-2955. 

https://gist.github.com/stonestevend/ed325752a878bfd00894cfd647044173

**Comment by phit** [comment] 2018-04-13 08:43
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1815

**Closed as completed by phit** 2018-04-13 08:43 UTC
Labels: resolution: duplicate, version: 1.12
