### ISSUE TITLE
End Crystals are still indestructable after summing the dragon

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1036] opened 2016-11-10 00:34 UTC
SpongeAPI: 6.0.0-SNAPSHOT-bd88c91
    SpongeForge: 1.10.2-2123-6.0.0-BETA-1876
    Minecraft Forge: 12.18.2.2123

After players summon the ender dragon using vanilla mechanics, they are unable to destroy the end crystals to do it again.

We tested this previously without sponge and it worked.

**Comment by ProsperCraft** [comment] 2016-11-10 00:34
https://github.com/SpongePowered/SpongeForge/issues/1021

**Comment by ProsperCraft** [comment] 2016-11-10 00:34
Reported here too
https://github.com/SpongePowered/SpongeForge/issues/933

**Comment by AussieWarGod** [comment] 2016-11-10 10:07
i can confirm this also. the ender dragon will also not drop a heart (draconic evolution) or an egg

**Comment by ProsperCraft** [comment] 2016-11-10 14:49
was the heart drop not fixed with the broken spawners fix recently?

**Comment by AussieWarGod** [comment] 2016-11-10 20:26
My apologies, we had not yet updated spongeforge. The ender crystals are the only issue.

**Comment by gabizou** [comment] 2016-11-11 04:17
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/795. It's unfortunate that it's being so weird, this was something previously on my todo list but I have sadly forgotten this. I'll get back to fixing this issue as soon as possible.

**Closed as completed by gabizou** 2016-11-11 04:17 UTC
