### ISSUE TITLE
Dupe Bug With Storage Drawers

### ISSUE THREAD

**Issue by Kaptinobvius** [SpongePowered/SpongeForge#1293] opened 2017-02-25 04:52 UTC
Sponge version - 1.10.2-2221-5.1.0-BETA-2188
Forge version - 12.18.3.2221

In Sky Factory 3, When using the packing tape from the "Packing Tape" mod on any storage drawer, it packages the drawer and also drops the items.  At which point you can open the packaged drawer and still have the original contents.

Works on any item in any quantity.

**Comment by gabizou** [comment] 2017-02-25 07:50
Duplicate of #823

**Closed as completed by gabizou** 2017-02-25 07:50 UTC
