### ISSUE TITLE
1.12.2 Server crashing on startup

### ISSUE THREAD

**Issue by Nulliik** [SpongePowered/SpongeForge#3227] opened 2020-11-16 08:47 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.3.1-RC4093, and lower versions i tried "RC4092, RC4079 and 7.3.0"
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: 1.8.0_222
- Operating System: Linux:amd64:4.15.0-118-generic

- Plugins/Mods:
 Server is crashing so i can't execute sponge command. My plugins directory is empty and i have sponge file only in mods.

**Issue Description**
This problem occurred on a clean server without mods. And on a server with mods installed, I also had a BetterFps mod on first launch, which I assume is not allowed.

 Server crashing on startup with "@Shadow method getPlayerProfileCache in mixins.forge.core.json:server.MinecraftServerMixin_Forge was not located in the target class net.minecraft.server.MinecraftServer. Using refmap mixins.forge.refmap.json" message. 

[Log file](https://gist.github.com/Nulliik/4765a40245bfa6556d9064ce64d5a805)

**Comment by clienthax** [comment] 2020-12-10 13:40
Dupe of https://github.com/SpongePowered/SpongeForge/issues/3221

**Closed as completed by clienthax** 2020-12-10 13:40 UTC
