### ISSUE TITLE
Brush rail bug causing background error unlimited refresh

### ISSUE THREAD

**Issue by DJmanito** [SpongePowered/SpongeForge#2925] opened 2019-08-08 16:02 UTC
I'm running:
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-0abc85a72
    Sponge: 1.12.2-7.1.7-SNAPSHOT
    SpongeForge: 1.12.2-2838-7.1.7-RC3880
    Minecraft Forge: 14.23.5.2838
    JVM: 1.8.0_201/64-bit (Oracle Corporation)
    OS: Windows Server 2019

When a player tries to use a piston to move a track to an empty square with another track next to the empty square, multiple tracks will fall, and the console will report an error, which will not be logged.
Then when players cooperate with some of the module's automated placement/pickup devices and cycle through them, the console will keep reporting errors that are difficult to use.(even if it is not automated, players can brush the rails indefinitely by right-clicking the mouse, causing the console to keep reporting errors)

In addition, this problem seems to lead to the probability that the game thread is stuck in the background, and the player will disconnect, but the server can still be searched, and the server will show that the player is online, even if the plug-in is automatically restarted, there will be no response.(it is not 100% certain at the moment, but when the rail brush machine is turned off, there has never been any jam phenomenon)

当玩家试图使用活塞将一个轨道移动到一个空的方块上，而在这个空方块旁边存在另外一个铁轨，就会掉落多个铁轨，同时后台报错，并且这个报错不会被记入日志。
然后，当玩家使用一些模组的自动放置/拾取设备的设备并循环使用这些设备时，控制台将不断地报错，并难以使用。(即使不是自动的，玩家也可以通过右键鼠标无限刷铁轨，从而导致控制台不断报告错误)
而且这个问题貌似会导致后台出现概率游戏线程卡死，玩家将断开连接，但是依旧可以搜寻到服务器，服务器会显示玩家在线，即使是自动重启插件工作，也无反应。(暂时不能100%确定，但是在刷铁轨机器关闭的时，从来没有出现过卡死现象)

**Comment by JBYoshi** [comment] 2019-08-08 16:24
Could you post the error and a list of mods?

**Comment by DJmanito** [comment] 2019-08-08 16:38
Oh, sorry, I forgot. Please forgive me.
These are the things that will show up in the console, but not in the log.

```
/*********************************************/
/*Exception while trying to apply transaction*/
/*********************************************/
/* BlockTransactions failing to process can lead to unintended*/
/* consequences. If the exception is *directly* coming from*/
/* Sponge's code, please report to Sponge.        */
/*                                                */
/*  BlockStates                                   */
/*   BlockPos{x=212, y=64, z=-364} : minecraft:air*/
/*                                                */
/*  MarkedRemoved                                 */
/*                                                */
/*  Affected Tiles                                */
/*   - BlockPos{x=212, y=64, z=-364} : null       */
/*                                                */
/*  QueuedTiles                                   */
/*                                                */
/*  QueuedRemovals                                */
/* ChangeBlock                                    */
/*  Original Block : SpongeBlockSnapshot{worldUniqueId=8670907a-8196-4e54-bd9d-d7ca707da01f, position=(212, 64, -364), blockState=minecraft:piston_extension[facing=west,type=normal], extendedState=minecraft:piston_extension[facing=west,type=normal]}*/
/*  New State : minecraft:golden_rail[powered=false,shape=north_south]*/
/*  RemovedTile : null                            */
/*  AddedTile : null                              */
/*  ChangeFlag : SpongeBlockChangeFlag{rawFlag=3, updateNeighbors=true, performBlockPhysics=true, notifyObservers=true, notifyClients=true, ignoreRender=false, forceReRender=false}*/
/*                                                */
/* Exception:                                     */
/* java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=shape, clazz=class net.minecraft.block.BlockRailBase$EnumRailDirection, values=[north_south, east_west, ascending_east, ascending_west, ascending_north, ascending_south]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}*/
/*     net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)*/
/*     net.minecraft.block.BlockRailBase.getRailDirection(BlockRailBase.java:211)*/
/*     net.minecraft.block.BlockRailBase.func_189540_a(BlockRailBase.java:96)*/
/*     net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)*/
/*     net.minecraft.block.BlockRailBase.func_176213_c(BlockRailBase.java:87)*/
/*     org.spongepowered.common.event.tracking.context.BlockTransaction$ChangeBlock.process(BlockTransaction.java:462)*/
/*     org.spongepowered.common.event.tracking.context.MultiBlockCaptureSupplier.processTransactions(MultiBlockCaptureSupplier.java:729)*/
/*     org.spongepowered.common.event.tracking.TrackingUtil.performBlockAdditions(TrackingUtil.java:596)*/
/*     org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:465)*/
/*     org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:391)*/
/*     org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.unwind(TileEntityTickPhaseState.java:110)*/
/*     org.spongepowered.common.event.tracking.phase.tick.TileEntityTickPhaseState.unwind(TileEntityTickPhaseState.java:61)*/
/*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:309)*/
/*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616)*/
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:239)*/
/*     net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4783)*/
/*     net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlg000(WorldServer.java:4767)*/
/*     net.minecraft.world.World.func_72939_s(World.java:1835)               */
/*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3943)   */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)*/
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)*/
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)*/
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)    */
/*     java.lang.Thread.run(Unknown Source)*/
/*********************************************/
```

**Comment by DJmanito** [comment] 2019-08-08 16:40
Mods (26): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Applied Energistics 2, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Dynmap, Extra Cells 2, IndustrialCraft 2, Just Enough Items, MineTweakerRecipeMaker, Redstone Flux, SpongeForge, TOP Addons, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Varied Commodities


Plugins (37): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AmberShop, DupeFixer, EconomyLite, EpicBanItem, FlexibleLogin, GiftCode, Inspector, JoinTitle, KaroglanSignEditor, LuckPerms, MMCLogger, MMCReboot, MMCRestrict, MMCRules, New Honor, Nucleus, PixelAutoMessages, PixelVip, PlaceholderAPI, ProjectBorders, ProjectCore, RedProtect, ServerListPlus, ShabbyHolograms, SpongeLoginFix, Title Broadcaster, UltimateChat, VirtualChest, VirtualChestEnchantments, WorldEdit, latch, wolrdpc

**Comment by JBYoshi** [comment] 2019-08-08 17:13
Could you post a screenshot of the machine?

**Comment by DJmanito** [comment] 2019-08-09 11:02
![1](https://user-images.githubusercontent.com/51894776/62774663-0456a400-bad8-11e9-996b-641a40f0c39b.png)
![2](https://user-images.githubusercontent.com/51894776/62774665-07519480-bad8-11e9-911d-a125d600a0dd.png)
![3](https://user-images.githubusercontent.com/51894776/62774668-0882c180-bad8-11e9-8b4a-0ce7dcc16988.png)

And then the player just stands around that, picking up the rail, putting rail in front of the piston.

**Comment by KorewaLidesu** [comment] 2019-08-09 14:28
I think this duplicate to #2920
BlockSnapshot  |  PropertyEnum

**Comment by JBYoshi** [comment] 2019-08-10 01:20
Duplicate of #2920

**Closed as completed by JBYoshi** 2019-08-10 01:20 UTC
Labels: version: 1.12
