### ISSUE TITLE
Applied Energistics breaks Galacticraft when using Sponge

### ISSUE THREAD

**Issue by CinnamonLambda** [SpongePowered/SpongeForge#2580] opened 2019-01-26 09:24 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.5-RC3540
- Forge version: forge-1.12.2-14.23.5.2768-universal
- Java version: build 1.8.0_191-b12
- Operating System: Windows 10

- Plugins/Mods: AppliedEnergestics2, BrandonsCore, BuildCraft, CodeChickenLib, Draconic Evolution, Galacticraft Core, Galacticraft Planets, Micdoodlecore, ProjectCore, ProjectPortals, RedstoneFlux, teleportonlogout, UniverseGuard, mcef, WebDisplays, WorldEdit

**Issue Description**
While using Sponge, Applied Energestics 2 causes Galcticraft to not work properly in the sense that:
1: Space travel attempts (planet menu) causes errors and does not display the menu.
2: In space, low-gravity doesn't work, rotation on space stations doesn't work and the sky is plain black unlike the starry sky it's meant to be with Earth visible underneath.

The issue does not occur when not using Sponge.

https://gist.github.com/TheAgentRAINBOW/e8804f54b87a0bfe4a606141e5e27e75
(latest.log)

**Comment by phit** [comment] 2019-01-26 17:56
what makes you believe it is Applied Energistics 2 causing any of that?

**Comment by CinnamonLambda** [comment] 2019-01-26 18:45
The issue doesn't occur without AE2. Without Sponge, AE2 works just fine with Galacticraft, but with Sponge it seems to cause the incompatibility.

**Comment by gabizou** [comment] 2019-01-26 19:52
Can you gist some of the errors you're getting trying to go to space travel? Is this happening with just AE2, GC and SF installed on the server and AE2 and GC on the client?

Locally, I've tested with:
SpongeForge 1.12.2-2768-7.1.5-RC3540
Galacticraft Core 4.0.2.190
Galacticraft Planets (same as core)
Applied Energistics 2 rv6-stable-6
Forge 2768

I've traveled to space, to other planets, landed, traveled back to space, and no exceptions or anomalies like low gravity not working (on the moon, low gravity is supposed to be 1/3 G I believe).

**Comment by CinnamonLambda** [comment] 2019-01-26 20:07
https://gist.github.com/TheAgentRAINBOW/80330f2dee5b767e396989304240b424

Lack of sky:
![2019-01-26_20 05 31](https://user-images.githubusercontent.com/21277859/51792180-c3371c00-21a5-11e9-905f-36006b27da2f.png)

SF isn't installed on the client.
And I haven't tried with only SF, GC and AE2. I can if you'd like me to.

**Comment by gabizou** [comment] 2019-01-26 21:31
Should have more of a log than that, can you include more (probably before it or after).

**Comment by CinnamonLambda** [comment] 2019-01-26 21:51
You're right, my bad, wasn't looking.

https://gist.github.com/TheAgentRAINBOW/dc64e33fc46dc707b8d00821e21e2a13

**Comment by CinnamonLambda** [comment] 2019-01-27 08:29
It may also be worth noting the space station from which the screenshot originates was created before AE2 was installed.

**Comment by gabizou** [comment] 2019-01-27 21:35
Notes to test to verify where the issue is originating:
- Test with AE2, GC, SF on the server and go to space station, if it fails, please provide full log
- Test with GC and SF only, create station, shut down, add AE2, boot up and travel to station, if fails, provide full log.
- Test with AE2 and GC, create station, travel back, shut down and add SF, start and try to go to station, if fails, provide full log.

Those are the three combinations I'd like done to have tested.

**Comment by phit** [comment] 2019-01-28 00:13
> Test with AE2, GC, SF on the server and go to space station

worked

> Test with GC and SF only, create station, shut down, add AE2, boot up and travel to station

did not work, but now i wonder if it's because of the server restart or because ae2 was added https://gist.github.com/phit/98c141da5bb875c099ebd11a7a0a0953

> Test with GC, SF on the server and go to space station, go back to overworld, restart server and go back to space

works..

> Test with AE2 and GC, create station, travel back, shut down and add SF, start and try to go to station

works after adding sponge, I also restarted after adding sponge and tried going there again and it still worked..


----
all was done with

appliedenergistics2-rv6-stable-6.jar
GalacticraftCore-1.12.2-4.0.2.190.jar
Galacticraft-Planets-1.12.2-4.0.2.190.jar
jei_1.12.2-4.13.1.225.jar
MicdoodleCore-1.12.2-4.0.2.190.jar
spongeforge-1.12.2-2768-7.1.5-RC3543.jar

**Comment by CinnamonLambda** [comment] 2019-01-28 07:52
So the problem lies in already existing space stations?

**Comment by gabizou** [comment] 2019-01-28 07:57
@phit could you get logs for GC + SF > create station > shut down > restart > travel to station knowing it worked?
Also, if you could get zip's of both setups if the dimension id's are different.

**Comment by CinnamonLambda** [comment] 2019-01-28 08:16
https://gist.github.com/TheAgentRAINBOW/e2b3567498f78c3252c06288287c3d20

This may be important:
`[08:13:02] [Server thread/INFO] [Sponge]: Unloading world [DIM_SPACESTATION2] (DIM2)`

And I assume you want a zip of the server.
Since GitHub doesn't like large files:
https://www.dropbox.com/s/7llxn0fij5h0xp9/Test%20Server.zip?dl=0

**Comment by phit** [comment] 2019-01-28 14:49
sorry, didn't save all the logs, but just checked the worlds
gc + sf: space station got id 2
ae2 + gc: space station got id 3
world downloads: https://phit.link/s/worlds.7z

makes sense, ae2 by default uses dimid 2 for its spatial dimension `I:storageDimensionID=2`
so by not editing that config to something thats free when adding ae2 to an existing server it will cause this id conflict

did you not change that config before adding this mod to your server @TheAgentRAINBOW ?

**Comment by CinnamonLambda** [comment] 2019-01-28 15:32
I didn't. I will try that a little later, that could explain everything.

**Comment by CinnamonLambda** [comment] 2019-01-28 16:15
I set it to two unused dimensions (3 & 7) yet neither of them worked. It may be worth noting I noticed Sponge saying the space station doesn't load on startup.
I also tried regenerating AE2's config. My next idea would be to make the space station load on startup.

**Comment by phit** [comment] 2019-01-28 16:47
> I set it to two unused dimensions (3 & 7) yet neither of them worked. It may be worth noting I noticed Sponge saying the space station doesn't load on startup.

what did you set to those ids?

> I also tried regenerating AE2's config. My next idea would be to make the space station load on startup.

that's just gonna reset the ids..

**Comment by CinnamonLambda** [comment] 2019-01-28 16:51
I set `I:storageDimensionID` to 3, it didn't work, then 7. Also didn't work. I checked after and 3 might have been used, but 7 certainly wasn't.

**Comment by CinnamonLambda** [comment] 2019-01-30 16:13
`[16:11:16] [Server thread/INFO] [Sponge]: Loading world [DIM_SPACESTATION2] (Storage Cell)`

**Comment by ghost** [comment] 2019-05-21 10:50
So correct me if I am wrong, @TheAgentRAINBOW will just need to change the conflicting dimension IDs?

**Comment by phit** [comment] 2019-05-31 02:50
I'm honestly lost at this point about this issue, I'm just gonna assume you have an ID conflict as nobody else has reported this and there are lots of servers running GC and AE2 with SpongeForge .

**Closed as completed by phit** 2019-05-31 02:50 UTC
Labels: system: world, version: 1.12, status: investigation

**Comment by bluelightning32** [comment] 2019-08-25 19:41
Space stations and galacticraft don't work. I filed a new bug for it:
https://github.com/micdoodle8/Galacticraft/issues/3775
