### ISSUE TITLE
Failed to process all PhaseContext captured! 

### ISSUE THREAD

**Issue by EcksEcksEcks** [SpongePowered/SpongeForge#2956] opened 2019-09-06 12:11 UTC
/* Minecraft : 1.12.2                                                                                                                                                                     */
/* SpongeAPI : 7.1.0-b38390e17                                                                                                                                                            */
/* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                                                                         */
/* SpongeForge : 1.12.2-2838-7.1.7-RC3908                                                                                                                                                 */
/* Minecraft Forge : 14.23.5.2844 

Abyssal Craft
Actually Additions
Applied Energistics 2
Aquaculture
Baubles
Better Foliage
Better FPS
Biomes O Plenty
Botania
Building Gadgets
Chisel
Chisel and Bits
Cooking for Blockheads
Crafting Tweaks
Cyclic
/Dank//Null
Decocraft
Draconic Evolution
DrZharks MoCreatures
Dynamic Surroundings
Dynamic Trees
Dynamic Trees (Biomes O Plenty)
EnderIO
Exotic Birds
Fence Jumper
Forestry
Galacticraft (Core + Planets + Extra Planets)
Gendustry
IDO
Immersive Engineering
Inventory Pets
Inventory Tweaks
Item Chat
Item Physics (Full)
Just Enough Resources
Just Enough Resources (Harvestcraft)
Just Enough Calculations
JurassiCraft
Mekanism (Core + Generators + Tools)
Mystical Agriculture
Mystical Agradditions
Natures Compass
Nether EX
Nether Portal Fix
Open Glider
Pam's Harvestcraft
Placeable Items
RailCraft
Redstonepaste
Solar Flux Reborn
Storage Drawers
Tinkers Construct
The One Probe
Thermal Dynamics
Thermal Expansion
Torchmaster
Twilight Forest
YABBA

Seems to happen randomly when generating new chunks. Chunks stop loading and TPS drops. Then the console gets spammed with the PhaseContext error included in the link below

https://gist.github.com/MrXuiryus/0c03e664a118905535e8b78e134ab81f

**Comment by EcksEcksEcks** [comment] 2019-09-06 14:29
[crash-2019-09-06_15.17.45-server.txt](https://github.com/SpongePowered/SpongeForge/files/3584352/crash-2019-09-06_15.17.45-server.txt)

This has now caused the server to completely crash... Crash report added

**Comment by KorewaLidesu** [comment] 2019-09-08 07:45
i think somethings broken with your world
the crash report due to Watchdog feature which auto kill server if it get to max-tick-time (reason is because it waiting on load the map so make tick time get ***high***)
*backup important file, then change max-tick-time in server.properties from 300 to 0*
*it could let to another crash, i think?* (for world?)

**Comment by gabizou** [comment] 2019-09-11 00:55
Could you provide a full server log?

**Comment by gabizou** [comment] 2019-09-12 08:55
Looks like a duplicate of #2953

**Closed as completed by gabizou** 2019-09-12 08:55 UTC
Labels: status: more information needed
