### ISSUE TITLE
Execute command not detecting player with a score

### ISSUE THREAD

**Issue by chrismack** [SpongePowered/SpongeForge#382] opened 2015-10-22 14:38 UTC
for example running the command "/execute @a ~ ~ ~ say hi" work fine however when you add arguments to the command it doesn't work i.e "/execute @a[score_R_min=1]  ~ ~ ~ say hi"

The score_R_min is a reference to the score board objective called R, and it looks for a minimum value of 1

@JBYoshi (tagged you because you helped last time :) )

**Comment by Aaron1011** [comment] 2015-10-22 19:18
I'm unable to reproduce this.

Does the objective exist on the world's scoreboard, and not a player-specific one? The vanilla selectors will only look at the world scoreboard.

**Comment by ryantheleach** [comment] 2015-10-23 17:58
Which world? It might be a cross world issue.

**Comment by chrismack** [comment] 2015-10-24 15:07
it's all in the main world, it also works in vanilla minecraft :/ after testing it a fair bit the issue seems to be fairly inconsistent which is annoying

![2015-10-24_16 03 25](https://cloud.githubusercontent.com/assets/1420361/10711098/4413b30c-7a69-11e5-8d98-4ff54e14d43d.png)

i'll keep looking into it to see if i can find out what causes it to fail

**Comment by Aaron1011** [comment] 2015-10-25 00:36
I've now reproduced this issue, and will be pushing a fix soon.

**Comment by JBYoshi** [comment] 2015-11-07 22:22
@Aaron1011 Status?

**Comment by Aaron1011** [comment] 2015-11-08 01:56
@JBYoshi: This will be addressed as part of my broader ccaners to scoreboards to properly support multiple worlds.

**Comment by chrismack** [comment] 2015-12-14 12:51
@Aaron1011 any newson this?

**Comment by chrismack** [comment] 2015-12-14 12:52
News*

**Comment by Aaron1011** [comment] 2015-12-14 16:37
@chrismack: This will be in by beta.

**Comment by chrismack** [comment] 2015-12-14 16:49
Awesome thank you

**Closed** 2015-12-30 17:30 UTC

**Comment by Aaron1011** [comment] 2015-12-30 19:00
@chrismack: Glad to see my changes fixed this :). Let me know if you have any other issues pertaining to scoreboards.

**Comment by chrismack** [comment] 2015-12-30 19:24
Thanks @Aaron1011 :) i'll keep an eye out
