### ISSUE TITLE
Teleportation glitch...

### ISSUE THREAD

**Issue by Retr0G** [SpongePowered/SpongeForge#2554] opened 2019-01-13 10:15 UTC
**I am currently running**
- SpongeForge version: Newest, released 8 hours ago (1.12.2-2768-7.1.5-RC3520)
- Forge version: FTBserver-1.12.2-14.23.5.2796-universal
- Java version: 8
- Operating System: Ubuntu

Hey guys so I am trying to make a Stoneblock 2 server to play on, and I get a little glitch, when I try to use the portal to other dimensions it doesn't teleport me to the right coordinates (It telelports me over bedrock instead of the what it should be at Y 2...), it teleports me to the right dimension though. I haven't installed any plugins, without Sponge it works perfectly, but I also need Bungeecord so Sponge is my only option so far...

**Comment by takarabako** [comment] 2019-01-13 10:51
Similar problem when using FTBUtilities teleport commands across dimension. The dimension is changed but location is not. It seems the `teleporter.placeEntity()` is not called. Haven't dig into the source yet but I hope this will provide some information to people more familiar with the code.

**Comment by Retr0G** [comment] 2019-01-13 10:53
Well can you change a mod without players to change it too?

Edit: Though I've seen many fix it, when there was a fix from kashike, but it doesn't seem to do the trick for me, even though the FTBUtilities tp works fine I think

**Comment by takarabako** [comment] 2019-01-13 11:08
The fix from kashike is already merged and before that ftbu tp didn't even execute at all. Are you sure you can use e.g. tpa to a player in different dimension without ending up in a weird location on the latest build?

**Comment by Retr0G** [comment] 2019-01-13 11:23
The tpa doesn't really matter, the server is on whitelist until the bug is fixed, and many people are waiting ...

**Comment by phit** [comment] 2019-01-13 15:19
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2266

the current solution is only a workaround for the crash and may not work fully as expected

**Closed as completed by phit** 2019-01-13 15:19 UTC
Labels: resolution: duplicate, version: 1.12
