### ISSUE TITLE
Constant Client Disconnects Network Dispatcher

### ISSUE THREAD

**Issue by KhaozFrost** [SpongePowered/SpongeForge#1925] opened 2018-01-01 00:24 UTC
**I am currently running**

    SpongeForge version: 1.12.2-2555-7.0.0-BETA-2807
    Forge version: 2555
    Java version: 1.8.0_151
    Operating System: Linux OS

    Plugins/Mods:
    1st test - SpongeForge / Forge
    2nd test - SpongeForge / Forge / Pixelmon Reforged / GriefPrevention / Nucleus / Luckperms ((all on latest versions))

**Issue Description**

`31.12 08:51:33 [Server] Netty Epoll Server IO #30/ERROR [FML]: NetworkDispatcher exception 31.12 08:51:33 [Server] INFO` 
 in the console. also this error on the client: `https://gist.github.com/KhaozFrost/eca131dcc9604899e27722f18d62ec87`
This seems to be happening alot lately for my server after switching to 1.12.2 and its basically unplayable. I contacted my host and they had me send a MTR Report http://prntscr.com/huhz9x based on what its saying there is no issues with the connection to the server, Its a server issue. The mods currently on the server though are just the sidemods and a few custom ported ones from here. 

<!-- Please provide a *full* server log (and crash-report if applicable).
https://gist.github.com/KhaozFrost/eca131dcc9604899e27722f18d62ec87

**Comment by phit** [comment] 2018-01-01 00:27
That super generic error is sadly not very helpful, I personally get that error a lot when my internet is being slow.

I'll leave this issue open but unless you find a way to consistently reproduce this without any mods/plugins, I would call it a network issue and not a bug.

**Comment by smmmadden** [comment] 2018-01-01 02:14
I've seen the same on my Pokecube Server and downgraded to build 2758.  After this build, it throws PhaseState Exceptions and the network dispatcher exception periodically and then the server needs to be restarted.  The two are probably not related, but 2758 is the only one I can use currently.

**Comment by JBYoshi** [comment] 2018-01-01 02:33
@smmmadden What are the PhaseState exceptions?

@KhaozFrost Could you post the full server log? I think the full error is longer.

**Comment by smmmadden** [comment] 2018-01-01 02:45
http://www.minecraftforge.net/forum/topic/62215-exception-occurred-during-a-phasestate-on-startup/
https://forums.spongepowered.org/t/exception-occurred-during-a-phasestate-on-startup/21845

**Comment by phit** [comment] 2018-01-01 02:47
relevant section https://gist.github.com/phit/74e8f94e50c38c6e6cd32bd1c8aae79c

**Comment by Faithcaio** [comment] 2018-01-11 19:55
If this was only the crafting grid size issue this is fixed in latest API-7

**Closed as completed by Faithcaio** 2018-01-11 19:55 UTC
Labels: version: 1.12, system: network
