### ISSUE TITLE
[1.10.2] Villagers having wrong trades

### ISSUE THREAD

**Issue by FoolishBalloon** [SpongePowered/SpongeForge#1829] opened 2017-11-02 19:05 UTC
For starters, I barely know what SpongeForge is, but my server administrator recommended me to post here. I'm running FTB Beyond 1.11, but the problem has persisted since many versions back, around 6 months I believe. 

Basically, all modded villager professions have the wrong trades assigned to them. Vanilla professions such as armorer and librarian all sell their usual stuff, but modded ones such as arborists and jam guys sell the wrong things. Some examples are that arborists (Forestry) sell Railcraft stuff and apirarists (Forestry) sell Immersive Engineering stuff. So I guess that some values have been switched / off balance somewhere, hopefully a fairly easy fix?

I have no idea which versions of Forge and SpongeForge we're running, as I'm just a normal member on the server (ToastyNetworks, FTB Beyond 1.11)

**Comment by ryantheleach** [comment] 2017-11-03 00:15
> I have no idea which versions of Forge and SpongeForge we're running, as I'm just a normal member on the server (ToastyNetworks, FTB Beyond 1.11)

This is the minimum of information we will need.

That said, it appears this issue is a duplicate of : https://github.com/SpongePowered/SpongeForge/issues/1562

**Comment by phit** [comment] 2017-11-06 20:31
Duplicate of #1562

**Closed as completed by phit** 2017-11-06 20:31 UTC
Labels: resolution: duplicate
