### ISSUE TITLE
Player kick "String too big" with /sponge plugins

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#1407] opened 2017-04-01 11:29 UTC
As of 
forge-1.10.2-12.18.3.2254-universal.jar
spongeforge-1.10.2-2254-5.2.0-BETA-2262.jar
with the Invasion modpack and no plugins.
Issue is reproduced with other modpacks like FTB Beyond, etc.

When using /sponge plugins, player gets kicked from server:
```
[06:57:00] [Server thread/INFO]: §r§r§r§r§e§r§eLemADEC§r§e joined the game§r
[06:57:31] [Netty Epoll Server IO #2/ERROR]: io.netty.handler.codec.EncoderException: String too big (was 33320 bytes encoded, max 32767)
[06:57:32] [Server thread/INFO]: LemADEC lost connection: Disconnected
[06:57:32] [Server thread/INFO]: §r§r§r§r§e§r§eLemADEC§r§e left the game§r
```

When checking from console, the chat message is only 3868 bytes long:
```
>sponge plugins
[06:57:39] [Server thread/INFO]: Plugins (158): §r§aMinecraft§r, §r§aMinecraft Coder Pack§r, §r§aForge Mod Loader§r, §r§aMinecraft Forge§r, §r§aAdvanced Rocketry§r, §r§aIvToolkit§r, §r§aNot Enough Items§r, §r§aStuff A Sock In It§r, §r§aSpongeAPI§r, §r§aSpongeForge§r, §r§aFoamFixCore§r, §r§accl-entityhook§r, §r§aFence Overhaul§r, §r§aActually Additions§r, §r§aForge Endertech§r, §r§aAdvanced Hook Launchers§r, §r§alibVulpes§r, §r§aAdvanced Rocketry§r, §r§aBiomeTweaker§r, §r§aBiomes O' Plenty§r, §r§aanimalium§r, §r§aJust Enough Items§r, §r§aAppleCore§r, §r§aapple_shields§r, §r§aAppleSkin§r, §r§aQuark§r, §r§aAutoRegLib§r, §r§aBagginses§r, §r§aCraftTweaker JEI Support§r, §r§aMineTweaker 3§r, §r§aB.A.S.E§r, §r§aBase Metals§r, §r§aBaubles§r, §r§aBD Lib§r, §r§aBetter Builder's Wands§r, §r§aBookshelf§r, §r§aBreakable Tables§r, §r§aCeramics§r, §r§aChameleon§r, §r§aChest Transporter§r, §r§aClumps§r, §r§aCodeChicken Lib§r, §r§aCodeChicken Core§r, §r§aCyclops Core§r, §r§aColossal Chests§r, §r§aCooking for Blockheads§r, §r§aCrossbow Mod§r, §r§aCrybaby§r, §r§aCustom Tweaks§r, §r§aCXLibrary§r, §r§aCyberware§r, §r§aDarko Tweaks§r, §r§aInvasion Tweaks§r, §r§adirt_flinger§r, §r§aDooglamoo Cities§r, §r§adrones§r, §r§aDungeonTactics§r, §r§aEarthworks§r, §r§aEdible Bugs Mod§r, §r§aElevator Mod§r, §r§aEnderCore§r, §r§aEnder IO§r, §r§aValkyrie Lib§r, §r§aEnvironmental Tech§r, §r§aEpic Siege Mod§r, §r§aET Lunar§r, §r§aEx Nihilo Adscensio§r, §r§aExtra Utilities 2§r, §r§aFast Leave Decay§r, §r§aFoamFix§r, §r§aForageCraft§r, §r§aForgelin§r, §r§aFTBLib§r, §r§aLimeLib§r, §r§aFurnus§r, §r§aGear Swapper§r, §r§aAdvanced Generators§r, §r§aGenetics Reborn§r, §r§aGravestone§r, §r§aGet Ya' Tanks Here§r, §r§aHardcore Darkness§r, §r§aHardcore Wither§r, §r§aHealth and Hunger Tweaks§r, §r§aHardcore Questing Mode§r, §r§aThe One Probe§r, §r§aImmersive Engineering§r, §r§aInfiniteFluids§r, §r§aInfinityLib§r, §r§aLunatriusCore§r, §r§aInGame Info XML§r, §r§aMTLib§r, §r§aInitialInventory§r, §r§aSimple Inventory sorting§r, §r§aIron Backpacks§r, §r§aIron Chest§r, §r§aJourneyMap§r, §r§aKaishi's Weapons Pack§r, §r§aKleeSlabs§r, §r§aKnob Control§r, §r§aLaser Creeper Robot Dino Riders From Space§r, §r§aLevels§r, §r§aLLibrary§r, §r§aLiteral Ascension§r, §r§aLittle Looter§r, §r§aLoot Table Tweaker§r, §r§amagma_monsters§r, §r§aMalisisCore§r, §r§aMalisisDoors§r, §r§aMineColonies§r, §r§aMinecraft Flight Simulator§r, §r§aMineSouls§r, §r§aMissing Pieces§r, §r§amob_grinding_utils§r, §r§aMod Tweaker§r, §r§aMore Furnaces§r, §r§aMore Shears§r, §r§aModPack Utilities§r, §r§aModPack Basic Tools§r, §r§aNo Nausea§r, §r§aClassic Oceans§r, §r§aOMLib§r, §r§aOpen Modular Passive Defense§r, §r§aOpen Modular Turrets§r, §r§aOreExcavation§r, §r§aOreSpawn§r, §r§aOre Tweaker§r, §r§aPam's HarvestCraft§r, §r§aRaiders§r, §r§aProgressive Automation§r, §r§aQuantumFlux§r, §r§aRebornCore§r, §r§aQuantumStorage§r, §r§aRanged Pumps§r, §r§aRealistic Item Drops§r, §r§areborncore-MCMultiPart§r, §r§aRecurrent Complex§r, §r§aReliquia§r, §r§aRope Bridge§r, §r§aRough Tweaks§r, §r§aSimple Corn§r, §r§aSimple Generators§r, §r§aSpartan Shields§r, §r§aStorage Drawers§r, §r§aSurvivalist§r, §r§aThermal Solars§r, §r§aThirsty Bottles§r, §r§aTOP Addons§r, §r§aTranslocator§r, §r§aTumbleweed§r, §r§avoxels§r, §r§aWanionLib§r, §r§aWater Strainer§r, §r§aWolf Armor and Storage§r, §r§aWorld Limiter Mod§r, §r§aexamplemod§r, §r§aWTFs-Expedition§r, §r§aair_support§r, §r§aUniDict§r
```

Issue is reproduced with spongeforge-1.10.2-2254-5.2.0-BETA-2236.jar .

**Comment by stephan-gh** [comment] 2017-04-01 11:30
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/918 and https://github.com/SpongePowered/SpongeCommon/issues/1239

**Closed as completed by stephan-gh** 2017-04-01 11:30 UTC
Labels: resolution: duplicate
