### ISSUE TITLE
Quantum Quarry - Broken

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1796] opened 2017-10-02 11:15 UTC
Hi all, on our Age of Engineering server the Quantum Quarries are not working. It takes Rf from a capacitor bank, also shows that in the quarry its mined blocks but they are not outputting to the chest.

Tested on single player and works fine.

SpongeForge:
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2477-5.2.0-BETA-2637

**Comment by phit** [comment] 2017-11-01 05:24
can't reproduce with with spongeforge-1.10.2-2477-5.2.0-BETA-2698 and extrautils2-1.10.2-1.6.4

![2017-11-01_06 24 07](https://user-images.githubusercontent.com/2097483/32261201-49220f9c-becd-11e7-89de-923d0404c583.png)

**Comment by heyoomimi** [comment] 2017-11-05 09:27
Do you have Grief Prevention installed? I got it to work by disabling Grief Prevention in the dimension -9999 quarry dimension.

**Comment by Keaton1188** [comment] 2017-11-05 16:47
No, we are using Nations. 

Also using the latest version of sponge and still having the issue.

Resetting the Quarry DIM now to see if that helps

**Comment by heyoomimi** [comment] 2017-11-05 21:36
Try to disable it in that dimension if possible.

**Comment by phit** [comment] 2017-11-06 20:29
@Keaton1188 sounds like Nations could be blocking the block breaking, check if there's a way to disable its protection for the Quarry Dimension.

**Comment by Keaton1188** [comment] 2017-11-08 22:34
Its already disabled in that Dimension.

**Comment by phit** [comment] 2017-11-21 22:12
Also can't reproduce with 

spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
extrautils2-1.12-1.6.7.jar

Closing, if you find a way to reproduce this feel free to open a new issue, with all the relevant information.

**Closed as completed by phit** 2017-11-21 22:12 UTC
Labels: version: 1.10 (u), status: more information needed

**Comment by tgstyle** [comment] 2017-12-05 19:19
If sponge is unloading the dimension, make sure it stays loaded with -

keep-spawn-loaded=true

This fixed my issue.
