### ISSUE TITLE
[1.11.2] Ender Dragon Summoning Ritual never fires.

### ISSUE THREAD

**Issue by Zytheus** [SpongePowered/SpongeForge#1766] opened 2017-09-08 04:19 UTC
Issue : After killing the Ender Dragon, I am unable to respawn it using the Vanilla method of placing 4 End Crystals around the Exit Portal. The method works fine without SpongeForge being loaded.  I am unable to figure out what is preventing the summoning ritual event.

Mods/Client Info : Run on MC forge-1.11.2-13.20.1.2393 + spongeforge-1.11.2-2393-6.1.0-BETA-2606

OS: Windows 10

Logs : https://paste.ee/p/z8qaM

Steps Taken

1: New World created. Creative mode.
2: Teleport to End
3: Kill Ender Dragon
4: Place 4 End Crystals

Expected Result : Summoning rays go WOOSH and POW. End crystals respawn. Ender Dragon respawns.

Actual Result : Literally nothing. No log. No woosh.

**Comment by liach** [comment] 2017-09-08 04:20
Might these be relevant?
```
[18:35:03] [Server thread/INFO]: Scanning for legacy world dragon fight...
[18:35:03] [Server thread/INFO]: Found that the dragon has not yet been killed in this world.
```

**Comment by Zytheus** [comment] 2017-09-08 04:33
That was simply the world checking for the Pre 1.9 fights. That is a normal log. If I kill the ender dragon, the log will simply say "The dragon has already been killed in this world." but won't actually change anything. Due to the lack of logs, I feel as if it may be a config issue, but I scanned the thing and find no mention of the Exit Portal.

**Comment by Zytheus** [comment] 2017-09-16 06:01
Hello :( ?

**Comment by phit** [comment] 2017-11-01 04:13
can't reproduce with spongeforge-1.11.2-2476-6.1.0-BETA-2715

![2017-11-01_05 13 11](https://user-images.githubusercontent.com/2097483/32259796-655fd73e-bec3-11e7-8db4-2cb212422e32.png)

**Comment by phit** [comment] 2017-11-06 19:52
Closing this for now. If this is still an issue for you, please let us know and provide relevant new info e.g. which mods are required to reproduce this.

**Closed as completed by phit** 2017-11-06 19:52 UTC
Labels: version: 1.11 (u)
