### ISSUE TITLE
eyes of ender errors

### ISSUE THREAD

**Issue by mineblow** [SpongePowered/SpongeForge#1539] opened 2017-05-24 22:26 UTC
**I am currently running...**

- SpongeForge version:  2344
- Forge version: 2281
- Java version: jdk 1.8
- Operating System: 

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X ] Windows

- Plugins/Mods: 
all the mods mod pack 1.10.2
**What is the expected result?**
right click enderpearl nothing happens
**What is the current result?**
should lead to end portal

https://gist.githubusercontent.com/mineblow/9a50babd6314ab8dc129520e88b55d83/raw/e04a4bd88bc16930866a693db73688218f7f28c5/fml-latest

**Comment by LJack2k** [comment] 2017-05-24 23:09
Enderpearls don't lead you to the end portal, eye of enders do.

**Comment by gabizou** [comment] 2017-05-24 23:21
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/937

**Closed as completed by gabizou** 2017-05-24 23:21 UTC
Labels: resolution: duplicate
