### ISSUE TITLE
Interacting with Shulker Boxes still produscs error

### ISSUE THREAD

**Issue by t2wave** [SpongePowered/SpongeForge#1399] opened 2017-03-29 15:50 UTC
Just letting you guys know it's still there. Thankfully it doesn't appear to cause the server any trouble functioning.

latest.log:
https://pastebin.com/SH3JWMrz

fml-server-latest.log:
https://pastebin.com/tBRHvQqP

**Comment by Inscrutable** [comment] 2017-03-30 09:03
This is a duplicate of the issue on SpongeCommon: https://github.com/SpongePowered/SpongeCommon/issues/1253

**Closed as completed** 2017-03-30 10:07 UTC
Labels: resolution: duplicate, system: inventory
