### ISSUE TITLE
Furnace dropping items

### ISSUE THREAD

**Issue by CaptainSisko** [SpongePowered/SpongeForge#2725] opened 2019-04-29 19:28 UTC
**I am currently running**

**- SpongeForge version:**  

Tested with
1. RC3670
2. RC3671
3. RC3682

**- Forge version:** 
forge-1.12.2-14.23.5.2825-universal.jar

**- Java version:**
1.8.0_201

**- Operating System:** 
Windows 10

**- Plugins/Mods:**
I have done multiple tests with different mods and plugins, see below

**- Issue Description**
Using Sponge RC3671(and above) with Nucleus (tested 1.8.2 & 1.9.3) is causing the [nuclearcraft issue that was posted the other day](https://github.com/SpongePowered/SpongeForge/issues/2710) but i have also found that it is causing the same issue with standard Minecraft Furnaces.

I setup a client containing only 
1. Sponge RC3671
2. Nucleus (tested both 1.8.2 & 1.9.3)
3. Forge 2825
4. JEI 4.15.0.268

I then placed a Minecraft Furnace and put a piece of coal and a gold ore block inside, The coal is consumed and the gold ore pops out of the furnace and onto the ground.

However, if i do the same steps but without Nucleus, the furnace will function correctly.

I then rolled sponge back to RC3670 and tested with:
1. Sponge RC3670
2. Nucleus (tested both 1.8.2 & 1.9.3)
3. Forge 2825
4. JEI 4.15.0.268

The furnace functioned correctly.

So it looks like something that was changed between RC3670 and RC3671 has broken some compatibility with Nucleus. I also performed the same test with Sponge RC3682 and i had the same experience as i did with RC3671.

I did these same tests with NuclearCraft 2.15 and can confirm that when running Sponge RC3671 and Nucleus, items placed into the Manufactory will pop out just like the furnace.

**- Logs:**
[Sponge RC3671 & Nucleus 1.9.3](https://hastebin.com/udorabecux.sql)
[Sponge RC3670 & Nucleus 1.9.3](https://hastebin.com/ewecokadig.sql)

Its possible that this issue will also need to be reported to Nucleus, im happy to do so if needed. Also if you require me to do any further testing, please let me know.

**Comment by Sir-Will** [comment] 2019-04-29 23:20
Same issue here but happens without nucleus too
![](https://i.imgur.com/EuhbUWy.gif)

**Comment by CaptainSisko** [comment] 2019-04-30 01:10
I can see that you have FastFurnace installed @Sir-Will, what version is it?

That issue could be related but i decided not to add it to my post as it required a different set of steps to replicate and also has a different outcome. I thought that would be best suited for a different issue tracker. 

I only tested FastFurnace with RC3670 and RC3671 and the same issue occurred in both versions.

With FastFurnace installed, the items put into the furnace do not eject onto the ground like the Sponge/Nucleus bug, the items completely vanish instead, this happens regardless of Nucleus being installed.

The bug may have been fixed on FastFurnaces side however [as seen here](https://github.com/Shadows-of-Fire/FastFurnace/commit/8a7145bd0105a0daee778a855c2a798133d884b0), i haven't tested the latest version of FastFurnace yet because i was reporting the issue in my OP, not an issue with FastFurnace.

**Comment by krisjenner** [comment] 2019-04-30 16:55
This happens on any build >3616. I was told it's a GriefPrevention issue more than anything and we have to wait for that to update.

**Comment by CaptainSisko** [comment] 2019-04-30 17:00
None of my testing involved GriefPrevention so it cant be that. (unless you are talking about the FastFurnace bug?)

The issue of items being ejected from the furnace (not swallowed by the furnace like which occurs with the FastFurnace bug) occurs when using only Sponge and Nucleus.

**Comment by johnfriedrich** [comment] 2019-05-06 15:07
This is not fixed as of Sponge 7.1.6-RC3693
Skyfactory Modpack 4.0.5 with Forge 14.23.5.2831

You can reproduce it like in the gif from Sir-Will above

**Comment by phit** [comment] 2019-05-06 22:06
@i9hdkill logs? you are probably having the same issue as https://github.com/SpongePowered/SpongeForge/issues/2713 or https://github.com/SpongePowered/SpongeForge/issues/2730

**Comment by johnfriedrich** [comment] 2019-05-06 23:59
No, not getting any phase errors due to this.
Here is the log: 
https://www.dropbox.com/s/n25lvohzaqwa3f9/ftb.log?dl=0

The bug was first discovered before these tons of Together Forever phase exceptions.
These exceptions made it over 1gb, just cutted the first part.

Edit: Just redproduced, no exceptions

**Comment by ktole1999** [comment] 2019-05-07 19:59
i was able to resolve this by reverting back to recommended version of sponge even while using the latest nucleus. Since i am using the SF4 pack this was my only option.

**Comment by johnfriedrich** [comment] 2019-05-07 20:37
@ktole1999 recommended or 3616?

**Comment by ktole1999** [comment] 2019-05-07 20:42
Still had issues with 3616 Had to back to recommended



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by gabizou** [comment] 2019-05-08 02:32
Can people test with 7.1.6-RC3694?

**Comment by johnfriedrich** [comment] 2019-05-08 02:41
7.1.6-RC3694 fixes the problem. At least for Furnaces (Didn't test more than that initially anyway) Thanks.
Please let the others test with other Tiles before closing

**Comment by Yorkforce** [comment] 2019-05-08 05:44
We still seem to be having issues, vanilla furnaces/cauldrons etc seem to be ok now, but nuclearcraft machines and mystical agriculture furnaces are eating resources, did not happen in RC3689

With the nuclearcraft machines once you put item in the GUI closes, you can reopen it again but the items will be gone and the machine stays in an 'active' state until broken. 

The big issue is it seems to be affecting all nuclearcraft machines which is breaking many other recipes that rely on items that can only be made in these machines. It's a pretty big problem when multiple mods become inaccessible.

**Comment by gabizou** [comment] 2019-05-08 22:23
> With the nuclearcraft machines once you put item in the GUI closes, you can reopen it again but the items will be gone and the machine stays in an 'active' state until broken.

I'm not getting this running 7.1.6-RC3694 and NuclearCraft 2.16f (it's using the exact same logic as furnaces during it's switching so it makes sense if furnaces were broken, nuclearcraft furnaces would be broken as well).

Example:
https://imgur.com/cTocdos

I do have the flag `-Dsponge.shouldFireAll=true` as a launch argument because without that (and without another plugin listening for some events) the tracking system wouldn't be used for block changes and tile entity changes.

**Comment by Yorkforce** [comment] 2019-05-09 01:07
@gabizou 
Edit: Just noticed you used the Nuclear Furnace, i just tested that and it works fine on the server, could you check the manufactory, alloy smelter and rock crusher, those are 3 machines we are definitely having the problem with.

We are on the SF4 modpack which is using NuclearCraft 2.16e, however I updated that to 2.16f and I'm still getting the same thing.

I downgraded to Spongeforge 7.1.6-RC3693 and the manufactory works again so something between RC3693 and 3694 is breaking some of the nuclearcraft machines for us.

I tested with and without FastFurnace, disabled griefprevention and skyclaims incase those were messing with it but those changes made no difference.
I added the -Dsponge.shouldFireAll=true to the jar.conf launch parameters again making no difference, only with RC3694 or RC3695 do they break.

**Comment by Yorkforce** [comment] 2019-05-09 21:08
Just to update, we started getting water and lava flow issues again on 3694

#2713 

https://pastebin.com/vqdeMSKW

[latest.log](https://github.com/SpongePowered/SpongeForge/files/3164028/latest.log)

Edit: Sorry the only reason I added this here was because of the similarities between the cause and effects, we used to have lava/water flow issues alongside the vanilla furnace problem, that bug seemly went away but has returned in 3694, along with the mystical agriculture furnaces now behaving in the exact same way the vanilla furnaces used to behave with eating items. Both those issues appear after a phase tracking error in the log.

Whatever changed in 3694 appears to be having a cascade effect on the same issue.

**Closed as completed** 2019-05-10 18:22 UTC
Labels: type: bug, status: accepted, system: phase tracker, version: 1.12

**Comment by Yorkforce** [comment] 2019-05-10 19:10
Thankyou @gabizou 
All the nuclearcraft machines are working again :)
