### ISSUE TITLE
space stations from advanced rocketry not spawning with spongeforge on Continuum 1.3.1

### ISSUE THREAD

**Issue by SimplyLime** [SpongePowered/SpongeForge#2328] opened 2018-07-20 02:48 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3320
- Forge version: 1.12.2-14.23.4.2705
- Java version: build 1.8.0_181-b13
- Operating System: Ubuntu

- Plugins/Mods:
Continuum Modpack 1.3.1
CatClearLag
EMPSponge
ForgedPerms
LuckPerms
MMCRestrict
MMCRules
Nucleus
MagiBridge
Nuvotifier
TickProfiler
WorldEdit

**Issue Description**
When Flying a rocket to go to a space station, the rocket gets to y1000 and doesnt go into the space DIM as it should, and eventually the rocket falls back down from lack of fuel. Have reproduced the problem without SpongeForge and it has worked flawlessly.
#1715 
This same issue has happened before through the above reference, But im unsure if this incident is related.

**Comment by phit** [comment] 2018-07-20 12:11
please give use your `/config/sponge` folder, you most likely have deny-chunk-requests enabled or something similar

**Comment by SimplyLime** [comment] 2018-07-20 16:12
Here is the global.conf.
https://gist.github.com/SimplyLime/8b45092bf817ca2d3ab3665f83ccb2fa
that setting is the first i checked as its referenced to be the problem but no dice.

**Comment by SimplyLime** [comment] 2018-07-20 16:15
Here is the whole sponge folder.
[sponge.zip](https://github.com/SpongePowered/SpongeForge/files/2214629/sponge.zip)
that setting is the first i checked as its referenced to be the problem but no dice.

**Comment by phit** [comment] 2018-07-20 16:18
yeah, looks fine, ill test it locally in a bit because last I checked it works fine on my server
just have to figure out what config setting differs

**Comment by SimplyLime** [comment] 2018-07-20 16:19
Alright thank you. ive been pulling my hair out on this issue.

**Comment by phit** [comment] 2018-07-20 16:23
try adding this if you have some time to test, because I won't be able to for a few more hours

https://gist.github.com/phit/abbedfa1c6f241a0e9fa59552f9eb5bd/revisions

btw unrelated to this `block-capturing` no longer has any effect in the global.conf and has been moved to the tracker.conf you can safely delete that section

**Comment by SimplyLime** [comment] 2018-07-20 16:31
I will try editing the config but unsure of when i will be able to properly test that change.

**Comment by bloodmc** [comment] 2018-07-26 16:59
@SimplyLime Retest using latest SF and make sure to address any config changes phit has mentioned.

**Comment by phit** [comment] 2018-09-26 23:07
couldn't even test this on latest, rocket simply doesnt launch

LibVulpes-1.12.2-0.2.8-37-universal.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3460.jar
AdvancedRocketry-1.12.2-1.4.0-102-universal.jar

https://gist.github.com/phit/062c0fb634c29fb877caca8a5de6500e

test world: https://phit.link/s/adv_rocketry_launch_test.zip

**Comment by phit** [comment] 2018-12-30 23:27
was unable to reproduce this with these mods and all stock configs

jei_1.12.2-4.13.1.225.jar
LibVulpes-1.12.2-0.3.0-45-universal.jar
AdvancedRocketry-1.12.2-1.4.1-119-universal.jar
spongeforge-1.12.2-2768-7.1.5-RC3513.jar
griefprevention-1.12.2-4.3.0.662.jar
LuckPerms-Sponge-4.3.62.jar

gonna close this, if this is still an issue for you please provide a test world

**Closed as completed by phit** 2018-12-30 23:27 UTC
Labels: status: needs testing, version: 1.12
