### ISSUE TITLE
MeeCreeps - Sponge issue (dupe)

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1865] opened 2017-11-19 02:22 UTC
Hi all, this issue is a Dupe bug with the Creep Cube.. place it down, set it to "flatten an area" and select 9x9.
It will then go to the nearest block and break it, it breaks the same block over and over again but also drops the item each time.

This does not happen on a Single Player world.

meecreeps-1.12-0.1.3beta.jar
[fml-server-latest.log](https://github.com/SpongePowered/SpongeForge/files/1485237/fml-server-latest.log)

SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-cc44fdf
SpongeForge: 1.12.2-2529-7.0.0-BETA-2736
Minecraft Forge: 14.23.0.2531

**Comment by ryantheleach** [comment] 2017-11-19 16:54
@Keaton1188 How is it breaking the same block over and over again? is it in a protected area?

**Comment by Keaton1188** [comment] 2017-11-19 23:59
Not in a protected area, just constantly breaks the nearest block but doesn't "break" it if that makes sense.
It goes to but just drops the block.

Example, place a Creep Cube next to a solar panel, set it to flatten an area then it will constantly break that item.

**Comment by RedNesto** [comment] 2017-11-23 18:32
I could not reproduce it with _only_ MeeCreeps and SpongeForge (the same versions as yours).

**Comment by phit** [comment] 2017-12-09 17:43
Can't reproduce either with 
spongeforge-1.12.2-2555-7.0.0-BETA-2763.jar
meecreeps-1.12-1.0.0.jar

Closing this for now, if this still an issue for you please provide a way to reproduce and I'll reopen this issue.

**Closed as completed by phit** 2017-12-09 17:43 UTC
Labels: status: more information needed, version: 1.12
