### ISSUE TITLE
SF Build 2336 break plugins

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1517] opened 2017-05-16 05:38 UTC
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2336
- Forge version: forge-1.10.2-12.18.3.2281-universal
- Java version: 1.8.0_131
- Operating System:
 - [x] Windows

- Plugins/Mods: 
Plugins (105): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, CoFH Core, Actually Additions, Baubles, Botania, Akashic Tome, Applied Energistics 2, Morph-o-Tool, Psi, Quark, AutoRegLib, Bad Wither No Cookie!, Bagginses, Better Builder's Wands, Biomes O' Plenty, Guide-API, Just Enough Items, Blood Magic: Alchemical Wizardry, Bookshelf, CodeChicken Lib, Brandon's Core, Chameleon, Chisel, MCMultiPart, Chisels & Bits, CodeChicken Core, IndustrialCraft 2, Compact Solar Arrays, CraftTweaker JEI Support, MineTweaker 3, Waila, Dark Utilities, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, EnderCore, Ender IO, Extra Utilities 2, Zero CORE, Extreme Reactors, Fast Leaf Decay, Flat Colored Blocks, FoamFix, Gravestone, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, Simple Inventory sorting, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Mercurius, Not Enough Wands, Pam's HarvestCraft, Railcraft, Ranged Pumps, Thermal Foundation, Redstone Arsenal, Storage Drawers, Refined Storage, RFTools, RFTools Control, RFTools Dimensions, Super Circuit Maker, Thermal Expansion, I Can See Everything, What Are We Looking At, XNet, EconomyLite, NuVotifier, Enjin Minecraft Plugin, GriefPrevention, Holograms, ItemAuction, LootChest, LuckPerms, MMCReboot, MMCRestrict, Nucleus, PlaceholderAPI, Nucleus Gluon, PayDay, Prism, RankUpper, ServerListPlus, VotifierListener, SleepVote, UltimateChat, WorldEdit

**What is the expected result?**
Server start up, but alot of sponge plugins are failing check provided log

**What is the current result?**
https://gist.githubusercontent.com/FiveEYZ/75dcec5b66e015c76876141512e4c8ff/raw/a4cbfc966a866ee4be4066a5113b3bc79c1790dd/fml-server-latest.log

reverting back to 1.10.2-2281-5.2.0-BETA-2330 will fix the errors

**Comment by DrZoddiak** [comment] 2017-05-16 08:37
I'm having a similar issue. Running only SF2336 and Luckperms.
Latest: https://gist.github.com/DrZoddiak/8e01e1bb6e759b2ebdd705e73e70632e
fml-server-latest: https://gist.github.com/DrZoddiak/70bde35dddde0c5933d3572eb2cdcc68

**Comment by mkrtes** [comment] 2017-05-16 10:47
I have the same problem.

**Comment by sintaxcz** [comment] 2017-05-16 16:33
I have the same problem.

**Comment by phit** [comment] 2017-05-16 17:18
dupe of SpongePowered/SpongeCommon/issues/1354

**Closed as completed** 2017-05-16 17:20 UTC
Labels: resolution: duplicate
