### ISSUE TITLE
SpongeForge Overloaded (Issue 2)

### ISSUE THREAD

**Issue by Mysterizon** [SpongePowered/SpongeForge#762] opened 2016-07-18 01:51 UTC
This issue is related to Sponge Forge Leaves not decaying (Issue 1):
https://github.com/SpongePowered/SpongeForge/issues/760

**ISSUE 2**: While the Forge server is running with SpongeForge mod, it show a message something like "did the time system changed or is the server overloaded, skipping 80 ticks"
i think the leaf decaying may have to do with it..  no telling. so please look in it. 

**Additional Information** (you can read this or not): 

since i chopped down a lot of trees, and none of them, the leaves are decaying or despawning. It cause my world to have a map corrupted because of Issue 2, it was overloaded.. the reason is there are too many items on the ground and it takes time for them to despawn. 

when leaves are not decaying, it drop three things: apples, Sticks, and sapling. I used mods following: 
-AutoSapling
-Immersive Craft
-FastLeafDecay

**Comment by kinggoesgaming** [comment] 2016-07-18 02:09
@Mysterizon can you show your server specs and how much memory you are giving it?

its very much likely that the server is overloaded...

**Comment by Mysterizon** [comment] 2016-07-18 04:01
alright.. 
Here is the spec of server following: 

**Forge-1.10.2 - 12.18.1.2011**
-autosapling
-bauble
-BiomeOplenty
-botania
-chameleon
-chisel&bits
-dynmap
-fastleafdcay
-immersive craft
-mantle
-mineralogy
-projectborder
-projectinventory
-projectportals
-realistic torches
-storagedrawer
-tconstruct
-betterfps (improve server's performance.. since there is no cauldron or bukkit for 1.10.2)
the RAM have 3G allocated to it (i think it should be enough) 

yeah i am not sure what caused "overloaded" and i know its not the system time that changed. 
i am aware that SpongeForge is still in development and its not completed. yet.

**Comment by gabizou** [comment] 2016-07-18 18:44
> -betterfps (improve server's performance.. since there is no cauldron or bukkit for 1.10.2)

Having looked at the source code, there's not much performance improvement server side that it's achieving. SpongeForge already bundles quite a few optimizations and performance tweaks by itself.

There's a possibility of some performance issues with the CauseTracking system needing to be tweaked in 1.10, but that's under heavy development and a moderate change with block change handling is coming into play very soon.

What you can do for now however is run a timings (at least 3 minutes of server uptime after initial world load) with `/sponge timings report`. The generated timings report will give more insight as to what could be causing the slow down.

**Comment by Mysterizon** [comment] 2016-07-19 01:25
Alright. i will do that.. well i can use your advice to improve the server's performance even that mean i have to remove betterfps

**Comment by Zidane** [comment] 2016-08-01 23:54
Closing this as perf improvements have been made.

**Closed by Zidane** 2016-08-01 23:54 UTC
