### ISSUE TITLE
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException   

### ISSUE THREAD

**Issue by xAlicatt** [SpongePowered/SpongeForge#1165] opened 2017-01-06 07:38 UTC
```
[23:25:17] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/entity/EntityAreaEffectCloud to metadata cache
[23:25:17] [main/INFO] [mixin/]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[23:25:17] [main/INFO] [Sponge/]: /******************************************************************************************************************************************************************************************************/
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /* Oh dear. Something went wrong and the server had to shut down!                                                                                                                                     */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /* A critical error was encountered while blending Sponge with Forge!                                                                                                                                 */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*   Possible causes are:                                                                                                                                                                             */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*    * An incompatible Forge "core mod" is present. Try removing other mods to                                                                                                                       */
[23:25:17] [main/INFO] [Sponge/]: /*      see if the problem goes away.                                                                                                                                                                 */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*    * You are using the wrong version of Minecraft Forge. You must use the                                                                                                                          */
[23:25:17] [main/INFO] [Sponge/]: /*      correct version of Forge when running Sponge, this version is for                                                                                                                             */
[23:25:17] [main/INFO] [Sponge/]: /*      12.18.3.2202 (you are running 12.18.3.2202)                                                                                                                                                   */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*    * An error exists in Sponge itself. Ensure you are running the latest version                                                                                                                   */
[23:25:17] [main/INFO] [Sponge/]: /*      of Sponge.                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*    * Gremlins are invading your computer. Did you feed a Mogwai after midnight?                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /* Technical details:                                                                                                                                                                                 */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*      Failed on class : N/A                                                                                                                                                                         */
[23:25:17] [main/INFO] [Sponge/]: /*         During phase : DEFAULT                                                                                                                                                                     */
[23:25:17] [main/INFO] [Sponge/]: /*                Mixin : entity.IMixinAreaEffectCloud                                                                                                                                                */
[23:25:17] [main/INFO] [Sponge/]: /*               Config : mixins.common.core.json                                                                                                                                                     */
[23:25:17] [main/INFO] [Sponge/]: /*           Error Type : org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /*            Caused by : Unknown                                                                                                                                                                     */
[23:25:17] [main/INFO] [Sponge/]: /*              Message : @Mixin target type mismatch: net.minecraft.entity.EntityAreaEffectCloud is not an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Interface@54402c04 */
[23:25:17] [main/INFO] [Sponge/]: /*                                                                                                                                                                                                    */
[23:25:17] [main/INFO] [Sponge/]: /******************************************************************************************************************************************************************************************************/

```

**Comment by axle2005** [comment] 2017-01-06 12:50
All this tell them is that a core mod is present. It doesn't have a log (FML log) or anything else to help them figure out what the issue is. 

IF I had to take a stab at it, I know 3 mods that currently cause this issue. 

Applied Energistics
Yunomakegoodmap
Itsbecauseyounogoodspawn

You would need to remove them or get a patched version. 

Additionally there is something called Sponge BootStrap on the forums that could help you actually load the server.

**Comment by FiveEYZ** [comment] 2017-01-06 13:00
wasn't it FoamFix that generated this error?

here is what Yunomakegoodmap will do https://github.com/SpongePowered/SpongeForge/issues/1153

**Comment by ktole1999** [comment] 2017-01-06 17:25
need to know what version forge the server is running as well as other mods.

**Comment by xAlicatt** [comment] 2017-01-06 17:54
AE2 is probably the cause then...I will look into seeing if it will run without it and I will look into patchs and bootstrap. thank you @axle2005 

@ktole1999 It's running forge-1.10.2-12.18.3.2202-universal

current modlist is here: https://minecraft.curseforge.com/projects/jakspack-1-10-2

**Comment by Aaron1011** [comment] 2017-01-06 21:00
@FiveEYZ: This is a different error from both the foamfix and Yunomakegoodma errors.

**Comment by Aaron1011** [comment] 2017-02-09 18:48
@xAlicatt: Are you able to reproduce this wit the latest SpongeForge?

**Comment by xAlicatt** [comment] 2017-02-10 00:51
I have a working server using spongeforge-1.10.2-2202-5.1.0-BETA-2070.jar. I have also long since dropped AE2 from my pack, so if that was the cause, it could be why it's working now.

**Comment by phit** [comment] 2017-07-19 18:04
dupe of #1473 or some other coremod, anyway its not a sponge bug

**Closed as completed** 2017-07-19 18:07 UTC
Labels: type: mod incompatibility
