### ISSUE TITLE
DeathUpdateState error

### ISSUE THREAD

**Issue by MoeShimaKaze** [SpongePowered/SpongeForge#2297] opened 2018-07-11 15:32 UTC
- Forge Version:1.12.2-14.23.4.2705
- Java Version:jre1.8.0_171
- SpongeForge Version:1.12.2-2705-7.1.0-BETA-3291
Mod list:https://pastebin.com/Zsf5A1wL
Plugins List:https://pastebin.com/bfLvYCpr
Error logs:
  - https://pastebin.com/K4LcY0za 
  -  (Edit: Better formatting, https://gist.github.com/ryantheleach/ae6122a4d02cb7db6eca7f557da7b114)

**Comment by ryantheleach** [comment] 2018-07-12 06:38
@MoeShimaKaze Do you have any steps to get this to occur? Is it constant? Does it happen on an empty server with just you?

**Comment by MoeShimaKaze** [comment] 2018-07-12 10:51
I didn't how the problem cause
but sometimes the errors logs appear...

**Comment by phit** [comment] 2018-09-14 01:35
@MoeShimaKaze does this still happen on newer versions (3400+)?

**Comment by phit** [comment] 2018-09-26 05:56
Closing this for now. If this is still an issue for you, please let us know and provide relevant new info.

**Comment by phit** [comment] 2018-09-30 17:49
found the cause by accident, die while having an item on your cursor

https://gist.github.com/phit/21b1640ea0fcd2bd4612beaeb22469af

repro, hop into a lava lake then die with your inventory open and an item on your cursor

**Comment by ghost** [comment] 2019-01-01 02:06
Perhaps this issue could be related to #2536

**Closed as completed** 2019-01-25 00:43 UTC
Labels: type: bug, system: phase tracker, version: 1.12
