### ISSUE TITLE
Intangible not updating with sponge? 

### ISSUE THREAD

**Issue by XPownage** [SpongePowered/SpongeForge#551] opened 2016-02-24 16:43 UTC
The problem i'm having with sponge right now is when ever I throw blue crystals into lava is usually turns the lava into molten blue lava the first try. But when ever sponge is installed it can take up to 30 blue crystals to be thrown into lava for intangible to register that I even threw one... This also affects the altar as well so if I wanted to craft something it just doesn't work at all. Sorry there isn't much to go off here and there isn't even an error and I've checked the logs and there is nothing on it that has to do with this.

**Comment by kashike** [comment] 2016-02-24 16:44
https://github.com/SpongePowered/SpongeForge/issues/537

**Comment by XPownage** [comment] 2016-02-24 16:45
Well it would have been nice if the post wasn't closed until it was fixed... Eh

**Comment by kashike** [comment] 2016-02-24 16:48
Have you tried the **latest** build of SpongeForge?

**Comment by XPownage** [comment] 2016-02-24 17:30
I used the latest build from last night more of a dev build actually that I got from @bloodmc and it seemed to fix most of the bugs but the intangible part wasn't fixed. Unless the latest public build from 2 am this morning fixed it because I have players who come on my server and I don't want to swap out builds if I know it isn't fixed.

**Comment by AuricPolaris** [comment] 2016-02-25 04:34
I am currently on Sponge 1164 (latest as of this post to my knowledge) and still have this issue. Just reporting in. :)

**Comment by Aaron1011** [comment] 2016-02-26 03:41
@XPownage: I'm unable to reproduce this - I can reliably turn lava into molten blue lava, with and without SpongeForge. Additionally, from looking at Intangible, it doesn't seem like any of Sponge's changes would affect throwing blue crystals into lava.

The issue seems to be that when throwing crystals into lava at a certain angle (with or without SpongeForge), it's not properly held in place by Intangible. Since Intangible only freeze the movement of the Item on the y-axis, it seems that throwing in a crystal from the side can cause it to be burned up, due to it moving too far into the lava horizontally.

**Comment by XPownage** [comment] 2016-02-26 16:17
@Aaron1011  Mmm... alright that makes sense but the altar for crafting things with intangible doesn't work with sponge, I assure you that is 100% broken.

**Comment by Aaron1011** [comment] 2016-02-26 17:01
@XPownage: Oops, my bad: I didn't see that you were having another issue.

I'm going to close this issue, since the molten blue lava issue was resolved. Could you re-open an issue for just the altar bug?

**Comment by Aaron1011** [comment] 2016-02-26 17:01
@XPownage: Oops, my bad: I didn't see that you were having another issue.

I'm going to close this issue, since the molten blue lava issue was resolved. Could you re-open an issue for just the altar bug?

**Closed by Aaron1011** 2016-02-26 17:01 UTC
