### ISSUE TITLE
Enchantment glow 

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeForge#470] opened 2015-12-30 15:35 UTC
This issue might be more related to spongeapi.

It would be nice to have an option to add just an enchantment glow to an item without enchanting the item.
Im aware that this is a bug in minecraft, but well it is the good one.
Basically server sends unknown enchantment to a client and the client displays the nonexisting enchantment as the glow effect.

Similar approach worked in bukkit and i excepted it will work in sponge as well.

The code i tried:

    itemStack.offer(Keys.ITEM_ENCHANTMENTS,Arrays.asList(ENCHANTMENT_GLOW));
    pl.setItemInHand(itemStack);

      public static ItemEnchantment ENCHANTMENT_GLOW = new ItemEnchantment(new Enchantment() {
        @Override
        public String getName() {
            return "Glow";
        }

        @Override
        public int getWeight() {
            return 0;
        }

        @Override
        public int getMinimumLevel() {
            return 0;
        }

        @Override
        public int getMaximumLevel() {
            return 0;
        }

        @Override
        public int getMinimumEnchantabilityForLevel(int i) {
            return 0;
        }

        @Override
        public int getMaximumEnchantabilityForLevel(int i) {
            return 0;
        }

        @Override
        public boolean canBeAppliedToStack(ItemStack itemStack) {
            return true;
        }

        @Override
        public boolean canBeAppliedByTable(ItemStack itemStack) {
            return true;
        }

        @Override
        public boolean isCompatibleWith(Enchantment enchantment) {
            return true;
        }

        @Override
        public String getId() {
            return getName();
        }

        @Override
        public Translation getTranslation() {
            return null;
        }
    }, 1);                    

Did i do something wrong, or is this feature/bug not supported. If so are there any plans to support this "bug"?

**Comment by ryantheleach** [comment] 2015-12-30 18:18
Just create an empty EnchantmentData and attach it to the item?

**Comment by gravityfox** [comment] 2016-01-03 14:19
Have a One-Liner Solution!™

`stack.offer(Sponge.getDataManager().getManipulatorBuilder(EnchantmentData.class).get().create());`

**Comment by JBYoshi** [comment] 2016-01-03 23:54
@gravityfox Does that actually work?

**Comment by gravityfox** [comment] 2016-01-04 00:05
Yep.

I have a wand command in FoxCore. That line is in my code:

https://github.com/FoxDenStudio/FoxCore/blob/master/src/main/java/net/foxdenstudio/sponge/foxcore/plugin/command/CommandWand.java#L94

I can confirm it works.

**Comment by Aaron1011** [comment] 2016-02-26 02:06
Closing this, as @gravityfox has already pointed out a way to do this. However, the API most likely won't support this any more explicitly, because as @NeumimTo pointed out, this is really a bug.

If more discussion is needed, an issue can be opened on SpongeAPI.

**Closed by Aaron1011** 2016-02-26 02:06 UTC
