### ISSUE TITLE
Water & Lava Will Not Spread, Even With a Block Update

### ISSUE THREAD

**Issue by xChristopher210** [SpongePowered/SpongeForge#535] opened 2016-02-13 03:26 UTC
This just came across from one of my players so I decided to test it myself. Water nor Lava will not spread even if I place a block next to it to update it. It still stays as a source block but does not move at all.

Server details:
SpongeForge: 1151
Forge: 1732 (1.8.9)
Pixelmon: 4.2
RAM: 16GB

**Comment by windy1** [comment] 2016-02-15 21:04
I am unable to reproduce this. Have you tried without Pixelmon?

**Comment by XPownage** [comment] 2016-02-16 06:17
I have the same problem as well using FTB Unstable. Water or lava will not flow and multi block structures like a nether portal will not light either. So pretty much EVERY block in the game is frozen and you can't update it. Keep in mind everything works for the first 5-10 minutes the server is online and after that everything freezes. You can still open chests and break blocks fine as well as a furnace works. But pretty much everything else is broken with tick updates. (Including redstone)

**Comment by hunter688** [comment] 2016-02-20 12:04
I have similar issues. Fo example cannot build iron/snow golems and others multiblock structures. Sand, Gravel not falling.

**Comment by Aaron1011** [comment] 2016-02-20 17:02
@hunter688 @XPownage: This is a known issue. It has to do with the current cause tracking code, which has some bugs. After @gabizou's refactor is merged, these bugs should be fixed.

**Comment by XPownage** [comment] 2016-02-21 02:39
@Aaron1011 Do you have any time frame when we will see an update with his merged?

**Comment by gabizou** [comment] 2016-02-21 05:15
@XPownage Refer to #538 as it's a fairly large rewrite of the current system.

**Comment by XPownage** [comment] 2016-02-21 05:43
@gabizou So about another 1-2 weeks? Just trying to get an outline for when this could possibly be fixed.

**Comment by gabizou** [comment] 2016-02-21 07:16
Something like that, yeah. I'm aiming to have it completed and working by the end of this coming week. There are a few bugs and problems that need a decision to be made on how to solve them.

**Comment by bloodmc** [comment] 2016-02-22 07:24
This should not be happening last I tested. Something must of broken it recently.
@hunter688 @XPownage can you please test builds and let me know which build this issue started to occur in?

**Comment by XPownage** [comment] 2016-02-22 17:52
@bloodmc I have actually tried every build from 1147 and up and none work. Water and Lava does work for the first 10-30 minutes and then everything stops working. Like lighting nether portals, making iron golems etc.

**Comment by bloodmc** [comment] 2016-02-22 18:01
@XPownage Did you test without any plugins or mods? Only test with SpongeForge.

**Comment by Aaron1011** [comment] 2016-02-23 00:33
@bloodmc: I was to reproduce this on the latest Sponge. Nothing has changed with cause tracking in master recently, so it should still be reproduceable.

I haven't found a sure-fire way to trigger this, but a pretty consistent method seems to be to cause a fair amount of chunk generation (through flying around), and then attempting to build a structure such as a snow or iron golem.

**Comment by bloodmc** [comment] 2016-02-23 05:15
@Aaron1011 OK thanks, I'll take a look at it soon.

**Comment by bloodmc** [comment] 2016-02-23 15:14
@Aaron1011 Does this happen in single player too?

**Comment by XPownage** [comment] 2016-02-23 16:15
@bloodmc I tried warmroast but when trying to start it... well it didn't work. 

I got this error

Starting a server on /199.168.96.138:8080...
Once the server starts (shortly), visit the URL in your browser.
Note: The longer you wait before using the output of that webpage, the more accurate the results will be.
java.rmi.ConnectException: Connection refused to host: 204.152.38.112; nested exception is:
        java.net.ConnectException: Connection refused
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130)
        at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source)
        at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2432)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229)
        at com.sk89q.warmroast.WarmRoast.connect(WarmRoast.java:129)
        at com.sk89q.warmroast.WarmRoast.main(WarmRoast.java:327)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
        at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
        ... 10 more

But yes I had 3 plugins they were: Name API, EssentialCmds-7.4e, and ExtraPermissions-0.4.9

**Comment by liach** [comment] 2016-02-23 16:33
Why are you using warmroast? It tried to launch a web based UI but it cannot, so it crashed. Try without warmroast once.

**Comment by XPownage** [comment] 2016-02-23 16:35
@liach I tried it without warmroast and nothing changed. I'm just curious how do I fix the web based UI problem.

**Comment by liach** [comment] 2016-02-23 18:06
Reproduce the crash again on the client and post the full log from `logs/fml-client-latest.log` in the run directory.

**Comment by hunter688** [comment] 2016-02-23 18:19
@bloodmc singleplayer is ok, forge server without sponge too

**Comment by XPownage** [comment] 2016-02-23 19:08
@liach Sponge never crashed... The server was never effected by warmroast. I'm just curious how to get warmroast up and running so I can see logs of what might be causing sponge powered to stop block tick updating.

**Comment by bloodmc** [comment] 2016-02-23 19:32
I already discovered cause, will have a fix eventually when I get some more time =). Essentially one of our flags are being stuck in the wrong state.

**Comment by XPownage** [comment] 2016-02-23 19:35
@bloodmc Alright, I hope its some time soon! Within a week would be the best but obviously I understand its a time consuming thing to do.

**Comment by bloodmc** [comment] 2016-02-23 19:46
@XPownage @hunter688 already fixed, I just need to test it.

**Comment by XPownage** [comment] 2016-02-23 19:51
@bloodmc So could this be in the next sponge release if all goes well? Or will be take a couple days?

**Comment by bloodmc** [comment] 2016-02-23 20:12
@XPownage I'll have it fixed today. Just getting a build for hunter688 to test.

**Comment by XPownage** [comment] 2016-02-23 20:20
@bloodmc By any chance could I have the build as well? I'd like to test it as well.

**Comment by bloodmc** [comment] 2016-02-23 21:22
@XPownage Sure, test this build 

https://www.dropbox.com/s/uvsptyp3w99pbhy/spongeforge-1.8.9-1732-3.1.0-BETA-0.jar?dl=0

**Comment by XPownage** [comment] 2016-02-23 21:32
@bloodmc alright i'll test it out and see if the problem persists.

**Comment by XPownage** [comment] 2016-02-23 22:02
@bloodmc Well this is very interesting every 10ish minutes everything freezes on the server and I get a timeout same with everyone else on my server... This never occurred before, bug?

**Comment by XPownage** [comment] 2016-02-23 22:06
@bloodmc Could have been a plugin I had called Twentyticks so I just removed it and i'm going to try again.

**Comment by XPownage** [comment] 2016-02-23 22:07
@bloodmc Ok... It wasn't that its deferentially a bug.. 
Here is the error.

[22:07:51] [Netty Epoll Server IO #0/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException

**Comment by XPownage** [comment] 2016-02-23 22:09
@bloodmc   and this error
[22:08:24] [Timer-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at java.util.TimerThread.mainLoop(Timer.java:555)

**Comment by JBYoshi** [comment] 2016-02-23 22:51
Could you post the full log?

**Comment by XPownage** [comment] 2016-02-23 22:53
@JBYoshi Well... there was the only 2 errors and those were them nothing else popped up except people joining or being disconnected by the first error, and randomly out of no where the second error started to occur. Also posting the whole log would be horrible... Its HUGE

**Comment by kenzierocks** [comment] 2016-02-23 22:57
Then use pastebin or gist.github.com.

**Comment by XPownage** [comment] 2016-02-23 23:01
@kenzierocks @JBYoshi @bloodmc  http://pastebin.com/AcywmxWH

**Comment by XPownage** [comment] 2016-02-23 23:02
oh... I see there is a crash report! oops ;p http://pastebin.com/jdGndiVv

**Comment by JBYoshi** [comment] 2016-02-23 23:07
```
[22:08:14] [Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[22:08:14] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
```
Well, there's your problem... the server got hung up.

**Comment by XPownage** [comment] 2016-02-23 23:09
Yup... I see that. The crash report shows that Cause tracker caused it.

**Comment by JBYoshi** [comment] 2016-02-23 23:10
Not necessarily; that's just where it was at the time the watchdog thread halted the server.

**Comment by XPownage** [comment] 2016-02-23 23:15
Mmm.. ok

**Comment by bloodmc** [comment] 2016-02-23 23:48
@XPownage I'll need a warmroast sample when the issue occurs. The default port is 23000, it seems you attempted to run on 8080 which was refused(firewall blocking). Use a port that is open and it will work fine.

**Comment by XPownage** [comment] 2016-02-23 23:58
@bloodmc I don't think that is the problem if you see the error its trying to bind to another IP than I put.

**Comment by bloodmc** [comment] 2016-02-24 00:06
@XPownage paste the EXACT line you are using to launch warmroast.

**Comment by XPownage** [comment] 2016-02-24 00:07
@bloodmc   java -Djava.library.path=/usr/java/jdk1.8.0_60/jre/bin -cp /usr/java/jdk1.8.0_60/lib/tools.jar:warm.jar com.sk89q.warmroast.WarmRoast --thread "Server thread" --bind 199.168.96.138

**Comment by bloodmc** [comment] 2016-02-24 00:07
@XPownage remove the --bind and see if that works.

**Comment by XPownage** [comment] 2016-02-24 00:07
@bloodmc same thing.

**Comment by XPownage** [comment] 2016-02-24 00:09
@bloodmc The IP it is trying to bind with is the main hosts IP and that is causing problems... As you can see.

**Comment by bloodmc** [comment] 2016-02-24 00:09
@XPownage Just join our IRC channel on irc.esper.net #spongedev

**Comment by XPownage** [comment] 2016-02-24 00:12
@bloodmc Ok I joined

**Comment by bloodmc** [comment] 2016-02-24 01:28
@XPownage @hunter688 OK I discovered cause of lag when loading excessive amount of chunks. I'll update my jar in a few.

**Comment by XPownage** [comment] 2016-02-24 01:37
@bloodmc alright

**Comment by bloodmc** [comment] 2016-02-24 01:48
@XPownage https://www.dropbox.com/s/uvsptyp3w99pbhy/spongeforge-1.8.9-1732-3.1.0-BETA-0.jar?dl=0

Redownload and try again.

**Comment by XPownage** [comment] 2016-02-24 01:59
@bloodmc You can monitor the server as you want with this ip 199.168.96.138:23000

**Comment by bloodmc** [comment] 2016-02-24 02:16
@XPownage is it working now?

**Comment by XPownage** [comment] 2016-02-24 02:21
@bloodmc Looks like it, I'll know more after its been up for about an hour.

**Comment by XPownage** [comment] 2016-02-24 02:21
@bloodmc I take that back... Water isn't working

**Comment by bloodmc** [comment] 2016-02-24 02:28
@XPownage Try https://www.dropbox.com/s/uvsptyp3w99pbhy/spongeforge-1.8.9-1732-3.1.0-BETA-0.jar?dl=0

I made another change.

**Comment by XPownage** [comment] 2016-02-24 02:59
@bloodmc alright

**Comment by XPownage** [comment] 2016-02-24 03:37
@bloodmc Potential bug, when ever sponge is enabled even after you updated it altars from intangible don't work when you want to craft something.

**Comment by bloodmc** [comment] 2016-02-24 04:37
@XPownage is the bug still occuring?

**Comment by hunter688** [comment] 2016-02-24 06:46
tested, looks like problem with chunks and server lag solved too

**Closed** 2016-02-24 06:57 UTC

**Comment by XPownage** [comment] 2016-02-24 15:34
@bloodmc It was with the last build you wanted me to test, if there is another build you have ready i'm more than happy to assist.

**Comment by bloodmc** [comment] 2016-02-24 15:59
@XPownage What is still occuring? I'm just concerned with the bug related to this ticket. Any new bugs should go into a new ticket. 
@hunter688 already confirmed that everything is working as expected.

**Comment by XPownage** [comment] 2016-02-24 16:04
@bloodmc Well using a mod called intangible when you use something called an altar and you try to craft something with the altar nothing happens like it would without sponge. Also if you throw a crystal into lava which is suppose to make blue lava or something on that order is usually takes 3-10 tries for the game to actually see i'm throwing an item in. If the item doesn't show its burning when it goes in then it doesn't work. This always worked the first time until after I installed sponge.

**Comment by bloodmc** [comment] 2016-02-24 16:07
@XPownage This has nothing to do with this ticket. Please create a new ticket with your issue.

**Comment by XPownage** [comment] 2016-02-24 16:09
@bloodmc Oh... I thought this maybe had something to do with sponge, sorry

**Comment by bloodmc** [comment] 2016-02-24 16:11
@XPownage it does, just not related to this ticket. Just create a new issue with the problem you are having and we will get to it when we have time.

**Comment by XPownage** [comment] 2016-02-24 16:12
@bloodmc alright

**Comment by hunter688** [comment] 2016-03-28 17:40
looks like this bug is back :-( spongeforge build 1227

**Comment by ghost** [comment] 2016-12-04 13:19
It looks like this bug returns in the SF build 1933 - build 1930 is ok

**Comment by stephan-gh** [comment] 2016-12-04 13:25
@hunter688 Have you tested with the latest build? The latest build is `1.10.2-2171-5.1.0-BETA-1949`

**Comment by ghost** [comment] 2016-12-04 13:28
Something is with my browser cache, i see latest 1933.

**Comment by stephan-gh** [comment] 2016-12-04 13:29
The Forge downloads page is having problems currently, for now you can access the latest build at https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2

**Comment by ghost** [comment] 2016-12-04 13:35
looks fine, thanks for suggestion

**Comment by ghost** [comment] 2016-12-04 14:07
latest build works without problem, thx
