### ISSUE TITLE
any item duped when placed 

### ISSUE THREAD

**Issue by dezil** [SpongePowered/SpongeForge#2703] opened 2019-04-20 21:05 UTC
I am currently running

- SpongeForge version: 1.12.2-2768-7.1.6-RC3665
- Forge version: 14.23.5.2814
- Java version: 1.8
- Operating System: Ubuntu

 Plugins (18): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, GriefPrevention, Integrity, LolnetAPI, LolnetForceRestarter, LuckPerms, Nucleus, Prism, ServerManager, Shop, SkyClaims, Sledgehammer, SpongePrometheusExporter, WorldEdit, spark

Mods (197): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Carry On, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Chunk Manager, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Extra Cells Patch, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, MekanismGenerators, Mercurius, Minecraft Multipart Plugin, Misc Server Utils, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, SilentBoss, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

Issue Description
all players on the server can place blocks with out it using the block from there inventory 

while this happens we are getting https://pastebin.com/EwzFyMAZ this error in the log

**Comment by Shybella** [comment] 2019-04-21 00:44
I had this happen suddenly last night on 3616 randomly, spent hours waiting for it to recur but didn't

**Comment by dezil** [comment] 2019-04-21 00:46
we have not been able to reproduce it but have had it happen randomly across multiple packs on multiple sponge versions after and including 3616

**Comment by julianubico** [comment] 2019-04-21 20:12
I've had this as well on 3616. Automatic user from Extra Utilities 2 may be the cause of this.

- **Proof:**

https://gyazo.com/58409a717d91fe1520ba2cd24b53cbfa

https://www.twitch.tv/videos/412726009

**Comment by phit** [comment] 2019-04-21 20:52
previous issue: https://github.com/SpongePowered/SpongeForge/issues/2698

**Comment by gabizou** [comment] 2019-04-21 21:00
From the stack trace, looks to be a nucleus exception on the interaction listener ends up causing the item not to be used, but the placement still to be tracked. I wouldn't really say it's a bug on Sponge's side, since the exception is occurring from a plugin's codebase, in this case, the `Optional` is not being checked, and Sponge doesn't have any real way to "roll back" if an exception occurred during a listener in this case, so it will still end up processing the blocks placed.

@dualspiral I'm almost sure this is from FakePlayers having fun issues with not being registered in any specific way, but I doubt Sponge can really do anything for this, since the interaction managers are always expected to process on fake players.

I wouldn't say this is a dupe in particular with Sponge, but a side effect of a plugin/mod throwing an exception and there being no feasible way to safeguard against already captured changes.

In the case it is not clear: I'm closing this issue because the duplication appears to be stemming from a plugin throwing an exception during placement from fake players, not something Sponge can safeguard against, since the exception is being caught, but no feasible way to roll back fake player changes. If however, without Nucleus being installed, the duplication is still reproduced, the issue needs to be abundantly clear on the setup of what the duplication is requiring to reproduce (because SpongeForge alone, or with some of these mods that I've had tested for the last month or so are not causing duplications). I understand this is a large mudpack, but also understand that as developer time is fairly limited (based on how much can be given voluntarily), we're not going to test individual mods and SpongeForge to find out which combination recreates the duplication issue.

**Comment by dualspiral** [comment] 2019-04-21 21:02
Yeah, that'll be it exactly. I haven't handled that well - I'll put it on the Nucleus tracker and try to resolve it ASAP.

**Comment by phit** [comment] 2019-04-21 21:02
this has been fine in the past with the exact same mods?

**Comment by dualspiral** [comment] 2019-04-21 21:07
Wait, no, I fixed that ages ago. That's a _really_ old version of Nucleus.

Reported in https://github.com/NucleusPowered/Nucleus/issues/1334
Fixed in https://github.com/NucleusPowered/Nucleus/commit/74a8a7b44ef5a34f03a2bb7af0ce9ee9b71fa719

Update Nucleus and try again. Make sure, if a plugin is in the stacktrace, that you update before reporting...

**Comment by Shybella** [comment] 2019-04-21 21:54
You are right, I am using  1.6.1-S7.1
<https://ore.spongepowered.org/Nucleus/Nucleus/versions/1.6.1-S7.1>

Sorry about that.

**Comment by julianubico** [comment] 2019-04-21 23:09
> You are right, I am using 1.6.1-S7.1 <https://ore.spongepowered.org/Nucleus/Nucleus/versions/1.6.1-S7.1> Sorry about that.

I was using version 1.6.3, updating to latest version now. Thanks for the response dualspiral.

**Comment by dezil** [comment] 2019-04-22 02:48
ok nice having updated to the latest nucleus and running the server for 8 hours the Dupe bug appeared again except now there is nothing in the logs, so we have no way to pinpoint the issue

everything is as above except i updated nucleus

**Comment by gabizou** [comment] 2019-04-22 04:37
Going to need some precise replication instructions, whether it’s installing the mod pack, specific plugins etc. Also, is it immediately duping or only occasionally? Is the dupe happening based on timing or is it just happening as a random interaction? 

Just SpongeForge along I’ve not seen it dupe (yet, if it’s a corner case requiring multiple players online, I need to know)

**Comment by phit** [comment] 2019-04-22 04:39
when i've seen this it simply works for everyone, you just place any block and it doesnt get used and it stays like that until server reboot

**Comment by dezil** [comment] 2019-04-22 04:45
this is the hard part the dupe does not show up straight away we have only been able to get it to happen on production servers at this time i have had it happen on 3 diff mod packs
SF4
Stone Block2
Dungeons Dragons and Space Shuttles

in all instances the plugin load out is the same
the dupe at this time has taken several hours to show up as i said above 8 hours to get it to happen earlier today and we were monitoring the server the whole time

**Comment by LemADEC** [comment] 2019-04-22 10:46
We had the issue with Nucleus-1.9.3-S7.1-MC1.12.2 on our SkyFactory4 setup.

**Comment by julianubico** [comment] 2019-04-22 19:46
I've noticed this on StoneBlock 2 and Sky Factory 4 so far.

- **StoneBlock 2:**
```
Mods (238): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, AE2 Stuff, AE2 Wireless Terminals (AE2WTLib), Actually Additions, Actually Baubles, Akashic Tome, AngelRing 2 Bauble, AppleSkin, Applied Energistics 2, ArchitectureCraft, Attribute Fix, AutoRegLib, Avaritia, B.A.S.E, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, Blockcraftery, Bonsai Trees, Bookshelf, Botania, Brandon's Core, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, Building Gadgets, CXLibrary, Ceramics, Chameleon, Chance Cubes, Chest Transporter, Chickens, Chisel, Chisels & Bits, Clipboard, Clumps, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, ContentTweaker, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Custom Mod Rejection Messsage, Cyclic, Cyclops Core, Dark Utilities, Diet Hopper, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender IO endergy, EnderCore, EnderStorage, Environmental Tech, Ex Compressum, Ex Nihilo Creatio, Exchangers, Expanded Equivalence, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTB Library, FTB Quests, FTB Utilities, Farming for Blockheads, Fast Leaf Decay, FastFurnace, FastWorkbench, Faster Ladder Climbing, Flat Colored Blocks, Fluid Cows, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Framland, GasConduits, Hammer Core, Hatchery, Immersive Engineering, Industrial Foregoing, Industrial Meat, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Backpacks, Iron Chest, Item Filters, Just Enough Energistics, Just Enough Items, KleeSlabs, LLibrary, Let's Encrypt Craft, LootTweaker, MTLib, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, MightyEnderChicken, MineTogether, MineTogetherServer, Minecraft Multipart Plugin, Missing Pieces, Mod Tweaker, ModPack Utilities, More Chickens, More Furnaces, Morph, Morph-o-Tool, MrTJPCore, Mystical Agradditions, Mystical Agriculture, Mystical Lib, No Mob Spawning on Trees, NoTemaStahp, Not Enough Wands, OpenBlocks, OpenModsLib, OpenModsLib Core, OreExcavation, Oreberries, PackCrashInfo, Pam's HarvestCraft, PetRock, Placebo, PlusTiC, Project EX, Project Intelligence, ProjectE, ProjectRed Core, ProjectRed Expansion, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Psi, QuantumFlux, RF Lux, RFTools, RFTools Control, RFToolsPower, Random Things, RandomPatches, RandomTweaks, Reborn Core, Redstone Arsenal, Redstone Flux, Roost, Sampling Performance Profiler, Server Level Type, ShadowMC, Shadowfacts' Forgelin, Simply Jetpacks 2, Simply Light, Smooth Font Core, Snad, SonarCore, SpongeForge, Stone Chest, StoneBlock Dimensions, StoneBlockUtilities, Storage Drawers, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Terminal, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, Tiny Progressions, Too Many Efficiency Losses, TorchMaster, Trample Stopper, Twerk-Sim 2K16, UniDict, Universal Modifiers, Unloader, Valkyrie Lib, VanillaFix, Void Island Control, WanionLib, Wireless Crafting Terminal 2, WirelessRedstone-CBE, WorldEdit, XNet, Xtones, YABBA, YNot, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library, projectred-compat, uppers
```
```
Plugins (36): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AuraBlockLimit, AurionsVoteListener, AutoReset, BetterChunkLoader, BungeeTabListPlus-SpongeBridge, Buycraft, CarrotShop, CatClearLag, CommandUtils, Crash Detector, Dirt keepInventory, Dirt-Join-Leave-Messages, DirtCrashFailsafe, DirtRanks, DirtRespect, EconomyLite, Holograms, HuskyCrates, HuskyUI, Inventory Sync, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, NuVotifier, Nucleus, OnlineBroadcast, PixelAutoMessages, Prism, RankUpper, UltimateChat, spark
```


- **Sky Factory 4:**
```
Mods (193): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BNBGamingLib, Backups, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Custom Mod Rejection Messsage, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Extra Cells Patch, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, MekanismGenerators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Sampling Performance Profiler, Shadowfacts' Forgelin, Simple Generators, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers
```

```
Plugins (38): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AuraBlockLimit, AurionsVoteListener, AutoReset, BetterChunkLoader, BungeeTabListPlus-SpongeBridge, Buycraft, CarrotShop, CatClearLag, Command-Blocker, CommandUtils, Dirt keepInventory, Dirt-Join-Leave-Messages, DirtCrashFailsafe, DirtRanks, DirtRespect, EconomyLite, GriefPrevention, Holograms, HuskyCrates, HuskyUI, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, NuVotifier, Nucleus, OnlineBroadcast, PixelAutoMessages, PlayerDataReset-Plugin, Prism, RankUpper, SkyClaims, UltimateChat, spark```

**Comment by gabizou** [comment] 2019-04-22 20:20
Way too many mods and plugins.... Anyone able to reproduce with a minimal setup?

**Comment by dualspiral** [comment] 2019-04-22 20:25
I just took an intersection of the two mod sets in case that helps anyone reduce the mod list futher.

```
{AppleSkin,Applied Energistics 2,B.A.S.E,Baubles,Bed Patch,Bonsai Trees,Bookshelf,Building Gadgets,Ceramics,Chisel,Chisels & Bits,CodeChicken Lib,CoFH Core,CoFH World,CommonCapabilities,Compact Machines 3,ContentTweaker,Cooking for Blockheads,CraftTweaker2,CraftTweaker JEI Support,Cucumber Library,Custom Mod Rejection Messsage,Cyclic,Cyclops Core,Dark Utilities,EnderCore,EnderStorage,Extra Cells 2,Farming for Blockheads,FastFurnace,FastWorkbench,Flux Networks,FoamFix,FoamFixCore,Forge Microblocks,Forge Mod Loader,Forge Multipart CBE,Industrial Foregoing,Integrated Dynamics,IntegratedDynamics-Compat,Integrated Tunnels,IntegratedTunnels-Compat,Just Enough Items,KleeSlabs,MalisisCore,MalisisDoors,Mantle,McJtyLib,Mekanism,MekanismGenerators,Minecraft,Minecraft Coder Pack,Minecraft Forge,Minecraft Multipart Plugin,mob_grinding_utils,ModPack Utilities,Mod Tweaker,MTLib,Mystical Agradditions,Mystical Agriculture,OreExcavation,Placebo,ProjectE,Redstone Flux,RFToolsPower,Sampling Performance Profiler,Shadowfacts' Forgelin,Snad,SonarCore,Sponge,SpongeAPI,SpongeForge,Tesla Core Lib,Tesla Core Lib Registries,Thermal Dynamics,Thermal Foundation,Thermal Innovation,TickProfiler,Tinkers' Construct,Tinkers Tool Leveling,Tiny Progressions,TorchMaster,Universal Modifiers,uppers,Valkyrie Lib,WorldEdit,XNet,YNot}
```

**Comment by DrZoddiak** [comment] 2019-04-22 20:42
I compared the list Dual made, and compared it to "Dungeons Dragons and Space Shuttles" which Dezil reported also had these issues. The list got a bit smaller.
```
appleskin
b.a.s.e
baubles
bonsai trees
bookshelf
ceramics
chisel
cofh core
cofh world
contenttweaker
crafttweaker2
foamfix
industrial foregoing
integrated dynamics
integrated tunnels
mantle
mcjtylib
mod tweaker
mtlib
mystical agriculture
redstone flux
rftoolspower
thermal dynamics
thermal foundation
thermal innovation
torchmaster
xnet
```
Note: My list doesn't contain the Forge/SF/MCP listings, since I pulled the modlist from an external source (curse)

**Comment by dezil** [comment] 2019-04-22 21:45
looks like your list was not complete @DrZoddiak here is the list of all 3 packs inclusions
`AppleSkin
B.A.S.E
Baubles
Bonsai Trees
Bookshelf
Ceramics
Chisel
Chisels & Bits
CoFH Core
CoFH World
CodeChicken Lib
CommonCapabilities
ContentTweaker
CraftTweaker JEI Support
CraftTweaker2
Cucumber Library
Cyclic
Cyclops Core
Dark Utilities
EnderStorage
FastWorkbench
FoamFix
FoamFixCore
Forge Microblocks
Forge Mod Loader
Forge Multipart CBE
Industrial Foregoing
Integrated Dynamics
Integrated Tunnels
IntegratedDynamics-Compat
IntegratedTunnels-Compat
Just Enough Items
MTLib
MalisisCore
MalisisDoors
Mantle
McJtyLib
Minecraft
Minecraft Coder Pack
Minecraft Forge
Minecraft Multipart Plugin
Mod Tweaker
Mystical Agradditions
Mystical Agriculture
Placebo
RFToolsPower
Redstone Flux
Shadowfacts' Forgelin
Sponge
SpongeAPI
SpongeForge
Tesla Core Lib
Tesla Core Lib Registries
Thermal Dynamics
Thermal Foundation
Thermal Innovation
TickProfiler
Tinkers Tool Leveling
Tinkers' Construct
TorchMaster
Universal Modifiers
Valkyrie Lib
XNet`

**Comment by Yorkforce** [comment] 2019-04-22 22:47
Could this be anything to do with it?
https://pastebin.com/hCQJcHKU

Our logs are getting spammed with that while its happening

**Comment by LemADEC** [comment] 2019-04-22 23:26
Automated user causing console spam is how we've reproduced the issue initially.
We can also see it happening without the Automated user spam.

**Comment by gabizou** [comment] 2019-04-23 01:21
> Our logs are getting spammed with that while its happening

Fixed a few builds ago from [this commit](https://github.com/SpongePowered/SpongeForge/commit/0342bb0b6237d9a68e5447e76acf5b2432249ff6), update to 3662 at the very least.

**Comment by Yorkforce** [comment] 2019-04-23 02:43
We did update to latest a couple of hours ago, i'll report back here if the duping occurs again.

**Comment by gabizou** [comment] 2019-04-23 02:56
Ok, pushed a commit that may affect the issue, not 100% sure as I've not had a chance to test the commit or reproduce the issue itself. Try 3667 (it's not on our downloads website for some reason, it's on forges though).

**Comment by KingDan27** [comment] 2019-04-23 04:29
seems to have resolved it on my server... been up for 1.5 hrs with no dupes will post back again if i see/hear otherwise

**Comment by Yorkforce** [comment] 2019-04-23 14:15
> Try 3667 (it's not on our downloads website for some reason, it's on forges though).

Where is the spongeforge download on forge website?

**Comment by dualspiral** [comment] 2019-04-23 14:15
https://files.minecraftforge.net/spongepowered

**Comment by LemADEC** [comment] 2019-04-23 19:47
Is that build 3667 integrated in the build 3668 on the Sponge website?

**Comment by phit** [comment] 2019-04-23 19:50
yes

**Comment by LemADEC** [comment] 2019-04-23 19:58
well, build 3666 & 3670 are silently deleting item drops, so we're going back to 3616 for now.

**Comment by phit** [comment] 2019-04-23 19:59
that should be fixed in 3671

**Comment by LemADEC** [comment] 2019-04-23 20:12
3671 does fix item not dropping from barrel/hopper/chest.

**Comment by gabizou** [comment] 2019-04-23 20:57
The question is: Are there still dupes happening with builds 3667 and newer (latest currently is 3671 that has a few other potential changes that may affect fake players that is likely causing contamination of some previously global state variables)?

Don't comment about reverting because of other issues, it's off topic.

**Comment by xElementzx** [comment] 2019-04-26 01:51
Dupe appears to be resolved, have been running for 2 days and had no issues with a dupe.

**Comment by Yorkforce** [comment] 2019-04-26 02:16
Can confirm, wanted to give it a bit more time before reporting back but so far so good!

**Comment by Sir-Will** [comment] 2019-04-29 22:46
I was able to get it reproduced on a test server and after updating I couldn't reproduce it anymore. It did only happen when a specific area in a base was loaded. Though I can't test it on the live server as the latest sponge versions still break too much.

**Comment by gabizou** [comment] 2019-05-02 17:06
Seeing as it's been a week since someone's been able to no longer reproduce the dupe, I'll consider this issue resolved.



> Though I can't test it on the live server as the latest sponge versions still break too much.

Please point out which issues you're referring to, just saying it breaks too much doesn't help anyone reading the issue to know if your issues are resolved or not (it's also off-topic).

**Closed as completed by gabizou** 2019-05-02 17:06 UTC
Labels: type: bug, status: needs testing, version: 1.12
