### ISSUE TITLE
Unable to move and shake

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3054] opened 2020-01-09 15:59 UTC
**I am currently running**
- SpongeForge version: SpongeForge 7.1.8
- Forge version: 1.12.2 2847
- Operating System: Ubuntu

**Issue Description**

I use waterfall-> lobby (sponge)-> subserver( sponge )

this problem happened to my subserver
this happens randomly, making the player unable to move, and the player must re-join
When it happens it makes the server think they have died so it causes those with a minimap / waypoint mod installed to auto create a death waypoint

https://gyazo.com/b3a91eea7b959291c9c51a12715123ad

**Comment by axle2005** [comment] 2020-01-10 13:07
Just as a perspective: This was a previous issue back in version 4. ... something. When I first developed clearmob and an Player entity was removed, it did this exact thing. So it is very possible one of your plugins is setup to remove a Player entity without respawning it.

**Comment by ghost** [comment] 2020-01-10 15:25
I have catclearLag and pixelgenocide installed. Maybe these two are the cause?

**Comment by gabizou** [comment] 2020-01-11 10:51
Try running the server without any plugins and add `-Dsponge.shouldFireAll=true` as a start up flag and see if the issue persists. If installing one of your currently installed plugins starts triggering it, report to the plugin author (The catch with `-Dsponge.shouldFireAll` is that it enables all events, so if Sponge was the root cause for players not being able to move, it'd be the event handling that causes it, but if a plugin being installed starts the issue after it's been tested with sponge already throwing all events, then it's very much likely it's the plugin's fault).

**Comment by ghost** [comment] 2020-01-11 16:17
This happens randomly and I have a hard testing

**Comment by axle2005** [comment] 2020-01-11 18:15
Narrowing down plugins shouldn't be too hard. You said you are using CatClear and PixelGenocide... I personally would start with PixelGenocide... basically whitelist your server, get a couple people on to test with, and spam the heck out of the clearing commands for 10 minutes or so. Rinse lather and repeat with CatClear and anything that has a hint of killing an entity honestly.

**Comment by ghost** [comment] 2020-03-09 09:37
@gabizou 
I'm sure this is a sponge bug , I test as you say
And I only install these mods , use Waterfall + lobby(spongeforge) + sub server(test server)
```
chiselsandbits-14.33
CloudBoots-1.12.2-1.3.0.jar
Pixelmon-1.12.2-7.2.0-server.jar
spongeforge-1.12.2-2838-7.1.8.jar
```
Only happen on test server , and should I test SF 7.1.10?

**Comment by gabizou** [comment] 2020-03-11 06:38
And is Pixelmon absolutely required or just CloudBoots and SpongeForge and ChiselAndBits?

**Comment by ghost** [comment] 2020-03-11 11:59
I tried the latest spongeforge and pixelmon still happening
But when I removed the pixelmon, it never happened again. :thinking:

**Comment by dualspiral** [comment] 2020-06-09 08:59
Are you still having this issue on 7.2.2?

**Comment by ghost** [comment] 2020-06-09 09:01
Since I changed the lobby server (spigot), it has happened less often

**Comment by dualspiral** [comment] 2020-06-09 09:02
Does this happen if you connect to the server directly (i.e. no Waterfall?)

**Comment by ghost** [comment] 2020-06-09 09:04
Without waterfall, it won't happen

**Comment by dualspiral** [comment] 2020-06-09 09:08
Okay! We don't do anything special to enable proxy support other than to enable the player information forwarding, nor should we. In addition, your two statements:

> Since I changed the lobby server (spigot), it has happened less often

and

> Without waterfall, it won't happen

indicate to me that this is not a Sponge issue, but a Waterfall issue, maybe with some awkwardness with the entity ID rewriting. I'd be inclined to say that they may need to have a look at this to see if there is something on their end - we shouldn't need to alter anything but the login phase for it to work (which we already do).

I'm closing this for that reason.

**Closed as completed by dualspiral** 2020-06-09 09:08 UTC
