### ISSUE TITLE
Duplication with Blood Magic Sentient Sword

### ISSUE THREAD

**Issue by Kuuch** [SpongePowered/SpongeForge#1366] opened 2017-03-20 15:46 UTC
Throwing a Blood Magic Sentient sword on the ground with 1000 Will, will duplicate the sword in the spectre which can be right clicked and collected, also the specter insta aggro's on any near by player which wasnt intended, the duplication i believe is spinge based as our server is running Sponge forge Version 1.10.2-2254-5.2.0-BETA-0 (custom) and the issue is there, however, single player, this doesn't happen.

hope this is enough information, if it isn't, ill be sure to provide what ever i can.

**Comment by TehNut** [comment] 2017-03-20 16:01
The agro is probably on my end, but I believe the duplication is due to how Sponge is handling the ItemTossEvent  (or whatever it's called)

**Comment by KasperFranz** [comment] 2017-03-20 16:04
Just for reference this is the issue on BloodMagic https://github.com/WayofTime/BloodMagic/issues/1096

**Comment by phit** [comment] 2017-11-07 10:52
still an issue with `spongeforge-1.10.2-2477-5.2.0-BETA-2698` & `BloodMagic-1.10.2-2.1.11-80`

repro:

* grab a tartaric gem with at least 1000 will from the creative menu
* drop a sentient sword

it will stay in your inventory, when you kill what it spawns you get a second sword

relevant sources
<https://github.com/WayofTime/BloodMagic/blob/305e001b1589737405a794b76a80d0db10bd8799/src/main/java/WayofTime/bloodmagic/util/handler/event/GenericHandler.java#L156>
<https://github.com/WayofTime/BloodMagic/blob/305e001b1589737405a794b76a80d0db10bd8799/src/main/java/WayofTime/bloodmagic/item/soul/ItemSentientSword.java#L499>

**Comment by gabizou** [comment] 2018-01-01 09:14
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by gabizou** 2018-01-01 09:14 UTC
Labels: type: mod incompatibility, version: 1.10 (u)
