### ISSUE TITLE
There are many errors in the console. Decrease in TPS.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2311] opened 2018-07-16 08:46 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3307
- Forge version: 14.23.4.2705
- Java version: Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
- Operating System: Debian 9

- Mods (43): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, Applied Energistics 2, BD Lib, CXLibrary, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, CreativeCore, CreativeCoreDummy, Ex Nihilo Creatio, Extreme Reactors, Fishing Net Mod, FoamFix, Forestry, Giacomo's Foundry, HoloInventory, IndustrialCraft 2, Iron Chest, ItemPhysic, Just Enough Items, Mantle, NoDestroy, Parachronology, Quick Leaf Decay, Redstone Flux, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, WanionLib, Zero CORE

- Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, LangSwitch, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VillagerShops, VirtualChest, VirtualTool, WorldEdit, spark

**Issue Description**
I do not know what causes this problem. I hope my logs will help you. If necessary, I can provide more timings and profile. My server was quite popular, but it can not work stably with online more than 30 players. In this case, the CPU(Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz) is usually loaded by no more than 20-30%. 

https://gist.github.com/Mr-Krab/077f9605baea7f6302cd869cdd9e3f07

**Comment by SawFowl** [comment] 2018-07-16 10:07
https://timings.aikar.co/?id=0373c09dd5104010b118a55026e34c70

https://sparkprofiler.github.io/?Qtmzqr59nb

**Comment by bloodmc** [comment] 2018-07-16 13:41
@Mr-Krab Please test the following build from my event branch that will soon be merged
https://www.dropbox.com/s/wb117qdtcte01ho/spongeforge-1.12.2-2705-7.1.0-BETA-BUG1-TEST9.jar

**Comment by SawFowl** [comment] 2018-07-16 13:43
@bloodmc It will take several hours. The problem does not appear immediately after the server starts.

**Comment by XakepSDK** [comment] 2018-07-16 14:06
@Mr-Krab in future - post debug.log and latest.log

**Comment by SawFowl** [comment] 2018-07-16 15:38
@XakepSDK  I gave it. See the first message.

**Comment by SawFowl** [comment] 2018-07-16 16:20
@bloodmc It seems there are fewer errors. But the performance is at the same low level.

Timings https://timings.aikar.co/?id=3823ceaf12ce42d999c97818a8db7c0b
Profiler https://sparkprofiler.github.io/?N8IdAM00KQ
Log and Debug https://gist.github.com/Mr-Krab/887abe999c5a6fadf6f7f0620b922bbb

I'll check even more new version. I will report the results here.

**Comment by gabizou** [comment] 2018-07-16 17:11
@Mr-Krab looks like your server is plagued by thermal dynamics doing a lot of stuff...

<img width="1478" alt="screen shot 2018-07-16 at 10 08 29 am" src="https://user-images.githubusercontent.com/1203877/42772812-6f362316-88e0-11e8-8b1b-ba7fdeaa204f.png">
Sponge's consumer code (the PhaseTracker bits) are seemingly non-existent in the profiler results, let alone timings. I'd look into the possibility of improving machines etc. as it shows in the profiler the massive systems are definitely impacting performance of the server.

Likewise, it appears Forestry has it's own NPE from oak tree sapling of sorts (as seen from the locatable block that is being ticked):
```
[17:11:39] [Server thread/ERROR] [Sponge]: /*************************************************************************************************************************************************************************************************************/
[17:11:39] [Server thread/ERROR] [Sponge]: /*                                                                                  Exception occurred during a PhaseState                                                                                   */
[17:11:39] [Server thread/ERROR] [Sponge]: /*************************************************************************************************************************************************************************************************************/
[17:11:39] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best effort to not throw exceptions randomly                                                                                                                             */
[17:11:39] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most cases, something else triggered this                                                                                                                              */
[17:11:39] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash by catching it. The following stacktrace                                                                                                                           */
[17:11:39] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                                                                                                                                   */
[17:11:39] [Server thread/ERROR] [Sponge]: /*************************************************************************************************************************************************************************************************************/
[17:11:39] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: RandomBlockTickPhase                                                                                                                                                  */
[17:11:39] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                                                                                                                                         */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     - Owner: EntityPlayerMP['delostor'/125, l='IslandWorld', x=4342,28, y=69,00, z=-1295,08]                                                                                                              */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     - Source: SpongeLocatableBlock{blockState=forestry:sapling_ge[tree=oak], position=(4371, 64, -1269), worldId=7f8e0177-ed1a-4de0-a937-05fe48f93ddb, worldReference=java.lang.ref.WeakReference@79b58a} */
[17:11:39] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@52d376c9                                                                                                                                                         */
[17:11:39] [Server thread/ERROR] [Sponge]: /*************************************************************************************************************************************************************************************************************/
[17:11:39] [Server thread/ERROR] [Sponge]: /* StackTrace:                                                                                                                                                                                               */
[17:11:39] [Server thread/ERROR] [Sponge]: /* java.lang.NullPointerException: null                                                                                                                                                                      */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     forestry.core.genetics.Genome.getActiveAllele(Genome.java:262)                                                                                                                                        */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     forestry.arboriculture.genetics.TreeGenome.getMaturationTime(TreeGenome.java:98)                                                                                                                      */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     forestry.arboriculture.genetics.Tree.getRequiredMaturity(Tree.java:171)                                                                                                                               */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     forestry.arboriculture.tiles.TileSapling.getRequiredMaturity(TileSapling.java:55)                                                                                                                     */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     forestry.arboriculture.tiles.TileSapling.tryGrow(TileSapling.java:87)                                                                                                                                 */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     forestry.arboriculture.tiles.TileSapling.onBlockTick(TileSapling.java:49)                                                                                                                             */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     forestry.arboriculture.blocks.BlockTreeContainer.func_180650_b(BlockTreeContainer.java:43)                                                                                                            */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     net.minecraft.block.Block.func_180645_a(Block.java:508)                                                                                                                                               */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:300)                                                                                                           */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2168)                                                                                                                                  */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)                                                                                                                                    */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)                                                                                                                           */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)                                                                                                                 */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                                                                                           */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                                                                                    */
[17:11:39] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Thread.java:748)                                                                                                                                                                 */
[17:11:39] [Server thread/ERROR] [Sponge]: /*  Phases Remaining:                                                                                                                                                                                        */
[17:11:39] [Server thread/ERROR] [Sponge]: /*                                                                                                                                                                                                           */
[17:11:39] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                                                                                                        */
[17:11:39] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-SNAPSHOT-a1418ae3                                                                                                                                                                       */
[17:11:39] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2705-7.1.0-BETA-0                                                                                                                                                                    */
[17:11:39] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.4.2705                                                                                                                                                                            */
[17:11:39] [Server thread/ERROR] [Sponge]: /*************************************************************************************************************************************************************************************************************/
```

**Comment by SawFowl** [comment] 2018-07-16 17:18
@gabizou This seemed strange to me. https://imgur.com/a/f852zI6#uZqRq3D
The funnel on the screenshot is empty. I also looked at the mechanisms from Thermal Dynamics, their indicators were lower. I do not even know what data to believe. 3 different checks show different data.

**Comment by Dockter** [comment] 2018-07-16 17:27
The performance issues was the main reason we abandoned all CoFH based mods.

**Comment by gabizou** [comment] 2018-07-16 18:24
@Mr-Krab I don't believe they count neighbor updates since chunk loads are showing up in the profiler (no idea why they don't do better chunk checks, or make it apparent that their mechanisms can cause chunk loads). Either way, I don't see much of the original issue being present with the latest logs/profiling.

**Comment by bloodmc** [comment] 2018-07-16 18:42
@Mr-Krab Please go on sponge's discord https://discord.gg/KuWhVP for testing this issue. It seems to be an issue with our Chunk GC feature and TE's neighbor power check.

**Comment by bloodmc** [comment] 2018-07-16 18:50
As a simple test, disable chunk's GC feature in the sponge's global config.

**Comment by SawFowl** [comment] 2018-07-17 08:58
bloodmc I tested on 1.12.2-2705-7.1.0-BETA-3315
The number of errors in the console is less. I think later I will make a profile using Lag Googles.
https://gist.github.com/Mr-Krab/45394778f84d16a4a2f27e3bf9dd018e
https://timings.aikar.co/?id=80ed04fccb00476da94e596183004d58
https://sparkprofiler.github.io/?pTsw8HHDwL

**Comment by bloodmc** [comment] 2018-07-17 13:28
@Mr-Krab I noticed you have `deny-chunk-requests` set to true. This can easily cause issues with certain mods like Thermal Expansion. Set this value to false and restart.

**Comment by SawFowl** [comment] 2018-07-17 13:33
@bloodmc As far as I know before, with the deny-chunk-requests = false parameter there were problems with the state of the blocks, they could unexpectedly be replaced. But I'll try to use the setting you suggested.

**Comment by bloodmc** [comment] 2018-07-17 13:45
@Mr-Krab All `deny-chunk-requests` does is allow requests to load chunks rather than deny them preventing the load. It should have no affect on the `state` of a block. If that is occurring, then something else is at play here.

**Comment by phit** [comment] 2018-07-17 15:09
seriously do not set that to true it can corrupt your world and breaks a lot of mods

**Comment by SawFowl** [comment] 2018-07-18 13:48
@bloodmc I did not notice the difference.
Tested on 1.12.2-2705-7.1.0-BETA-3319(An error occurred when the player disconnected unexpectedly)
[logs.zip](https://github.com/SpongePowered/SpongeForge/files/2205924/logs.zip)
https://timings.aikar.co/?id=8001416b150645af97e84fef5e47b60e
https://sparkprofiler.github.io/?SY25LD4VH3
![default](https://user-images.githubusercontent.com/29023558/42885663-3ab5d980-8aaa-11e8-8a7d-e5921164084e.png)
I will test in the near future a newer version of Sponge.

**Comment by bloodmc** [comment] 2018-07-18 13:57
@Mr-Krab Include a copy of your world zipped with all relevant mods/configs. Also specify the location where lag occurs most.

**Comment by SawFowl** [comment] 2018-07-19 06:54
@bloodmc https://www.beandex.ru/test.7z

World - IslandWorld
Coordinates 5354, 109, -5355

I also noticed that there are problems with unloading chunks. This problem occurs regardless of the configuration of Sponge. Without Sponge, chunks are unloaded normally.

**Comment by bloodmc** [comment] 2018-07-19 15:29
@Mr-Krab I'm not seeing any issues. Set `chunk-gc-tick-interval` back to 600 and disable `deny-chunk-requests`.

**Comment by SawFowl** [comment] 2018-07-20 08:07
@bloodmc There are no problems with the basic world. There is a problem with the created worlds. Watch the video, I hope you understand what the problem is. 
https://youtu.be/pnNyainxY0I
SpongeForge: 1.12.2-2705-7.1.0-BETA-3323

**Comment by bloodmc** [comment] 2018-07-20 13:52
@Mr-Krab Thanks for the video, I was able to reproduce the issue. I'll be pushing a fix soon once I figure out what is happening.

**Closed as completed** 2018-07-20 20:43 UTC
Labels: version: 1.12
