### ISSUE TITLE
[Sponge 1.10.2-2221-5.1.0-BETA-2109]  Exception during phase body    

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1243] opened 2017-02-03 17:28 UTC
Error Report: http://pastebin.com/EDssvjVB

**Comment by Deamon5550** [comment] 2017-02-03 17:35
The first stack is harvestcraft being stupid. The actual error seems to be a bug with https://github.com/MikeLydeamore/ExNihiloAdscensio/blob/master/src/main/java/exnihiloadscensio/barrel/modes/compost/BarrelModeCompost.java#L81 Can't see anything there that we might cause, try and reproduce it without sponge.

**Comment by Zidane** [comment] 2017-02-26 01:18
Closing due to no feedback.

**Closed as completed by Zidane** 2017-02-26 01:18 UTC
