### ISSUE TITLE
Unable to capture transaction from class org.spongepowered.mod.item.inventory.adapter.IItemHandlerAdapter at index 1

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2378] opened 2018-08-13 00:39 UTC
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3396
- Forge version: 1.12.2 2705

Why is this message always appearing in my console, what should I do: [Sponge]: Unable to capture transaction from class org.spongepowered.mod.item.inventory.adapter.IItemHandlerAdapter at index 1

**Comment by phit** [comment] 2018-08-13 00:41
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2366

**Closed as completed by phit** 2018-08-13 00:41 UTC
Labels: resolution: duplicate, version: 1.12
