### ISSUE TITLE
Baubles Inventory voids items

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1320] opened 2017-03-03 00:10 UTC
Not sure if this is a mod bug or a sponge issue.

### Press E (to open your inv) have a Angel Ring on you, place it in the crafting grid (4 slots) then hit on Baubles and go back to your inv, the angel ring then just vanishes, does not drop on the floor and a relog does not help.

Update - Its not just the Angel Ring, its any item.

(Only tested on Infinity Lite, not sure if it does it for the other 1.10's)

Sponge Version
SpongeAPI: 5.2.0-SNAPSHOT-982a6b0
SpongeForge: 1.10.2-221-5.2.0-BETA-2211
Minecraft Forge: 12.18.3.2185

**Comment by Eufranio** [comment] 2017-03-03 00:13
Confirm with
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-cf4dfb1
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2208
    Minecraft Forge: 12.18.3.2239

Other items will not be lost, instead they'll just be dropped.

**Comment by bloodmc** [comment] 2017-03-30 16:26
@Keaton1188 @Eufranio does this occur with latest SpongeForge build?

**Comment by Keaton1188** [comment] 2017-04-16 21:21
Sorry for the late reply. @bloodmc 

Still happening on sponge version - 1.10.2-2281-5.2.0-BETA-2274

**Comment by Aaron1011** [comment] 2017-04-22 18:25
@Keaton1188: I can't reproduce this on the latest SpongeForge. Is this still an issue?

**Comment by Keaton1188** [comment] 2017-04-22 21:33
Still happening on FTB Beyond (1.5.3)
Could not get this to happen on Sky Factory 3 though.

Both are using Sponge version 2274 (newest one)

**Comment by Keaton1188** [comment] 2017-06-05 00:23
This is still an issue, any update?

@Aaron1011 @bloodmc

**Comment by phit** [comment] 2017-07-17 19:34
still an issue in 1.11.2

Baubles-1.11-1.4.5.jar
extrautils2-1.11.2-1.5.jar
jei_1.11.2-4.5.0.291.jar
spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar

item drops as expected when Sponge is removed

**Comment by Keaton1188** [comment] 2017-08-26 18:10
Still an issue, any update on this please?

@bloodmc @Aaron1011

**Comment by phit** [comment] 2017-12-02 02:52
Can't reproduce with:
spongeforge-1.12.2-2529-7.0.0-BETA-2748.jar
Baubles-1.12-1.5.1.jar
extrautils2-1.12-1.6.8.jar

Item always go back to your inventory now when closing a crafting table, which also applies to the player crafting table.

**Comment by phit** [comment] 2018-01-01 15:48
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:48 UTC
Labels: type: mod incompatibility, version: 1.10 (u), system: inventory, version: 1.11 (u)
