### ISSUE TITLE
Server/Client sync issue with PSI

### ISSUE THREAD

**Issue by lilmoefow** [SpongePowered/SpongeForge#1028] opened 2016-11-05 23:27 UTC
Not sure how to really explain this one, i may record a small video if necessary.  When placing the Casting Assistant Device into a chest, it will leave a ghost version of it in your inventory, sometimes leading to it to be duped.   Also if you open your inventory and happen to accidentally "drop" or throw the C.A.D. onto the ground, it can leave a ghost version of it in you inventory either causing it to dupe, or it deletes both the dropped and the ghosted version.  

I personally have only been able to reproduce the first issue with the chest, but i have another player on my server reporting the second issue to me.  So I'm lumping it all together because it seems related.

forge-1.10.2-12.18.2.2107-universal.jar
spongeforge-1.10.2-2107-6.0.0-BETA-1872.jar
Psi-r1.0-41.jar
PSIonicUpgrades-r1.15.jar

**Comment by Eufranio** [comment] 2016-11-06 07:31
Happens only with PSI stuff?

**Comment by lilmoefow** [comment] 2016-11-06 16:27
So far, i have only noticed it happening with the C.A.D.

**Comment by bloodmc** [comment] 2016-11-29 05:47
@lilmoefow Does this bug occur with SF 1914+?

**Comment by lilmoefow** [comment] 2016-11-29 06:39
Yes it is still occurring with these versions.

forge-1.10.2-12.18.2.2123-universal.jar
spongeforge-1.10.2-2123-5.1.0-BETA-1914.jar
Psi-r1.0-42.jar

And When trying to recreate it, I acutally got a client crash.

Here is the Crash Log - http://pastebin.com/WZ57xWV5

Client Log Latest - http://pastebin.com/akgtCe5C

Fml Client Latest - https://gist.github.com/lilmoefow/d81f051b0054f63c4582df135861c998

**Comment by bloodmc** [comment] 2016-12-07 15:08
@lilmoefow Does this occur with SF 1971? Also turn off item pre-merging if you have it on in sponge's global.conf

**Comment by lilmoefow** [comment] 2016-12-07 22:35
forge-1.10.2-12.18.2.2171-universal.jar
spongeforge-1.10.2-2171-5.1.0-BETA-1971.jar
Psi-r1.0-42.jar

It seems to be fixed.  When i pick up the item from my inventory and try to place into a chest, there is an extra "ghost" item still in my inventory for not even a half a second then it corrects its self.  No crashing, duping or deleting of the C.A.D. seems to  be happening any more.

**Comment by Eufranio** [comment] 2017-01-29 22:08
Sync issues (because PSI GUIs are client-side), the issue is with Psi and not Sponge.

**Comment by Yorkforce** [comment] 2017-03-05 22:35
We are also experiencing something very similiar to this with Draconic items and the coke oven too, they both spit out ghost items to the ground that can't seemingly be interacted with, they also decay way faster than normal items would.

Relogging doesn't fix the issue, they are still on the ground after logging out and back in.

This is on spongeforge 2215

**Comment by phit** [comment] 2017-11-06 20:02
Pretty sure this was fixed on Psi's end at some point, let me know if it's still an issue and I'll reopen this.

**Closed as completed by phit** 2017-11-06 20:02 UTC
Labels: resolution: fixed externally

**Comment by Nihilhalla** [comment] 2020-09-13 15:49
Hey there, sorry to necro this, but it's happening again on spongeforge 7.3.0 stable recommended. PSI CADs are being pseudocloned and the gui is bugged, what would a possible fix be if there isn't one coming from PSI?

**Comment by ShoukakuChuuCC** [comment] 2020-11-12 07:06
> 嘿，很抱歉让我无法接受，但建议在海绵forge 7.3.0稳定器上再次发生。PSI CAD正在被伪克隆，并且gui出现错误，如果没有PSI CAD，将有可能解决此问题？

me too

**Comment by CC-3301** [comment] 2020-11-12 07:07
> Hey there, sorry to necro this, but it's happening again on spongeforge 7.3.0 stable recommended. PSI CADs are being pseudocloned and the gui is bugged, what would a possible fix be if there isn't one coming from PSI?

me too
