### ISSUE TITLE
Spongeforge bug,please help me,The armor value is too high, no damage 

### ISSUE THREAD

**Issue by shinefield** [SpongePowered/SpongeForge#3263] opened 2021-07-24 15:59 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.3.0.jar
- SpongeVanilla version: 1.12.2
- Java version: 1.8.0_191
- Operating System:windows server 2008

- Plugins/Mods:
iceandfire-1.9.1-1.12.2.jar
spongeforge-1.12.2-2838-7.3.0.jar

**Issue Description**

The armor value is too high, no damage
Low damage cannot damage dragon armor in ice and fire
After testing, it was caused by Spongeforge mod
Seek a solution

game version 1.12.2

server:
forge-1.12.2-14.23.5.2847

mods:
iceandfire-1.9.1-1.12.2.jar
LLibrary-1.12.2.jar
spongeforge-1.12.2-2838-7.3.0.jar

No bugs in single player mode

**Comment by ImMorpheus** [comment] 2021-07-24 18:33
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/3140

**Closed as completed by ImMorpheus** 2021-07-24 18:33 UTC
Labels: resolution: duplicate, version: 1.12

**Comment by shinefield** [comment] 2021-07-24 18:52
May I ask when it can be repaired
