### ISSUE TITLE
Scheduler not running tasks on internal server

### ISSUE THREAD

**Issue by creeper123123321** [SpongePowered/SpongeForge#2095] opened 2018-04-10 21:16 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-3016
- Forge version: 1.12.2-14.23.2.2611
- Java version: openjdk version "1.8.0_162"
- Operating System: Arch Linux

- Plugins/Mods: modified ViaVersion

**Issue Description**
SpongeForge is not running tasks while internal server is open, but when i exit world it seems to execute that tasks
```
[18:58:44] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[18:58:44] [Server thread/INFO]: Generating keypair
[18:58:44] [Server thread/INFO] [test]: test
[18:58:44] [Server thread/INFO] [Sponge]: Checking for worlds that need to be migrated...
[18:58:44] [Server thread/INFO] [Sponge]: No worlds were found in need of migration.
[18:58:44] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[18:58:44] [Server thread/INFO] [FML]: Applying holder lookups
[18:58:44] [Server thread/INFO] [FML]: Holder lookups applied
[18:58:46] [Server thread/INFO]: Loaded 488 advancements
[18:58:46] [Server thread/INFO]: Loaded 6 advancement trees
[18:58:47] [Server thread/INFO]: Preparing start region for level 0 (Novo Mundo)
[18:58:48] [Server thread/INFO]: Preparing spawn area: 0%
[18:58:49] [Server thread/INFO]: Preparing spawn area: 66%
[18:58:50] [Server thread/INFO] [Sponge]: Loading world [Novo Mundo] (overworld)
[18:58:50] [Server thread/INFO]: Loaded 488 advancements
[18:58:50] [Server thread/INFO]: Loaded 6 advancement trees
[18:58:50] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (the_nether)
[18:58:50] [Server thread/INFO]: Loaded 488 advancements
[18:58:50] [Server thread/INFO]: Loaded 6 advancement trees
[18:58:50] [Server thread/INFO] [Sponge]: Loading world [DIM1] (the_end)
[18:58:51] [Server thread/INFO]: Changing view distance to 8, from 10
[18:58:54] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
[18:58:54] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[18:58:54] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 7 mods : minecraft@1.12.2,sponge@1.12.2-2611-7.1.0-BETA-3016,FML@8.0.99.99,test@1.0-SNAPSHOT,spongeapi@7.1.0-SNAPSHOT-bec74cd,forge@14.23.2.2611,mcp@9.42
[18:58:54] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[18:58:54] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[18:58:54] [Server thread/INFO]: creeper123123321[local:E:f3b8c689] logged in with entity id 98 in Novo Mundo(0) at (66.91255091950123, 72.8637031262935, 67.40550885460154)
[18:58:54] [Server thread/INFO]: creeper123123321 entrou na partida
[18:58:54] [main/WARN] [Sponge]: No entity type is registered for class net.minecraft.client.entity.EntityPlayerSP
[18:58:58] [Server thread/INFO]: Saving and pausing game...
[18:58:58] [Server thread/INFO]: Saving chunks for level 'Novo Mundo'/overworld
[18:58:58] [main/INFO]: [CHAT] creeper123123321 entrou na partida
[18:58:58] [Server thread/INFO]: Saving chunks for level 'DIM-1'/the_nether
[18:58:58] [Server thread/INFO]: Saving chunks for level 'DIM1'/the_end
[18:58:58] [main/INFO]: Loaded 124 advancements
[18:58:58] [main/INFO]: Loaded 5 advancement trees
[18:58:58] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4429ms behind, skipping 88 tick(s)
[18:59:00] [Server thread/INFO]: Stopping server
[18:59:00] [Server thread/INFO]: Saving players
[18:59:00] [Server thread/INFO]: creeper123123321 lost connection: Desconectado
[18:59:00] [Server thread/INFO]: creeper123123321 saiu da partida
[18:59:00] [Server thread/INFO]: Stopping singleplayer server as player logged out
[18:59:00] [Server thread/INFO]: Saving worlds
[18:59:00] [Server thread/INFO]: Saving chunks for level 'Novo Mundo'/overworld
[18:59:00] [Server thread/INFO]: Saving chunks for level 'DIM-1'/the_nether
[18:59:00] [Server thread/INFO]: Saving chunks for level 'DIM1'/the_end
[18:59:00] [Server thread/INFO] [Sponge]: Unloading world [Novo Mundo] (DIM0)
[18:59:00] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (DIM-1)
[18:59:00] [Server thread/INFO] [Sponge]: Unloading world [DIM1] (DIM1)
[18:59:00] [Server thread/INFO] [FML]: Applying holder lookups
[18:59:00] [Server thread/INFO] [FML]: Holder lookups applied
[18:59:03] [main/INFO] [test]: test 123
```
test code:
```
@Plugin(id = "test", description = "test")
public class test {
    @Inject
    Logger logger;
    @Listener
    public void onStart(GameAboutToStartServerEvent e) {
        logger.info("test");
        Sponge.getScheduler().createTaskBuilder().execute(new Runnable() {
            @Override
            public void run() {
                logger.info("test 123");
            }
        }).submit(this);
    }
}
```

**Comment by kashike** [comment] 2018-04-10 21:17
Please provide a description of your issue.

**Comment by liach** [comment] 2018-04-10 22:45
Recall that last tine dockter moved ticking events onto the client. I suspect that's the cause. (I've pointed out back then)

**Comment by simon816** [comment] 2018-04-11 00:20
@Dockter you checked the scheduler still worked with this PR? https://github.com/SpongePowered/SpongeForge/pull/1995#issuecomment-364645691

**Comment by Zidane** [comment] 2018-04-11 15:30
@simon816 

While we can revert his commit, the core issue still remains. We have no means of scheduling on client thread.

I mean one could say "Well you could use NMS, grab Minecraft and schedule interally to Minecraft from a Sponge scheduled task" but that is horrifically hacky. We really need a scheduler per logic thread (Server/Client).

Thoughts?

**Comment by kashike** [comment] 2018-04-11 15:43
Time to start introducing `Client`?
`Client#getScheduler()` etc

**Comment by liach** [comment] 2018-04-11 16:33
Didn't zidane mention a few month ago that sponge is in cleanup phase recently?

**Comment by simon816** [comment] 2018-04-11 18:44
@Zidane Perhaps we could reconsider this? https://github.com/SpongePowered/SpongeAPI/commit/a3ad9e6c1dc47ea0f99f5fcbc1650652df0abfa5#r16207084

I like @kashike's suggestion.
Or you chould choose the scheduler when building a task, something like @maxov's suggestion way back https://github.com/SpongePowered/SpongeAPI/pull/697#issuecomment-106014675

**Comment by Zidane** [comment] 2018-04-25 19:19
Closing this as @Aaron1011 's fix fixes the original issue with a PR to rightfully add per-side Scheduler support later.

**Closed as completed by Zidane** 2018-04-25 19:19 UTC
Labels: system: client, version: 1.12
