### ISSUE TITLE
xNet - Fatal error - 1.12

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2470] opened 2018-10-08 09:32 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3448.jar
- Forge version: 14.23.4.2760
- Java version: Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: StoneBlock

**Issue Description**
Hi there, I have reported this issue before and has been a problem for some time now, when placing an xNet Controller it will disconnect you with “Fatal error this connection is terminated” this does not happen on SP and seems to only occur when you have sponge active.

**Comment by phit** [comment] 2018-10-08 11:09
can't reproduce this using StoneBlock 1.0.17
with Sponge 3475 https://i.imgur.com/Pk4d3lf.png

are you using BungeeCord? check that console and also check your client console for any errors that may help

**Comment by Keaton1188** [comment] 2018-10-08 11:33
My bad, I said controller.. you able to try the sequencer, that’s what I meant :) 

If you’re not then don’t worry I’ll be home in about an hour to give it a go.

**Comment by phit** [comment] 2018-10-08 11:36
![2018-10-08_13 35 53](https://user-images.githubusercontent.com/2097483/46606857-20c43180-caff-11e8-9a33-26611b23020f.png)

works fine, been using it a few times in the last few months too for the endergenic generator

**Comment by Keaton1188** [comment] 2018-10-08 12:51
Hmm okay, I’ll upgrade to the latest Sponge and give it another try, if it’s still an issue then it’s probably bungee related?

**Comment by phit** [comment] 2018-10-08 12:57
Most likely, I use Bungee too but with some extra patches for mod compatibility. Definitely check your Bungee logs when you get kicked.

**Comment by Shybella** [comment] 2018-10-08 13:48
I am using Sponge 3476/Forge 2760/xnet-1.12-1.7.3

I cannot reproduce the issue as-well.

**Comment by Keaton1188** [comment] 2018-10-08 14:44
Had the problem occur when I opened the Controller, Sequencer seemed fine..

Bungee just showed "{user} disconnected: A fatal error has occurred etc" 

There was this however in the console: https://pastebin.com/MT9Q3JFL

**Comment by phit** [comment] 2018-10-08 14:59
that's just xnet and ingameinfoxml not following https://github.com/MinecraftForge/MinecraftForge/pull/4890

**Comment by Keaton1188** [comment] 2018-10-08 21:58
Still an issue for me with the latest sponge.

Bungee:
disconnected with: A fatal error has occurred, this connection is terminated
[23:58:37 WARN]: [/72.222.225.242:51634|UndeadPlays] <-> DownstreamBridge <-> [Stoneblock] - NativeIoException: syscall:read(..) failed: Connection reset by peer

Are you able to open the Controller as well?

**Comment by phit** [comment] 2018-10-08 22:20
yup and have been for months, never heard any complaints from my players either, a lot of them use xnet

**Comment by Keaton1188** [comment] 2018-10-08 22:43
strange... you mentioned you use Bungee with some patches for mod compatibility, could that be my issue??

**Comment by Arudarin** [comment] 2018-10-12 17:34
@phit @Keaton1188 What became of this?

**Comment by phit** [comment] 2018-10-12 17:50
nothing, theres known open issues for hexacord/waterall with mods, I'm gonna close this here if someone can reproduce it without some form of proxy, reply and I'll reopen

**Closed as completed by phit** 2018-10-12 17:50 UTC
Labels: status: more information needed, version: 1.12, status: waiting for reply
