### ISSUE TITLE
Crash ConcurrentModificationException

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/SpongeForge#2915] opened 2019-07-31 18:16 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3866
- Forge version: 2838
- Java version: 1.8.0_211
- Operating System: Ubuntu 19.04

- Plugins/Mods:

 Plugins (24): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AmberShop, AutoPickup, BelzShop, ClearMob, DupeFixer, ESPayMoney, EconomyLite, GriefPrevention, LuckPerms, MMCRestrict, NanoChat, Nucleus, PayDay, PixelAutoMessages, Plan, PlayTimeCounter, Simple Scavenger, WorldEdit, spark

 Mods (115): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Advanced Solar Panels [GamePoint Edition], BD Lib, Baubles, Better Questing, BetterBedrockGen, Bigger Packets, please !, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Botania, Brandon's Core, Cases, ChickenChunks, Clumps, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Draconic Evolution, Electro-Magic Tools, Embers Rekindled, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Energy Converters, EventHelper, Extra Utilities 2, ExtraBotany, Forestry, GamePoint Mod, GamePoint Mod, GenDustry, Gravitation Suite, Hammer Core, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Inventory Tweaks, Just Enough Items, LagGoggles, LunatriusCore, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MetalChests, Mod Tweaker, Mystical Lib, NoMoreRecipeConflict, OpenBackup, OpenFM, Phosphor Lighting Engine, PlusTiC, Quick Leaf Decay, RF Expansion, RandomPatches, Redstone Flux, Refined Storage, Shadowfacts' Forgelin, Solar Flux Reborn, SpongeForge, Stackie, Standard Expansion, Storage Tech, Surge, TBone, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Grid, The One Probe, Thermal Cultivation, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, Tiquality, ToroHUD Damage Indicators, Trade, Tree Chopper, UniDict, Varied Commodities, WanionLib, XNet, YNot, gpaddons, tileentitylimiter

**Issue Description** server crash

Crash report: https://gist.github.com/bigenergy/0548430d4056d52ab2ed751f09531030
Full debug log: https://drive.google.com/file/d/1puP5lza61ZxUBBO3jM4tOTOtxMIFmgIb/view?usp=sharing

**Comment by ImMorpheus** [comment] 2019-08-02 13:06
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2831

This is a forge bug

**Closed as completed by ImMorpheus** 2019-08-02 13:06 UTC
Labels: resolution: duplicate, version: 1.12
