### ISSUE TITLE
Simple Life 2 Ore Gen issue

### ISSUE THREAD

**Issue by Jager67** [SpongePowered/SpongeForge#1846] opened 2017-11-11 08:45 UTC
**I am currently running.. a Simple Life 2 server.**

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2731
- Forge version: 1.10.2 forge 12.18.3.2511
- Java version: jre1.8.0_151
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 
MagiBridge-2.4.1-all
UltimateCore
CatClearLag-0.8
LuckPerms-Sponge-4.0.6
**What is the expected result?**
Server boots up but there is terrible lag from an Ore Generation.

**What is the current result?**
[fml-server-3.log](https://github.com/SpongePowered/SpongeForge/files/1463580/fml-server-3.log)

**Comment by phit** [comment] 2017-11-21 22:36
Can't reproduce with 

spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
OreSpawn-1.12-3.2.0.95.jar

Set these config options and flew around for a bit
`B:"Replace Vanilla Oregen"=true`
`B:"Flatten Bedrock"=true`

no exceptions in the console and TPS seemed fine.

**Comment by LemADEC** [comment] 2017-11-23 20:58
SimpleLife2 was using OreSpawn-1.10.2-2.0.0.15.jar in 1.3.6 and removed the mod altogether in 1.4.
Are those new configuration options from OreSpawn 3.x?

**Comment by phit** [comment] 2017-11-23 21:01
no idea, I just tested if it is an issue in 1.12 for https://github.com/SpongePowered/SpongeForge/projects/3

**Comment by HorizonsMC** [comment] 2017-12-09 03:14
It's an issue because the SImple Life 2 is using an outdated version of MMD Orespawn (almost a year old). Tell the author to update.

**Comment by phit** [comment] 2018-01-01 15:50
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:50 UTC
Labels: version: 1.10 (u), system: world, system: phase tracker
