### ISSUE TITLE
Multiple crashes with RailCraft

### ISSUE THREAD

**Issue by Y0ungSandwich** [SpongePowered/SpongeForge#2540] opened 2018-12-29 17:24 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.4.jar/spongeforge-1.12.2-2768-7.1.5-RC3512
- Forge version: forge-1.12.2-14.23.5.2781-universal.jar
- Java version: 1.8.0_171
- Operating System:CentOS

- Plugins/Mods: Mod List: https://www.atlauncher.com/pack/MechMagic
                          Plugins: GriefPrevention, LuckPerms, MMCRestrict, Nucleus, Prism

**Issue Description** 
 The first issue was tested on Sponge 1.12.2-2768-7.1.5-RC3512. When placing a Ralicraft Cargo cart down on a track the server crashes(1). 

The second issue was tested with spongeforge-1.12.2-2768-7.1.4.jar. When connecting a Minecraft Chest Cart to a Railcraft locomotive the server crashes(2). 

First Issue Crash Report(1)
https://gist.github.com/Y0ungSandwich/b7e988f92114a4edb6c416822f0904c7

Second Issue Crash Report(2)
https://gist.github.com/Y0ungSandwich/b8294ecd2265a2ff570696a0f61ce77b
Log(2)
https://gist.github.com/Y0ungSandwich/198ec2ff4e131aa7e5c27da4c799d83f

**Comment by liach** [comment] 2018-12-29 22:10
Railcraft ticket at Railcraft/Railcraft#1607

**Comment by Aaron1011** [comment] 2019-01-07 19:21
The issue appears to be caused by Sponge causing `EntityMinecartContainer` to implement `MinecraftInventoryAdapter` (via `MixinTraitInventory`). Since both `MinecraftInventoryAdapater` and a Railcraft subclass of `EntityMinecartContainer` provide a default implementation of `Iterable.iterator`, this results in an error at runtime.

Normally, javac knows about this kind of diamond issue at compile time, and requires the user to specify which default method they intend to use at each call site. However, unless we transform every loaded class to look for instances of this situation, there's not much we can do about the Railcraft side of this.

I think we need to reconsider how we handle inventory adapters for classes that mods can subclass. Even if we fix the default method problem, we have both Sponge and Railcraft trying to provide `Iterable` implementations for the same class.

**Comment by Faithcaio** [comment] 2019-01-08 07:33
Iterable is gone from Inventories in API8.
Not sure what we can to for 7

**Comment by liach** [comment] 2019-01-08 13:15
@aaron1011 this actually reminds me of a more subtle issue: mods and sponge can add an generic interface to a class at the same time, but the generic parameters may be different. if railcraft specified iterator method in its minecart classes, sponge will break when plugins try to cast the iterator's output to sponge Inventory. The best resolution to prevent such cases is possibly to make mixin fail-fast, then.

**Comment by bookerthegeek** [comment] 2019-01-11 05:57
## Heyo
Same issue except it crashes during startup
- Railcraft | 12.0.0-beta-4
- SpongeForge | 1.12.2-2768-7.1.4
- Forge | 14.23.5.2807

### Crash
https://gist.github.com/bookerthegeek/a0fb38358a88a78ff9534d54ad6a4447

**Comment by liach** [comment] 2019-01-18 07:40
It turns out not to be very hard to change on railcraft's side. Given spongeapi 7 is frozen, https://github.com/Railcraft/Railcraft/pull/1663 might be the best choice available.

**Comment by liach** [comment] 2019-01-19 05:36
This can be closed now as it's fixed on Railcraft's side.

**Closed as completed** 2019-01-19 05:37 UTC
Labels: type: mod incompatibility, system: inventory, version: 1.12, resolution: fixed externally
