### ISSUE TITLE
sponge doesnt work with FTBUtilities-1.10.2-3.2.4

### ISSUE THREAD

**Issue by Sitherious** [SpongePowered/SpongeForge#1144] opened 2016-12-27 13:57 UTC
FTBserver-1.10.2-12.18.3.2185-universal
spongeforge-1.10.2-2171-5.1.0-BETA-2008
FTBUtilities-1.10.2-3.2.4

http://pastebin.com/5jCzEzK5

**Comment by Aaron1011** [comment] 2016-12-27 16:46
@zml2008: The cause of this issue is that this mod has an option to [re-register all commands](https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/java/com/feed_the_beast/ftbu/FTBU.java#L92) (including its own) for the purpose of adding permission support.

I'm not sure what the best way is to handle this - do we want to add an exception for mods, since this does work in plain Forge?

**Comment by Sitherious** [comment] 2016-12-27 16:48
works fine in forge, soon as i add sponge, sponge crashes and gives me that error

**Comment by Aaron1011** [comment] 2016-12-27 16:50
@Sitherious: Sorry, I should have been more clear - this is indeed caused by Sponge, but I'm unsure of how best to fix it.

**Comment by Sitherious** [comment] 2016-12-27 16:52
i have no clue, just reporting the issue :) hopefully you or someone else can solve this.

**Comment by Sitherious** [comment] 2016-12-27 23:34
its fixed, https://github.com/LatvianModder/FTBUtilities/issues/292

**Comment by Whazaaaaa** [comment] 2017-01-01 21:30
Hello! I'm having this issue aswell. Not sure if this is better solved on the FTBUtil side but seeing as modpacks dont get updated as much as SpongeForge I would really love to see a fix for this in sponge (if possible as soon as possible)
Skyfactory3 just came out and it is very depending on FTBUtilities to function properly. So if it were possible to fix this that would be great.

**Closed as completed** 2017-01-02 21:59 UTC
Labels: system: command, type: mod incompatibility

**Comment by Sitherious** [comment] 2017-01-03 11:21
works like a charm thanks :)

**Comment by Schuldakt** [comment] 2017-11-14 23:26
Any chance we could get a compiled version of this, i don't have Gradle or linux?

**Comment by phit** [comment] 2017-11-14 23:28
this was fixed months ago, so it's in all release versions since then!

**Comment by Schuldakt** [comment] 2017-11-15 00:06
well the issue is still occurring on my server

**Comment by phit** [comment] 2017-11-15 00:07
well then feel free to open a new issue with an updated log
