### ISSUE TITLE
McMultipart/Mekanism Sponge Bug

### ISSUE THREAD

**Issue by Fently** [SpongePowered/SpongeForge#1797] opened 2017-10-02 22:49 UTC
Strange issue directly caused by sponge when placing pipes in Mekanism. These two videos I recorded will project the problem easier than I cane explain in words: 

[Video1](https://youtu.be/cmZ3dPL2BcI) 
[Video2](https://youtu.be/Uk8igR_3m8I)

I tested with and without sponge, and the issue only occurs when sponge is installed. I am using Mekanism v9.3.5.206 in conjunction with McMultipart v2.0.2 + Chisel&Bits. In video example 2, the items in the logistical pipe also never leave the logistical pipe, this is not just a render bug and the items never appeared in the chest.

EDIT: Further trials prove that this issue is caused ONLY when McMultipart is activated. When disabled, the issue does not occur. Unfortunately, McMultipart is a dependency for some of my mods and cannot be permanently disabled

## Version Numbers
Minecraft Version: 1.11.2
Forge Version: 13.20.1.2429
SpongeForge Version: 2476-6.1.0-BETA-2652
Mekanism Version: 9.3.5.206
McMultipart Version: 2.0.2

**Comment by phit** [comment] 2017-12-02 23:30
can't reproduce with

MCMultiPart-2.3.3.jar
Mekanism-1.12.2-9.4.2.327.jar
MekanismGenerators-1.12.2-9.4.2.327.jar
MekanismTools-1.12.2-9.4.2.327.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2753.jar

**Comment by phit** [comment] 2018-01-01 15:48
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Closed as completed by phit** 2018-01-01 15:48 UTC
Labels: version: 1.11 (u)
