### ISSUE TITLE
Server crash from putting Twilight Forest Magic Map in item frame in over world

### ISSUE THREAD

**Issue by bluelightning32** [SpongePowered/SpongeForge#2630] opened 2019-03-02 10:45 UTC
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3596.jar
- Forge version: forge-1.12.2-14.23.5.2807-universal.jar
- Java version: openjdk version "1.8.0_201"
- Operating System: Fedora 29

- Plugins/Mods:
   + Plugins:
  ```
  [02:19:18] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (6): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, LuckPerms, spark
   ```
  + Mods: the ones that come with the DD-SS 4.5a modpack. Most notably twilightforest-1.12.2-3.8.689-universal.jar.

**Issue Description**
Placing a magic map from the twilight forest inside of an item frame in the overworld causes the server to crash. More specifically, these are the simplest repro steps:
1. Using creative mode, put a magic map and item frame in your inventory.
2. Switch to survival mode.
3. Place the item frame and the magic map inside the item frame.

This exception shows up in the crash report:
```
Time: 2019-03-01 11:19:22 PST
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
    at java.util.ArrayList$Itr.next(ArrayList.java:859)
    at net.minecraft.server.MinecraftServer.handler$onEndTick$bab000(MinecraftServer.java:4079)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:713)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

I've added log statements to narrow the problem down as much as possible. I think this is happening because the server is iterating through a list of loaded data for all the dimensions In 
[MixinMinecraftServer_MapOptimization](https://github.com/SpongePowered/SpongeCommon/blob/74573a2d0af6facdabfa58973edf1ad2eb181024/src/main/java/org/spongepowered/common/mixin/optimization/mapoptimization/MixinMinecraftServer_MapOptimization.java#L53), then when it tries to update the magic map, it loads up data for the twilight forest, which modifies the ArrayList that is being iterated.

I think the ArrayList is getting modified here:
```
java.lang.Thread.getStackTrace(Thread.java:1559)
net.minecraft.world.storage.MapStorage.handler$onSetData$zog000(SourceFile:1058)
net.minecraft.world.storage.MapStorage.func_75745_a(SourceFile)
net.minecraft.world.World.func_72823_a(World.java:3670)
net.minecraft.item.ItemMap.redirect$setOverworldMapData$zif000(ItemMap.java:588)
net.minecraft.item.ItemMap.func_77873_a(ItemMap.java:75)
net.minecraft.item.ItemMap.func_150911_c(ItemMap.java:403)
net.minecraft.world.storage.MapData.updatePlayersInWorld(MapData.java:754)
net.minecraft.world.storage.MapData.tickMap(MapData.java:699)
net.minecraft.server.MinecraftServer.handler$onEndTick$bab000(MinecraftServer.java:4087)
net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:713)
net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
java.lang.Thread.run(Thread.java:748)
```

I tried putting a map from The End inside an item frame in the overworld, but that didn't reproduce the problem. [Here](https://github.com/TeamTwilight/twilightforest/blob/d980bdb5fc5ff1af982103406b0df2c79f859861/src/main/java/twilightforest/item/ItemTFMagicMap.java)'s the magic map source code.

Crash report and debug.log:
https://gist.github.com/bluelightning32/d323786b2d35bfef0d28d14b3bcae6e6

**Comment by ImMorpheus** [comment] 2019-03-02 10:50
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2398

**Closed as completed by ImMorpheus** 2019-03-02 10:50 UTC
Labels: resolution: duplicate, version: 1.12
