### ISSUE TITLE
Sponge 5.2.0 & Pokecube Dupe

### ISSUE THREAD

**Issue by Snez0kRU** [SpongePowered/SpongeForge#1673] opened 2017-07-24 15:56 UTC
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar
- Forge version: forge-1.10.2-12.18.3.2281-universal.jar
- Java version: 1.8.0_131
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
    spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar
    Pokecube Core-4.31.0.jar
    Pokecube Mobs-2.10.0.jar
    Pokecube Revival-4.20.0.jar 
    pokecubeserverutils-1.4.0.jar
    thutcore-3.16.0.jar
    
**What is the expected result?**
Pokecube must go into PC, and didn't dupe in my hands. 
**What is the current result?**
Running this mod without sponge, all ok no dupe, running with sponge have 2 pokecubes, 1 in PC, another still in inventory

[logs.zip](https://github.com/SpongePowered/SpongeForge/files/1170370/logs.zip)

![2017-07-24_18 33 14](https://user-images.githubusercontent.com/30385407/28532083-6c94b530-70a1-11e7-8367-563ec0132c9c.png)
![2017-07-24_18 33 15](https://user-images.githubusercontent.com/30385407/28532084-6c958fb4-70a1-11e7-9295-dff3ce195a3d.png)
![2017-07-24_18 33 19](https://user-images.githubusercontent.com/30385407/28532085-6c97bdf2-70a1-11e7-93c6-a02812e2da73.png)

**Comment by Snez0kRU** [comment] 2017-07-24 23:25
Someone understands why this happens, or how to fix it, maybe just need to switch something in config, which blocking event sending from player inventory to chest?

I really do not want to go to a clean forge without sponge

**Comment by Thutmose** [comment] 2017-07-25 09:28
Pokecube sends to PC, but checking the ItemTossEvent, checking if it is a filled Pokecube (ie has correct nbt tag on it), and if so, sends to to PC, kills the entityItem, and cancels the event, with just forge, this has the intended behaviour of preventing the item from being dropped, yet still deleting it from inventory.

I suspect sponge is somehow cancelling the toss event, but still allowing it to be sent to mods, which is what is resulting in this dupe, or is taking the cancelled event to mean that the item shouldn't be removed from inventory.

**Comment by Snez0kRU** [comment] 2017-07-26 14:12
Anybody from sponge team. Can smbd fix this ? anyone ? Pls it's still open

**Comment by Zidane** [comment] 2017-07-26 16:13
@Thutmose 

Can you link where you're handling that event for us?

**Comment by Thutmose** [comment] 2017-07-26 19:35
here is where I handle the ItemTossEvent:

https://github.com/Thutmose/Pokecube/blob/1.10/Pokecube%20Core/src/main/java/pokecube/core/events/handlers/PCEventsHandler.java#L202-L215

PokecubeManager.isFilled just checks to see if the itemstack has NBT containing a pokemob, then InventoryPC.addPokecubeToPC adds it to the appropriate PC box if it does.

**Comment by gabizou** [comment] 2017-07-27 05:13
So, from what I'm following, you're still allowing the entity to be spawned (as dead and ignored), but then you're cancelling the event. To my understanding of the event and how it's being *used*, you're still accepting the item toss event, you're just cancelling the toss, which to Sponge, means that the item needs to be placed back into the inventory. I can understand why you'd want to set the entity to dead or to be removed (because it should be removed), but cancelling the event in this context doesn't make sense. I'll stand by Sponge's determining that the item should be put back into the inventory for the event cancellation.

**Comment by Thutmose** [comment] 2017-07-27 05:46
Here is what the Forge documentation says about this event:

![image](https://user-images.githubusercontent.com/2363472/28655978-3d758ce8-726d-11e7-99fc-e273bed7f589.png)

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/event/entity/item/ItemTossEvent.java#L26-L31

I was setting the item dead I think from an issue that was occuring in having the not-dead item around in 1.7.10 or 1.6.4, I can probably remove the setDead() call now.

**Comment by Zidane** [comment] 2017-07-27 13:54
I slept on this @Thutmose and I agree. We are incorrectly putting the stack back in the inventory on cancel.

Originally I imagine our thought process was people wanting to stop an ItemToss and preserve inventory but that is easily fixed by firing a Pre event on our end for our plugins. If not cancelled, it then goes into ItemTossEvent then into SpawnEntityEvent for the EntityItem (should ItemToss not be cancelled).

@gabizou we need to investigate getting such an event added to address this.

**Comment by Snez0kRU** [comment] 2017-07-27 13:56
@Zidane It would be great, comrades look forward to the update with impatience.

**Comment by bloodmc** [comment] 2017-07-27 16:56
@Snez0kRU Please confirm issue is fixed in latest SF.

**Comment by Snez0kRU** [comment] 2017-07-27 17:11
@bloodmc i didn't know what is SF, sorry. And on site didn't find new builds of sponge. Last 12 days ago

**Comment by gabizou** [comment] 2017-07-27 17:18
There is the latest SF [here](http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/1.10.2-2281-5.2.0-BETA-2482/spongeforge-1.10.2-2281-5.2.0-BETA-2482.jar).

**Comment by Snez0kRU** [comment] 2017-07-27 17:26
@bloodmc I'm tested this, and i confirm that issue is fixed in latest SF. Thanks a lot comrades

**Closed as completed** 2017-07-27 17:26 UTC
Labels: version: 1.10 (u)
