### ISSUE TITLE
[1.12.2] Server crashing frequently and what seems randomly. 

### ISSUE THREAD

**Issue by JakePost** [SpongePowered/SpongeForge#1855] opened 2017-11-15 23:48 UTC
**I am currently running...**

- SpongeForge version: 1.12.2-2529-7.0.0-BETA-2732
- Forge version: 14.23.0.2529
- Java version: V8.131
- Operating System: Windows Server 2012

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 

**Mods:**
Animania
BiblioCraft
Biomes O' Plenty
Chisel
CraftStudios API
Decocraft
FastAsyncWorldEdit
Hats
KleeSlabs
Mantle
Natura
NetherPortalFix
Pam'sHarvestCraft
WorldEdit
iChunUtil
ptrmodlelib

**Plugins:**
AdminShop
EconomyLite
GriefPrevention
Hello MMO (Custom)
Hey I Saved Your Stuff
InstantRespawn
LuckPerms
NPCs
Nucleus
Nucleus API
VoxelSniper

Server is crashing frequently and randomly, I've tried multiple things to recreate the crash but I can't.
At the end of the crash log it sites Natura and the different logs within Natura, but the server still crashes with it removed. 

https://pastebin.com/VASDir56

**Comment by phit** [comment] 2017-11-15 23:51
Raise [max-tick-time](https://minecraft.gamepedia.com/Server.properties#max-tick-time) in your `server.properties`, the server watchdog is killing the server when the server freezes a bit too long.

The crashlog will just spill out whatever the server was doing in that moment, as this is not a bug I'm closing this.

**Closed as completed by phit** 2017-11-15 23:51 UTC
Labels: type: support, version: 1.12

**Comment by JakePost** [comment] 2017-11-16 00:26
While that prevent the server from shutting down, it just endlessly spams console with https://pastebin.com/7iLJr0LR endlessly and times players out.

**Comment by phit** [comment] 2017-11-16 00:28
please open a new issue for that with a full server log

**Comment by smmmadden** [comment] 2017-11-16 03:04
I couldn't tell from the log provided what you are using for JVM Arguments with Java 8.  There are new arguments in Java 8 that replace some from Java 7.  I'd recommend visiting Oracle's site and see what's changed and what may work for you to stop thread dumps.  I've been managing app servers for a couple decades and it takes that long sometimes to get it right. :-)

Word of caution - throwing more physical memory to the JVM does not mean it will fix the problem.  Same goes with allocating CPU's - if you over allocate or under allocate you will have problems.  Here is what I use but keep in mind the number of users you have may be quite different than mine.

I start my servers up with a batch file (Windows) so the console remains open and can be monitored.
The important message here is proper garbage collection and getting your MetaspaceSize and MaxMetaspaceSize correct.  If you get a lot of Out of Heap Space, increase these gradually until no more heap dumps.  This metaspacesize is to handle all the classes that get loaded at startup.  The more plugins and mods you have, the higher the value will be.  Increment by 64m until you get the right setup.

java -Xmx4G -Xms2G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=30 -XX:+UseBiasedLocking  -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -jar D:\Minecraft-Worlds\spigot1.12.2.jar

Here is a good site to get into more specifics: http://blog.sokolenko.me/2014/11/javavm-options-production.html
