### ISSUE TITLE
Startup crash with Dynamic Surroundings

### ISSUE THREAD

**Issue by Blayyke** [SpongePowered/SpongeForge#2126] opened 2018-04-28 15:42 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3064
- Forge version: forge-1.12.2-14.23.3.2655-universal
- Java version: 1.8.0_171
- Operating System: Win10 64bit Home

- Plugins/Mods:
MODS: https://i.imgur.com/VxiuX88.png
Plugins: https://i.imgur.com/YTGAteu.png

**Issue Description**
Server crashed on startup with Dynamic Surroundings installed. Dev mentioned that it was probably a sponge issue, so am posting here. Previous issue: https://github.com/OreCruncher/DynamicSurroundings/issues/321#issuecomment-385130676

Crash log: https://hastebin.com/ofebirerum.md

**Comment by gabizou** [comment] 2018-04-28 22:44
This sounds like a world is not a legitimate world with a proper provider, [because this area is throwing the null pointer](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/world/MixinWorld.java#L116-L118).

The problem is I'm not sure whether @OreCruncher is doing anything special with this world, or whether the world is considered as handled by the "server" and through the `DimensionManager`. If it isn't, then I can add a sanity check to the world info and avoid the error, but if it is supposed to be handled by the server, then that's a separate issue from what I'm thinking this is.

**Comment by OreCruncher** [comment] 2018-04-28 22:55
I'm not doing anything special with the world.  All my code is trying to do is get a hold of the world info data when processing the Forge world load event.  And I agree - it is strange there is no world info object.

**Comment by gabizou** [comment] 2018-04-28 23:02
@Blayyke do you have a full log? There already seems to be some debugging information that should've been printed to that log before the crash.

**Comment by Blayyke** [comment] 2018-04-28 23:06
[crash-2018-04-28_10.42.27-server.txt](https://github.com/SpongePowered/SpongeForge/files/1958265/crash-2018-04-28_10.42.27-server.txt)
This is the entire crash log. Edit: Misread what you asked.

**Comment by gabizou** [comment] 2018-04-28 23:21
No, I need the full server log, the crashlog only contains the crash, but there should be some more errors printed to the log before the crash.

**Comment by Blayyke** [comment] 2018-04-29 00:01
No longer have the log. Re-added it and going to see if it happens again, will report back if it does.

**Comment by phit** [comment] 2018-05-21 03:31
@Blayyke ever happened again?

**Comment by phit** [comment] 2018-06-07 01:37
closing, reply if it pops up again

**Closed as completed by phit** 2018-06-07 01:37 UTC
Labels: type: mod incompatibility, version: 1.12
