### ISSUE TITLE
Mod Teleport Problem with Sponge

### ISSUE THREAD

**Issue by sandtechnology** [SpongePowered/SpongeForge#2235] opened 2018-06-18 03:08 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3171
- Forge version: 2705
- Java version: 1.8.0_172
- Operating System: Windows Server 2018

- Plugins/Mods:

Plugins (9): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, FlexibleLogin, LuckPerms, Prism, UWhitelist

Mods (23): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, CraftTweaker JEI Support, CraftTweaker2, Cyclic, FoamFix, FoamFixCore, Guide-API, Inventory Tweaks, Iron Chest, JourneyMap, Just Enough Items, MrCrayfish's Furniture Mod, NoMoreRecipeConflict, Pam's HarvestCraft, Pixel Extras, Pixelmon, Waila, What Are We Looking At

**Issue Description**
When I use Ender Book of Cyclic(https://minecraft.curseforge.com/projects/cyclic/files/2544035) teleport to chunk-no-load chunk,I was kicked by an error "A fatal error has occurred, this connection is terminated".

Log:https://gist.github.com/sandtechnology/75c0c40a4bc0301223b203f403608499

**Comment by ryantheleach** [comment] 2018-06-18 03:30
Duplicate of Cyclics issue: https://github.com/PrinceOfAmber/Cyclic/issues/756 https://github.com/PrinceOfAmber/Cyclic/issues/795

This looks like the CSM being unable to know what caused the teleport.

This is due to Cyclic using the GUI thread hooks, to schedule a chunk load, then using a callback on chunk load in order to teleport the player.

Seems pretty straight forward from their end, wanting to load the chunk first.

But I'm not 100% sure of their code..

https://github.com/PrinceOfAmber/Cyclic/blob/c7edb436d41868a015254d219c8909c45e5be6ea/src/main/java/com/lothrazar/cyclicmagic/item/enderbook/ItemEnderBook.java#L145

**Comment by phit** [comment] 2018-06-18 11:14
literally calling teleport from their packet handler, mod bug 
https://github.com/PrinceOfAmber/Cyclic/blob/6c8a7a51e2204f8879a35a4e3158665f3e5772ba/src/main/java/com/lothrazar/cyclicmagic/item/enderbook/PacketWarpButton.java#L60

report it to the mod author

**Closed as completed by phit** 2018-06-18 11:14 UTC
Labels: version: 1.12, type: mod bug
