### ISSUE TITLE
[1.10.2] 2 crashes with logs

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#1644] opened 2017-07-13 18:33 UTC
Forge Mod Loader version 12.18.3.2316
spongeforge-1.10.2-2281-5.2.0-BETA-2456
Mods: CustomNpcs, Mo'Creatures, CustomMobSpawner, LotsOfFood
Plugins: WorldEdit, RedProtect, Nucleus, ProjectWorlds, ProjectPortals, Twentyticks, LuckPerms, Holograms

1) Crash: https://hastebin.com/alacepewuc.php
Log: https://hastebin.com/dokewiboxo.md

2) Crash: https://hastebin.com/eyutiwosul.php
Log: no log, crash 1 min after restart

**Comment by dualspiral** [comment] 2017-07-13 19:26
Duplicate of #1632

**Closed as completed by dualspiral** 2017-07-13 19:26 UTC
Labels: resolution: duplicate
