### ISSUE TITLE
Improve startup times?

### ISSUE THREAD

**Issue by kmecpp** [SpongePowered/SpongeForge#2471] opened 2018-10-09 16:10 UTC
**I am currently running**
- SpongeForge version: 2705-7.1.0-BETA-3361
- Forge version: 1.12.2-14.23.5.2768
- Java version: 1.8.0_181
- Operating System: Windows 10
- Plugins/Mods: None

**Issue Description**

Startup time with just Forge: ~8.5 seconds
Startup time with just SpongeForge: ~34 seconds

Startup for 31 mods without Sponge: ~26 seconds
Startup for 31 mods with Sponge: ~61 seconds

Could you please try and find ways to improve startup time with sponge? It is crucial for server owners to be able to restart their servers quickly so that they can test fixes and minimize downtime for players when the server is being modified. Currently the difference is extremely noticeable and probably could be improved upon significantly. I also tested this with 1.12.2-2705-8.0.0-BETA-3474 and the times are basically the same

**Comment by phit** [comment] 2018-10-09 16:20
disable the timings module and try again https://github.com/SpongePowered/SpongeForge/issues/2074

**Comment by kmecpp** [comment] 2018-10-09 16:41
That completely fixed the issue, thank you.

Startup doesn't really change at all between normal server restarts so if someone does want the startup timings its probably enough to just export it to a file once after they run a command specifying they want timings for the next restart. Running it more than once seems like overkill, running it without it being explicitly asked for is more overkill, and running it by default on every startup is extreme overkill.

**Suggestion:** Don't have timings enabled by default

Other suggestions:
- Have a "/sponge timings testStartup" command that does and saves timings for the next restart only
- Separate regular timings from startup timings

**Comment by gabizou** [comment] 2018-10-09 16:46
Duplicate of #2074.

**Closed as completed by gabizou** 2018-10-09 16:46 UTC
Labels: type: performance, version: 1.12
