### ISSUE TITLE
Crash, villager has no careers, entity.DeathPhase

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1786] opened 2017-09-28 01:13 UTC
When loading/saving a chunk with this specific villager, the server crashes. (Or when he is attacked by a Zombie?)
Also an error occurs when trying to kill the villager

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2637
- Forge version: 1.10.2-12.18.3.2422
- Java version: OpenJDK for some reason, but shouldn't matter anyway in this case.
- Operating System: Debian 9.1

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
FTB Beyond 1.11

**What is the current result?**
Server crashes if this villager is loaded
Crashlog:
https://pastebin.com/7kTjQAmz
Full log:
https://pastebin.com/J27iZsiA
error when trying to kill him via command
https://pastebin.com/TCuP1STC

If you need more details let me know. But this should be enough

**Comment by phit** [comment] 2017-11-21 00:55
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1467

**Closed as completed by phit** 2017-11-21 00:55 UTC
Labels: resolution: duplicate, version: 1.10 (u)
