### ISSUE TITLE
[1.12.2] Rcon is broken

### ISSUE THREAD

**Issue by mblob** [SpongePowered/SpongeForge#1862] opened 2017-11-18 21:18 UTC
**I am currently running...**

- SpongeForge version: 1.12.2-2529-7.0.0-BETA-2732
- Forge version: 1.12.2-14.23.0.2529
- Java version: 1.8.0_152-b16
- Operating System: 

 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Llamagistics, Applied Llamagistics Core, AutoRegLib, BD Lib, BiblioCraft, Biomes O' Plenty, Chameleon, Chest Transporter, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Corail Recycleur, Forestry, Immersive Engineering, Inventory Tweaks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, Mantle, NHAVE's Core, Pressure Pipes, Psi, RFTools, RFTools Control, Redstone Flux, Storage Drawer
s, Storage Drawers Extras, TESLA, TOP Addons, The One Probe, The One Wrench, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, WorldEdit, XNet, mercurius_updater

**What is the expected result?**
To be able to issue commands through rcon. I'am using mcrcon or rcon_shell.

**What is the current result?**
Nothing except errors "Exception whilst parsing RCON input".
Taking out sponge resolve the issue.

[latest.log](https://gist.github.com/mblob/5ba82ee8fa9df486546ecdd42a8e115e)

**Comment by phit** [comment] 2017-11-18 21:20
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1533, will be fixed by https://github.com/SpongePowered/SpongeCommon/pull/1526

**Closed as completed by phit** 2017-11-18 21:20 UTC
Labels: resolution: duplicate, system: phase tracker, version: 1.12
