### ISSUE TITLE
ItemExpireEvent is throwing SpawnEntityEvent

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeForge#421] opened 2015-11-20 09:49 UTC
I'm not sure why, but I'm finding `ItemExpireEvent` being thrown for an event listener of `SpawnEntityEvent`, and that the `Cause` is empty. I'm not 100% sure whether this was intended.

**Comment by bloodmc** [comment] 2015-11-20 19:59
@gabizou ItemExpireEvent isn't even implemented yet.

**Comment by gabizou** [comment] 2015-11-21 02:09
I'm getting the event instance from forge as SpawnEntityEvent with an empty cause.

**Comment by simon816** [comment] 2015-11-21 02:25
I'm pretty sure this is because of `MixinEventDropItem` which is why I changed the interface in https://github.com/SpongePowered/SpongeForge/commit/1e82dcb3962040b8f69588ce833919c43bbb40a3#diff-7c39fe1f732d4f66909c05582e2b6c0cR53 but blood said it needed to be how it was for a reason https://github.com/SpongePowered/SpongeForge/commit/3a71fbff72a670a857e2ddd740d30aa021791982#diff-7c39fe1f732d4f66909c05582e2b6c0cR52

**Comment by simon816** [comment] 2015-11-23 17:46
```java
@Listener
public void onDropEventCustom(DropItemEvent.Custom event) {
    System.out.println(event);
}
```
prints 
`net.minecraftforge.event.entity.item.ItemExpireEvent@a6155a5`

This is due to the event hierarchy caused by `MixinEventDropItem` essentially making all Forge `ItemEvent`s implement `DropItemEvent.Custom`

@bloodmc You told me it had to be like this but I still don't see it

**Comment by bloodmc** [comment] 2015-11-23 21:11
@simon816 Yes you are correct, please push a fix.

**Comment by simon816** [comment] 2015-11-24 18:34
Fixed by https://github.com/SpongePowered/SpongeForge/commit/2854007d5b19d78b24155950ef7b512c4d5c9a69

**Closed by simon816** 2015-11-24 18:34 UTC
