### ISSUE TITLE
Server crash -Position is out of bounds: expected in range

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#2071] opened 2018-03-29 14:51 UTC
**I am currently running**
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-06016f2
SpongeForge: 1.12.2-2611-7.1.0-BETA-2990
Minecraft Forge: 14.23.2.2628
Java version: openjdk version "1.8.0_161"
Operating System: Centos 7 minimal install

- Plugins/Mods:
Plugins/Mods:
Plugins (21): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BetterChunkLoader, EconomyLite, GriefPrevention, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, Nations, Nucleus, PayDay, PwnFilter Sponge Plugin, Rankup, ServerListPlus, SleepVote, StatusProtocol, Tab Modifier, WorldEdit
Mods (164): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AI Improvements, Applied Energistics 2, Astikoor, Backpacks!, Bad Wither No Cookie! Reloaded, Bailey's Dailies, Baubles, Bed Bugs, Better Animals Mod, Better Builder's Wands, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bookshelf, Car Mod, Cavern II, Ceramics, Chameleon, ChinjufuMod, Chisel, Chisels & Bits, Chococraft 3, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Cooking for Blockheads, Corail Pillar, Corail Pillar - Biomes O'Plenty Extension, Corail Pillar - Chisel Extension, Corail Pillar - Forestry Extension, Corail Tombstone, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Dark Roleplay Core, Dark Roleplay Medieval, Decocraft, DeepResonance, Default World Generator, Diet Hopper, Display, Dooglamoo Cities, Edible Bugs Mod, ElecCore, Elevator Mod, EnderTanks, EqualDragons, Extra Bit Manipulation, Farming for Blockheads, Farseek, Fast Leaf Decay, FoamFix, FoamFixCore, Forestry, Futurepack, Futurepack API, Futurepack Forestry Addon, Hydrophobia, Immersive Engineering, Immersive Petroleum, Immersive Railroading, Immersive Tech, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, Inventory Tweaks, JEI Bees, Just Enough Items, LLibrary, Landlust, Lapis Stays in the Enchanting Table, Laser Level, LibrarianLib, LibrarianLib Stage 2, Long Fall Boots, LunatriusCore, MTLib, MagicBees, Mantle, McJtyLib, Mekanism, MekanismTools, MineColonies, MineTweakerRecipeMaker, Minecraft Transport Simulator, Mod Tweaker, MrCrayfish's Furniture Mod, MrCrayfish's Jumping Castle Mod, Multi-Beds, Multi-Storage, Natura, Nature's Compass, No FOV, NoNausea, NotEnoughIDs, OC Glasses, Open Glider, OpenComputers, OpenComputers (Core), OpenComputers Sensors, OpenEye, Placebo, Platforms, Prefab, Pumpkin Carving, RC Roads, RF Lux, RandomPatches, Reborn Core, Redstone Flux, Rocky Core, Rope Bridge, Sampling Performance Profiler, Shadowfacts' Forgelin, ShetiPhian-Core, Standard Expansion, Steve's Carts 2, Storage Drawers, Streams, Super Sound Muffler, TESLA, TOP Addons, Tech Reborn, Techguns, Techguns Core, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, ToroChess, Track API, Unloader, Waddles, Wearables, What Are We Looking At, Wizardry, World Drop, Xtones, Zetta Industries, careerbees, mxTune, p455w0rd's Library, ptrmodellib, �9RuneCraft

https://minecraft.curseforge.com/projects/towncraft

**Issue Description**

server crash while pregenning a fresh world using chunk pregenerator
https://paste.fedoraproject.org/paste/orrWQrAHt6F20B8gQqqdgQ

[2018-03-29-1.log.gz](https://github.com/SpongePowered/SpongeForge/files/1860602/2018-03-29-1.log.gz)
https://gist.github.com/ProsperCraft/8c4a2c5ad67043b8d1f11a90572d1c03

**Comment by elementalistic** [comment] 2018-03-30 09:33
I've just had the same type of biome gen error.  This is a Void World for Modern Skyblock 3, generated using Void Island Control's "voidworld" gen type.

> Position is out of bounds: expected in range (1600, 0, 1104) to (1615, 0, 1119) but got (1568, 0, 1088)

I am currently running
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-06016f2 
SpongeForge: 1.12.2-2611-7.1.0-BETA-2970
Minecraft Forge: 14.23.2.2611
Java Version: 1.8.0_161, Oracle Corporation
Operating System: Windows Server 2012 R2 (amd64) version 6.3
Modern Skyblock 3 Departed: 3.1.5.3 

https://gist.github.com/elementalistic/f8bdf9b741ec96a67b182e007fcbb4ec

**Comment by Zidane** [comment] 2018-03-31 15:33
The errors are clear, the pregenerator is literally causing it to generate biomes out of the range you are supposed to generate biomes at. Using the pregenerator from Nucleus, I have never seen that problem (as it uses the one we ship inside Sponge).

**Comment by elementalistic** [comment] 2018-04-01 07:30
I don't understand world gen code, I've not had to play with it, but looking at the source for the worldtype, it's using the minecraft default biome generator.  The worldBiomeID is set as -1 in the config.

https://github.com/Bartz24/VoidIslandControl/blob/16493e320a623b77888551d6acc057374fbbc70d/src/main/java/com/bartz24/voidislandcontrol/world/WorldTypeVoid.java#L47

This was from a new player starting an island (controlled/spawned by skyclaims) and it generating the new chunks.  

Skyclaims uses a Sponge schematic to then spawn in the island.

**Comment by ProsperCraft** [comment] 2018-04-27 22:09
Server crashes when not pre-generating chunks, just under normal play.

https://gist.github.com/ProsperCraft/61218e45c344b73fc0829b0684a86583

https://gist.github.com/ProsperCraft/fc6bb719304eb85784c9de48a8ac3a01

**Comment by phit** [comment] 2018-05-06 15:29
Just had another user report a crash with this on Discord, again with a different mod and also without using a pregenerator..

https://pastebin.com/K4mihyix

**Comment by ryantheleach** [comment] 2018-07-27 10:23
It's pretty clear that this is mods violating our assumptions for our world generation system.

My question is can we instead log a warning, and prevent the crash, and compare the results to generation without SpongeForge?

Would Vanilla instead redirect and load chunks at this point, or would it silently drop the changes?

If it's literally just a performance reason / different world gen architecture, Is it possible for us to adopt Vanilla / Forge behavior here, maybe with a warning?

**Comment by Zidane** [comment] 2019-06-21 23:21
Can someone re-test this on latest SF and see if it is still a problem?

**Comment by Zidane** [comment] 2019-08-04 19:28
Closing until someone reports back that this is still a problem (I cannot reproduce myself) and gives up steps how.

**Closed as completed by Zidane** 2019-08-04 19:28 UTC
Labels: version: 1.12, system: world gen
