### ISSUE TITLE
Animal Nets from Hatchery do not function properly with SpongeForge

### ISSUE THREAD

**Issue by bookerthegeek** [SpongePowered/SpongeForge#1168] opened 2017-01-07 11:50 UTC
https://github.com/GenDeathrow/Hatchery/issues/23
Versions:
* Sponge: spongeforge-1.10.2-2202-5.1.0-BETA-2019.jar
* Forge: forge-1.10.2-12.18.3.2185-universal.jar
* ModVersion: hatchery-1.10.2-0.2.1.jar

What Happens:
- Item is not changing on use

What is Expected to happen:
- Item changes on use

Overview of Issue:
- When right clicking an Animal Net (Mod added item to hold a mod added chicken that lays resources such as Iron instead of eggs) that has a Chicken (From said mod) in it, it will spawn the chicken in the world, but not remove it from the net. It is suppose to remove it from the net.
- Right clicking on a Pen (A block added by the mod) with an empty net will void a Chicken from the Pen, but not add it to the net as it is suppose to.

More information:
- Reproducible on a Sky Factory 3 Server running Sponge where issue was discovered.
- Reproducible on a Sky Factory 3 Single Player instance running Sponge.
- Reproducible on a Single Player instance running Sponge and Mod only.
- Not reproducible on Sky Factory 3 server running only Forge
- Not reproducible on Single Player instance running Forge and Mod only.

**Comment by GenDeathrow** [comment] 2017-01-09 08:41
Thanks for posting this.

**Comment by phit** [comment] 2017-01-24 17:42
the mod dev marked this a wontfix and blames sponge, so it would be nice if this could be looked at by the sponge team

**Comment by Aaron1011** [comment] 2017-01-24 18:54
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/4648e4af32f68b07690df05d5446a5b74b99f2b2. The latest SpongeForge will contain this fix.

**Closed as completed by Aaron1011** 2017-01-24 18:54 UTC
Labels: type: bug, type: mod incompatibility

**Comment by rob5251** [comment] 2018-02-01 01:37
Issue seems to be occurring on the latest spongeforge releases again.

**Comment by ryantheleach** [comment] 2018-02-01 02:49
@rob5251 What version numbers have you tested, Can you open a new ticket with reproduction steps? Was this newly introduced, or has it happened on every 1.12 release you have tried?

**Comment by rob5251** [comment] 2018-02-02 00:26
@ryantheleach I opened a new ticket here:
https://github.com/SpongePowered/SpongeForge/issues/1982

I only recently added Hatchery to my modpack so I can't comment on what version it started to occur again. Further testing will need to be done at this point.
