### ISSUE TITLE
Unlimited use of food in a bowl. 

### ISSUE THREAD

**Issue by jinkhya** [SpongePowered/SpongeForge#2437] opened 2018-09-08 17:58 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3440.jar
- Forge version: 2707
- Java version: 1.8.0_121-b13
- Operating System: Centos 7.3.1611

- Plugins/Mods:
Sevtech v. 3.0.8
Minecraft, Minecraft Coder Pack, spongeAPI, SpongeForge, AdamantineShield, Catclearlag, Enjin Minecraft Plugin, GriefPrevention, Luckperms, MMCRestrict, Nucleus, Prism

When you eat some kind of soup that returns an empty bowl, after eating it if you open your inventory, start drag and dropping the empty bowl like you would want to move the empty bowl to another slot then it just reappears as full again like it was never eaten. 
I've noticed the issue on Meef Stroganoff (Twilight forest), Chicken Soup (Better with Mods), Beetroot Soup(Minecraft). It seems to do it as long as you're getting an empty bowl.

**Comment by phit** [comment] 2018-09-26 05:46
I can't reproduce this using spongeforge-1.12.2-2705-7.1.0-BETA-3460

Closing this for now. If this is still an issue for you, please let us know and provide relevant new info, like which mods exactly are required to reproduce this. Testing with a huge modpack is not really an option.

**Closed as completed by phit** 2018-09-26 05:46 UTC
Labels: version: 1.12
