### ISSUE TITLE
NuclearCraft (and other mods possibly) Incompatibility

### ISSUE THREAD

**Issue by xElementzx** [SpongePowered/SpongeForge#2710] opened 2019-04-24 22:45 UTC
**I am currently running**
- SpongeForge version:  1.12.2-2768-7.1.6-RC3671
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212 | 1.8.0_201
- Operating System: Windows 10 1809 Build 17763.437 | Ubuntu 18.04 LTS

- Plugins/Mods: NuclearCraft-2.15-1.12.2, Nucleus-1.9.2-S7.1-MC1.12.2, RedstoneFlux-1.12-2.1.0.6

**Issue Description** Using an Alloy Furnace from NuclearCraft or the Manufactory from NuclearCraft, put materials inside to perform an action, when the furnace starts its action for smelting the items in the inventory are thrown on the ground and the furnace GUI remains open appearing like its smelting but nothing happens. it appears that the GUI is being closed server side but simply remaining open on the client. Issue was found on a SkyFactory 4 and tested locally.

Expected Behavior is that the items remain in the GUI until the job completes and then items get moved to the output.

Possible Related Issue: https://github.com/SpongePowered/SpongeForge/issues/2702
When running SpongeForge 3670 the issue is not present.

**Server Log**
https://gist.github.com/e8d85ab67c33a2e70188c1fe1e8a64c8

**Comment by Yorkforce** [comment] 2019-04-26 17:42
Since 3679 the items are still being spat out but now it also performs the action in the furnace/manufactory effectively duping anything you put inside.

So its gone from a minor issue and become a major dupe issue.

**Comment by gabizou** [comment] 2019-04-27 14:11
Re-test with 3679.

**Comment by xElementzx** [comment] 2019-04-27 23:05
It works fine in a test environment with only nuclearcraft, however putting it into a SkyFactory 4 install produces https://github.com/SpongePowered/SpongeForge/issues/2716 all items are being thrown on the ground, as soon as the crafting job is complete, the output is thrown onto the ground

**Comment by selkiess** [comment] 2019-04-28 06:21
I can confirm that this issue persists with 3680

**Comment by phit** [comment] 2019-04-30 17:23
closing in favor of https://github.com/SpongePowered/SpongeForge/issues/2725 we don't 4 issues on the same thing, becomes messy

**Closed as completed by phit** 2019-04-30 17:23 UTC
Labels: version: 1.12, status: waiting for reply
