### ISSUE TITLE
Bad entity performance

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/SpongeForge#3167] opened 2020-05-31 12:39 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.2-RC4030
- Forge version: forge-1.12.2-14.23.5.2847
- Java version: 1.8.0_211
- Operating System: Ubuntu 19.04

- Plugins/Mods:
Mods (105): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Antique Atlas, Aquaculture, Astral Sorcery, Atum 2, AutoRegLib, Bad Wither No Cookie! Reloaded, Baubles, Better Questing, Bewitchment, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Botania Needs These Things!, Botanic Additions, Cases, Cathedral, Chameleon, ChickenChunks, ChineseWorkshop, Chisel, Chisels & Bits, Chunk Pregenerator, CodeChicken Lib, ContainerFix, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, DivineRPG, DupeFix Project, Dynamic View Mod, Electroblob's Wizardry, Embers Rekindled, EventHelper, ExtraBotany, FoamFix, FoamFixCore, GamePoint Mod, GamePoint Mod, Grand Economy, Grand Economy Currency Provider, Guide-API, Hammer Core, Iron Chest, Just Enough Items, MTLib, Macaw's Bridges, Macaw's Roofs, Macaw's Windows, Mantle, Mod Tweaker, Mystical Lib, NoMoreRecipeConflict, NotEnoughIDs, OpenBackup, OpenFM, Oxygen Core, Oxygen: Exchange, Oxygen: Friends List, Oxygen: Groups, Oxygen: Mail, Oxygen: Merchants, Oxygen: Shop, Oxygen: Trade, Pam's HarvestCraft, Patchouli, Pewter, Phosphor Lighting Engine, Placebo, PlusTiC, Quark, Quick Leaf Decay, RandomPatches, Shadowfacts' Forgelin, Some Like It Dry, SpongeForge, Standard Expansion, Storage Drawers, Surge, TOP Addons, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Augmentation, Thaumic Periphery, The One Probe, The Twilight Forest, Tinkers Tool Leveling, Tinkers' Construct, Totemic, Trample Stopper, VanillaFix, Varied Commodities, YUNG's Better Caves, gpaddons, gpvetheafix, performant Mod, personalize

**Issue Description**
Server on sponge shows very poor entity performance.
https://spark.lucko.me/#OLRtDHBjfU

There are only about 800-1600 entities on my server and I get loads of up to 5 tps..
This is considering the fact that I lowered the monsters tick rate, installed a lot of mods for optimization, but still my server lags

![image](https://user-images.githubusercontent.com/17977139/83352650-b73d0a80-a355-11ea-843a-994dbbb31874.png)

global.conf
```
# Used to control spawn limits around players. 
    # Note: The radius uses the lower value of mob spawn range and server's view distance.
    spawner {
        # The number of ambients the spawner can potentially spawn around a player.
        spawn-limit-ambient=6
        # The number of animals the spawner can potentially spawn around a player.
        spawn-limit-animal=5
        # The number of aquatics the spawner can potentially spawn around a player.
        spawn-limit-aquatic=3
        # The number of monsters the spawner can potentially spawn around a player.
        spawn-limit-monster=20
        # The ambient spawning tick rate. Default: 400
        tick-rate-ambient=400
        # The animal spawning tick rate. Default: 400
        tick-rate-animal=400
        # The aquatic spawning tick rate. Default: 1
        tick-rate-aquatic=400
        # The monster spawning tick rate. Default: 1
        tick-rate-monster=4
    }
```

view-distance=4

**Comment by ImMorpheus** [comment] 2020-05-31 13:22
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/3085 https://github.com/SpongePowered/SpongeCommon/issues/2602

there's not much that sponge is doing to cause or add on to lag

**Closed as completed by ImMorpheus** 2020-05-31 13:22 UTC
Labels: resolution: duplicate, type: support

**Comment by bigenergy** [comment] 2020-06-03 23:16
@ImMorpheus okay, it's normal?
![image](https://user-images.githubusercontent.com/17977139/83698129-52a9d600-a609-11ea-8787-f0e55a828214.png)

**Comment by gabizou** [comment] 2020-06-10 05:43
Dude, stop opening new issues, an issue can still be discussed until it is locked. Just because it's closed doesn't mean that you can't keep replying there.
