### ISSUE TITLE
TP / Home error

### ISSUE THREAD

**Issue by RainOfPain125** [SpongePowered/SpongeForge#2566] opened 2019-01-21 03:32 UTC
**I am currently running**

- SpongeForge version: SpongeAPI: 7.1.0-70763aa8
    Sponge: 1.12.2-7.1.4
    SpongeForge: 1.12.2-2768-7.1.4
- Forge version: 14.23.5.2768
- Java version: 1.8.191
- Operating System: Windows 10 2016 Server

- Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, Boop, LuckPerms, Nucleus, WorldEdit

(All The Mods 3 Modpack) Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, ATM Tweaks, AbyssalCraft, AbyssalCraft Integration, Actually Additions, Actually Baubles, Additional Banners, Advanced Generators, Advanced Rocketry, Advanced Rocketry Core, Akashic Tome, AngelRing 2 Bauble, AppleCore, AppleSkin, Applied Energistics 2, Armory Expansion, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Debug, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Ceramics, Chameleon, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Colossal Chests, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, ComputerCraft, Computronics, Construct's Armory, Cooking for Blockheads, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Cyclic, Cyclops Core, Dark Utilities, Default World Generator, Diet Hopper, Dismantler, Doomlike Dungeons, Draconic Evolution, EXCore, EluCore, EluLib, Embers, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Exchangers, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Fairy Lights, FastWorkbench, Fence Jumper, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Funky Locomotion, GenDustry, Guide-API, HelpFixer, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Generators, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, JEI Bees, JMFixer, JourneyMap, Just A Ore Processing Compatibility Attempt: Additions, Just Enough Dimensions, Just Enough Items, KJ Lib, KleeSlabs, LibrarianLib, LibrarianLib Stage 2, Lost Souls, MCMultiPart, MTLib, MagicBees, Magical Psi, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, MineColonies, Minecraft Multipart Plugin, Mob Totems, Mod Tweaker, Morph-o-Tool, Morpheus, MrTJPCore, Mystical Agradditions, Mystical Agriculture, Natura, Nature's Compass, No Mob Spawning on Trees, Not Enough Wands, NotEnoughIDs, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OpenModsLib, OpenModsLib Core, OreDictInit, OreExcavation, OreExcavation Integration, Overloaded, PackCrashInfo, PackMode, Pam's Cookables, Pam's HarvestCraft, Pink Flamingo, Placebo, Plants, Platforms, PlusTiC, PneumaticCraft: Repressurized, PortalGun, Portality, Practical Logistics 2, Pressure Pipes, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Psi, QuantumStorage, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RandomPatches, Ranged Pumps, Real Filing Cabinet, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Reliquary, Roots 2, Rustic, Sampling Performance Profiler, ShadowMC, Shadowfacts' Forgelin, ShetiPhian-Core, Shield Parrying, Simply Jetpacks 2, SlimyBoyos, SonarCore, Soul Shards - The Old Ways, SpongeForge, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tech Reborn, Terraqueous, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The Betweenlands, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, Tomb Many Graves, TombManyGraves2 API, Traverse, UniDict, Universal Modifiers, Unloader, Useful Nullifiers, Valkyrie Lib, Vulpes library, WAIM, WanionLib, Water Strainer, Waystones, Wireless Crafting Terminal 2, WirelessCharger, Wizardry, Wooden Shears, Woot, World Utils, WrapUp, XNet, Xtones, YNot, Zero CORE, asielib, careerbees, iChunUtil, p455w0rd's Library, projectred-compat

**Issue Description**
When we /home, we get an error in chat that says "Unexpected error, Intended to track block entity spawns. Please analyze the current phase" so on. Then I'm moved around to a broken somewhat un-chunk loaded area of the dimension I was in (the end). I was trying to teleport from the End to the Overworld when this happened. I tried to /tp and /home to the overworld and neither worked.

<!-- Please provide a *full* server log (and crash-report if applicable).
The error - https://pastebin.com/CNaNvmer sorry, had to use pastebin
The entire log is way too big. So I attached it.
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2777473/latest.log)

**Comment by phit** [comment] 2019-01-21 07:07
please add your debug.log to the issue

**Comment by dualspiral** [comment] 2019-01-21 08:07
https://github.com/NucleusPowered/Nucleus/issues/1310 has some info, but the full log as indicated would be helpful too.

**Comment by phit** [comment] 2019-01-21 14:05
ah, duplicate of https://github.com/SpongePowered/SpongeForge/issues/2355

**Closed as completed by phit** 2019-01-21 14:05 UTC
Labels: resolution: duplicate, version: 1.12
